### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#1]
- [x] Implement chrome.i18n API https://developer.chrome.com/extensions/i18n
- [x] Find contributors to translate extension into various languages.

For those interested in helping translate new languages, I have posted on contributing guidelines for this here: https://github.com/bitwarden/browser/blob/master/CONTRIBUTING.md

**Comment by Igetin** [comment]
Will gladly help with the Finnish translation when the resource string system has been implemented.

**Comment by bcallaars** [comment]
Will gladly help with the Dutch translation!

**Comment by ArtemNikolaev** [comment]
Hi guys, can you code review my pull request about adding i18n to this extension. Thanks!

**Comment by kspearrin** [comment]
@ArtemNikolaev Thanks for the week. I left some feedback for you on the PR.

**Comment by ArtemNikolaev** [comment]
@kspearrin , yes, i forget to add new files to git. Now its gonna work fine.

**Comment by ArtemNikolaev** [comment]
@bcallaars, @Igetin changes merged in master, you can do translations now.

**Comment by kspearrin** [comment]
@ArtemNikolaev Thanks for the help! Looks great.

**Comment by sersoftin** [comment]
I can to help with Russian translation.

**Comment by Igetin** [comment]
A question about semantics: when the word "free" is used in the English locale's strings, is it supposed to mean free as in free beer, or free as in free speech?

**Comment by kspearrin** [comment]
Free beer

**Comment by Igetin** [comment]
Thank you. I have now created a pull request (https://github.com/bitwarden/browser/pull/32/commits/430c73041d94ea721fa7e8262187b5a57b458704) for the Finnish translation.

**Comment by kspearrin** [comment]
We have resolved this task with Crowdin. https://github.com/bitwarden/browser/blob/master/CONTRIBUTING.md#localization-l10n
