### ISSUE TITLE
Bitwarden failed fetch login or any request

### ISSUE THREAD

**Issue by JonathanAJ** [bitwarden/browser#1000]
Hi, i'm with a problem wicht I can't login into my account.

Follow pictures of developer debug mode:

![bit1](https://user-images.githubusercontent.com/12076722/64178256-83b96800-ce37-11e9-8b4f-9ecad3d984ca.png)

![bit2](https://user-images.githubusercontent.com/12076722/64178267-8ae07600-ce37-11e9-990b-9bd3ba5e8362.png)

Someone help in this case? I debugged using the Postman, but the url **https://api.bitwarden.com/accounts/prelogin** send me an 404 error not found.

**Yes, I disabled the AdBlocker and I'm using Opera Browser.**

Thanks.

**Comment by kspearrin** [comment]
Does it work with another browser or is this specific to Opera and it's ad blocker?

**Comment by JonathanAJ** [comment]
Yes, in Google Chrome is fine. I'm using the same extension from Chrome in Opera.

**Comment by kspearrin** [comment]
Sounds like a bug with Opera's ad blocked stopping legitimate traffic.

**Comment by JonathanAJ** [comment]
Yes, you're correct. I disabled the default Opera AdBlocker, and the request work after this.

**Comment by kspearrin** [comment]
You might want to report this to Opera.

**Comment by JonathanAJ** [comment]
Ok, thanks! ;)

**Comment by jwsp1** [comment]
Same problem with Brave Browser. Getting 'failed to fetch' errors when trying to save something new.
