### ISSUE TITLE
Autofill issue on banking site

### ISSUE THREAD

**Issue by dzampino** [bitwarden/browser#1003]
Using the Chrome browser add-in, the autofill fills in the username, but not the password field on [www.landmarkcu.com](https://www.landmarkcu.com/). This site works for me using LastPass.

**Comment by kspearrin** [comment]
The website has some really weird "fake password" fields that appear to be there to try to trick automated password input like Bitwarden is doing.

![image](https://user-images.githubusercontent.com/1190944/64478357-4b869200-d175-11e9-9cff-e4de969da7ee.png)

I am not sure the best way to try to subvert this.

**Comment by jellykells** [comment]
I looked at the site out of curiosity and it looks like the "fakepassword" field is only used to display the word "Password" before the user focuses on the input. The developer apparently didn't know about the input "placeholder" attribute. Unless they need to support IE versions <10... https://caniuse.com/#feat=input-placeholder

See this relevant javascript from the page:
```
<script type="text/javascript">
    $(document).ready(function () {
        $('form').attr('name', 'Login');

        var defaultUsername = "User ID";
        $("#userid").val(defaultUsername);

        var defaultPassword = "Password";
        $('#fakepassword').val(defaultPassword);
        $("#password").hide();

        $("#userid").focus(function () {
            fnInputReset_Focus(this, defaultUsername);
        });

        $("#userid").blur(function () {
            fnInputReset_Blur(this, defaultUsername);
        });

        $('#fakepassword').focus(function () {
            $("#password").show();
            $("#fakepassword").hide();
            $("#password").focus();
        });

        $('#password').blur(function () {
            var pass = $("#password").val();
            if (pass == "") {
                $("#fakepassword").val(defaultPassword);
                $("#fakepassword").show();
                $("#password").hide();
            }
        });
    });
</script>
```
Maybe the "type" attribute could be used to find the real password field? Not sure if that's reliable across other websites though.

**Comment by iamjsed** [comment]
I had a similar experience. [https://online.bdo.com.ph/sso/login?josso_back_to=https://online.bdo.com.ph/sso/josso_security_check](url).  Bitwarden chrome extension can auto-fill the the password field but when I click **Login** the site says my password is invalid.

However, if I tried it using my android phone using chrome for android and bitwarden app it works like a charm.

**Comment by dzampino** [comment]
Website has changed and the issue no longer persists.
