### ISSUE TITLE
Password Generator Behaviour is inconsistent with other bitwarden apps

### ISSUE THREAD

**Issue by erclu** [bitwarden/browser#1007]
Hi! loving the project so far.

Generating passwords through the generator tab in the browser extension currently behaves so that every time you go inside the password generator "History" tab and then back to the generator page, the password changes.

I noticed because I was trying to find the last generated password but the simple fact of checking the history moves the "wanted password" down the list, meaning the one i search is no longer the last but the second-to-last, which made me double check which was the right one, which moved the one i wanted to third-to-last, and so on...

This makes it kinda difficult to find the correct one and might lead to stuff like permanently losing passwords (e.g. copying and saving the wrong one).

Besides, this behaviour is inconsistent with the other bitwarden apps:
In the ones where i could verify (web vault/windows desktop) changing between the "Password Generator" tab and the "Password Generator History" tab DOES NOT regenerate the current password. Meaning that even if the "wanted" password does get moved down the list by one, switching back and forth does not move it further, which makes this behaviour a bit more bearable.

As a final point (but maybe this isn't the correct place), it would probably be better overall if the password generator history would get updated only AFTER a new one is generated. Meaning:

NEW behaviour:

- the generator tab has the CURRENT generated password
- the history tab contains the pw that was generated BEFORE the current generated password

ACTUAL behaviour (on every app I could test it on):

- the generator tab has the CURRENT generated password
- the history tab contains the CURRENT generated password

And if you made it till down here, thanks for your attention/patience :)

**Comment by dcominottim** [comment]
The current behavior has been a down-breaker for a while, almost enough for me to consider switching to another service... It's extremely infuriating and confusing to automatically see/get a new password everytime I open the generator tab in order to see the history.

**Comment by skube** [comment]
I find the current functionality does not match with most people's mental model of UI/X.

• Every click of **Generator**, generates a new password ✅ 
• Just _visiting_ Password History, then returning _also_ generates a new password 🤔.

https://user-images.githubusercontent.com/146396/118360060-fb6bef80-b553-11eb-869d-810681096506.mp4
