### ISSUE TITLE
Zoom level in Chrome messes popup menu up

### ISSUE THREAD

**Issue by dav20011** [bitwarden/browser#1008]
For some reason Chrome also applies the global zoom setting to the popup menus from extensions. This causes issues with the extension menu:

![Extension](https://user-images.githubusercontent.com/7550520/64929348-7e8bee00-d825-11e9-9291-6ccadae8131c.png)

I was unable to find a fix without modifying the extension itself. Chromes site-based zoom levels do not apply to the popup menus. A CSS zoom set to "1 / window.devicePixelRatio" works when I apply it manually.

**Comment by kspearrin** [comment]
I am not sure what the fix could be here. Are you suggesting one? This sounds like a Chrome problem.

**Comment by dav20011** [comment]
It's unlikely that this would be changed in Chrome since it would cause problems with a lot of plugins.

Yes my fix works, I added this line to the main.ts of the popup:
```typescript
document.body.setAttribute("style", "zoom: " + (1 / window.devicePixelRatio * 100) + "%");
```
It is not a very nice solution, but it works by simply compensating Chromes Zoom-Setzung.

**Comment by jprupp** [comment]
When I change the zoom level in Chrome, the BitWarden pop-up shows a useless scrollbar on Linux. I haven't tested in any other OS.

![BitWarden Zoom](https://user-images.githubusercontent.com/904557/87288716-9ee31280-c4f3-11ea-80fb-bde2003862c4.png)

**Comment by dav20011** [comment]
@AdnanHodzic I had to look this up because I did not use this fix for years (I just accepted that the browser scaling causes issues and lived without...), but it should be [this file](https://github.com/bitwarden/clients/blob/103662349fcac4cfaeb45726887393d845f8a664/src/popup/main.ts). It should not really matter where the code gets executed as long as it is called during initialization.
