### ISSUE TITLE
Autofill gets previous passwords from custom fields (1password import)

### ISSUE THREAD

**Issue by auggod** [bitwarden/browser#1010]
This may not be a bug but this can be a problem for people coming from 1password. I'll explain. I imported my vault from 1password into Bitwarden. Import went fine although autofill didn't work for many websites. Password length didn't seem to match either. Later, I realized autofill was using an older password instead. Then I found the custom fields containing previous passwords...

So, the problem is that autofill is using previous passwords stored in custom fields and now I have to manually cleanup.

I use 1password 6. Didn't want to upgrade to 7 just because 6 didn't work on latest brave browser.

**Comment by kspearrin** [comment]
Can you please provide an example export from 1Password that reproduces the issue?

**Comment by auggod** [comment]
It's easy to reproduce. You create a new login using 1password and generate a random password then immediately change it. The previous password will remain in the web form details of 1password.
Bitwarden will use the previous (old password) for autofill and not the main one. Copy password button will get the right one. 

So, I expect all logins for which I ever changed the password to be affected.

Here's an example for github (pif)

```{"uuid":"4F88AD8AA88B4B54839AED332F6752C4","updatedAt":1568926346,"locationKey":"github.com","securityLevel":"SL5","contentsHash":"e99e4d84","title":"example github","location":"https:\/\/github.com","secureContents":{"fields":[{"value":"bouncer-heifer-panicky-coolie-pep-incase","name":"password","type":"P"},{"value":"","name":"username","type":"T"},{"id":"login_field;opid=__2","value":"example@example.com","designation":"username","name":"login","type":"T"},{"id":"password;opid=__3","value":"colonize-torrid-pavanne-wats-veteran-oint","designation":"password","name":"password","type":"P"},{"value":"","id":"required_field_396c;opid=__5","name":"required_field_396c","type":"T"},{"value":"Sign in","id":";opid=__8","name":"commit","type":"I"},{"value":"","id":";opid=__9","name":"","type":"B"}],"passwordHistory":[{"value":"bouncer-heifer-panicky-coolie-pep-incase","time":1568926346}],"htmlMethod":"LB1","URLs":[{"url":"https:\/\/github.com"}]},"txTimestamp":1568926346,"createdAt":1568926314,"typeName":"webforms.WebForm"}```

**Comment by michaelx** [comment]
Can confirm. If I delete the custom fields, the right password is used again.

Is there are reason for importing the password history into `secureContents` and `passwordHistory`?

**Comment by kspearrin** [comment]
Should be fixed next version. Thanks.
