### ISSUE TITLE
Tab does not cycle through logins in popup

### ISSUE THREAD

**Issue by jellykells** [bitwarden/browser#1012]
1. I visit a site which I have multiple logins for.
1. Open the action popup either with the keyboard shortcut or the mouse.
1. Press the tab key but it only cycles through the pop out/add item buttons and the search field.
1. Have to use the mouse to click on the login I want to use.

Using the Bitwarden browser extension with Vivaldi 2.8.

**Comment by kspearrin** [comment]
Weird. This doesn't seem to be the case in Firefox. I am not sure why it won't tab to those items in Vivaldi.

**Comment by bvinnerd** [comment]
This is the case for me in Firefox 71.0b5 (64-bit)

**Comment by lamBOOO** [comment]
I have the same issue using Firefox. This prevents me from switching from Chrome to FF.

**Comment by bvinnerd** [comment]
A later version of FF (71.0b7 (64-bit) on macOS), has fixed this for me.

**Comment by lamBOOO** [comment]
Agreed, FF 71.0b8 works now for me – thanks!

**Comment by jellykells** [comment]
I still have this issue after upgrading to Vivaldi 2.9.1705.41. Changing tab behavior in the Vivaldi keyboard settings doesn't seem to work either.

**Comment by lamBOOO** [comment]
I even got it to run with Firefox 70.0.1 on macOS 10.15.1 using the steps of this guide:
https://stackoverflow.com/a/11713537

Adding the "accessibility.tabfocus" as integer with value of 7 in the "about:config" did the job. At least for me, it was an tabfocus issue of macOS.

**Comment by jellykells** [comment]
> Do you also use macOS, @jellykells?
No I've encountered this issue while using Manjaro Linux 18.1.3 and Windows 7

**Comment by benash** [comment]
I'm hitting this issue with Firefox 72.0.2/MacOS 10.15.2. Using the suggestion of @lamBOOO, I was able to tab through the list of logins. However, after pressing enter with an focused item in "My Vault", the item details appear instead of that site being launched, which is what I'd hope to achieve through the keyboard shortcut.
