### ISSUE TITLE
Safari extension does not work on Safari 13

### ISSUE THREAD

**Issue by mzch** [bitwarden/browser#1015]
Safari extension does not work on Safari 13.

**Comment by tcelestino** [comment]
Will we update about that? I saw discussion others open sources extensions on Safari and I'm worrying about the Apple changes to API's and many extensions don't update because it's toughest. 😢

**Comment by tcelestino** [comment]
@mzch https://github.com/bitwarden/browser/issues/664#issuecomment-525021821
