### ISSUE TITLE
Autofill hotkey clash with Firefox Nightly

### ISSUE THREAD

**Issue by bfabio** [bitwarden/browser#1016]
A couple weeks ago Firefox Nightly [bound Ctrl+Shift+L to the debugger](https://github.com/mozilla/gecko-dev/commit/d9ce406a8a20969b2a3c035f57bd27453903151b), resulting in the default keybinding for autofilling logins not working anymore.

**Comment by kspearrin** [comment]
Well, that's a bummer. Does Firefox allow you to change extension shortcut bindings yet?

**Comment by bfabio** [comment]
It does, there's a menu item in about:addons when viewing extensions (the cog icon).

I added a comment to [bug 1532139](https://bugzilla.mozilla.org/show_bug.cgi?id=1532139) in case they're willing to change it to something else.

**Comment by kspearrin** [comment]
Please let me know if they reply. Thanks.

**Comment by AbhishekTripathi** [comment]
There are conflicts with other browsers as well. I see that shortcut for generating the password conflicts with opening sidebar shortcut in Vivaldi.

**Comment by bfabio** [comment]
Firefox folks are working on checking in an alternative hotkey (https://bugzilla.mozilla.org/show_bug.cgi?id=1583042#c6)

**Comment by bfabio** [comment]
It's fixed now.
