### ISSUE TITLE
CloudFlare issue in Chrome(ium) - Error 1020

### ISSUE THREAD

**Issue by zloveless** [bitwarden/browser#1017]
I first noticed this last night. My bitwarden extension on my home PC wouldn't log me in (said my session had expired and that an error occurred). This morning I checked the website just to see if the web vault was functioning since I could access it via the mobile app.

![image](https://user-images.githubusercontent.com/385946/65379117-e011e980-dc77-11e9-9d0b-b2090d2a8f35.png)

```
Error 1020 Ray ID: 519ef351ad8e7fd2 • 2019-09-21 20:57:15 UTC
Access denied
```

Tried googling it, but the closest I got was a reddit post asking if it were down...from 4 months ago. Found a couple other issues here (#806 and #805), but they show a CF 1006 error instead of a 1020.

I can access the website from Firefox on my home PC, Bitwarden extension in Chromium on my work PC, and Bitwarden app on my Android phone just fine. Checked with a friend whom I converted to Bitwarden a year ago (and he pays for our organization's access) and he isn't getting this error.

**Comment by kspearrin** [comment]
Should be resolved now. You should also look into upgrading your outdated Chrome version, however.

**Comment by zloveless** [comment]
Thanks for the quick response in solving it.

> You should also look into upgrading your outdated Chrome version, however.

What do you mean? I'm running the latest version of Chromium.

![image](https://user-images.githubusercontent.com/385946/65390074-a5a85b00-dd10-11e9-9e7b-de19e595ccd2.png)

**Comment by kspearrin** [comment]
The latest version is chrome is 76.
