### ISSUE TITLE
No autofill from pinned tab

### ISSUE THREAD

**Issue by ctammes** [bitwarden/browser#1018]
I noticed that autofill of username and password doesn't work anymore on a pinned tab. Cmd-\ doesn't work either.
When I open the same site from Bitwarden in a new tab, autofill works as expected.

Safari 13.0 (14608.1.49)
Bitwarden extension 1.42.0

**Comment by kspearrin** [comment]
I think that this is a bug in Safari Extensions. I opened an issue on Apple developer forums here:
https://forums.developer.apple.com/thread/123120

**Comment by ctammes** [comment]
I think you are right, it happened after the latest Safari update.

**Comment by l0rda** [comment]
Hi,

they said: "This is expected behavior."
So, is there any workaround? I have a lot pinned tabs for my home infrastructure. This is annoying.

**Comment by kspearrin** [comment]
I am planning on looking to add a workaround.

**Comment by jZhangTk** [comment]
+1

**Comment by tech509201941** [comment]
+1

**Comment by Dobby16** [comment]
+1

**Comment by thedeany** [comment]
+1

**Comment by ToGitOrNotToGit** [comment]
> I am planning on looking to add a workaround.

So @kspearrin... at this point should we expect for it to be left as is for legacy Safari versions but working with the unified browser extension framework in future releases?

**Comment by cscharf** [comment]
We've figured this out and a fix will be released shortly that supports autofill in pinned tabs for Safari App Extensions.

**Comment by ToGitOrNotToGit** [comment]
It is resolved for me in Safari Version 14.0 (15610.1.28.1.9, 15610) with Bitwarden Version 1.22.2 (1.22.2)! Thanks, refreshing to have it working again.
