### ISSUE TITLE
experimental autofill should not autofill fields that are already filled

### ISSUE THREAD

**Issue by Nemo64** [bitwarden/browser#1019]
I have the experimental autofill option enabled and it is mostly awesome.

However, I work on a lot of sites that have user-management. What happens is: If I edit a user (not me) bitwarden will autofill the username/password fields with my current login credentials. If I'd safe that user, I'd either get an error (username already defined) or worse.

So my thinking is that it should be easy enough to not autofill username/password fields that are already filled. It should still be possible to manually fill them using the ⌘+⇧+L shortcut if some site has the fields pre-filled with `username` or similar.

**Comment by kspearrin** [comment]
Good suggestion. I like it.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/commit/93e5eeda6bc5268e5c4d3c42bd42f442d5ca171b
