### ISSUE TITLE
Copy username/password from right-click context menu

### ISSUE THREAD

**Issue by jagerman** [bitwarden/browser#102]
One thing I miss from LastPass is the ability to copy the username/password for the current site from the context menu.  I.e. when I right-click on this page with bitwarden, I get just:

```
    bitwarden -> Autofill -> github.com (jagerman)
```

I would like to also have:

```
    bitwarden -> Copy username -> github.com (jagerman)
    bitwarden -> Copy password -> github.com (jagerman)
```

Because, sometimes, I run into situations where autofill doesn't work (often because web page designers decided to do broken, stupid, non-standard crap with form fields).  Of course I *can* do that through clicking the extension button, but the context menu is a lot closer.

It might also make sense to swap the context menu orders, i.e. to present:

```
    bitwarden -> github.com (jagerman) -> Autofill
                                       -> Copy username
                                       -> Copy password
```

**Comment by kspearrin** [comment]
This function is actually there for all browsers except Firefox. For some reason Firefox does not allow access to the clipboard from the background thread, only from within the popup window which is why we had to remove it.

**Comment by jagerman** [comment]
I wonder how LastPass worked around that (I just verified that it does have it, and it works).

**Comment by kspearrin** [comment]
I think LastPass still uses the old Firefox addon API which gives better access to things like this. [Firefox is actually phasing this API out this year](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/), so LastPass will likely lose that functionality at some point when they move to the web extension API like bitwarden uses (or Firefox will eventually add clipboard support in the background thread for web extensions).

**Comment by kspearrin** [comment]
Just so you dont think I'm crazy, this is documented here:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard

> 
> Browser-specific considerations
> 
> In Chrome:
> 
>     you can write to the clipboard like this in all execution contexts - background pages, content scripts, options pages, and popups.
>     you don't actually need "clipboardWrite", even to write to the clipboard outside a user-generated event handler.
> 
> In Firefox:
> 
>     you can write to the clipboard like this in all execution contexts except background pages. In Firefox you can't select text or focus an input field in background pages, so you can't write to the clipboard from a background page.
>     the "clipboardWrite" permission is only supported from version 51 onwards.
>

**Comment by jagerman** [comment]
That seems likely more of a bug that an intentional limitation, e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1272869

Hopefully it'll be fixed before too long, but I guess I'll have to live without it for now.

**Comment by kspearrin** [comment]
Closing this until Firefox allows it.
