### ISSUE TITLE
Unable to save new logins in Safari 13.0.1 running v. 1.16.4

### ISSUE THREAD

**Issue by Natalie-321** [bitwarden/browser#1022]
Environment:

OS: macOS 10.14.6
Bitwarden version: dmg install 1.16.4
Browser: Safari 13.0.1

What happens?

When using Safari 13.0.1 to sign in to any website with username and password not previously known to Bitwarden, the "Should Bitwarden remember this password for you?" banner shows for a second, but then disappears as the page refreshes following successful login, and doesn't reappear to continue saving the new login. Can confirm that this does not occur in the latest versions of Firefox or Google Chrome on the same OS. In both Chrome and Firefox, the banner reappears following page refresh, allowing the new login to be saved successfully.

How to reproduce:

Using Safari, visit an account based website that you have a preexisting account for (I tested with both Target.com and Walmart.com). Be sure that you use an account not yet stored in Bitwarden vault.
Enter your account credentials (username and password) and tap "Sign In."
After tapping "Sign In" button, verify that the "Should Bitwarden remember this password for you?" banner pops up momentarily (about 1 second) at the top of the page, but disappears following page refresh for successful login. The banner does not reappear to continue saving new login.

**Comment by TheDaveAbides** [comment]
Same issue here.

**Comment by jweetogh** [comment]
Same issue on my Mac.

**Comment by javisan23** [comment]
Same issue for me. Still not fixed in Feb 2020. I was excited to drop LastPass for Bitwarden but this issue has frustrated me enough to make me stop using Bitwarden.

**Comment by kolja1507** [comment]
Same for me

**Comment by tomillr** [comment]
I am using the same setup and have never once even been shown the banner to save new login credentials to the vault.

**Comment by kushpvo** [comment]
Same here. I am using the latest version and I never get the banner to save new login info on safari.

**Comment by patrickbgates** [comment]
Me too. I'm using Mac OS 10.15.4 and Safari 13.1. For me (like some others in this thread), the banner to add new logins is never displayed.

**Comment by t5n** [comment]
Ditto. Out of 70+ sites I've logged in to since installing Bitwarden on Safari 13, the banner only appeared once.

**Comment by tonimelisma** [comment]
Same here. The issue's been open 1,5 years with no comments from the maintainers. Is this considered a bug? Is there something we can help with or contribute - and if so, how?

**Comment by metabubble** [comment]
OSX Version: 11.1
Safari Version: 14.0.2 (16610.3.7.1.9)
Bitwarden Version: 1.47.0

Banners do not display here either.

**Comment by nikallass** [comment]
For me banner in Safari never displays.
Safari 14.0.2 (16610.3.7.1.9)
BigSur 11.1 (20C69)
Bitwarden 1.23.1 (1.23.1)
Safari Bitwarden Extension 1.47.1
