### ISSUE TITLE
High CPU usage when opening a large data:image... url

### ISSUE THREAD

**Issue by jonas-jonas** [bitwarden/browser#1023]
I have the extension installed on my Chrome `77.0.3865.90 (Official Build) (64-bit)` and when I open a large (>500kb) `data:image` url, the CPU usage spikes up. The Chrome task manager reports that Bitwarden takes up a 100% of CPU. There's also no way to stop it other than ending the process in the task manager.

For example; this triggers it for me: https://gist.github.com/jonas-jonas/e933be8463ea87d707d0c3426018c194 (for reference: it's a ~600kb big random jpg file)
Just paste the data-url into chrome's url bar, and watch the task manager.

Edit: Extension version is `Version: 1.41.0`

**Comment by kspearrin** [comment]
Have you tried disabling Bitwarden to see if the problem goes away?

**Comment by jonas-jonas** [comment]
> Have you tried disabling Bitwarden to see if the problem goes away?

Yes, it does. As described above, the built-in task manager of Chrome reports 100% CPU usage by the Bitwarden extension.

But just to be sure, I just disabled the extension and tried opening the image. The CPU did not go up.

**Comment by kspearrin** [comment]
I can reproduce this, but I have no idea why it is happening.

**Comment by rickysyamsi** [comment]
Hi people, first time here.

I can reproduce this too with the same extension `version (1.41.0)` and slightly newer Chrome `Version 77.0.3865.120 (Official Build) (64-bit)`.

Also this issue only occurs when I'm logged in to my Bitwarden account via extension, It does not occur when I'm logged out.
