### ISSUE TITLE
Password are less lengthy than asked for

### ISSUE THREAD

**Issue by mackaaij** [bitwarden/browser#1026]
Using macOS 10.14.6 Safari 13.0.1 and Bitwarden 1.42.0, I generated a password asking for length 20. The generated passwords are 18 characters instead of the expected 20.

**Comment by kspearrin** [comment]
I am not able to reproduce.

![Screen Shot 2019-10-04 at 10 16 40 AM](https://user-images.githubusercontent.com/1190944/66214714-3b88a200-e690-11e9-876f-fd2f4f6b7b9b.png)

**Comment by mackaaij** [comment]
Hmm I really counted several times and retried so I was about to record a movie. But now I can't reproduce either... Weird.
