### ISSUE TITLE
Add platform identifier to App name

### ISSUE THREAD

**Issue by Stephan-P** [bitwarden/browser#1028]
I've got both Bitwarden Desktop and Bitwarden browser extension installed on my PC.

In Windows settings - Apps - Apps, two seemingly identical items Bitwarden are listed:
- Bitwarden (version 1.16.6)
- Bitwarden (version 1.14.0)

From the app names (and/or their version numbers) I cannot tell which is the desktop app and which is the Edge browser extension. Even worse, I could not tell the difference between Bitwarden Desktop (installer) and Bitwarden Desktop (Store version).

If the apps would be named "Bitwarden - Desktop", "Bitwarden - Store version" and "Bitwarden - Edge browser extension" respectively, it will be clear which is which.

**Comment by kspearrin** [comment]
There was a bug in version 1.14.0 of the desktop app that caused this issue. You will need to reinstall the app to clear it. It shouldn't occur again.
