### ISSUE TITLE
[Firefox 69.0.2] Duo 2FA showing a blank page

### ISSUE THREAD

**Issue by CSAS-Nicholas-Roberts** [bitwarden/browser#1031]
When logging into the firefox plugin with 2FA enabled, the Duo page that's displayed is blank. This is the first time I'm attempting to use the plugin, so for me it has never worked.

![image](https://user-images.githubusercontent.com/48771206/66342313-fc5f8880-e8fd-11e9-981f-adac5abfded7.png)

I've tried refreshing the browser, adding exceptions for cookies and whitelisting duo.com and duosecurity.com addresses for popup windows, and still just the blank image above. Any guidance would help. Thanks in advance!

**Comment by kspearrin** [comment]
I am not sure. It seems to work for me. Do you have another browser you can try to see if it is just Firefox related?

**Comment by CSAS-Nicholas-Roberts** [comment]
Yeah it seems to be Firefox specific. I just tried on Chrome 77.0.3865.90 and the Duo prompt came up without a problem.

**Comment by CSAS-Nicholas-Roberts** [comment]
I got it to work. Had to fiddle with some of my other plugins but it's looking good now. Sorry to distract you. Have a good one!

**Comment by ThePresence** [comment]
Hi @CSAS-Nicholas-Roberts which plugin was causing this issue? I'm getting the same issue.

**Comment by CSAS-Nicholas-Roberts** [comment]
@ThePresence I had both uBlock and PrivacyBadger enabled with some pretty strict settings.

**Comment by ThePresence** [comment]
> @ThePresence I had both uBlock and PrivacyBadger enabled with some pretty strict settings.

Thanks.. it worked.
