### ISSUE TITLE
Bitwarden notifications not obvious for screen reader users

### ISSUE THREAD

**Issue by tyrylu** [bitwarden/browser#1032]
Hello.
When a Bitwarden notification appears, a visually impaired user has no other choice than to scroll all way down to access it (of course, he can use a frame jump command). Ideally, he discovers that just this time, there's no notification. Would it be possible to add some sort of ARIA roles and attributes so a screen reader would announce the notification?

**Comment by kspearrin** [comment]
Let me look into that. How's the rest of the app been for accessibility?

**Comment by kspearrin** [comment]
I added `aria-live="polite"` to the toast message in the next update. Do you think that will solve the problem?

**Comment by tyrylu** [comment]
It might definitely help, no idea how the exact case will be handled, but after adding this you might enter the territory of browser/screen reader bugs, so thanks for this one. I'll try the current master branch and we'll see. Also, thanks for the other a11y commit.

**Comment by kspearrin** [comment]
Please let me know if you encounter any other a11y issues.

**Comment by tyrylu** [comment]
It seems that the aria-live attribute must be set on the notification bar div (e. g. the code in notificationBar.ts where the div and the iframe is being created must change. There appears not to be any difference if the attribute is set on the iframe or on the div. I would like to see a role="alert" there, but in that case it's read just weirdly (at least with Firefox and NVDA), so the aria-live will have to suffice.
