### ISSUE TITLE
Clipboard cleared even if password isn't in vault

### ISSUE THREAD

**Issue by thebnich** [bitwarden/browser#1035]
The following has happened to me on more than one occasion:

1. Enable the Clear Clipboard option in Bitwarden.
1. Register for a site by generating a password (context menu > Bitwarden > Generate Password).
1. Submit the form, and Bitwarden fails to prompt to save the credentials for some reason.
1. I go to add the login to my vault manually, but the password has been cleared from my clipboard.

At this point, I'm forced to do a password reset since it's not in the vault or clipboard. Shouldn't the clipboard be cleared only if the password is actually stored in the vault?

**Comment by kspearrin** [comment]
The clear clipboard feature will clear the clipboard of anything that you copied from the Bitwarden application.

**Comment by thebnich** [comment]
Right -- I was proposing this behavior be amended so that the clipboard is cleared of anything that you copied from the Bitwarden application _once that item is in the vault_, due to the password being lost in the steps described above.

However, I just discovered that passwords generated this way are still available in Generator > Password History in Bitwarden, so all is not lost. That's good enough for me, so closing this issue.
