### ISSUE TITLE
Safari extension doesn't stay logged in

### ISSUE THREAD

**Issue by jlhopes** [bitwarden/browser#1036]
I am using the Safari extension on Safari 13.0.1, running on High Sierra, and I currently have Bitwarden 1.16.6 installed (from the website). The Safari extension works but it keeps logging me out every few minutes, even though it's set to lock only on restart.

With the old extension on Safari 12, it worked as expected, and I would stay logged in unless I restarted Safari. Now, it seems I am logged out very frequently.

**Comment by kspearrin** [comment]
You are logged out, or the app locks?

**Comment by jlhopes** [comment]
I click on the button for the Bitwarden extension (in Safari) and I am logged out (have to re-enter my master password) even though I entered the password just a few minutes ago. I don't have the Bitwarden app open, as I only need the browser extension. Thanks for your help.

**Comment by kspearrin** [comment]
If you are only entering your master password, this would just be unlocking. Logging in requires email + master password.

**Comment by jlhopes** [comment]
I see what you mean. So yes, it is locking, even though it is set to lock only on restart.

**Comment by jlhopes** [comment]
Setting the lock option to "Never" seems to work properly, but I'd rather not have to do that, as it's less secure.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1021
