### ISSUE TITLE
fedora 31 beta w/ firefox latest closes popup when using folder select list

### ISSUE THREAD

**Issue by tpetersohn** [bitwarden/browser#1038]
Editing a new vault entry to move item to other folder not working. Works only in side panel, but not from icon bar.

**Comment by kspearrin** [comment]
> not working.

Can you please explain more details about what behavior is occurring?

**Comment by tpetersohn** [comment]
In vault I select a newly created website. I click on edit. I choose a new Folder. Now Bitwarden closes itself, leaving me with the list of Folders. Clicking on a Folder does nothing.

**Comment by Hinton** [comment]
Hi @tpetersohn,

Are you still able to re-produce this issue? We've had a couple of related issues with fedora related to their specific FF patches but from what I can see those issues have been resolved.

Going to close this issue for now, but if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
