### ISSUE TITLE
Safari 13 - Can't login to custom server

### ISSUE THREAD

**Issue by Balooforever** [bitwarden/browser#1039]
Hi,

With the new Safari 13 (on all mac os version), i can't login to my custom server.

I get this message :
"Origin file:// is not allowed by Access-Control-Allow-Origin."

Can you help me ? :)

**Comment by kspearrin** [comment]
You need to update your server

**Comment by Balooforever** [comment]
Oups !

Sorry, i go update :)

**Comment by gawertm** [comment]
hi. I am facing the same problem. what exactly must be updated? I tried yesterday and there were no updates available. It is just regarding safari extension. on chrome it works

**Comment by Balooforever** [comment]
Hi,

You need update the Bitwarden server

**Comment by gawertm** [comment]
stange - I tried already yesterday but didn't work. now it updated and it works!
thanks all
