### ISSUE TITLE
[enhancement] Search bar in the Main Tab (Current Tab)

### ISSUE THREAD

**Issue by LivingWithHippos** [bitwarden/browser#104]
I often search for passwords not belonging to the current tab's website, I think we could add the search bar to the "current tab" tab, maybe simply replacing the top bar. Or maybe just merging the two tabs (sometimes less is better ;D)

**Comment by globau** [comment]
how about switching to the 'my vault' page automatically if you start typing on the 'tab' page?

**Comment by LivingWithHippos** [comment]
Sounds good to me

**Comment by kspearrin** [comment]
We'd need to add auto-filling capabilities from the my vault page I assume.

**Comment by LivingWithHippos** [comment]
Maybe it could just switch to the my vault page when typing?

**Comment by mhammond** [comment]
> We'd need to add auto-filling capabilities from the my vault page I assume.

I think that would be ideal - I've struck cases where I should have set an equiv domain, so wanted to search the vault and autofill. Of course, auto-filling an unrelated domain should make a noisy warning and probably shouldn't be presented as something you regularly want to do, so it sounds tricky to get right...

**Comment by sergwish** [comment]
"Current tab" tab usually has enough free space to display a search bar. This would give a hint to users. Just switching to the "Vault" tab on a key press is not as obvious. Just like many users still do not know about a very convenient Firefox feature of starting text search on any page just by typing text.

**Comment by kspearrin** [comment]
We added the search bar there in 1.17.x. When you start searching it simply switches you to the vault tab.
