### ISSUE TITLE
Autofill keyboard shortcut overridden in Firefox 71

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/browser#1041]
I'm using Firefox Developer Edition (71) and today's update shipped with a change that binds Control+Shift+L to the devtool debugger pane. 

Not sure how you want to proceed, but thought you'd want to know what's coming soon to the release version.

**Comment by cadecairos** [comment]
Related bug report in Bugzilla: https://github.com/bitwarden/browser/issues/1041

**Comment by digitarald** [comment]
The new shortcut is only in Nightly atm and we are working on testing other shortcuts.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1016

**Comment by kspearrin** [comment]
@digitarald I appreciate you guys re-considering this. It would be a huge pain to re-train our Firefox userbase on a new shortcut.
