### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by jimwins** [bitwarden/browser#1042]
When 1.6.10 is installed from App Store, it crashes immediately on startup on Mac OS X 10.11.6. Diagnostics attached.

1.16.6 downloaded from the website runs, but the extension does not show up in Safari.

**Comment by jimwins** [comment]
[Bitwarden Helper_2019-10-16-140837_aruna.crash.txt](https://github.com/bitwarden/browser/files/3736459/Bitwarden.Helper_2019-10-16-140837_aruna.crash.txt)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/desktop/issues/325
