### ISSUE TITLE
Don't trigger autofill when there are multiple password fields.

### ISSUE THREAD

**Issue by jdgregson** [bitwarden/browser#1049]
When I go to edit a user account on various websites and apps, they often have a "new password" and "confirm password" field to allow me to change the user's password. Bitwarden always seems to trigger on these pages, and autofills the username and password wherever it can. What's worse is when it uses the wrong entry to autofill. For example, if I go to change a setting on an employees' account and don't notice that Bitwarden has done this, I'll end up changing the setting I was after and then changing their password to mine. This is obviously not what was intended. This also happens on password reset forms, filling whatever password Bitwarden selects into the "old password", "new password", and "confirm password" fields.

Would it be possible to modify the autofill functionality so that it does not activate when there are two or three password fields next to each other?

**Comment by MurzNN** [comment]
I have similar problem on user profile pages, when I open other user profile, I describe it in separate issue #1072

**Comment by PinkDev1** [comment]
If it's that annoying, you can disable the setting in Settings -> Options -> Enable Auto-fill On Page Load. Also, I suggest you add "[FEATURE REQUEST]" at the beggining of this issue's title, so that afterwards the developers of BW can sort through easily.

PS: friendly reminder that this feature still has the text :
> WARNING: This is currently an experimental feature. Use at your own risk.
