### ISSUE TITLE
custom and username fields not working for hsbc.com

### ISSUE THREAD

**Issue by fawaf** [bitwarden/browser#1051]
the username field of the username form does not fill in and the month, day, and year fields of the password form also do not fill in.

**Comment by kspearrin** [comment]
It would be helpful if you linked to the actual form so I know what you are referring to.

**Comment by gnowxilef** [comment]
oh, good point. sorry about that. https://www.security.us.hsbc.com/gsa/SECURITY_LOGON_PAGE/

**Comment by kspearrin** [comment]
Try creating a custom field called "username" for your username. You can do the same for the other date fields.

**Comment by gnowxilef** [comment]
ah, that worked for username, but not the month/day/year field.

**Comment by kspearrin** [comment]
What are the HTML names/ids of those fields?

**Comment by gnowxilef** [comment]
dateMonth, dateDay, and dateYear from what i could see, which was what i put in the custom fields.

**Comment by gnowxilef** [comment]
also of note, only when the field is selected does the plugin fill in the value. otherwise, nothing happens.

**Comment by gnowxilef** [comment]
anything yet?

**Comment by PinkDev1** [comment]
It would might be usefull if you upload the form's HTML here, since we can't visit see the actual form in https://www.security.us.hsbc.com/gsa/SECURITY_LOGON_PAGE/ without an hsbc account.

**Comment by gnowxilef** [comment]
good point, sorry about that. gist link here: https://gist.github.com/gnowxilef/ce5baa470469364d9c5be3d0c5c753b7

**Comment by cmcooper1980** [comment]
I am struggling with this also...any progress or suggestions?  I also tried dateMonth, dateDay, dateYear...even tried lbl_dateMonth/Day/Year...  I went as far as trying regex= but Autofill only fills password...

**Comment by yuancx** [comment]
I've looked a bit into the autofill while the inspector is active. 

It seems that Bitwarden is correctly detecting the field and is able to fill it, once the field has been edited. However, with the page in its default loaded state (field's `value` equal to an empty string, and showing `MM`, `DD` or `YYYY`), Bitwarden somehow cannot fill the field. 

In the inspector, the difference between the unfillable and fillable field's `outerHTML` is: 

Unfillable field: 
`<input class="dijitReset dijitInputInner" data-dojo-attach-point="textbox,focusNode" autocomplete="off" name="dateDay" type="text" tabindex="0" data-nlsid-value="InputErrorMsg.LOGON_MISSING_MESSAGE,InputErrorMsg.LOGON_INVALID_DAY_MESSAGE,Logon.DOB_DD" aria-labelledby="lbl_dateDay" id="dateDay" maxlength="2" aria-required="true" aria-describedby="dateError">`

Fillable field: 
`<input class="dijitReset dijitInputInner " data-dojo-attach-point="textbox,focusNode" autocomplete="off" name="dateDay" type="text" tabindex="0" data-nlsid-value="InputErrorMsg.LOGON_MISSING_MESSAGE,InputErrorMsg.LOGON_INVALID_DAY_MESSAGE,Logon.DOB_DD" aria-labelledby="lbl_dateDay" id="dateDay" maxlength="2" aria-required="true" data-com.bitwarden.browser.user-edited="yes">`

**Comment by cmcooper1980** [comment]
THANKS!!!
I use Violentmonkey as an extension in Firefox.  I've copy and pasted your script into Violentmonkey, loaded HSBC site and attempted Bitwarden extension login...  I noticed right off the bat MM DD YYYY are now blanked out and clicking Bitwarden extension to auto-fill now properly works...this is awesome!

**Comment by fawaf** [comment]
seems to be working now
