### ISSUE TITLE
Firefox extension remembers my password

### ISSUE THREAD

**Issue by kosvrouvas** [bitwarden/browser#1052]
When trying to unlock my vault, clicking on the extension I see that Bitwarden remembers my password. Just by pressing unlock, it unlocks. Is this normal?

![image](https://user-images.githubusercontent.com/3307723/68113598-d5947200-fefc-11e9-8a67-3651206f7ff7.png)

Latest Firefox and Bitwarden versions, macos catalina (happened to previous version of macos too)

**Comment by kspearrin** [comment]
Yes, since Firefox see this as a login form. You should probably disable Firefox's built-in password manager.

**Comment by dioptryk** [comment]
In addition, there's this "show password" button. Someone would need just a second, when your back is turned, to see your master password. Then we go from 2FA to 1FA ;) Why is this button even there (in the desktop clients also)? Seems unreasonable and dangerous. On mobile, perhaps; it's sometimes hard to write a long password with the on-screen keyboard, but I'd definitely remove this button on the desktop. If there was a discussion about it already I couldn't find it.

**Comment by PinkDev1** [comment]
@dioptryk who would leave their password written on a login form and leave their PC without locking it? smh
Removal of the "show password" button is **very** unlikely to happen in any nearby release.

Now, on regards to OPs issue, as @kspearrin said, odds are bitwarden's vault password was auto-filled by another password manager. Such as, firefox's built-in password manager
