### ISSUE TITLE
Extremely high energy impact of the Safari extension

### ISSUE THREAD

**Issue by omidontop** [bitwarden/browser#1056]
The Safari extension has an enormous energy impact which can be seen in Activity Monitor:

<img width="1113" alt="Screenshot 2019-11-07 at 14 22 59" src="https://user-images.githubusercontent.com/1851344/68392523-3c6a9300-016a-11ea-9eda-e6ce17216df8.png">

It seems to be eating the battery alive. 

macOS Catalina 10.15.1 (19B88)
Safari Version 13.0.3 (15608.3.10.1.4)
Bitwarden Version: 1.42.0

**Comment by kspearrin** [comment]
From what I read, it says the energy impact is 0.0?

**Comment by omidontop** [comment]
@kspearrin At that moment yes, but the average over the last 12 hrs exceeds even that of the Parallels Desktop!!

**Comment by djsmith85** [comment]
Closing this as we are tracking this issue at https://github.com/bitwarden/browser/issues/1770
