### ISSUE TITLE
No feedback on failed password saves when server unavailable

### ISSUE THREAD

**Issue by jesherman** [bitwarden/browser#1057]
My docker instance running Bitwarden had some sort of mssql error around October 19th. Not sure what the underlying problem was that led to it, but update/restart fixed the issue. 

However, all the while (for almost 3 weeks) Bitwarden was failing to update itself and save new passwords since the db was crashing. On the Chrome Extension side of things, there were no warning message, no alerts that sync recently failed even as I saved new passwords during that 3 week period. I only found this out after manually checking the web vault was broken and going to the extension settings and noticing the last sync date was very old. After restarting docker and freshly syncing, it didn't add any of the new passwords I had created over the last few weeks.

It appears all the while, the new passwords were not saved, either locally on the Chrome Extension or on the web vault, so they're now all lost. It seems like there needs to be more alerts around syncing and some sort of check upon creating a new password to take action when there's a connectivity issue.

**Comment by kspearrin** [comment]
How were you saving the new passwords? From the notification banner or directly in the popup window interface?

**Comment by jesherman** [comment]
Yeah via the popup which gave me the impression it was being stored locally for sync
