### ISSUE TITLE
Two Bitwarden Chrome Extension instances?

### ISSUE THREAD

**Issue by Bluetexon** [bitwarden/browser#1058]
Hello,

i really enjoy Bitwarden and am using it now at my work and private. The problem here is, that my work vault is self-hosted and my private Bitwarden is using the default Bitwarden servers.
Is there any way to have two Bitwarden Instances in Chrome?

Thank you,
Bluetexon

**Comment by kspearrin** [comment]
The only way to handle this is to have two browser profiles. You can install Bitwarden in each profile and run it with different user accounts/servers.

**Comment by Bluetexon** [comment]
But those two browser profiles can't run simultaneously, correct?

**Comment by kspearrin** [comment]
Not that I know of. I think you have to toggle between them.

**Comment by Bluetexon** [comment]
I've had the idea of having two Bitwarden Chrome Extension. One normal and one "business" or "secondary" Bitwarden version. But I think Google won't allow that due to their TOS

**Comment by Zeustopher** [comment]
I overcome similar in a few ways:

**Option 1)** by having the plugin installed in Chrome logged into Vault A and then I've installed the desktop app and had it logged into Vault B. I log into the Chrome Plugin with whichever vault I need to access most often.

**Option 2)** Use Chrome/Firefox with plugin for Work Vault and Vivaldi with plugin for Personal Vault. This has the added advantage that _everything_ in Vivaldi is personal and _everything_ in Chrome/Firefox is work.

Neither option is perfect, but I've ended up staying with Option 2 for several months now and have gotten used to it being that way. Those options don't work in all scenarios either (like if you are using  a Chromebook then you're locked into Chrome _and_ you can't install a desktop app).

**Comment by Bluetexon** [comment]
Alright, thank you for your reply. I appreciate it.
I think I'll go with option 2, but I'll try your idea with installing it in chrome as secondary instance.

**Comment by LaurentSGL** [comment]
I've got the same problem, since last week where we install a self hosted version in our company.
Before that i'm using Bitwarden for private use and wanted two instance of BW extension in Chrome
That's why, with the open source of BW extension, i compile it, with some lightly diff like the color of icon, and now i've got 2 instances of BW

![image](https://user-images.githubusercontent.com/51741721/75443936-bbc2e300-5962-11ea-9b9f-ea6b107450ee.png)

**Comment by MurzNN** [comment]
@LaurentSGL, thanks for great solution! Maybe Bitwarden officially publish "Bitwarden secondary" extension in repositories (with different icon color) for solve this issue?

**Comment by whereisaaron** [comment]
How do you handle two or three accounts with the mobile apps? Only supporting one account per app install is not sensible.
Just think, if you use Bitwarden for your company, then you must **never recommend Bitwarden** to any company you work with, because if they adopt it, you would be able to access your account for both without extreme hassle 😄

**Comment by tgreer-bw** [comment]
@whereisaaron client account switching is on the roadmap :-)

**Comment by LaurentSGL** [comment]
the account switching wil be avalaible for both mobileapp and browser extension ?

**Comment by ygbillet** [comment]
> 
> 
> How do you handle two or three accounts with the mobile apps? Only supporting one account per app install is not sensible.
> Just think, if you use Bitwarden for your company, then you must **never recommend Bitwarden** to any company you work with, because if they adopt it, you would be able to access your account for both without extreme hassle 😄

On Androind, a workaround is to use [Work Profile] (https://support.google.com/work/android/answer/6191949?hl=en). However, this is limited to 2 instances

**Comment by whereisaaron** [comment]
@tgreer-bw has this moved up the roadmap queue? Is the roadmap anywhere we can follow along?

Is this the right feature to vote for?
https://community.bitwarden.com/t/log-in-with-multiple-bitwarden-user-accounts/716

**Comment by tgreer-bw** [comment]
It's high priority, but also a very large item, so we plan on having it available in Q4 roughly.

**Comment by Kerwood** [comment]
> I've got the same problem, since last week where we install a self hosted version in our company.
> Before that i'm using Bitwarden for private use and wanted two instance of BW extension in Chrome
> That's why, with the open source of BW extension, i compile it, with some lightly diff like the color of icon, and now i've got 2 instances of BW
> 
> ![image](https://user-images.githubusercontent.com/51741721/75443936-bbc2e300-5962-11ea-9b9f-ea6b107450ee.png)

Nice @LaurentSGL .. Could I get you write a couple of lines on how you did that ?

**Comment by LaurentSGL** [comment]
> > I've got the same problem, since last week where we install a self hosted version in our company.
> > Before that i'm using Bitwarden for private use and wanted two instance of BW extension in Chrome
> > That's why, with the open source of BW extension, i compile it, with some lightly diff like the color of icon, and now i've got 2 instances of BW
> > ![image](https://user-images.githubusercontent.com/51741721/75443936-bbc2e300-5962-11ea-9b9f-ea6b107450ee.png)
> 
> Nice @LaurentSGL .. Could I get you write a couple of lines on how you did that ?

just follow the instruction here to compile :)  : https://github.com/bitwarden/browser#buildrun

**Comment by Kerwood** [comment]
@LaurentSGL  Thanks :)
Where did you change the color of the icon ?

**Comment by LaurentSGL** [comment]
> @LaurentSGL Thanks :)
> Where did you change the color of the icon ?

in the folder "images" of the extension, i change the existing ones :)

**Comment by MurzNN** [comment]
@Kerwood maybe you (or someone else) can publish your recompiled version of Bitwarden extension to Chrome Web Extensions Store (and Firefox too), for make it publicly available for all? Or the license don't allow to do this?

**Comment by nylocx** [comment]
@MurzNN License is one thing, but I don't think one should encourage users to use a build from a "random" stranger for something like a password manager ;).

**Comment by nathanael-h** [comment]
There is a PR for that: https://github.com/bitwarden/browser/pull/2250

**Comment by addisonbeck** [comment]
> There is a PR for that: #2250

This isn't totally accurate. We're going to be releasing an account switching feature for the Bitwarden desktop app soon, but the browser PR linked here is just refactoring the browser extension to use the backing storage structure necessary to facilitate account switching. We're doing that refactoring on all of our apps for consistency. 

Account switching as a feature for the browser extension is on the roadmap, but not being implemented on #2250.

**Comment by nathanael-h** [comment]
Ah sorry...

24 janv. 2022 18:48:40 Addison Beck ***@***.***>:

**Comment by levihb** [comment]
> @Kerwood maybe you (or someone else) can publish your recompiled version of Bitwarden extension to Chrome Web Extensions Store (and Firefox too), to make it publicly available for all others? Or the license don't allow to do this?



> > > @LaurentSGL Thanks :)
> > > Where did you change the color of the icon ?
> > 
> > 
> > in the folder "images" of the extension, i change the existing ones :)
> 
> sorry for dragging up an old thread here, but I went ahead and modified the colors a tad, build the extension and have it loaded into my chrome, however, no matter what I seem to do, I can't get it to work with my selfhosted "vaultwarden" instance even though the extensions in the store seem to work just fine without any issue. Any ideas why?

I [built a signed version for Firefox](http://fs.levihb.com/personalwarden-1.56.8-fx.xpi) if either of you minds trusting a random internet person. [I just pushed it here](https://github.com/levihb/browser/commit/75f0b87aa04fbcefd7c1f0aac43faf44a51bc014), it's on a bit of an older version, and the colours have been replaced with black (including the thumbnail/icon), and the name has been changed to "Personalwarden". Also as I said it's signed, so there will be no issue in installing it within a non-dev Firefox.

@schmittg25 this is likely caused by a weird behaviour in the jslib electron library. For some reason in the dev version it uses slightly different URL's, and Vaultwarden doesn't like this. My compiled version will fix that, but the git version won't, if you want to add it to the git version, go into `jslib/electron/src/utils.ts` and look for the `isDev` function. Then just replace it with `return false;`.

**Comment by UseN1bble** [comment]
I just compiled the extension for Chrome following the instructions from the page advised by @[LaurentSGL](https://github.com/LaurentSGL)

I use Nodejs version 16 and NPM version 8.
I got quite a lot of warnings  and deprecated information during the compiling.
The extension installs fine in Chrome though, but there are 2 errors one with Gecko (`Unrecognized manifest key 'applications'.`) and the other with sidebar action (`Unrecognized manifest key 'sidebar_action'.`)

No idea if this going to be a problem or that I should recompile again with differentversions op Nodejs and/or NPM.

**Comment by erikschwalbe** [comment]
Saw the same problems like @UseN1bble during build process.
```
npm ci 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bitwarden/clients@0.0.0',
npm WARN EBADENGINE   required: { node: '~16', npm: '~8' },
npm WARN EBADENGINE   current: { node: 'v19.0.1', npm: '9.2.0' }
npm WARN EBADENGINE }
 ```
```

husky install

husky - Git hooks installed

added 3391 packages, and audited 3401 packages in 1m

417 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (1 low, 5 moderate, 34 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
npm run build:watch
 main (webpack 5.74.0) compiled with 21 warnings in 46157 ms

Than followed the guide for chrome on https://contributing.bitwarden.com/getting-started/clients/browser/ but after loading the unpacked source from file system I saw 3 errors.:

- Unrecognized manifest key 'applications'.
```
 "applications": {
    "gecko": {
      "id": "{446900e4-71c2-419f-a6a7-df9c091e268b}",
      "strict_min_version": "42.0"
    }
  },
```
- Unrecognized manifest key 'sidebar_action'.
```
 "sidebar_action": {
    "default_title": "Bitwarden",
    "default_panel": "popup/index.html?uilocation=sidebar",
    "default_icon": "images/icon19.png"
  },
```
- Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```
"manifest_version": 2,
```
@UseN1bble have you been able to solve your problem?

**Comment by UseN1bble** [comment]
Hello Erik,

Same here, dispite the errors (or warnings) it works.

**Comment by riccardospeggiorin-centropaghe** [comment]
Any news on account switchin?

**Comment by royduin** [comment]
It's on de roadmap voor the first half of 2023. Be patient or compile a second instance as mentioned above.

**Comment by robross0606** [comment]
Here we are at the end of 2023 and still not multi-account support in browser extensions.

**Comment by dbosompem** [comment]
Hi @robross0606 ,the team has done a good amount of work on this. Expect some great news with account switching in the upcoming releases!

**Comment by MurzNN** [comment]
> the team has done a good amount of work on this. Expect some great news with browser account switching in the upcoming releases!

Yes, the multi-account feature is coming (still), but it doesn't make the life of two-login users a lot easier, so publishing the second copy of the extension is still the better solution. So I posted a separate feature request about this: https://community.bitwarden.com/t/publish-a-secondary-copy-of-the-bitwarden-browser-extension-to-allow-use-two-logins-at-the-same-time/61966 - please upvote.

**Comment by tldev-de** [comment]
just to let you know - it's implemented with [2024.1.0](https://github.com/bitwarden/clients/releases/tag/browser-v2024.1.0) Thanks for the great work!

**Comment by robross0606** [comment]
I show as running 2024.1.1 right now and I don't see any changes.  Where is this option located?

**Comment by robross0606** [comment]
aha!  Just found it.

**Comment by robross0606** [comment]
FYI, this seems to work okay on Chrome but does not work on MS Edge (Chromium).  There seems to be bugs related to having multiple accounts on different self-hosted instances.
