### ISSUE TITLE
Autofill does not work when Chrome tab is loaded in IE Tab

### ISSUE THREAD

**Issue by dlwillequer** [bitwarden/browser#1059]
Username and password auto-fill do not appear to be functioning when used in conjunction with a page loaded with Google Chrome addon IE Tab. Manually copy & pasting into the fields works as expected. I have tried this with the experimental feature as well as the Windows shortcut key. I am using the Chrome Extension. 

IE Tab extension URL: https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd?hl=en-US

Error: 
![image](https://user-images.githubusercontent.com/25806407/68690504-98dd0200-051e-11ea-8624-13b0a1708b83.png)

As an additional note: Autofill works as expected on these same pages when not loaded in the IE Tab addon.

**Comment by Hinton** [comment]
Hi @dlwillequer,

I believe the IE Tab extension swaps out the rendering engine to IE. Which means we can't use the regular chrome APIs on the page.

Going to close this as it's not something we can fix at this stage.
