### ISSUE TITLE
Prompts to change password even though password hasn't been 

### ISSUE THREAD

**Issue by drewmccal** [bitwarden/browser#1060]
Every time I log into my timesheet system, Bitwarden asks me with a banner if I would like to change my password.  I would like to disable this prompt or have it be more robust.  I think this particular website somehow changes the field text to "•".  When I click save change, the saved value then becomes all bullets.  I'm not sure why this website does this.  Maybe something in the javascript?

I'm using Firefox 70.0.1 and the Bitwarden browser extension 1.41.0

**Comment by kspearrin** [comment]
Can you share what timesheet system it is? You can disable the feature completely under Settings > Options if it is too annoying.

**Comment by drewmccal** [comment]
It's Deltek/Costpoint https://www.deltek.com

**Comment by wsw70** [comment]
I have the same problem on numerous pages.

An example is https://ozecollege.yvelines.fr/
I can update this ticket with other sites as I stumble upon them - but this is several times a day.

As for disabling this option: it is extremely useful, I just believe its "discovery that there is a new password" feature could be fine tuned.
