### ISSUE TITLE
Auto fill not working on some sites

### ISSUE THREAD

**Issue by dadooqs** [bitwarden/browser#1061]
Hi, new to Bitwarden. I find, on some sites when I tap on the url, bitwarden displays a pop-up offering the choice of ‘Copy Password’, ‘copy login’ in stead of filling the data in.
I’m using Safari on an iPad Pro.
Two sites displaying this problem are bookdepository and reddit.

**Comment by kspearrin** [comment]
This occurs whenever it cannot locate a password field on the page.

**Comment by dadooqs** [comment]
Thanks for the prompt reply Kyle. There must be many Bw users who regularly login to reddit using Bw’s auto fill. Could this be aN issue peculiar to Safari on iOS?

**Comment by kspearrin** [comment]
Are you not using the newer autofill service? It sounds like you are trying to use the old share menu autofill feature.

**Comment by dadooqs** [comment]
Would that work on Firefox, which will be our cross-platform browser? Anyway, if a method has been superseded it maybe should be made clear that that is the case. Maybe in was in the docs somewhere but if so, I missed it. Thanks for your replies but we won’t be taking our evaluation of BitWarden any further. Good luck for the future.
