### ISSUE TITLE
iOS app is crashing on saving a new password 

### ISSUE THREAD

**Issue by andrewkr** [bitwarden/browser#1062]
iOS app on both my iPhone and iPad is crashing when I try and save a new/changed password.

My iPhone is an older model and not running the latest version of iOS. It’s an iPhone 6 Plus, running iOS 12.4.3.
My iPad is an iPad Pro 9.7, running,13.2.2

Bitwarden is Version: 2.2.5 (59) on both devices

It crashed a couple of times on my iPhone and I thought, oh, here we go. I’m going to have to update my phone and I don’t have the money right now. At least it will work on my iPad. But no. It keeps crashing on it, too.

Therefore, I think, I hope (?) that it’s an app problem.

**Comment by kspearrin** [comment]
Can you attempt to reinstall the app and see if anything changes? Maybe there is some corrupt data from a previous version or something.

**Comment by andrewkr** [comment]
Thanks, Kyle.

I didn’t think that a simple reinstallation was going to fix this as it was happening on two different devices.

I won’t close this in case you want to add something.

**Comment by kspearrin** [comment]
Did that fix it?

**Comment by andrewkr** [comment]
Sorry, I thought that I indicated that it fixed the problem. I know that I didn't state it explicitly, but I had indicated it.

Yes, it is fixed.
