### ISSUE TITLE
Clicking "Close" back to search results, shows input in search, but doesn't filter items.

### ISSUE THREAD

**Issue by SethX3** [bitwarden/browser#1063]
Using Firefox with the Bitwarden extension, the view shown in the GIF is the side-panel.

When we search for something, select an item from the results, then click "Close" to go back to our search results, we can see the search input at the top just fine but the list of items shows all logins, not just the filtered ones until the input is updated again.

![Peek 2019-11-18 22-43](https://user-images.githubusercontent.com/22801583/69096741-47b89b00-0a55-11ea-8229-99a4b18a5f1e.gif)

**Comment by kspearrin** [comment]
Thanks for the report. Should be fixed in the next version. See https://github.com/bitwarden/browser/commit/88b27469204bb19a8e203c10048f66b6d3f9da53
