### ISSUE TITLE
browser extension won't log in under chrome canary

### ISSUE THREAD

**Issue by duke8585** [bitwarden/browser#1064]
trying to use the current version from the chrome web store under chrome canary 
_Version 80.0.3968.0 (Official Build) canary (64-bit)_ does not allow me to log into the extension.
the error message is:
`Failed to fetch`
interestingly, in chrome canary i am also not capable of accessing bitwarden.com while in brave browser or regular chrome, this is possible as well as login into the browser extension.

**Comment by kspearrin** [comment]
Have you tried reporting the issue to Google? Sounds like a chrome issue.

**Comment by duke8585** [comment]
thx, planned to do this now, strangely after trying again today, neither accessing the website nor logging into the extension remains to be a problem. cannot reproduce this sadly.
