### ISSUE TITLE
Firefox: Cannot select Organisation Collection (Version 1.41.0)

### ISSUE THREAD

**Issue by x2764tech** [bitwarden/browser#1067]
When trying to add an Item to an Organisation, the list of Collections doesn't have a checkbox (as it does in the Windows version), and so there is no way of selecting a Collection, and clicking "Save" raises a "You must select at least one collection" error.

The web version looks like this:
![image](https://user-images.githubusercontent.com/2870080/69433168-049b4800-0d33-11ea-932d-33e53a2d2980.png)

The desktop (windows) version looks like this:
![image](https://user-images.githubusercontent.com/2870080/69433688-f39f0680-0d33-11ea-89d5-1f5d5f9afbce.png)

**Comment by kspearrin** [comment]
I am not able to reproduce the issue. Can you inspect the popup and see if the checkbox is in the DOM?

**Comment by x2764tech** [comment]
Thanks for verifying - seems restarting/updating FF (I'm on the aurora channel) fixed the problem - the checkbox was there, but the styling completely hid it.
