### ISSUE TITLE
Disable autocomplete for search field

### ISSUE THREAD

**Issue by MDXDave** [bitwarden/browser#1069]
Since a few days the chrome extension shows an autocomplete list of search queries when open it.

Is it possible to disable this list? Its very annoying. 
![image](https://user-images.githubusercontent.com/6099976/69533722-a1025c00-0f78-11ea-9f7b-71d58df7e9f1.png)

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/commit/86e3374d3d5eb573160a851f16e94b2aac8567be Should fix it
