### ISSUE TITLE
Difficult to see the URL for matching sites

### ISSUE THREAD

**Issue by mhammond** [bitwarden/browser#107]
If you have many logins matching a domain, it's quite difficult to see what the URL is for each matching entry - if you view the entry, you can see "Website" and the domain - but in this case, every matching domain has the exact same value, so it's difficult to differentiate the logins - you need to select "edit" where the URL can be seen.

I see 2 options:
* change vaultViewLogin.html so the full URL is shown
* show the full URL as a tooltip when hovering over the domain name.

I can open a pull request, but thought I'd get some feedback on a preferred solution first.

**Comment by kspearrin** [comment]
I don't have a problem with using a tooltip. A simple `title` attribute should suffice. There are plans for adding a URI rules engine in the future that should give you much better control over things like subdomains, ports, etc.
