### ISSUE TITLE
Content autofill is slowing down page loads severely in Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [bitwarden/browser#1070]
**Steps to reproduce:**
Load 5 tabs with some Jira URL (https://issues.jenkins-ci.org/browse/JENKINS-1181)
Select all tabs with Shift + Click.
Click F5 to reload all pages at the same time.
Wait for all pages to load then repeat this 3 more times.

**Expected behavior**
Most of the web content process's work is related to the site

**Actual behavior**
More than 50% of web content process is spent in autofill.js. Here is the profile I recorded https://perfht.ml/2OnWdx2

![image](https://user-images.githubusercontent.com/922368/69670793-5dedd900-109d-11ea-9061-311c846bcc9a.png)
In case you never used the Firefox Profiler here is some documentation https://profiler.firefox.com/docs/#/

I built the Bitwarden extension from the master branch in order to get the sources in the profile. Not sure how well that went since content.js line 96 does not point to any valid line.

BitWarden it the most resource hungry extension I use and I use quite a lot. I would be happy with some flag or option to disable whatever feature causes this perf issue.

**Comment by kspearrin** [comment]
Can you open Settings > Options and check "Disable Add Login Notification" and "Disable Changed Password Notification". Does the problem go away?

**Comment by andreicristianpetcu** [comment]
Sadly this does not fix my issue. Here is the new profile https://perfht.ml/2KWiZKd
![image](https://user-images.githubusercontent.com/922368/69678519-761a2400-10ae-11ea-85ee-9a6e99623dff.png)
This is where the profile points to. It seems that even with these flags changed, I still load the autofiller.js file.
![image](https://user-images.githubusercontent.com/922368/69678575-a19d0e80-10ae-11ea-83a9-2487d3ef8fdb.png)
![image](https://user-images.githubusercontent.com/922368/69678608-b7123880-10ae-11ea-9a57-2174721cd918.png)

**Comment by kspearrin** [comment]
Are you using “autofill on page load”?

**Comment by andreicristianpetcu** [comment]
No, I'm not 
![image](https://user-images.githubusercontent.com/922368/69678741-1c662980-10af-11ea-9b63-adc87ee539a7.png)

**Comment by kspearrin** [comment]
> This is where the profile points to. It seems that even with these flags changed, I still load the autofiller.js file.

The file will still load. I cannot conditionally change that. However, it should not do any work if those settings are as described.

Is the problem coming from `autofill.js` or 'autofiller.js`? You reference both of those in your comments.

**Comment by andreicristianpetcu** [comment]
@kspearrin The first one is [autofill](https://perfht.ml/2OnWdx2) and the second one is [autofiller](https://perfht.ml/2KWiZKd). I also saw `notificationBar` but that did not have such an impact.

I see you load both of these files from [manifest.json](https://github.com/bitwarden/browser/blob/86e3374d3d5eb573160a851f16e94b2aac8567be/src/manifest.json#L19-L23). 

What stops you from executing it on page load?

```javascript
function onComplete(e){
    if(isFeatureEnabled()){
        chrome.tabs.executeScript(e.tabId, { file: "content/autofill.js"});
        chrome.tabs.executeScript(e.tabId, { file: "content/autofiller.js"});
        chrome.tabs.executeScript(e.tabId, { file: "content/autofill.js"});
    }
}

chrome.webNavigation.onCompleted.addListener(onComplete,
  { url: [{ schemes: ["http", "https"] }] }
);
```

[executeScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript) is available cross browser.

![image](https://user-images.githubusercontent.com/922368/69738203-5b8f8b80-113e-11ea-9f28-780212130d9a.png)

I can try to make these changes locally when I get some time and see how it affects page load and performance data.

**Comment by andreicristianpetcu** [comment]
I made [this silly little commit](https://github.com/andreicristianpetcu/browser/commit/dee4aa5ce035c67f5c137b1b9a713bc5a1c29db0).

With `const isNotificationEnabled = true;` the performance issues are still there.
https://perfht.ml/2slbeXH
![image](https://user-images.githubusercontent.com/922368/69752488-f8135700-1159-11ea-88f8-34bc51bb5e5c.png)

With `const isNotificationEnabled = false;` the performance issues are fixed.
https://perfht.ml/2L2HoxQ
![image](https://user-images.githubusercontent.com/922368/69752524-1711e900-115a-11ea-8565-4d200a45c21a.png)

Unfortunately in both cases the extension does not work properly. I blame it on my lack of familiarity with your code base :smile:

**Comment by kspearrin** [comment]
TIL about `executeScript`.

I would certainly expect your commit to resolve the issues since it is essentially removing all of the scripts. We need to figure out which feature is causing the autofill collection that causes the degrading perf.

**Comment by andreicristianpetcu** [comment]
Is there anything else I can help with? Is the performance profile enough for you? @kspearrin 

Basically this is how I recorded the profile https://vimeo.com/269371096 the video is old, the profile url changed but that is the general idea.

**Comment by mstange** [comment]
> **Actual behavior**
> More than 50% of web content process is spent in autofill.js. Here is the profile I recorded https://perfht.ml/2OnWdx2

This is not actually what the profile shows. The profile has a search filter applied to it (for the string `moz-extension`), and the percentage shown in the tree is relative to the filtered samples, i.e. to the number of samples that have the string `moz-extension` anywhere in their stack. There is no easy way in the profiler to see the percentage relative to all collected samples.
It's instructive to look at the absolute "Running time (ms)" numbers, and they aren't all that high in this profile.

**Comment by eoger** [comment]
Could be [related](https://bugzilla.mozilla.org/show_bug.cgi?id=1369274)? ([root cause](https://bugzilla.mozilla.org/show_bug.cgi?id=613498) is still not fixed). I didn't look very hard at the profile that was posted though.

**Comment by andreicristianpetcu** [comment]
You are right, sorry for the confusion @mstange the filter influences the percentage.

@eoger these issues do not seem like mine. My browser does not slow to a crawl or freeze. I noticed that Jira is really slow on my main profile with a ton of extensions and it's faster on a new profile. I found a public Jira and started profiling. I noticed Bitwarden was injecting scripts for features I disabled being the number one performance consumer among several extensions. I will try to profile on Chrome also.

**Comment by andreicristianpetcu** [comment]
Why not lazy load the content scripts based on features being used? They get loaded all the time even if you need them or not.

**Comment by hirusi** [comment]
Is anyone else still facing this issue today? Bitwarden is frustratingly slower on Firefox when compared with Chromium - both the popup and the autofill.

**Comment by andreicristianpetcu** [comment]
Not sure if this helps but I switched to Keepass 😢

**Comment by wylfen** [comment]
This is definitely still an issue and can slow down certain pages by about half a second even on a very fast machine. Would it perhaps be possible to add an option to completely disable the autofill feature?

For now my workaround is to keep the extension logged out, since it won't check for autofill in that case.
