### ISSUE TITLE
[Chrome] password query for the master password remains after confirming

### ISSUE THREAD

**Issue by reigaaa** [bitwarden/browser#1071]
Hello, the password query for the master password remains after I have entered the password and confirmed it with the Enter key. Only after I close the popup and then open it again the PIN is requested. Should it work like this?

Settings: 
Lock options - If system locked
Unlock with PIN code - True

System:
Windows 10 - 1909 / Chrome 78
macOS - 10.15.1 / Chrome 78

**Comment by kspearrin** [comment]
I am not sure I understand the issue. Can you provide a video?

**Comment by reigaaa** [comment]
strange. today the mistake did not occur anymore, last week it actually occurred every day. should it occur again, i will try it.

**Comment by kspearrin** [comment]
We can re-open if the issue persists.
