### ISSUE TITLE
Bitwarden overwrite field content on profile pages for other users

### ISSUE THREAD

**Issue by MurzNN** [bitwarden/browser#1072]
Bitwarden autofill works well when I login to site - it fill my login and password. But if I am an admin of site, and try to change profile of other site user (I open profile edit page for not mine user) - Bitwarden replace that user credentials to mine! So, if I don't catch this before form submit, I will replace his password with mine. So this is also large security problem.

You can reproduce this on any popular CMS (Wordpress, Joomla, Drupal) with user admin permissions - try to open edit user profile form for any other user.

How we can prevent this situation? Can I configure ignore rules for disable Bitwarden autofill by url, or by filling "blacklist" field selectors?

**Comment by kspearrin** [comment]
You can change your item to use custom fields and target the login page inout fields specifically for your username and password. See https://help.bitwarden.com/article/custom-fields/
