### ISSUE TITLE
HTTP auth not working with subdomains

### ISSUE THREAD

**Issue by praetorxyn** [bitwarden/browser#1075]
Hello all, I am not sure if this is an issue per se, or if the fixes for a couple of other issues are not supposed to work together.

The way I understand it from [#116 ](url), if I only have a single login for a domain, it should log me in without me seeing the basic auth prompt at all. So far so good. Per #77, since I have multiple subdomains under my domain I am using the dropdowns to specify Starts With on the URL's, this way if I go to nextcloud.domain.com it will match that, without it interfering with calibre.domain.com.

I am not sure the aforementioned issues are supposed to work together, but I can at least inform that they do not seem to be in my case. I have no issues with [#77](url), as I'm able to login to different subdomains without interference. It just so happens that one of them is a COPS server (cops.domain.com) with basic auth using nginx, and I still get the auth prompt when I try to connect to it. The only recourse I've had at the moment is opening the desktop client, copying the password to the clipboard, and pasting it.

Bitwarden is the best password manager I've ever used (LastPass > 1Password > Bitwarden) and I'm aware of the technical hurdle for basic auth. I've only got a couple of things I am hosting that use basic auth, and I won't be using them too particularly often, as they're mainly OPDS feeds that I will configure once on my reading device and forget about it, but it is making testing the setup of these services more of a pain than it should be, so I just figured I would inform of the potential issue.

**Comment by kspearrin** [comment]
When you go to `cops.domain.com`, how many items does Bitwarden suggest? You can just reference the little number over the icon in the browser toolbar.

**Comment by praetorxyn** [comment]
I actually got it resolved. I could have sworn I was using Starts WIth to match the URL but when I went to get you a screen shot to show that, it was on Exact. Changing it to Starts With resolved the issue.

Sorry for the trouble, and thank you for the effort. I migrated from 1Password to a self-hosted Bitwarden maybe a month ago and I can't imagine using anything else now.
