### ISSUE TITLE
Sync not working since December 3rd

### ISSUE THREAD

**Issue by mike2307** [bitwarden/browser#1076]
Since December 3rd, the sync within firefox doesn't work any more.

Extension version is 1.41.0.
Firefox version is 71.0.
System is Fedora 31 with all updates installed.

Whenever I start the sync, it is being reported as successful, but neither the last sync date, nor the synced content changes.

This only affects the firefox extension. The flatpak app runs without any problems.

**Comment by mike2307** [comment]
Probably caused by the Firefox 71 update:
https://bugzilla.redhat.com/show_bug.cgi?id=1779570

**Comment by mike2307** [comment]
Confirmed to be a problem with Firefox 71 on Fedora.
I used [this](https://kojipkgs.fedoraproject.org//packages/firefox/71.0/12.clang.fc31/x86_64/firefox-71.0-12.clang.fc31.x86_64.rpm) as a workaround.

**Comment by starxg** [comment]
`
rm -rf /Applications/Firefox.app
rm -rf ~/Library/Application Support/Firefox/
rm -rf ~/Library/Caches/Firefox
rm -rf ~/Library/Preferences/org.mozilla.firefox.plist 
`

First remove your Firefox then install it again.
