### ISSUE TITLE
Bitwarden doesn´t recognize Login on the <input type="password" name="UserId">

### ISSUE THREAD

**Issue by MrFishLP** [bitwarden/browser#1078]
http://www.eproasp.biz/aci/Comuni/login.asp
Probably because  in the form:
input type="password" class="groove" name="UserId" size="14"
input class="groove" type="PASSWORD" name="Password" size="14"
It fill always password in UserId and Password on Chrome Browser.

**Comment by kspearrin** [comment]
If both fields are marked as passwords, it will assume they are password values. To fix this, you can use custom fields to target the fields more specifically.

See https://help.bitwarden.com/article/custom-fields/
