### ISSUE TITLE
A11y (onscreen keyboard) issue in Firefox Extension

### ISSUE THREAD

**Issue by DanielVitor97** [bitwarden/browser#1079]
Hi, I'm a Google Chrome and Google Passwords user trying to migrate to Firefox and Bitwarden.

I liked a lot Bitwarden's features, but I am unable to use the Firefox extension.

I have several motor issues and the only way I can interact with my computer is through a mouse, then I use a onscreen keyboard.

When I try to use Bitwarden's Firefox Extension I am unable to type anything (even log in) because when I click on the keyboard the extension minimizes.

I have tried different keyboard apps but the behavior is always the same.

Is there a way of change this behavior? Or maybe add the option of use the extension on a pop-up window/tab?

For now I am using Web Vault and Linux app, but they are not practical as a browser extension.

**Comment by kspearrin** [comment]
Unfortunately, this is the behavior of the web browser and we cannot change it. Alternatively, you would pop the window out to a new window so that it will persist using the icon in the top left corner. Or you could persist the extension in the sidebar window.

**Comment by DanielVitor97** [comment]
Wow, thanks, I didn't know that Firefox have these options, it will help me a lot. Sorry to bother you, Bitwarden is awesome.
