### ISSUE TITLE
[Firefox] Auto-fill on PayPal website doesn't work properly

### ISSUE THREAD

**Issue by pianogamer5** [bitwarden/browser#1080]
### Steps to reproduce
1. Go to PayPal
2. Autofill saved login

### Expected results
User and Pass is auto-filled

### Actual results
Something else gets auto-filled too, causing an error when pressing the Next button: "Try entering the code again."

![image](https://user-images.githubusercontent.com/16405746/70459667-ab494d80-1a82-11ea-917c-23fe1b581a3a.png)

**OS:** macOS 10.14.6
**Browser:** Firefox Nightly 73.0a1 (2019-12-09) (however, this was happening also in the latest release Firefox version, 71)
**Bitwarden extension version:** 1.41.0

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/982
