### ISSUE TITLE
Bitwarden autofill Credit Card

### ISSUE THREAD

**Issue by Silver0066** [bitwarden/browser#1082]
Bitwarden will not autofill credit card info.  Wants me to copy and paste.

I am trying Bitwarden instead of Lastpass, but this is a deal breaker.  Any suggestions?

**Comment by kspearrin** [comment]
It would be helpful if you included the webpage that is having issues autofilling.

**Comment by Silver0066** [comment]
Walmart checkout and all others..  I am using Windows 10.

**Comment by kspearrin** [comment]
I just tested walmart checkout and everything works as expected. Open the Bitwarden popup window and click your credit card to autofill.

**Comment by Silver0066** [comment]
Thanks, I was just clicking the Bitwarden credit card icon.  When I opened it and then closed it, it worked.  This is different than LastPass.
