### ISSUE TITLE
Discourse sites are not recognized when creating an account or logging in after a manual addition

### ISSUE THREAD

**Issue by wsw70** [bitwarden/browser#1084]
Sites based on [Discourse](https://discourse.org/) are not recognized by the Chrome extension (Chrome 79, extension 1.41.0) when
- creating a new account: after filling in the login and password, and submitting - BW does not recognize that a new site was used (and does not pop up the "do you want to remember this site" button)
- logging into the newly created account (same as above).

After adding the site manually, it is correctly recognized (I can use BW to fill in the login and password)

The site I last witnessed that on is the Go forum (https://forum.golangbridge.org/) but I saw this behaviour on all Discourse-based sites.

**Comment by kspearrin** [comment]
I looked into this a while back and I could not figure out a good way to detect these actions from those forms.

**Comment by Hinton** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
