### ISSUE TITLE
Bitwarden Safari extension asking for master password despite enabling PIN option

### ISSUE THREAD

**Issue by pavankjadda** [bitwarden/browser#1086]
Bitwarden Safari extension asking for master password despite enabling PIN option with 30 minutes timeout. Sometimes it locks out immediately (before 30 minutes). However when I click on 'Lock Now' it asks for PIN as expected. I am using Safari extension version **1.42.0**

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1021
