### ISSUE TITLE
Chrome extension: Bitwarden offered to save UPPERCASE EMAIL as a separate account

### ISSUE THREAD

**Issue by yegle** [bitwarden/browser#1087]
Some website (in this case, marriott.com) the password change form will contain a text input field with upper case email address (MYEMAIL@GMAIL.COM) alone with the fields to enter current and new passwords.

It looks like Bitwarden will prompt if I want save MYEMAIL@GMAIL.COM as a new account when I attempt to change password, despite I have myemail@gmail.com already in my vault.

**Comment by kspearrin** [comment]
Fixed in the next version. Thanks.

**Comment by yegle** [comment]
That was quick, thank you!
