### ISSUE TITLE
It always thinks citi.com password is "a"

### ISSUE THREAD

**Issue by jaymzh** [bitwarden/browser#1088]
When logging into citi.com it asks if you want to update the password and then saves "a" as the password (even though I used bitwarden to login and the password didn't change), every time.

**Comment by jaymzh** [comment]
This is similar to #1060 ... But slightly different in that it isn't saving starred-out password.

**Comment by andrewkr** [comment]
What browser and OS are you using?

I'm on Mac OS X 10.13.6 with Safari Version 13.0.4 (13608.4.9.1.4) and I don't experience that problem.

**Comment by jaymzh** [comment]
Chromebook. I'll try a few different browsers tomorrow and report back.

**Comment by jaymzh** [comment]
OK, so it turns out it seems to be the login URL that was bookmarked. If you go to:

https://www.citi.com/credit-cards/citi.action

and login, it seems to happen. I can repro this in:

Chrome 79.0.3945.86 on a Chromebook
Firefox 69.0.2 on Ubuntu Linux 18.04

but if I just login from citi.com, then I don't have this issue.

**Comment by PinkDev1** [comment]
I tried to replicate the issue on Edge, but no "Do you want to update the password?" dialogue appeared, and my stored password stayed the same.
INFO:
Microsoft EdgeHTML 18.18363
Microsoft Edge 44.18362.387.0
Bitwarden 1.39.4
OS:
Windows 10 home
Version: 1909

Try deleting the account in Bitwarden and adding it again. 
If it doesn't work, then maybe you used Special Characters / Unicode weird letters / Emojis in the password/username field wich _citi.com_ didn't support; And so, your password/username was "sanitized" (as to not to corrupt the database with data it doesn't know how to handle) and the actuall password that was send, is different than the one you have stored in Bitwarden; Maybe Bitwarden detects this and asks you if it should "store the new password".

I've had it happen to me a couple of times, when I was creating an account in an old Linux forum wich didn't support special characters.

@jaymzh, if none of the above works, can you post a screenshot of how you have your _citi.com_ accout stored in Bitwarden? (With your password hidden of course)

**Comment by PinkDev1** [comment]
<h2>UPDATE: I WAS ABLE TO REPLICATE THE ISSUE </h2>

_Step by step_ guide on how to replicate this:

**1 - Add login credentials to Bitwarden with the following data:**
NAME: %ANYTHING%
USERNAME: %ANYTHING%
PASSWORD: %ANYTHING%
URI 1: _https://www.citi.com/credit-cards/citi.action_
where "%ANYTHING%" can be any text.

**2 - Try to login to _https://www.citi.com/credit-cards/citi.action_ with any credentials**
    Pretty straight forward. Go to the said URL, and try to login with any credentials. It doesn't matter if it's valid or invalid credentials.
    After you're logged in/declined to log in, you'll be redirected.

**3 - Go back to _https://www.citi.com/credit-cards/citi.action_**
**4 - The "Should Bitwarden remember this password for you?" dialogue pops up**
**5 - Click "Yes, Save Now"**
**6 - A new account will be added to bitwarden with the data modified as follows:**
    The USERNAME you used to login in _step 2_ will have all of it's characters replaced with asteriscs, except for the first and last 2 letters.
    **The PASSWORD will have been replaced with the letter "a"**

**Comment by jaymzh** [comment]
Nice work @PinkDev1, thanks for spending time on the repro!

**Comment by patchbank** [comment]
Because it wasn't mentioned here: I guess this is because citi.com actually displays 5 different password fields _before_ the password field used by the user. While they're not specificly hidden and just moved out of the viewport, I imagine it to be kind of tricky to add detection for something like this.

I've checked it on this site:
https://online.citi.com/US/login.do
![image](https://user-images.githubusercontent.com/6287093/83323063-8d53ed00-a25c-11ea-8102-3dd1a3d2f6a0.png)

The highlighted line is the password field which is actually used.

**Comment by jaymzh** [comment]
wow, nice find @patchbank . That said, it feels like `aria-hidden="true"` is a good indication these should be ignored.

**Comment by andrewkr** [comment]
I think that this is a separate issue, but I'm mentioning it here just for reference at the moment. Or did I do something wrong?

On citi.com.au, I tried to login on my phone (iOS 12.4.7) and BW filled in the account number from my Debit Card (not my account number) and the password filled in was the 3 digit check number on the back of the card. That's what alerted me to a problem. Even without any requirements imposed by an organisation, I would never have a password which was only three characters long!

If you need me to open a new issue, please let me know. I can copy all of this to a new issue. And I can delete this, if required.

**Comment by jaymzh** [comment]
Either this was fixed or they changed their site enough to not trigger it. Closing, thanks.
