### ISSUE TITLE
doesn't prompt to save password on venus.com

### ISSUE THREAD

**Issue by jaymzh** [bitwarden/browser#1089]
While walking my mother through using Bitwarden this weekend, she signed up for an account on venus.com and used BW to generate a password, but when she created the account, it did not offer to save the password for her.

Chrome 79.0.3945.86 on a Chromebook

**Comment by kspearrin** [comment]
This is because this website uses ASP.NET WebForms which has a unusual wrapping form around the entire page rather than the actual login form. This makes detection difficult. I don't have a fix at the moment.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known issue that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this post: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
