### ISSUE TITLE
misunderstands password confirmation on wayfair.com

### ISSUE THREAD

**Issue by jaymzh** [bitwarden/browser#1090]
When changing password on wayfair.com, and generating a new password in Bitwarden, and then asking BW to fill in the pw fields, it puts the address in `password confirm` box.

Chrome 79.0.3945.86 on a Chromebook

**Comment by kspearrin** [comment]
I am not able to reproduce. Whenever I autofill the password into the change password box, I see it autofill the password in all 3 password input fields on the page.

**Comment by djsmith85** [comment]
Hi @jaymzh, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
