### ISSUE TITLE
Inactive 2FA Report - NOT WORKING

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/browser#1091]
I am Bitwarden **Premium** user and if I start the **Inactive 2FA Report** then I get the message:
> **GOOD NEWS**
> No websites were found in your vault with a missing two-factor authentication configuration.

In my vault I have the following **popular websites** stored that all support 2FA, but I have **no 2FA Authenticator Key stored** in Bitwarden:
- **GitHub** (https://github.com/login)
- **Paypal** (https://www.paypal.com/de/signin)
- **Amazon** (https://www.amazon.de/ap/signin?ie=UTF8&clientContext=.....) *truncated*
- **Discord** (https://discordapp.com/login)
- **Ashes of Creation** (https://accounts.ashesofcreation.com/login)
- **Facebook** (https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=110)
- **Star Citizen** aka **Roberts Space Industries** (https://robertsspaceindustries.com/)

All of them are on the **Two Factor Auth List** (https://twofactorauth.org/).
I guess you use the Two Factor Auth List in Bitwarden?

In my opinion Bitwarden should report these websites in the **Inactive 2FA Report**.
So is this feature currently broken?

**Comment by OLLI-S** [comment]
Also these **popular websites** (all on the Two Factor Auth List) **are missing**:
- **Paypal** (https://www.paypal.com/myaccount/security/)
- **Amazon** (https://www.amazon.de/a/settings/approval)
- **Discord** (https://discordapp.com/channels/@me)
- **Ashes of Creation** (https://accounts.ashesofcreation.com/profile)
- **Facebook** (https://www.facebook.com/security/2fac/settings/)

These websites are also missing, but are **not on the the Two Factor Auth List**:
- **Allianz Connect** (https://connect.allianz.com/)
- **Star Citizen** (https://robertsspaceindustries.com/account/security)

So is this feature currently broken?
I guess you use the **Two Factor Auth List** (https://twofactorauth.org/) for getting the data...

**Comment by kspearrin** [comment]
DUplicate https://github.com/bitwarden/web/issues/422
