### ISSUE TITLE
Vivaldi 2.10: Shortcut for autofill logins doesn't work anymore.

### ISSUE THREAD

**Issue by PoooMukkel** [bitwarden/browser#1092]
After upgrading Vivaldi browser to version 2.10.1745.21 (Stable channel) (64-Bit) shortcut CTRL+SHIFT+L doesn't work anymore to autofill login fields. You have to click the extension and select the login to fill in.
Because of this bug I actually stay with version 2.9 and don't want to upgrade. Is there a solution to get shortcut to work again?

**Comment by kspearrin** [comment]
This is a bug with Vivaldi itself. I sent them a bug report.

Closing since it is an upstream issue.

**Comment by PoooMukkel** [comment]
Sorry to ask again for this problem. There is a new Vivaldi update released (2.10.1745.26) but still this problem isn't solved. Do you have a bug id or something else which I can use to ask in the Vivaldi forum?

**Comment by jamescridland** [comment]
In case someone else sees this in Google and wants to know how to fix it (it's still an issue in June 2021), here's how to fix it:

* Right-click the Bitwarden extension icon, and click "Manage Extensions"
* Click the ☰ menu and choose "keyboard shortcuts"
* Change "Auto-fill the last used login" to be "Global" instead of just "in Vivaldi"

Job done.

**Comment by dmckee-ebsco** [comment]
> In case someone else sees this in Google and wants to know how to fix it (it's still an issue in June 2021), here's how to fix it:
> 
> * Right-click the Bitwarden extension icon, and click "Manage Extensions"
> * Click the ☰ menu and choose "keyboard shortcuts"
> * Change "Auto-fill the last used login" to be "Global" instead of just "in Vivaldi"
> 
> Job done.

@jamescridland This works, but it will also prevent the same keybinding from working in other applications. An example is: when using VS Code, `ctrl+shift+L` is used to 'select all instances of highlighted text' but this will fail if `ctrl+shift+L` is set to Global within Vivaldi.

**Comment by Gortus** [comment]
> This is a bug with Vivaldi itself. I sent them a bug report.

As noted, the workaround isn't ideal. Can you provide the bug id so we can check its progress with the Vivaldi team?

**Comment by rayat-amperity** [comment]
Any updates? Could we get a bug ID?

**Comment by johnkitchen** [comment]
This still isn't fixed. Can we get a bug ID please?

**Comment by synthercat** [comment]
We need this fixed!

**Comment by majal** [comment]
Vivaldi-Chromium [doesn't seem to have a public bug tracker](https://forum.vivaldi.net/topic/21605). Instead, they encourage users to [file a new bug report to add weight](https://forum.vivaldi.net/post/79930) to a bug.

I just filed one, and there was no bug tracker page link given. If you like, you can also go ahead and file another bug report here: https://vivaldi.com/bugreport/
