### ISSUE TITLE
[Edge] Autofill hotkeys not working

### ISSUE THREAD

**Issue by PinkDev1** [bitwarden/browser#1093]
I'm trying to use the **shortcut keys** for edge but nothing happens. I've tried with CTRL + \  and with CTRL + 9  (as specified in [Bitwarden's help page](https://help.bitwarden.com/article/auto-fill-browser/) ) **_but none seem to work_**. I've checked and Bitwarden does detect that I'm in a website it has credentials of (a number with the detected credentials matching the open website appears on the down right corner of Bitwarden's extension logo).

**INFO:**
Microsoft EdgeHTML 18.18363
Microsoft Edge 44.18362.387.0
Bitwarden 1.39.4
**OS:** 
Windows 10 home
Version: 1909

**Comment by kspearrin** [comment]
Go to `chrome://extensions` and verify that the shortcuts are set for the Bitwarden extension.

**Comment by PinkDev1** [comment]
I don't think you read correctly xp. I'm using **Microsoft Edge Browser**, not google chrome.

**Comment by kspearrin** [comment]
Is this the new chromium-based edge browser or old edge?

**Comment by dj-nitehawk** [comment]
@PinkDev1 try a differnt key combination by changing the key assignments by going to:
`edge://extensions/shortcuts`

**Comment by PinkDev1** [comment]
@kspearrin Just the "old" regular Edge that comes preinstalled with Windows 10.
@dj-nitehawk Am I supposed to put that in the Address Bar? if so, it only gives me the option to **search** for that string with my default search engine :/

**Comment by rosystain** [comment]
> @PinkDev1 try a differnt key combination by changing the key assignments by going to:
> `edge://extensions/shortcuts`

'chrome://extensions/shortcuts' is right.

**Comment by cscharf** [comment]
Due to inactivity we're closing this issue. If it remains a problem please feel free to re-open it and let us know. It would also appear there are some known issues with Microsoft Edge (old edge as indicated by the version listed) where we would recommend trying with the new Microsoft Edge Chromium browser.
