### ISSUE TITLE
No easy way to get to self-hosted vault

### ISSUE THREAD

**Issue by STaRDoGG** [bitwarden/browser#1094]
I host my bw vault via a docker container, and then point to it in the extension. When I want to load up the page of my vault, there's nowhere in the extension to get to it.

There's a button labeled "my vault", but that just shows all items in the vault, within the extension, and there s a menu item on right-click labeled "Bitwarden - Free Password Manager", but that just takes me to the official bw homepage.

This seems like a bit of an oversight, to not add a link somewhere to go to the web ui of your own vault?

**Comment by kspearrin** [comment]
There is a link under settings to open the web vault.

**Comment by NZSmartie** [comment]
First time using the firefox extension, My first instinct was to manage the extension within Firefox's extension manager:
![image](https://user-images.githubusercontent.com/1032029/87734585-2946b180-c827-11ea-9c84-c46e3cb5efc5.png)

Seeing your comment didn't make any sense to me as there's no indication of custom setting panel in the extension itself without first being familiar with the extension.
When trying to log in, there's no hint or help for users with a self hosted vault. This makes for an unpleasant first time user experience.

![image](https://user-images.githubusercontent.com/1032029/87734876-f355fd00-c827-11ea-9cd9-d3a1318b14b8.png)

May I suggest:
- adding a button on the login dialog to configure a self hosted server url
- Adding a link to navigate the user to the settings panel to configure the self hosted server.
