### ISSUE TITLE
Passphrase generator GUI wraps mid-word instead of on a separator

### ISSUE THREAD

**Issue by Atemu** [bitwarden/browser#1096]
When you generate a passphrase that's sufficiently secure, it gets long enough to need to be split into multiple lines in the GUI.  
The GUI splits the lines in the middle of a word most of the time (i.e. `anima\nl`) which looks ugly and can be confusing. This happens both in the generate screen and the history.   

It'd be better if it split the passphrase after a word separator.

**Comment by naokiri** [comment]
Sounds like an `overflow-wrap` css change only.
