### ISSUE TITLE
Firefox Randomly Logging User Out

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#110]
I've noticed a few times over the past couple weeks that I've been logged out of the extension for no apparent reason. I've only seen this in Firefox. Requires more investigation as to why this is happening. Possibly more logging.

Anyone else seen this?

**Comment by Primokorn** [comment]
I'm on Firefox 52.0 several hours a day and I've never seen this issue.
bitwarden is set to be locked every 4 hours, though.

**Comment by Anaithsol** [comment]
I actually just experienced this for the first time this past Sunday with Firefox. I was fully logged out despite having Bitwarden set to never lock in the settings menu.

There was a very annoying login/logout hiccup back when the addon was still being run through Mozilla's approval process, but that was quickly rectified with an update after the initial report. This current issue isn't remotely as prevalent judging from what I've seen so far.

**Comment by globau** [comment]
i'm on firefox all day, every day.  never seen a premature logout.

**Comment by kspearrin** [comment]
I think I have identified a possible issue. The fix was pushed to the server over the weekend so if anyone sees this happen again please let me know.

**Comment by kspearrin** [comment]
I believe this has now been resolved.
