### ISSUE TITLE
Safari: Autofill function broken within pinned tabs

### ISSUE THREAD

**Issue by tech509201941** [bitwarden/browser#1100]
**Environment**
MacOS 10.15.2
Safari Version 13.0.4 (15608.4.9.1.3)
Newest bitwarden extension

**Issue**
If a tab is "pinned" in safari, it is impossible to autofill any forms within these tabs:
"Unable to auto-fill the selected item on this page. Copy and paste the information instead."

If a tab gets unpinned then the autofill functions magically works again until the tab gets into pinned mode.

**Comment by kspearrin** [comment]
Dupe https://github.com/bitwarden/browser/issues/1018
