### ISSUE TITLE
Autofill does not work from the context menu

### ISSUE THREAD

**Issue by nijel** [bitwarden/browser#1102]
The [recommended workaround](https://help.bitwarden.com/article/extension-wont-load-in-private-mode/) for #136 is to use auto fill from the context menu. Unfortunately that does exactly nothing in my case. It's not related to the private mode, it doesn't work anywhere I tried. The auto fill from toolbar popup and sidebar works just fine (in non private mode).

Maybe I was just unlucky and I'm testing it only sites where it doesn't work (like mentioned https://github.com/bitwarden/browser/issues/204). For example, I've tried https://github.com/login or https://gitlab.com/users/sign_in.

Any hints how to debug this? I'm using Firefox 71.0 and Bitwarden 1.41.0.

**Comment by kspearrin** [comment]
I just tested this on Firefox 71 on macOS and the autofill options on the context menu worked just fine in private mode on github.com/login. Is your vault unlocked?

**Comment by nijel** [comment]
It doesn't work even in normal mode for me. My vault is unlocked and autofill from sidebar or toolbar works fine.

After some testing, it seems to be related to other Firefox addons. When I disabled LanguageTool it started to work, but enabling it again didn't break it. So for now it works, but I'm not really sure what fixed it.

**Comment by haluzpav** [comment]
I have the same issue. Even with all other addons disabled.

Bitwarden is logged in. Autofill from addon popup works, but not from context menu. That's quite annoying in private windows. 

Firefox: 75.0, Bitwarden: 1.43.4. It's been broken for a few months for me.
