### ISSUE TITLE
Autofill does not work for https://www.citibankonline.pl/apps/auth/signin/

### ISSUE THREAD

**Issue by fwsl** [bitwarden/browser#1103]
Hello
Autofill does not work for https://www.citibankonline.pl/apps/auth/signin/

Browser: Desktop Opera 65 and Opera 66
It does work correctly on android
Cheers

**Comment by djsmith85** [comment]
Hi @fwsl thank you for opening this issue. If this is still an issue, could you please add details to #1621.
Closing this issue now.
