### ISSUE TITLE
Autofill does not work for Dynatrace

### ISSUE THREAD

**Issue by Mart124** [bitwarden/browser#1104]
Hi,
Autofill does not work for Dynatrace.
https://sso.dynatrace.com/
Don't know if it's related to the 2 steps login form.
What is strange is that E-mail is not filled-up, but password is.
Thank you 👍

**Comment by Greenderella** [comment]
A custom field (https://bitwarden.com/help/article/custom-fields/) for the username should solve this issue:
![image](https://user-images.githubusercontent.com/5418577/100255247-925fd380-2f43-11eb-9eae-e41bb7ac3005.png)

**Comment by Mart124** [comment]
That's right, a pity I did not try this by myself...
Thank you for the workaround @Greenderella 👍
