### ISSUE TITLE
Autofill does not work without Password

### ISSUE THREAD

**Issue by Mart124** [bitwarden/browser#1105]
Hi,
Let's assume a web portal asking for username only (then redirecting to a SSO for example).
I then have a Bitwarden login item with _Username_, but without _Password_.
Like this, autofill fails.
If I save a fake _Password_ into the Bitwarden item, autofill will work.

Could we then make autofill to work even if there's no _Password_ in the Bitwarden item ?

Thank you 👍

**Comment by kspearrin** [comment]
You can achieve this with custom fields.

**Comment by Mart124** [comment]
Yes you're right, don't know why I did not think about this :)
Thank you for your quick reply 👍
