### ISSUE TITLE
Brave Browser: FIDO U2F Error 4 with Yubikey 4 series

### ISSUE THREAD

**Issue by neukams** [bitwarden/browser#1109]
Hi,

I ran in to an issue using my Yubikey series 4 for 2fa on Bitwarden today, 1/15/2019. Brave browser version v 1.2.42.

**Steps to Recreate**
1. Click Bitwarden Plugin in Brave
2. Click 'Login'
3. Enter email and master password 

**Bug**
Result: The plugin will immediately throw repeating errors 'Error 4: U2F Error'. These errors don't stop popping up, they appear ever half second and keep cycling through, regardless of whether the key is plugged in or not.

**Other Scenarios**
I tested the plugin with the chrome browser, thinking that it may have been my recent Yubikey 2FA FIDO U2F setup, but the chrome browser extension worked fine logging in with my yubikey.

**Context**
I recently obtained a premium subscription (last couple days), and set up 2 yubikeys I have for FIDO U2F. (These are old yubikeys, probably series 4 as best as I can tell).

During the setup process, I initially set up both Yubikeys for Yubico OTP 2FA. I then decided to switch methods, set each up yubikey up for Fido U2F, and then deleted the Yubico OTP keys.

![fido u2f bitwarden brave error](https://user-images.githubusercontent.com/59550102/72467989-269cce00-37aa-11ea-8089-39489d322301.JPG)

**Comment by kspearrin** [comment]
I was not able to reproduce the issue. I just installed the latest Brave on Windows 10 and logged into my user account in the extension using my U2F key.

**Comment by fhalim** [comment]
I encounter the same error with my [YubiKey Security Key NFC](https://www.yubico.com/product/security-key-nfc-by-yubico/) which were registered as FIDO U2F keys on the vault. I can reproduce this on all Chromium based browsers. Older keys work fine.

**Comment by clayadams5226** [comment]
I was unable to reproduce this in Production. However I did run across it in our dev environment while testing Chrome. I'll see if I can get any logs that may help.

**Comment by danflory** [comment]
Same error for me, I do have both OTP and U2F set up, so am able to "user another 2 factor method" and get on.
