### ISSUE TITLE
Bitwarden detects logins from the new Microsoft Edge as Chrome

### ISSUE THREAD

**Issue by mackaaij** [bitwarden/browser#1110]
Minor detail of course and it's great the extension already works but the email notifications for a new login state:

Subject: New Device Logged In From Chrome Extension
Body: Your Bitwarden account was just logged into from a new device.
[...]
Device Type: Chrome Extension
[...]

I actually got two email messages, one mentions Chrome, the other Chrome Extension.

**Comment by mudnug** [comment]
I would guess many Chrome-based browsers are also impacted by this, then.

**Comment by mudnug** [comment]
#1131 related
