### ISSUE TITLE
"Failed to fetch" when login from Edge extension to self-hosted environment

### ISSUE THREAD

**Issue by pachulo** [bitwarden/browser#1116]
We self-host Bitwarden and our Edge users are getting "Failed to fetch" errors when trying to log in through the extension.

The have properly configured the environment on the "Self-hosted environment" page.

We are using a wildcard certificate and everything works fine when they use Chrome & Firefox extension...any ideas?

Thanks!

**Comment by kspearrin** [comment]
Can users visit your web vault in Edge without cert errors?

**Comment by pachulo** [comment]
Yes, they can access the Web vault without problems.

**Comment by kspearrin** [comment]
Is this using "old" edge or the new Chromium edge?

**Comment by edermi** [comment]
I'm having the same problem, "old" edge (Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18363).

Regular desktop app, Chrome Plugin and Website work fine (tested using Edge, Chrome and Firefox)

**Comment by pachulo** [comment]
We did some more tests and it's working for a user with:
```
Edge 44.17763.831.0 (EdgeHTML 18.17763) 
```
but it's failing for users with:
```
Edge 44.18362.449.0 (EdgeHTML 18.18362)
```
So I'm not really sure if something broke on the latest updates...

**Comment by superusercode** [comment]
are they using the version from the MS addon store? looks like it might be behind. I also believe that the version on the MS addon store is the version that was previously used on old edge (rather than the native chromium version) and as a result has errors.

CWS:
![image](https://user-images.githubusercontent.com/23001825/72944512-1a36e900-3d47-11ea-8b1b-62b2edda51eb.png)
Edge Addon:
![image](https://user-images.githubusercontent.com/23001825/72944528-2458e780-3d47-11ea-87f7-7ddf8014bcc5.png)

**Comment by pachulo** [comment]
The users for which this doesn't work and the one that got it working (but they have different versions of Edge) are using the same version of the plugin: `1.39.4` which, to mee, looks a little old...isn't it @kspearrin ?

**Comment by edermi** [comment]
Our users have the store version, they are not allowed to install anything apart white listed store applications.

**Comment by pachulo** [comment]
> Our users have the store version, they are not allowed to install anything apart white listed store applications.

Is there any other way to install it on Edge, apart from getting it from the store?

**Comment by edermi** [comment]
I don't know, I was just referring to your comment as I assumed there is another way to get a newer version.

If this is a version issue, is it possible to push the latest release to the Store @kspearrin?

**Comment by pachulo** [comment]
Any news on this @kspearrin ?

**Comment by kspearrin** [comment]
Unfortunately, no. We are no longer proving support or updates for the old Edge. The newer Chromium-based Edge is all we will support going forward.

**Comment by superusercode** [comment]
@kspearrin It appears that the version on microsoft edge has still not been updated. Is there any holdup in the review process?
![image](https://user-images.githubusercontent.com/60588434/74619159-98966900-5102-11ea-9cee-87b1308a1a92.png)

**Comment by edermi** [comment]
The new Edge browser has not been rolled out completely by Microsoft, especially for business customers this is still going to take some time. Dropping support within days after the first Edge-Chromium rollout stage while leaving the old, broken extension unmaintained is not very supportive, independently of on-prem or cloud is used.

**Comment by djsmith85** [comment]
Closing this, as we no longer support MS Edge pre-Chromium and Microsoft has also dropped support for it
