### ISSUE TITLE
Save password dialog buttons misaligned

### ISSUE THREAD

**Issue by WolfspiritM** [bitwarden/browser#1118]
Hi,

When I'm using the extension in a browser that has multiple languages installed and set the browser to use german while at the same time keeping german sorted below for example english, then the Bitwarden bar is looking wrong. The reason is that the extension uses "window.navigator.language" to set the body to "lang-en" which seems to be the topmost language but it's not the language chrome uses for translation for i18n. So while the body class is "lang-en" the text itself is german and too big for that space.

![image](https://user-images.githubusercontent.com/5904171/72888517-fd31f400-3d0d-11ea-96cb-957a8a3f2824.png)

Workaround is to move german to the top of the languages used:

![image](https://user-images.githubusercontent.com/5904171/72888616-2fdbec80-3d0e-11ea-8e3d-75d449b3ebfb.png)

I think the popup should also use the chrome api to detect the language but I'm not sure if that's possible as it's in the context of the page and not the extension.

Seems to be similar to #926

**Comment by kspearrin** [comment]
Should be resolved with https://github.com/bitwarden/browser/commit/70eb421e7a38b7de4fff5156dd557bbe4bbd5f4f
