### ISSUE TITLE
Firefox extension never syncs

### ISSUE THREAD

**Issue by rodimius** [bitwarden/browser#1119]
Mac OS X 10.14.6
Firefox 72.0.2 (64-bit)
Bitwarden extension 1.42.2

Clicking "Sync vault now" reports "Sync Successful" in a toast, but the last sync remains at "Never" and no items are shown in my vault.
![image](https://user-images.githubusercontent.com/8717/72891818-01a9dd00-3d0d-11ea-8aee-1dd1b24e3b5b.png)

Console logs show the following two entries repeated:
```
Failed to persist storage for principal: moz-extension://32fc85ea-fa16-c445-9590-aad783eda741
callback resource://gre/modules/ExtensionStorageIDB.jsm:741
```
```
Unchecked lastError value: Error: An unexpected error occurred
get browserStorage.service.ts:25
```

**Comment by kspearrin** [comment]
Have you tried logging out and back in to see if that fixes anything?

**Comment by rodimius** [comment]
Yes. No change.

**Comment by kspearrin** [comment]
What does the network tab show?

**Comment by rodimius** [comment]
I cleared the network tab and pressed sync, there was one request
```
Request URL:https://api.bitwarden.com/sync
Request method:GET
Remote address:104.26.11.153:443
Status code:
200
```
The response begins:
```
{"Object":"sync","Profile":{"Object":"profile","
```
and looks like it contains my encrypted vault information.

**Comment by kspearrin** [comment]
Maybe try reinstalling the extension? Something sounds corrupt.

**Comment by rodimius** [comment]
Update on this, I finally got around to investigating and it was an instance of this firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=944918
You can check if it's affecting you here https://firefox-storage-test.glitch.me/
Resolved by deleting folders in <your firefox profile>/storage/{default,permanent,temporary}/

I'll close now.

**Comment by starxg** [comment]
look at : https://github.com/bitwarden/browser/issues/1076#issuecomment-651499203
