### ISSUE TITLE
UI issues with Vimperator

### ISSUE THREAD

**Issue by xczv** [bitwarden/browser#112]
In vimperator, I am using the `set gui=nonavigation` setting, which hides most of my user chrome. I have the bitwarden icon in my tab bar, which is the only piece of the user chrome I need.

Clicking on this doesn't do anything in this case. The bitwarden menu just doesn't pop-up.

When `set gui=all`, the icon seems to work just fine, but that's not what I want. Not sure if it's an issue with vimperator specifically, but I don't see why hiding my userChrome should result in that menu breaking.

I'm not sure if this is intended, but the context menu item `bitwarden>Auto-fill>Vault is locked.` doesn't do anything. Would be nice if I could just interact with it this way, if I really have to use my mouse

**Comment by kspearrin** [comment]
Can you just use the bitwarden hotkey? Default is `ctrl` + `shift` + `Y` but it can be customized from browser settings. In chrome this is in `chrome://extensions` at the bottom. I'm not sure how to change it in Firefox.

**Comment by xczv** [comment]
I've just re-enabled bitwarden, set vimperator to ignore all keys, and tried it. This hotkey doesn't seem to work, and it could be a vimperator thing. I'll look into it and report back.

**Comment by kspearrin** [comment]
@xczv This is Firefox right?

**Comment by xczv** [comment]
Yes, sorry for not mentioning that earlier.

**Comment by kspearrin** [comment]
I'm not really sure how to debug the UI issue. I would say it seems to be some issue with the Vimperator addon since we don't really control how our icon is displayed or activated (Firefox handles this automatically).

The only thing I can suggest for now is to use the `ctrl + shift + Y` hotkey. Firefox doesn't allow changing the binding like Chrome does so if you have something that is conflicting with that binding you'll need to remove it.

**Comment by kspearrin** [comment]
Closing for now.

**Comment by xczv** [comment]
I think I understand the issue a little better. The hotkey `ctrl+shift+Y` seems to only work if the icon is visible on the userChrome, since all it does it bring up the menu that appears when you click on it anyway. Not sure if it's a big, but it feels like it's worth reporting.

I disabled vimperator, and tried the hotkey when it was both on my userChrome, and when it wasn't. It only works for me when the button is visible on of my toolbars.

**Comment by kspearrin** [comment]
All we do is define the hotkey (see https://github.com/bitwarden/browser/blob/master/src/manifest.json#L84). If it isn't working when Vimperator is enabled, it still seems like an issue with Vimperator. There isn't really anything I can change to accommodate that.

**Comment by xczv** [comment]
Er-- but it isn't working when Vimperator is disabled, either.

**Comment by kspearrin** [comment]
Ok, I see. Yes, I can also confirm that if you remove the icon from the Firefox UI the hotkey no longer works as well. This is just a Firefox thing then.

**Comment by mhammond** [comment]
> This is just a Firefox thing then.

*sob* - I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1351928
