### ISSUE TITLE
Please bring the chromium edge addon in line with the chrome web store version

### ISSUE THREAD

**Issue by superusercode** [bitwarden/browser#1120]
CWS:
```
Version
1.42.2
Updated
January 13, 2020
```
Edge addon (ported from the EdgeHTML version by microsoft):
```
Version
1.41.0
Updated
December 6, 2019
```

Microsoft claims that they have handed over extension control back to the developers. It seems that people are experiencing issues related to the version on the edge addon store over sideloading from the chrome web store.

**Comment by superusercode** [comment]
https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/

## Transitioning your existing extensions to Chromium
As we move towards the general availability of the new Microsoft Edge on January 15th, 2020, we will no longer accept new submissions for Microsoft Edge Legacy (EdgeHTML-based) extensions after December 17th, 2019. We will continue to accept updates for your existing extensions.

We recommend you prioritize building new extensions for the new Chromium-based Microsoft Edge, and continue to support your existing EdgeHTML-based extensions to ensure a quality experience for active users.

Developers who have given consent for Microsoft to migrate their EdgeHTML extension listings to the new Microsoft Edge should begin to see their extensions available in the new Addons store experience in Microsoft Edge. If you publish an EdgeHTML extension and have not received any communication regarding its migration or are unsure of its status, please contact us at ExtensionPartnerOps@microsoft.com.

If you have already received a confirmation from us regarding migration, we encourage you to log on to the Partner Center Developer Dashboard to validate your access to the extension, and verify whether you can update it. Once the migration is complete, ownership and management will be completely transferred to you, and Microsoft will not be responsible for updating or maintaining your extension.

**Comment by kspearrin** [comment]
I have submitted the 1.42.2 update. It is in review and should be available soon.
