### ISSUE TITLE
Google Chrome Extension doesn't sync

### ISSUE THREAD

**Issue by NLLucifer** [bitwarden/browser#1122]
When i edit something on my own hosted server of in the browser Extension (Chrome) it doesn't sync. I have to manually sync them.

**Comment by NLLucifer** [comment]
Versions:

Self hosted: V2.11.0 (docker)
Extension: v1.42.2

**Comment by kspearrin** [comment]
Are you using a proxy?

**Comment by NLLucifer** [comment]
Nope.

**Comment by NLLucifer** [comment]
It looks like reinstalling did the trick
