### ISSUE TITLE
[Edge] Can't export vault

### ISSUE THREAD

**Issue by PinkDev1** [bitwarden/browser#1123]
Supposedly, the browser extension is able to export your vault in the scenario you wanted to migrate accounts for any reason. However, when I go to settings -> Tools -> Export vault it just opens up https://help.bitwarden.com/article/export-your-data/

INFO:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
Bitwarden 1.39.4
OS:
Windows 10 home
Version: 1909

**Comment by kspearrin** [comment]
"old" edge does not support saving files from extensions. You should consider updating tot he "new" chromium-based edge, which would support this feature.
