### ISSUE TITLE
U2F browser "remember me" doesn't

### ISSUE THREAD

**Issue by jikamens** [bitwarden/browser#1125]
I am using a YubiKey with the Chrome Bitwarden extension.

I am frequently asked to re-authenticate with my YubiKey even though I check the "remember me" checkbox every single time.

One scenario: when I change my master password and the extension therefore makes me log in again, I have to do 2FA authentication as well.

I am not sure what the "remember me" checkbox actually does, i.e., when it is paid attention to, but I would not expect to have to re-do 2FA after checking it just because my master password has changed.

**Comment by kspearrin** [comment]
This is expected. Changing your master password or deauthorizing sessions will require you to re-authenticate 2FA, no matter if you selected "remember me" on it previously or not.
