### ISSUE TITLE
Autofill for tsp.gov fills password twice instead of account number and password

### ISSUE THREAD

**Issue by tony971** [bitwarden/browser#1126]
It works correctly if you hit the "show" button for the account number.

**Comment by kspearrin** [comment]
This is because the account number is marketed as type password until you show it. You can use custom fields to target the account number field with the correct value.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
