### ISSUE TITLE
Localization issue: Missing plural form

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/browser#1127]
There is missing plural form in your string. Text like "text(s)" looks bad. In many languages translators need to have one, few (2-4) and also many form.

See grammar rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

https://github.com/bitwarden/browser/blob/97a38b000b1aa378e18d3812157a0b0ce84966cd/src/_locales/en/messages.json#L1115

**Comment by mKoonrad** [comment]
@mKoonrad Issue still present

**Comment by dwbit** [comment]
Thanks @mKoonrad, we use [Crowdin](https://crowdin.com/profile) for translation conversations, and everyone is free to contribute or vote on correct usage there.
