### ISSUE TITLE
Autofill input got instantly deleted

### ISSUE THREAD

**Issue by Biepa** [bitwarden/browser#1134]
I can't use the auto fill feature on the site:
https://login.splunk.com

The Plugin fills out both fields and then both fields are cleared a second later.
So not possible to login.

Using Version: 1.42.2 with Firefox Version 72.0.2
I'm happy to provide more information, if needed and if it's a bitwarden problem.

**Comment by kspearrin** [comment]
I am not sure why the website is doing this. It seems like Splunk has some weird code that removes automated methods of inputting data into the text fields.

**Comment by Biepa** [comment]
Okay. But thanks for checking it out.
