### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by rajib-raiyat** [bitwarden/browser#1138]
#1138
When I login to the browser's extension and go to collect OTP, the login I made becomes logout. As a result, I have to login again with my password and then the extension want OTP again and continue to do so. Later, the first time I log in, the opt that is sent and the OTP in my email is to login the second time.

**Comment by kspearrin** [comment]
I'm sorry, but I do not understand the issue you are describing.

**Comment by balagurusurendar** [comment]
@kspearrin 
I think he set up a two-step Login with an email 

then the problem will be he is not able to enter OTP in extension that sent to the email, while tab switch to check email for OTP.

**Comment by kspearrin** [comment]
Yes, this is a known issue, which is why we offer to pop the extension out to a new window for you if you hit the email OTP step.

**Comment by rajibraiyat** [comment]
@kspearrin 
please fix this as soon as possible.

**Comment by balagurusurendar** [comment]
@rajibraiyat 
you can use the "pop out the window" to fill the OTP rather than waiting for an issue to fix
