### ISSUE TITLE
Safari "Preflight response is not successful" error when loggin into extension

### ISSUE THREAD

**Issue by poldim** [bitwarden/browser#1140]
I used to have the Safari extension working.  Upon opening it recently it prompted me to log in but now I get this error.  I found [someone else that had the same error](https://github.com/dani-garcia/bitwarden_rs/issues/636) but no solution posted.

<img width="782" alt="Image 2020-02-10 11-52-49" src="https://user-images.githubusercontent.com/16869713/74165863-1981cc00-4bfc-11ea-8418-4262ee054aac.png">

![image](https://user-images.githubusercontent.com/16869713/74165972-3fa76c00-4bfc-11ea-888c-93765bfd9094.png)

![image](https://user-images.githubusercontent.com/16869713/74165989-4635e380-4bfc-11ea-9d3f-32eb9643cab0.png)

![image](https://user-images.githubusercontent.com/16869713/74166502-0b807b00-4bfd-11ea-9169-f77907068c16.png)

**Comment by kspearrin** [comment]
Are you using the official Bitwarden server or the community implementation like you linked?

**Comment by amarendra** [comment]
> Are you using the official Bitwarden server or the community implementation like you linked?

I am also facing this. I am using latest and default/official Bitwarden server. Started having the issue just now. Logged out and was able to login back to extension. 

Can't sync → "Sync failed". Can't edit → "Preflight response is not successful". 

Never noticed this before.

**Comment by manojchandrashekar** [comment]
I am having the same issue. Works everywhere except safari.

I am using https://github.com/jcs/rubywarden for the backend.

**Comment by cscharf** [comment]
Preflight issues are generally CORS related. Safari is very strict (now-a-days) from it's App Extensions in pre-authorizing requests (using preflight) against resources which must return applicable CORS headers for allowed domains. Our official server handles (or should handle) this and there have been recent security changes/updates to the same, (see: https://github.com/bitwarden/server/pull/787, and https://github.com/bitwarden/server/pull/800)
