### ISSUE TITLE
"change master password" link should follow server variable

### ISSUE THREAD

**Issue by lewisphil** [bitwarden/browser#1144]
In a self hosted environment, user sets host variable to point to server.  This works as intended for sync. 
Settings->Change master password brings up a pop-up that says 
    
     "You can change your master password on the bitwarden.com web vault. Do you want to visit the 
     website now?"   

In a self-hosted environment, this is not true.  The link directs a user to a site where they potentially don't have an account.   

This pop-up should say, and the link should direct to the users server (in a self-hosted environment) or else to the bitwarden.com server.

**Comment by kspearrin** [comment]
We could just change it to "the bitwarden web vault"

**Comment by lewisphil** [comment]
> We could just change it to "the bitwarden web vault"

yes, as long as the link is changed to the server variable

**Comment by kspearrin** [comment]
What link are you referring to? The button just takes you to our help center article to explain how you can change your master password from the web vault.

**Comment by lewisphil** [comment]
Yes, it looks like that's correct.  But then when the user clicks "web vault" on that page, it then takes you to the bitwarden.com web vault.  
Is it possible to just link to the "https://{my.server.name.here}/#/settings/account" page from the "settings->change master password" pop up?

**Comment by lewisphil** [comment]
Maybe two options on the pop-up:  1. instructions (on the website) or 2. link to change the password.
