### ISSUE TITLE
The copy to clipboard icon looks like paste instead of copy

### ISSUE THREAD

**Issue by kznrluk** [bitwarden/browser#1147]
This 'fa-clipboard' express the button to copy value. But this icon is misleading to pasting.
![スクリーンショット 2020-02-20 15 19 26](https://user-images.githubusercontent.com/29700428/75001480-d26dc380-54a4-11ea-9696-2d206b46cb6b.png)

'fa-clone' Is more suitable.
![ERMryy0VUAAXKox](https://user-images.githubusercontent.com/29700428/75001761-a69f0d80-54a5-11ea-81dc-7bdf7b3702ac.png)

You can find out by doing a search. The pasteboard has a clipboard, but the copy does not.
![スクリーンショット 2020-02-21 12 31 51](https://user-images.githubusercontent.com/29700428/75001973-4bb9e600-54a6-11ea-95bd-ef1b6c015aa0.png)
![スクリーンショット 2020-02-21 12 32 04](https://user-images.githubusercontent.com/29700428/75001977-4ceb1300-54a6-11ea-822c-5fda7aba76b5.png)

I can also send a pull request for this. Please consider.

**Comment by Jipje** [comment]
This issue seems solved, can it be closed?

**Comment by djsmith85** [comment]
@kznrluk Thank you for your contributions. Could you please close this issue, as your PR's have been merged.

**Comment by kznrluk** [comment]
Thank you for pointing this out, it has been closed.
