### ISSUE TITLE
authentication popup not shown - Chrome

### ISSUE THREAD

**Issue by EDWernars** [bitwarden/browser#1148]
When opening a webpage with authentication with username and password. The popup won't be able to show in Chrome and you have only a blank webpage.

When i'm disabling bitwarden the popup is shown and I can login.

Dont know if this issue is only in Chrome, havn't tested in any other browser.

bitwarden extension **not active**
![image](https://user-images.githubusercontent.com/9058229/75036126-6ba2d700-54b1-11ea-8713-fc4b05541cb4.png)

bitwarden extension **active**
![image](https://user-images.githubusercontent.com/9058229/75036175-8c6b2c80-54b1-11ea-9993-4c3fa65324b7.png)

**Comment by kspearrin** [comment]
Do you have a password in your vault for this website?

**Comment by BloatDesginer** [comment]
I am having the same issue, Chrome autofill is prompting for autofill but bitwardern is not please help this is my 2nd day of using bitwardern.

**Comment by EDWernars** [comment]
> Do you have a password in your vault for this website?
I havn't a password registered in bitwarden for this website and I also don't want it. I'm using bitwarden for private use and I have to visit this website for not private use.

**Comment by EDWernars** [comment]
issue is fixed in 1.43.1
