### ISSUE TITLE
Autofill doesn't work for Safari pinned tabs

### ISSUE THREAD

**Issue by fuggum** [bitwarden/browser#1149]
MacOS 10.15.3 / Safari13.0.5 / Bitwarden Application 1.16.6 / Extension 1.42.0

Using the Safari extension if I open a site and select an entry to autofill login details it works fine. If I open the same site and pin the tab first I get the following message in the extension when I try to autofill the login details.  

Unable to auto-fill the selected item on this page. Copy and paste the information instead.  

If I then unpin the tab autofill again works.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/1018
