### ISSUE TITLE
Question on sync behavior / offline usage

### ISSUE THREAD

**Issue by lainy** [bitwarden/browser#115]
Hi, I've been going over the browser extension code and I have a question about syncing:

If I understand correctly, right now `fullSync` will call `syncVault`, which will **replace the local vault with the remote vault** rather than doing a merge. It looks to me like `syncFolders` and `syncLogins` will do a proper merge, but they do not appear to be used.

Adding and editing logins & folders goes through `saveWithServer` on the respective service, which ensures it is synchronized _when you add it_, so merging isn't actually necessary - adding won't succeed unless the PUT or POST succeeds, which ensures the server is always consistent with the client.

Is my understanding correct?
I'm guessing, then, that bitwarden can't be used offline at the present time?

**Side note:** I wanted to personally go over all the browser extension code before using it, and I have to say the code is super clean. Thank you for making it well-structured and easy to follow! 👍

**Comment by kspearrin** [comment]
@lainy 

You are correct about the sync code. Those sync `syncFolders` and `syncLogins` is old deprecated sync code that has now been removed (https://github.com/bitwarden/browser/commit/02dc3609b42d9875b747ee32161a3c6b98b45b85). It is no longer in use. Thanks for pointing this out. 

You are also correct about the `saveWithServer` code. However, bitwarden will continue to work offline in a read-only capacity. Adding/editing items in your vault requires an internet connection.

**Comment by lainy** [comment]
Awesome, thanks for the clarification, and thanks for this excellent app!!
