### ISSUE TITLE
autofill not works on this site https://www.jpo.go.jp/cgi/cgi-bin/search-portal/narabe_tool/narabe.cgi

### ISSUE THREAD

**Issue by ssfjhh** [bitwarden/browser#1160]
https://www.jpo.go.jp/cgi/cgi-bin/search-portal/narabe_tool/narabe.cgi
I have saved some radio values for the site above by hand so that I don't need to select them every time I open the site above.
But bitwarden cannot autofill them.

**Comment by kspearrin** [comment]
You need to use custom fields:

https://help.bitwarden.com/article/custom-fields/

**Comment by ssfjhh** [comment]
> You need to use custom fields:
> 
> https://help.bitwarden.com/article/custom-fields/

I have added all the essential custom fields. but it still not works yet.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
