### ISSUE TITLE
Example text (year) when adding a card is wrong

### ISSUE THREAD

**Issue by k3anton** [bitwarden/browser#1161]
Hi,

This is a small bug or rather a consideration.
I am using the Bitwarden addon in Firefox. When adding a new card, the year suggested in the text field for "Expiration Year" is 2019. But since we are now in 2020, maybe change that to this year, to minimize mistakes. 

<img width="364" alt="Screenshot 2020-03-01 at 10 05 07" src="https://user-images.githubusercontent.com/10774165/75622803-33c81d80-5b9c-11ea-9644-9e12ec1e61fe.png">

Best regards,
Anton

**Comment by AmGarera** [comment]
Working on submitting a PR for this, it's now going to match to the current year so it won't have to be touched ever again

**Comment by AmGarera** [comment]
PR is now submitted #1272

**Comment by AmGarera** [comment]
Changes were merged in #1272 @k3anton so expect to see it reflected in the extension soon!

**Comment by AmGarera** [comment]
@kspearrin This issue can be closed now as the fix has been merged into the code as of July 4th 2020. #1272
