### ISSUE TITLE
Wrong credentials filled for subdomain 

### ISSUE THREAD

**Issue by eenpadvinder** [bitwarden/browser#1162]
I have two logins saved for one domain, e.g. `sub1.domain.com` and `sub2.domain.com`. The urls are correctly configured in the saved logins.

When I fill a login on domain.com with <kbd>shift</kbd><kbd>ctrl</kbd><kbd>L</kbd>, it always fills the last used login and doesn't take the subdomain into account. Thus, when I'm trying to log in on sub1.domain.com, it fills the credentials for sub2.domain.com if that was the last login I used.

Using Firefox on Windows

**Comment by kspearrin** [comment]
Have you tried changing the uri match type to “host”?

**Comment by eenpadvinder** [comment]
That was easy 😅
