### ISSUE TITLE
In private windows, the widget is disabled but auto-fill-in and item count badge still work

### ISSUE THREAD

**Issue by fnune** [bitwarden/browser#1163]
## Current behavior

On private windows, my Bitwarden extension shows:

> Unfortunately this window is not available in private mode for this browser.

However, it still:

- Shows the number of items I have for this domain.
- Fills out email and password fields automatically, using my Bitwarden account.

## Expected behavior

If the extension popup is not available in private windows, why are these other two features working? I believe they should be disabled as well.

## Environment

Version: 1.42.2
Browser: Mozilla Firefox 73.0.1

_Aside: thanks for your great product, I love it_

**Comment by kspearrin** [comment]
The way our application is designed in the popup window is not compatible with Firefox's requirements. The rest of the extension will still function.

**Comment by fnune** [comment]
I need some more context to understand what you mean. Here's my guess: the script that has access to the DOM can't know whether it's acting on a private window or not, and therefore it's impossible to stop if from working like normally?

**Comment by devurandom** [comment]
@fnune #859 has some more information on the technical background.

**Comment by djsmith85** [comment]
Closing this, more information can be found here: https://github.com/bitwarden/browser/issues/136
