### ISSUE TITLE
Browser extension not working after importing data from LastPass

### ISSUE THREAD

**Issue by flobeier** [bitwarden/browser#1166]
After importing data from LastPass the Chrome and Safari extension stop working. 
The "Tab" section shows a loading animation and a right click - Bitwarden - Auto fill shows: "Vault is locked." However, the password entries in the "My vault" section show up and can be viewed.

This issue was verified by deleting and recreating the account. Afterwards the browser extensions worked again, but after importing the LastPass data the problems reappeared.

**Comment by kspearrin** [comment]
Did other clients apps still work, like the web vault?

**Comment by kspearrin** [comment]
Can you view the browser developer tools for the web vault and extension and see if there are any errors listed in the console?

**Comment by danactive** [comment]
I switched from LastPass to BitWarden on iOS and macos Firefox and did not reproduce this issue

**Comment by djsmith85** [comment]
Hi @flobeier, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
