### ISSUE TITLE
Authenticate (MAC) and/or encrypt equivalent domains

### ISSUE THREAD

**Issue by lainy** [bitwarden/browser#117]
As far as I can tell, the equivalent domains are not currently encrypted or authenticated. It would be nice if they were at least authenticated.

Please consider this low priority, as I believe the attack surface is basically non-existent (assumes evil/compromised server and convincing the victim to visit and fill creds on an evil equivalent domain, blah blah).

It could be considered a minor information leakage if someone adds their own equivalent domains (eg. implies they go to the domains added).

**Comment by kspearrin** [comment]
This has been brought up before and is being tracked here: https://github.com/bitwarden/core/issues/31
