### ISSUE TITLE
Custom checkbox field isn't cleared when logging into vault after page load

### ISSUE THREAD

**Issue by SyntaxErrol** [bitwarden/browser#1175]
This happens on Firefox on Windows 10. The problem is clear when comparing to behavior on Chromium-Edge.

Steps to produce:
1. Open a page with a login form with a checkbox (that is checked by default).
2. Notice the Bitwarden extension is logged out as the form is not auto-filling.
3. Log in to Bitwarden, see the saved credentials matching the current page.
4. Click the credentials to auto-fill the form.
5. Username and password are filled as expected but the checkbox state doesn't change.

Setting the checkbox state via auto-fill works correctly (most of the time) when opening the login page while already logged into the Bitwarden extension/vault.

**Comment by vincentsalucci** [comment]
@SyntaxErrol - thanks for the report! Could you please provide some more details regarding my questions below:

> Open a page with a login form with a checkbox (that is checked by default).
- Could your provide a few example websites where you've personally experienced this issue? I'd like to try and replicate this with them.

> Notice the Bitwarden extension is **logged out** as the form is not auto-filling.
- Can you confirm that you're logged out and looks like this? 
<img width="57" alt="Screen Shot 2020-03-18 at 8 44 40 AM" src="https://user-images.githubusercontent.com/26154748/76967284-35604800-68f5-11ea-93ac-f6048a6e0ce7.png">

- Or is the extension just locked? 
<img width="57" alt="Screen Shot 2020-03-18 at 8 44 29 AM" src="https://user-images.githubusercontent.com/26154748/76967299-3beebf80-68f5-11ea-9d41-fb17fbaa47a7.png">

> Username and password are filled as expected but the checkbox state doesn't change.
- From your first note - it appears the checkbox is already checked by default. Once the username/password are auto-filled, are you expecting that to uncheck the checkbox as well?

**Comment by SyntaxErrol** [comment]
> * Can you confirm that you're logged out and looks like this?
> 
> 
> <img alt="Screen Shot 2020-03-18 at 8 44 40 AM" width="57" src="https://user-images.githubusercontent.com/26154748/76967284-35604800-68f5-11ea-93ac-f6048a6e0ce7.png">
> 
> * Or is the extension just locked?
> 
> 
> <img alt="Screen Shot 2020-03-18 at 8 44 29 AM" width="57" src="https://user-images.githubusercontent.com/26154748/76967299-3beebf80-68f5-11ea-9d41-fb17fbaa47a7.png">
> 

Good point! I hadn't made the distinction. The extension is **locked**.

> * From your first note - it appears the checkbox is already checked by default. Once the username/password are auto-filled, are you expecting that to uncheck the checkbox as well?

Exactly.

The site I'm having the most problems with isn't public. And when I tried to replicate the problem with a simple form I cooked, of course it's not happening there. So clearly the issue isn't as simple as I originally thought it was. Something is definitely up with checkboxes in general. For example, the "remember me" checkbox on https://app.hubspot.com/ login page isn't filling for me. But it isn't this.
