### ISSUE TITLE
commsec.com.au password shown in cleartext; login fails

### ISSUE THREAD

**Issue by josh-parris** [bitwarden/browser#1178]
Commonwealth Securities, also known as CommSec, is Australia's largest online stockbroking firm operated by the Commonwealth Bank of Australia. It offers a telephone based brokerage service and advisory service, though its Internet trading platform constitutes the vast majority of its business.

CommSec have a propensity to log users out inactive users, and when you try navigating to a page that requires a current session, you end up at the [login page](https://www2.commsec.com.au/Public/HomePage/Login.aspx), which is where everything falls in a heap.  

If you go to the login page, select your Bitwarden login, then Bitwarden fills in the user id successfully, and puts focus on the password field. If you tab away from the password field, the browser shows your password in greyed-out cleartext in the password field, but hitting the "login" button results in an error because there's no password.  

If you go to the login page, type anything in the password field, select your Bitwarden login, then Bitwarden fills in the user id and password successfully and puts focus on the password field. If you tab away from the password field, the browser shows your password starred-out in the password field; hitting the "login" button results in a successful login.  

Problem known in Bitwarden 1.43.3 on Firefox 74.0 under Linux Mint, no other tech tested.

**Comment by absentbri** [comment]
Same issue here on Ubuntu 20.04 LTS
Chrome Version 86.0.4240.111
Bitwarden Extension Version: 1.46.2

Seems like it's filling in the Placeholder text instead of the actual password field. Does seem they have honeypot fields, the DOM is a bit of a mess, probably for security by obscuration more than anything.

**Comment by Hinton** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
