### ISSUE TITLE
Linkedin TOTP produces incorrect code

### ISSUE THREAD

**Issue by sayjota** [bitwarden/browser#1179]
I attempted to add 2-step verification to my Linkedin account using the TOTP feature of bitwarden.

After entering the secret key shown by Linkedin, the 6 digit key produced by BitWarden was rejected.

I added the same secret key to the authenticator app on my phone and a different 6 digit key was produced which was accepted by Linkedin.

**Comment by kspearrin** [comment]
This is usually because your device does not have the correct system time.

**Comment by sayjota** [comment]
Confirmed after correcting system time the issue was fixed.
