### ISSUE TITLE
Safari extension creates multiple empty windows on macOS Mission Control

### ISSUE THREAD

**Issue by ntimo** [bitwarden/browser#1182]
The Bitwarden Safari extension creates multiple invisible Bitwarden Windows in the macOS Mission Control view. The only way to get rid of them is to click on every single one of them.

Steps to reproduce:
- Just use the Safari extension

Example (all the other space on the screenshot is also used by these invisible windows):
![Screenshot 2020-03-23 at 23 39 10 copy](https://user-images.githubusercontent.com/6145026/77369765-a96c7700-6d5f-11ea-8bd1-36249e50a50a.jpg)

Bitwarden Safari extension version: 1.43.4
Safari version: 13.1 (15609.1.20.111.8)
macOS version: 10.15.4 (19E266)

**Comment by yoonsikp** [comment]
same here

**Comment by dtpett16** [comment]
I can confirm the same issue. The invisible windows usually appear in Mission Control after opening Bitwarden in Safari. 
![Screenshot 2020-08-04 at 14 00 09](https://user-images.githubusercontent.com/25056311/89291535-00ae1c80-d65b-11ea-9462-4404d0846c51.png)

**Comment by saegl5** [comment]
for me too
