### ISSUE TITLE
Auto-fill not working on virustotal.com

### ISSUE THREAD

**Issue by maxim-sm** [bitwarden/browser#1183]
Auto-fill doesn't work on VirusTotal's login page.

**URL:** https://www.virustotal.com/gui/sign-in
**Error:** "Unable to auto-fill the selected item on this page. Copy and paste the information instead."
**Browsers tested:** Chrome 80.0.3987.132, Firefox 74.0
**Extension Version:** 1.43.3

Thanks!

**Comment by kspearrin** [comment]
Looks like their password field is like this

```
<vt-ui-text-input id="password" type="password" placeholder="Password" empty=""></vt-ui-text-input>
```

Our autofill code only understand `<input>` fields today.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
