### ISSUE TITLE
automatic TOTP copy does not work when Auto-Fill i enabled

### ISSUE THREAD

**Issue by morten-b** [bitwarden/browser#1184]
## Subject of the issue

In the Firefox client the automatic TOTP copy does not work when Auto-Fill i enabled

## Steps to reproduce

Enable Auto-Fill, let Auto-Fill type username and password, on the following page paste TOTP code, without manually copying it.

## Expected behaviour

TOTP should be pasted

## Actual behaviour

Nothing/previous clipholder content is pasted

**Comment by kspearrin** [comment]
TOTP is only copied to clipboard on explicit autofill operations. If you are using auto-fill on page load, it does not copy there.

**Comment by morten-b** [comment]
Wouldn't it make sense to implement it so that it did?

-------- Original Message --------

**Comment by kspearrin** [comment]
We do this because we don't want to override things in a users clipboard without some explicit action.

**Comment by morten-b** [comment]
That makes sense. Thanks for responsiveness.

**Comment by breuerfelix** [comment]
what about explicitly allowing this to happen ? e.g. turned off via default.

to be honest the only advantage that you get when choosing "auto fill on page load" is that you do NOT have to open the extension.

if you then have to open the extension, click on the item and also click on the copy button you actually have to do more clicks then when you would turn off the auto fill on page load. cause that way you only need to do 2 clicks instead 3.

that means turning on this feature which should make logging in faster actually slows you down.

**Comment by kspearrin** [comment]
@breuerfelix We could add an option for this. Consider opening a feature request on our forums at https://community.bitwarden.com

**Comment by breuerfelix** [comment]
@kspearrin got it, thanks !

https://community.bitwarden.com/t/automatic-totp-copy-with-autofill-on-page-load/12927

**Comment by TimoGlastra** [comment]
I already openend a feature request on the bitwarden community pages. The moderators said it should be seen as a bug and filed here.

See: https://community.bitwarden.com/t/also-copy-totp-code-after-autofill/12859

**Comment by tgreer-bw** [comment]
@breuerfelix  @TimoGlastra - the issue on the forums didn't indicate (at first) that it was due to autofill on page load - that *is* a feature request, so this issue should remain closed and we'll continue on the forums 👍

**Comment by humleflue** [comment]
I still have this problem.

**Comment by tomershvueli** [comment]
This is something I'm really missing right now after recently having turned on the 'Enable auto fill'. If I create a PR to enable this extra option, will it be considered for merging in?
