### ISSUE TITLE
Add current URL to Entry

### ISSUE THREAD

**Issue by andrejrcarvalho** [bitwarden/browser#1187]
I've a problem and I'm triyng to solve it my self. I find users with the same problem:

[Add current URL to Entry - Feature Requests - Bitwarden Community Forums](https://community.bitwarden.com/t/add-current-url-to-entry/8019)

I've exactly the same issue. It's a pain in the ass to add the url manually. The plugin dialog automatically closes when you click in the browser url to copy and then paste it.
I'm currently trying tho add this feature to the plugin, but I'm having some problems with it.
I notice that core code is shared between the bitwarden apps and I may need to change same code in there.
Can you gave me some tips about what I have to do to implement this new feature

**Comment by kspearrin** [comment]
You can click the "pop out" arrow in the top left corner to make the window persist.

**Comment by andrejrcarvalho** [comment]
I know but if the site that we open are not in the uri list we can use the autocomplete

**Comment by JSteeleIR** [comment]
I've also very much felt the need for this. I sometimes end up having multiple URLs/IPs that point to the same actual resource, and I just want to "add the current page" to this entry.

**Comment by benridley** [comment]
Agree, it'd be nice if when you searched for a credential that selecting it asked if you wanted to save the current tab for this secret, and then autofilled.

**Comment by luckman212** [comment]
Nice idea! Another vote for this
