### ISSUE TITLE
Firefox Extension Not Showing Passwords (Firefox 75)

### ISSUE THREAD

**Issue by bricep** [bitwarden/browser#1188]
Have been encountering this on Firefox Beta for two weeks +. 

Initially, the extension stopped showing new / updated passwords. However, when I went to the web vault, those passwords were up-to-date and present. 

I removed the extension from Firefox, added it back again, and logged in. Now there are no passwords in the vault in the extension and once again I am able to see all of the passwords when I go to the web vault. I've manually synced. 

Screenshots of web vault vs. searching in extension for Github login:

![image](https://user-images.githubusercontent.com/17284764/77653815-9798f880-6f46-11ea-834c-2a4e0730955c.png)
![image](https://user-images.githubusercontent.com/17284764/77653835-9ff13380-6f46-11ea-9b4b-d8605dc82da2.png)

**Comment by kspearrin** [comment]
If you debug the extension under about:debugging so you see any errors in the console?

**Comment by bricep** [comment]
There are, here are the errors and alerts:
![image](https://user-images.githubusercontent.com/17284764/77687385-b0200780-6f74-11ea-9ad6-25f459eff8a2.png)

**Comment by bricep** [comment]
I removed the extension again and made sure the XPI file and offline storage in the browser-extension-data was removed, where the last time the storage for the extension was written to was some time ago. 

After re-adding the extension, I don't see the offline storage being re-created in the browser-extension-data folder in the browser profile

**Comment by kspearrin** [comment]
What if you try a new user profile in firefox?

**Comment by bricep** [comment]
Ugh, that did it. Sorry to bother you with something so basic - appreciate the help! Love Bitwarden and appreciate everything you do. Thanks!
