### ISSUE TITLE
Replaces title of WordPress posts/pages

### ISSUE THREAD

**Issue by forteller** [bitwarden/browser#1190]
If you're editing a post or a page in a WordPress instance but then don't do anything for a while you will be logged out and a login box will appear on top of the page. If you then use the Bitwarden extension (at least for Firefox, haven't checked anywhere else) to fill in the username/password the extension will do that. But it will also fill in your username in the Title field of the post/page, removing whatever was there before. In addition you can not use Undo to get the previous text back. 

In a few occasions you might not remember what was the title, and this will be even more annoying than if you just had to write the title again.

Is it possible to avoid doing this?

Thanks for your great work! :)

**Comment by kspearrin** [comment]
You could target the username field using a custom field that only works for the login page.
