### ISSUE TITLE
Cloudflare Blocking Loging requests - error message is bad.

### ISSUE THREAD

**Issue by c00w** [bitwarden/browser#1196]
I'm attempting to login to the extension on chrome running on chromeos - it errors with a statement that the previous loging has expired. I tried to log in on the website and it returned the same error. I traced the network activity, and saw that cloudflare was rejecting requests to
https://valut.bitwarden.com/api/account/prelogin from my chrome browser. I have attached a screenshot for reference. This appears to be working on my other browsers.

![Screenshot 2020-04-04 at 5 43 35 PM](https://user-images.githubusercontent.com/486199/78462046-882f5300-769c-11ea-80c0-fa1907d9dcae.png)

For reference the ray id is 57ee3472ab24f045

It would be great if this returned a more useful error (i.e. you've been ratelimited, please contact us at help@bitwarden.com - or even return the ray id to put in that email.

**Comment by kspearrin** [comment]
This should now be resolved.
