### ISSUE TITLE
2FA via Authenticator app not working

### ISSUE THREAD

**Issue by ReactMarc** [bitwarden/browser#1200]
When I try to login in via the Firefox extension or Web Vault in Firefox or Opera, I get the following error after authenticating via the Authenticator app:

> "An error has occurred
> Two-step token is invalid. Try again.

2FA via an alternate method is working. Removing Bitwarden from Authenticator and scanning the QR code again has no effect.

**Comment by kspearrin** [comment]
Is your authenticator app configured to generate correct codes? THe most common reason for this is the device not having the proper system time set.

**Comment by ReactMarc** [comment]
It's strange, but it is working again. I checked the time on the device, but nothing changed in that regard. Anyway, I'm glad it's "fixed" :)
