### ISSUE TITLE
Pay attention to subdomain for autofilling

### ISSUE THREAD

**Issue by 4VRDriver** [bitwarden/browser#1202]
I recently switched to Bitwarden, because it's an awesome open source project.

The autofill funtion for login forms works well in the browser. But it seems that it is not paying attention to the subdomain. I have to log in to several university sites which are all hosted on the same domain, but the subdomains vary. I have multiple login-names and passwords, but Bitwarden does not fill in the correct ones, because it can't differentiate between the subdomains.

**Comment by kspearrin** [comment]
See "Host" URI detection: https://help.bitwarden.com/article/uri-match-detection/

**Comment by 4VRDriver** [comment]
Thank you, now it works just fine!

Is there a reason, why this setting is not the default?
