### ISSUE TITLE
Bitwarden does not auto-prompt to save login information on the ubisoft login page.

### ISSUE THREAD

**Issue by ShockRocky** [bitwarden/browser#1204]
Steps to reproduce:-

1) Go to the ubisoft international store page.

2) Go to the login page i.e. https://store.ubi.com/ie/account-connection 

3)Make a new account

4)Bitwarden does not prompt to save the login details, which is the default behavior.

What should be the ideal result:-

Bitwarden should prompt the user to save the login information after the account is created.

Browser and OS information:-

Brave Browser | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --

OS | Windows 10 OS Version 1909 (Build 18363.720)
-- | --

Workaround for the issue:-

1)Open bitwarden on chrome://newtab.

2)Click on the ' add a login' button.

3)Enter the details as necessary and in the uri section, copy paste https://store.ubi.com/ie/account-connection 

4)Bitwarden will autofill the details, as it should.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known issue that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this post: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
