### ISSUE TITLE
100% CPU usage while viewing video on PluralSight website

### ISSUE THREAD

**Issue by jsphkm** [bitwarden/browser#1207]
I've posted my question on reddit, which can be found here:
https://www.reddit.com/r/pluralsight/comments/g07n28/cpu_100_usage_from_the_safari_desktop_browser/

I'm using:
- Safari 13.1
- macOS Catalina 10.15.4
- 16" MacBook Pro

I've found that while I was viewing a video from the online course site PluralSight, my CPU would spike to 100% usage, with a timer being fired constantly:
![image](https://user-images.githubusercontent.com/28643797/79386199-a7d93d80-7f1e-11ea-9279-9273c642f108.png)

I noticed that this issue was only occurring from Safari.  Due to tech support recommendations, I've deactivated, and uninstall the Bitwarden extension from Safari, and now the issue is gone.  The browser's timeline looks like this now:
<img width="1321" alt="Screen Shot 2020-04-15 at 1 47 45 PM" src="https://user-images.githubusercontent.com/28643797/79386932-bb38d880-7f1f-11ea-864f-42283ee0a228.png">

Now I'm convinced to keep the extension uninstalled until this is resolved.  Was the extension really causing this issue?

**Comment by kspearrin** [comment]
@clayadams5226 Can you try reproducing this one?

**Comment by clayadams5226** [comment]
@kspearrin I'm able to reproduce this pretty consistently. It seems to only be an issue on pluralsight WITH Bitwarden installed, but not on any other streaming sites such as Twitch and YouTube. On those sites my CPU usage hovers around 30, but as soon as I go to Pluralsight it spikes to about 115 and stays there. When I uninstall Bitwarden and try Pluralsight again, it stays at about 30. 

I've included some screenshots. 

![PluralSight1](https://user-images.githubusercontent.com/61576435/79628315-fc8edb00-810d-11ea-9bab-ce0d102ca4d3.png)
![PluralSitght2](https://user-images.githubusercontent.com/61576435/79628318-00226200-810e-11ea-8e99-6aba7602817e.png)
![PluralSight3](https://user-images.githubusercontent.com/61576435/79628322-057fac80-810e-11ea-8c71-79c8dbc9f889.png)
![PluralSight4](https://user-images.githubusercontent.com/61576435/79628335-15978c00-810e-11ea-813d-41279c932f14.png)

**Comment by kspearrin** [comment]
Can you go to Settings > Options and disable add login notification and change password notification and see if they problem changes at all?

**Comment by clayadams5226** [comment]
Same Result. CPU is at 108% and stays there.

<img width="1792" alt="PluralSight" src="https://user-images.githubusercontent.com/61576435/79790887-709dce80-831a-11ea-96a5-47fcc910d93b.png">
