### ISSUE TITLE
Create pt-PT translation

### ISSUE THREAD

**Issue by SW1FT** [bitwarden/browser#121]
I noticed you currently don't have a Portuguese (pt-PT) translation and I'm able to provide one, which is also a very good foundation for the pt-BR translation (if someone else wants to do it).

A bit about me so you know this translation is reliable :-) :
My name is Rodrigo and I'm an [editor for the l10n pt-PT locale team at Mozilla](https://wiki.mozilla.org/L10n:Teams:pt-PT), currently one of the managers in both the [Pontoon](https://pontoon.mozilla.org/contributors/VFtdUt4Xpmlah8YxXJVSqeL8GjI/) and [Pootle](https://mozilla.locamotion.org/user/SW1FT/) platforms. Also, you can look at my [Crowdin profile](https://crowdin.com/profile/SW1FT/).

Reply to this if you're interested, because I have the extension part of the translation pretty much ready.

**Comment by kspearrin** [comment]
@SW1FT we'd love for you to add `pt` support. Please review https://github.com/bitwarden/browser/blob/master/CONTRIBUTING.md for details.
