### ISSUE TITLE
Minor UI Issue: In-progress spinner does not always work

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#1210]
In Firefox (currently seeing this issue in Firefox 75, but have noticed it in previous versions too), when I click on the Bitwarden toolbar button, an empty popup with a spinner appears for a few seconds.  Most of the time, the spinner looks as it should.  Sometimes, though, it's just a spinning rectangular box with a character code in it.

I'm guessing the font (or less likely, an image) being used to display the spinner gets unloaded, which messes up the ability to display it correctly.

Since Bitwarden already consumes a large amount of memory, instead of forcing the required font (if my guess is correct) to remain resident, how about just simplifying the spinner to not require any resources that are not native to the browser?

**Comment by nicolaerario** [comment]
I also noticed this little glich (on FF78 and Chrome 83); it happens after the unlock by pin: the spinner isn't loaded and shows the unrecognized font symbol.
