### ISSUE TITLE
Autofill hotkey in Vivaldi not functioning

### ISSUE THREAD

**Issue by lschober-bw** [bitwarden/browser#1212]
## Describe the Bug

Autofill does not input matching data when attempting to autofill via hotkey (ctrl+shift+L)

## Steps To Reproduce

1. Open Vivaldi Browser
2. Log in/Unlock Bitwarden 
3. Navigate to a website with a corresponding Bitwarden item.
4. Attempt autofill via hotkey

## Expected Result

Username and password data is filled in respective fields

## Actual Result

No data is filled.

## Environment

- Operating system: Windows 10
- Build Version: Vivaldi 3.0.1874.23 (Stable channel) (64-bit)
- Is this a Beta release? N

**Comment by kspearrin** [comment]
Last I checked this was due to bugs in Vivaldi not firing hotkey events.

**Comment by lschober-bw** [comment]
Confirmed to be a bug in Vivaldi: https://forum.vivaldi.net/topic/43370/bitwarden-autofill-shorcut-broken-on-newer-vivaldi?lang=en-US&page=1

Setting the hotkey to "Global" as opposed to "In Vivaldi" enables autofill functionality

![vivaldiAF](https://user-images.githubusercontent.com/59910153/81752691-d50a0480-9466-11ea-9c2f-1fe02151ff19.png)

**Comment by calexicoz** [comment]
I did not realize there was this "shortcut" page for extensions.

That works! Thanks 🙏
