### ISSUE TITLE
Doesn't have fill-and-save like the mobile plugin

### ISSUE THREAD

**Issue by jaymzh** [bitwarden/browser#1217]
This falls in between bug and feature request...

If you have credentials saved for a website but the entry doesn't have the URL on it, you can search for for the name and select it. On the mobile BW client one of the options is "fill and save" but on the browser plugin, this option doesn't exist. So you end up in the `edit` menu where you must manually add the URL. The browser plugin should also offer a fill-and-save option.

**Comment by eliykat** [comment]
"Auto-fill" and "Auto-fill and Save" buttons have now been added on the View Item page.

**Comment by jaymzh** [comment]
I noticed this recently and it's *awesome*. Thank you!
