### ISSUE TITLE
The login information submitted by ajax will not pop up a save prompt box

### ISSUE THREAD

**Issue by zanderpu** [bitwarden/browser#1218]
Hello,

I found that the browser plug-in cannot pop up the save prompt box for the form logged in through ajax.
But when I use lastpass, the save prompt box can pop up normally
Hope to increase the matching of login forms using ajax

**Comment by kspearrin** [comment]
Please provide an example.

**Comment by zanderpu** [comment]
thank you for your reply,

example：[http://www.ugouquan.com/login.html](http://www.ugouquan.com/login.html)

I am using Firefox and Google browsers that are not working properly

**Comment by kspearrin** [comment]
The form needs to be properly wrapped in a `<form>` element and then it should be detected.

**Comment by zanderpu** [comment]
I know. Thank you
