### ISSUE TITLE
TOTP not working correctly

### ISSUE THREAD

**Issue by gbursson** [bitwarden/browser#1219]
TOTP seems to not work on PayPal and degiro especially. I got locked out from both services.
I made sure to wait for mid-time of the code (i.e. 15s). I did not change auth pass for TOTP.
This behaviour persists between browsers (Firefox/Brave) and across different PCs.

My initial suspicion is a problem with time-sync, as TOTP used to work after a few attempts and pasting a 'new' code when the 'old' expired.

**Comment by kspearrin** [comment]
Is the system time on your devices correct?

**Comment by gbursson** [comment]
yes, I even updated it with NTP.

**Comment by gbursson** [comment]
Started behaving. Closing the issue.
