### ISSUE TITLE
No icon download on Regular Expression

### ISSUE THREAD

**Issue by Smallinger** [bitwarden/browser#1220]
Hey if i use a regular expression like ^https://example.com/$ then i see no Website favicon in the bitwarden Chrome extension. and i cannot click on the open URL button.

**Comment by kspearrin** [comment]
If you use a regex in slot #1 of the item, we cannot determine a proper website URL to fetch the icon or launch URL. `^https://example.com/$` is a regular expression, not a properly formatted URI.
