### ISSUE TITLE
Pop Out window prevents timed auto lock of vault

### ISSUE THREAD

**Issue by bung69** [bitwarden/browser#1221]
Version: 1.43.4

when using the Bitwarden chrome browser extension,  with "pop out to a new window" the vault does not automatically lock after the time out set in Settings > Security > lock options.

The pop out window could easily end up hidden behind another window and be unlocked indefinitely.  seems like an oversite.  

thanks

**Comment by kspearrin** [comment]
The timeout timer only starts if the popup window is closed, including if it is popped out. This is the expected behavior.

**Comment by Jacalz** [comment]
I think this perhaps should be changed. Popping out the extension is a great way to have it open like an external application without having to have the browser open at all times for grabbing passwords and other stuff.

**Comment by JonathanLindsey** [comment]
It looks like this is a duplicate of #1334. And there is more discussion over there.

**Comment by eliykat** [comment]
Closed as a duplicate of #1334, thanks @JonathanLindsey
