### ISSUE TITLE
[Firefox] Unable to open addon using hotkey when any field select

### ISSUE THREAD

**Issue by hoshsadiq** [bitwarden/browser#1224]
When pressing the hotkey for bitwarden while a text field is selected (tested `<input type=text/>` and `<textarea/>`), bitwarden doesn't show up at all. I have to remove focus from the input element, only then does the hotkey work.

Using:
Firefox 75 on Linux Mint 19.1

**Comment by kspearrin** [comment]
We cannot control the action of the hotkey to open Bitwarden. We only define what the hotkey should be. This sounds like a bug in Firefox itself.
