### ISSUE TITLE
Clear clipboard feature

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/browser#1234]
Clearing data (login, password, card numer, TOTP code etc) from clipboard doesn't work correctly. After specific time clipboard isn't cleared completely but string is replaced by `" "` (spacebar). It should be fully cleared like in desktop or mobile app.

Tested on Bitwarden Chrome extension 1.43.4

**Comment by 3zero2** [comment]
Ideally it should work as follows:

1. Copy current clipboard data to a temporary space
2. Put TOTP/Password/login etc into the clipboard
3. When timeout specified occurs, the original clipboard data is restored from the temporary storage.
