### ISSUE TITLE
Shortcut key issue on Firefox + macOS Catalina

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/browser#1236]
When using **Cmd + Shift + Y** the tab just toggles between "Search vault", "Add item" and "Pop out to new window", you are unable to keep tabbing down, in order to select the login you want, you need to use the mouse:
![tab](https://user-images.githubusercontent.com/5418577/82318177-b4dec600-99cf-11ea-86dc-3d4db604b1db.gif)

We tested: Windows 10, Ubuntu 18 LTS and macOS Catalina 10.15.4 and browsers Chrome and Firefox, the problem only arises when using macOS + Firefox 

Expected behavior: be able to keep tabbing and select an entry without a mouse.

**Comment by Aryik** [comment]
+1. Bitwarden is a great piece of software overall but this significantly hampers usability on Firefox + macOS. FWIW, I'm seeing it on macOS Mojave, Firefox 79.0, Bitwarden 1.45.0.
