### ISSUE TITLE
Lock options timeout doesn't seem to work in Vivaldi 3.0

### ISSUE THREAD

**Issue by theCroh** [bitwarden/browser#1237]
Lock options: 4 hours never seems to lock the extension in Vivaldi 3.0. I can reproduce this on both Windows 10 and Kubuntu 20.04. The extension is locked only after restarting the browser even when lock options is set to 4 hours. I havent tested other settings.

**Comment by envake** [comment]
Can confirm Windows 10 Education 64bit and Arch Linux 64bit kernel 5.6.15-arch1-1 with Vivaldi v3.1.1929.34 on both systems. Bitwarden only locks when restarting the browser. The timeout options and the instant lock option don't work.

**Comment by Alphaprot** [comment]
This is a bug in Vivaldi (cross-platform; e.g. the error appears on Windows machines as well), as you can read here:
https://github.com/bitwarden/browser/issues/1037#issuecomment-569672167

**Comment by BloodyIron** [comment]
So this is still a thing then? 2 YEARS later?

**Comment by sso-bitwarden** [comment]
I think we can close this, @eliykat . The issue is fixed. Vetted.
