### ISSUE TITLE
Deleting site/note on browser is not pushed to extension or android app

### ISSUE THREAD

**Issue by Helicle** [bitwarden/browser#1247]
I'm deleting items in the browser vault, but these deletions are not reflected in the extension or android app, even after forced syncs. Creating new items in the browser or moving items to different folders is immediately reflected in the extension and app, as normal. "Deleted" browser entries, while incorrectly persisting on other platforms, are consistently missing (correctly deleted) on other instances of browser logins across different devices and browsers.

Please let me know if there is any additional info I can provide.

**Comment by tgreer-bw** [comment]
The web vault has a new “Trash” area - you’ll need to delete the items from the trash on the web vault and they’ll disappear from the other clients. The other clients will get the trash feature over the coming week or so.

https://bitwarden.com/help/article/managing-items/#items-in-the-trash
