### ISSUE TITLE
Some websites don't trigger save notification

### ISSUE THREAD

**Issue by getreadyforme** [bitwarden/browser#125]
https://store.steampowered.com//login
https://signin.ebay.com/ws/eBayISAPI.dll?SignIn

I will update this list if I encounter more of these.

**Comment by kspearrin** [comment]
Thanks. I see the issues. I have a fix for eBay in the next release. I don't have a solution for steam yet.

**Comment by getreadyforme** [comment]
Here's another one   https://www.gog.com/

**Comment by getreadyforme** [comment]
also https://twitter.com/
on this URL the login doesn't trigger autosave, but after logout and re-login it triggers it (the URL changes then)

**Comment by getreadyforme** [comment]
http://www.ign.com/

**Comment by kspearrin** [comment]
Fix for the eBay issue is available now in v1.11.0

**Comment by kspearrin** [comment]
These are all fixed for next version (minus steam which I have no solution for).
