### ISSUE TITLE
Bitwarden keeps logging me out when `Vault Timeout` is set to `On System Lock`

### ISSUE THREAD

**Issue by DougParker1992** [bitwarden/browser#1254]
Ever since the Browser extension updated, Bitwarden keeps logging me out despite the fact that `Vault Timeout Action` is set to `Lock`. This seems to exclusively happen when `Vault Timeout` is set to `On System Lock`.

**Chrome Version:** 83.0.4103.61
**Brave Version:** 1.9.72 **Chromium:** 81.0.4044.138
**Bitwarden Version:** 1.44.1

**Comment by Gazorby** [comment]
I can reproduce this too

**Comment by spncrhrstn** [comment]
I can reproduce this as well, with the addition that my vault timeout is set to 15 minutes. I timed it for the 15 minutes and I was logged out. Vault Timeout Action is set to Lock.

Same versions as author.

**Comment by 73R3WY** [comment]
Hello, below is my configuration, I can also confirm that the browser extension keeps on logging out, and I need to enter my master password whenever I open the extension. (Same `Chrome` and extension versions as the OP)
<img width="359" alt="Screen Shot 2020-05-28 at 10 58 25 AM" src="https://user-images.githubusercontent.com/8436044/83093511-286c8b80-a0d2-11ea-98bb-da5fb57af56e.png">

**Comment by passlickdev** [comment]
Reproducable for me, too. Quite annoying right now.

**Chrome Version:** 83.0.4103.61
**Bitwarden Version:** 1.44.1

**Comment by vincentsalucci** [comment]
Thanks everyone. This is being investigated/fixed asap.

**Comment by Zeustopher** [comment]
I was having this issue as well, but I seem to have found a possible **workaround** for now:

1. Set Vault Timeout Action to "Lock" (probably what your default is right now)
2. Change the Vault Timeout Action to "Log Out"
3. Change the Vault Timeout Action back to "Lock" again

After toggling it to "Log Out" and back to "Lock" again it appears that the setting took this time and it just locks instead of logging me out all the way.

Since I did the workaround above it has successfully only locked instead of logging out twice. I would be interested to know if others can use workaround successfully also.

**Comment by srd424** [comment]
Aha, seems to work! Thanks :)

**Comment by 73R3WY** [comment]
@Zeustopher 's workaround is working! :)

**Comment by smellysfunky** [comment]
Version 86.0.4240.198 (Official Build) (x86_64)
MACOS 10.15.6

If you cannot log into Bitwarden Chrome Extension, or it keeps logging out, then you can try this solution. Make sure the Extensions Jigsaw icon is visible on your URL. Click the jigsaw, select Bitwarden Extension, then select PIN to toolbar. For some reason, you can't access this PIN function in the Windows/Extension area. Seems like a pain in the behind. Select the new Bitwarden pinned icon, then you can log in .

I set mine to never log out, and selected PIN to login, and used my screen saver as the lock out for security (set for 3 minutes) . if someone steals my computer, they can't copy and decrypt the bitwarden file as its encrypted.


Issue Resolved for vault locked/ vault logged out in the Chrome Extension (MacOS)
