### ISSUE TITLE
Respect sub-domains

### ISSUE THREAD

**Issue by tomasnorre** [bitwarden/browser#1257]
Hi,

I have some services on the same TLD-domain, but with different sub-domains, the sub-domains are all different services like Jira, Confluence, Jenkins etc. 

When I go to one of these sub-domains all the matching TLD-domain entries get displayed as possible matches as well. 

It's ok, if there is no sub-domain match, as it could be single sign-on on something like that. But just because I'm on the same TLD-domain I'm not having the same user/pass credentials for my accounts :) 

Example: 

I have user/pass for `wiki.example.tld`, `jenkins.exmaple.tld`, `jira.example.tld`
If I visit `jenkins.example.tld` all tree suggestion would be displayed. 

I'm looking forward to getting your feedback on this, and if it's a bug, also try to help to solve this.

**Comment by srd424** [comment]
You can change the match type to 'host' - that should do it? Settable per-entry or as a global default I think.

**Comment by tomasnorre** [comment]
Thanks, I didn't pay attention to that, works like a charm.
