### ISSUE TITLE
Autofill not working with custom field

### ISSUE THREAD

**Issue by airycanon** [bitwarden/browser#1258]
Hi,I have a password input bellow
```html
<p>
    <label for="password_ims">输入您的密码</label>
    <input id="password_ims" name="password_ims" type="password" value="" placeholder="输入您的密码">
</p>
```
I add a hidden custom field `regex=password_ims` for autofill，but it is not working.
Thanks for any help.

**Comment by kspearrin** [comment]
You don't need regex. Just use `password_ims` for the name.

**Comment by airycanon** [comment]
> You don't need regex. Just use `password_ims` for the name.

@kspearrin Thanks kspearrin, but it is still not working.
It seems that Bitwarden could not detect a matched password input when there is a "display:none" style, this is the whole HTML
```html
<div class="step-main step-2 step-error" style="display: none;">
    <div id="u13" class="ax_text_line">
        <p>
            <label for="password_ims">输入您的密码</label>
            <input id="password_ims" name="password_ims" type="password" value="" placeholder="输入您的密码">
        </p>
    </div>
</div>
```
