### ISSUE TITLE
Firefox & Chrome extension does not load "Tab" or "My Vault"

### ISSUE THREAD

**Issue by ple103** [bitwarden/browser#126]
I am logged into the extension on Firefox and Chrome, but neither will load accounts and folders when I'm on the "Current Tab" or "My Vault". All I see is the spiral loading animation.

I have tried logging out and back in again, but that hasn't fixed it. The web vault and mobile app are still working fine for me.

**Comment by kspearrin** [comment]
Can you open the popup's console as well as the background page console and see if there are any errors?

**Comment by ple103** [comment]
![image](https://cloud.githubusercontent.com/assets/935054/24532204/f7ff5148-1601-11e7-89f2-2142aeca4803.png)

By background page are you referring to the _Elements_ tab of the Developer Tools?

**Comment by kspearrin** [comment]
Go to `chrome://extensions/` and inspect the background page view.

**Comment by ple103** [comment]
![image](https://cloud.githubusercontent.com/assets/935054/24533907/ff0315cc-160d-11e7-832e-b8f79314444e.png)

**Comment by kspearrin** [comment]
You need to enable developer mode and then inspect the background page.

![image](https://cloud.githubusercontent.com/assets/1190944/24534155/24e7aeca-159a-11e7-82f9-7d72c5c6bc62.png)

**Comment by ple103** [comment]
Cheers for the instructional screenshot.
![image](https://cloud.githubusercontent.com/assets/935054/24534336/b4b168f4-1610-11e7-8ce9-4d88b8524bce.png)
![image](https://cloud.githubusercontent.com/assets/935054/24534363/eda96ba2-1610-11e7-97f1-59883a7976c8.png)

**Comment by kspearrin** [comment]
Well that's interesting. Did this ever work?

**Comment by kspearrin** [comment]
May I suggest trying to log out and back in? Or going to settings and doing a full sync again.

**Comment by ple103** [comment]
It _was_ working. The only thing I remember doing before it broke was changing my email address. I'll try a combination of those things to see if I can get it fixed.

**Comment by kspearrin** [comment]
Can you try changing your password (it can be the same password again)?

**Comment by ple103** [comment]
@kspearrin When I change my password, how long can I expect to wait for bw to re-encrypt my 200 passwords? It's been running for 15 minutes.

**Comment by kspearrin** [comment]
It should be done in less than a second. If it is still running that means an error probably occurred. Can you check the console?

**Comment by kspearrin** [comment]
@ple103 Any update?

**Comment by ple103** [comment]
@kspearrin No wonder I didn't get a reply. My screenshot didn't send. I'll get back to you in a day or two. Currently without a phone. So no 2FA codes ...

**Comment by ple103** [comment]
@kspearrin I can't replicate the issue in Chrome at the moment because I don't have my phone for the 2FA code. However, I can replicate it in Firefox since I'm already signed into it. If you prefer console logs from Chrome then I can provide that to you as well.

Clicking the bitwarden extension icon:
![image](https://cloud.githubusercontent.com/assets/935054/24642048/b698b43a-1947-11e7-8ff3-5da0eeb6e2dd.png)

Unlocking bitwarden:
![image](https://cloud.githubusercontent.com/assets/935054/24642089/175fa33c-1948-11e7-88b8-a5b22c1a5e08.png)

Switching to "My Vault"
![image](https://cloud.githubusercontent.com/assets/935054/24642100/2b8b9910-1948-11e7-954a-582e6c5b1ac1.png)

**Comment by kspearrin** [comment]
It appears that your it is still having issues decrypting the data. When you have some time, would you mind hoping in our live chat to try and debug with with me live? https://gitter.im/bitwarden/Lobby

**Comment by ple103** [comment]
After the account reset, everything is working again. Would you like me try and replicate that corruption issue?

**Comment by kspearrin** [comment]
@ple103 Yes, please if you can. I'd like to figure out some reproducible steps if we can.

**Comment by ple103** [comment]
I am no longer able to reproduce this issue.
