### ISSUE TITLE
chrome extension remembers login details

### ISSUE THREAD

**Issue by kaiomurz** [bitwarden/browser#1260]
I recently set my office chrome browser to not remember any of the passwords, since I login using a company specific gmail account that is insecure and might have to be made available to my IT manager. I have deleted all the saved passwords manually from the Chrome settings manager. However, the Bitwarden extension remembers my user name. It would ordinarily not be an issue but I once typed in my password into the user name box in the extension and that is shown along with my normal user name.
I've uninstalled and reinstalled the browser, but it still remembers my details as long as the browser is logged in to the office gmail account. 
So if my office IT manager logs into Chrome with the insecure account and then syncs the extension, he will be able to see my Bitwarden password
 
How do I remove that from wherever it is stored?
thanks.

**Comment by kspearrin** [comment]
Are you talking about the Chrome input suggestion box that drops down under the field? If so, the browser stores that, not the extension. I think you can delete them with the Delete key or something.

**Comment by kaiomurz** [comment]
Thanks. Yes that is what I'm talking about. I tried to use the delete key but it doesn't work. 
Would you now where in the browser (Chrome) i might be able to delete this from? I've cleared out all the passwords saved by the browser but maybe it stores extension details some place else that I can't find.

**Comment by kspearrin** [comment]
Seems to be several suggestions here: https://www.google.com/search?client=firefox-b-1-d&q=delete+chrome+input+suggestions

**Comment by kaiomurz** [comment]
Thanks. I've tried those suggestions - they are mostly about disabling autofill. However, while that does stop the browser from filling out websites, it doesn't stop it from doing the same for extensions.

**Comment by kspearrin** [comment]
https://superuser.com/questions/1289097/how-to-delete-specific-autofill-entries-from-google-chrome



> Hopefully I haven't oversimplified but I think there'll be enough to answer your question.
> 
> Step 1 - For example, click in the "Username" field/input box and press the down arrow (this will bring up a list of remembered "username" auto-fill entries)
> 
> Step 2 - Use the down arrow key to highlight the username (auto-fill entry) you want to delete
> 
> Step 3 - Press shift+delete, or shift+alt+backspace if you have a Chromebook
> 
> Done.

**Comment by kaiomurz** [comment]
worked!!!
thanks a lot! Really appreciate the help.
