### ISSUE TITLE
Password overlap with subdomain and same username

### ISSUE THREAD

**Issue by renantmagalhaes** [bitwarden/browser#1264]
I notice a behavior when using websites with subdomain and the same username, it will overlap the current password.

Example:

site1.domain.com 
user: admin
pass: 123

I save the credentials and everything works fine, BUT if i have this situation.

site2.domain.com
user: admin
pass: 111

The plugins asks to UPDATE the password (even if this was my first time in this site2) and the user will overlap the credential of site1.

**Comment by MattTheDev** [comment]
Hey there, @renantmagalhaes  - 

I tested with 3 azurewebsites.net sites, each with their own subdomain, and was unable to reproduce this issue. Is there any pattern you've noticed? ie: site1 is first in the list, url matching is different than the base/default matching.

Anything you have would help me repro the issue and get it resolved.

**Comment by MattTheDev** [comment]
We’ve been unable to reproduce this issue ourselves. If this issue persists, please reopen it, and we’d be happy to help resolve the problem.
