### ISSUE TITLE
TOTP desynchronization

### ISSUE THREAD

**Issue by BarbossHack** [bitwarden/browser#1265]
Hi,

Since yesterday, all my TOTP codes are delayed by 2 minutes, so I can't connect on my accounts anymore.

I tested with software "WinAuth.exe" on the same computer (so same system time) and it works, and I saw that if I generate a totp code with WinAuth, I see the same code on bitwarden extension 2 minutes after.

As it worked like a charm before yesterday, and as I do not see any totp update in your code, I assume it's a problem on my side, but I can't figure it out... if you have any idea !

Device: Windows 10 (insider), Chrome extension, Chrome 83 and 81 (yes I have 2 chrome installation, same error on both)
Connection: Wifi (with and without my VPN)
Extension version: 1.44.2

**Comment by BarbossHack** [comment]
I just tested with v1.44.1 and v1.43.4 and it doesn't work, so it's clearly a problem on my side... I will try to look at what could happened...

**Comment by BarbossHack** [comment]
When I click on "See" icon to show my website informations (and totp code), i have these error (yeah same error 3 times for 1 click) on the console, but I think it's not related [https://i.imgur.com/I1D0oDx.jpg](https://i.imgur.com/I1D0oDx.jpg)

**Comment by patchbank** [comment]
Have you check if your local time is correct? You can use sites like [time.is](https://time.is/) to check for any difference.

**Comment by BarbossHack** [comment]
Indeed, "Your clock is 1 minute and 50.5 seconds behind."
Thank you @patchbank !

For those who have the same problem on Windows : 
- Go to windows settings
- Search "Date & Time"
- Click on "Sync now" under "Synchronize your clock"

Solved  👍
