### ISSUE TITLE
Password generator option from the context menu is gone

### ISSUE THREAD

**Issue by Rendi-boi** [bitwarden/browser#1266]
With broswer extension version 1.44.2, i can only see auto-fill and copy password/username options, no more generating password into the clipboard ("generate password (copied)" option).
I can't see such change in firefox extension version history (https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/versions/) so i would assume it was deleted by mistake?
Copying TOTP codes from context menu option is also gone.

**Comment by kspearrin** [comment]
It still shows on mine.

**Comment by Rendi-boi** [comment]
https://i.imgur.com/3TRUVCb.png
That's what i see now instead of five options before (there were two additional for totp copy and for generation before).

**Comment by Rendi-boi** [comment]
There are some insights from one user in bitwarden forums. He managed to replicate and kind of fix the issue in Chrome. Unfortunately there doesn't seem to be a similar way to fix this in Firefox if the issue occurred.  https://community.bitwarden.com/t/password-generator-option-from-the-context-menu-is-gone/12415/7

**Comment by foxylion** [comment]
I have exactly the same problem. Maybe this has something to do with [this](https://bitwarden.com/help/article/authenticator-keys/):

> Authenticator key (TOTP) storage is available to all accounts. TOTP code generation requires a premium membership or paid organization account.

I'm not sure if this was always the case. I use a free account and used TOTP generation heavily, now I can't access those accounts with another extension like [TOTP Authenticator](https://chrome.google.com/webstore/detail/totp-authenticator/ibpjepoimpcdofeoalokgpjafnjonkpc/related).

Are we now required to buy a premium account to use TOTP?

**Comment by MattTheDev** [comment]
I'm able to reproduce this:

`if (await this.userService.canAccessPremium()) {
                    await this.contextMenusCreate({
                        type: 'normal',
                        id: 'copy-totp',
                        parentId: 'root',
                        contexts: ['all'],
                        title: this.i18nService.t('copyVerificationCode'),
                    });
                }`

this block of code here, in Firefox, throws an error in the console:

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

By wrapping the call in a try/catch, the context menu completes building.

**Comment by dezza** [comment]
This bug totally halts Firefox ESR and makes it very slow and unresponsive. That error scrolls by in the console window all the time.

**Comment by dezza** [comment]
I see this all the time in console on Firefox ESR 68.12 along with

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
```

**Comment by Rendi-boi** [comment]
So i randomly checked the context menu today. and the option cane back on both places that i use the extension. I don't know if that was intentional fix, and i already got familiar with using keyboard extension for password generation, but really happy that this option came back. Thank you.
