### ISSUE TITLE
Cannot select text in note field

### ISSUE THREAD

**Issue by Fealthas** [bitwarden/browser#1269]
1. Open firefox browser w/ latest bitwarden extension
2.  Open the sidebar bitwarden view (shift-alt-y)
3. Type in desired item in search bar
4. Click it as it pops up below
5. Try to select text in the notes field. ⚠⚠ This does not work. You cannot select any text.

It is mildly annoying, as I use the notes field to store answers to those stupid security questions and it would be nice to be able to just copy paste it in, but I need to be able to select the items first.

Oddly enough, you CAN select the text when just clicking the bw icon and getting the dropdown.

**Comment by kspearrin** [comment]
This appears to be a firefox thing. I cannot find anything in our code that would prevent user selection of text.
