### ISSUE TITLE
Web/Browser Simultaneous login

### ISSUE THREAD

**Issue by ple103** [bitwarden/browser#127]
When I log into the browser extension, I also want to be logged into the web vault and vice versa.

**Comment by kspearrin** [comment]
I am not yet sure of the security implications of allowing something like this. It just sounds wrong though.

I will leave open while I think about it.

**Comment by Primokorn** [comment]
Do you have issues while trying to be connected into the web vault and the browser extension?
It works fine on my end.

**Comment by ple103** [comment]
@Primokorn nope. I just want the same functionality as LastPass.
