### ISSUE TITLE
How to use the Bitwarden API for Ruby (just a little help)

### ISSUE THREAD

**Issue by bdoublet91** [bitwarden/browser#1273]
Hi,

Sorry if I post my question here. I have tried in bitwarden community but get no response and don't manage to fix it on my own.
I try to use the bitwarden API to create entry like you do with the bitwarden plugin.
I reuse the ruby bitwarden API of github project rubywarden

I can post well on /api/ciphers and create the entry but my data aren't well encrypted so I get a null entry on Bitwarden.
https://community.bitwarden.com/t/bitwarden-api-api-ciphers-create-browser/12035/2

May you look at my code in bitwarden community ? Or at least, tell me how to find the code that did it in your project.

Thanks for your help

**Comment by kspearrin** [comment]
We do not support calling our `/ciphers/create` APIs outside of the client apps. Have a look at using the CLI instead. https://bitwarden.com/help/article/cli/
