### ISSUE TITLE
[bug] Takes two clicks to make FF extension pop up

### ISSUE THREAD

**Issue by ndrezn** [bitwarden/browser#1277]
When using BW on FireFox, making the extension properly "pop up" requires clicking the icon once showing the caret to the modal but not the full modal, clicking the icon again to get rid of the caret, and then clicking it a third time to pop up the modal and caret (i.e. the full extension). 

Attaching a photo of the exposed caret and unexposed modal for reference. 

<img width="75" alt="Screen Shot 2020-06-02 at 11 16 36 AM" src="https://user-images.githubusercontent.com/38958867/83537421-86c6af00-a4c2-11ea-8857-ad84661abe98.png">
<img width="127" alt="Screen Shot 2020-06-02 at 11 20 49 AM" src="https://user-images.githubusercontent.com/38958867/83537858-1ff5c580-a4c3-11ea-9c13-32b588724ba7.png">

**Comment by kspearrin** [comment]
Try restarting Firefox.

**Comment by ndrezn** [comment]
Dang, it really was that simple. Thanks!
