### ISSUE TITLE
Clipboard not clearing after X secs on Android 

### ISSUE THREAD

**Issue by L-o-o-t** [bitwarden/browser#1278]
I'm on
 Android 10 
Galaxy tab s6

**Comment by cscharf** [comment]
We were unable to reproduce this behavior with the latest version of Bitwarden, please update and re-open if you're still experiencing this issue.


[ClipboardExample.mov.zip](https://github.com/bitwarden/browser/files/4896767/ClipboardExample.mov.zip)

**Comment by tgreer-bw** [comment]
@cscharf - https://youtu.be/qJOzLGcYNiU example from @L-o-o-t

**Comment by L-o-o-t** [comment]
more info at https://community.bitwarden.com/t/bitwarden-is-not-clearing-the-clipboard/13227/11

**Comment by spit06** [comment]
Hello,

I have the same issue on a Samsung device. As mentioned [here](https://community.bitwarden.com/t/bitwarden-is-not-clearing-the-clipboard/13227/8), Dash lane has this issue solved by replacing the password by multiple dummy values, which overwrite the copied password. Any update on this issue?
