### ISSUE TITLE
Option to generate the MFA/2FA code from the TOTP Key is gone

### ISSUE THREAD

**Issue by kxr** [bitwarden/browser#1279]
I have an account configured with Authenticator Key (TOTP). I used to generate the 2FA with in the browser to fill in the login form. That option is no longer there.

**Comment by kspearrin** [comment]
Do you have premium access?

**Comment by kxr** [comment]
@kspearrin No,  I don't, never had. However it was working before.

**Comment by kspearrin** [comment]
This is a premium feature only. The option was patched in the latest release which should have never been available to non-premium users.
