### ISSUE TITLE
Icon problem with Global Dark

### ISSUE THREAD

**Issue by omnitec** [bitwarden/browser#1282]
Firefox 76,0,1 (64 bit), BW 1.44.3, June 2 2020
![BitWarden Global Dark Icon issue](https://user-images.githubusercontent.com/2415710/83671306-18552000-a59a-11ea-8f74-6dc0f6a07507.png)

Chromium  81.0.4044.138 (64 bit), BW 1.44.3
![BitWarden Normal (Chromiun) Icon](https://user-images.githubusercontent.com/2415710/83671593-8c8fc380-a59a-11ea-9ce8-e03d38176c56.png)

OpenSuSE 15.2 Global Dark theme
The view icon is missing on the FF version., .. also do not understand why there is a difference in the icon sequence.

**Comment by kspearrin** [comment]
Did you disable website icons under Settings > Options?

**Comment by omnitec** [comment]
On Wed, 3 Jun 2020, Kyle Spearrin wrote:

> Did you disable website icons under Settings > Options?
>
Yes, .. verifed disabled.

**Comment by kspearrin** [comment]
Website icons are disabled?

**Comment by omnitec** [comment]
On Wed, 3 Jun 2020, Kyle Spearrin wrote:

> Website icons are disabled?
>
Yes. Not a website icon issue - the icons for the github entry are:

1) Different between Chrome & Firefox for the same entry and vault;
2) The View icon is borked on FF/Global Dark.

**Comment by omnitec** [comment]
Just noticed another problem - 2/3 of the icons at the bottom of the popup are also missing. (Chrome version OK.) Tried reinstalling after deleting any filename including bitwarden, but no difference.

Would really be nice to get the icons back, .. does BW save them somwhere without a bitwarden name in the path?
![Bitwarden More Missing icons 2](https://user-images.githubusercontent.com/2415710/84192103-21913180-aa5f-11ea-829e-712d9f53534f.png)

**Comment by omnitec** [comment]
The icon problem is there with all themes, .. the one just above is default. The biggest issue is that only the tiny tic is 'clickable', instead of an area the size of the icon, so it does appear that the icons are just  not being loaded..

**Comment by kspearrin** [comment]
Those bottom icons are all fetched locally from the font-awesome icon font.

**Comment by omnitec** [comment]
On Tue, 9 Jun 2020, Kyle Spearrin wrote:

> Those bottom icons are all fetched locally from the font-awesome icon font.
>
Interesting, .. suspect it may have been damaged. Is there a way to
reinstall manually?

The only font-awesome packages available for rails.

**Comment by kspearrin** [comment]
It is included in the extension assets when you install it from the store. The only way I know is to reinstall from the store.

**Comment by omnitec** [comment]
On Tue, 9 Jun 2020, Kyle Spearrin wrote:

> It is included in the extension assets when you install it from the store. The only way I know is to reinstall from the store.
>
Already reinstalled multiple times, .. no change. Any way to ensure that
file is gone? Could not find any files with bitwarden in the path before
or after installation.

**Comment by omnitec** [comment]
Possible conflict with another extension?

Looks like the binary is: {446900e4-71c2-419f-a6a7-df9c091e268b}.xpi, .. installed two hours ago.

**Comment by omnitec** [comment]
Removed BW from Firefox; logged out; removed all files with 446900e4 in the name (including (including the directory in browser-extension-data/{446900e4-7); started firefox, reinstalled, .. received the "new login email" so BW thinks it is a new installation, .. could BW be affected by a font-awesome installation from another extension?

**Comment by omnitec** [comment]
Deleted ALL font-awesome files on this system, .. still having the same problem. It's almost impossible to view an entry in the valut, as without the icon, everything is "autofill".

Normal on Chromium:
![Bit Warden Chromium](https://user-images.githubusercontent.com/2415710/85335783-2d3f1800-b4a3-11ea-8377-575b84b8039f.png)

Icons missing on Firefox:
![Firefox Icons Missing](https://user-images.githubusercontent.com/2415710/85335791-316b3580-b4a3-11ea-947c-5dc472bde2e8.png)
..
Appreciate any thoughts to possible cause, ..

**Comment by omnitec** [comment]
1.57.0 no longer has the problem, ..
