### ISSUE TITLE
On some pages with both login and register fields, BW fills both

### ISSUE THREAD

**Issue by 64kramsystem** [bitwarden/browser#1283]
On some pages with both login and register fields, for example [Hacker News](https://news.ycombinator.com/login?goto=news), or Facebook.

This is quite annoying, because after filling, the default button is typically the register, which forces the use to manually select and click the login button, instead of just tapping Enter.

My Browser is Firefox 76, on Linux.

**Comment by kspearrin** [comment]
I too noticed this, but I am not sure if a way to distinguish the two.
