### ISSUE TITLE
`Cmd + 9` is not working for auto-fill in Safari

### ISSUE THREAD

**Issue by sevensixseven** [bitwarden/browser#1285]
Cmd + 9 does not seem to work in Safari on macOS. This hot key can be very useful for users not using a QWERTY keyboard layout.

**Comment by kspearrin** [comment]
This was added in the last release. Have we confirmed it is not working in the latest?

**Comment by mportune-bw** [comment]
Cmd + 9 isn't doing anything for me (plugin 1.44.2) - Is it possible something else is stealing the keypress?

**Comment by cscharf** [comment]
I wonder if this caused it with the last release? https://github.com/bitwarden/browser/blob/e12cce711c071dc055dd154110f7e21ec2368c84/src/safari/safari/SafariExtensionViewController.swift#L157

**Comment by cscharf** [comment]
I had added some type safety checks and added this code above to see if that may have been causing the crash, but without understanding the popoverOpenCount impacts. I wonder if that change could be impacting the hot-key.

**Comment by kspearrin** [comment]
Hotkey is defined here:
https://github.com/bitwarden/browser/blob/master/src/content/shortcuts.ts#L21

Does the old `Cmd + |` work still?

**Comment by mportune-bw** [comment]
`Cmd + \` works for me.

**Comment by kspearrin** [comment]
Hmm, this is the library that we use:

https://craig.is/killing/mice

**Comment by kspearrin** [comment]
For some reason `Cmd + 9` does not work in Safari. `Cmd + 8` seems to work, however. Is that good enough?
