### ISSUE TITLE
Login auto-matching fails if URI in any login entry contains a malformed URL

### ISSUE THREAD

**Issue by JackBeQuick87** [bitwarden/browser#1295]
Bitwarden does not auto-match a login to the webpage currently open.  Instead, the addon's "Tab" tab permanently displays loading animation.  "Search vault" search box still works.
<nbsp>
<img name="Bitwarden-pane-error-state" src="https://user-images.githubusercontent.com/9307520/84922012-4145dc80-b093-11ea-94bf-e63fac843821.png" width="33%" height="33%">

Right-clicking in the website's form and using the "Bitwarden>Auto-fill" context menu shows the message "Vault is locked" even while the vault is unlocked.

Debug output shows:
``` ERROR Error: "Uncaught (in promise): URIError: malformed URI sequence... ```

A malformed URL in any login entry will break match detection for all entries, not just said entry.

Found on Firefox 77.0.1 (64-bit) using a fresh, default Firefox profile.

__Steps to reproduce:__
1. Create a new login entry (or add to an existing) with
 -  **URI** set to **%80@host**
 -  **match detection** set to "**Base domain**".
2. Visit a web page that has a proper/previously working login entry and reopen the Bitwarden pane or refresh it by clicking on "Tab".

**Troubleshooting notes:**

The issue is strongly related to the "%" (percent sign) in the URL/URI.
Based on my experiments with the URIs, I've put together a the following template for a URI which will break the auto-match function:

URI template: 
&nbsp;&nbsp;&nbsp;&nbsp; **%**[_hex number higher than 7f_]**@**[_host_]**.**[_non-gTLD_]  (https://en.wikipedia.org/wiki/Generic_top-level_domain)

```
- Works:	%70@host
- Broken:	%80@host
- Works:	%80host
- Works:	%80@host.com
- Works:	%80@host.org
- Broken:	%80@host
- Broken:	%80@host.sdl
- Broken:	username:passwd%80@host.non-gTLD
- Broken:	%80@host.non-gTLD
```

I discovered this after saving a URL with an in-URL username/password combination containing a percent sign.

**Comment by cscharf** [comment]
@JackBeQuick87 , what is the OS + version you're currently running Firefox 77.0.1 (64-bit) on?

**Comment by JackBeQuick87** [comment]
> @JackBeQuick87 , what is the OS + version you're currently running Firefox 77.0.1 (64-bit) on?

Windows 8.1, 64 bit.

**Comment by djsmith85** [comment]
Closing this as this was fixed with https://github.com/bitwarden/jslib/pull/123
