### ISSUE TITLE
What can I do if Bitwarden can't autofill fields?

### ISSUE THREAD

**Issue by Vinz87** [bitwarden/browser#1297]
Is there something I can do if Bitwarden says it can't fill in a website fields? Changing the pointed url with something more specific could help? Thanks

**Comment by MattTheDev** [comment]
@Vinz87 Thanks for submitting this issue. In order to help, could you provide more detail? Maybe an example of what you're trying to do that won't work? This will better help me get you taken care of.

**Comment by MattTheDev** [comment]
We’ve been unable to reproduce this issue ourselves. If this issue persists, please reopen it, and we’d be happy to help resolve the problem.

**Comment by Vinz87** [comment]
Hi, for example I noticed this behaviour on the login form of the [Home Assistant](http://www.home-assistant.io) Front-End, but given the nature of the application it's obviously a local installation, I don't know if you can replicate it.
