### ISSUE TITLE
Would it be possible to change the server address in settings.

### ISSUE THREAD

**Issue by elsimir** [bitwarden/browser#13]
Given that this is open source the ability for individuals or small companies to run a private install of the server software would be appreciated. From what I can see this should just require setting the API url from settings instead of the hardcoded api.bitwarden.com. I am happy to help out with this work if you would want to support this.

**Comment by kspearrin** [comment]
This is now planned for an upcoming release.

**Comment by kspearrin** [comment]
This is done for next release.
