### ISSUE TITLE
Firefox extension displays blank dialog when used with RequestPolicy extension

### ISSUE THREAD

**Issue by josh-parris** [bitwarden/browser#130]
![screenshot-the best free password manager bitwarden - mozilla firefox](https://cloud.githubusercontent.com/assets/7473103/24907522/f53fbde2-1eff-11e7-9c18-0ab7a224d178.png)
Interaction problem between bitwarden and RequestPolicy, I _presumed_ that the dialog is loaded from the intertubes somewhere and RequestPolicy was nixing it. When web pages get up to these shenanigans, the RequestPolicy UI is able to tell me what's blocked, but that I can't interact with it while the bitwarden dialog is up; once it's down there's nothing that RequestPolicy is blocking.  The developer console doesn't report any errors.  The RequestPolicy log doesn't show that it's blocking anything.  Checking RequestPolicy's "Temporarily allow all requests" does no resolve the problem. Disabling the RequestPolicy extension resolves the problem; this makes me sad.

RequestPolicy 0.5.28.1-signed.1-signed
bitwarden 1.10.1
FireFox 52.0.2
Linux Mint Maya

**Comment by kspearrin** [comment]
Hm, I am not really sure what could be happening here without the logs, but it appears some javascript is being blocked from the extension, causing it to fail. This same thing has been reported when using the NoScript addon in Firefox and clocking rules have to be adjusted. I don't use that plugin so I am unfamiliar with it.

Is there some rules engine built into that addon where you can whitelist domains or anything?

When I get some time I can check it out. In the meantime, if you find a solution please let me know.

**Comment by josh-parris** [comment]
Yes, domains can be whitelisted with no trouble.

What logs do you need?

As an aside, I'm using NoScript without trouble, but I did whitelist bitwarden.com to use the vault

**Comment by kspearrin** [comment]
Try whitelisting `moz-extension://8ec1de8a-be8b-476c-ade8-df7359092073`, which is bitwarden.

**Comment by josh-parris** [comment]
whitelisting moz-extension://8ec1de8a-be8b-476c-ade8-df7359092073 and bitwarden.com - both as origin and destination - has no effect, which is consistent with 'Checking RequestPolicy's "Temporarily allow all requests" does no resolve the problem'

This is a weird interaction, and I'm willing to forgo RequestPolicy in lieu of bitwarden, but it would be nice to know what the heck's going on here.  That coupled with "these are extensions that the tin foil hat brigade will probably want to use together".

**Comment by kspearrin** [comment]
@josh-parris If you have some time, would you mind joining me in our dev chatroom to try and troubleshoot further? https://gitter.im/bitwarden/Lobby

**Comment by josh-parris** [comment]
Sure

**Comment by josh-parris** [comment]
Solution: Ditch RequestPolicy, replace with RequestPolicy Continued. Stored settings are carried over transparently.
