### ISSUE TITLE
Autofill shouldn't be applied to one-time passcodes fields

### ISSUE THREAD

**Issue by tetafro** [bitwarden/browser#1301]
## Describe the Bug

I have a form (which is not public available), which has an input for one-time passcodes (from sms). Bitwarden plugin autofills this field. I believe it shouldn't.

## Steps To Reproduce

As I said, the form is not public available, but I can provide html of the input field:
```
<input id="oneTimePasscodeInput" name="OneTimePasscode" type="password" value="" class="fullWidth text " data-com.bitwarden.browser.user-edited="yes">
```

This field is autofilled on page load.

## Expected Result

The field is not autofilled.

## Actual Result

The field is autofilled on page load.

## Environment

- Operating system: Linux Mint 19.1
- Browser: Firefox 77.0.1 (64-bit)
- Build Version: 1.44.3

**Comment by kspearrin** [comment]
Bitwarden autofills input fields of `type="password"`. We don't have a way to distinguish non-password fields that are marked as passwords.

**Comment by tetafro** [comment]
Then I guess the issue can be closed.
