### ISSUE TITLE
Credentials are not captured on https://users.rust-lang.org

### ISSUE THREAD

**Issue by 64kramsystem** [bitwarden/browser#1303]
## Describe the Bug

When registering a new user on https://users.rust-lang.org, the credentials are not captured.

## Steps To Reproduce

Register on https://users.rust-lang.org

## Environment

- Operating system: Ubuntu 20.04
- Browser: Firefox 77.0.1
- Build Version: 1.44.3

**Comment by djsmith85** [comment]
Hi @64kramsystem thank you for your report. I'm closing this here and link to #1620 where we are tracking this .
