### ISSUE TITLE
Autofill filling in password of website into text field

### ISSUE THREAD

**Issue by Taomyn** [bitwarden/browser#1307]
## Describe the Bug

I use an MDaemon mail server and its WorldClient webmail client - I'm actually part of their beta team and have discussed this with them to check it wasn't something they were doing. I have tested this with the Chrome extension under Chrome, Edge and Brave, and they all do the same.

The account I connect with has 2FA enabled. At the main login page I am asked just the account name and password, with an option to save the credentials. Then at the next screen I am asked for my authenticator code, again with an option to save this.

Bitwarden works perfectly on the first page, and autofills this as expected. However for the next page and the request for the authenticator code it also autofills that in, but with the password for the account. As the field is text and in the clear, it's visible for anyone to see.

## Steps To Reproduce

I would need to arrange a test account for my mail server which I cannot for obvious reasons provide here. But the steps to reproduce are above.

## Expected Result

Should not be autofilling the authenticator field

## Actual Result

Fills the authenticator field, clear text, with the account password.

## Screenshots or Videos

This is the HTML code of the main logon page which works fine:
![image](https://user-images.githubusercontent.com/4365929/85572278-22b48800-b635-11ea-9271-cf267084c312.png)

This is the HTML for the authenticator page:
![image](https://user-images.githubusercontent.com/4365929/85572372-35c75800-b635-11ea-8462-16ce1baf491c.png)

## Environment

- Operating system: Windows 10
- Browser: [e.g. Chrome/Edge/Brave v83]
- Build Version (go to "Settings" → "About" in the app): 1.44.3

**Comment by kspearrin** [comment]
This is happening because the OTP field has a name with "password" in it.

A workaround to this issue is to use a custom field to explicitly define the password field for this website. You could use a hidden field with name "password" and it should work.

**Comment by jpehman** [comment]
Would it not be more prudent to add an exception that looked for "OneTimePassword" and returned false?

**Comment by luckman212** [comment]
@kspearrin I didn't know about that trick, but it came very much in handy today with a login page field that wasn't recognized ([Mailstore Server](https://www.mailstore.com/en/products/mailstore-server/)). Thanks for the tip!
