### ISSUE TITLE
Two password reveal buttons on login and unlock fields on Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#1308]
## Describe the bug
When you input any charater into the login and unlock fields on Microsoft Edge (Chromium) a second password reveal icon is generated by Microsoft Edge.

## Steps to reproduce
Enter any characters into the login or unlock password field.

## Expected result
Microsoft Edge doesn't generate a second password reveal button.

## Actual result
Microsoft Edge does generate a second password reveal button

## Screenshots
![Login popup](https://i.imgur.com/FVqhkbb.png)
![Unlock popup](https://i.imgur.com/ydLfxc9.png)

## Environment
- Operating system: Windows 10 Pro Education v2004 x64
- Browser: Microsoft Edge (Chromium) v83.0.478.56
- Build version: 1.44.3

**Comment by djsmith85** [comment]
Closing this as this was fixed and merged with https://github.com/bitwarden/browser/pull/1325
