### ISSUE TITLE
Login on Safari extension fails with error: "An error has occurred Origin file:// is not allowed by Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by dh024** [bitwarden/browser#1311]
## Describe the Bug
Safari browser extension cannot login; generates error: "An error has occurred
Origin file:// is not allowed by Access-Control-Allow-Origin."

Sync on a locked vault fails without generating a specific error message.

## Steps To Reproduce

1. Open Bitwarden extension on Safari (logout first if vault is currently locked).
2. Click on Login and enter credentials

## Expected Result
Successful login using appropriate credentials.

## Actual Result
Generates error:  "An error has occurred Origin file:// is not allowed by Access-Control-Allow-Origin"

## Screenshots or Videos
https://community.bitwarden.com/uploads/default/original/2X/4/466ec9507f1d51faf3d2ec5e1ff5cb2443ed45e5.png

## Environment

- Operating system: MacOS Mojave 10.14.6
- Browser: Safari 13.1.1
- Build Version (go to "Settings" → "About" in the app): Bitwarden extension 1.44.2

## Additional Context
I first noticed this behavior after updating Safari to version 13.1.1. (May be a coincidence.)

**Comment by dh024** [comment]
See also user reports on BW community forum:
https://community.bitwarden.com/t/access-control-allow-origin/13015
https://community.bitwarden.com/t/help-please-error-access-control-allow-origin/13017

**Comment by kspearrin** [comment]
This should be fixed now.
