### ISSUE TITLE
No Identies on Tab page

### ISSUE THREAD

**Issue by mirdaki** [bitwarden/browser#1313]
## Describe the Bug

Hello, I do not see the identities I have on the "Tab" page. When I look through my vault I still find them under the Identity section, so they still exist. I recently switched to the Flatpak version of Firefox, my guess is that is related.

## Steps To Reproduce

1. Open up Firefox Flatpak
2. Click on Bitwarden Extension in the top bar or the side bar

## Expected Result

To see the Identity section under the Logins and Cards section.

## Actual Result

No Identity section.

## Screenshots or Videos

![bitwarden](https://user-images.githubusercontent.com/8786151/85952405-e9726580-b91d-11ea-8ccd-8e82393c8629.png)

## Environment

- Operating system: Fedora 32
- Browser: Firefox 77.0.1 [Flatpak](https://flathub.org/apps/details/org.mozilla.firefox)
- Build Version: 1.44.3

## Additional Context

I might be able to do some debugging if you can't reproduce.

**Comment by kspearrin** [comment]
Is that section disabled under Settings  > Options?

**Comment by mirdaki** [comment]
Oh yes it is. My bad. Guess I accidentally hit it when I was scrolling through the settings. Thank you for your help!
