### ISSUE TITLE
Bitwarden keeps asking main password

### ISSUE THREAD

**Issue by Vinz87** [bitwarden/browser#1316]
## Describe the Bug
Despite the Timeout Setting being "at browser restart" or "after 4 hours", Bitwarden keeps asking the main password to unlock after a few minutes.

## Environment

- Operating system: macOS High Sierra
- Browser: Safari 13.1.1
- Build Version (go to "Settings" → "About" in the app): 1.18.0

**Comment by cscharf** [comment]
This is a duplicate of https://github.com/bitwarden/browser/issues/1021
