### ISSUE TITLE
Browser extension window does not open correctly requiring multiple clicks 

### ISSUE THREAD

**Issue by dietofworms** [bitwarden/browser#1317]
## Describe the Bug
Bitwarden Firefox extension does not open on first click of icon, requiring multiple clicks of the icon to open it properly. On the first click, it appears hidden or cut off.

## Steps To Reproduce
1. Navigate to any website where you have saved login credentials in Bitwarden;
2. Go to the login page;
3. Click on the Bitwarden icon in the top right of your browser window (your position may vary) as if you were going to auto-fill credentials;
4. The Bitwarden window will not open, instead it appears hidden or cut off (note: this happens every second time, not every time).

## Expected Result
The Bitwarden window should open revealing my login credentials for the page I am on.

## Actual Result
The window does not open. Instead, it appears cut off and hidden. This requires me to press the icon again to close the hidden window, and then press it again to open it which works.

## Screenshots or Videos
<img width="276" alt="Firefox Bitwarden Window Not Opening" src="https://user-images.githubusercontent.com/28944297/86202508-b6da9e00-bba5-11ea-9de4-50001f0c05ed.png">

## Environment
- Operating system: macOS Catalina
- Browser: 77.0.1 (64-bit)

**Comment by kspearrin** [comment]
This happens on Firefox when a Bitwarden extension update occurs. Restart firefox to fix it. No idea why.

**Comment by dietofworms** [comment]
@kspearrin that worked for me however, I had to restart the application twice. No idea why the first one didn't register but figured it was worth mentioning.
