### ISSUE TITLE
Prompt to save new entry doesn't showup when vault is locked

### ISSUE THREAD

**Issue by dhrunia** [bitwarden/browser#1324]
## Describe the Bug

Prompot to save new login entries is not showing up when the vault is locked. After unlocking the vault and retrying the login made the prompt work.

## Steps To Reproduce

How can we reproduce the behavior:

1. Register on https://pnascentral.org
2. Go to the login page https://www.pnascentral.org/cgi-bin/main.plex
3. Make sure the vault is locked
4. Login with the credentials created in step 1

## Expected Result

Bitwarden should prompt to save the new entry

## Actual Result

No prompt is shown unless the vault is unlocked

## Environment

- Operating system: Ubuntu 20.04
- Browser: Firefox 78.0.1 (flatpak)
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by clayadams5226** [comment]
This is the expected behavior. You must be logged into your vault (and unlocked) in order to make any changes to it.

**Comment by dhrunia** [comment]
Okay, but it would be great if it can prompt to save new logins while lthe vault is locked and then if I press save it can prompt for password/pin.

**Comment by cscharf** [comment]
Agreed that may be a valuable add or behavioral change. I would highly recommend you search our community forums to see if there has already been [a feature request](https://community.bitwarden.com/c/feature-requests) and if not feel free to make a request there so the community can provide feedback, vote, etc. and we don't lose sight of it. 

This issue will now be closed. Thanks!
