### ISSUE TITLE
Can not autofill account number on Mullvad desktop site

### ISSUE THREAD

**Issue by GHF** [bitwarden/browser#1328]
## Describe the Bug

The Bitwarden Firefox plugin does not auto-fill the login credentials for Mullvad's web interface.

## Steps To Reproduce

1. Go to https://mullvad.net/en/account/#/login
2. Click on Bitwarden extension button in Firefox toolbar
3. Click on the appropriate saved login for mullvad.net

## Expected Result

The login page's account number page is filled in.

## Actual Result

Bitwarden overlay shows an error message, "Unable to auto-fill the selected item..."

## Environment

- Operating system: Windows 10 1909
- Browser: Firefox 78.0.2
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by kspearrin** [comment]
You should use custom fields for this scenario. See https://bitwarden.com/help/article/custom-fields/
