### ISSUE TITLE
Master password field is readonly

### ISSUE THREAD

**Issue by artee666** [bitwarden/browser#1329]
#1320  Describe the Bug

After installing bitwarden, I cannot log in into my account as I'm able to input my email address, but "Master password" field is not editable. It seems to be read only.

## Steps To Reproduce

This happens to me on google chrome 83 and 84.

## Expected Result
I should be able to enter master password and login to my account.

## Screenshots or Videos

This is html code for the Master password element:

`<input appinputverbatim="" class="monospaced ng-untouched ng-pristine ng-invalid" id="masterPassword" name="MasterPassword" required="" autocomplete="off" autocapitalize="none" autocorrect="none" spellcheck="false" inputmode="verbatim" type="password">
`

**Comment by daveliao** [comment]
@artee666 - is this still happening for you?

I can't reproduce the issue; I'm using Chrome 84 (stable) in Windows 10. I can log into the Chrome extension without issue.

**Comment by artee666** [comment]
@daveliao - it is specific to one of my computers... It is working on one, on the other one it is not... I'm using gentoo linux... Might be issue with filesystem ownership or something... I will close this issue. Sorry for bothering,
