### ISSUE TITLE
working with on-premise installation?

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/browser#1335]
Hi,

This issue is similar to [this one](https://github.com/bitwarden/browser/issues/352) but the code has changed quite a bit since then so the info there is probably no longer relevant.

I just compiled the extension to test it with Chrome on my on-prem installation. If I change the baseURL through the GUI it works as expected.

But if I change the apiBaseURL in https://github.com/bitwarden/jslib/blob/94d363bfca687f70a056e027b6646f49e5d0293d/src/services/api.service.ts#L152
like so

```
// Production
        if (this.apiBaseUrl == null) {
           this.apiBaseUrl = 'https://my.domain.com';
        }
        if (this.identityBaseUrl == null) {
            this.identityBaseUrl = 'https://my.domain.com';
        }
        if (this.eventsBaseUrl == null) {
            this.eventsBaseUrl = 'https://my.domain.com';
```

When I try to login through the extension I get the red error warning sign with the following text which doesn't help much in debugging:

An error occurred.
An unexpected error has occurred

I thought this was the proper way to hardcode the baseURL on our server programatically but it doesn't seem to work.
Any ideas?

Thanks

**Comment by cscharf** [comment]
Are those URLs fully qualified to your on-prem install's endpoints for each of those services? It's a bit different overriding here vs. in the UI, where you can assign a single base url, these each expect the literal endpoints to the respective services at that base URI (e.g., `this.eventsBaseUrl = 'https://my.domain.com/events';`, etc.)

**Comment by pdarcos** [comment]
Thanks @cscharf 

I'll try to debug using dev tools and will report back.

Cheers

**Comment by pdarcos** [comment]
That did it. 
I had to adjust the path in the backend.
Thanks
