### ISSUE TITLE
Auto-fill not working on Pinned Tabs in Safari

### ISSUE THREAD

**Issue by crazybadger** [bitwarden/browser#1340]
## Describe the Bug

When using the Safari extension, sites 'pinned' to the tab bar can't be auto-filled and display the message 'Unable to auto-fill the selection on this page. Copy and paste the information instead'.  The same page unpinned will auto-fill the selection.

## Steps To Reproduce

Right-click a browser tab in Safari with login details and then select Pin Tab.  Try using Bitwarden to auto-fill this.

## Expected Result

If the tab isn't Pinned this would work, but when Pinned it doesn't.  This isn't a problem on Chrome, although Chrome is a little power hungry on macOS

## Actual Result

Display the message 'Unable to auto-fill the selection on this page. Copy and paste the information instead

## Environment

- macOS 11.15.6 Catalina
- Browser: Safari 13.1.2 (15609.3.5.1.3)
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/browser/issues/1018
