### ISSUE TITLE
Error while loading the Chrome extension unpacked/manually

### ISSUE THREAD

**Issue by lasombra** [bitwarden/browser#1343]
## Describe the Bug

I'm using ungoogled-chromium, https://github.com/Eloston/ungoogled-chromium, and I load extensions by unpacking them and loading them in developer mode.

When trying to load the BitWarden Chrome extension I receive the following error message:
```
Localisation used, but default_locale wasn't specified in the manifest.
```

## Steps To Reproduce

1. Install ungoogled-chromium
2. Download the BitWarden extension, https://github.com/bitwarden/browser/releases/download/v1.45.0/dist-chrome-2598.zip, for example
3. Unzip the extension
4. On Chromium, go to the **Extensions** page, chrome://extensions/, switch **Developer mode** on and click on **Load unpacked**
5. Locate the directory where the extension was unpacked and click on **Open**

## Expected Result

The extension should be installed and enabled.

## Actual Result

The error message, ```Localisation used, but default_locale wasn't specified in the manifest.```, shows up instead.

## Environment

- Operating system: Fedora 32
- Browser: ungoogled-chromium from the RPMFusion repository
- Build Version (go to "Settings" → "About" in the app): 84.0.4147.89

**Comment by lasombra** [comment]
Sorry, found the issue. The permissions of the unpacked directory are wrong.

```
modok :: ~/Apps/bitwarden.chromium % ls -l
total 4.8M
-rw-rw-rw-  1 user user  188 Jun 29 19:05 background.html
-rw-rw-rw-  1 user user 2.3M Jun 29 19:05 background.js
drw-rw-rw-  2 user user 4.0K Jun 29 19:05 content
drw-rw-rw-  2 user user 4.0K Jun 29 19:05 images
drw-rw-rw- 40 user user 4.0K Jun 29 19:05 _locales
-rw-rw-rw-  1 user user 2.0K Jun 29 19:05 manifest.json
drw-rw-rw-  2 user user 4.0K Jun 29 19:05 notification
drw-rw-rw-  4 user user 4.0K Jun 29 19:05 popup
-rw-rw-rw-  1 user user 2.5M Jun 29 19:05 vendor.jmodok
```

After running ``` find . -type d -exec chmod 0755 {} \;``` and ```find . -type f -exec chmod 0644 {} \;```, the issue was fixed.

**Comment by lasombra** [comment]
I know this has been closed, but should be packaging process be fixed to account for this issue?

**Comment by cscharf** [comment]
Not sure I understand the issue... Are you asking for file and folder permissions to be correctly transferred through Zip packaging for extraction for this purpose, or whether a `default_locale` be specified in the manifest? The `default_locale` is specified in the manifest already as `en`, and at this moment I do not believe we can or will change file/folder permissions on our build server prior to the gulp webpack operation that creates the ZIP file as this would also require additional and extended testing of those packaged extensions to the various browser stores and/or create possible permissions issues outside of what's there today. Is the only issue you're having with the permission the missing `x` option for directories allowing navigation/entry (assuming that's needed for unpacked side-loading by the browser to scan/load the files)? For now we may add something to the FAQ regarding this but at this time we likely won't create a fix.

**Comment by lasombra** [comment]
@cscharf, the latter option. The missing `x` is necessary for directory traversal on Linux, making sideloading without this manual step impossible.

The manifest is correct, I interpreted the error at face value. The real issue is the wrong directory permissions.
