### ISSUE TITLE
Login fail at Chinese's Network

### ISSUE THREAD

**Issue by ScottliuNonwin** [bitwarden/browser#1346]
![IMG_20200731_135810](https://user-images.githubusercontent.com/58081491/89004964-ed870e00-d335-11ea-9b67-c6d4808f8c61.JPG)

**Comment by ScottliuNonwin** [comment]
@bitwarden

**Comment by kspearrin** [comment]
It seems your machine is having trouble reaching our servers. Could you test another network?
