### ISSUE TITLE
Filled login is not recognize by website

### ISSUE THREAD

**Issue by szymon-wesolowski** [bitwarden/browser#1350]
## Describe the Bug

Bitwarden fill login edit box but the value is not set. The website thinks field is empty.

## Steps To Reproduce

1. Go to https://login.nestbank.pl/login
2. Autofill login
2. Click on Dalej (Next) button

## Expected Result

Move to next page after click on Dalej (Next) button

## Actual Result

Enter the login is still required with error message: Aby kontynuować musisz wpisać poprawny login. (You must enter a valid login to continue)

## Environment

- Operating system: Windows 10
- Browser: Chrome  84.0.4147.105
- Build Version 1.45.0

**Comment by Greenderella** [comment]
You may just need to configure a custom field for this entry: https://bitwarden.com/help/article/custom-fields/
![image](https://user-images.githubusercontent.com/5418577/89634751-254a0480-d8a6-11ea-8ea8-c2a909b30bf1.png)

**Comment by szymon-wesolowski** [comment]
Have you clicked Dalej (Next) button?
![image](https://user-images.githubusercontent.com/33084923/89681941-2f93ef00-d8f6-11ea-8e98-47aa1044f4c1.png)
Bitwarden does not change the value of this field.
When I fill the box manulay the value is changed.
![image](https://user-images.githubusercontent.com/33084923/89682049-5f42f700-d8f6-11ea-8e99-94cf6717fb2a.png)

**Comment by szymon-wesolowski** [comment]
Same situation is on this site https://www.pekao24.pl/logowanie.
Bitwarden seems to fill all boxes but they are empty for the page.
![image](https://user-images.githubusercontent.com/33084923/89682250-b8128f80-d8f6-11ea-9d53-87d3467b0fd6.png)
You can see filed dots in boxes but the warning on the top of the site say: You have to fill all boxes.

**Comment by szymon-wesolowski** [comment]
Please reopen this bug, you have not complete all the repoduce steps.
