### ISSUE TITLE
extension lockout every browser start, no matter which timeout i selected

### ISSUE THREAD

**Issue by rampolino** [bitwarden/browser#1352]
extension lockout every browser start, no matter if i select at system lock, or 4 hours.

- Operating system: Windows 10
- Browser: Chrome Version 84.0.4147.105
- Build Version 1.45.0

**Comment by kspearrin** [comment]
This is the expected funntionality at the moment.

**Comment by rampolino** [comment]
Ok, but Chrome on Mac the vault is open until System is locked. Chrome on Win10 vault locked if i close browser.

**Comment by lhecht** [comment]
I have the same issue.
I don't understand, why this is the expected functionality. I use the option vault-timeout on system lock and would like bitwarden to behave that way.

**Comment by clayadams5226** [comment]
When some web browsers are closed then the process is completely stopped, any time the process itself is stopped then the web browser will automatically lock regardless of the lock option set. This is a security measure put in place for your protection, the unlock options come into play while the browser process is running.
