### ISSUE TITLE
Hiding the bitwarden extension GUI and then re-clicking it makes the search bar lose its search/progress

### ISSUE THREAD

**Issue by Lilja** [bitwarden/browser#1357]
## Describe the Bug
When you search for something, then let's say copy the username and paste it on the website, you click the background to lose focus and close the app's window. Doing so, you lose the search bar input and have to search twice. This is really annoying.

In this video I try to log into Github but have to search for github twice.

![ezgif-6-d36d6cdb3085](https://user-images.githubusercontent.com/6134511/90114013-6af94800-dd52-11ea-921d-0d655fb49918.gif)

## Expected Result
The input state is preserved.

## Environment

- Operating system: Windows 10
- Browser: Firefox 79.0 
- Build Version: 1.45.0

**Comment by kspearrin** [comment]
This is a known limitation of the browser. We cannot control keeping the window open on focus changes. We do offer the ability to "pop out" the window, however. Click the icon in the top left corner.
