### ISSUE TITLE
Trying to get the status code.

### ISSUE THREAD

**Issue by lmk07** [bitwarden/browser#1359]
Hi guys,
            i'm trying to fetch the details from network activity in browser using javascript, i need to get the status code of each and every resource while page loading and interaction happens in page. Any one can help me to get this... Thanks in advance.

![Capture](https://user-images.githubusercontent.com/66107540/90236045-d836d700-de3f-11ea-9fbb-0a522a0cf3b1.JPG)

**Comment by Greenderella** [comment]
Hi, could you help us understand why do you need those status codes?

**Comment by Greenderella** [comment]
If you are trying to get the network details in your browser regarding the extension itself, you will need to go to chrome://extensions and turn on Developer Mode:

![image](https://user-images.githubusercontent.com/5418577/90269063-4edfce80-de58-11ea-891d-d28adcc89779.png)

Then you will see a link to inspect the background.html page, which can lead them to the network traffic/communication and JS world of our browser extension.

**Comment by lmk07** [comment]
@Greenderella  Hi, i want it as javascript code, which should work in all the browser. Thank you.

**Comment by cscharf** [comment]
Hi @lmk07 , hopefully that gets you the information you need. For now I'm going to close this issue as it looks like Alex has answered your question. Please let us know if you run into any issues or feel free to re-open this if necessary.
