### ISSUE TITLE
Search does not look in NOTES

### ISSUE THREAD

**Issue by wsw70** [bitwarden/browser#1360]
## Describe the Bug

Search does not search in NOTES

## Steps To Reproduce

1. add a keyword in the NOTES section of any entry
2. try to search for this keyword from the global search
3. the search fails (does not return the entry with the keyword)

## Expected Result

Search is done against all available fields of an entry.

## Actual Result

It does not (at least for NOTES)

## Environment

- Operating system: Windows 10
- Browser: Chrome 84
- Build Version (go to "Settings" → "About" in the app): 1.45.0

## Additional Context

The issue is also present in the Android app (https://github.com/bitwarden/mobile/issues/1040)

**Comment by cscharf** [comment]
Thank you for getting in touch and bringing this to our attention! We are not able to reproduce this issue but we'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by wsw70** [comment]
@cscharf Thank you for follwing up. Before moving to the helpdesk, could you please make the specific test below?

I created an item such as

![image](https://user-images.githubusercontent.com/1345886/90287106-7db96d00-de77-11ea-93b2-135d4cfe38ef.png)

Then I tried to search for 

- `azert` (**without the `y`**) → the search failed
- `azerty` (by adding the `y` to the search above) → the search succeeded

![image](https://user-images.githubusercontent.com/1345886/90287242-bb1dfa80-de77-11ea-8550-16f772425484.png)

![image](https://user-images.githubusercontent.com/1345886/90287276-c96c1680-de77-11ea-8c9a-072399a16b22.png)


It therefore looks like a **partial** search in NOTES fails (such a partial search works for other fields)

**Comment by kspearrin** [comment]
wildcards are automatically applied to popular fields like name, username, URL. For tohers (like notes), you need to use the wildcard yourself.

`azert*`

**Comment by wsw70** [comment]
@kspearrin thanks - this is a very useful information
