### ISSUE TITLE
Bitwarden auto-fills login and registration form on the page.

### ISSUE THREAD

**Issue by dragi-ns** [bitwarden/browser#1361]
## Describe the Bug

When using the Bitwarden's auto-fill to log in, both forms (login and registration) are filled, which makes the login form disabled.

## Steps To Reproduce

1. Go to 'https://www.oglasi.rs/korisnici/prijava/stari'
2. Use auto-fill

## Expected Result

Only the login form should be filled.

## Actual Result

Both forms, login and registration, are filled which makes login form disabled and I can't press the "Prijavi se" ("Log in/Sign In") button.

## Screenshots or Videos

Before auto-fill (left login, rigth registration):
![Before auto-fill](https://i.imgur.com/c3kHZbn.png "Before auto-fill")

After auto-fill (left login, rigth registration):
![After auto-fill](https://i.imgur.com/Q7GMsz3.png "After auto-fill")

## Environment

- Operating system: Solus OS Release 4.1 64-bit
- Browser: Firefox 79.0 (64-bit)
- Build Version 1.45.0

## Additional Context

None

**Comment by Greenderella** [comment]
You need to generate 2 custom fields (https://bitwarden.com/help/article/custom-fields/) with these names: 
![image](https://user-images.githubusercontent.com/5418577/90333224-64720700-dfc4-11ea-9892-ae27884fa07e.png)

**Comment by dragi-ns** [comment]
Thank you, I didn't know that there are custom fields option.

I have used the `username` for name, instead of the placeholder text.
Also, I have used the `hidden` field type instead of the `text` for the password.

![Screenshot_at_2020-08-16_13-46-39](https://user-images.githubusercontent.com/54716240/90333735-735ab880-dfc8-11ea-9465-feb7bcb86898.png)
