### ISSUE TITLE
"Get the apps" hyperlink points to wrong url

### ISSUE THREAD

**Issue by adamwinn** [bitwarden/browser#1362]
## Describe the Bug

In the web vault, when you click on your user icon and see the dropdown of a list of actions to take, one of them is "Get the apps".  Clicking on that takes you to `https://bitwarden.com/#download`, rather than the correct url of `https://bitwarden.com/download/`

## Steps To Reproduce

1. Log into the web vault
2. Click the user icon in the top right
3. Click on "Get the apps"

## Expected Result

User is taken to the download page

## Actual Result

User is taken to the bitwarden homepage with a nonexistent html anchor

## Screenshots or Videos

![Screen Shot 2020-08-16 at 11 33 43 PM](https://user-images.githubusercontent.com/3028964/90360674-93ff2e80-e019-11ea-9b1b-ffaa96ca1a2d.jpg)

## Environment

- Operating system: MacOS Big Sur
- Browser: Microsoft Edge Version 84.0.522.59 (Official build) (64-bit)
- Build Version Version: 1.45.0

**Comment by Greenderella** [comment]
Hi, thank you for the report, it should be already fixed (https://github.com/bitwarden/web/commit/d3664321fde923494e96d4075f81d0e44f9ae3b7), maybe we just need to wait to the next deploy.

**Comment by cscharf** [comment]
Thanks for reporting this. Since this has been resolved and we're just waiting for the deployment of that fix, going to close this issue. We're hoping for the next release of the browser extension this month.
