### ISSUE TITLE
User has to enter correct login details twice when using U2F as second factor

### ISSUE THREAD

**Issue by belidzs** [bitwarden/browser#1363]
## Describe the Bug

I've set up the browser extension to log out after closing the browser so I have to login each time the browser is restarted. 

Currently when I use the drop-down menu to log in to the extension I get the following message:

![image](https://user-images.githubusercontent.com/7085801/90378334-82e60a00-e079-11ea-8d20-85317d23f5a1.png)

My problem is that I only get this message after I entered the correct username and password. When I choose `Yes` the window correctly pops out but now I have to log in again.

I'd really love to have an option from the login screen to pop out the extension before entering my credentials, so I don't have to enter it twice

## Steps To Reproduce

1. Start with logged out state
1. Access the extension from the top-right toolbar using its icon
1. Click Log in
1. Enter the correct credentials to a user which requires additional U2F factor verification
1. Click Yes on the message
1. Enter login details again
1. Touch the key to finalize login

## Expected Result

I'd like to be able to log in without the need to enter my credentials twice. 

For example, you could put this icon on the login screen as well:
![image](https://user-images.githubusercontent.com/7085801/90379066-8201a800-e07a-11ea-94fc-0586fd924396.png)

This way I could pop out the extension before logging in.

I'm aware that I could use the sidebar to log in as a workaround, but it was really difficult to figure out, how to even open it.

## Actual Result

Currently I have to provide valid credentials, click yes, then log in again.

## Environment

- Operating system: Windows 10
- Browser: Firefox 79.0
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
 
Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by belidzs** [comment]
I understand that feature requests are supposed to go to the forums but requiring the user to log in twice because of a missing button looks like a bug and definitely not a missing feature to me.

**Comment by cscharf** [comment]
Thanks @belidzs , we definitely appreciate the request, our community forum allows changes to behavior, additions, enhancements and new features alike to be discussed by our community members, voted on as well as give opportunities for those wishing to contribute to propose solutions before working on PRs for the same. It is that in which we are respectfully closing this GitHub issue in request that you open this up to our community on the forum linked above which is where we manage our backlog of enhancements.
