### ISSUE TITLE
Chrome Extension Failed to load

### ISSUE THREAD

**Issue by fhidal01** [bitwarden/browser#1364]
## Describe the Bug

The chrome extension does not load after installation. I don't see its icon next to other extensions that I have installed.

## Steps To Reproduce

1. Go to [extension page](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb)
2. Click on 'Add to chrome'
3. Then you get redirected to [browser-start page](https://bitwarden.com/browser-start/)
4. Extension icon is not found next to my profile icon                                                        

## Expected Result

1. I expect to see the extension icon be able to click on it and login and use it

## Actual Result

Seems like the extension code is throwing and error and failing to load.

`Uncaught (in promise) Error: Token not found.
    at token_service_TokenService.decodeToken (token.service.ts:119)
    at token_service_TokenService.getPremium (token.service.ts:199)
    at user_service_UserService.<anonymous> (user.service.ts:110)
    at Generator.next (<anonymous>)
    at organization.ts:68`

when I go to chrome://extensions/ and then click on Inspect views background.html
I see the error above in the console tab.

## Screenshots or Videos

![Screen Shot 2020-08-18 at 7 28 54 AM](https://user-images.githubusercontent.com/2779834/90508928-87b4c780-e126-11ea-8645-faba02b27b1c.png)

## Environment

- Operating system: Mac OS Catalina v10.15.6
- Browser: Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- Build Version: v 1.45.0

## Additional Context

For what its worth I also tried to clone he code ad load the extension that way following the readme file but the project failed to build. Master branch build failure:

`ERROR in /Users/felixhidalgo/projects/code/bitwarden/src/popup/accounts/login.component.ts
./src/popup/accounts/login.component.ts
[tsl] ERROR in /Users/felixhidalgo/projects/code/bitwarden/src/popup/accounts/login.component.ts(28,13)
      TS2554: Expected 6 arguments, but got 9.

ERROR in /Users/felixhidalgo/projects/code/bitwarden/src/services/autofill.service.ts
./src/services/autofill.service.ts
[tsl] ERROR in /Users/felixhidalgo/projects/code/bitwarden/src/services/autofill.service.ts(231,47)
      TS2339: Property 'getNextCipherForUrl' does not exist on type 'CipherService'.`

**Comment by maichler** [comment]
I have the same issue - with loading an unpacked version of the extension, though.

OS: Ubuntu 20.04
Google Chrome: Version 84.0.4147.125 (Official Build) (64-bit)
Version: v1.44.2 - v1.45.0

It seems like the regression was introduced in v1.44.2 since v1.44.1 loads just fine.

**Comment by secur3** [comment]
I also have the same issue, both for the extension downloaded from Chrome web store and the unpacked version obtained via git.

OS: Mac OS Catalina version 10.15.5 (19F101)
Google Chrome: version  85.0.4183.83 (Official Build) (64-bit)

**Comment by RayBB** [comment]
I would like to take a crack at #1392 but this issue is blocking me.

OS: Mac OS Catalina version 10.15.6 (19G2021)
Google Chrome: Version 85.0.4183.102 (Official Build) (64-bit)

Does anyone have a workaround or know what the cause is?

**Comment by fhidal01** [comment]
@Ryan

**Comment by fhidal01** [comment]
@Raybb what do yo mean by, work around is to use FF?

**Comment by RayBB** [comment]
@fhidal01 yes. It is chrome specific issue but thing work fine with firefox.

**Comment by fhidal01** [comment]
Chrome extension seems to be working now. I just downloaded again and it's working now.
