### ISSUE TITLE
"Safari detected an app or service that interfered with clicking" When Enabling Bitwarden Extension

### ISSUE THREAD

**Issue by danfuentes** [bitwarden/browser#1370]
**Describe the Bug:**
When trying to enable the Bitwarden Safari Extension, I receive a message indicating _"Safari detected an app or service that interfered with clicking."_
<img width="907" alt="Screen Shot 2020-08-27 at 11 57 18 AM" src="https://user-images.githubusercontent.com/42923035/91466249-d700a380-e85c-11ea-851c-ad1ab0b681f3.png">

**Environment:**
- **Operating system:** macOS Catalina 10.15.6 (19G2021)
- **Browser:** Safari Version 14.0 (15610.1.25, 15610)
- **Bitwarden Build Version:** Version 1.20.1 (1.20.1)

**Troubleshooting Attempts:**
- Restart Macbook
- Completely uninstall Bitwarden and install again.

**Comment by clayadams5226** [comment]
Looks like that's a new security precaution with Catalina. The apple article below talks about possible workarounds. 
[](https://support.apple.com/en-is/HT211233)

**Comment by tkreind** [comment]
For me uninstalling and reinstalling Bitwarden solved this.

**Comment by Krasser01** [comment]
Solved. Disabling firewall while turning on the extension solved it for me!

**Comment by moeabbass** [comment]
After searching high and low for a solution to this problem, I've found one that worked for me. On macOS Ventura 13.4
Go to System Settings > Network > Firewall.
Firewall was turned off for me.
Turn on Firewall and leave all default settings.
Immediately turn Firewall back off.
Go back to the Extension menu in Safari (Safari > Settings > Extensions) and try to enable the extension(s) again.
This time it worked.
There was no need to boot into Safe Mode or reinstall the extension.
The extensions in question for me were Adblock Engine and Adblock Icon.
I hope others can get this to work with this method.
