### ISSUE TITLE
Password autofill works even for non-password fields

### ISSUE THREAD

**Issue by MilovanovM** [bitwarden/browser#1372]
## Describe the Bug

It looks like the browser extension fills out non-password fields with password without masking symbols. 

## Steps To Reproduce

Open any page (Slack help center in my case) that contains a field with the word "password" in the placeholder.

## Expected Result

Do not fill non-password fields with password.

## Actual Result

Password is inserted into the field without masking symbols

## Screenshots or Videos

<img width="874" alt="search form" src="https://user-images.githubusercontent.com/1742065/91636490-b6298100-ea09-11ea-8de5-cb18032935cf.png">

## Environment

- Operating system: Mac OS Catalina
- Browser: Chrome 85.0.4183.83
- Build Version 1.45.0

**Comment by riaanduplessis** [comment]
The check on the field placeholder would have to be removed, which might make sense for situations that are similar to this issue.

https://github.com/bitwarden/browser/blob/a889aff39ac61a1fa4da230a9ba5c9466e3242da/src/services/autofill.service.ts#L914-L928

**Comment by MaxWipfli** [comment]
I found the same issue with a field for 2FA on mintos.com, where Bitwarden autofills the password.

The input element's id and name is "_one_time_password", the placeholder "6-digit code".

**Comment by addisonbeck** [comment]
Something like adding a setting to disable non-password fields specifically would need to be rerouted through a feature request on our [community forum](https://community.bitwarden.com/)  (@riaanduplessis), but I think even if that setting existed people that *did* want to autofill on non-password fields wouldn't want blatantly irrelevant data being autofilled like with these example fields. A setting would be a nice addition, and a better solution would be to do that in addition to tightening up what we consider "isLikePassword".

**Comment by addisonbeck** [comment]
Gonna close this one, as the use cases mentioned here should now be resolved.
