### ISSUE TITLE
Unable to auto-fill on every website - Chrome 85 / MacOS

### ISSUE THREAD

**Issue by jamescridland** [bitwarden/browser#1374]
On attempting to sign in to any website using the Chrome extension, I get a red error message inside the extension saying "Unable to auto-fill the selected item on this page."

I'm using v1.45.0 of the Bitwarden Chrome extension on Chrome 85.0.4183.83 on MacOS 10.15.6. A typical page that fails is https://github.com/login which is [quoted as the auto-fill example](https://bitwarden.com/help/article/auto-fill-browser/) in Bitwarden's documentation.

Auto-fill did work perfectly when I first installed the extension; but is now no longer working at all. It looks as though Chrome updated itself on September 2, which would be when I first noticed Bitwarden no longer auto-filling. That may be a coincidence.

Right-clicking the username/password and selecting 'autofill' also fails. "Enable auto-fill on page load" has no effect, and does not change the behaviour either.

I can't see any errors present in the Console, and Bitwarden otherwise works fine on this system.

**Comment by Greenderella** [comment]
Hi jamescridland,
Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/
Let us know how it goes.

**Comment by jamescridland** [comment]
Thanks. This worked, and Chrome is now auto-filling again. Yay!

As a side note - the leftover data was properly removed by Chrome after uninstalling the extension, which was nice to see.
