### ISSUE TITLE
Bitwarden gets confused over fields on AWS login

### ISSUE THREAD

**Issue by stevemarksd** [bitwarden/browser#1381]
From: https://github.com/bitwarden/browser/issues/70 which is closed. AWS login is still broken

![image](https://user-images.githubusercontent.com/58653359/92673527-e51aed80-f34d-11ea-98cf-084ba2f260fd.png)

https://signin.aws.amazon.com/
same here, for root options the password is entered on a separate form, it's not auto identified/filled

**Comment by cscharf** [comment]
Hi @stevemarksd, this currently works as intended. The autofill on page load does exactly that, auto-fills the form on **page** load. The second "form" which happens after you click "Next" or submit this form, which presents the password field, is done via XHR/Ajax and does not fire a page load event; with that our extension does not scan the DOM on DOM change, as the overhead would be pretty high. If you wish to propose some kind of XHR hooks/detection of form changes/form loads via AJAX within the extension (if that's possible, not sure) I would suggest posting in our [Bitwarden Community Forums](https://community.bitwarden.com) as a feature request.

![image](https://user-images.githubusercontent.com/3904944/103660012-193c9e80-4f3b-11eb-8aec-3c1a2a6da559.png)
