### ISSUE TITLE
Login fails when bitwarden.com is blocked by NoScript in Firefox

### ISSUE THREAD

**Issue by Aculeo** [bitwarden/browser#139]
I have scripts disabled by default in my browser, and the Firefox extension fails with this error unless I whitelist bitwarden.com:

![bitwarden-noscript](https://cloud.githubusercontent.com/assets/3977620/25247453/1ea8a66e-260b-11e7-8e45-f3f2470d91d5.png)

Which is basically an unexpected error.

**Comment by kspearrin** [comment]
The extension relies on javascript, so if you disable that it will likely fail in unexpected ways.

**Comment by SylwesterZarebski** [comment]
Should extension's javascript be running under local browser context (contained inside extension), and not bitwarden.com domain - not loaded from outside?

**Comment by kspearrin** [comment]
All javascript is running from the local browser context. There are no external scripts loaded.

**Comment by SylwesterZarebski** [comment]
Ok, but NoScript do not block scripts inside extensions (run in browser UI context), only page ones. I do not know how webextension works.
Besides, with uMatrix extension i do not see this problem.

**Comment by jonathonf** [comment]
There are xhr requests being made (logged via uMatrix logger):

```
21:57:04 |   |   | xhr | https://api.bitwarden.com/settings/domains?excluded=false&access_token3=***
21:57:00 |   |   | xhr | https://api.bitwarden.com/ciphers?includeFolders=false&includeShared=true&access_token3=***
21:57:00 |   |   | xhr | https://api.bitwarden.com/folders?access_token3=***
21:56:59 |   |   | xhr | https://api.bitwarden.com/accounts/profile?access_token3=***
21:56:57 |   |   | xhr | https://identity.bitwarden.com/connect/token
```

Could NoScript be blocking these?

**Comment by kspearrin** [comment]
We cannot control what other extensions are doing. This is more on a NoScript bug.

**Comment by SylwesterZarebski** [comment]
It should be documented somewhere here what connections/hosts are used to proper working with maybe some examples how to unblock.

**Comment by kspearrin** [comment]
@SylwesterZarebski  I don't use this addon so if someone has that information please post it and we can update the help section.

**Comment by SylwesterZarebski** [comment]
Ok, for me working configuration for uMatrix is altered one from #171:
```
* api.bitwarden.com xhr allow
* identity.bitwarden.com xhr allow
* maillink.bitwarden.com other allow
* vault.bitwarden.com other allow
```
or all communication for domain:
```
* bitwarden.com * allow
```

For NoScript, user should whitelist same addresses:
```
api.bitwarden.com
identity.bitwarden.com
maillink.bitwarden.com
vault.bitwarden.com
```
or full domain:
```
bitwarden.com
```

**Comment by kspearrin** [comment]
Updated docs: https://help.bitwarden.com/article/blocker-access-rule/

**Comment by SylwesterZarebski** [comment]
I have two UUIDs on debugging extensions page, which one should i use: extension UUID or internal UUID?
Also please note that first one changed for me after updating extension :-(.
