### ISSUE TITLE
Spinning Wheel in Safari with 1.46.1

### ISSUE THREAD

**Issue by kennymc-c** [bitwarden/browser#1394]
## Describe the Bug

Today I have updated the Desktop App to version 1.22 and with that the extension in Safari has been updated to version 1.46.1. Unfortunately since then I only get to see a spinning wheel when I open the extension. The vault was completely logged out before. In Chrome with the same version I didn't have this problem even after logging out and in several times.
I have already tried to uninstall and reinstall the desktop app and tried it with version 1.21. But every time I get the same error. It seems that even with the old desktop app the current extension is always installed.
Is there no way for a downgrade? What else could be the problem?

## Environment

- Operating system: macOS Catalina 10.15.6
- Browser: Safari 13.1.2
- Build Version 1.46.1
- Self hosted with BItwardenRS

**Comment by kspearrin** [comment]
@kennymc-c We're working on a hotifx. Stand by

**Comment by kspearrin** [comment]
Fixed with https://github.com/bitwarden/desktop/releases/tag/v1.22.1
