### ISSUE TITLE
Unable to log in via SSO - Enterprise Single Sign-On button greyed out and unclickable

### ISSUE THREAD

**Issue by rkujawa** [bitwarden/browser#1401]
(This is a problem I've originally reported via mail, but since I have never received a reply, I am reporting here)

## Describe the Bug

I'd like to log in to Bitwarden via SSO using browser extension.

## Steps To Reproduce

1. Install the browser extension.
2. Click on Bitwarden icon
3. Try clicking on "Enterprise Single Sign-On"
4. Notice that it is greyed out, unclickable and does nothing at all

## Expected Result

Being able to log in via SSO.

## Actual Result

Not able to log in via SSO.

## Screenshots or Videos

See the following screencast:

https://youtu.be/z7oUvWNkELQ

## Environment

- Operating system: Linux (Fedora 32)
- Browser: Firefox 80
- Build Version: 1.46.1

## Additional Context

None.

**Comment by cscharf** [comment]
This should be resolved/fixed by https://github.com/bitwarden/browser/pull/1395 which has been merged, we'll be planning a browser extension update soon.

**Comment by rkujawa** [comment]
Thanks!
