### ISSUE TITLE
Only a partial list of all your passwords are displayed under the My Vault > Login section

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/browser#1402]
## Describe the Bug

While going to My Vault > Login section in the browser extension, only a partial list of passwords it's displayed, this behaviour repeats itself across all Chromium browsers (Chrome, Vivaldi, Brave)

## Steps To Reproduce

1. Log in into your browser extension.
2. Go to My Vault > Login.
3. You will see only a fraction of your saved passwords.

## Expected Result

You should be able to see all your passwords.

## Actual Result

You can see only a fraction of your saved passwords.

## Screenshots or Videos

![vault](https://user-images.githubusercontent.com/5418577/93863157-76318300-fcc3-11ea-9e23-1ba1e82cf5b1.png)

## Environment

- Operating system: [Windows 10, Ubuntu 18]
- Browsers: 
[Chrome: Version 85.0.4183.102 (Official Build) (64-bit)]
[Brave: Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)]
[Firefox: Version 80.0.1 (Official Build) (64-bit)]
[Vivaldi: Version 3.3]
- Build Version: [1.46.1]

**Comment by kspearrin** [comment]
Looks like it might be an issue with the infinite scroll. @vincentsalucci could look.

**Comment by vincentsalucci** [comment]
Thanks for the report. We're currently looking into this!

**Comment by vincentsalucci** [comment]
Resolved via https://github.com/bitwarden/browser/commit/959c488f5a92b2dc024995e9d0f1b85d7cdaf087
