### ISSUE TITLE
HTTP Basic auth autofill isn't controlled by the autofill setting

### ISSUE THREAD

**Issue by LunNova** [bitwarden/browser#1408]
Continued from #1124, which was only partially resolved.

When autofill is disabled HTTP Basic Auth is still autofilled.

The correct behaviour is to do nothing and require the user to manually copy/paste the password, since there's no way to ask.

**Comment by kspearrin** [comment]
We probably need to control this with a separate setting, such as "Auto-fill based authentication prompts" since the only way to fill a basic auth prompt is without user iteraction.

**Comment by hablutzel1** [comment]
I currently have the "Enable Auto-fill On Page Load" option disabled but the Bitwarden Browser Extension (tested in Firefox) is still login me in automatically to a site that accepts HTTP Digest Access Authentication. **This is plainly contradictory and confusing**.

Now, in my opinion, the most coherent and safe behavior for now (until an option such as "Auto-fill basic authentication prompts" gets implemented) would be that if "Enable Auto-fill On Page Load" is disabled, credentials would never be automatically provided, not in html forms or with HTTP Basic and Digest Access Authentication or anywhere!.
