### ISSUE TITLE
[FR] Ability to apply login to multiple domains

### ISSUE THREAD

**Issue by rjcoupe** [bitwarden/browser#141]
For instance, my Office365 login applies to both *.office365.com _and_ *.microsoftonline.com. Currently, I have to either set up two entries in Bitwarden (AFAIK, at least) or do some manual copying of the password to paste it into the form.

**Comment by kspearrin** [comment]
Check out https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by kspearrin** [comment]
Additionally I have added office365 to the global Microsoft group for next release as well.

**Comment by rjcoupe** [comment]
Beautiful, thank you.
