### ISSUE TITLE
Auto-fill not working for Tangerine password

### ISSUE THREAD

**Issue by Merrit** [bitwarden/browser#1411]
## Describe the Bug

Auto-fill of password on the [Tangerine bank login page](https://www.tangerine.ca/app/#/) doesn't work.

> Unable to auto-fill the selected item on this page. Copy and paste the information instead.

## Steps To Reproduce

1. Go to https://www.tangerine.ca/app/#/
2. Input client number and click "Log Me In"
3. Next page has "Enter your PIN"

![image](https://user-images.githubusercontent.com/9575627/94369703-706be100-00b9-11eb-90ce-87f5727cc91c.png)

## Expected Result

The saved password (PIN) should be autofilled.

## Actual Result

Must copy the password and paste into the box.

## Environment

- Operating system: Manjaro KDE
- Browser: Chromium 85.0.4183.102 (tested & autofill appears to work on Firefox)
- Build Version (go to "Settings" → "About" in the app): Version: 1.46.1

## Additional Context

I inspected the element for the PIN in case it helps:

```html
<div class="field">
    <!-- ngIf: !$ctrl.isFirstTimeLogin --><input ng-if="!$ctrl.isFirstTimeLogin" type="tel" name="login_pin"
        id="login_pin"
        class="input CB_DataMask ng-pristine ng-scope ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength ng-touched"
        ng-class="{warning:
    $ctrl.pinSectionForm.login_pin.$invalid &amp;&amp;
    $ctrl.pinSectionForm.login_pin.$touched &amp;&amp;
    $ctrl.pinSectionForm.login_pin.$dirty &amp;&amp;
    $ctrl.showErrorOn,
    'c-login__grey':  $ctrl.isPinLockedInPinPage
  }" maxlength="6" minlength="4" numeric-input="" inputmode="numeric"
        in-view="$ctrl.pinInputInView($inview, $inviewInfo)" autofocus="" autofocus-device="ALL" autocomplete="off"
        ng-change="$ctrl.validateInput($ctrl.pinCredentials.PIN)" ng-focus="$ctrl.onFocus()" ng-required="true"
        ng-blur="$ctrl.onBlur()" ng-disabled="$ctrl.isPinLockedInPinPage" ng-model="$ctrl.pinCredentials.PIN"
        ng-trim="false" placeholder="4 or 6 digit Number" required="required" aria-invalid="true" style="">
    <!-- end ngIf: !$ctrl.isFirstTimeLogin -->
    <!-- ngIf: $ctrl.isFirstTimeLogin -->
    <div class="field__error_const_height">
        <div ng-messages="$ctrl.pinSectionForm.login_pin.$error"
            ng-show="$ctrl.pinSectionForm.login_pin.$touched &amp;&amp; $ctrl.pinSectionForm.login_pin.$dirty &amp;&amp; $ctrl.showErrorOn"
            class="field__error ng-hide ng-active" aria-live="assertive" aria-hidden="true">
            <!-- ngMessage: required -->
            <p ng-message="required" class="ng-binding ng-scope"> This information is required. </p>
            <!-- ngMessage: minlength -->
        </div>
    </div>
</div>
```

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by robbie2121** [comment]
Did you ever fix this? I have this issue too.

**Comment by djsmith85** [comment]
Hi @robbie2121,

I'm unable to test this as I do not have an account at this bank, but autofill might be possible using custom-fields: https://bitwarden.com/help/auto-fill-custom-fields/
