### ISSUE TITLE
Cant select language in bitwarden extension firefox?

### ISSUE THREAD

**Issue by GitJamz** [bitwarden/browser#1415]
Can not find where to change the language in the bitwarden firefox extension ? Works fine on webvault and the standalone application in linux but cant find the option anywhere to set language in the web extension..

**Comment by Greenderella** [comment]
Hi GitJamz,

The browser extension as well as the mobile app will adopt the language set for the browser/mobile device. If after setting those up the UI isn't changing, please log out from the app completely and log back in to ensure the changes kick in.

Regards

**Comment by cscharf** [comment]
Hi @GitJamz , I'm closing this issue, please feel free to re-open if you have or experience issues with language settings in Bitwarden's browser extension after changing your browser's/device's language.
