### ISSUE TITLE
Brave signs me out of all sites even after uninstalling Bitwarden browser extension

### ISSUE THREAD

**Issue by nshutijean** [bitwarden/browser#1416]
## Describe the Bug
Recently I lost all passwords from the browser, and decided to install Bitwarden browser extension for better security but Bitwarden came with its own issues and again decided to uninstall it. 

And that annoying issue was that the Bitwarden was signing me out of all the sites after it's closed or the system goes off, which i looked for a solution and could not find any. **Even after uninstalling the extension the effect is still there in the browser**

## Environment
- Operating system: Windows 10 OS Version 1809 (Build 17763.1217)
- Browser: Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
- Build Version (a three-weeks-from-now build version)

**Comment by kspearrin** [comment]
Bitwarden does not sign you out of websites. This sounds like a brave issue.

**Comment by nshutijean** [comment]
Thanks. Raised a similar issue on Brave, hope to find a solution.
