### ISSUE TITLE
Locked Extension does not accept masterpassword (need to logout and login)

### ISSUE THREAD

**Issue by jonathanmmm** [bitwarden/browser#1424]
## Describe the Bug

Browser Extension is set to lock at browser restart.
At Browser restart (or even on pressing the lock now button under settings) the masterpassword is not accepted.
It comes a red error warning saying "Wrong Masterpassword" (translated from german).
We then click on logout and type it in and can login in sucessfully.

Browser: Brave (latest version)
Extension from Chromestore (latest version)
OS: MacOS (latest version, is a new iMac 2020, not mine)
2FA enabled on account with TOTP/OTP (stay logged in is ticked in extension, to not put the 2FA key in everytime).

Same problem accured on Debian with Brave from official repositories, reinstalling the extension helped on Debian but not on MacOS.

I looked exactly in the moment that it was tried on the server. The client didn't even reach my nginx proxy in front of it, so also not the bitwarden server.

After logout and login I could see it in logs in bitwarden server and nginx.

If I can give any information about what kind of logs I can activate, please tell me :)

**Comment by jonathanmmm** [comment]
Probably reference to https://github.com/bitwarden/browser/issues/1404

**Comment by kspearrin** [comment]
Sounds like you need to update your server

**Comment by jonathanmmm** [comment]
As I sayed the client never reaches the server in this case, so it can't be a server error (nginx log not showing any activity for bitwarden in the minute we tried)

**Comment by lukasdietz** [comment]
Hi,
I am experiencing the same error. If the extension is locked and locked in as a user my masterpassword is not accepted. In this case I have to log out and log in again. Then it is working till the next lock of the extension. 
My Server is running version 2.11.0 and the extension is on the current version for Google Chrome

**Comment by stevesirois** [comment]
Same behaviour here. Firefox 81 on Ubuntu 20.04, Bitwarden extension 1.46.2, Bitwarden server 2.16.2 (self-hosting). Master password not after initial login and on unlock... need to logoff/login to get back to normal.

**Comment by jonathanmmm** [comment]
Ok, I don't know why exactly but it seemed to be an server issue, even if the nginx logs didn't show any connection.

I am using bitwardenrs and with version 1.17 docker it works again. Sorry for the confusion, I thought it had to be a client error as the client never reached the server.

https://github.com/dani-garcia/bitwarden_rs/issues/1179

So upgrading the server, if official or unofficial one could really help.

Thanks for your great work Bitwarden Team :)

**Comment by jonathanmmm** [comment]
> Hi,
> I am experiencing the same error. If the extension is locked and locked in as a user my masterpassword is not accepted. In this case I have to log out and log in again. Then it is working till the next lock of the extension. 
> My Server is running version 2.11.0 and the extension is on the current version for Google Chrome

If you updated the server and still experience these issue please tell or if it resolved, too.
If it is resolved I will close this issue :)

**Comment by X-Ryl669** [comment]
I can confirm that you need `bitwarden_rs 1.17.0`, but you also need to logout and login for this to take effect. It seems the previous version of **bitwarden_rs** stores something wrong in the new version's state of the extension and thus without logout, the extension does not even query the server upon unlocking.

**Comment by jonathanmmm** [comment]
I will close this issue then :)
