### ISSUE TITLE
Feature Request - Ability to select multiple entries in bitwarden

### ISSUE THREAD

**Issue by molly-holly** [bitwarden/browser#143]
Please add the feature to select multiple password and username entries in My Vault. When there are a lot of passwords and old information to delete, currently it has to be done one by one. This feature is available in other password managers and it would be great to see it in bitwarden too.

**Comment by kspearrin** [comment]
This is being tracked as a feature for the web vault here:

https://github.com/bitwarden/web/issues/39
https://github.com/bitwarden/web/issues/27

Closing as a duplicate for now, since we don't have any plans to being this to apps other than the web vault.
