### ISSUE TITLE
Microsoft Edge Chromium Autofill Shortcut

### ISSUE THREAD

**Issue by douglasparker** [bitwarden/browser#1430]
## Describe the Bug
Edge is missing the autofill shortcut. The new philosophy seems to be to sweep it under the rug and pretend it doesn't exist at the expense of your less technical userbase. Please address this issue. More information in issue #950 

## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by kspearrin** [comment]
The autofill shortcut exists for Edge, the defined default (`Ctrl + Shift + L`) is just overwritten by a shortcut that already exists in Edge that takes priority. You can change it to whatever you like, including re-establishing it as `Ctrl + Shift + L` under Settings > Extensions > Keyboard shortcuts (`edge://extensions/shortcuts`).

We could define a new default, specifically for Edge, if that makes sense. Please make a suggestion.

**Comment by douglasparker** [comment]
> The autofill shortcut exists for Edge. The defined default (`Ctrl + Shift + L`) is just overwritten by a shortcut that already exists in Edge that takes priority. You can change it to whatever you like, including re-establishing it as `Ctrl + Shift + L` under Settings > Extensions > Keyboard shortcuts (`edge://extensions/shortcuts`).
> 
> We could define a new default, specifically for Edge, if that makes sense. Please make a suggestion.

I'm not sure what a good alternative shortcut would be. In an ideal world, you'd want a consistent user experience across all browsers.

What does this shortcut do by default in edge? Is it a shortcut that the average user would use often enough that it would cause confusion if Bitwarden overwrites it?

Perhaps there could be a prompt upon extension installation that asks if the user wants to override the default for edge so that the shortcut stays the same? This in itself could be confusing for users as well.

Let's leave this issue open so that others can chime in on what makes the most sense.

**Comment by kspearrin** [comment]
See https://support.microsoft.com/en-us/help/4531783/microsoft-edge-keyboard-shortcuts

We cannot overwrite the Edge shortcut from the extension. The browser will not let us. This is why the autofill shortcut gets blanked out upon install and requires user intervention to override from the setting page.

**Comment by douglasparker** [comment]
> See https://support.microsoft.com/en-us/help/4531783/microsoft-edge-keyboard-shortcuts
> 
> We cannot overwrite the Edge shortcut from the extension. The browser will not let us. This is why the autofill shortcut gets blanked out upon install and requires user intervention to override from the setting page.

Okay, that is good to know.

So I think the simplest solution is to make the hotkey `Ctrl + Win + L` for Edge on Windows; and then just update the [documentation](https://bitwarden.com/help/article/auto-fill-browser/#keyboard-shortcuts-hot-keys) to reflect this.

It might be worth explaining why this is the default for Edge on Windows along with instructions on how to manually change it if the user prefers using `Ctrl + Shift + L`. That way if it ever comes up again, we can just redirect the user to that page and all of the information they need is right there in front of them.

Thank you for taking the time to communicate on this topic.
