### ISSUE TITLE
Google Chrome Bitwarden Extension erratic behavior filling credit cards on State Farm

### ISSUE THREAD

**Issue by thegoogleguy** [bitwarden/browser#1431]
## Describe the Bug

When filling in Credit Card information from the Bitwarden Extension in Google Chrome on the State Farm website, the extension freaks out and auto-fills the boxes with my credit card number, CVV, and expiration date over and over again, probably several hundred times until it finally stops. I'm unable to do any interaction on the page while this is happening because the extension keeps on refilling the credit card information fields over and over again, several times per second.

## Steps To Reproduce

These are the exact steps that I did which led me to this issue, but it may occur when attempting to process a credit card anywhere on the State Farm website.

1. Go to https://www.statefarm.com/pay
2. Scroll down to the section where you have two options, "Access your account" or "No login required"
3. Under no login required, click on the drop-down that has a default value of Phone Number, and change it to Key Code.
4. Type in the Key Code, and then click on Pay Bill.
5. Verify the correct policy is displayed and choose whether to split the payment over time or pay in full.
6. Go to the next page, and choose Credit Card as the payment method.
7. On this screen, open the Bitwarden Extension and click on a Saved Credit Card to fill the fields on the page.

## Expected Result

The credit card information is filled once.

## Actual Result

The credit card information is continuously filled over and over again, preventing any interaction with the page because the extension is constantly setting the focus to the credit card info input boxes and filling the information. This goes on for at least 2 minutes, and the extension is probably filling the information hundreds of times.

## Environment

- Operating system: Windows 10 Build 1909
- Browser: Google Chrome 86.0.4240.75
- Build Version: 1.46.2

## Additional Context

I remember encountering this issue about a month ago as well when I had another State Farm bill to pay, so I don't think it's necessarily specific to this current Chrome/Bitwarden version.

**Comment by kspearrin** [comment]
Unfortunately, I do not have an account with State Farm to access that page. Maybe you could try saving the page as HTML and zip it up and attach it here? Be sure it does not have any sensitive info in it.

**Comment by thegoogleguy** [comment]
I can definitely do that the next time I have to pay a bill - unfortunately I can't do that until April of next year, it won't even let you get to the credit card payment page unless you have some kind of balance due. Not sure if anyone else on your team has an account to test this with.

**Comment by clayadams5226** [comment]
Hi @thegoogleguy , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
