### ISSUE TITLE
Why cannot show TOTP code?

### ISSUE THREAD

**Issue by dong2590** [bitwarden/browser#1433]
## Why cannot show TOTP code

Here config,It's works in web site and desktop version
![image](https://user-images.githubusercontent.com/1455816/96739649-99e70680-13f2-11eb-98f1-10f2399eb485.png)

## Steps To Reproduce

Go to 'View Item'

## Expected Result
![image](https://user-images.githubusercontent.com/1455816/96739562-7fad2880-13f2-11eb-8941-14e55e857e1e.png)

## Environment

- Operating system: Mac OS Catalina
- Browser: Google Chrome 86.0.4240.80
- Build Version : 1.46.2

PS: Same problem in Android App

**Comment by kspearrin** [comment]
This feature requires a premium membership.

**Comment by dong2590** [comment]
> This feature requires a premium membership.

YES, I was

**Comment by kspearrin** [comment]
Try logging out and back in to make sure your premium membership is applied

**Comment by dong2590** [comment]
> Try logging out and back in to make sure your premium membership is applied

Thanks~It's works

**Comment by Neurotoxin001** [comment]
What will happen with already added totp when I lose premium? Codes will stop generating and showing and I will not be able to login until I pay premium again?

**Comment by tgreer-bw** [comment]
@Neurotoxin001 The codes will stop generating within Bitwarden, but you can access the key that is saved, and use it in another authenticator app if you'd like.
