### ISSUE TITLE
"Invalid Master Password" when re-entering password when using a custom environment URL.

### ISSUE THREAD

**Issue by dr-bonez** [bitwarden/browser#1434]
After being promoted to re-enter password, will present "Invalid Master Password" with correct password. Log in still works if I log out, resave the environment URL, and try with the same password again. 

Tested on Firefox for OSX and Android.

**Comment by kspearrin** [comment]
Is your sever up to date?

**Comment by DarkMio** [comment]
I have this problem as well, I'm currently in the process of looking up full environment infos.

**Comment by a1pilot** [comment]
Same problem here. Everything is up-to-date as far as I can tell.

**Comment by poldim** [comment]
Same as well.  I have it configured to prompt for password upon restart.  Right now if I restart and it prompts for password, it will not accept password.  Clicking *logout* returns me to the regular extension login screen (with custom environment URL still in place).  Then I just type in the same password that didn't work before and it log right in...

Running `image: bitwardenrs/server:latest` and Chrome Version 86.0.4240.111 (Official Build) (x86_64) with Extension Version: 1.46.2
```
docker-compose up -d bitwarden
srv_bitwarden is up-to-date
```

@dr-bonez does it work for your without adjusting the environmental URL?

**Comment by dr-bonez** [comment]
Looks like I was rain dancing a bit. Yeah no need to resave the environment url, logout-login works fine.

**Comment by cscharf** [comment]
Thanks Aiden, if this continue to be an issue please let us know and feel free to re-open this issue.
