### ISSUE TITLE
Inserting password adds space to class of password input field

### ISSUE THREAD

**Issue by pbruins84** [bitwarden/browser#1435]
## Describe the Bug

Auto-filling a password adds a space to the value of class attribute of the input field. The value of 'class' is apparently changed for the animation, but after the animation, the value of the class attribute has an additional space. This breaks some websites.

## Steps To Reproduce

- Go to a webpage where you have to login in Chrome.
- Right-click on the password field, an choose 'Inspect'
- Let bitwarden auto-fill the password.
- Observe the value of the class attribute

## Expected Result

The value of class should be the same after the animation.

## Actual Result

The value of the class attribute has an additional space.

## Screenshots or Videos

Before:
![bitwarden1](https://user-images.githubusercontent.com/5555752/96898550-23004b00-1490-11eb-8648-a03cf8cdd9f7.PNG)

After: (`form-control` now has an additional space)
![bitwarden2](https://user-images.githubusercontent.com/5555752/96898589-2d224980-1490-11eb-915b-b11b959171f4.PNG)

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by kspearrin** [comment]
This probably has something to do with the animation style since it appears to be happening to the username field as well.
