### ISSUE TITLE
Get bitwarden to autofill password form

### ISSUE THREAD

**Issue by piejanssens** [bitwarden/browser#144]
1. I'd like bitwarden to autofill the password form so that I don't have to manually select the login from the addon popup (this seems like a nobrainer, but I was quite surprised that Bitwarden doesn't do this - or it's just me and I'm overlooking something).
2. It would be nice to be able to indicate priories or another way to select the default login which is prefilled in case you have multiple logins for the same domain

**Comment by kspearrin** [comment]
This has been brought up before many times. See https://github.com/bitwarden/browser/issues/75

We may add it as an opt-in experimental feature in the future.
