### ISSUE TITLE
TOTP copying to clipboard doesn't work Chrome  86.0.4240.75  

### ISSUE THREAD

**Issue by korjavin** [bitwarden/browser#1442]
After filling TOTP code is not is clipboard when it should be.

- Operating system: Debian Linux
- Browser: Chrome  86.0.4240.75  
- Build Version (go to "Settings" → "About" in the app): 1.46.2

**Comment by Greenderella** [comment]
Hi @korjavin,

Take into account that TOTP codes will not automatically be copy to the system clipboard when “Enable Auto-fill On Page Load” is enabled in the browser extension (https://bitwarden.com/help/article/authenticator-keys/#using-generated-codes).

**Comment by korjavin** [comment]
Looks like it was a temporary glitch (or may be slow sync process)

Can't reproduce it now.
