### ISSUE TITLE
Digitalocean 2FA auto-fill not working

### ISSUE THREAD

**Issue by jonahgeorge** [bitwarden/browser#1446]
## Describe the Bug

Bitwarden does not populate Digitalocean's two factor authentication field on login.

## Steps To Reproduce

1. Go to https://cloud.digitalocean.com/login
2. Cmd-Shift-L
3. Enter
4. Cmd-Shift-L

## Expected Result

The 6-digit code field should be populated

## Actual Result

No change

## Screenshots or Videos

![Screen Shot 2020-11-03 at 12 33 13 PM](https://user-images.githubusercontent.com/2058205/98037642-bf9be480-1dd0-11eb-970b-cb433f9cad18.png)

## Environment

- Operating system: Mac OS Catalina 10.15.4
- Browser: Firefox Developer Edition 83.0b7
- Build Version (go to "Settings" → "About" in the app): 1.46.2

## Additional Context

```html
<form action="#" class="do-u-pb--small">
   <div class="sc-fzpmMD enYpte is-invalid">
      <label for="code" class="sc-fznxKY cpjajG">6-digit code</label>
      <div></div>
      <div class="sc-fznMAR gSVBBi">
         <input id="code" type="text" placeholder="Enter 6-digit code" autocomplete="off" class="sc-fznWOq sc-fzoKki jIqSjN" value="" data-com.bitwarden.browser.user-edited="yes">
         <div class="sc-fzoxKX craeZe"></div>
         <div class="sc-fzpkJw dCChlU"></div>
      </div>
      <div class="sc-fzolEj jJAzoG">
         <svg class="sc-AxiKw eSbheu do-Icon sc-fznzOf jxQFAb do-Icon--large">
            <use xlink:href="#_sprite-error"></use>
         </svg>
         <div class="sc-fzqBkg fCkJVF required-err">Verification code required</div>
      </div>
   </div>
   <button type="submit" class="sc-AxhUy dWKobR sc-fzoyTs jZUSDr do-u-mt--large">Verify Code </button>
   <p class="do-u-mb--remove">Can't access your authentication app?</p>
   <a type="default" role="button" tabindex="0" class="sc-Axmtr eXTzQs sc-fzqARJ eLpUJW" href="/login">
      <span class="sc-fzpans cKJzHK"></span>
      Send an sms instead</a> or <a type="default" class="sc-AxheI fniENO sc-Axmtr eXTzQs sc-fzqNJr hXQgjp" href="https://www.digitalocean.com/support" target="_blank" rel="noopener noreferrer">
      <span class="sc-fzpans cKJzHK"></span>contact support
   </a>
</form>
```

**Comment by lschober-bw** [comment]
Hi @jonahgeorge 

Thanks for getting in touch! This is the expected behavior. Bitwarden's autofill won't include any TOTP codes upon autofill. If you autofill any item that has TOTP attached, the code is copied to your system clipboard. From the page you are sharing in your screenshot, you should now use the paste function of your device. The 6 digit code will be input.

[See this article for more info.](https://bitwarden.com/help/article/authenticator-keys/#using-generated-codes)

**Comment by jonahgeorge** [comment]
Understood. Thank you!
