### ISSUE TITLE
Edge extension is not rendering correctly

### ISSUE THREAD

**Issue by cghughes** [bitwarden/browser#1454]
## Describe the Bug
The Edge extension is not rendering correctly; it occurs on all aspects of the extension and impacts login, capturing new logins, generating a new password 

## Steps To Reproduce
1. Click on the extension icon
2. Logins available for the site are not displayed correctly (see screenshot)

## Expected Result
Extension to display correctly

## Actual Result
Extension appears to have a grey block render over the extension

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/35765912/98531038-6cbaa500-2288-11eb-995b-64e29d5bebaa.png)

## Environment
- Operating system: Mac OS Catalina 10.15.7
- Browser: Edge 86.0.622.63 (Official build) (64-bit)
- Build Version 1.46.2

**Comment by Greenderella** [comment]
As per my current testing the extension is rendering correctly on Edge 86.0.622.63 (Official build) (64-bit) for Mac OS. 

Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?

Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

![photo4999167561622988937](https://user-images.githubusercontent.com/5418577/98797309-af0cef00-240c-11eb-88fe-41be32729361.jpg)

**Comment by cghughes** [comment]
You need to manually delete the extension in `/Users/<username>/Library/Application Support/Microsoft Edge/Default/Extensions` and then reinstall in order to resolve the issue
