### ISSUE TITLE
Login screen not correctly rendered in Italian language

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/browser#1459]
## Describe the Bug

The login screen in the extension window is not rendered correctly in the Italian language.

## Steps To Reproduce

1. Install the extension from the Microsoft Add-ons page.
2. Click on the extension icon in the toolbar.

## Expected Result

The text and buttons are perfectly visible within the window area.

## Actual Result

The text and buttons come out of the window area.

## Screenshots or Videos

![login](https://user-images.githubusercontent.com/62190484/98906834-18006f80-24be-11eb-9ead-0518e00cbf82.png)

## Environment

- Operating system: Mac OS Catalina 10.15.7
- Browser: Microsoft Edge 86.0.622.68 (Official build) (64 bit)
- Build Version: 1.47.0

**Comment by wusatosi** [comment]
This can be fixed by switching the _(Single Sign-On)_ to a new line.

**Comment by fabriziobagala** [comment]
@wusatosi This is not a good idea because you would have to resize all 3 buttons. Maybe it would be better to leave only the text "Single Sign-On"?

**Comment by wusatosi** [comment]
You're prob right, though I think its the (Single Sign-On) that needs to be removed.
I will check how hard it will take to re-style this first.
