### ISSUE TITLE
Clicking out of the popup causes it to switch back to the 'Tab' tab

### ISSUE THREAD

**Issue by ollieh** [bitwarden/browser#146]
In the case where you need to copy and paste both a username and a password:
1. press the bitwarden button
2. press 'My Vault' tab, and navigate to the relevant account
3. click the clipboard button to copy the username
4. click out of bitwarden onto the webpage (or application) to paste the username
5. click bitwarden again, the popup is now back on the 'Tab' tab, instead of the account details you were using

Now you have to navigate back to 'My Vault' and search for your account again to get the password.

**Comment by kspearrin** [comment]
Unfortunately we can't stop the browser from closing the popup since we don't have control over that, however, we may be able to preserve your existing state between open/closes.

**Comment by begincalendar** [comment]
@kspearrin How about the ability to open a new browser tab and thus achieve persistence that way?
E.g. Similar to how LastPass does it.

Yes we could just open a browser tab and visit the web vault, but the advantage of staying within the confines of the browser extension realm, is that our login credentials can be encrypted client-side (during the authentication process), right?

**Comment by kspearrin** [comment]
@begincalendar 

The web vault offers the same client side encryption as the browser extension. There is no difference.

Launching/using the web vault could be a simple workaround for this.

**Comment by begincalendar** [comment]
OK cool.

> There is no difference.

Technically client-side code that is "shipped" via a signed browser extension is more trustworthy than similar code that is just delivered via an HTTPS request, right? [[0]](https://tonyarcieri.com/whats-wrong-with-webcrypto)

**Comment by kspearrin** [comment]
@begincalendar Sure, that definitely does offer some additional security, however, the same can be done on the web as well. We can sign all of our code with [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). Probably not a bad idea to start doing this anyways, though now we're getting a bit off topic for this issue.

**Comment by kspearrin** [comment]
This is resolved in the next version of the browser extension. You can now open the popup into a full-page "website" in the browser window. See: 

![image](https://user-images.githubusercontent.com/1190944/26991617-1cea27c2-4d29-11e7-840a-be273158b1b1.png)


![image](https://user-images.githubusercontent.com/1190944/26991643-3752821c-4d29-11e7-813a-c7d3f99c506b.png)
