### ISSUE TITLE
Lock stay on icon after unlock

### ISSUE THREAD

**Issue by Wadera** [bitwarden/browser#1460]
## Describe the Bug

Broken icon after unlock on last Chrome. 

## Steps To Reproduce

1. Unlock Bitwarden ;)

## Expected Result

Red lock should disappear after unlock. 

## Actual Result

Red lock remain in background.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/407236/98932971-f9a76d80-24d7-11eb-8df2-259275861a04.png)

![image](https://user-images.githubusercontent.com/407236/98934257-b51cd180-24d9-11eb-9201-0945ef26eeab.png)

![bit-bug](https://user-images.githubusercontent.com/407236/98934208-a3d3c500-24d9-11eb-89bb-e6f38a191c66.gif)

## Environment

- Operating system: Windows 10
- Browser: Version 86.0.4240.198 (Official Build) (64-bit)
- Build Version: Version: 1.46.2

**Comment by clayadams5226** [comment]
@Wadera if you uninstall the extension and install it again does the problem persist?

**Comment by Wadera** [comment]
I've noticed that it was resolved a while ago. Not sure if extension updated or Chrome, but it's working fine now.

**Comment by Wadera** [comment]
Fixed
