### ISSUE TITLE
Virtualizor Panel - Autofill not working

### ISSUE THREAD

**Issue by camjac251** [bitwarden/browser#1462]
I don't think autofilling with Virtualizor Panels is working. I've always had to manually fill in my username and password. Virtualizor is a Control Panel (like cPanel but for VPS hosting). Their official demo doesn't have authentication so I wasn't able to link that but the below is an instance setup by a hosting provider, best I could find in terms of a demo.
https://master.drserver.net:4083

When you try to autofill through the 3 methods, extension at top, clicking the item, keyboard shortcut, right click context menu, they all fail. Both the email and password are left empty.

## Environment

- Windows 10
- Firefox 82.0.3
- Build Version : 1.46.2

**Comment by TheLinuxGuy** [comment]
+1 I am seeing this too.

**Comment by cscharf** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
