### ISSUE TITLE
Organization aren't being displayed after joining organization

### ISSUE THREAD

**Issue by baens** [bitwarden/browser#1464]
## Describe the Bug

From the chrome web extension, I would expect to see my organization's folders. My co worker can see the folders, but I have to use the web vault to see the organization's items.

No amount of uninstalling/reinstalling, logout/login seems to fix the issue.

## Environment

- Operating system: Linux & Mac
- Browser: Chrome 87.0.4280.60
- Build Version: 1.47.0

**Comment by tgreer-bw** [comment]
Make sure that you're assigned either directly to the collections, or your user is in a group that is assigned to the collections.

**Comment by baens** [comment]
I'm so sorry, I looked and looked for something and I didn't find that one. Thank you! That worked!
