### ISSUE TITLE
Blank Add-On Pop-Up in Firefox

### ISSUE THREAD

**Issue by igray** [bitwarden/browser#1465]
## Describe the Bug

I don't think this is the same bug as #882 but it is the exact same symptom. This started happening when I upgraded to Firefox 83. I can open the add-on pop-up once and it works fine. The second time I open it, and thereafter until I restart Firefox, the pop-up is completely blank. It is the correct size, and at appears to have content because as I move the mouse the cursor changes from default to pointer as I move it around the pop-up. When I hover near the upper-left corner and click, it does open a separate window and I see the Bitwarden interface there.

## Steps To Reproduce

1. From any tab
2. Click the Bitwarden activation button
3. See Bitwarden
4. Dismiss Bitwarden by either clicking the activation button again or by clicking anywhere on the web page
5. Click the Bitwarden activation button once again
6. See that the pop-up is blank

## Expected Result

For item 6 above, the pop-up should not be blank.

## Actual Result

For item 6 above, the pop-up is blank.

## Screenshots or Videos

![blank](https://user-images.githubusercontent.com/346073/99578866-0b3eb880-29a3-11eb-866d-8d812c2b7b31.png)

## Environment

- Operating system: ArchLinux
- Browser: Firefox 83.0 (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.47.0

## Additional Context

If I "inspect the add-on", I can get it to re-display again if I clear the web-console output of the inspector tab. Here is the web-console output from a single successful pop-up and the a blank pop-up:
```
13:39:46.120 unreachable code after return statement
analytics.ts:58:8
13:39:46.205 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). 10 vendor-angular.js:5707:20
13:39:46.397 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://1b763ac1-f9a1-44a5-a008-8c80c43d2a20/popup/vendor-angular.js
Source Map URL: scrolling.js.map

13:39:49.621 unreachable code after return statement
analytics.ts:58:8
13:39:49.702 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). 10 vendor-angular.js:5707:20
13:39:49.877 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://1b763ac1-f9a1-44a5-a008-8c80c43d2a20/popup/vendor-angular.js
Source Map URL: scrolling.js.map
```

**Comment by igray** [comment]
Sorry-- this seems to have nothing to do with BitWarden. It affected other add-ons as well.

**Comment by 314eter** [comment]
I have the same problem, on Archlinux with Firefox 83.0.

**Comment by mike2307** [comment]
I'm facing the same issue with firefox 83 under fedora 33. I have to click many times on the icon to make the menu appear.
Does anyone have a link to an upstream ticket?

**Comment by igray** [comment]
@mike2307 I believe it is related to [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1672139) which should be fixed in 84.
