### ISSUE TITLE
Issue Resolved for vault locked/ vault logged out in the Chrome Extension (MacOS)

### ISSUE THREAD

**Issue by smellysfunky** [bitwarden/browser#1468]
Version 86.0.4240.198 (Official Build) (x86_64)
MACOS 10.15.6

If you cannot log into Bitwarden Chrome Extension, or it keeps logging out, then you can try this solution. Make sure the Extensions Jigsaw icon is visible on your URL. Click the jigsaw, select Bitwarden Extension, then select PIN to toolbar. For some reason, you can't access this PIN function in the Windows/Extension area. Seems like a pain in the behind. Select the new Bitwarden pinned icon, then you can log in .

I set mine to never log out, and selected PIN to login, and used my screen saver as the lock out for security (set for 3 minutes) . if someone steals my computer, they can't copy and decrypt the bitwarden file as its encrypted.

Issue Resolved for vault locked/ vault logged out in the Chrome Extension (MacOS)

## Steps To Reproduce

4. Click on '...'

## Environment

Version 86.0.4240.198 (Official Build) (x86_64)
MACOS 10.15.6

**Comment by djsmith85** [comment]
@smellysfunky Thank you for the information.

As we use GitHub issues as a place to track bugs and other development related issues, and there is no action for the developers, I'm closing this now.

The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for [User-to-User Support](https://community.bitwarden.com/c/support) which is probably a better place to document this.
