### ISSUE TITLE
SSO from Browser Extension Does not Login Browser Extension

### ISSUE THREAD

**Issue by cscharf** [bitwarden/browser#1473]
## Describe the Bug

When initiating Enterprise SSO from the browser extension, the user is taken through the web vault's SSO flow (expected), after IdP authentication, the user is redirected back through another round-trip and then logged into the web vault (unexpected); the browser extension remains logged out/unauthenticated (unexpected).

## Steps To Reproduce

1. Open the browser extension, click `Enterprise Single Sign-On` button
2. In the new tab, enter in your organization's identifier and click `Log In`
3. Authenticate with your IdP
4. Note you are back at the prompt for your organization's identifier, should be pre-filled
5. Click `Log In` again
6. Note you are at the web vault's Unlock screen, prompted to enter your master password
7. Enter your master password and click "Unlock"
8. Note you are logged into the web vault only, the browser extension remains logged out

## Expected Result

After successfully authenticating with your IdP, the user should be shown a message to close their browser tab and the browser extension should be logged in, however the user would still have to enter their master password into the browser extension to gain access and enable decryption of their vault data.

## Actual Result

User is only logged into the web vault (after several round trips) and the browser extension remains in a logged out state.

## Screenshots or Videos

![Screen Recording - SSO Browser Extension Login](https://user-images.githubusercontent.com/3904944/100272381-0476ef00-2f29-11eb-873a-674f23cb1659.gif)

## Environment

- Operating system: All
- Browser: All; testing in Firefox, Chrome, Brave, Safari, and Edge
- Build Version (go to "Settings" → "About" in the app): Browser Ext: 1.47.0, Web: 2.17.0

## Additional Context

This has been reported by several folks over the last week.

see related PRs:
 * https://github.com/bitwarden/browser/pull/1472
 * https://github.com/bitwarden/jslib/pull/210
 * https://github.com/bitwarden/jslib/pull/211
 * https://github.com/bitwarden/web/pull/720

**Comment by MGibson1** [comment]
fixed by bitwarden/web#719

**Comment by MGibson1** [comment]
Browser sso experience is further improved by bitwarden/web#720

**Comment by cscharf** [comment]
Re-opened by internal testing team.

**Comment by MGibson1** [comment]
Configuration handling improved by #1476

**Comment by cscharf** [comment]
This works, for the most part.... the extension is now logged in but the experience is wonky... In Chrome, I get a full Chrome tab open after SSO is successful, but the address of the 2nd tab is that of the chrome extension (oddity # 1), then when I complete 2FA, and unlock, I'm presented the extension vault (and UI) in the chrome tab... which I can close, and then close the other tab that says I can close it, and at least my extension is open, but this is not ideal.... will open a new issue for that behavior.

**Comment by MGibson1** [comment]
@cscharf some questions about your experience.

In the 2nd tab, were you asked to do anything to log in, 2fa, for example? or were you just asked to unlock your vault? If so, this blocks the auto-close of the second window to give you a chance to complete login.

I think the ideal behavior is to open the popup window rather than a new tab, but in all cases we're requesting a tab. If we could open reliably open the popup instead, we could do away with autoclose entirely and clean the experience up substantially. You're still left with a hanging, useless tab, but at least everything else is clearly handled inside the extension.

**Comment by danpoltawski** [comment]
I have found that this is **not** working for the Safari extension connecting to a self-hosted installation. (All other browsers seem to work)

**Comment by cscharf** [comment]
Hi @danpoltawski , can you please provide some information on the issue you're seeing in Safari. We have some known issues currently with header/cookie sizes reaching Safari's limit when using OIDC for SSO which are not occurring in any other browser and generally seem to impact self-hosted folks depending on their domain configuration (which cookies get served where in what requests).

If you're seeing an issue still on how the extension itself behaves, whether it's unlocked after successful SSO, etc. per the original issue above, please also let us know so our team can attempt to reproduce this issue (with some redacted screen shots or steps to reproduce and a little info about your environment).

**Comment by danpoltawski** [comment]
> If you're seeing an issue still on how the extension itself behaves, whether it's unlocked after successful SSO

Yes, following the SSO flow - the extensions doesn't get logged in:
https://user-images.githubusercontent.com/533249/102794541-6fd6a400-43a3-11eb-8da0-63152a56185c.mov

**Comment by cscharf** [comment]
Thanks @danpoltawski , can you please provide the version of your browser extension in Safari?

**Comment by danpoltawski** [comment]
1.47.1

**Comment by cscharf** [comment]
re-opening this based on the above, the team will take a look shortly, thank you Dan!
