### ISSUE TITLE
Autofill/autosave not working for this site

### ISSUE THREAD

**Issue by daviddem1971** [bitwarden/browser#1478]
## Describe the Bug

On https://online.bdo.com.ph/sso/login BW does not correctly fill the password field (unlike several other password managers). Something gets filled, but this always results in a login error from the website.

Also when trying to type the login/password manually, BW prompts to save, but the password is saved as ********** instead of the actual password.

## Steps To Reproduce

1. Go to https://online.bdo.com.ph/sso/login
2. Fill in valid credentials
3. Accept autosave prompt from BW
4. Check the vault and reveal the password, which is saved as *********** instead of what you typed in
5. Correct the vault entry to the correct password
6. Refresh https://online.bdo.com.ph/sso/login
7. ctrl+shift+L to autofill
8. Click login
9. Get login error from the website

## Expected Result

1. Expected the password to be saved correctly by BW
2. Expected BW to correctly autofill after correcting the password in the vault
## Actual Result

1. Password is saved as ********** instead of the actual password
2. After correcting the password in the vault, autofill results in a login error
## Environment

- Operating system: Windows 10 20H2 64-bit
- Browser: Firefox, Chrome
- Build Version: Firefox 83.0 64-bit, Chrome 87.0.4280.88 64-bit

## Additional Context

All other password managers were disabled for this test.

Also tested this site with other password managers:
1. built-in Firefox PW manager: OK
2. built-in Chrome PW manager: OK
3. LastPass: OK
4. 1password: fails (same way as BW fails)

Note: manually pasting in the password field is disabled by the website. Not sure if this may have something to do with it.

**Comment by daviddem1971** [comment]
No definitely the built-in password manager is disabled, and I also made sure the LastPass extension was disabled when I did the test. Also the behavior is the same both in Chrome and Firefox (Windows 10).

**Comment by daviddem1971** [comment]
Tested this site (and there are surely others like it) with:

LastPass: OK
Chrome built-in PW manager: OK
Firefox built-in PW manager: OK
BitWarden: Fail
1password: Fail (the same way as BitWarden)

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
