### ISSUE TITLE
SSO in Browser Extension Leaves multiple tabs open

### ISSUE THREAD

**Issue by cscharf** [bitwarden/browser#1479]
## Describe the Bug

This is a follow-up issue discovered after resolution of https://github.com/bitwarden/browser/issues/1473.

## Steps To Reproduce

1. Install the latest browser extension on Chrome, v1.47.1
2. Click on Enterprise Sing Sign-On
3. Authenticate in the new tab
4. Finish any 2FA + master password unlock in new tab

## Expected Result

The browser extension itself is navigated to the appropriate screen and the user is prompted to close the 1 tab and open the extension to complete the log in process.

## Actual Result

A 2nd tab is opened which completed the log in process and stays open; but has the same address as the chrome extension itself.

## Screenshots or Videos

This tab is expected to be left open (and is 👍🏻 )
![image](https://user-images.githubusercontent.com/3904944/101180933-3f101400-361a-11eb-84b3-7403bb8a9f25.png)

This tab is **not** expected to be left open, or to be opened at all (but is 👎🏻 )
![image](https://user-images.githubusercontent.com/3904944/101180802-0a03c180-361a-11eb-968c-6b5204f3c66c.png)

Here's a video of the behavior:
![browser-extension-behavior](https://user-images.githubusercontent.com/3904944/101192108-91583180-3628-11eb-802d-f58bc5a1e3a7.gif)

## Environment

- Operating system: macOS Catalina
- Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Build Version 1.47.1

cc: @clayadams5226 , @MGibson1

**Comment by MGibson1** [comment]
This is not specific to chrome. I think it's because you had to enter 2fa, which seems to side-step the onSuccessfulLogin event set in the sso connector
