### ISSUE TITLE
The keyboard cannot navigate to login items in the Firefox extension popup window

### ISSUE THREAD

**Issue by PSalant726** [bitwarden/browser#1482]
## Describe the Bug

When using Bitwarden via the Firefox extension's toolbar popup window, it is not possible to use the keyboard to navigate to specific login items, in order to (I assume) press ↵ to autofill them on the current page. The user is forced to use the mouse to click on the login item.

The ⌘+⇧+Y shortcut correctly opens the popup window, but using ↹ only navigates between the items in the top toolbar (pop-out, search, add item), and using ↑/↓ only scrolls within the window.

## Steps To Reproduce

1. Visit a URL for which a login item match exists
1. Use ⌘+⇧+Y to open the toolbar popup window
1. Use ↹ to attempt to navigate to a login item
    - Observe that continuously pressing ↹ cycles only through the items in the toolbar at the top of the window
1. Use ↑/↓ arrow keys to attempt to navigate to a login item
    - Observe that the ↑/↓ arrow keys only scroll the window (if enough items are present such that scrolling is available)

## Expected Result

When using ⌘+⇧+Y to open the toolbar popup window, the first login item should be automatically selected/highlighted, indicating that the user can then press ↵ to autofill that login item in the current tab. Pressing ↹ and/or ↑/↓ should navigate between any additional login items. Pressing ↑/↓ should *not* navigate the user out of the list of login items; only pressing ↹ should allow that to happen.

## Screenshots or Videos

[bitwarden_bug.mov.zip](https://github.com/bitwarden/browser/files/5647848/bitwarden_bug.mov.zip)

## Environment

- Operating system: macOS Big Sur (11.0.1)
- Browser: Firefox 84
- Build Version (go to "Settings" → "About" in the app): 1.47.0

**Comment by PSalant726** [comment]
The [Help Center](https://bitwarden.com/help/article/auto-fill-browser/#keyboard-shortcuts-hot-keys) confirms that the expected behavior described above is the intended behavior.

**Comment by PSalant726** [comment]
@clayadams5226 Can you point me to the code change that addressed this issue please?

**Comment by sso-bitwarden** [comment]
Probably because this is a duplicate issue https://github.com/bitwarden/browser/issues/1236

**Comment by PSalant726** [comment]
Ah - thanks for the explanation!

**Comment by clayadams5226** [comment]
hey @PSalant726 apologies, I thought I linked the duplicate issue before I closed it.
