### ISSUE TITLE
Remember password pop-up banner not sticking after successful authentication (Safari)

### ISSUE THREAD

**Issue by sevensixseven** [bitwarden/browser#1487]
When using Safari (Big Sur), certain websites are not working as expected regarding the "Should Bitwarden remember this password for you?" pop-up banner. On some sites, after authentication is successful, the page will refresh and the banner will disappear after appearing for a short period of time. Some sites will refresh the banner as well and it will load again and stick but this is not the case of certain sites. I share a private video via an alternate channel.

**Comment by kspearrin** [comment]
I wasn't aware that the banner worked at all in Safari. Are you saying that it does for some websites?

**Comment by sevensixseven** [comment]
Yes, it is working on some sites. I will share the video with you.

**Comment by 3zero2** [comment]
It does indeed work on some sites, but the banner disappears as soon as the login page is refreshed with the new content. It doesn't give you enough time to read the message and respond.
