### ISSUE TITLE
Huge delay when Bitwarden extension is enabled in Safari (Intel)

### ISSUE THREAD

**Issue by silvetti** [bitwarden/browser#1492]
## Describe the Bug

Bitwarden Safari extension causes huge lag when starting Safari, difference between 1 second and 4 seconds when starting on an Intel i9 MacBook Pro 16 with 16GB RAM.

## Steps To Reproduce

1. Enable Bitwarden extension in Safari settings
2. Close Safari
3. Open Safari
(huge delay before Safari window opens)

## Expected Result

Safari to open as fast or close enough as it does with Bitwarden extension disabled.

## Actual Result

Huge delay, opening Safari, over 3 seconds before the Safari window even appears.
Does not happen when Bitwarden disabled.

## Screenshots or Videos

https://www.youtube.com/watch?v=C6ThjHfzfP8

## Environment

- Operating system: macOS Big Sur 11.0.1 (20B29)
- Browser: Safari Version 14.0.1 (16610.2.11.51.8)
- Build Version (go to "Settings" → "About" in the app): Version 1.22.2 (400)

## Additional Context

**Comment by SergeantConfused** [comment]
Hi there,

Did you try to uninstall Bitwarden, reboot your computer, and then reinstall it?


Thank you in advance,

**Comment by silvetti** [comment]
> Hi there,
> 
> Did you try to uninstall Bitwarden, reboot your computer, and then reinstall it?
> 
> Thank you in advance,

Hi!
Yes I did.
Same results.

**Comment by muzzah** [comment]
I too am seeing this as soon as I upgraded to 10.15.7. I know its bitwarden because if I open activity manager, bitwarden is not responding in there. 

MacBook Pro (15-inch, 2017)

**Comment by silvetti** [comment]
I might need to move off Bitwarden, this makes it completely unusable :(

**Comment by cscharf** [comment]
Thanks for the report! We will be releasing a new version of the browser extension for Safari in Feb, 2021; based on the Web Extension framework vs. the current App Extension today. This should completely change the game for our Safari users, we simply need some time for regression testing before releasing it. As of right now we don't plan to maintain or further troubleshoot issues with the current Safari App Extension. se: https://github.com/bitwarden/browser/pull/1531. This issue will now be closed, thanks again and looking forward to getting this new extension out to everyone.
