### ISSUE TITLE
Failed to differentiate email and username

### ISSUE THREAD

**Issue by tddschn** [bitwarden/browser#1494]
## Describe the Bug

When using Bitwarden extension's autofill, username from Bitwarden sometimes is filled to the email field (on the Sign Up pages).

It seems that the extension does not differentiate email and username, and autofill will fill the value of the username to the first field of the login form that is not password.

## Steps To Reproduce

1. Go to any account registration page that requires user to input his/her 1) email address, 2) username, 3) password (ordered in this way)
2. Add a new account for this site in the Bitwarden extension, use a username in the username field, not an email address, and click Save.
3. Click on the newly created account in the extension UI, username gets autofilled into the email address field on the site (unwanted behavior), and password filled to to password field as expected.

## Expected Result

Value of username gets filled in the username field, not the email field or other fields.

## Actual Result

The extension does not differentiate email and username, and autofill will fill the value of the username to the first field of the login form that is not password.

## Environment

- Operating system: macOS Big Sur 11.0.1
- Browser: Google Chrome 87.0.4280.88
- Build Version: 1.47.1

**Comment by wusatosi** [comment]
Can you provide an example website to reproduce this bug?

**Comment by tddschn** [comment]
@wusatosi I'll reply to this thread next time I see such website. :)

**Comment by clayadams5226** [comment]
Hi @tddschn , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
