### ISSUE TITLE
Vivaldi: "Unfortunately this window is not available in private mode for this browser"

### ISSUE THREAD

**Issue by avens19** [bitwarden/browser#1495]
## Describe the Bug

Extension in Vivaldi is now showing the error "Unfortunately this window is not available in private mode for this browser" in the extension window, even when not in a private tab.

## Steps To Reproduce

- Install extension in Vivaldi
- Open extension window

## Expected Result

It should show my vault

## Actual Result

It is showing "Unfortunately this window is not available in private mode for this browser"

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/2607693/102117971-4a262980-3dfc-11eb-95bc-f25ed65cb26d.png)

## Environment

Vivaldi	3.3.2022.47 (Stable channel) (64-bit)
Revision	0ccf6997c3958ed4378f4fdea56f2dcf01757962
OS	Windows 10 OS Version 2004 (Build 19041.685)

**Comment by lschober-bw** [comment]
Hi @avens19,

The extension seems to be working properly in Vivaldi private windows with the most up-to-date version for Windows, v3.3.2115.81  Can you try updating your browser and giving it a try?
