### ISSUE TITLE
Asana Integration Test Issue

### ISSUE THREAD

**Issue by MGibson1** [bitwarden/browser#1500]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by wusatosi** [comment]
????????????????

**Comment by MGibson1** [comment]
This was to test our internal integration with our Asana boards. Don't worry about it ;)
