### ISSUE TITLE
Keyboard shortcut conflict in Firefox >= 84

### ISSUE THREAD

**Issue by 8d4eg6** [bitwarden/browser#1501]
## Describe the Bug

Firefox was updated to version 84.0+build3-0ubuntu0.20.04 this this morning, and the shortcut Ctrl + Shift + B to open the Bitwarden menu now conflicts with the shortcut to show/hide the bookmark toolbar.

## Steps To Reproduce

Upgrade Firefox to version 84 on Linux, install the Btiwarden addon, press Ctrl + Shift + B. 

## Expected Result

Bitwarden addon menu appears.

## Actual Result

The bookmark toolbar is toggled.

## Environment

- Operating system: Ubuntu 20.04
- Browser: Firefox 84
- Build Version: 1.47.1

**Comment by Greenderella** [comment]
Hi @8d4eg6 if you click the Menu button > click the Addons-icon > select Extensions (https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox), you should be able to customize them:

![image](https://user-images.githubusercontent.com/5418577/102639516-7671db00-4159-11eb-89f7-863e4fbe899b.png)
