### ISSUE TITLE
Google browser extension login prompts for invalid master password.

### ISSUE THREAD

**Issue by gebangfeng** [bitwarden/browser#1502]
![image](https://user-images.githubusercontent.com/56078492/102679092-e7f86a80-41e7-11eb-994f-6588013a95d4.png)
The solution I tried to learn was to log out of my account first.And then you log in and you log in.But there is no way to unlock the screen with the master password after each lock.
What surprises me most is that my other computer doesn't have this problem.My attempt to uninstall the extender still didn't work

**Comment by SergeantConfused** [comment]
Hi there,

Are you using a self-hosted Bitwarden server?


Thank you in advance,

**Comment by wusatosi** [comment]
This is happening to me too.
I am self-hosting a bitwarden server.

I personally think this is a client problem, as both the chrome extension and the windows app are having this problem as they updated to the latest version.

**Comment by gebangfeng** [comment]
The problem we have is one of the following links that we can also focus on
https://github.com/bitwarden/browser/issues/1456

**Comment by gebangfeng** [comment]
> 嗨，您好，
> 
> 您是否正在使用自托管的Bitwarden服务器？
> 
> 先感谢您，

Yes, I use a self-managed server

**Comment by cscharf** [comment]
This is an issue with older versions of Bitwarden server OR alternate servers which have not kept up to date with client data requirements. Please contact your alternate server repo's owner OR update your self-hosted server to the latest version to resolve this issue. You will need to restart your server + log out and back into your extension after the server update to permanently correct this issue.
