### ISSUE TITLE
White space and newlines are ignored when displaying notes

### ISSUE THREAD

**Issue by iain-id** [bitwarden/browser#151]
Any newlines or white-space is removed from the notes field when it is displayed via the browser add-on.

![image](https://cloud.githubusercontent.com/assets/28516860/25785969/ab17136e-33e0-11e7-9e5b-6bf3ffb45b55.png)

![image](https://cloud.githubusercontent.com/assets/28516860/25785951/4a9d025a-33e0-11e7-830c-476558f0c029.png)

**Comment by kspearrin** [comment]
Thanks.

**Comment by kspearrin** [comment]
Fixed next version. 1.13.3+
