### ISSUE TITLE
Autofill not working for this site

### ISSUE THREAD

**Issue by bong0** [bitwarden/browser#1511]
## Describe the Bug

Autofill does not work on https://mein.greenpeace-energy.de/ 

## Steps To Reproduce

1. go to https://mein.greenpeace-energy.de/
2. try autofill 

## Expected Result

user/password filled out

## Actual Result

no change at all

## Environment

- Operating system: macos 10.15.7
- Browser: firefox 84.0
- Build Version 1.47.1

**Comment by apmarshall** [comment]
Is there any sort of error in the output or just nothing happens?

If you try copying and pasting your password from Bitwarden, what happens? Some sites block paste for password fields.

**Comment by bong0** [comment]
@apmarshall thanks die asking!

There are no errors, just nothing happens, as if they aren’t detected for example.

Copy paste *is* working, I used this way to login after all, but each field separately of course.

**Comment by apmarshall** [comment]
I'm not on a device where I can check this right now, but I am wondering if the fields aren't labeled in the HTML so that Bitwarden can know what they are. Can you paste the HTML source of the login form on the page?

**Comment by bong0** [comment]
This is the outer and inner HTML of the form section

```
<form enctype="application/json">
                    <input-element id="email" bind-name="email" label="E-Mail-Adresse oder Kundennummer *" placeholder="E-Mail-Adresse" required="" optional="" pristine="" invalid=""></input-element>
                    <input-element id="password" bind-name="password" label="Passwort" placeholder="Passwort" type="password" autocomplete="on" required="" optional="" pristine="" invalid=""></input-element>
                    <p class="pflichtfelder">
                      <sup>* Email-Adresse oder Kundennummer oder Benutzername aus
                        dem Mitgliederportal</sup>
                    </p>
                    <br>
                    <submit-button-outline>
                      Login
                    </submit-button-outline>
                  </form>
```

**Comment by apmarshall** [comment]
So it looks to me like they are using some sort of custom HTML elements here: `input-element` instead of regular old `input`. I'm not sure if that is related to the issue: could be that those custom elements aren't being picked up when BW searches the DOM for username/password fields. If so, I'm sure that could be fixed by amending BW's search to include some "common" names for custom elements. But I'm not sure how generalizable that solution would be (as in, how many custom element names would be needed to cover both this site and others with a similar issue).

**Comment by johnpiapian** [comment]
I just checked it. Although a custom HTML element(input-element) is used as a container, there is also a valid input element if you inspect it on Chrome. My guess is that the form is dynamically injected using Javascript that is messing up the autofill.
