### ISSUE TITLE
Safari extension won't display another language that's it is not English

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/browser#1513]
## Describe the Bug

Safari extension won't display another language that it is not English despite setting it up correctly in the app menu.

## Steps To Reproduce

1) Go to Apple menu 
2) System Preferences and 
3) Click Language & Region
4) Click on Apps > Safari 
5) And select any language that it's not English
6) If Safari is open, quit (Command + Q) and relaunch Safari
7) Open Bitwarden browser extension and corroborate language applied

## Expected Result

The browser extension should be displayed in the selected language if a translation exists.

## Actual Result

The browser extension is displayed in English.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5418577/103447643-27b25e00-4c8e-11eb-97ce-1dde4aa7594f.png)

## Environment

- Operating system: macOS Catalina
- Browser: Safari 14.0.2
- Build Version: 1.47.1

**Comment by eliykat** [comment]
Hey @Greenderella, I couldn't reproduce this on our latest build (switching from English to Spanish - Latin America). The language changed as expected after I restarted Safari. For some reason I can't install the App Store version, so I haven't tested on that. Can you still reproduce it at your end?

## Environment
* Operating system: macOS Big Sur
* Browser: Safari 14.0.3
* Build version: 1.50.0 built from [this commit](https://github.com/bitwarden/browser/commit/2c58dbb344655bd4edfb7fec5825d238de24eabe)

**Comment by Greenderella** [comment]
The issue seems to be no longer present, I'm also unable to reproduce it.

/closed
