### ISSUE TITLE
TOTP codes in browsers not working

### ISSUE THREAD

**Issue by TooMuchRAM** [bitwarden/browser#1514]
## Describe the Bug

When logging into any website where 2 factor authentication is enabled using TOTP and the TOTP code is loaded into the Bitwarden browser extension, the code that is copied to the clipboard when logging in is incorrect. The code shown in the extension window is also incorrect.

## Steps To Reproduce
1. Go to any site where 2FA is enabled and the TOTP code is saved to Bitwarden
2. Autofill username and password and log in
3. Paste the 2FA code provided by Bitwarden into the correct field

## Expected Result
The code works and the log in process should be successful

## Actual Result
The code is rejected by the website.

## Screenshots or Videos
https://user-images.githubusercontent.com/39091235/103454119-0cbd0980-4ce1-11eb-95e4-49de2d94a728.mp4

## Environment

- Operating system: Linux, Windows 10
- Browser: Firefox 84.0.1, Chromium 87.0.4280.88 (Linux)
- Bitwarden app 1.23.1, Extension 1.47.1

## Additional Context

2FA codes from the mobile app work fine.

**Comment by SergeantConfused** [comment]
Hi there,

The most common cause of issues with TOTP is having the wrong time or time zone set on the device that is generating the TOTPs. Please make sure that the time and time zone on your computer are accurate, then it would generate the correct TOTP.

Please let me know how this goes.

All the best,

**Comment by TooMuchRAM** [comment]
It was indeed the issue. My clock was off by a few minutes; not enough to notice right away, but just enough to screw over the TOTP codes. Thank you!

**Comment by Corrodias** [comment]
How is there a right or wrong time zone? What is the "right" time zone? How should we know? How can we log in if we travel and are no longer residing in the "right" time zone?
