### ISSUE TITLE
Compact and expand folders from the vault

### ISSUE THREAD

**Issue by iain-id** [bitwarden/browser#152]
If a user has a large number of passwords in folders it would be very helpful to be able to compact and expand folders in the My Vault tab of the browser plugin.  Also having a option to compact/expand all folders would help.

**Comment by kspearrin** [comment]
We actually already have this option but it is automatically activated whenever you have more than 100 Logins in your vault. Maybe we should make it available all the time?

**Comment by iain-id** [comment]
Thank you for your fast reply.  I personally think that it should be on by default, possibly with an option to turn it off.

**Comment by kspearrin** [comment]
No plans on changing this behavior at this time.
