### ISSUE TITLE
No creds options for Paypal modal window when asked from eBay.com

### ISSUE THREAD

**Issue by jjdelc** [bitwarden/browser#153]
I'm not sure if https://github.com/bitwarden/browser/issues/80 refers to this as well. But when you're logged into eBay and want to make a Payment a modal window for your Paypal credentials will show up and the Bitwarden options don't show Paypal to pick.

**Comment by kspearrin** [comment]
Can this be corrected with a `ebay.com, paypal.com` domain rule?

**Comment by jjdelc** [comment]
What is that? A configuration I can make?

I think the detection could be based on the `action` domains for the forms in the page. For the Paypal modal, the login form should point to `paypal.com` I'm don't know if it's inside an iframe, but it must be a different `action` domain that the ebay login form.  This way, the Paypal credentials are only available on the UI if there is a Paypal form shown. If I linked both ebay.com and paypal.com I'd see the Paypal credentials available when I want to login at eBay.com and there is no use for Paypal credentials there.

**Comment by kspearrin** [comment]
See https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by jjdelc** [comment]
In my case I use different username and password for eBay and Paypal.

The blog post does not explain how the extension behaves after this configuration is done, but if it happens that when I am in ebay.com I see the options for ebay.com and paypal.com, then that would be an OK work around.

That means that when I log in directly to Paypal I'll see the creds for ebay.com that on this case are of no use, and that when I log in to eBay I have the option to enter Paypal creds, which are also unneeded there.

**Comment by kspearrin** [comment]
@jjdelc Yes, that is how it works.
