### ISSUE TITLE
Feature Request: TouchID access on Macbooks

### ISSUE THREAD

**Issue by Vinz87** [bitwarden/browser#1540]
The desktop application has the super-useful feature of access by TouchID available on Macbooks equipped with TouchID sensor.
Could it be possible to replicate this feature in the Safari browser extension?

**Comment by SergeantConfused** [comment]
Hi there,

Absolutely, this is in development right now, and you can see it on our roadmap here: https://community.bitwarden.com/t/bitwarden-roadmap/12865

Please keep me posted if you have any further questions.

All the best,

**Comment by cscharf** [comment]
Closing this issue as this will be released this week and we use GitHub to track issues vs. feature requests. Thanks!
