### ISSUE TITLE
The set PIN suddenly/randomly stops (stopped) working in both Firefox and Safari

### ISSUE THREAD

**Issue by justauserid** [bitwarden/browser#1543]
## Describe the Bug

The PIN I have been using on the Mac in both the browser Safari and Firefox suddenly stopped working just now. It's the same PIN I used last night and have been using since the last 6-7 months. 

## Steps To Reproduce
1. Have a set PIN in your browser(s) - in my case Safari and Firefox
2. Restart browser 
3. Enter PIN
4. PIN doesn't work

## Expected Result

The set PIN should be accepted.

## Actual Result

The error message indicated it was not the same PIN.

## Screenshots or Videos

This is the message that shows on browser add-on pop-up bottom with a lighting icon in red colour.
```
An error has occurred
Invalid PIN code.
```

## Environment

- Operating system: Mac OS Catalina
- Browser: Firefox 84.0.2 (64-bit), Safari 14.0.2
- Build Version 1.47.1

## Additional Context

I have no idea what else to write in the steps for this issue because I am not able to reproduce this. It doesn't happen every day. It had happened a couple of times before. PIN suddenly stopped working again. Earlier I used to think I must have forgotten the PIN and that's why this time I had saved it in KeePass and also ensured that I was using the PIN at least 2-3 times everyday across the browsers and I did. Then this morning it didn't work. It worked last night before I had to **force quit** Firefox and Safari as my laptop was running very slow. And after that, while I had restated browsers, I didn't enter the PIN until now in the morning.

I had to log in with my password and username and 2FA and then set the PIN again (same PIN actually) and it has been working (tried to lock manually a couple of times and then unlock with PIN again).

I am raising the issue because this time I am 100% sure it was the same PIN I had set. (I use the same PIN for Authy Desktop as well - and some more PIN protected apps on mobile and desktop, and it's working perfectly fine)

**Comment by clayadams5226** [comment]
Hey @justauserid, Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by justauserid** [comment]
I am going to do that. Also, I restated my computer, and it's not working in Safari now. It worked in Firefox.

@clayadams5226 By the way, why did you close the issue here? 

Also, please know that I will not be able to provide my Bitwarden account info or account email. Because it's entirely different from this GitHub account (and email) I am using, and I would want to keep that way. However, I will be able to provide any logs or non identity information you'd need.

**Comment by clayadams5226** [comment]
Hey @justauserid, the issue was closed here because we believe the issue can be resolved by contacting support and there isn't anything the dev team needs to do. If that ends up not being the case we can always reopen this one or support will open a new one.

**Comment by justauserid** [comment]
@clayadams5226 I am getting this error when I try to submit the form you pointed me to:

```
405 Method Not Allowed

- Code: MethodNotAllowed
- Message: The specified method is not allowed against this resource.
- Method: POST
- ResourceType: OBJECT
- RequestId: 3A3C2FA8AEA7331B
- HostId: D34KGwBEZuZFUO6rX6Lwzw303UqMHrSKsNwoZrI4/w4P9s1wrWv/myg3xE90hqe9NaA6s3htDRE=

```
There are no content/tracking blockers in the browser (and yes of course I am not logged in but I guess that should not be an issue)

**Comment by clayadams5226** [comment]
The contact page should be operational again. Please try to submit your ticket again.

**Comment by clayadams5226** [comment]
Re-opening after support was unsuccessful in finding a root cause.

**Comment by justauserid** [comment]
Is there any specific logs needed?
Should I enable some specific log level so that next time I face it I can just share the logs?
