### ISSUE TITLE
Bitwarden permission change warning on brave browser

### ISSUE THREAD

**Issue by jibraniqbal666** [bitwarden/browser#1549]
## Describe the Bug
shows this warning with the new update, that Bitwarden needs "Communicate with cooperating native applications".

## Steps To Reproduce

1. Go to 'Brave'
2. Update bitwarden

## Expected Result
should show warning but Bitwarden should give some explanation.

## Actual Result
shows a horrible warning.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/30576574/105579838-c7a16a00-5daa-11eb-8896-675a78d4baaa.png)

## Environment

- Operating system: Mac OS Big Sur
- Browser: Brave Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)
-  Build Version: Version 1.19.86

## Additional Context
Must be a brave policy.

**Comment by lkhphuc** [comment]
Same popup in Firefox, so I came here to look for an explaination.
My guess is for it to communicate with the desktop to use the new biometric verification.

**Comment by Nepoxx** [comment]
Same in Chrome/Chromium. I feel like an explanation of why this permission is required is necessary. 

There are no posts on the [blog](https://bitwarden.com/blog/) either.

**Comment by orrc** [comment]
This is pretty much a duplicate of #1548.

But yeah, this [poorly documented change][0] in permissions in v1.48.0 is indeed required to [enable biometric unlock][1] (albeit probably unnecessarily, as mentioned in #1548).

[0]:https://twitter.com/orrc/status/1353027069991649281
[1]:https://bitwarden.com/help/article/security-faqs/#q-why-does-the-browser-extension-need-nativemessaging-permission

**Comment by clecap** [comment]
And it shows very bad judgement to role out this change without any further communication with the users.

This is exactly what you would see in case of a security attack against the extension.

Sorry, to be so harsh in my feedback - but Bitwarden is the third password manager I am using. The other two I left since they just did the same rubbish: Polishing up the UI, adding additional features - with the effect of making the system less secure.

**Comment by guilhermegarcz** [comment]
> And it shows very bad judgement to role out this change without any further communication with the users.
> 
> This is exactly what you would see in case of a security attack against the extension.
> 
> Sorry, to be so harsh in my feedback - but Bitwarden is the third password manager I am using. The other two I left since they just did the same rubbish: Polishing up the UI, adding additional features - with the effect of making the system less secure.

Exactly, Thought the application was compromised still feel weird about accepting this permission, can't this be made optional?

**Comment by bialad** [comment]
Went digging around for release notes, and found this.

https://bitwarden.com/help/article/biometrics/#browser-extensions

So the change seems legit, but should for sure be optional. I won't be using this functionality for example.

**Comment by Mixermachine** [comment]
Some of my users already called and asked me what is up with this change.

PLEASE communicate this better.

**Comment by escape0707** [comment]
If we are going to implement optional permissions, maybe fix issue #883, too.

**Comment by SergeantConfused** [comment]
Hi there,

This new permission allows the browser extension to communicate with your local desktop client to use biometrics to unlock the vault. More on this here: https://bitwarden.com/help/article/releasenotes/ and here: https://bitwarden.com/help/article/biometrics/#browser-extensions

I hope this clarifies this, please let me know if you have any further questions.


All the best,

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/browser/issues/1548

**Comment by Danie10** [comment]
This is a pretty irritating issue, and has taken me days to track down this post. I can second others in saying it was not well implemented. I have two Brave browsers open and they keep locking me out after a while, despite the vault being set to not do so.

I've installed the desktop client on my Linux and that unlocks fine with my biometrics, and despite it being set to 'Enable browser integration' my browser extension for Bitwardens keeps saying:

```
Browser integration is not enabled
Browser integration is not enabled in the Bitwarden Desktop application. Please enable it in the settings within the desktop application.
```
Just very messy and Bitwarden was really working seamlessly up to the end of January for me.

**Comment by TheAGames10** [comment]
Can I bring this back in 2026? because i'm now getting this action required for this exact message as of June 26, 2026, and I don't know if I should accept the permissions or not.

**Comment by notkudu** [comment]
why is it forced now? 

<img width="448" height="229" alt="Image" src="https://github.com/user-attachments/assets/c0d043fe-1afc-46c0-86c7-f37eccec55b9" />

**Comment by pamperer562580892423** [comment]
@TheAGames10 @notkudu See this explanation from @quexten (BW developer): https://community.bitwarden.com/t/browser-2026-6-0-vivaldi-permission-question/98206/6
