### ISSUE TITLE
Search function not working for login notes and secure notes

### ISSUE THREAD

**Issue by perariontaeadastra** [bitwarden/browser#1552]
## Describe the Bug

Search is broken after latest update. Doesn't search in the Notes fields for any kind of items (logins, secure notes), returns search results from logins fields only. 
## Steps To Reproduce

Update plugin. 
Create login or secure note. 
Enter some text, save and then search for it.

## Expected Result

Should return matching text from notes fields as well.
## Actual Result

Search is broken after latest update. Doesn't search in the Notes fields of any kind of items (logins, secure notes), returns search results from logins fields only. 
## Environment

- Operating system: [Windows 10, Mac OS Catalina]
- Browser: [Brave 1.19.86, Chrome 88.0.4324.104]
- Build Version : [e.g. 1.48.0]

## Additional Context

This issue also concerns Desktop versions of Bitwarden, Windows and Mac OS alike.

**Comment by zoredache** [comment]
I believe I am also seeing the same behavior on Chrome with 1.48.0.

**Comment by x19er** [comment]
I'm seeing this as well on Firefox 84.0.2 on Win10. Add-on version 1.48.0

**Comment by shackrock** [comment]
Confirmed on Brave (chrome) v1.48

**Comment by lumpysimon** [comment]
Confirmed here too. I used to be able to search name and content of secure notes, now results are only returned for the name of the secure note, not the content.

**Comment by cscharf** [comment]
Similar/possibly the same issue as: https://github.com/bitwarden/desktop/issues/679

**Comment by cscharf** [comment]
Will be resolved with:
* https://github.com/bitwarden/jslib/pull/251
* https://github.com/bitwarden/desktop/pull/683
* https://github.com/bitwarden/web/pull/810
* https://github.com/bitwarden/cli/pull/219
* and https://github.com/bitwarden/browser/pull/1569

**Comment by lumpysimon** [comment]
Thank you Chad, much appreciated

**Comment by cscharf** [comment]
Fixed and closing, v1.48.1 resolves this issue and has been submitted to the extension stores.
