### ISSUE TITLE
Cannot TAB to the Unlock with biometrics button in the browser extension.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1557]
## Describe the Bug
You cannot reach the Unlock with biometrics button in the browser extension without using the mouse.

## Steps To Reproduce
1. On Windows and Chrome, lock your browser extension.
2. Hit CTRL+SHIFT+Y to open the extension.
3. Hit TAB repeatedly.

## Expected Result
To reach the Unlock with biometrics button.

## Actual Result
The focus circles through all other fields and buttons.

## Screenshots or Videos
N/A.

## Environment

- Operating system: Windows 10 Pro 19042.746.
- Browser: Chrome Version 88.0.4324.104.
- Build Version: 1.48.0.

## Additional Context
N/A.

**Comment by Hinton** [comment]
This issue was resolved in https://github.com/bitwarden/browser/pull/1578.
