### ISSUE TITLE
Brave browser extension cannot find biometrics integration on Mac OS

### ISSUE THREAD

**Issue by brandonguigo** [bitwarden/browser#1558]
## Describe the Bug

I've tried to enable browser biometrics on Brave for Mac and it says that browser integration is not activated even when it is.

## Steps To Reproduce

1. Go to Desktop app
2. Enable browser integration
3. Go to brave extension
4. Try to enable biometrics

## Expected Result

Biometrics should enable

## Actual Result

No browser integration found.

## Environment

- Operating system: Mac OS Big Sur
- Browser: Brave 
- Build Version: 1.19.86

**Comment by richartkeil** [comment]
I can reproduce this for Chrome 87.0.4280.141 on Mac OS Big Sur. Bitwarden from the App Store is on 1.24.1 (509) and the Chrome extension on 1.48.0. Restarting both chrome and Bitwarden did not resolve the issue.

**Comment by gleichda** [comment]
I can confirm the same for Firefox.
FF: 84.0.2
Extension: Version: 1.48.0
Desktop App: Version 1.24.1 (509)

**Comment by Stahlreck** [comment]
Same issue with Edge (Chromium) on Windows 10 though I did install the extension from the Chrome Web Store...not sure if that has something to do with it.

Windows 10 v2004
Edge 88.0.705.50
Extension version: 1.48.0
Desktop App version (from the Microsoft Store): 1.24.1

**Comment by adrianghc** [comment]
> Same issue with Edge (Chromium) on Windows 10 though I did install the extension from the Chrome Web Store...not sure if that has something to do with it.
> 
> Windows 10 v2004
> Edge 88.0.705.50
> Extension version: 1.48.0
> Desktop App version (from the Microsoft Store): 1.24.1

I installed the extension from the Edge extension store and have the same issue.

**Comment by PlanetWilson** [comment]
Confirmed the same with Firefox on M1 MacBook Air.

MacOS 11.1
FF 85.0
Extension 1.48.0
Desktop app version from App Store 1.24.1

**Comment by cscharf** [comment]
Should be resolved with https://github.com/bitwarden/desktop/pull/678

**Comment by Tealk** [comment]
I just installed an update from Bitwarden, desktop 1.24.4 and extension 1.48.1
Now the setting for the Beometirie in the settings of the extension is completely missing.

**Comment by cscharf** [comment]
Hi @Tealk , Safari isn't quite yet supported here until we release the Web Extension port in Feb. You should be able to use it on any chromium based browser on macOS however (Chrome, Brave, Opera, Edge, Vivaldi, etc., etc.). We just didn't want to release the Safari extension port to a Web Extension (vs. App Extension) until we had a chance to go through thorough regression testing.

**Comment by 5moufl** [comment]
> Hi @Tealk , Safari isn't quite yet supported here until we release the Web Extension port in Feb. You should be able to use it on any chromium based browser on macOS however (Chrome, Brave, Opera, Edge, Vivaldi, etc., etc.). We just didn't want to release the Safari extension port to a Web Extension (vs. App Extension) until we had a chance to go through thorough regression testing.

Should we open a different issue for Firefox and its derivatives?

**Comment by cscharf** [comment]
> Should we open a different issue for Firefox and its derivatives?

No, an issue has already been opened and we have made the decision not to support Firefox until Mozilla provides upstream support for optional permission of `nativeMessaging `, please see this help note: https://bitwarden.com/help/article/biometrics/#browser-extensions

**Comment by cscharf** [comment]
@brandonguigo , this should be resolved with the extension version 1.48.1 and desktop version 1.24.4. Closing this for now, please let us know if you're still experiencing this issue after upgrading to the latest extension and desktop app.

**Comment by Tealk** [comment]
> Hi @Tealk , Safari isn't quite yet supported here until we release the Web Extension port in Feb. You should be able to use it on any chromium based browser on macOS however (Chrome, Brave, Opera, Edge, Vivaldi, etc., etc.). We just didn't want to release the Safari extension port to a Web Extension (vs. App Extension) until we had a chance to go through thorough regression testing.

I don't plan to ever use a Chromium based browser.
I'm just surprised that the feature was already selectable and the email support told me that the next update should fix the problem.

**Comment by cscharf** [comment]
> And why doesn't it work for FF?

Please see discussion here: https://github.com/bitwarden/browser/issues/1548#issuecomment-767027871

> email support told me that the next update should fix the problem.

I understand the frustration, we had to make some very fast decisions as we worked through the final release phases of this update, which was a massive update to the product, and I'll take responsibility for any miscommunication/misunderstandings that may have occurred during that timeframe. As a team we're constantly looking to improve and ensure we offer the best experience to our users, community and team across the board. Thank you for your patience and feedback!

**Comment by brandonguigo** [comment]
@cscharf I've not the same issue now : i can activate biometrics but no confirmation dialog pops up in the desktop app

**Comment by cscharf** [comment]
@brandonguigo , please see the comment from [this community thread](https://community.bitwarden.com/t/new-browser-extension-not-working-with-biometric-login/16902/31) for background; otherwise you should be able to go into settings on your desktop app, uncheck and re-check the enable browser integration and that should allow it start working again. Let me know if that's still not working for you.

**Comment by tgreer-bw** [comment]
@brandonguigo you may also need to enable the "allow access to file URLs" permission in the extension permissions.

**Comment by brandonguigo** [comment]
@tgreer-bw The extension setting made it work! thanks! 

@cscharf Any idea on how to directly prompt for biometrics when setting is enable ?

**Comment by cscharf** [comment]
> Any idea on how to directly prompt for biometrics when setting is enable ?

@brandonguigo , not sure I know what you mean by that question, sorry :-(. Depending on the desktop platform you're using and browser, there may be slightly different experiences; however when I use it, for example, on Brave on macOS, all I see when I try to unlock the extension is the TouchID prompt vs. the desktop app (which is hidden from the dock).

**Comment by brandonguigo** [comment]
> > Any idea on how to directly prompt for biometrics when setting is enable ?
> 
> 
> 
> @brandonguigo , not sure I know what you mean by that question, sorry :-(. Depending on the desktop platform you're using and browser, there may be slightly different experiences; however when I use it, for example, on Brave on macOS, all I see when I try to unlock the extension is the TouchID prompt vs. the desktop app (which is hidden from the dock).


I was meaning that it would be cool to not to have to click on the use biometrics button when we have to login on the browser, just have the Touch ID prompt when cmd+maj+Y'ing. Is it clearer ?

**Comment by cscharf** [comment]
@brandonguigo , Yes, that is clearer now... Please feel free to open up a request on the [Bitwarden Community Forums](https://community.bitwarden.com) for that enhancement (I know we implemented it on Desktop already so it shouldn't be _too_ much of a stretch I wouldn't think, but needs voting and prioritization).

**Comment by p-vernaeckt** [comment]
Thanks @tgreer-bw !
I use Brave and had to enable "allow access to file URLs" permission. It's a bit sad I had, as a user, to dig into this repo's issues to find the answer though...

**Comment by tgreer-bw** [comment]
@p-vernaeckt glad it worked! For those who may need it in the future, we have this help article with more info: https://bitwarden.com/help/article/biometrics/#native-messaging-permissions

**Comment by p-vernaeckt** [comment]
Thank you. Maybe a small caption right under the option in BW's Chrome extension with an link to this page would help too ;)

**Comment by Tealk** [comment]
Which version do you need for this, I currently have version: 1.48.1 and there the setting is missing.
