### ISSUE TITLE
Biometric unlocking w/ desktop companion app does not work w/ Firefox Windows 10

### ISSUE THREAD

**Issue by winkler-winsen** [bitwarden/browser#1560]
## Describe the Bug

I read about "Biometric unlocking w/ desktop companion app" in https://github.com/bitwarden/browser/releases/tag/v1.48.0 

So I updated my Bitwarden Desktop App (Store) zu 1.24.1 and the Firefox Addon to 1.48.0.

When I try to activate "use biometrics" in Firefox Addon, I got the message to activate browser-integration feature in Desktop App first. So, I activate this in the Desktop App. But Firefox Addon says same message. So I activated in Desktop App check für browser-integration. But Firefox Addon message still exists.

Biometrics aren't useable in Firefox Addon.

## Steps To Reproduce

I'm using german language version. So I try to translate the german options and messages into english.
1. Update Bitwarden Desktop App (Store) zu 1.24.1 and the Firefox Addon to 1.48.0
2. in Desktop App activate "use Windows Helo to unlock" .. works fine
3. In Desktop App activate "browser integration" 
4. In Firefox Addon activate "use biometeics to unlock" 
5. Firefox Addon gives messages "[Browser integration is not enabled](https://github.com/bitwarden/browser/blob/eec9ba3277ed8b1fb35149311ed91cf4a6794e61/src/_locales/en/messages.json#L1399)" and "[Browser integration is not enabled in the Bitwarden Desktop application. Please enable it in the settings within the desktop application.](https://github.com/bitwarden/browser/blob/eec9ba3277ed8b1fb35149311ed91cf4a6794e61/src/_locales/en/messages.json#L1402)" ("desktopIntegrationDisabledTitle" and "desktopIntegrationDisabledDesc")
6. In Desktop App activate "check for browser-integration required"
7. In Firefox Addon same message appears

So. Biometrics are not useable in Firefox Addon.

## Expected Result

In my imagination, the desktop app opens and uses Windows Helo to ask for my fingerprint to biometrically unlock the browser addon. 

## Actual Result

Biometrics are not useable in Firefox Addon.

## Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/43114182/105692348-989c0d00-5efe-11eb-8037-f0274172eda1.png)

## Environment

**Windows 10 Pro** 64 Bit Version 20H2 Build 19042.746) 
**Firefox** 84.0.2 64 Bit
**Bitwarden Desktop App** (via Microsoft Store)
Version 1.24.1
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64
**Bitwarden Browser Addon** (via Firefox Addon Store)
Verion 1.48.0

## Additional Comments ##
For sure, I granted Firefox Access to use external programs:
![grafik](https://user-images.githubusercontent.com/43114182/105693030-82428100-5eff-11eb-8143-d317c49380b8.png)

**Comment by jordanbertasso** [comment]
Same issue running:
* macOS Catalina (10.15.7)
* Firefox (84.0.2)
* Bitwarden Desktop Client (1.24.1 (509))
* Bitwarden Firefox browser extension (1.48.0)

**Comment by adrianghc** [comment]
Same issue here, although running Edge instead of Firefox.

**Comment by dimonkov** [comment]
Same here, 

- MacOS 11.1
- Brave 1.18.77
- Bitwarden Desktop Version 1.24.1 (509)
- Bitwarden browser extension Version: 1.48.0

**Comment by cscharf** [comment]
Should be resolved with https://github.com/bitwarden/desktop/pull/678.. For Edge on macOS, there is another PR that will hit soon. All will be released together to resolve this issue re: MAS version.

**Comment by jonathanmmm** [comment]
@cscharf Ok, just saw this new feature (sadly seeing it through getting the permission prompt and googling as it seemed suspicious). Installed the UWP App, as it was easier to update and seemed more containerized (if I am right about how UWP Apps are handled on Windows?).
But great, that a fix for Desktop App is on the way.
Does Microsoft somehow documents how UWP Apps support communication with outside UWP?

**Comment by cscharf** [comment]
> Does Microsoft somehow documents how UWP Apps support communication with outside UWP?

@jonathanmmm , this is due to the need for registry key access in Windows 10; it looks like we'll just need to spend a little extra time working through the additional approval with Microsoft or a workaround to get native messaging app to work from  UWP. See: https://stackoverflow.com/a/55315334. It's not that we won't support it, but that at the moment we've not decided on the best approach or started work on that effort.

**Comment by cscharf** [comment]
Closing this issue, please see this [help note regarding Firefox support](https://bitwarden.com/help/article/biometrics/#browser-extensions).
