### ISSUE TITLE
Suggestions provided for the wrong website

### ISSUE THREAD

**Issue by FredrikDahlberg** [bitwarden/browser#1564]
## Describe the Bug

Firefox plugin suggests logins for the wrong website.

## Steps To Reproduce

1. Add a password for any website that uses subdomains. (myuser.somesite.something)
2. Go to another subdomain for the same domain. (someotheruser.somesite.something)
3. Password for the first website is suggested. (myuser.somesite.something)

## Expected Result

No suggestions.

## Actual Result

Login for the wrong website is suggested.

## Environment

Win 10 - Firefox 85.0b9 (64-bit)

**Comment by gzachos** [comment]
Probably because `Settings` -> `Options` -> `Default URI Match Detection` is set to `Base domain`. You can change the default behavior via Options menu or select a specific `Default Match Detection` option for each URI on a Login entry. For more help see: https://bitwarden.com/help/article/uri-match-detection/

**Comment by FredrikDahlberg** [comment]
@gzachos Thank you. You are correct. What a horrible design. Defaults are supposed to be safe...

This issue can be closed.

**Comment by DejfCold** [comment]
It is a compromise between usability and security. It is secure in a sense that you won't get the suggestion for `éxample.tld` if you have it saved for `example.tld`. However websites often change the subdomains where you login. For example when switching from custom solution (`example.tld`) to some sso provider (`sso.example.tld`) and it becomes less usable and even less secure in the sense that you then have to validate the url yourself (so it isn't `sso.éxample.tld`) and update the record in bitwarden itself.

**Comment by cscharf** [comment]
Well stated @DejfCold , thank you. I'll go ahead and close the issue @FredrikDahlberg , thank you for your candid feedback.
