### ISSUE TITLE
Shared passwords not accessible from Firefox add-on

### ISSUE THREAD

**Issue by yo-da-man** [bitwarden/browser#157]
I shared a lot of my passwords with another user I added to my account recently. As of this morning, all of these shared accounts and passwords do not show up in "My Vault", on my Firefox add-on. The Chrome add-on does not exhibit this behavior.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/core/issues/47

We are waiting on Mozilla to approve the version of the extension (1.12.0+) that supports sharing.

**Comment by kspearrin** [comment]
I just talked with the Mozilla team and v1.12.3 has now been reviewed and is available. Updating should bring in your shared logins.

https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/
