### ISSUE TITLE
Auto-fill is not working for these sites

### ISSUE THREAD

**Issue by TesterMan247** [bitwarden/browser#1571]
Auto-fill is not working for the following sites when you press the CTRL SHFT L hotkey or any other method:

https://www.lottoland.com.au
https://www.epicgames.com/id/login/epic
https://www.priorityguestrewards.com/login

Please see here for more information:
https://community.bitwarden.com/t/auto-fill-is-not-working-for-these-sites/16526

Issue first found on Chrome extension v1.47.1 and then also now happening on v1.48.0.

**Comment by Wever1985** [comment]
Still waiting on a fix for epicgames.com myself: https://github.com/bitwarden/browser/issues/1029

**Comment by setyb** [comment]
It will be good to determine if there is something in common for those 3 sites, or if each case is unique.

**Comment by TesterMan247** [comment]
Another site auto-fill is NOT working on:
`https://patelonline.com.au`

**Comment by MorningSleeper** [comment]
Add live.com to the list which Microsoft's outlook.com and hotmail.com redirect to. The URI detection seems to work as the multiple logins I have there surface in the Chrome extension and if I right click the form field I can manually insert the data but it does not auto fill on page load as specified in options.

**Comment by eliykat** [comment]
Thanks all. I'm compiling a list of sites that our autofill doesn't work for, so that we can figure out underlying issues and decide what we can and can't fix.

**Comment by TesterMan247** [comment]
Yes, lets get the auto-fill to work on all sites please....

**Comment by eliykat** [comment]
To help us track autofill issues, we've set up a dedicated issue here: #1621. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in that issue. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by setyb** [comment]
@eliykat :

> To help us track autofill issues, we've set up a dedicated issue here: #1621. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in that issue. Please also direct any discussion or questions to that issue. This issue will now be closed.

I'm sorry, I ***don't use Google***, nor do I recommend any of their products to others.  In fact, Google-run host names as well as all known Google IP addresses are completely blocked here.  ***Life is better without Google™.***

I'm happy to contribute via a non-Google open-source product.
