### ISSUE TITLE
chrome / macOS biometric not working

### ISSUE THREAD

**Issue by LanceSandino** [bitwarden/browser#1573]
keeps saying it's not enabled, but it is

**Comment by okalman** [comment]
Same in Firefox

**Comment by cscharf** [comment]
@LanceSandino , can you please try again from the latest version of the desktop app in the macOS App Store, v1.24.5? Please let us know if that helps.

@okalman , FF is not supported this go-round, please see [this discussion](https://github.com/bitwarden/browser/issues/1548#issuecomment-767027871).

**Comment by LanceSandino** [comment]
> @LanceSandino , can you please try again from the latest version of the desktop app in the macOS App Store, v1.24.5? Please let us know if that helps.
> 
> @okalman , FF is not supported this go-round, please see [this discussion](https://github.com/bitwarden/browser/issues/1548#issuecomment-767027871).

works! had to uncheck and recheck in desktop app, and it works now cool!

thank you

**Comment by cscharf** [comment]
Awesome, thanks for checking and glad it's working now. Closing this issue.
