### ISSUE TITLE
No option for biometrics access in Safari

### ISSUE THREAD

**Issue by Vinz87** [bitwarden/browser#1574]
## Describe the Bug

No option for biometrics access in Safari, even after enabling browser integration in desktop app.

![Schermata 2021-01-27 alle 00 58 30](https://user-images.githubusercontent.com/6201178/105922588-37c61f00-603b-11eb-8444-a6faca87b0f4.png)
![Schermata 2021-01-27 alle 00 58 48](https://user-images.githubusercontent.com/6201178/105922596-3a287900-603b-11eb-8941-b7813e0bd940.png)

## Steps To Reproduce

install v.1.24.5 from AppStore on macOS Big Sur 11.1

## Environment

- Operating system: macOS Big Sur 11.1
- Browser: Safari Versione 14.0.2 (16610.3.7.1.9)
- Build Version (go to "Settings" → "About" in the app): Versione: 1.48.1

**Comment by cscharf** [comment]
Hi @Vinz87 , this is expected as support for Safari won't drop until our web extension port goes live in Feb. Please see the release update note here: https://bitwarden.com/help/article/releasenotes/#2021-01-19-post-release-update

Thanks!
