### ISSUE TITLE
(Firefox) Contextual menu doesn't work

### ISSUE THREAD

**Issue by hamtaai** [bitwarden/browser#1581]
## Describe the Bug

On any page whenever I try to use the contextual menu for any action (auto-fill, copy username, copy password) It doesn't work most of the time.

## Steps To Reproduce

- go to e.g. https://vault.bitwarden.com/#/ (but this is not site-dependent)
- right click / Bitwarden / auto-fill (or copy username or copy password)
- (in case of a copy option was selected) Ctrl+V into a field

## Expected Result

- auto-fill works
- username/password gets copied to the clipboard

## Actual Result

No auto-fill and original content of the clipboard.

## Screenshots or Videos

-

## Environment

- OS: Ubuntu 20.04, Windows 10 (2004 or maybe newer, don't remember exactly)
- Browser: Firefox (84.0.2 for Ubuntu, 85 for windows)
- Build: 1.48.1 (had the same issue with 1.48.0, too, don't remember it being an issue in 1.47.x or earlier)

## Additional Context

Using the widget works as expected, so clicking on an item auto-fills, clicking on the password/username icons copies them to the clipboard.

**Comment by Greenderella** [comment]
Hi @hamtaai, I'm unable to reproduce this issue, contextual menu works on both Windows 10 and Ubuntu 20 with Firefox 84.0.2 and Bitwarden 1.48.1: 

![contextual menu](https://user-images.githubusercontent.com/5418577/106260819-1de63100-6221-11eb-90d9-9b69ad020ca0.gif)

Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?

Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues. Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by hamtaai** [comment]
Alright, removing the extension in itself did nothing, but removing the extension and then removing the leftover data solved it. I'll try it later on Windows, too.
Thank you for the help!

**Comment by hamtaai** [comment]
Followup for windows: removing the extension and installing it again did the trick (for whatever reason there was no leftover data like on Ubuntu, so that's weird but ok). Thank you again!

**Comment by vrnvorona** [comment]
Removing extension and cleaning folder didn't help
MacOS 12.3
Firefox 100.0.1
Bitwarden 1.58.0

Not being able to copy info from context window is annoying
