### ISSUE TITLE
Firefox MacOS Keeps my Mac User password on bitwarden unlock input.

### ISSUE THREAD

**Issue by Lzok** [bitwarden/browser#1583]
## Describe the Bug
When my bitwarden extension is locked, it automatically has my user machine password pre-filled in its input. It doesn't matter if I have just logged on to the pc or if I have been logging in for a while and just locked the extension.

### Way 1
1. Log in onto your computer (MacOS in my case)
2. Open Firefox
3. Click on the Bitwarden extension icon
4. You will see the master password input pre-filled with your machine user password

### Way 1
1. Lock the Bitwarden extension after been navigating for a while.
2. Click on the Bitwarden extension icon to unlock.
3. You will see the master password input pre-filled with your machine user password.

## Expected Result
I expect the master password input to be empty **always**.

## Actual Result
The master password input is pre-filled with my user machine password.

## Screenshots or Videos
![imagen](https://user-images.githubusercontent.com/45211582/106297896-fe0b3900-6231-11eb-8c79-2b97566dc115.png)

## Environment

- Operating system: Mac OS Mojave v10.14.6
- Browser: Firefox Developer Editition 85.0b5 (64-bit)

Let me know if you need any additional information please.

Thanks!

**Comment by kspearrin** [comment]
Maybe try turning off the built-in password manager for your browser? Sounds like it is auto filling stuff for you.

**Comment by Lzok** [comment]
@kspearrin Damn, your are right. That was the problem.

Firefox: Go to `about:logins` and delete from that list the Bitwarden extension.

Thanks!
