### ISSUE TITLE
UI freezes unless mouse is moved over the Item Information section

### ISSUE THREAD

**Issue by fxlemire** [bitwarden/browser#1584]
## Describe the Bug

When editing `URLs` or `NOTES`, the extension UI is frozen and gets only refreshed if the mouse is moved over the `ITEM INFORMATION` section.

## Steps To Reproduce

1. Open the extension
2. View or create an item
3. Try to edit a URL or add some notes

## Expected Result

Interacting (e.g. edit, select) with `URLs` or `NOTES` should not freeze the UI and behave the same way as when editing a `username` for example.

## Actual Result

UI is not refreshing.

## Screenshots or Videos

![lag](https://user-images.githubusercontent.com/4381789/106315675-9e189080-6239-11eb-8875-75814ad294da.gif)

## Environment

- Operating system: Mac OS Big Sur and Catalina
- Browser: Edge 88.0.705.56
- Build Version: Official Build

**Comment by clayadams5226** [comment]
Hey @fxlemire, Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by bgallagher** [comment]
I'm experiencing the same on Chrome on macOS Catalina.

**Comment by jmeridth** [comment]
Duplicate of #1209. But why was this closed?

**Comment by mlennox22** [comment]
I'm having the same problem with the BitWarden extension on Chrome and macOS.  Parts of the UI don't update, which is extremely frustrating when entering your master password, generating passwords or updating vault items.  It's basically unusable.

https://user-images.githubusercontent.com/29780066/114472594-81e18a00-9bc0-11eb-8a0c-4232d2efdb91.mov

**Comment by mlennox22** [comment]
I believe that I have solved the issue.  In Chrome, you need to enable hardware acceleration.

Settings -> Appearance -> Advanced -> Enable Hardware Acceleration when Available.

As soon as I did this, the chrome extension window is responsive and I can see myself type in fields and the password generator is super responsive.

**Comment by mausv** [comment]
Also having the same issue.

**Comment by mausv** [comment]
This seems to be the open ticket tracking this issue.

https://github.com/bitwarden/browser/issues/1854

**Comment by eliykat** [comment]
Just confirming that this is a known issue, and @mausv is correct that we're tracking it in #1854. It's an issue that is specific to Chrome on external monitors. The workarounds at the moment are:
* popout the extension into a new window
* move the window onto a non-external monitor

Please read through #1854 for more information and continue the conversation over there.
