### ISSUE TITLE
No longer ask to save login after create an account

### ISSUE THREAD

**Issue by MGMehdi** [bitwarden/browser#1586]
It ask when I login but not when I create an account (tested with 9gag since it worked before)

**Comment by SergeantConfused** [comment]
Hi there,

Please uninstall the extension, reboot your machine, reinstall the extension, and test this again. If you encounter the same behaviour, please get in touch with us here: https://bitwarden.com/contact/ and let us know what browser version and extension version you're using, and we'll proceed.


Thank you in advance,

**Comment by MGMehdi** [comment]
I tested it with three browsers (Edge Chromium, Mozilla and Brave). The problem has appeared since the extension asks for authorizations

**Comment by MGMehdi** [comment]
I use Bitwarden_rs and before I used a domain name to be able to use the extension. Is it possible that the problem comes from the fact that now I have my DNS server and I used openssl to create a certificate and a certificate authority?

**Comment by eliykat** [comment]
Hi @MGMehdi, I wouldn't think that this is affected by DNS/CA changes.

This is a known issue that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this post: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
