### ISSUE TITLE
Vivaldi - Extension does not lock at the set Vault Timeout.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1588]
## Describe the Bug
The Bitwarden browser extension does not lock at the set Vault Timeout.

## Steps To Reproduce
1. Install the Vivaldi browser.
2. Install the Bitwarden browser extension.
3. Log into your vault through the extension.
4. Set the Vault Timeout to 1 minute.
5. Wait 2 minutes.

## Expected Result
For the extension to be locked.

## Actual Result
The extension is unlocked.

## Screenshots or Videos
N/A.

## Environment
- Operating system: Windows 10 Pro 19042.746.
- Browser: Vivaldi 3.6.2165.34
- Build Version: 1.48.1.

## Additional Context
N/A.

**Comment by clayadams5226** [comment]
Looks like this is a known issue and outside of Bitwarden's control. 
https://github.com/bitwarden/browser/issues/1037
