### ISSUE TITLE
Biometrics not working on Mac OS + Big Sur + Vivaldi

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/browser#1590]
## Describe the Bug

Received error Message "Please confirm using biometrics in the Bitwarden Desktop application to enable biometrics for browser."

## Steps To Reproduce

Start Desktop app
Browser integration checked
Enable the option on Browser Extension

Note: Tried unchecked and checked the "Browser integration" option on desktop app

## Expected Result

Able to use Biometrics since Vivaldi is Chromium based

## Actual Result

Received error Message "Please confirm using biometrics in the Bitwarden Desktop application to enable biometrics for browser."

## Environment

- Operating system: MacOS Big Sur 11.1  (Intel)
- Browser: Vivaldi browser (3.6.2165.34 (Stable channel) (x86_64))
- Desktop app version: 1.24.5(513)
- extension version :1.48.1

**Comment by aimuz** [comment]
There's a temporary solution,
```
mkdir -p ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts
```
Find native messaging hosts in the Vivaldi directory

```
ln -s ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/com.8bit.bitwarden.json com.8bit.bitwarden.json
```


If you want permanent repair, please refer to：

https://github.com/bitwarden/desktop/pull/757
