### ISSUE TITLE
Cannot add or edit an entry

### ISSUE THREAD

**Issue by winterqt** [bitwarden/browser#1592]
## Describe the Bug

I cannot add or edit an entry within my vault.

## Steps To Reproduce

Either try to add a new entry, or edit an existing one.

## Expected Result

For the entry to be successfully added or saved.

## Actual Result

The progress indicator in the top right corner spins infinitely.

## Environment

- Operating system: NixOS
- Browser: Firefox 85.0
- Build Version (go to "Settings" → "About" in the app): 1.48.1

## Additional Context

This only started within the last few minutes, as of writing. Previously, the extension worked fine.

**Comment by cscharf** [comment]
Hi @winterqt , can you pleas try now or are you still having the same issue?

**Comment by winterqt** [comment]
@cscharf Seems to be better, but intermittently failing still. Is that expected, should this be considered fixed?

**Comment by cscharf** [comment]
We're monitoring. Looks like one of the servers in the cluster was failing but stuck (not being deprecated).

**Comment by cscharf** [comment]
Should be back to full normal operations, please let us know if you experience any other issues. Thanks!
