### ISSUE TITLE
New Safari browser window takes long time to display

### ISSUE THREAD

**Issue by crieke** [bitwarden/browser#1594]
## Describe the Bug
When a new window is opened on current Mac Safari, it takes quite a long time to open. When Bitwarden extension is disabled in Safari preferences, it opens nearly instantly.

## Steps To Reproduce

Should be easy to reproduce. Just open a new window in safari, when Bitwarden extension is enabled.

## Expected Result

The window should open nearly instantly.

## Actual Result

A new window in safari takes more than 2 seconds to open.
## Screenshots or Videos

Here is a screen recording of the behaviour:
https://dl.rie.ke/index.php/s/sJkZ2F8CCNj8x8L

I checked the duration of a new window by the  screen recording to compare the times more accurately:
<img width="1037" alt="NewWindow_Safari_Bitwarden_LoadingTimes" src="https://user-images.githubusercontent.com/1208602/106665757-01daea80-65a7-11eb-984f-876833e80f4a.png">

## Environment

- Mac OS Big Sur: 11.2 (20D64)
- Browser: Safari: 14.0.3 (16610.4.3.1.4)
- Bitwarden App: 1.24.6 (515)
- Safari Bitwarden Extension: 1.48.1

**Comment by possibleworlds** [comment]
Can reproduce exactly, approx 2 second delay every new window.

**Comment by silvetti** [comment]
Reported the same a while ago.
#1492 

Was closed as a known issue that will be solved once Bitwarden ports the extension to the new framework.

@cscharf Can you provide us any ETA for this new extension?

**Comment by crieke** [comment]
Thanks @silvetti. I just read it. 
(Sorry, I did not look in the closed issues, as I assumed that current issues, won't get closed until fixed)

**Comment by cscharf** [comment]
ETA for new extension is early March; needs a lot of testing but it was merged into master and we're testing it now: https://github.com/bitwarden/browser/pull/1531

**Comment by godly-devotion** [comment]
I've removed my Bitwarden copy that I downloaded from the website and switched over to the Mac App Store version (which included the new safari web extension). Since then, I can say that opening a new window takes much less time than it did before.

Thank you for your hard work!

**Comment by gravesit** [comment]
I confirm this also resolved the slowness for me. Thanks!

**Comment by crieke** [comment]
Issue is solved. Thanks!

**Comment by silvetti** [comment]
Resolved.
