### ISSUE TITLE
Auto-fill requires a refresh to get to work via context menu

### ISSUE THREAD

**Issue by winterqt** [bitwarden/browser#1596]
## Describe the Bug

When attempting to auto-fill credentials via the context menu, it sometimes requires a refresh to make it work. Auto-filling via the extension window works fine every time.

## Steps To Reproduce

1. Go to a site where auto-fill works
2. Attempt to auto-fill via the context menu

## Expected Result

For auto-fill to work first try

## Actual Result

It requires a refresh of the page.

## Environment

- Operating system: NixOS
- Browser: Firefox 85.0
- Build Version (go to "Settings" → "About" in the app): 1.48.1

**Comment by SZemanek** [comment]
I can confirm, I'm seeing this same issue on 
Linux Mint 20.1  +  Firefox 89.0  +  Bitwarden Version: 1.50.0
This is a fresh Linux Mint install, and I also tried a clean Firefox profile to make sure it wasn't another extension interfering.  

Observed behavior:
Goto a website, goto login:
Right Click ->  Fill:  Does nothing.
Clicking the Bitwarden icon on toolbar -> clicking the correct saved login:  Works perfectly.

**Comment by SZemanek** [comment]
Actually, I noticed something.  It seems to work fine if I right-click a password field, but it doesn't work fine if I click a username field.   This is annoying on login screens that are ask for the username and password on separate screens.    It would nice to have the option of "fill username" and "fill password" for those websites that don't quite auto-fill right.
