### ISSUE TITLE
AES Nonce generation is done with paranoia level 0

### ISSUE THREAD

**Issue by doomrobo** [bitwarden/browser#16]
[Here](https://github.com/bitwarden/browser/blob/master/src/services/cryptoService.js#L116) is the offending line. Paranoia level 0 disables all entropy requirements for the PRNG. [This](https://github.com/bitwiseshiftleft/sjcl/blob/00bd42dae9ebc3a28708db2053ffa2e88f99ad1e/core/random.js#L111) is the warning from SJCL when paranoia=0. I don't think it'd be a good idea to use a predictable value as an AES nonce.

**Comment by kspearrin** [comment]
Thanks for this report. I wonder why I am not getting the exception?

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/commit/1426719406942dad75bd1d164db0b78d6b3f3bf1
