### ISSUE TITLE
Autofill is not working properly on Hello bank! Italy

### ISSUE THREAD

**Issue by xates** [bitwarden/browser#1600]
## Describe the Bug

Autofill is not working as expected on Hello bank! Italy login page.

## Steps To Reproduce

1. Go to 'https://banking.hellobank.it/it/login/'
2. Try to autofill the form

## Expected Result

The form is filled out

## Actual Result

Only the password is filled out

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/17145424/107008202-cbae8e00-6793-11eb-9c11-afd98319c788.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 88
- Build Version 1.48.1

## Additional Context

HTML code of the form:

```html
<form id="command" name="websealForm" action="/SEEA-pa01/devServer/seeaserver" method="post" autocomplete="off" data-bitwarden-watching="1">
  <div>
    <div class="titolo-area-riservata-div">
      <strong>AREA RISERVATA</strong>
    </div>
    <div class="credenziali-area-riservata-div">
      <table class="login-table">
        <tbody>
          <tr>
            <td class="row-cells-area">
              <div class="cont-div">
                <div class="sub-cont-div">
                  <p class="credenziali-font-par sub-cont-par">
                    <strong> <label for="real_username">ID CLIENTE</label></strong>
                  </p>
                  <input type="number" class="type-text-new" name="real_username" id="_real_username" tabindex="1" maxlength="10" value="">
                  <p class=" credenziali-font-par sub-cont-par">
                    <strong> <label for="real_password">PIN</label></strong>
                  </p>
                  <input class="type-text-new" type="password" name="real_password" id="_real_password" tabindex="2" maxlength="6">
                  <div class="line" id="taxCodeField" style="display: none">
                    <p id="taxCodeField" class="credenziali-font-par sub-cont-par">
                      <strong> <label for="real_taxCode">CODICE FISCALE</label></strong>
                    </p>
                    <input type="text" class="type-text-new uppercase" name="real_taxCode" id="_real_taxCode" tabindex="3" maxlength="16">
                  </div>
                </div>
              </div>
            </td>
            <td class="row-cells-area">
              <div class="cont-div">
                <table class="inner-login-table">
                  <tbody>
                    <tr>
                      <td class="login-td">
                        <div class="absolute-bottom-margin32 login-div">
                          <button class="login-button" type="submit" name="Invia" value=""></button>
                        </div>
                      </td>
                      <td id="recupera-id" class="login-td">
                        <div class="absolute-bottom-margin32 left-padding-6 bottom-padding-10 " style="bottom: 0px;">
                          <a class="link-testuali" href="/pubblica/RecuperoNumeroCliente">Recupera ID cliente &gt;</a>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <input type="hidden" name="AUTH" id="_AUTH">
  <input type="hidden" name="pan" id="_pan" value="[omitted]">
  <input type="hidden" id="device_print" name="pm_fp" value="[omitted]">
  <input type="hidden" id="dom_print" name="dp">
  <input type="hidden" id="events_print" name="ep">
</form>
```

**Comment by cho-m** [comment]
It looks like fields with `type="number"` are not considered usernames by autofill code:
https://github.com/bitwarden/browser/blob/5d51fd3fbd2da79801c67be3d57855d8cf72cabb/src/services/autofill.service.ts#L982

Since I am just another user, you will probably need to wait on someone familiar with autofill logic to comment on impact of adding `type="number"` as a valid username.
Or maybe someone can improve the autofiller to fuzzy search on username values since the field has `name="real_username" id="_real_username"`


As a workaround, you can try adding a "Custom Field" (See: https://bitwarden.com/help/article/custom-fields/) of type `Text` with a Name of `_real_username` (or `real_username` since the former matches `id="_real_username"` while the latter matches `name="real_username"`) along with a Value of whatever your ID CLIENTE is.

**Comment by xates** [comment]
Thank you @cho-m for the workaround! 😊

The fixes you have described both seem very valid to me, with the first appearing easier to implement, though as you stated someone qualified will have to evaluate potential side effects.

**Comment by Pulsar** [comment]
Hello @xates,
please also check the #1621 issue.

**Comment by eliykat** [comment]
This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
