### ISSUE TITLE
Bitwarden does not recognize user name field on new USAA Login

### ISSUE THREAD

**Issue by jtmullen** [bitwarden/browser#1606]
## Describe the Bug
USAA has rolled out a new "login-experience" and Bit Warden does not seem to be able to recognize the username field any more. It does recognize the password field (on the next page after username). They seem to name the field memberId instead of username which is why Bitwarden does not recognize it.  

## Steps To Reproduce

1. Go to 'https://www.usaa.com/my/logon'
2. Click on Bitwarden extension and select USAA logon credentials to autofill

## Expected Result
Bitwarden puts the username into the form

## Actual Result
I get the error: `Unable to autofill the selected item`

## Screenshots or Videos

New logon form: 
![image](https://user-images.githubusercontent.com/30645732/107315325-13ffd180-6a5c-11eb-8937-eed495ef6c80.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 85.0.1
- Build Version: : 1.48.1

## Additional Context

The error seems to be because USAA calls the field "memberId" instead of username. If I edit the page via the inspector to rename the field to "username" it works as expected. 

Form HTML on load: 

```html
<input name="memberId" aria-invalid="false" autocomplete="off" id="usaa-form-v5-7-5-input-p0tmti5mm2vb" type="text" aria-describedby="usaa-form-v5-7-5-input-p0tmti5mm2vb-errorMessage undefined" value="" tabindex="7" autocorrect="false">
```

If I change the field name to username as follows Bitwarden auto fills as expected: 
```html
<input name="username" aria-invalid="false" autocomplete="off" id="usaa-form-v5-7-5-input-p0tmti5mm2vb" type="text" aria-describedby="usaa-form-v5-7-5-input-p0tmti5mm2vb-errorMessage undefined" value="" tabindex="7" autocorrect="false" >
```

**Comment by sso-bitwarden** [comment]
Hi @jtmullen 

There is a workaround for this. You can add a custom field and it will auto-fill it. 
https://bitwarden.com/help/article/custom-fields/

**Comment by jtmullen** [comment]
Hi, I did find that and will do so. Just wasn't sure if this is something was supposed to work out of the box or not. Thanks!

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue.
