### ISSUE TITLE
Firefox Extension ignores vault timeout when installed in private mode

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/browser#1607]
## Describe the Bug

The session on Firefox extension stays logged in and unlocked even when setting "Vault Timeout"  on  "Browser Restart"  & action to "Lock"

## Steps To Reproduce

As you know, Firefox allows users to set private browsing mode as default by using the toggle in Option/privacy&security/history. It is also possible to use the configuration editor and change "browser.privatebrowsing.autostart" from false to true.

I discovered that if the Bitwarden addon is installed *after* enabling private mode as default using the configuration editor, closing the browser does not end the extension session, it just suspends it, even if the Vault is set to timeout and lock on browser restart. What's worse is that the extension is still unlock even after restarting the PC.

## Expected Result

Bitwarden Firefox Extension follow the vault timeout and action values

## Actual Result

Extension stays logged in and unlock

## Environment

- Operating system: Windows 10
- Browser: 85.0.2
- Build Version: 1.48.1
-

**Comment by PlankCipher** [comment]
I had the same issue here. I don't  know if this is what fixed it, but I opened `Settings` and clicked `Lock now`. And it has been working fine since then.
