### ISSUE TITLE
🔰 Feature request:  add an option for PIN to :  View/Copy password !

### ISSUE THREAD

**Issue by dnknn** [bitwarden/browser#1611]
1. Chrome86 extension  (🔰Bitwarden V1.48.1)
2. ⚙Bitwarden  option: Restart the browser to lock the password library with PIN

Then I found that any "local person" can **View**/**Copy** password directly .....

Why does it not support secondary verification to want to view/copy password?

I checked all the options and [bitwarden.com/help](https://bitwarden.com/help/), but at the end I didn’t find an option for this feature.

![212_15035056](https://user-images.githubusercontent.com/10995302/107887431-0c02ce80-6f41-11eb-8278-4bac8b4ef83e.png)

At this point, LastPass did a perfect job.

- ## ❥ **Expected/fixed behavior:** 
　　　1. 🔓 During this period, the password library and features are not locked, and after the browser is closed, Bitwarden will be locked and unlocked with a PIN. (Achieved)
　　　2. 🔐 But anyone who wants view/copy password needs to verify the PIN or master password any time ! (Not currently implemented)

- ### 🎀 One sentence summary: 
　　　Even if Bitwarden is not locked(🔓), but the action of manually obtaining the password (View/Copy) must be locked(🔐) at all times!
　　　That is to say, want to View/Copy password , you must enter a PIN to unlock it before it can be successfully operated.

- ## 💡 **Implementation plan:**
　　　Changed by default,  or Add an ON/OFF option: ⬜/☑
　　　Optional:  within 5/10/15 minutes without this restriction

**Comment by tgreer-bw** [comment]
You can set the timeout period for the Browser extension to be instant, if you'd like:

https://bitwarden.com/help/article/vault-timeout/

**Comment by dnknn** [comment]
> You can set the timeout period for the Browser extension to be instant, if you'd like:

No....no...  I said so in detail in the issue, don't you understand?

Of course I know how to set an instant timeout, but I must never do that.

1. Absolutely not instant (so I set it to not lock 🔰Bitwarden until restart the browser), otherwise, it is very inconvenient, so it is better not to use the password tool.

2. Based on the above conditions, I made this `local security` proposal !

@tgreer-bw  Can you understand now?

**Comment by tgreer-bw** [comment]
Yes, understood.

We have a forum for feature requests. I believe what you're asking for can be accomplished with this request, which is on our backlog.

https://community.bitwarden.com/t/require-master-password-re-prompt-for-some-items/41

Please add your vote/feedback on the forum so we can capture it.

**Comment by dnknn** [comment]
> I believe what you're asking for can be accomplished with this request, which is on our backlog.

Thank you very much, but I can’t see the same feature as my requirement? Should I post a request?

sorry for my English. ...
<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/107890348-80df0400-6f53-11eb-882d-07515d8a22e1.png)

</details>
