### ISSUE TITLE
Changing Chrome extension "This Can Read and Change Site Data"-permission breaks the extension

### ISSUE THREAD

**Issue by jonls** [bitwarden/browser#1612]
## Describe the Bug

In Chrome, the BitWarden extension requires full access to all pages by default, however it's possible to right-click the extension and select "This Can Read and Change Site Data" -> "When You Click the Extension". When this is enabled, the extension can only read and change the page after the extension button is clicked. This is a setting I would prefer to use since I don't want the BitWarden extension to have full page access to all websites that I visit unconditionally.

When I try this, the BitWarden extension seems to break in strange ways:

- If I'm logged in already when I change the permission to "When You Click the Extension", it seems to work at first but the extension will no longer sync. If I try to force sync, it fails with a generic "Syncing failed" error message.
- If I log out while the permission is set to "When You Click the Extension", I can no longer log in again. I get a generic "Failed to fetch" error on login.

My suspicion is that this is caused by the change to "When You Click the Extension" because the issue goes away immediately when I switch back to giving the extension access to all pages unconditionally.

## Steps To Reproduce

1. Right-click BitWarden extension in Chrome. Select "This Can Read and Change Site Data" -> "When You Click the Extension".
2. In the extension popup, go to settings -> sync -> sync vault now. It fails with "Syncing failed."
3. In the extension popup, go to settings -> log out. Logging in again fails with "Failed to fetch".

## Expected Result

I expected to be able to give the BitWarden extension access to specific pages where I want passwords filled without granting unconditional access to every page I visit.

I was able to do this with LastPass and it basically works. Ideally BitWarden would use the activeTab permission in Chrome instead of what it's currently doing: https://developer.chrome.com/docs/extensions/mv2/manifest/activeTab/

## Actual Result

Extension appears to break in strange ways with error messages that don't indicate what the issue is.

## Environment

- Operating system: MacOS Catalina
- Browser: Chrome 88.0.4324.150
- Build Version (go to "Settings" → "About" in the app): 1.48.1

**Comment by lwouis** [comment]
I can confirm this issue. Here are the console logs of me logging in the extension, with either `When You Click the Extension` or `On all sites` selected:

Setting | Console logs
-|-
`When You Click the Extension` | ![image](https://user-images.githubusercontent.com/106195/109113080-fed6b280-777e-11eb-84e6-69e86aaa2075.png)
`On all sites` | ![image](https://user-images.githubusercontent.com/106195/109113075-fda58580-777e-11eb-8111-2529e214ba8a.png)

It seems like it's a CORS issue

**Comment by pauliusg** [comment]
I also have similar CORS issue after day or two of Chrome extension usage. If I log out, I am not able to login because of the same CORS issue. I have uninstall extension and install it again. Then it again works for day or two... Very frustrating.

**Comment by lwouis** [comment]
@pauliusg yeah I witnessed that as well. When you switch to `When You Click the Extension`, it doesn't log you out or throw an error. It *looks* like everything is fine. Then when you try to add a company to the list, or any other task that requires authentication, it throws the `Failed to fetch` error.

It made it tricky to notice that the cause was switching to `When You Click the Extension`, but now it's clear.

**Comment by zEdS15B3GCwq** [comment]
I'm also having issues with the 'on click' setting in Chrome and Edge. To be fair to BitWarden, Lastpass is also having some problems if set to the same.

I managed to unnecessarily create another thread about this, which I've closed now, so I'm moving my report here instead.

> In Chrome and Edge (and probably other chromium-based browsers), settings "site access" of an extension to "on click" prevents access to a site's data until the extension's icon is clicked on. This setting creates several issues in BitWarden:
> 
> 1. (tested in Chrome) Adding a site to the vault manually fails with "fetch error". E.g. I tried to add one of my gmail accounts to the vault, filled in the URI, name, user and pass fields, pressed save -> fail.
> 2. (tested in Edge) Could not perform the initial login to my existing account after installing the extension.
> 3. (tested in Chrome) auto-popup to remember new login details doesn't appear, e.g. after logging into a gmail account not stored in the vault.
> 
> OS Win10 x64 20H2
> Browser: Edge 89.0.774.68 / Chrome 89.0.4389.114
> BitWarden v1.49.1
> 
> Basically, the "on click" setting breaks some things. While in Chrome I am able to log into my account and use existing logins, new logins are not added automatically (in at least a couple of sites) and manually adding them doesn't work either. In Edge, first login kept failing until I changed "on click" to "allow on all sites" (wording might be slightly different). Naturally, I did click on the extension's icon to enable it. Changing back to "allow on all sites" fixes all the issues. In Edge, setting to "allow on all sites", logging in to initialise the account, then setting back to "on click" allowed further logins without problems.
> 
> This setting also breaks stuff in LastPass, so all might not be BitWarden's fault. Auto-adding a new login to gmail didn't evoke an automatic pop-up to save in LastPass either, until the "on click" setting was changed.
> 
> I'm aware that I might be mixing slightly different issues in Edge and Chrome, sorry for the sloppiness, but because these browsers share the same engine, I'm going on the assumption that the site access setting works the same way in both. If some of these issues cannot be confirmed, I can do more thorough testing.

**Comment by kendratodd** [comment]
Additional reports: https://github.com/bitwarden/browser/issues/1747

**Comment by jonls** [comment]
It doesn't look like this issue was fixed but I recently found a way to work around the issue that seems to work okay. The key is to add the API endpoints to the list of allowed sites:

1) Go to Manage Extension -> Site access. Set allow extension to read: "Specific sites".
2) Add `https://api.bitwarden.com/*` and `https://identity.bitwarden.com/*` to the list of sites.

For other sites, this appears to work exactly the same as when access is set to "on click". You click the extension and click reload to activate the extension for that session only.

**Comment by GraemeARobinson** [comment]
> It doesn't look like this issue was fixed but I recently found a way to work around the issue that seems to work okay. The key is to add the API endpoints to the list of allowed sites:
> 
> 1. Go to Manage Extension -> Site access. Set allow extension to read: "Specific sites".
> 2. Add `https://api.bitwarden.com/*` and `https://identity.bitwarden.com/*` to the list of sites.
> 
> For other sites, this appears to work exactly the same as when access is set to "on click". You click the extension and click reload to activate the extension for that session only.

This is a great solution, thanks @jonls

**Comment by SchizoDuckie** [comment]
A three year old problem is the root cause of a problem in 2025. 

I should NOT have to go to Github issues to see why the chrome extension is not syncing with a vague error message.
