### ISSUE TITLE
password is shown in 2fa "token field" in clear text

### ISSUE THREAD

**Issue by hteibler** [bitwarden/browser#1616]
when you have a site with 2fa where, after the username and password is entered, you get a new page to import the token, the password is filled in, in clear text !!

## Describe the Bug

password is shown in clear text in 2fa token field

## Steps To Reproduce

eg: if you have an account at:  support.fortinet.com 

## Expected Result

don't fill anything

**Comment by Greenderella** [comment]
Ho @hteibler,

Have you tried generating a custom field for the password? That may prevent the autofill issue:  https://bitwarden.com/help/article/custom-fields/

**Comment by hteibler** [comment]
> Ho @hteibler,
> 
> Have you tried generating a custom field for the password? That may prevent the autofill issue: https://bitwarden.com/help/article/custom-fields/

thanks, this helps.
