### ISSUE TITLE
Keyboard shortcut doesn't work for community.bitwarden.com on Chrome macOS

### ISSUE THREAD

**Issue by skube** [bitwarden/browser#1624]
## Describe the Bug

Keyboard shortcut _doesn't_ work for https://community.bitwarden.com using Google **Chrome macOS**

## Steps To Reproduce

1.  Using Chrome on macOS go to https://community.bitwarden.com (with BitWarden extension installed)
2. Click on **Log In**
3. Tap <kbd>⌘</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd>

## Expected Result

Form to be auto-filled

## Actual Result

Nothing happens. Form doesn't fill-in with credentials.
(works in Firefox though! 🦊 )

## Environment

- Operating system: **Mac OS Catalina**
- Browser: **Chrome**
- Build Version: **Version 88.0.4324.182 (Official Build) (x86_64)**

**Comment by tgreer-bw** [comment]
Make sure Chrome has the shortcuts enabled

[chrome://extensions/shortcuts](chrome://extensions/shortcuts)

<img width="685" alt="Screen Shot" src="https://user-images.githubusercontent.com/61418192/108604093-b16ed580-7379-11eb-87f7-1e12e3fbbbac.png">

**Comment by skube** [comment]
Yep! It was indeed this.  I guess some other app had wiped this out for me.
