### ISSUE TITLE
Bar offering to save credentials is blinking/refreshing constantly

### ISSUE THREAD

**Issue by dave7280** [bitwarden/browser#1628]
## Describe the Bug

Add new credential bar is blinking:

https://streamable.com/apzoo1

## Steps To Reproduce

Go to any page and try to add credential so bitwarden detects a new one and offers to save it.

## Expected Result

Upper header should not blink

## Actual Result

Upper header is blinking like page it's refreshing

## Screenshots or Videos

https://streamable.com/apzoo1

## Environment

- Operating system: Windows 10
- Browser:  Chrome 88.0.4324.150 
- Build Version: 1.48.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. We're aware of it and it's being tracked in issue #1243, so I'll close this as a duplicate.
