### ISSUE TITLE
Unlock with PIN not working in both Firefox and Chrome

### ISSUE THREAD

**Issue by ezxpro** [bitwarden/browser#1631]
## Describe the Bug
If I configure the extension to unlock the vault with a PIN, it doesn't work at all afterwards.

## Steps To Reproduce

1.Unlock the vault (either in Chrome or Firefox)
2. Go to settings and check the "Unlock with PIN" checkbox
3.  Set a PIN
4. Lock the vault and try unlocking it again

## Expected Result

It should ask me for the pin I set.

## Actual Result

It asks for the master password again.

## Environment

- OS: Windows 10 x64 20H2 v2 (build 19042.804)
- Browser: Google Chrome 88.0.4324.182 z64 (official installer) / Firefox 85.0.2 x64 (official installer)

- 1.48.1 (curiously, while checking the extension build version, it asked for a PIN in Firefox. Usually it doesn't, though. On Chrome, it always asks for the master password, although the "Unlock with PIN" checkbox is checked.

**Comment by sioban** [comment]
I have the same problem since 20H2.

Firefox 88.0.1 (64-bit)
Chrome 90.0.4430.212 (Official Build) (32-bit)
BW 1.49.1

Each time I close the browser it asks for Master Code and not the PIN Code.

Vault Timeout is on "On Browser Restart"
Vault Timeout action is "Lock"
"Unlock with PIN" checkbox is checked

**Comment by ezxpro** [comment]
@sioban seems we're forgotten. The problem persists and no one ever replied

**Comment by tgreer-bw** [comment]
When you enable PIN, and you always want a PIN for unlock, make sure you uncheck "lock with Master Password on browser restart" or it will prompt for your password instead 👍 

<img width="346" alt="Screen Shot 2021-05-23 at 8 50 19 AM" src="https://user-images.githubusercontent.com/61418192/119261122-e7ec0480-bba3-11eb-9074-bc0eacfd0f15.png">

**Comment by sioban** [comment]
Thanks @tgreer-bw, it solved my issue.
I was confused because when I've set it up first it was working fine and I did uncheck this checkbox.
Then it suddenly stopped working.
To make it work again I had to remove, add the Pin and be sure to uncheck this box.

**Comment by ezxpro** [comment]
I didn't realize this checkbox existed until @tgreer-bw mentioned it. I'm closing this issue, since this is not a bug.
