### ISSUE TITLE
"Should Bitwarden remember this password for you?" notification blinking...

### ISSUE THREAD

**Issue by stevemarksd** [bitwarden/browser#1634]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by Greenderella** [comment]
Thanks for reporting this issue. We're aware of it, and it's being tracked in issue [#1243](https://github.com/bitwarden/browser/issues/1243), so this one will be closed as a duplicate.
