### ISSUE TITLE
Switching app from Firefox while in the 2FA step resets the login process to the first step

### ISSUE THREAD

**Issue by jacopocolo** [bitwarden/browser#1636]
## Describe the Bug

After entering email and master password in the Firefox extension, if I have 2FA enabled I (probably) need to switch to app to my authenticator to retrieve my 2FA code. Doing so causes the extension to close the popup AND reset the login process to the beginning, asking me again to enter the master password — potentially making my 2FA code expire.

## Steps To Reproduce

1. Log out from the bitwarden extension
2. Press Log In
3. Enter Master password
4. Unfocus the app by switching to another app
5. The extension is reset to the first step

## Expected Result

I expected the extension to stay in the step where I need to enter my 2FA code

## Actual Result

The extension is reset to the first step

## Screenshots or Videos

N/A

## Environment

- Operating system: Mac OS 10.15.7
- Browser: Firefox 85.0.2
- Build Version: 1.48.1

**Comment by cscharf** [comment]
Did you see an option to pop out the window so it persists open? - see: https://github.com/bitwarden/browser/issues/795

**Comment by jacopocolo** [comment]
Totally didn't but I'll say that even if I had seen it, I don't think I would have pressed it. My expectation is that if I'm in the middle of a flow, the extension will remember where I am since it's expecting more data from me.

**Comment by cscharf** [comment]
I completely understand where you're coming from, however the browser controls 100% of this, we can't force the browser to keep the pop-up open, and upon close it kills off context forcing you to start over again, which is why we have the pop-out prompt. Our Customer Success team/QA team will take a look to ensure that's working as expected.

**Comment by kapitainsky** [comment]
There is no option to pop out the window in Firefox when extensions asks for either password or 2FA - so logging into bitwarden extension (with 2FA enabled) requires quick fingers:) - copy 2FA code from e.g. Authy then attempt to login. It is not deal-breaker but a bit annoying.

**Comment by cscharf** [comment]
Thanks, we'll take a look at it!

**Comment by kapitainsky** [comment]
the latest Firefox 86 login to bitwarden extension:

<img width="370" alt="Screenshot 2021-02-26 at 19 38 47" src="https://user-images.githubusercontent.com/15635386/109347197-ada3ed00-786a-11eb-96d9-b50efa5a5977.png">

<img width="370" alt="Screenshot 2021-02-26 at 19 39 36" src="https://user-images.githubusercontent.com/15635386/109347211-b399ce00-786a-11eb-85bc-a2d41583e8a3.png">

<img width="370" alt="Screenshot 2021-02-26 at 19 40 14" src="https://user-images.githubusercontent.com/15635386/109347216-b72d5500-786a-11eb-8a3a-457c5bf41a12.png">

pop out is only available at this stage:

<img width="370" alt="Screenshot 2021-02-26 at 19 41 10" src="https://user-images.githubusercontent.com/15635386/109347226-b98faf00-786a-11eb-82e6-40ff4c93eca7.png">

**Comment by kapitainsky** [comment]
Not fixed in 1.49.0 yet

**Comment by gtimbo** [comment]
> I completely understand where you're coming from, however the browser controls 100% of this, we can't force the browser to keep the pop-up open, and upon close it kills off context forcing you to start over again, which is why we have the pop-out prompt. Our Customer Success team/QA team will take a look to ensure that's working as expected.

I would simply like to add that LastPass somehow deals with this situation as expected: i.e. attempt to login, asks for auth code, switch apps, popup closes, copy auth code, re-open popup and it's still asking for auth code, as one would expect.

So I'm not sure how they're managing it, but it's a _much_ better experience than Bitwarden is at the moment.

**Comment by lmackley** [comment]
I hate to revive a closed issue but this problem still exists.
