### ISSUE TITLE
Biometrics doesn't work with Chrome

### ISSUE THREAD

**Issue by ostasevych** [bitwarden/browser#1638]
## Describe the Bug

After installing Chrome extension I am trying to enable biometrics. However, it doesn't work.

## Steps To Reproduce

1. Open Desktop client
2. Login to Desktop client
3. Call chrome extension
4. Try to enable biometrics
5. The alert window about the need to react in the desktop client is appearing, but nothing appearing in the desktop client. 

## Expected Result

Enabled biometric function

## Actual Result

Cannot enable biometric function.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5199030/109074486-7f0a0300-7700-11eb-9e8b-3059fd115c15.png)
![image](https://user-images.githubusercontent.com/5199030/109075043-44549a80-7701-11eb-80fc-f618661b899c.png)

## Environment

- Operating system: Windows 10
- Browser: Google Chrome 88
- Build Version: 1.24.6

## Additional Context

Fingerprint unlocking works well in the desktop client.

**Comment by traed** [comment]
I'm having the same issue on MacOS (Catalina). I don't see any setting called "allow access to file URLs" in the extension settings, though.

**Comment by tgreer-bw** [comment]
Visit chrome://extensions/ and view Bitwarden details:

![Uploading Screen Shot 2021-02-25 at 1.57.38 PM.png…]()

**Comment by traed** [comment]
Ah, found it, thanks. It didn't work with only Allow access to file URLs enabled, but when I also enabled Allow in incognito it started working.

**Comment by ostasevych** [comment]
> Can you check to make sure "allow access to file URLs" is checked in your chrome extension settings? It resolves this issue on Chrome + macOS.

Yes! Now it works fine. I think, this should be added directly to the chrome extension with some pop-up window or even the request to set up this flag on by default.
