### ISSUE TITLE
Secure Note Master Password Re-Entry

### ISSUE THREAD

**Issue by PeterKW** [bitwarden/browser#1640]
Is there yet or a known upcoming feature to allow the user to set a setting requiring that the master password must be re-entered each time a particular 'Secure Notes' contents are requested to be viewed?

**Comment by eliykat** [comment]
This feature has been requested over at the [community forums](https://community.bitwarden.com/t/require-master-password-re-prompt-for-some-items/41). There is some discussion on that thread you can check out or contribute to.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

This issue will now be closed. Thanks!
