### ISSUE TITLE
Copy username/password does not work when autofill doesn't work

### ISSUE THREAD

**Issue by geostant** [bitwarden/browser#1646]
## Describe the Bug
It seems that when autofill doesn't work you can't copy the username / password
manually as clipboard stay empty or with previous value from another unrelated copy.

## Steps To Reproduce
Browse to a known website that doesn't work with autofill (in my case https://portal.ampr.org/login.php)
try to copy save credentials for manual pasting.

4. Click on '...'

## Expected Result
Copy the values

## Actual Result
Doesn't copy

## Environment

- Operating system: MacOS BigSur
- Browser: Firefox 85.0.2
- Build Version (go to "Settings" → "About" in the app): Build 1.48.1

**Comment by cheako** [comment]
Comment from a new user.  You don't describe how "try to copy save credentials" is performed.  Also, the past tense of save is saved.  I'm using the background context menu, for example.

**Comment by geostant** [comment]
> Comment from a new user. You don't describe how "try to copy save credentials" is performed. Also, the past tense of save is saved. I'm using the background context menu, for example.

The past tense for save is saved, loved it.
