### ISSUE TITLE
Firefox - The browser extenstion does not lock if the Vault Timeout Action was set previously to Never.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1647]
## Describe the Bug
Changing the Vault Timeout Action from Never to On Browser Restart does not cause the browser extension to lock after closing the browser.

## Steps To Reproduce
1. Open Firefox
2. Set the Vault Timeout Action in the Bitwarden browser extension to Never.
3. Close Firefox.
4. Open Firefox.
5. Set the Vault Timeout Action in the Bitwarden browser extension to On Browser Restart.
6. Close Firefox.
7. Open Firefox.

## Expected Result
For the extension to be locked.

## Actual Result
The extension is unlocked.

## Screenshots or Videos
N/A.

## Environment
- Operating system: Windows 10 Pro 19041.746.
- Browser: Firefox 86.
- Build Version: 1.48.1.

## Additional Context
If you click on Lock Now once after you change the Vault Timeout Acton to On Browser Restart, Bitwarden will start locking the extension after closing the browser.

**Comment by eliykat** [comment]
This may be fixed in the upcoming release by other changes to `secureStorageService`.

**Comment by eliykat** [comment]
QA has confirmed that this appears to be resolved after the changes to `secureStorageService`. This bug will be resolved in the next release.
