### ISSUE TITLE
Chrome popup always shows scrollbar

### ISSUE THREAD

**Issue by MHebes** [bitwarden/browser#1650]
## Describe the Bug

In chrome, an unnecessary scrollbar appears in the popup. Scrolling down exposes extra space underneath the tabs.

## Steps To Reproduce

1. Install bitwarden for chrome from the chrome store: https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en
2. Log in
3. Click on the extension button
4. Examine scrollbar; scroll down.

## Expected Result

If the content fits in the popup, no scrollbar is shown.

## Actual Result

A scrollbar is shown despite the content fitting the popup

## Screenshots or Videos

Observe the scrollbar and extra space:

![image](https://user-images.githubusercontent.com/8306042/109542573-356c4000-7a93-11eb-8fd2-f898a232c723.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
- Build Version: 1.48.1

**Comment by skizztle** [comment]
Just as an FYI I also see this in Edge.

Windows 10
Edge Version 88.0.705.81

**Comment by eliykat** [comment]
The fix for this is being reverted (see #1714), so I am reopening the issue.
I am treating #1008 and #1030 as duplicates and keeping them closed.

**Comment by patrickhlauke** [comment]
is this issue resolved now? fwiw I can't replicate it (not in chrome nor in edge) with the latest 1.54.0 release

**Comment by Cabus1982** [comment]
The same thing happened to me and it was because I had the zoom level set to 110% in the browser

**Comment by Jackpison** [comment]
> The same thing happened to me and it was because I had the zoom level set to 110% in the browser

Is there a way to keep websites zooms and extensions zoomed to different levels?
due to resolution of my screen I had to use 125% but it messes up my extension

**Comment by Cabus1982** [comment]
> > The same thing happened to me and it was because I had the zoom level set to 110% in the browser
> 
> Is there a way to keep websites zooms and extensions zoomed to different levels? due to resolution of my screen I had to use 125% but it messes up my extension


This [extension](https://chromewebstore.google.com/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd) did the job for me. 

Remember in the extension settings, select “**Use the built-in browser zoom**”, to keep the correct proportion of websites, but you will see that in no case affects the windows of the extensions 💪
