### ISSUE TITLE
Extension cannot fill username on AWS login page

### ISSUE THREAD

**Issue by bigon** [bitwarden/browser#1652]
## Describe the Bug

When going to the AWS login page, the extension in firefox cannot autofill the username (but it can fill the password)

## Steps To Reproduce

1. Go to `https://<account-name>.awsapps.com/start`
2. You are redirected to `https://eu-west-1.signin.aws/platform/login?workflowStateHandle=<UUID>`
3. Try to autofill the username

## Expected Result

You can autofill the username

## Actual Result

Getting an error that I should copy/paste the username instead

## Environment

- Operating system: Debian unstable
- Browser: Firefox 86
- Build Version 1.48.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
