### ISSUE TITLE
Card details fill not working the first time on ČSOB payment gate (https://platebnibrana.csob.cz/)

### ISSUE THREAD

**Issue by JanPokorny** [bitwarden/browser#1653]
## Describe the Bug

When paying through the gate https://platebnibrana.csob.cz/, first click on the saved card in Bitwarden only fills the card number. It needs to be clicked again to fill the expiration and CVC.

## Steps To Reproduce

1. Go to pay something using the ČSOB payment gate (eg. try to order something on https://deliverybrno.forkys.eu/)
2. Once the gate appears, click your saved card details in the Bitwarden browser extension

## Expected Result

Everything is filled

## Actual Result

Only the card number has been filled, not expiration or CVC.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/4580066/109639408-6d38bd80-7b4f-11eb-974a-be3a2e7ab928.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 86.0
- Build Version: 1.48.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
