### ISSUE TITLE
Username and password fill does not work on edpuzzle.com

### ISSUE THREAD

**Issue by neoxk** [bitwarden/browser#1657]
## Steps To Reproduce

1. Go to https://edpuzzle.com/
2. Click on 'Log in'
3. Click on 'bitwarden browser extension'
4. Click on the edpuzzle login auto-fill

## Expected Result

When going to bitwarden browser extension and clicking the edpuzzle login information it should fill in the credentials.

## Actual Result

When trying to log into edpuzzle with auto-fill option the extension tries filling in the credentials but they get deleted.

## Environment

- Operating system: Windows 10
- Browser: Google Chrome 
- Build Version: 88.0.4324.190

**Comment by cscharf** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
