### ISSUE TITLE
FIDO U2F Security Key 2FA not presented as option in Edge extension

### ISSUE THREAD

**Issue by KylePreuss** [bitwarden/browser#1658]
## Describe the Bug

The browser extension does not show FIDO U2F Security Key as a 2FA option. In Chrome, I receive the typical pop-up with Windows 10 integration about touching the button on my security key.

## Steps To Reproduce
1. Close and reopen latest Edge browser
2. Click on BitWarden icon in browser toolbar
3. Enter username and password.

## Expected Result
The popup about touching my security key.

## Actual Result
A popup for using my backup 2FA option (TOTP code via authenticator app)

## Environment
- Operating system: Windows 10
- Browser: Edge v88.0.705.81
- Build Version: 1.48.1

## Additional Context
I believe this PR for BitWarden/web is relevant:
https://github.com/bitwarden/web/pull/804

Since Edge is now Chromium based, the browser extension should now work with U2F hardware keys, yes?

**Comment by eliykat** [comment]
Thanks @KylePreuss, I must have missed this when I updated the web client.
