### ISSUE TITLE
Biometric unlocking funciton cannot be enabled.

### ISSUE THREAD

**Issue by nico-zck** [bitwarden/browser#1661]
## Describe the Bug
Biometrics funciton (windows hello) not work properly with extension and desktop.
`Biometric Unlocking` cannot be enabled even I have enabled `Browser Integration` in the desktop app's setting. 

The extension still warning: "Browser integration is not enabled in the Bitwarden Desktop application. Please enable it in the settings within the desktop application."

## Environment
- Operating system: Windows 10 20H2
- Browser: Edge 89.0.774.45
- Build Version (go to "Settings" → "About" in the app): 1.48.1
- Desktop version: 1.24.6

**Comment by couchninja** [comment]
I have the same experience, on a different environment:

Operating system: MacOS 10.15.3
Browser: Chrome 88.0.4324.192
Plugin Version: 1.48.1
Desktop version: 1.24.6

**Comment by nico-zck** [comment]
> I have the same experience, on a different environment:
> 
> (By the way, I love this project! A big thanks to everyone who works on it!!)
> 
> Operating system: MacOS 10.15.3
> Browser: Chrome 88.0.4324.192
> Plugin Version: 1.48.1
> Desktop version: 1.24.6

I suggest you shoud also try the next version Chrome.

**Comment by couchninja** [comment]
I updated chrome to the latest stable version (89.0.4389.82) but still have the same issue.

**Comment by nico-zck** [comment]
> I updated chrome to the latest stable version (89.0.4389.82) but still have the same issue.

Sorry to hear that, you can try to reset/restart/reinstall the desktop app. 

If the problem persists, you can reopen this issue.
