### ISSUE TITLE
Bitwarden Vault Timeout doesn't work on Firefox if Bitwarden is open in sidebar

### ISSUE THREAD

**Issue by Dan884** [bitwarden/browser#1665]
## Describe the Bug
The Vault Timeout doesn't work in Firefox if Bitwarden is open in the Sidebar. It works if the sidebar is not open. This has been not working for years but I just discovered today that it was only not working when the Sidebar was open.

## Steps To Reproduce

1. Open a Sidebar in Firefox and select Bitwarden to be displayed in that Sidebar. 
2. Set the Vault Timeout to 1 minute. 
3. Wait 2 minutes. The Vault will not lock.

## Expected Result
The vault should lock.

## Actual Result
The vault doesn't lock.

## Environment
MacOS Big Sur version 11.2.2
Firefox 86.0
Bitwarden 1.48.1
But this has been not working for years on previous versions of MacOS, Firefox and Bitwarden.

**Comment by eliykat** [comment]
This is currently the expected behaviour, as the sidebar and pop-out window are considered "active" states that won't start the lockout timer running. There's some discussion here about changing this behaviour: https://github.com/bitwarden/browser/issues/1334. I'll close this thread as a duplicate.
