### ISSUE TITLE
Emoji passwords incorrectly displayed

### ISSUE THREAD

**Issue by edent** [bitwarden/browser#1682]
## Describe the Bug

My password is a string of Emoji `✅🐎🔋📎`

It displays as `✅������`
![Screenshot from 2021-03-11 08-16-12](https://user-images.githubusercontent.com/837136/110757395-3fd0cb80-8243-11eb-922a-dee4a43c5f7e.png)

When copied, the password is correct - it is only the display that is corrupted.  All other fields display emoji correctly.

## Steps To Reproduce

1. Create a new entry
2. Paste or type emoji into the password field
3. Save the password
4. View the password.

## Expected Result

The password should display the emoji - not a series of Unicode replacement characters.

## Screenshots or Videos

This also occurs on the Android and Desktop app (Linux).

### Android App

![Emoji Test](https://user-images.githubusercontent.com/837136/110757200-0730f200-8243-11eb-8101-02227daef289.jpg)

See https://github.com/bitwarden/mobile/issues/1310

### Desktop Linux
![Screenshot from 2021-03-11 08-14-14](https://user-images.githubusercontent.com/837136/110757397-40696200-8243-11eb-8d8c-ddcb3f4b7acc.png)

### Web Vault
This displays the password properly
![Screenshot from 2021-03-11 08-26-23](https://user-images.githubusercontent.com/837136/110757650-8b837500-8243-11eb-8269-1c91dda76407.png)

## Environment

- Operating system: Linux
- Build Version (go to "Settings" → "About" in the app): Version: 1.48.1
- Is this a Beta release? N

## Additional Context

I know that having [an emoji password is a stupid idea](https://apple.stackexchange.com/questions/202143/i-included-emoji-in-my-password-and-now-i-cant-log-in-to-my-account-on-yosemite)!

**Comment by eliykat** [comment]
Fixed by https://github.com/bitwarden/jslib/pull/354

**Comment by edent** [comment]
Thanks gang - tested and working perfectly!
