### ISSUE TITLE
Firefox extension stuck loading

### ISSUE THREAD

**Issue by shlomster** [bitwarden/browser#1699]
Firefox 72.0.1
MacOS Mojave 10.14.6

The bitwarden toolbar button no longer shows the locked symbol. When I click on it, it displays a loading circle perpetually. The sidebar also loads indefinitely.

I don't know of any changes I made that caused this to happen.

I've tried restarting firefox and my computer. I also tried removing and adding the extension back. I obviously can't login or out on the extension since it's stuck loading. The bitwarden application functions normally.

I just want the browser extension to work, so I can use autofill, etc. Very sad :( Help please!

**Comment by naipilk** [comment]
Firefox 68.6.0esr (64-bit)
Win 7, SP1
Bitwarden 1.49.0

Same issue. Think this is an issue with the latest update (1.49.0).
Fixed it by uninstalling the Bitwarden extension, and installing the previous version (1.48.1).
Older versions can be found in the link below.
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

**Comment by Anjoland** [comment]
Win 10
FF 53
Same issue as above, when you click on the BW toolbar button it opens up and there is just a circle spinning.  Going back to 1.48.1 works fine.

**Comment by MattRyder** [comment]
Loading the sidebar's page: `/popup/index.html?uilocation=sidebar`, the console reports a TypeError, reproduced below:

```
TypeError: page.bitwardenMain is undefined services.module.ts:63:8
    getBgService services.module.ts:63
    691 services.module.ts:69
    Webpack 4
```

Ubuntu / Firefox 75 / Bitwarden 1.49.0. Downgrading to 1.48.1 corrects the error.

**Comment by shlomster** [comment]
Yes, I was also on Bitwarden 1.49.0.

Thank you thank you!!

**Comment by ScottWitte** [comment]
Same problem.
Windows 10 OS Build 19042.867
FF 72.0.2 
Bitwarden 1.49.0
Problem started with this version

Uninstalled/reinstalled the extension. Restarted FF, Restarted the system, Cleared cache. Nothing helped.

**Comment by eliykat** [comment]
I've had a quick look at this and have found the problem. Upgrading to Firefox 77 or later should fix this issue, but I've raised it with the team for a proper fix, as I don't believe we intended to break backwards compatibility.

**Comment by MattRyder** [comment]
> I've had a quick look at this and have found the problem. Upgrading to Firefox 77 or later should fix this issue, but I've raised it with the team for a proper fix, as I don't believe we intended to break backwards compatibility.

Thank you, it's appreciated.

I'm on Firefox 75 ESR as it's the last supported version before the megabar update. Obviously, you can't support every version of Firefox forever, so I'll see whether I can't hack the megabar out with user-defined CSS on the latest GA release.

**Comment by Sjeiti** [comment]
I don't think Firefox itself is the issue. I've run into it multiple times; currently on Firefox 100.0b9 (Bw ext v1.57.0)
