### ISSUE TITLE
Biometric unlock option not available in Firefox extension

### ISSUE THREAD

**Issue by CrabAss** [bitwarden/browser#1703]
## Describe the Bug

Having the latest version of Bitwarden Windows client (1.25.0) installed and "browser extension integration" option enabled, I cannot find the option to unlock my vault using Windows Hello on my Bitwarden Firefox extension (1.49.0). I've also installed Bitwarden extension on Microsoft Edge (Chromium-based), and biometric unlocking works smoothly on Edge. 

I tried to re-install Bitwarden Firefox extension from addons.mozilla.org, But the problem remains the same.

## Steps To Reproduce

(I am using Bitwarden in Chinese language, so the option names below may differ)
1. Install the latest version of Bitwarden Windows client (1.25.0), login and enable "browser extension integration" option and "authentication using browser integration" option. 
2. Install Bitwarden Firefox extension from addons.mozilla.org, and login.
3. Switch to "Settings" tab
4. Failed to find the option to unlock the vault using Windows Hello.

## Expected Result

(The screenshot below is taken from Microsoft Edge extension; the UI is in Simplified Chinese)
![图片](https://user-images.githubusercontent.com/13916997/111112328-f235c500-859a-11eb-8f29-5bafc67c2bef.png)

## Actual Result

(The screenshot below is taken from Firefox extension; the UI is in Simplified Chinese)
![图片](https://user-images.githubusercontent.com/13916997/111112434-20b3a000-859b-11eb-91ec-91d5bf83af42.png)

## Screenshots or Videos

Provided in previous sections.

## Environment

- Operating system: Windows 10 Pro 20H2
- Browser: Firefox 86.0.1
- Build Version: 1.49.0

**Comment by cscharf** [comment]
Hi @CrabAss , thanks for the report, however Biometrics for the Firefox extension relies on Firefox 87 which is currently only in Beta. You can either upgrade to the Beta program of Firefox OR wait for v87 to be released, then the option should be available.

**Comment by CrabAss** [comment]
Thanks for your info! I will wait for the release of Firefox v87.

**Comment by kapitainsky** [comment]
I am on Firefox 87 (now release candidate)/macOS 11.2.3 and it does not work. I tested with Chrome no problem but with Firefox option in browser add-on is not available.  I have latest desktop BW app from Apple App Store, and latest Firefox extension. It did not work with previous 87 betas neither.

**Comment by cscharf** [comment]
> I would suggest this issue should be reopened.

I agree.

**Comment by kapitainsky** [comment]
not sure if it helps but here you some additional info - these are permissions requested by add-on:

<img width="659" alt="Screenshot 2021-03-16 at 15 28 41" src="https://user-images.githubusercontent.com/15635386/111335640-74da8500-866c-11eb-9aad-0760c87b7fbe.png">

Reading BW help it mentions "communicate with cooperating native applications" permission required. I agreed to accept whatever add-on was asking during installation.

**Comment by Hinton** [comment]
Unfortunately the Firefox extension is still missing support for the browser biometrics. Support was added to master by #1668, and is currently being tested.

After the testing wraps up we will release an update which we are aiming to have done before 87.0 is released.

**Comment by kapitainsky** [comment]
Great! Thank you for clarifying - all is in the process then.

However would make sense to update 1.94.0 release notes. Firefox 87 will be probably released next week and I would expect many people to complain about it.

<img width="1143" alt="Screenshot 2021-03-16 at 19 40 54" src="https://user-images.githubusercontent.com/15635386/111370143-c5170e80-868f-11eb-9877-6ff3c4b57961.png">

**Comment by cscharf** [comment]
> However would make sense to update 1.94.0 release notes. Firefox 87 will be probably released next week and I would expect many people to complain about it.

I will do that, this was my dumb, sorry for the confusion. 🤦🏻

**Comment by kapitainsky** [comment]
Also it requires update on Mozilla add-ons page - https://addons.mozilla.org/en-GB/android/addon/bitwarden-password-manager/versions/

<img width="1263" alt="Screenshot 2021-03-17 at 07 59 31" src="https://user-images.githubusercontent.com/15635386/111433909-cb8ca100-86f6-11eb-8ea0-c6a1d8ad7edc.png">

**Comment by kapitainsky** [comment]
I see that now all potential confusion is cleared. Thank you very much for fantastic tool and responsiveness for even small issues. 
And it is getting better with every new release!

**Comment by CrabAss** [comment]
Hi @kapitainsky , since the biometric support for Firefox v87 has been shipped with the Bitwarden extension v1.49.1, could you have a try to see whether it's working properly? If yes, I think this issue can be closed. Thanks!

**Comment by kapitainsky** [comment]
of course! as soon as it lands in Mozilla add-ons updates - I have just checked it is still 1.49.0. Will check a bit later

**Comment by cscharf** [comment]
Yes, it's been submitted, just waiting for approval.

**Comment by kapitainsky** [comment]
I've tried installing from github releases but seems Firefox now checks signatures

<img width="430" alt="Screenshot 2021-03-17 at 20 46 38" src="https://user-images.githubusercontent.com/15635386/111536266-efd19780-8761-11eb-93cd-39756650f509.png">

If already on the way to Mozilla store I will wait then. 

And test as soon as available.

**Comment by kapitainsky** [comment]
Firefox 87 release candidate on macOS 11.2.3

After updating add-on from Mozilla store to the latest version:

<img width="349" alt="Screenshot 2021-03-18 at 16 23 55" src="https://user-images.githubusercontent.com/15635386/111661467-f2d29380-8806-11eb-962e-095d986d4994.png">

biometric option is available:

<img width="381" alt="Screenshot 2021-03-18 at 16 20 17" src="https://user-images.githubusercontent.com/15635386/111661540-0251dc80-8807-11eb-91e5-3e638ee2823b.png">

After selecting it Firefox asks for additional permission:

<img width="418" alt="Screenshot 2021-03-18 at 16 21 44" src="https://user-images.githubusercontent.com/15635386/111661608-13025280-8807-11eb-930f-21cbd25ac005.png">

Now locked add-on vault can be unlocked using macOS fingerprint functionality.

Thank you for fixing it! I consider this issue to be resolved.

**Comment by cscharf** [comment]
@CrabAss , let me know if you agree and are able to see this working and we can close out this issue. Thanks!

**Comment by CrabAss** [comment]
Yes, I'm glad to see it working! So I'm going to close this issue. Thank you!

**Comment by yureiita** [comment]
I downloaded firefox 87 from this link https://ftp.mozilla.org/pub/firefox/releases/87.0/mac/en-GB/Firefox%2087.0.dmg and it does not work. I tested on brave browser and it does work. When I try to enable unlock with biometrics on firefox the following dialog box appears:

<img width="356" alt="Screenshot 2021-03-22 at 11 21 33 PM" src="https://user-images.githubusercontent.com/26035759/112015591-eaf85380-8b66-11eb-9e20-4c7ab98f0b90.png">

- Operating system: macOS 11.2.3
- Browser: Firefox 87.0
- Build version: 1.49.1 (Firefox add-on), 1.25.0 (Desktop downloaded from mac App Store)

**Comment by kapitainsky** [comment]
First you have to open desktop application and in settings enable browser integration.

**Comment by yureiita** [comment]
It is enabled in the desktop application, I have tested in brave browser and it does work in brave browser

**Comment by kapitainsky** [comment]
hmm. I have exactly the same configuration and it works without any issues. I would try to disable integration, restart firefox and try again maybe.

No idea why it does not work for you.

**Comment by kapitainsky** [comment]
One more thing I can think about is Firefox version - check which version you are running. Because Firefox 87 is still on beta channel and can be installed alongside release version (86 at the moment). So maybe you have both versions. And biometrics don't work with 86.

**Comment by yureiita** [comment]
> hmm. I have exactly the same configuration and it works without any issues. I would try to disable integration, restart firefox and try again maybe.
> 
> No idea why it does not work for you.

I have tried that and it still doesn't work. I have tried reinstalling the add on and also the desktop app but still doesn't work.

> One more thing I can think about is Firefox version - check which version you are running. Because Firefox 87 is still on beta channel and can be installed alongside release version (86 at the moment). So maybe you have both versions. And biometrics don't work with 86.

Yes, it is still on beta and will be released tomorrow but the download link for it is alread live here https://ftp.mozilla.org/pub/firefox/releases/87.0/mac/en-GB/Firefox%2087.0.dmg. I have checked the Firefox version and it is Firefox 87.0.

<img width="779" alt="Screenshot 2021-03-23 at 1 02 27 AM" src="https://user-images.githubusercontent.com/26035759/112028716-71b32d80-8b73-11eb-8503-c9dc0a3a12b9.png">

**Comment by kapitainsky** [comment]
you are right, clearly it is another cause.

**Comment by kapitainsky** [comment]
@CrabAss does it work for you?

**Comment by CrabAss** [comment]
> 
> 
> @CrabAss does it work for you?

Yes, it's working fine for me in the following environment:

- Windows 10 Pro 20H2 x64
- Firefox v87.0 (stable) x64
- Bitwarden Firefox extension v1.49.1
- Bitwarden Windows client v1.25.1

@yureiita Could you please open another issue with the problem you've encountered? Since the original problem ("option not available") in this issue has been solved, and I think you're raising a new problem ("biometric unlock not working").

**Comment by CrabAss** [comment]
@yureiita btw, the latest version for Bitwarden macOS client is v1.25.1. You may download it from [Bitwarden official website](https://bitwarden.com/download/), and have a try with this latest one.

**Comment by kapitainsky** [comment]
> @yureiita btw, the latest version for Bitwarden macOS client is v1.25.1. You may download it from [Bitwarden official website](https://bitwarden.com/download/), and have a try with this latest one.

It might work with Firefox but wont with Safari - on mac it is better to install BW desktop from Apple Store

https://bitwarden.com/help/article/install-safari-app-extension/

**Comment by kapitainsky** [comment]
@yureiita do you have required add-on permission enabled as below?

<img width="930" alt="Screenshot 2021-03-22 at 18 22 20" src="https://user-images.githubusercontent.com/15635386/112039254-c0dd6c00-8b3b-11eb-9b1b-4386edd55c2f.png">

**Comment by Hinton** [comment]
@yureiita Would you mind checking if you have the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json`, and also paste the content of it. Also just to verify you are using the Bitwarden addon from addons.mozilla.com?

**Comment by yureiita** [comment]
> @yureiita btw, the latest version for Bitwarden macOS client is v1.25.1. You may download it from [Bitwarden official website](https://bitwarden.com/download/), and have a try with this latest one.

According to this link https://bitwarden.com/help/article/biometrics/ only the desktop app from the App Store support biometrics.

> @yureiita do you have required add-on permission enabled as below?
> 
> <img alt="Screenshot 2021-03-22 at 18 22 20" width="930" src="https://user-images.githubusercontent.com/15635386/112039254-c0dd6c00-8b3b-11eb-9b1b-4386edd55c2f.png">

Yes it is enabled.

> @yureiita Would you mind checking if you have the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json`, and also paste the content of it. Just to verify, you are using the Bitwarden addon from addons.mozilla.com?

I tried to check the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json` but there is no folder named `nativeMessagingHosts` inside the directory `~/Library/Application Support/Mozilla/`. Only a folder named `Extensions` is inside it but it is also empty.

**Comment by yureiita** [comment]
> @yureiita Could you please open another issue with the problem you've encountered? Since the original problem ("option not available") in this issue has been solved, and I think you're raising a new problem ("biometric unlock not working").

I have created a new issue here #1731

**Comment by CrabAss** [comment]
Thanks! Then I am going to close this issue.
