### ISSUE TITLE
"Errors have occurred" when creating new Chrome extension login

### ISSUE THREAD

**Issue by minmarble** [bitwarden/browser#171]
When attempting to make a new login for a site using the Chrome browser extension, this error pops up:

![extension_error](https://cloud.githubusercontent.com/assets/29119539/26675027/53dc5d62-4690-11e7-90a8-0b6299633058.png)

You're able to make a login using the web vault, but it doesn't seem to sync with the extension itself and will not show the new login you've made in the extension. 

I have disabled all other Chrome extensions except Bitwarden itself to test for conflicts and it still seems to be a problem.

**Comment by kspearrin** [comment]
@minmarble It appears that you are having issues connecting to the bitwarden server for some reason. Can you try doing a manual sync and see if you get an error with that as well?

**Comment by minmarble** [comment]
@kspearrin After adding a login to the web vault, then going to Settings > Manage section > Sync in the extension, it still does not seem to update, even after the "Syncing complete" prompt. 

It also doesn't seem to update to the latest time of the sync when it's done manually... it says the last sync was done more than 30 minutes ago, which is when I opened Chrome (and started my computer) for the first time today.

**Comment by kspearrin** [comment]
@minmarble Are you familiar with how to view the dev tools on the extension to see if there are any network errors occurring during the sync?

You can swing into our dev chat room if you like and I can walk you through it: https://gitter.im/bitwarden/Lobby

**Comment by jjdelc** [comment]
Seeing same error here (Firefox Nightly + Ubuntu), the text is a bit different. It says "An **unexpected** error has occurred" when trying to manually add a new site.

**Comment by kspearrin** [comment]
@jjdelc log out and back in app to fix it for now.

**Comment by jjdelc** [comment]
Logged out, now I see the same red error trying to log in.

**Comment by kspearrin** [comment]
Can you email me at https://bitwarden.com/contact so I can get more info.

**Comment by jjdelc** [comment]
Done, I also joined the gitter channel

**Comment by jjdelc** [comment]
@minmarble do you have uMatrix installed? I just tried disabling the extension completly and it worked.

The problem was that even when I "switched off" the filtering, I still had trouble. And there were no sources pointing to anything bitwarden in the uMatrix menu to indicate that some requests were being blocked. The only way to get around was completly disable the extension.

**Comment by Primokorn** [comment]
@jjdelc no need to disable uMatrix. There are a few connections to allow in the _behind-the-scene_ mode. Here is what I allowed on my end: 

> behind-the-scene api.bitwarden.com xhr allow
behind-the-scene identity.bitwarden.com xhr allow
behind-the-scene maillink.bitwarden.com other allow
behind-the-scene vault.bitwarden.com other allow

**Comment by jjdelc** [comment]
@Primokorn Thanks! I was trying with `matrix-off` and didn't have any luck.

I found though that disabling and enabling it also resolved the issue, a re-enabled uMatrix even without any rules added also allowed bitwarden to work.

**Comment by LivingWithHippos** [comment]
I fixed this with the rule "* bitwarden.com * allow" into the my-rules section

**Comment by Primokorn** [comment]
@jjdelc Disabling uMatrix is not a good idea since you allow (even temporarily) all the traffic.
@LivingWithHippos yes... if you want to allow everything from bitwarden including analytics.

**Comment by bb010g** [comment]
For whatever reason, when I checked the log and tried to enable it from there, it was marked as coming from `youtube.com` despite trying to create the password in a different tab. I ended up using @Primokorn's exceptions with a `*` filter instead of `behind-the-scene`.

**Comment by SylwesterZarebski** [comment]
With Firefox 54.0.1 `behind-the-scene` do not work for me also. I have to use `*` instead, like bb010g do.

**Comment by kspearrin** [comment]
This should be resolved now.

**Comment by 569258yin** [comment]
I also had the same problem。 On the server I built myself, I can log in using the browser web page, but the login error using the plug-in
After I uninstalled the plug-in, I can log in normally for the first time. When I close Chrome and reopen it and need to log in again, I get an error when I log in.

chrome: 98.0.4758.80
bitwarden plugin: 1.55.0
