### ISSUE TITLE
Bitwarden extension 1.49.0 on Firefox ESR 68.1.0 not working

### ISSUE THREAD

**Issue by ari-vaha-erkkila** [bitwarden/browser#1711]
## Describe the Bug

Bitwarden browser extension (1.49.0) no longer works with Firefox ESR 68.1.0 (on Windows 10). Previous version did work just fine.
## Steps To Reproduce

1. Install Firefox 68.1.0 ESR
2. Install Bitwarden extension
3. Try to open it (click on the icon on toolbar)

## Expected Result

A working Bitwarden window.

## Actual Result
A blank popup shows up, with spinning icon spinning (for ever I suppose)

## Environment

- Operating system: Windows 10
- Browser: Firefox ESR 68.1.0
- Build Version: extension 1.49.0

## Additional Context

A browser update is not possible as it is controlled by corporate policy.

**Comment by eliykat** [comment]
Thanks @ari-vaha-erkkila, we've already received and have actioned this issue - see #1699. A patch to fix this is on its way. I'll close this issue as a duplicate.
