### ISSUE TITLE
Incorrect rendering when hardware acceleration is disabled

### ISSUE THREAD

**Issue by kiseleon** [bitwarden/browser#1712]
## Describe the Bug

On Mac OS Chrome, the extension menu is not displaying correctly when hardware acceleration is disabled. 

## Steps To Reproduce

1. In Chrome on Mac OS
2. Go to settings, disable `Use hardware acceleration when available`
3. Relaunch
4. Click on the extension in the toolbar
5. Notice that the top of the displayed menu is visually blocked off.

## Expected Result

I would expect to be able to see the menu like normal so I can click on a site password.

## Actual Result

The top bit (almost enough to cover the entire first password box) is just blocked off, sometimes after 5 seconds or so it will fix itself, but not always. This area will also display the wrong thing as I browse through menu options.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/4294484/111337606-d7fff380-863b-11eb-9171-f2b1c10c59c2.png)

## Environment

- Operating system: Mac OS Catalina 10.15.7
- Browser: Chrome 89.0.4389.82 (Official Build) (x86_64)
- Build Version (go to "Settings" → "About" in the app): 1.49.0

## Additional Context

I cannot enable hardware acceleration as there are rendering issues for everything with that ([see here for more info on that](https://forums.macrumors.com/threads/strange-chrome-browser-graphical-glitches.2229803/)). Until that is fixed I need to have hardware acceleration disabled.

**Comment by asenmitrev** [comment]
Experiencing the same problem on Chrome on MacOS 11.2.3. For some reason, issue appears only when chrome is opened on an external monitor.
