### ISSUE TITLE
After update Bitwarden AddOn not function

### ISSUE THREAD

**Issue by yozgatliahmed** [bitwarden/browser#1715]
## Steps To Reproduce

 Make update from Bitwarden AddOn

## Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/17163918/111433777-01358800-86ff-11eb-9b35-5aa517be4090.png)

## Environment

- Operating system: Windows 10]
- Browser: [e.g. Firefox Quantum 68.2.0esr (32-Bit)]

**Comment by eliykat** [comment]
Hi @yozgatliahmed,  we've already received and have actioned this issue - see #1699. A patch to fix this is on its way. I'll close this issue as a duplicate.
