### ISSUE TITLE
Unable to fill AWS accountId after migration from LastPass

### ISSUE THREAD

**Issue by MatteoGioioso** [bitwarden/browser#1716]
## Describe the Bug

Hello, I have just migrated from LastPass and I am exploring Bitwarden.
Seems like that after I have migrated from LastPass the aws AccountId does not get populated.  I heavily use AWS so for me is crucial that this works.
I remember that this was working out of the box when saving the password directly on AWS, however does not seems to work when importing it.

Is it a known issue?

## Steps To Reproduce

1. Export password from last pass (should include the AWS login with URL, username and password)
2. Import to bitwarden
3. Disable LastPass extension to avoid conflict
4. Go to aws console login
5. Try to fill the credentials
6. Only username and password get populated

## Expected Result

Account id should get populated

## Environment

- Operating system: Ubuntu 18.08
- Browser: Chrome 89.0.4389.90 (Official Build) (64-bit)
- Build Version Version: 1.49.0

**Comment by kapitainsky** [comment]
Have you tried to add account id as custom field:

<img width="375" alt="Screenshot 2021-03-17 at 15 01 23" src="https://user-images.githubusercontent.com/15635386/111489125-c6007c80-8731-11eb-976c-9804495bfb38.png">

https://bitwarden.com/help/article/custom-fields/

**Comment by eliykat** [comment]
Thanks for reporting this issue. This isn't related to the LastPass migration - unfortunately some sites just don't play nicely with our autofill scripts. (I have seen AWS mentioned before.) Using custom fields is a good workaround.

This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by MatteoGioioso** [comment]
For everyone coming here I actually found out that in order to your accountId to be filled you have to bookmark the right url and save it in Bitwarden under `website`, in the case of AWS you need to url pattern

```
https://<ACCOUNT_ID>.signin.aws.amazon.com/console
``` 

I hope this help
