### ISSUE TITLE
Firefox - Vault showing locked but context menu allowing access to vault.

### ISSUE THREAD

**Issue by jquilli** [bitwarden/browser#1717]
## Describe the Bug

Firefox 86.0.1 (64-bit) with settings to "Never Remember History"
Bitwarden extension settings are set to logout vault anytime on browser close
After closing the browser, or restarting the PC, and opening up Firefox again I am able to navigate to Google's sign in page and use the right click context menu to fill in my credentials while the vault icon is showing locked. I've tried to access the vault by clicking on the icon but it shows to log in.

## Steps To Reproduce

Set Firefox browser to "Never Remember History"
Set Bitwarden settings to log out of vault on browser close
Navigate to a website that requires access to the vault and use the right click context menu to fill in the credentials.

## Expected Result

Expected results are the context menu and vault to both be locked and access to be blocked from filling in credentials.

## Actual Result

The vault is still accessible by using the context menu although the vault is still locked when accessing it via the browser extension icon.

## Screenshots or Videos

![Capture](https://user-images.githubusercontent.com/22248924/111642278-51cae500-87d4-11eb-8249-b76c725ca8bd.JPG)

## Environment

- Operating system: Windows 10 Pro 20H2 19042.868
- Browser: Firefox 86.0.1 (64-bit)
- Build Version: 1.49.0

**Comment by kapitainsky** [comment]
Maybe it is something Windows specific. 

Using Firefox on macOS it acts as expected:

<img width="773" alt="Screenshot 2021-03-18 at 16 36 31" src="https://user-images.githubusercontent.com/15635386/111663272-8d7fa200-8808-11eb-9e19-95de0caa6946.png">

I know it does not help your specific setup but maybe let developers to look into right code place (might be just Windows specific).

**Comment by kapitainsky** [comment]
@jquilli  - on your screenshot BW icon shows small badge with number 4 - which could imply that your vault is not locked. 

Maybe it is problem with auto locking - try to lock it manually and see if it is the case.

**Comment by jquilli** [comment]
@kapitainsky my mistake on not checking with a different OS. It could very well be a Windows issue.

When I click on the vault icon that shows the number 4 it opens up asking me to log in and the 4 clears.

**Comment by kapitainsky** [comment]
strange thing is that it should not depend on OS - Windows or macOS we use Firefox and install the same add-on.

For me when vault is locked icon shows small red dot.

<img width="134" alt="Screenshot 2021-03-18 at 18 03 58" src="https://user-images.githubusercontent.com/15635386/111674832-56af8900-8814-11eb-9dd3-5684f7bf7db1.png">

**Comment by kapitainsky** [comment]
maybe issue is with private mode you are using...

**Comment by jquilli** [comment]
Preferences are "Never Remember History" with these settings to clear every time on browser close.
I also noticed it does not lock either when BW settings are set to lock on browser close.

![Capture](https://user-images.githubusercontent.com/22248924/111677326-7e432900-87f5-11eb-8fa8-7898a722acdd.JPG)

**Comment by kapitainsky** [comment]
Just checked on my Windows virtual machine - the same. It does not respect "lock on browser restart". History settings do not matter - the same for private or normal mode.

On macOS it behaves different - when I restart Firefox with lock on restart selected it locks BW vault. So definitely there is an issue with this add-on on Windows version of Firefox.

**Comment by kapitainsky** [comment]
one more thing you can try - update add-on to 1.49.1 - it has been release just few hours ago

**Comment by jquilli** [comment]
Updated to 1.49.1 and still the same issue.

I noticed that even after I click on the BW extension icon the 4 remains. I can even hit the log in button which shows my email and when I right click to access the context menu it will still display my credentials.
