### ISSUE TITLE
Bitwarden Firefox plugin suggests 2 logins for 2 URLs (pointing to the same IP)

### ISSUE THREAD

**Issue by freekvh** [bitwarden/browser#1721]
## Describe the Bug

The Bitwarden plugin suggests I have two logins for a website (and 2 for another), but there should be only one per website/URL. It could be because both websites run on the same (my own) server and it is because both sites have the same IP address?

## Steps To Reproduce

1. Add two sites to vault that run on the same server (behind the same reverse proxy).
2. See how BW suggests both entries for both websites under "logins"

## Expected Result

Suggest the correct, single login for each site

## Actual Result

Two suggested logins for both sites (two for bw.mydomain.com [my bitwarden_rs server] and two for cloud.mydomain.com, running on the same server)

## Screenshots or Videos

Sorry, if needed I can provide them but I don't want to give out all these personal URLs

## Environment

- Operating system: Windows
- Browser: Firefox 86
- Build Version: 1.49.1

## Additional Context

I enjoy Bitwarden very much,

**Comment by arno-vdk** [comment]
Same issue for me here. Running different websites on Synology behind a reverse proxy with different accounts for each of these websites. Bitwarden does not use the (sub-)domain name of these websites but the IP-address, so it presents a list of different accounts to choose from each time logging on to one of these sites.

**Comment by freekvh** [comment]
As the number of self hosted services on my home server grows, I now sometimes get 4 suggestions for a website, it makes crtl-shift-L useless in many cases. I've also encountered this on the intranet of my employer.

**Comment by eliykat** [comment]
Bitwarden will use the URL in the address bar for its suggestions. This could be the same as the IP but in your case it looks like you have different subdomains for different intranet sites. In that case, you should be able to change the match detection options: see the help article [here](https://bitwarden.com/help/article/uri-match-detection/).

I think the `Host` option should achieve what you're after.

**Comment by freekvh** [comment]
> Bitwarden will use the URL in the address bar for its suggestions. This could be the same as the IP but in your case it looks like you have different subdomains for different intranet sites. In that case, you should be able to change the match detection options: see the help article [here](https://bitwarden.com/help/article/uri-match-detection/).
> 
> I think the `Host` option should achieve what you're after.

Yes! This fixed it, thanx! Indeed they were all services on different subdomains of the same domain.
