### ISSUE TITLE
Very slow to load

### ISSUE THREAD

**Issue by Tinrobotguy** [bitwarden/browser#1725]
When I login to the BitWarden browser app, it takes up to 5 seconds to load the passwords.  Never took so long before.  I am using Safari on an M1 MacBook Air running Big Sur, but it's also the same on my older iMac running Catalina.

**Comment by hantatsang** [comment]
@Tinrobotguy you should fill out the Issue template to help others understand the isue

**Comment by Tinrobotguy** [comment]
I'm not sure how this happened as I did fill it out. Weird.

**Comment by Tinrobotguy** [comment]
Okay, I went and deleted all the text asking for the specifics and just wrote my post. Now it shows up.

**Comment by hexicans** [comment]
hello

We have described the problem here : https://github.com/bitwarden/browser/issues/1732

Please see

**Comment by eliykat** [comment]
Closing this issue as it appears the originally posted problem has been resolved (per #1732). If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
