### ISSUE TITLE
Biometric unlock not working on Firefox 87 macOS Intel

### ISSUE THREAD

**Issue by yureiita** [bitwarden/browser#1731]
I downloaded firefox 87 from this link https://ftp.mozilla.org/pub/firefox/releases/87.0/mac/en-GB/Firefox%2087.0.dmg and it does not work. I tested on brave browser and it does work. When I try to enable unlock with biometrics on firefox the following dialog box appears:

<img width="356" alt="Screenshot 2021-03-22 at 11 21 33 PM" src="https://user-images.githubusercontent.com/26035759/112015591-eaf85380-8b66-11eb-9e20-4c7ab98f0b90.png">

- Operating system: macOS 11.2.3
- Browser: Firefox 87.0
- Build version: 1.49.1 (Firefox add-on), 1.25.0 (Desktop downloaded from mac App Store)

_Originally posted by @yureiita in https://github.com/bitwarden/browser/issues/1703#issuecomment-804159178_

**Comment by yureiita** [comment]
https://community.bitwarden.com/t/when-will-the-firefox-extension-get-biometric-support-now-that-i-think-it-supports-nativemessaging/17354/17

Looks like the user dh024 is also having the same problem. He also downloaded from the Mozilla ftp site.

@kapitainsky Can you try to download from the Mozilla ftp site and see if it's also working for you?

**Comment by SquareBottle** [comment]
It's not working in any browser for me either. I'm also using macOS, and I've tried it in Firefox, Chrome, and Brave.

**Comment by yureiita** [comment]
Did you use the desktop app from the App Store? Biometrics support for extensions is only available on the App Store version fo the desktop app according to this link https://bitwarden.com/help/article/biometrics/. I tried in Brave and it is working for me in Brave.

**Comment by yureiita** [comment]
https://github.com/bitwarden/browser/issues/1703#issuecomment-804487213

> > @yureiita Would you mind checking if you have the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json`, and also paste the content of it. Just to verify, you are using the Bitwarden addon from addons.mozilla.com?
> 
> I tried to check the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json` but there is no folder named `nativeMessagingHosts` inside the directory `~/Library/Application Support/Mozilla/`. Only a folder named `Extensions` is inside it but it is also empty. And I am using the Bitwarden addon from addons.mozilla.com.

@Hinton Since the folder ~/Library/Application Support/Mozilla/NativeMessagingHosts/ is missing, I tried creating the folder `nativeMessagingHosts` inside `~/Library/Application Support/Mozilla/` and then I unchecked and checked the enable browser integration in desktop app. After that the file `~/Library/Application Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json` is created and biometric unlock is working in Firefox.

So it seems that the json file cannot be created when folder doesn't exist. I tried deleting the folder `nativeMessagingHosts` and I can reproduce the issue.

So the fix is to create the folder `nativeMessagingHosts` inside `~/Library/Application Support/Mozilla/`.

**Comment by kapitainsky** [comment]
> @kapitainsky Can you try to download from the Mozilla ftp site and see if it's also working for you?

Yes I am downloading Fierfox 87 from Mozilla ftp site too and it works for me.

**Comment by cho-m** [comment]
Assuming comments inside following Firefox issue is still accurate, Firefox intentionally doesn't create empty subdirectories: https://bugzilla.mozilla.org/show_bug.cgi?id=1367100

The logic for Bitwarden Desktop 1.25.1 will check existence of `NativeMessagingHosts` subdirectory:
https://github.com/bitwarden/desktop/blob/v1.25.1/src/main/nativeMessaging.main.ts#L90-L94
```ts
                if (existsSync(`${this.homedir()}/Library/Application\ Support/Mozilla/NativeMessagingHosts/`)) {
                    this.writeManifest(`${this.homedir()}/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.8bit.bitwarden.json`, firefoxJson);
```

Same situation for the current master branch of Bitwarden Desktop:
https://github.com/bitwarden/desktop/blob/master/src/main/nativeMessaging.main.ts#L162
```ts
            'Firefox': `${this.homedir()}/Library/Application\ Support/Mozilla/NativeMessagingHosts/`,
```

---

Perhaps the more accurate option would be to check existence of parent directory, i.e.
```ts
            'Firefox': `${this.homedir()}/Library/Application\ Support/Mozilla/`,
```
to detect if Firefox is installed. Then, create `NativeMessagingHosts` if missing and then write file.

Looking at 1Password's help steps, I think this is closer to what they do
https://support.1password.com/could-not-connect/#for-all-browsers
```
2. Copy and paste the following command and press Return:

 mkdir -p  ~/Library/Application\ Support/Google/Chrome
```
Since they only need the app's main directory, I would assume this means they automatically create the `NativeMessagingHosts` if missing.

One thing to watch out for would be directory ownership/permissions. This seems to have been an issue with 1Password.

**Comment by Hinton** [comment]
I've opened a PR which should hopefully create the directory if it does not already exist in the future. @yureiita thank you for the help in tracking down the issue.

**Comment by danbaragan** [comment]
Another way to break this:
Pre-emptively activate `Exchange messages with programs other than Firefox` for the extension.

Then when you go to settings and click allow with biometrics, it will tell you that they are not enabled in the desktop app (although they are).

Solution:
- turn off the permission.
- activate biometrics from settings
- you will be asked for the permission
- go to settings again, as this interaction closed it and did not activate it
- activate biometrics again and it should ask you for touch id
