### ISSUE TITLE
Unlock with biometrics not working with Firefox 87 and 89

### ISSUE THREAD

**Issue by chaNcharge** [bitwarden/browser#1734]
## Describe the Bug

Since firefox and the browser extension have been updated to work with browser biometrics on firefox now, I tried to turn on browser biometrics but I'm getting an error saying that biometrics is not turned on in the desktop app. I have the desktop app from the Mac App Store, and in the browser console, it shows an error with `ExtensionError: No such native application com.8bit.bitwarden`

## Steps To Reproduce

0. Make sure bitwarden app is on and browser integration is enabled
1. Go to settings and check unlock with biometrics 
2. Click on the optional permission to allow it
3. Reopen the extension and unlock it if necessary (is this also intended?)
4. Go back to settings and check unlock with biometrics again.

## Expected Result

Browser biometrics would work properly and turn on

## Actual Result

Browser integration is not recognized as enabled in the app, with an error in the browser console `ExtensionError: No such native application com.8bit.bitwarden`

## Environment

- Operating system: macOS Big Sur 11.2.3
- Browser: Firefox 87.0, and tested in Nightly 89.0a1 (2021-03-23)
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by chaNcharge** [comment]
Sorry, accidentaly pressed the wrong button too early, closing this and reopening later.

**Comment by chaNcharge** [comment]
Reopened with proper issue, ignore my silly mistake!

**Comment by kapitainsky** [comment]
check this thread for workaround: 
https://community.bitwarden.com/t/when-will-the-firefox-extension-get-biometric-support-now-that-i-think-it-supports-nativemessaging/17354/20

**Comment by chaNcharge** [comment]
Ah, I understand now and it worked! Thank you for the tip!
