### ISSUE TITLE
Safari UI half hight

### ISSUE THREAD

**Issue by cdce8p** [bitwarden/browser#1739]
## Describe the Bug
The browser extension in Safari opens at only half the usual hight regardless of display size.
The result is similar to #1582 although I believe the issue is a different one.

## Steps To Reproduce
Open Browser extension

## Expected Result
The browser extension opens in full hight.

## Actual Result
<img width="396" alt="Screen Shot 2021-03-25 at 02 10 31" src="https://user-images.githubusercontent.com/30130371/112403757-4b29f980-8d0f-11eb-8fcf-0e6837c2c6c3.png">

## Environment

- Operating system: Mac OS Catalina 10.15.7
- Browser: Safari 14.0.3
- Build Version: 1.49.1

## Additional Context

--

**Comment by eliykat** [comment]
This is a known issue from porting to the Web Extension API in Safari. I believe we've intentionally limited the popup to that size due to unstable behaviour at full size. It's unrelated to #1582. [Upstream ticket here](https://bugs.webkit.org/show_bug.cgi?id=218704).

**Comment by cdce8p** [comment]
Might be just my opinion, but I don't think that issue is a good reason for the size limit. I for one didn't remember any problems before I updated Bitwarden yesterday. Half hight in contrast limits the extension to just logins. Any management of login information is basically unusable.

**Comment by odetinin** [comment]
I would like this to be fixed too ! I have some other Safari extensions which are not limited to the height of the box.

**Comment by dmcfaddengalway** [comment]
This is still occurring with me on the latest version of macOS, Safari and Bitwarden extension.

**Comment by cscharf** [comment]
Hi all, closing this as https://github.com/bitwarden/browser/issues/1692 was already opened for this issue.
