### ISSUE TITLE
401k.com User input error

### ISSUE THREAD

**Issue by trinitron79** [bitwarden/browser#174]
Login fails even if you have user name / password correct.   
If you copy / paste each field it works just fine.

Also after every login it asks to save the user/password again.

**Comment by Hinton** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
