### ISSUE TITLE
[1.25.1 (518)] Extension in Safari does not minimize when login is clicked

### ISSUE THREAD

**Issue by green-brontosaurus** [bitwarden/browser#1742]
## Describe the Bug

The Bitwarden pop up does not automatically minimize once you click on your login information. The box remains on the screen and covers up a good portion of the window you're trying to access, which makes it difficult to see whether your information has indeed been filled out.

## Steps To Reproduce

I believe this issue afflicts both M1 and Intel Macs. Mine is an Intel (MacBook Pro (Retina, 13-inch, Early 2015)). To reproduce this issue, simply go to any page for which you have a saved login in Bitwarden. Once you click on your information, the Bitwarden window should (and historically has) minimize. It no longer does.

## Expected Result

The Bitwarden popup should auto-minimize when you click on your login.

## Actual Result

The Bitwarden popup remains open and obstructs a good portion of the window you're trying to access.

## Screenshots or Videos

<img width="1004" alt="Screen Shot 2021-03-25 at 4 19 30 PM" src="https://user-images.githubusercontent.com/81385765/112538157-f37aa500-8d85-11eb-8d0f-be6e97e76078.png">

## Environment

- Operating system: Mac OS Big Sur Version 11.2.3 (20D91)
- Browser: Safari Version 14.0.3 (16610.4.3.1.7)
- Bitwarden: Version 1.25.1 (518)

**Comment by Ghantaz** [comment]
I can confirm the same issue exists for me too and I am using Safari on M1 hardware. Tested on another website (overleaf.com)

Operating system: Mac OS Big Sur Version 11.2.3 (20D91)
Browser: Safari Version 14.0.3 (16610.4.3.1.7)
Bitwarden Extension: Version: 1.49.1

**Comment by kennymc-c** [comment]
I can confirm this issue

**Comment by zgafford** [comment]
I'm seeing the same issue in the latest App Store update. M1 Mac Mini

**Comment by kennymc-c** [comment]
This issue is still relevant with 1.58.0
