### ISSUE TITLE
[BUG] Browser Extension Password Doesn't Work for https://bdo.com.ph

### ISSUE THREAD

**Issue by hmenorjr** [bitwarden/browser#1745]
## Describe the Bug

Upon load of the website and chose my saved username/password, login always fail. No matter what browser I use.

## Steps To Reproduce

1. Assuming you're already logged in Bitwarden browser extension, go to 'https://online.bdo.com.ph/sso/login'
2. Click on the Bitwarden logo.
3. Click on the saved username and password.
4. Click on 'Login' button

## Expected Result
The bank's dashboard will show up

## Actual Result

Error pops-out "Login Error"

## Environment

- Operating system: Mac OS Catalina
- Browser: Firefox 87.0 (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
