### ISSUE TITLE
Chrome extension vault export does not work.

### ISSUE THREAD

**Issue by quietmansoath** [bitwarden/browser#1752]
## Describe the Bug

I am on latest version of chrome on linux (ubuntu 20.10). Tried to export the vault as a .csv. Did not work. Nothing happened at all after I typed in my password when I was prompted to prior to exporting. No prompt that the file had downloaded, no downloaded file, nothing. After I hit submit, nothing happened. I had to login to the web vault to export as .csv instead.

**Comment by djsmith85** [comment]
Hi @quietmansoath I've just tried all offered file formats on Win10 using Chrome (89.0.4389.114) and I'm unable to reproduce the issue. It might be something linux-specific. I unfortunately currently haven't got a linux-machine at hand to test.

Do you receive a prompt after entering your master-password and hitting the enter-key? It should inform about exporting as a csv is unencrypted and after confirming the prompt the `.csv` should be downloaded.

**Comment by clayadams5226** [comment]
I'm not able to reproduce this either running ubuntu 20.04. Can you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
