### ISSUE TITLE
Autofill should choose most specific domain-based entry

### ISSUE THREAD

**Issue by silverwind** [bitwarden/browser#1754]
## Describe the Bug

When multiple password entries are present with domain-based matching, the extension seems to randomly choose among them for autofill. It'd great if the most specific domain-based entry is chosen among multiple such entries.

## Steps To Reproduce

1. Create Entry 1: Base Domain "example.com"
2. Create Entry 2: Website "https://service.example.com"
3. Visit "https://service.example.com"

## Expected Result

Autofill should choose entry 2 because its domain has 3 parts so is more specific than entry 1 with 2 parts.

## Actual Result

Autofill seems to randomly choose among the two entries.

## Environment

- Operating system: all
- Browser: Firefox 88
- Build Version: 1.49.1

**Comment by eliykat** [comment]
I'm not sure which particular autofill functionality you're referring to (autofill on page load, autofill by keyboard shortcut, or autofill via the extension popup), but generally:
* autofill on page load and autofill by keyboard shortcut will choose the last used login that matches the URI
* the Tab page in the browser extension popup is also ordered according to last used
* if you press the keyboard shortcut multiple times, it will cycle through the list of matching logins (again, I believe, in order of most recently used to last recently used)

By "used" I mean the last login item that was autofilled on a page, using any method.

If this isn't the behaviour you're experiencing, please let me know and I'll reopen this issue. If you'd like to request a change in this behaviour, you can lodge a feature request at our [community forums](www.community.bitwarden.com).

**Comment by silverwind** [comment]
I meant autofill on page load. I'm aware of this "last used" feature but I think the root issue may actually be that feature working inconsistently. I certainly get a lot of incorrect autofills. Maybe it's because that feature does not track last-used on a per-origin basis, but on a global basis. Certainly a topic for another issue I guess.
