### ISSUE TITLE
AWS Autofill didn't fill correctly

### ISSUE THREAD

**Issue by AugustasV** [bitwarden/browser#1755]
## Describe the Bug

I would like the AWS, Amazon pages would be filled correctly. Found Github gist, which explains which steps I should do to fix the problem, and it works. [https://gist.github.com/gene1wood/ad3fc1e2f20fd83e78c9bea86f4e339a](https://gist.github.com/gene1wood/ad3fc1e2f20fd83e78c9bea86f4e339a)
Bitwarden should automatically understand how to behave on that kind of pages.

## Steps To Reproduce

Try to log in. 

## Expected Result
Login screen fields filled correctly.

## Actual Result

It only fills login and password

## Environment

- Operating system: Mac OS Catalina
- Browser: Firefox 87
- Build Version: 1.49.1

## Additional Context
Paste from Gist, how to fix this issue:
Here's how to get BitWarden to treat these three different types of Amazon logins as separate
* amazon.com consumer retail business login
* AWS root user login (AWS logins that use an email address)
* AWS IAM user login (AWS logins that use a username)

# amazon.com consumer retail

* Set `URI 1` to `Exact` with a value of

  `https://www.amazon.com/ap/signin?_encoding=UTF8&ignoreAuthState=1&openid.assoc_handle=usflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin&switch_account=`
* Set `URI 2` to `Starts with` with a value of

  `https://www.amazon.com/ap/signin?`

# AWS root user

* Set `URI 1` to `Exact` with a value of

  `https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3Fstate%3DhashArgs%2523%26isauthcode%3Dtrue&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fhomepage&forceMobileApp=0`
* Set `URI 2` to `Regular expression` with a value of

  `https://[^./]*\.?signin.aws.amazon.com/signin\?`

# AWS IAM user

* Set `URI 1` to `Exact` with a value of

  `https://YOUR-ACCOUNT-NAME-OR-NUMBER.signin.aws.amazon.com/console`

  Where `YOUR-ACCOUNT-NAME-OR-NUMBER` is replaced by your AWS account ID number
  or alias
* Set `URI 2` to `Regular expression` with a value of

  `https://[^./]*\.?signin.aws.amazon.com/oauth\?`

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
