### ISSUE TITLE
Autofill does not work on any website that uses a browser-built in popup for login

### ISSUE THREAD

**Issue by nwhiteman42** [bitwarden/browser#1759]
## Steps To Reproduce

1. Go to any website that uses a browser popup to ask for login.
2. See the autofill doesn't work and right click autofill is not an option

## Expected Result

I would hope that I can click autofill

## Actual Result

Autofill does not work 

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/22136824/113430887-ede61600-93a8-11eb-9fc0-6382383074cd.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 87.0
- Build Version (go to "Settings" → "About" in the app): 1.49.1

## Additional Context

In this example I am logging into the WebUI for a server running rutorrent

**Comment by cho-m** [comment]
You might want to read through https://github.com/bitwarden/browser/issues/946 which uses the same example.

**Comment by nwhiteman42** [comment]
I set my login for an exact match.  I will report back in ~24 hours when my login would normally expire.  Thanks for finding that issue for me

**Comment by nwhiteman42** [comment]
I got it working.  Thanks for the help.  If anyone looks at this issue this is the setting I needed.  
![image](https://user-images.githubusercontent.com/22136824/113634386-a8417b80-963c-11eb-8957-a78eece34285.png)
