### ISSUE TITLE
Biometric unlock not working on windows 20H2/Firefox 88 b7 developer version

### ISSUE THREAD

**Issue by benzBrake** [bitwarden/browser#1768]
## Describe the Bug
I have alread enable Biometric unlock on Microsoft Edge according to documents. When I was trying to enable biometric unlock on firefox 88, Bitwarden extensions show this message.
![图片](https://user-images.githubusercontent.com/11323774/113554911-9d7eea80-962c-11eb-99aa-da7dd719eb96.png)

## Steps To Reproduce

1. Enable Windows Hello in Bitwarden Desktop.
2. Click Bitwarden Button on Firefox toolbar
3. Switch to settings tab on Bitwarden popup
4. Enable Biometric unlock.

## Expected Result

Biometric unlock would be enabled.

## Actual Result

Show error message(Picture provided in previous sections.)

## Screenshots or Videos

https://user-images.githubusercontent.com/11323774/113555608-c8b60980-962d-11eb-8146-cb83c7052392.mp4

## Environment

- Operating system: Windows 10 20H2 19042.867
- Browser: Firefox 88 b7 developer edition
- Build Version: Bitwarden Desktop 1.25.1, Bitwarden Extensions 1.49.1

## Additional Context
Biometric unlock has already worked on Bitwarden Desktop
![图片](https://user-images.githubusercontent.com/11323774/113555290-49283a80-962d-11eb-8693-2c35ce7a0c0a.png)
Biometric unlock has already worked on Bitwarden For Microsoft Edge
![图片](https://user-images.githubusercontent.com/11323774/113555678-e5524180-962d-11eb-801a-356a66643873.png)

My Firefox is a portable version firefox using [MyFirefox Firefox Loader](https://github.com/charygao/MyFirefox).

Error message from browser context toolbox
```
ExtensionError: No such native application com.8bit.bitwarden ExtensionUtils.jsm:58:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:58
    startupPromise resource://gre/modules/NativeMessaging.jsm:83
    (异步：promise callback)
    NativeApp resource://gre/modules/NativeMessaging.jsm:79
    openNative resource://gre/modules/ExtensionParent.jsm:289
    recvPortConnect resource://gre/modules/ExtensionParent.jsm:343
    recvPortConnect self-hosted:1173
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsParent.jsm:371
```

**Comment by SergeantConfused** [comment]
Hi there,

I just tested it, and biometric unlocking is functioning as intended in a standard installation of Firefox 87.0 on Windows 10 Pro 19042.870. Please try this using the stable release of Firefox and let me know how it goes.

I thank you in advance for your understanding and cooperation.

**Comment by benzBrake** [comment]
> 
> 
> Hi there,
> 
> I just tested it, and biometric unlocking is functioning as intended in a standard installation of Firefox 87.0 on Windows 10 Pro 19042.870. Please try this using the stable release of Firefox and let me know how it goes.
> 
> I thank you in advance for your understanding and cooperation.

I tried installation version of Firefox 88 beta7, still not worked
![图片](https://user-images.githubusercontent.com/11323774/113652813-1a5ea280-96c7-11eb-9101-62eab7e7e497.png)

**Comment by cho-m** [comment]
@benzBrake
One reason for **"No such native application"** is when Firefox cannot find matching Windows registry, e.g. `HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.8bit.bitwarden`

The registry is added by Bitwarden Desktop app when you click the **Enable Browser Integration** and have Firefox installed.

Bitwarden detects Firefox is installed by checking for Windows registry: `HKLM\SOFTWARE\Mozilla\Firefox`

---

You can try uncheck + check **Enable Browser Integration** in Desktop App to see if that adds registry. 

You also mentioned you are using a portable Firefox.
It is possible that it doesn't write/read from expected Windows registries.

**Comment by benzBrake** [comment]
@cho-m
> It is possible that it doesn't write/read from expected Windows registries.
Run bitwarden desktop with administator fixed this problem.
