### ISSUE TITLE
"File not found" error after click the top left button of the valut tab

### ISSUE THREAD

**Issue by yfdyh000** [bitwarden/browser#177]
`moz-extension://645f822c-3ee6-4e6d-aa77-2cb702990014/popup/index.html#!/tab/vault` opened.
Versions: bitwarden for Firefox, 1.13.5 in Firefox 55.0b2.

**Comment by begincalendar** [comment]
Same issue on FIrefox 54.0 (Ubuntu Xenial).

I think the problem is related to the `vaultController` `expandVault()` function/method.
For whatever reason, when `chrome.tabs.create({ url: '/popup/index.html#!/tab/vault' });` is run, it appears that the wrong root URL is generated/used.

**Comment by kspearrin** [comment]
Looks like Firefox product builds cannot link to internal AngularJs routes for some odd reason. Navigating directly to just `/popup/index.html` seems to work.

**Comment by kspearrin** [comment]
Opened bug report with Firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1374610

**Comment by begincalendar** [comment]
Turns out there was already a Bugzilla entry for it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1328865

Seems like it has been resolved and will be shipped with FIrefox 56.
