### ISSUE TITLE
Safari extension not available with App Store installed Bitwarden

### ISSUE THREAD

**Issue by al3xandru** [bitwarden/browser#1773]
## Describe the Bug

Safari extension is not available with Bitwarden 1.25.1 (518) installed from the App Store on M1 machine running Big Sur 11.2.3 

Removing the app and reinstalling from App Store did not fix the issue.

## Screenshots or Videos

<img width="520" alt="image" src="https://user-images.githubusercontent.com/290841/113777336-ca400a00-96df-11eb-870e-a85f612f6ed2.png">

## Environment

- Operating system: macOS BigSur
- Browser: Safari 14.0.3
- Build Version (go to "Settings" → "About" in the app): 1.25.1 (518)

**Comment by cho-m** [comment]
Probably same issue as #1696 and #1718

**Comment by al3xandru** [comment]
I’ll close this ticket as #1696 covers it better
