### ISSUE TITLE
Extension popup does not open in a new tab

### ISSUE THREAD

**Issue by f1u77y** [bitwarden/browser#178]
### Steps to reproduce
1. Open "My Vault" tab in the popup
2. Click the top left button which should open the popup page in a new tab.
3. See an error page ![screenshot of an error page](http://i.imgur.com/UcQPmXN.png)

### Affects
* [x] Firefox 54.0
* [x] Firefox Nightly
* [ ] Chromium

**Comment by kspearrin** [comment]
duplicate #177
