### ISSUE TITLE
Not able to use username value in custom field

### ISSUE THREAD

**Issue by MFYP** [bitwarden/browser#1782]
## Describe the Bug

Not able to use username value in a custom field.

## Steps To Reproduce

1. Go to 'https://www.us.hsbc.com/'
2. Click on 'Log On'
3. Use auto-fill.

## Expected Result

Username to be filled
## Actual Result

The username in bitwarden database is not filled
## Environment

- Operating system: Windows 10
- Browser: Chrome - Version 89.0.4389.114 
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

In the meantime, you may be able to create a custom field for the information that is not being correctly autofilled: see https://bitwarden.com/help/article/custom-fields/.
