### ISSUE TITLE
Can anyone  tell me what format this is?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [bitwarden/browser#1785]
When I click on Edit for some of me logins in the extension, I see this in the notes section:

>
Icon$: OM_OM_ONONOO{O{OOKOOOOOOOOOOO@@@@COOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOM_OM_ONONOO{MOsOO{OOOOOOOOOO@CO|@O@COBp^AO@TC@G@TC@G@TC@GHy@@OJqS@cJqS@cO^S@sLQg@kLQg@kNu}@sJqS@cFXp@OAdN@[@TC@GAdN@[AdN@[@TC@G@TC@G@TC@GJqS@cHy@@OLQg@kO^S@sHyE@SHyE@SO^S@sLQg@kFXp@OCLX@K@TC@GAdN@[AdN@[@TC@G@TC@GCLX@KKAS@WKAS@WNu}@sO^S@sFXp@OFXp@ONu}@sLQg@kFXp@OCLX@K@TC@GAdN@[AdN@[@TC@G@TC@GHyE@SNu}@sNqn@_Nu}@sNu}@sCLX@KJqS@cNqn@_Nqn@_FXp@OCLX@K@TC@GAdN@[LQg@kKAS@WLQg@kO^S@sO^S@sNu}@sHyE@SHyE@SHyE@SKAS@WLQg@kNqn@_FXp@OAdN@[@TC@GAdN@[Nu}@sNu}@sNqn@_O^S@sLQg@kFXp@O@TC@GCLX@KNu}@sHyE@SLQg@kNqn@_Hy@@OAdN@[@TC@GAdN@[IAQBCFXp@OFXp@OHyE@SHy@@O@TC@G@TC@GCLX@KLQg@kLQg@kNqn@_LQg@kFXp@OAdN@[AdN@[AdN@[FX|AoAdN@[@TC@GAdN@[JqS@c@TC@GFXp@OLQg@kCLX@KKAS@WO^S@sNu}@sCLX@K@TC@G@TC@GC|iAkC|iAkAdN@[AdN@[@TC@GJqS@cHyE@SKAS@WFXp@OCLX@KNqn@_O^S@sLQg@kHyE@SHyE@SHyE@SLQg@kFX|AoHyE@SFXp@OHyE@SLQg@kNu}@sCLX@KCLX@KLQg@kNqn@_LQg@kAdN@[@TC@GCLX@KFXp@OC|iAkIAQBCFXp@OHyE@SFXp@OAdN@[Hy@@OFXp@OHy@@ONu}@sNu}@sCLX@K@TC@GCLX@KFXp@O@TC@G@TC@GC|iAkCLX@KAdN@[CLX@KFXp@OFXp@OO^S@sO^S@sNqn@_FXp@OCLX@KFXp@OCLX@KAdN@[AdN@[Bp^AO@TC@G@TC@GCLX@KFXp@OKAS@WNqn@_O^S@sO^S@sLQg@kCLX@KAdN@[AdN@[AdN@[AdN@[@TC@GAdN@[IAQBCHyE@SKAS@WNqn@_Nqn@_Nqn@_KAS@WC|iAkHy@@OJqS@cFXp@OAdN@[AdN@[AdN@[AdN@[Bp^AONu}@sNqn@_Nqn@_Nqn@_KAS@WFXp@O@TC@G@TC@G@TC@GCLX@KHy@@OJqS@cHyE@SHy@@OHy@@OJqS@cIAQBCIAQBCIAQBCFX|AoC|iAkBp^AOBp^AOBp^AOC|iAkBp^AOBp^AOC|iAkC|iAkFX|AoFX|AoC|iAk

Does anyone know what format that is?

**Comment by cscharf** [comment]
Can I ask what kind of content you did have in those notes (perhaps emojis from a special emoji keyboard on your phone/device, embedded images, etc.)?

Did you import these items from another file, service or provider? (and if so, which)

That looks similar to a PNG or ICO binary mask with a hint header of `Icon$:`, which I've seen `PNG$:`, etc. so I'm _assuming_ it could be something to that degree, but not entirely sure.

**Comment by YouveGotMeowxy** [comment]
> Can I ask what kind of content you did have in those notes (perhaps emojis from a special emoji keyboard on your phone/device, embedded images, etc.)?
> 
> Did you import these items from another file, service or provider? (and if so, which)
> 
> That looks similar to a PNG or ICO binary mask with a hint header of `Icon$:`, which I've seen `PNG$:`, etc. so I'm _assuming_ it could be something to that degree, but not entirely sure.

@cscharf 

A long time ago I did an import from LastPass -> Bitwarden; maybe it came from there?

Ultimately I'm wondering if Bitwarden is reading it's favicon info from it, and if so, is there some sort of generator out there that I can select an image and have it convert into that format, so I can paste it into the Notes field of logins to set my own icons?

**Comment by cscharf** [comment]
> A long time ago I did an import from LastPass -> Bitwarden; maybe it came from there?

Perhaps, I've not ever seen that happen before, so that would be my _assumption_. What browser/version are you using?

> I'm wondering if Bitwarden is reading it's favicon info from it

No, Bitwarden will read favicon info from the URL of the vault item (password), however that would never show up in the notes field; it's only used in the list view next to the item itself. That is also pulled from the icon service, which in turn discovers the favicon, if available, from the site's domain itself and then is cached; there's no way to override this unless of course you're using your own icon service (self-hosted) and modify the code to do so.

**Comment by YouveGotMeowxy** [comment]
ok  ty @cscharf. I knew the icons were coming from the bw server, but had also wondered if maybe it had found the icon code in the notes field it would overwrite the icon from the server.

My main issue is that for whatever reason, I'm guessing because all of these services are run from behind a reverse proxy and BW  is just grabbing the favicon of the root domain, that I end up with a list that looks like this:

![image](https://user-images.githubusercontent.com/39491297/114743543-65edfd80-9d12-11eb-961b-2f3fa5f19b7f.png)

I'm sure you can imagine that with that it's had to "zip right to" the login I want at a glance whenever I visit any one of those services' page, so I want to "force" the logins to use the actual service's icons.

**Comment by cscharf** [comment]
Ah, I see, I'm not super familiar with how that would or could work but perhaps someone in the community can offer some help in configuration of the reverse proxy or icon service accordingly.

**Comment by cho-m** [comment]
> would overwrite the icon from the server.

If you have no control over the servers, the workaround right now (while custom icons are not yet supported) is to use a **Never** match for 1st URI just to get Favicon from arbitrary site.
See: https://community.bitwarden.com/t/custom-icons-for-items/80/15

There may be some other options if you have control over configurations of servers/services.

**Comment by YouveGotMeowxy** [comment]
> > would overwrite the icon from the server.
> 
> If you have no control over the servers, the workaround right now (while custom icons are not yet supported) is to use a **Never** match for 1st URI just to get Favicon from arbitrary site.
> See: https://community.bitwarden.com/t/custom-icons-for-items/80/15
> 
> There may be some other options if you have control over configurations of servers/services.

@cho-m Thank you for helping. I am running the Bitwarden server on a local machine using docker, so I have control up to that level. Are there any other options I can use knowing that?

**Comment by djsmith85** [comment]
@YouveGotMeowxy : Closing this issue as it appears the originally posted problem has been resolved. For the second request I'd ask you to please have a look at the community forums and see if someone has a solution there.
