### ISSUE TITLE
[Multi-Browser] Extension ignoring account timeout settings

### ISSUE THREAD

**Issue by BloodyIron** [bitwarden/browser#1789]
I'm using bitwarden cloud/hosted, and testing with Firefox and Chrome currently.

When I set the vault timeout to a certain time, and set to "log out", both extensions in Firefox and Chrome 100% ignore this setting.

I restarted Chrome to see if it was a caching issue, and while the web interface for Vault honoured the setting, the browser extension remained on the defualt of "on borwser restart" and "lock" as opposed to the settings I tested "15 minutes" and "log out".

This constitutes a tangible security risk if the extensions are not following the settings of this aspect (and will be especially pronounced when this becomes a policy option in the future for organisations).

I highly recommend this be added to a milestone, or some sort of kanban card, as this is an easy way to sidestep the security aspects of timed vault locks, etc.

**Comment by kendratodd** [comment]
Hi @BloodyIron - Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by BloodyIron** [comment]
Uh why can't we just have this as a bug here? I don't see why this should transition to support elsewhere...

**Comment by kendratodd** [comment]
We weren’t able to reproduce the issue and our Customer Support team indicated they’d like to get some additional information to be able to help. Our awesome support folks are better equipped to help through our [contact form](https://bitwarden.com/contact) where they can collect additional info/follow up with a call or other troubleshooting as needed.

**Comment by fra-luc** [comment]
I am experiencing a similar issue on Firefox: my vault is set to timeout at browser restart but it stays unlocked between restarts.
