### ISSUE TITLE
[Firefox] Conflict with keyboard shortcut 

### ISSUE THREAD

**Issue by f1u77y** [bitwarden/browser#179]
Ctrl+Shift+Y is a shortcut that opens downloads manager in Firefox ([here](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) is the full list). User is not able to change it (OK, as for now he's able but the add-on that lets him do it will not work on Firefox 57+). Could you provide a shortcut that does not conflict with default (and unchangeable) browser shortcuts?

**Comment by kspearrin** [comment]
The page you linked does not show `Ctrl + Shift + Y` as being a shortcut for anything in Firefox...

**Comment by f1u77y** [comment]
It does.
![Screenshot of the page](http://i.imgur.com/84xSAZe.png)

Sorry, I haven't found a way to link to the certain shortcut on this page.

**Comment by kspearrin** [comment]
Weird. Here is what mine says:

![image](https://user-images.githubusercontent.com/1190944/27331511-c868edf8-558b-11e7-9fb8-332f6f94943f.png)

**Comment by f1u77y** [comment]
That depends on useragent because default shortcuts on different systems differ.
![Screenshot](https://user-images.githubusercontent.com/11313125/27332723-b326d53c-55cb-11e7-9b4f-06f843232ac8.png)

**Comment by xdevla** [comment]
Same here, may I suggest to also switch to a shorter shortcut (I personally use it a lot).
My suggestion would be Alt+W

**Comment by chrisirwin** [comment]
Also affected, Firefox on Linux.

A similar sequence to lastpass would be great: Alt+PgDn / Alt+pgUp for next/prev matching password, which is handy for sites with multiple password matches.

**Comment by f1u77y** [comment]
That's mostly browser fault but not extension one. Firefox does not allow changing the extension keyboard shortcuts (though the semantics of the `manifest.json` entry name seems to imply that the default key could be changed. So, I think the best idea is to change the shortcut to something else (like @xdevla's suggestion) only for GNU/Linux leaving it the same for all other platforms (and therefore majority of users)

**Comment by kspearrin** [comment]
I have adjusted this for next release. The follow commands with be available as the defaults:

- Open bitwarden popup:
  - Linux: `Ctrl+Shift+U`
  - Windows/macOS: `Ctrl+Shift+Y` (unchanged)
- Auto-fill current website: `Ctrl+Shift+L`
- Generate password to clipboard: `Ctrl+Shift+Period` (not available on Firefox)

**Comment by Unixware** [comment]
kspearrin  just tell me what you are smoking there... Ctrl+Shift+U  is shortcut to enter unicode, try to use your crap while on a textbox firefox+ubuntu

**Comment by f1u77y** [comment]
@Unixware it's not a Firefox shortcut. I'm not the developer but I think if there's conflicting shortcut in your DE (there are too many of them for GNU/Linux to adapt to all of them), it's up to you to change the keyboard shortcut for the extension. Recent versions of Firefox allow this, so this should not be a problem.
