### ISSUE TITLE
Unable to "use another method" if cancel U2F security key @ login

### ISSUE THREAD

**Issue by user10293** [bitwarden/browser#1790]
## Describe the Bug

Browser gets stuck in bad state when cancelling security key prompt while trying to logon to webvault. Cancel should allow another method of 2FA but the webpage gets stuck in a loop. Happens with Yubikey OTP and FIDO U2F.

## Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/
2. Sign-in using login that requires U2F security key
3. Do NOT insert USB security key
3. Click Cancel on the Windows Security

## Expected Result

Expect NOT to see the Window Security prompt AGAIN. 
Expect to be able to click on "Use another two-step login method" in the browser.

## Actual Result

U2F Error: 1
The Windows Security prompt pops up again.
Unable to click anywhere on webpage (e.g. "Use another two-step login method")

## Screenshots or Videos

![bitwarden_u2f_error1](https://user-images.githubusercontent.com/81660427/115106950-b6d14200-9f1c-11eb-850f-f27390c65092.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 87.0

## Additional Context

I am confident this is not a Windows OS issue because it does not occur when using Gmail login.

Chrome Browser is actually worse: it causes Windows to freeze if you cancel and close browser. You'll need to Ctrl+Alt+Del.

**Comment by SergeantConfused** [comment]
Hi there,

I've encountered this in both Firefox and Chrome, and you can hit Esc while you navigate the mouse to use an alternative two-step method. Cancelling that prompt does not cause Chrome or Windows to freeze in my testing and experience, do you have any browser extensions installed on that browser?

I understand that the pace at which it prompts to read your FIDO U2F Security Key may benefit from an adjustment, and I'll relay this internally.

Thank you in advance,

**Comment by user10293** [comment]
> 
> 
> Hi there,
> 
> I've encountered this in both Firefox and Chrome, and you can hit Esc while you navigate the mouse to use an alternative two-step method. Cancelling that prompt does not cause Chrome or Windows to freeze in my testing and experience, do you have any browser extensions installed on that browser?
> 
> I understand that the pace at which it prompts to read your FIDO U2F Security Key may benefit from an adjustment, and I'll relay this internally.
> 
> Thank you in advance,

Thank you for verifying this issue. I would argue Bitwarden should only attempt to read the FIDO U2F Security Key only once. If a reattempt is really required, there should be a timeout or maximum limit of automatic read attempts. 

Hmm I'm having trouble reproducing the freeze in Chrome (including one instance in which it let me sign in without tapping the security key). I will try a couple more times.
