### ISSUE TITLE
Incorrect displaying IP-addresses

### ISSUE THREAD

**Issue by cawa-93** [bitwarden/browser#18]
![2016-10-10 23-33-38](https://cloud.githubusercontent.com/assets/1662812/19250270/390f193a-8f42-11e6-89fe-2bb942f17322.png)

**Comment by ArtemNikolaev** [comment]
@cawa-93 how it can be reproduce? The most easy way, please!

**Comment by kspearrin** [comment]
@ArtemNikolaev This appears to be a problem with the tld.js library I am using to process URLs. What should be done here is to check if the URL starts with `http://` or `https://`. If so, use the tld.js parser to get the base domain to display as the "website", if not just show the raw URI.

**Comment by kspearrin** [comment]
This will be fixed in next version (1.11.0).
