### ISSUE TITLE
[Firefox] Bitwarden breaking a site. Possibly others.

### ISSUE THREAD

**Issue by cj-sv** [bitwarden/browser#180]
Was testing out a tutorial site. Some objects aren't rendered properly when Bitwarden is enabled. I've tried loading the page with and without Bitwarden alone, with all other addons disabled. It looks like I get the same issue when enabling Privacy Badger alone too. Something related maybe.

Firefox 55.0b2 (64-bit) on Ubuntu 17.04
Site: http://try.jquery.com/levels/3/sections/12

Bitwarden Enabled:
![screenshot from 2017-06-20 19-52-18](https://user-images.githubusercontent.com/11567756/27332001-a702eb84-55f2-11e7-9c2d-a7d8e6bb21e0.png)

Bitwarden Disabled:
![screenshot from 2017-06-20 19-57-50](https://user-images.githubusercontent.com/11567756/27332039-c8fced66-55f2-11e7-935e-4a72529f81e6.png)

**Comment by kspearrin** [comment]
I do not get any issue in Firefox or Chrome on windows.

**Comment by Primokorn** [comment]
No issue here with FF 54.0 - 64 bits
No issue with Inox/Chromium browser
Manjaro

**Comment by streetwolf** [comment]
I can confirm this behavior on Fx56 (Nightly) 64 bit. Running Windows 10 Pro CU 64 bit. I'll try to narrow it down.  Perhaps it's caused by a preference setting.

**Comment by streetwolf** [comment]
Created a new profile with only BW.  Page displays as it should with BW disabled.  It doesn't display as it should with BW enabled.

**Comment by kspearrin** [comment]
Are you using other extensions ?

**Comment by streetwolf** [comment]
You probably missed my last post.  I tested on a new profile with only BW installed.  You have to be aware that Fx ships with add-ons that Mozilla calls features.  Thede are located in the Firefox main folder ….  \firefox\browser\features.  I have 14 of them.  However I did disable all of them when testing.  The fact that Tampermonkey does the same thing is interesting.
____
Gary

**Comment by streetwolf** [comment]
Could be a Webextensions problem.  After all WE is still a WIP.

**Comment by streetwolf** [comment]
Let me know if you need any more info on this issue.

**Comment by streetwolf** [comment]
Here's my Browser Console after I loaded the page in question:

GET http://try.jquery.com/levels/3/sections/12 [HTTP/1.1 304 Not Modified 567ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/application-82281c06c4be80d34fb54d4f6e563fe4.css [HTTP/1.1 304 Not Modified 16ms]
GET http://cdn.codeschool.com/blackboard/blackboard-stable.css [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/application-a7fd1434c73111597f2819a38ca73acf.js [HTTP/1.1 304 Not Modified 32ms]
GET http://cdn.codeschool.com/blackboard/blackboard-stable.js [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/bg-html-915211d8095672e2b45fe4718bd20fca.png [HTTP/1.1 304 Not Modified 0ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/radar-02309006dacc4d5d36ebf6d893d4ea5d.png [HTTP/1.1 304 Not Modified 0ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/logo-codeschool-a441c3c1343051517fa888c1ace99986.png [HTTP/1.1 304 Not Modified 15ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/bg-body-e1bd71c8db06545b3f76eb77f49596c9.jpg [HTTP/1.1 304 Not Modified 15ms]
[Exception... "Must have a non-null string spec or nsIFile object"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionParent.jsm :: ProxyContextParent :: line 307"  data: no]  (unknown)
Error: WebExtension context not found!  ExtensionParent.jsm:695:13
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/bg-sidebar-c5aa38c6164eff857ca1d87048b7f16b.png [HTTP/1.1 304 Not Modified 15ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-toc-2dbe6b389bbe0fa24fe4d2c0acbe29ca.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-video-78ca125b0e3f7c2d0555052709203f6e.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-challenge-a5ca800e246733a9320af6c05eef5878.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-slides-ef1514a4f67949eab0fc3da1f3f74a8e.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/bg-total-points-c6b4bdc6ff4459ca1653ed910f38ac63.png [HTTP/1.1 304 Not Modified 32ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/bg-drag-b0a1b9777ed30a03699ba55e67a712d5.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-view-7e2088e9c91c815f1f81478d75051278.png [HTTP/1.1 304 Not Modified 16ms]
GET http://d3n3e0roqdrhcc.cloudfront.net/assets/icn-lock-6d2800cbb165a874c3d3b886a983374f.png [HTTP/1.1 304 Not Modified 16ms]
Loading failed for the <script> with source “http://cdn.mxpnl.com/libs/mixpanel-2.2.min.js”.  12:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  application-a7fd1434c73111597f2819a38ca73acf.js:3347:28
GET https://beta.openbadges.org/issuer.js [HTTP/1.1 304 Not Modified 43ms]
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone :: line 52"  data: no]  (unknown)
TelemetryStopwatch: key "WEBEXT_CONTENT_SCRIPT_INJECTION_MS" was already initialized  TelemetryStopwatch.jsm:343
TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "WEBEXT_CONTENT_SCRIPT_INJECTION_MS", key: "null"  TelemetryStopwatch.jsm:363
TypeError: context.contentWindow is null  ExtensionContent.jsm:320:9
SyntaxError: redeclaration of const ContentScript  content.js:1:1
SyntaxError: redeclaration of const CLASS_SELECTABLE  content.js:1:1
ReferenceError: browserAction is not defined
Stack trace:
onMessage/</<@moz-extension://d0a216c3-8ac1-4eb1-9b72-32536d491a27/index.js:156:1
promise callback*onMessage/<@moz-extension://d0a216c3-8ac1-4eb1-9b72-32536d491a27/index.js:152:21
  index.js:167:35

**Comment by kspearrin** [comment]
Can you see what extension you have that is id `d0a216c3-8ac1-4eb1-9b72-32536d491a27`? I don't think that is bitwarden since we have no `index.js` file.

**Comment by streetwolf** [comment]
It’s not BW.  It’s a different add-on.

____
Gary

**Comment by kspearrin** [comment]
Ok. Can it be disabled?

**Comment by streetwolf** [comment]
As I said I created a new profile and installed only BW.  Furthermore, I disabled all of the feature add-ons I mentioned.  No add-ons or features except for BW.  BW enabled the page in question is missing some stuff.  BW disabled the page displays the missing stuff.

The fact that Tampermonkey and the other program mentioned by the OP gives credence that something might not be quite right with Webextensions.

____
Gary

**Comment by kspearrin** [comment]
The console log that you posted points to some other extension causing an error:

```
ReferenceError: browserAction is not defined
Stack trace:
onMessage/</<@moz-extension://d0a216c3-8ac1-4eb1-9b72-32536d491a27/index.js:156:1
promise callback*onMessage/<@moz-extension://d0a216c3-8ac1-4eb1-9b72-32536d491a27/index.js:152:21
index.js:167:35
```

I am not sure how that is effecting bitwarden, but that looks to be the cause of it.

**Comment by mhammond** [comment]
FWIW, I can reproduce the issue on my 56 dev profile - bitwarden installed (not even logged in) causes the issue reported. Disabling the addon and refreshing the page fixes it. Re-enable it and refresh re-causes the problem.

As I disable bitwarden my console shows:
13:02:24.357 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 1 ExtensionCommon.jsm:306
	withLastError resource://gre/modules/ExtensionCommon.jsm:306:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:359:11

upon refreshing the page I see nothing in the console (other than a deprecation warning about the page itself using getPreventDefault)

**Comment by kspearrin** [comment]
It sounds like everyone that is reporting this is on Firefox nightly.

**Comment by cj-sv** [comment]
Looks like both Beta and Nightly are affected. I'm currently on beta.

**Comment by derjanb** [comment]
FYI: Looks like a FF bug. I've created a bug report at their issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1375875
