### ISSUE TITLE
Cannot enable unlock with browser biometrics with Chromium on macOS Big Sur

### ISSUE THREAD

**Issue by maiux** [bitwarden/browser#1804]
## Describe the Bug
Just can't enable "Unlock with biometrics", it will lead to "Browser integration is not enabled" wheter Bitwarden desktop is running or not.

## Steps To Reproduce

1. Installed Bitwarden Desktop from Mac App Store (v 1.25.1) on Big Sur 11.3
2. Logged in my Bitwarden account in Bitwarden Desktop and enabled Browser integration
3. Installed Bitwarden extension (1.49.1) in Brave browser (1.23.73) from Chrome web store and made it unlock with biometrics using "create tmp folder in app container" workaround
4. Made sure that unlock with biometrics works in Brave
5. Installed Bitwarden extension (1.49.1) in Chromium (https://github.com/macchrome/macstable/releases/download/v90.0.4430.72-r857950-macOS/Chromium.90.0.4430.72.sync.app.zip) and logged in my Bitwarden account
6. tried to enable "Unlock with biometrics" with Bitwarden desktop running with Dock icon visible and unlocked: lead to  "Browser integration is not enabled"
7. tried to enable "Unlock with biometrics" with Bitwarden desktop closed, lead to "Browser integration is not enabled"
8. checked for "~/Library/Application Support/Chromium/NativeMessagingHosts", exists and is empty

## Expected Result
In case of Bitwarden desktop app running and unlocked: unlock with biometrics enabled and working
In case of Bitwarden desktop app closed: "Bitwarden desktop not running" error or something similar

## Actual Result
See 6 and 7 step reported before

## Environment

- Operating system: macOS Big Sur 11.3
- Browser: Chromium.90.0.4430.72.sync from woolyss
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by anthonymag** [comment]
Same here.

Brave Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64) macOS Catalina 10.15.7
Bitwarden Desktop Version 1.25.1 (518)
Bitwarden extension Version: 1.49.1

![image](https://user-images.githubusercontent.com/29254374/116249352-bade3a80-a73a-11eb-990a-38c7d2fd25f2.png)

**Comment by kapitainsky** [comment]
you might try some suggestions from https://github.com/bitwarden/browser/issues/1709

**Comment by maiux** [comment]
On Brave I confirm it's working but tried various workarounds for Chromium and they not work.

In Brave make sure _tmp_ folder exists in Bitwarden container at Library/Containers/com.bitwarden.desktop/Data

**Comment by Hinton** [comment]
Hmm I don't believe we currently create any manifests for Chromium. As a temporary workaround try:

- Create the directory `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`
- Disable and re-enable "Enable browser integration"
- Copy the directory `~/Library/Application Support/Google/Chrome/NativeMessagingHosts` to `~/Library/Application Support/Chromium/NativeMessagingHosts` (Which I believe is the correct path according to https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#mac-os-x)

**Comment by maiux** [comment]
Many thanks, as you stated it works. I just signed in GitHub using BitWarden & Touch ID.

**Comment by M09NST3R** [comment]
> Hmm I don't believe we currently supports creating manifests for Chromium. As a temporary workaround try:
> 
> * Create the directory `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`
> * Disable and re-enable "Enable browser integration"
> * Copy the directory `~/Library/Application Support/Google/Chrome/NativeMessagingHosts` to `~/Library/Application Support/Chromium/NativeMessagingHosts` (Which I believe is the correct path according to https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#mac-os-x)

Hello, I tried switching from the Chrome Web Store version of this extensionn (1.49.1) to a self-built package from this repo (1.50.*), but the Biometric integration stopped working as a result. Should the above fix it, or is this unrelated? (I've switched back to the Chrome Store version for now.) Thank you!

PS: On Big Sur.

**Comment by Hinton** [comment]
@M09NST3R The readme on the desktop project describes how to get Native Messaging working with self-built extensions https://github.com/bitwarden/desktop#buildrun. Self-built extensions on Chrome gets assigned a different ID which needs to be added to the manifests.
