### ISSUE TITLE
Local browser build much slower than the official chrome extension

### ISSUE THREAD

**Issue by nneul** [bitwarden/browser#1807]
## Describe the Bug

Is there anything different/special/extra done in the full release process for the extension beyond what is documented for the build process here?

If this were C based I'd automatically assume "oh, you built it with debug and didn't enable optimization" - but is there anything equivalent to that for the extension build?

## Steps To Reproduce

1. Do a local build
2. Load into Chrome
3. Click on browser toolbar icon

## Expected Result

Equivalent responsiveness to the official extension

## Actual Result

Popup takes significantly longer to display every time the icon is clicked - almost 3-4 times as long.

## Screenshots or Videos

Can provide if needed.

## Environment

- Operating system: Ubuntu 20 64bit
- Browser: Chrome various versions from 88-90
- Build Version (go to "Settings" → "About" in the app): at the moment 1.48.1, but not version specific

## Additional Context

I have two instances of the plugin installed, one official, and one custom build with just some cosmetic tweaks to menu names to distinguish it from the official plugin. Using to support separate logins simultaneously.

**Comment by eliykat** [comment]
What build command are you using? If you're using `npm run build`, you could try `npm run dist` instead. Then extract the appropriate .zip from the `dist` folder and sideload that. I think this should enable additional optimization, but I haven't tested it myself to see if it's any faster.

**Comment by nneul** [comment]
Thank you. I will give that a try!
