### ISSUE TITLE
Safari crashes when trying to access insecure website with https

### ISSUE THREAD

**Issue by M-Whitaker** [bitwarden/browser#1812]
## Describe the Bug
When trying to access an HTTP only website through HTTPS rather than showing the safari page of "Connection not private" safari crashes.

## Steps To Reproduce
Go to [https://neverssl.com](https://neverssl.com) (A well-known site that doesn't support HTTPS)
## Expected Result
Safari should show the "connection not private" message.
![image](https://user-images.githubusercontent.com/32771451/116766787-3a625700-aa24-11eb-925b-da8d2621681f.png)
## Actual Result
Safari Crashes (I can send a crash report if needed)

## Environment

- Operating system: macOS Big Sur 11.2.3 (arm64)
- Browser: Safari 14.0.3 (16610.4.3.1.7)
- Build Version: 1.25.1 (518)

## Additional Context
- Bitwarden is from the App Store (if that is pertinent). 
- I do run other safari extensions but have removed them all and just left Bitwarden enabled to weed out the bug. 
- I also have chrome installed with Bitwarden and chrome doesn't crash so it looks like only safari is affected.
- "Just don't use HTTPS on websites that don't support it" - Unfortunately, this does happen with google images too sometimes however it is not reproducible. I assume it is the same issue just it looks like a different use case because I'm not aware of the website SSL certificate when using google images.

**Comment by tgreer-bw** [comment]
Are you on 11.3 by chance? This issue seems to be resolved in Safari after the update.

**Comment by M-Whitaker** [comment]
Knew I would have missed something... No, 11.2.3

**Comment by tgreer-bw** [comment]
No worries, hopefully you'll see this resolved with 11.3.

**Comment by M-Whitaker** [comment]
Perfect, thanks for the help :)
