### ISSUE TITLE
When using dark mode, a white screen appears briefly before Bitwarden loads up

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#1813]
## Describe the Bug
When using dark mode, a white screen appears briefly before Bitwarden loads up. Sometimes this screen appears longer if the user is logged out.

## Steps To Reproduce
1. Use dark mode;
2. Open Bitwarden and also open it when the user is logged out.

## Expected Result
When using dark mode, Bitwarden should not display a white screen when loading.

## Screenshots or Videos
https://user-images.githubusercontent.com/78433932/116826415-3b050580-ab6a-11eb-8698-64ab305b54ff.mp4

## Environment
- Operating system: Kubuntu 21.04
- Browser: Firefox 88
- Build Version 1.49.1

**Comment by Krychaz** [comment]
### Reproduction Environment

- macOS: 11.3.1(M1 Chip)
- Brave: 1.24.82
- Extension: 1.49.1

### Steps taken to re-produce

- Use Dark Mode
- Open bitwarden extension (both when users is logged in and out)

 ### Results
-a white screen appears briefly before Bitwarden loads up.

### Next Steps
-Issue added to the tracker.

**Comment by semi-transparent-dodecahedron** [comment]
Can confirm this is happening with version 1.51.1 (Firefox).

**Comment by setyb** [comment]
I fixed this bug locally in Firefox by adding the following ruleset to `userContent.css`:

```
body {
	background-color: #281A18 !important;
}
```

For best results, you'll want to enclose that ruleset an appropriately specified `@-moz-document` block.

It's possible the same technique could be used directly in Bitwarden, but it was more time-efficient for me to fix it locally.
