### ISSUE TITLE
Name & URI 1 Fields Populated Incorrectly when creating new Login in popout window

### ISSUE THREAD

**Issue by arunkapur** [bitwarden/browser#1816]
## Describe the Bug

When popping out the Firefox browser extension in a new window, the URI 1 and Name fields are being populated with the Firefox browser extension Internal UUID. This forces the user to constantly have to manually delete these values when adding new entries.

## Steps To Reproduce

1) Click the Bitwarden Browser Extension Icon
2) Click the "Pop out to to new window" icon. Do not navigate elsewhere or perform any other action.
3) Click the Plus Icon to add a new item.
4) The Name field shows a long string that refers to the moz-extension Internal UUID. The URI 1 field shows moz-extension://{Bitwarden browser extension Internal UUID}/popup/index.html?uilocation=popout#/tabs/current

## Expected Result

The Name and URI 1 fields should be empty. 

## Actual Result

1) The Name field shows a long string that refers to the moz-extension Internal UUID. 
2) The URI 1 field shows moz-extension://{Bitwarden browser extension Internal UUID}/popup/index.html?uilocation=popout#/tabs/current

## Screenshots or Videos

I did not include a screenshot for security reasons as I see the moz-extension internal UUID
is used in HTTP requests.

## Environment

- Operating system: Windows 10
- Browser: Firefox 88.0b9
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by eliykat** [comment]
I agree we shouldn't prepopulate the new Login details in this situation. This would be a good first issue - just add a check in `vault/add-edit.component.ts` whether `PopupUtilsService.inPopout()` is true, and if so, don't prepopulate these details.

**Comment by arunkapur** [comment]
@marcioflaviof That change does not fix the issue.

I fixed the issue in Pull Request #1820. @eliykat Please assign this issue to me.
