### ISSUE TITLE
Overlapping text in password verification window

### ISSUE THREAD

**Issue by Aculeo** [bitwarden/browser#182]
For the german translation the text is overlapping when entering the master password:

![bitwarden-overlapping-text](https://user-images.githubusercontent.com/3977620/27494787-9ee99916-584f-11e7-8d2f-ca3112959f3f.jpg)

I imagine other translations are affected as well.

**Comment by kspearrin** [comment]
Check out our guide on how to contribute to translations.

https://github.com/bitwarden/browser/blob/master/CONTRIBUTING.md

Unfortunately I don't speak German so I'm not sure how to fix it.

**Comment by Aculeo** [comment]
Hmm, I can't think of any way to shorten that. As long as there's master password in the title it's probably going to be too long in a few languages. Maybe renaming the title to _Unlock vault_ (which would be _Tresor entsperren_ in german). But other languages might not have such a short word for vault.

I guess another option would be to change text alignment.

**Comment by SW1FT** [comment]
In the Portuguese translation I changed the title from "Verify Master Password" to "Verify Password" (in the Portuguese equivalent) because it would overlap. Maybe a change in the source string would be better to avoid overlapping with other languages as well.

**Comment by Aculeo** [comment]
FYI, there's the same problem now on the Premium Membership tab. IMO there needs to a design change, like increasing the size of the popup. Text changes aren't always going to solve this.

![bitwarden-premium-membership](https://user-images.githubusercontent.com/3977620/28684667-87345e7a-7305-11e7-8cf4-7bd7789c0ae4.png)

**Comment by kspearrin** [comment]
Is this in Firefox? We actually did increase the size of the popup in other browsers but Firefox has a stubborn bug that has prevented us from doing so at the moment.

**Comment by Aculeo** [comment]
Ah, I see. Yeah, I'm using Firefox.

**Comment by kspearrin** [comment]
Can you check version 1.26 and see if this is a still a problem?

**Comment by Aculeo** [comment]
Looks great now! 
![grafik](https://user-images.githubusercontent.com/3977620/38952861-435137be-434d-11e8-96e8-cff085878fe4.png)

Also checked other menus and I can't see any overlapping text.
