### ISSUE TITLE
Keyboard disabled by ‘Enable auto-fill on page load’

### ISSUE THREAD

**Issue by LeginNY** [bitwarden/browser#1823]
## Describe the Bug
In Bitwarden free, using the Edge browser extension under Windows 10, and with ‘Enable auto-fill on page load’ option ticked, after launching a number of web pages with Bitwarden, and having the login info successfully auto-filled, sometimes the keyboard becomes partially disabled - characters have no effect when typed although the function buttons such as Home, Delete etc still work; a reboot is required to cure this.
Problem does not occur if Bitwarden is used with the ‘Enable auto-fill on page load’ option unticked.

## Steps To Reproduce
1. Tick the ‘Enable auto-fill on page load’ option.
2. From the vault, launch a website such that the username & password are successfully auto-filled; login to the website.
3. Repeat website launch & login in step 2 a number of times (5 or 6); do some general browsing in other tabs.
4. Launch Notepad and attempt to type some text.

## Expected Result
Typed text appears normally in Notepad window.

## Actual Result
When typing characters, they are not echoed in the Notepad window.  However, if a previously typed document is opened, the function keys such as HOME, END and DELETE do operate correctly.  Mouse and other functions all work correctly.

## Screenshots or Videos
N/A

## Environment
- Operating system: Windows 10: Home edition, 10.0.19042 Build 19042
- Browser: Edge 90.0.818.41 (Official build) (64-bit)
- Build Version 1.49.1 (loaded from Chrome store); problem also reproduced using 1.49.0 (loaded from Edge store)
- Hardware:  HP G72-B10SA laptop, purchased May 2011; problem also reproduced using a Lenovo Ideapad 330S-14IKB, purchased May 2019.

## Additional Context
Note this problem can sometime take a while to reproduce - i.e. repeated website launches.

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for bringing this to my attention. Do you happen to have the Kaspersky Internet Security extension installed on that browser?

Thank you in advance,

**Comment by LeginNY** [comment]
Hi @SergeantConfused - thanks for your reply - yes I do have the Kaspersky extension installed in the Edge browser that I'm using with the Bitwarden extension.  Is there a known conflict here between the two extensions?  Should I remove the Kaspersky extension (I don't use it)?  Should I switch to another virus checker altogether?

**Comment by kapitainsky** [comment]
My two pennies worth opinion here is that most antivirus software is just more problem than solution, since I ditched it my computer experience moved from troubleshooting constantly to using it for whatever I like be doing. Ars Technica had some good explanation time ago - https://arstechnica.com/information-technology/2017/01/antivirus-is-bad/

On Windows build in Defender is perfectly sufficient for 99% of users. If you must experiment with shady origin software do it always in some Virtual Machine environment anyway. Black hat guys are always few steps ahead of so called antivirus software.

**Comment by LeginNY** [comment]
Hi @SergeantConfused - great suggestion: I removed the Kaspersky browser extension and now Bitwarden has been fine for a week.  Thanks for your help.
