### ISSUE TITLE
No update when changing password

### ISSUE THREAD

**Issue by williamgh2019** [bitwarden/browser#1825]
I use Chrome latest version and my problem is Bitwarden not ask for update password whenever I change password in a website.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. (I just edited this issue to include password updates as well as saving new passwords.) Please also direct any discussion or questions to that issue. This issue will now be closed.
