### ISSUE TITLE
Should fill the 2nd page

### ISSUE THREAD

**Issue by jief666** [bitwarden/browser#1831]
## Describe the Bug

Only the first page (where the username is asked) is auto filled. I have to click on bitwarden icon to fill the second page.

## Steps To Reproduce

Create an entry with a password and 2 custom fields clientId and referenceNumber
1. Go to https://www.cignahealthbenefits.com/en/login/plan-members/
2. Click on continue

## Expected Result

password you be filled.

## Actual Result

empty password field.

## Environment

- Operating system: Mac OS Mojave
- Browser: Chrome 81.0.4044.129
- Build Version : 1.49.1

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
