### ISSUE TITLE
Vault timeout feature does not seem to work.

### ISSUE THREAD

**Issue by Erengit** [bitwarden/browser#1832]
## Describe the Bug

I have set the vault timeout to 4 hours, but when I restart the browser the vault locks. I reinstalled the extension but my way didn't work either.

## Steps To Reproduce

1. Go to Settings
2. Click on `Vault Timeout`
4. Click on `4 hours`

## Expected Result

Vault should be locked after 4 hours.

## Actual Result

Vault timeout feature does not seem to work.

## Environment

- Operating system: [Windows 10]
- Browser: [Chrome 90]
- Build Version: [1.49.1]

**Comment by eliykat** [comment]
Hi @Erengit, it is correct that the vault locks when you close all browser windows. It would be unsafe to keep your unencrypted passwords in memory after all browser windows are closed, so the vault automatically locks to ensure the safety of your data.

There is more information and some suggestions on how to deal with this in our help docs: https://bitwarden.com/help/article/vault-timeout/
