### ISSUE TITLE
Session expired by Cloudflare blocking requests, preventing offline use

### ISSUE THREAD

**Issue by ehaskins** [bitwarden/browser#1835]
## Describe the Bug

When Cloudflare blocks requests to vault.bitwarden.com, the browser extension considers the session timed out.

Also, error message is ugly...

## Steps To Reproduce

Appears to happen due to 5xx responses while Cloudflare is blocking requests.

## Expected Result

The browser extension should not consider the session expired due to 5xx response. It should continue to work as if offline.

## Actual Result

Session is ended, and login fails until Cloudflare stops blocking requests.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5442879/118039733-47414d80-b336-11eb-88e9-3a7e6d75c731.png)
## Environment

- Operating system: Windows 10
- Browser: Chrome 90
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

## Additional Context

n/a

**Comment by eliykat** [comment]
Hi @ehaskins, this Cloudfare issue has now been resolved and all services should be working again. However, please tag me here if you're still getting the error and I can check with our team.
