### ISSUE TITLE
[Android, Firefox Ext.] unlock with biometrics doesn't work

### ISSUE THREAD

**Issue by lucscamps** [bitwarden/browser#1846]
## Describe the Bug

The option to unlock with biometrics in android firefox extension doesn't work. When I select the checkbox the option doesn't stay on, although no error message is displayed.

## Steps To Reproduce

1. Go to Settings
2. Click on Enable unlock with biometrics

## Expected Result

Biometric is shown when it's locked.

## Actual Result

Nothing happens and the option turn back to disabled.

## Environment

- Operating system: [Android 11]
- Browser: [Firefox 88.1.3]

**Comment by tgreer-bw** [comment]
If you're using the extension on Android, that makes sense. That checkbox is for the extension on Desktop browsers, and requires the Desktop app to be installed.

If you use the Android app, you can leverage biometrics.

**Comment by lucscamps** [comment]
Oh, I see. I tried this method because android app doesn't have credcards autofill, according to bitwarden page. Thought it would work through browser...
Thanks! =)

**Comment by roussak** [comment]
> If you're using the extension on Android, that makes sense

I'm not quite understood this phrase. Furthermore, I don't understand why the biometrics using on the desktop FF extension is logical (though, the biometrics scanners by itself is not so widely-used), but in the mobile FF extension its using is illogical according with your words (though, nowadays there need to try to find a smartphone without the biometrics scanner).

I have both the BW application on my Android (of 8.0) smartphone and the FF extension. I set up the biometrics on the Android and switched on the corresponding unlocking option on the BW application and it works. But I can't switch it on for the FF extension with the same symptoms as the topic starter described. So, even if the BW application will be locked out, all the secrets can be seen via the FF extension. Or I must use a locking with the master-password or PIN in the FF extension, which is inconvenient (for me, at least).

**Comment by Hinton** [comment]
Unfortunately this is a technical limitation with browser extensions in FF for Android. On Desktop browsers we get around this limitation by communicating with our native application, unfortunately to my knowledge the same is not possible on Android.

**Comment by roussak** [comment]
I see..
Maybe, it could be better to remove (or hide) this checkbox then?
