### ISSUE TITLE
Firefox extension doesn't allow to unlock with biometric

### ISSUE THREAD

**Issue by YoniMelki** [bitwarden/browser#1848]
## Describe the Bug

The Firefox extension doesn't allow to unlock with biometric when using Mac OS although the option is enabled in the Desktop application.

## Expected Result
Prompting fingerprint in order to activate the unlock with biometric

## Actual Result
Error

## Screenshots or Videos
**Screenshot from extension**
<img width="352" alt="Screen Shot 2021-05-16 at 13 07 49" src="https://user-images.githubusercontent.com/58732001/118393421-b9bc7100-b647-11eb-8347-435c1eb54f02.png">

**Screenshot from desktop application in Mac OS (Big Sur)**
<img width="468" alt="Screen Shot 2021-05-16 at 13 08 58" src="https://user-images.githubusercontent.com/58732001/118393449-e2446b00-b647-11eb-97f2-8a5d7f99b514.png">

## Environment

- Operating system: Mac OS Big Sur Version 11.2.3
- Browser: Firefox 88.0.1 (64-bit)

**Comment by kapitainsky** [comment]
Have you installed bitwarden from App Store? Biometrics do not work when installed from dmg.

**Comment by kapitainsky** [comment]
Also try this:

https://community.bitwarden.com/t/when-will-the-firefox-extension-get-biometric-support-now-that-i-think-it-supports-nativemessaging/17354/20?u=kapitainsky

**Comment by YoniMelki** [comment]
> Have you installed bitwarden from App Store? Biometrics do not work when installed from dmg.

Yes, I have installed it from the app store.
Your link solved my issue! thank you very much
