### ISSUE TITLE
Two factor broken on Firefox

### ISSUE THREAD

**Issue by bobobo1618** [bitwarden/browser#185]
I'm unable to log in to my two factor Bitwarden account on Firefox.

Steps to reproduce:

- Use Firefox
- Install either from Mozilla addons or load from Git (commit 8f236f76a795f8ad562a4bb8f569c9a7980812f9)
- Attempt login

Expected behaviour: Login works

Actual behaviour: "An unexpected error has occured."

I've had a fiddle with the Firefox debugger and the problem appears to be that the error condition on the XHR is being hit here: https://github.com/bitwarden/browser/blob/master/src/services/apiService.js#L53

I don't actually see an outgoing network request and as far as I can see, the XHR has a useless "error" response code with no text. I do see this in the logs though:

```
Possibly unhandled rejection: {"statusCode":0} undefined
```

From `angular.js`.

**Comment by kspearrin** [comment]
What other addons are you using?

**Comment by bobobo1618** [comment]
- Addon compatibility reporter
- FoxyProxy Standard
- h264ify
- Image Search Options
- JSONView
- Reddit Enhancement Suite
- Referrer Control
- Tampermonkey
- uMatrix

**Comment by kspearrin** [comment]
See https://github.com/bitwarden/browser/issues/171


Umatrix is likely breaking it

**Comment by bobobo1618** [comment]
That was indeed the cause of status code 0!

However after resolving that, I'm still getting the error, it's just caused by something different. I'm now getting a `400 Bad Request` response consisting of this:

```json
{"error":"invalid_grant","error_description":"Two factor required.","TwoFactorProviders":[0],"TwoFactorProvider":0}
```

There's no prompt to enter a code like there is on Chrome.

**Comment by KenyaAdams** [comment]
To jump on this as well (with anecdotal evidence), my Authy code wasn't working for my account earlier today either (Both on Chrome and Brave).  Entering the code on while on chrome's console also reported a 400 error.  I created a new account and linked it to Authy and the Two-Factor Authentication worked in the same browser.
The 2FA account was linked to Authy on July 1st and was working at least until July 2nd.

I've unlinked the 2FA so I can no longer reproduce for more information.

**Comment by mhammond** [comment]
Working fine for me on Firefox nightly

**Comment by kspearrin** [comment]
@bobobo1618 Are you using a dev build off of master or from the addon store? Master has a lot of new 2FA stuff that isn't in sync with prod server yet. Make sure you are using the prod build form the addon store.

**Comment by bobobo1618** [comment]
Yep, I was using it direct from Git. Going back to release and adding a uMatrix exception (`* bitwarden.com * allow`) resolves this for me.
