### ISSUE TITLE
can't remove an item from a shared collection 

### ISSUE THREAD

**Issue by jaymzh** [bitwarden/browser#1855]
## Describe the Bug

If you shared something to a collection, you cannot remove it from that collection. There's an "unselect all" button, but when you save it says you must pick a collection.

## Steps To Reproduce

Share an item to a collection. Attempt to remove it from that collection.

## Expected Result

It works

## Actual Result

You get an error.

This is on the web interface.

**Comment by kendratodd** [comment]
Hi @jaymzh  - Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. 

I believe that this article may address your concern about how to "unshare" an item from a collection: https://bitwarden.com/help/article/org-faqs/#q-how-do-i-unshare-an-item-from-my-organization. 

If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.

**Comment by jaymzh** [comment]
@kendratodd - Yes, I know this is a place for bugs and development issues, as you'll see, I've filed several legitimate bugs on bitwarden - and a feature request I hope to get the time to implement one day.

It seems to me to be a bug to have an "unselect all" option implying that's reasonable, while also not allowing one to unselect all. Perhaps the error might point people to that article?

Further, the article you point to, however, doesn't seem to be valid. I do not get a "clone" option either under the account that shared the item, nor under the account that the item was shared with.  I'm attaching relevant screenshots.

The person being shared with:
![bw_sharee](https://user-images.githubusercontent.com/938467/121972743-b1338500-cd30-11eb-80fc-1abfaf19b906.png)
The person sharing:
![bw_sharer](https://user-images.githubusercontent.com/938467/121972746-b1338500-cd30-11eb-81ba-282d614dd052.png)

**Comment by tgreer-bw** [comment]
@jaymzh - if you access the item from the organization context in the web vault, you can clone it.

**Comment by jaymzh** [comment]
Heh, that _also_ doesn't work, if I uncheck the collection in the clone, I get the "You must select at least one collection" error and can't save the clone.

**Comment by tgreer-bw** [comment]
You'll want to change the 'Who owns this item?' dropdown to your individual email address. That will save the item in your individual vault.

**Comment by jaymzh** [comment]
There is no such option.

![bw_clone](https://user-images.githubusercontent.com/938467/122121121-1a260600-cde0-11eb-84a8-c6c551e3ef93.png)

**Comment by tgreer-bw** [comment]
You'll need to be an Admin to perform the change of ownership action:

<img width="482" alt="ownership" src="https://user-images.githubusercontent.com/61418192/122212446-d4b41800-ce75-11eb-96fa-6b0add7bfc78.png">

**Comment by jaymzh** [comment]
Right, so... that leads to a weird problem:

Account1: the original creator of the entry. Shared it with a collection that includes account1 and account2
Account2: admin

Account1 can't clone it to themselves
Account2, the admin, can change ownership of the clone, but not to account1, only to account2

Account2 (me, the admin) doesn't want this to show up anymore, but Account1 still wants to keep it around.

It seems there is literally now way for the original creator of the item to keep the item while removing it from the collection other than to manually make a new entry, manually copy over all the data, then delete the shared item?

That seems... like a bug.

**Comment by tgreer-bw** [comment]
@jaymzh - I can definitely understand. There are a couple of items at play here - one of which is the connotation of **share** that conveys ownership is maintained. When you share an item in Bitwarden, it's **moved** to the Org, and as such is now owned by the Organization - thus why the admin requirement for cloning. We're updating some of that UI now actually.

However, you raise a good point on UX, and we do agree that there is room for improvement in this flow, and on product backlog for evaluation for sure!

**Comment by jaymzh** [comment]
Thanks for the clarity @tgreer-bw . 

So it seems to me that the UX changes to describe shared items is already being tracked, that's awesome. It also seems like maybe I should open a separate bug/feature request for "non-admins should be able to clone Org items in their personal space" - does that sound reasonable?

Justification: a non-admin can already read a shared item, which means they can manually copy it into their personal space, so there's no reason not to allow users to do this, as far as I can tell.

**Comment by tgreer-bw** [comment]
@jaymzh all good points. A feature request on our [forums](https://community.bitwarden.com) would be great, though not absolutely needed, as we've got this tracking internally, too 👍

**Comment by alnjxn** [comment]
This issue has still not been resolved. IMO this is a bug, not a UX issue. There is no legitimate path from taking an item out of a collection and moving it back to the original owners account. Additionally there should is the item of UX, where you should not be able to uncheck all if you can't actually have an item not in any collection.
