### ISSUE TITLE
White corners on Firefox Proton

### ISSUE THREAD

**Issue by DimitriDR** [bitwarden/browser#1864]
## Describe the Bug
It's not really a bug, but a enhancement, on Firefox Nightly, which features the new "Proton" interface, add-on windows have been rounded a bit, and it barely works but there's still a little white square on corners.

## Steps To Reproduce

1. Check on Firefox Nightly to see the new interface.
2. Open Bitwarden

## Screenshots or Videos

![Capture d’écran 2021-05-30 161659](https://user-images.githubusercontent.com/56969769/120107749-7b07da00-c162-11eb-87ee-c1e26590e63b.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 90.0a1
- Build Version (go to "Settings" → "About" in the app): 1.50.0

**Comment by kapitainsky** [comment]
I wonder if it is Bitwarden or Firefox on Windows problem as on macOS it looks ok:

![Screenshot 2021-05-31 at 08 04 43](https://user-images.githubusercontent.com/15635386/120153976-4427d780-c1e7-11eb-8f51-9014f683af07.png)

![Screenshot 2021-05-31 at 08 05 04](https://user-images.githubusercontent.com/15635386/120153991-48ec8b80-c1e7-11eb-9166-723b71d31a33.png)

**Comment by DimitriDR** [comment]
Issue solved.
