### ISSUE TITLE
Waterfox 78.10 / "Unlock with biometrics" option is missing

### ISSUE THREAD

**Issue by galaxyrun** [bitwarden/browser#1865]
## Steps To Reproduce
download the Bitwarden extension (Chrome or Firefox)
login
search for the unlock with biometrics option in the menu

## Expected Result
It should show up in the settings menu

## Actual Result
there is only "unlock with pin"

## Environment

- Operating system: Windows 10 21H1
- Browser: Waterfox G3.2.1 (64-Bit) 
- Build Version: Version: 1.50.0

## Additional Context
The Desktop program is installed, with browser mode enabled
was the same with Windows 20H2

**Comment by Hinton** [comment]
Firefox 78 (and probably Waterfox) does not support the optional permission required to enable biometrics. Unfortunately it's only supported in Firefox 87+, https://bitwarden.com/help/article/biometrics/.
