### ISSUE TITLE
Firefox - biometrics - secure channel constantly invalidated

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/browser#1867]
## Describe the Bug

App store BW application is installed and running. It has enabled "Enable browser integration" and "Require verification for browser integration" so first time I try to unlock Firefox extension with biometrics I have to approve it. It works fine. 

But then after some time it breaks and subsequent extension biometrics unlocks display following error:

<img width="391" alt="Screenshot 2021-05-31 at 15 03 38" src="https://user-images.githubusercontent.com/15635386/120206039-99cda580-c222-11eb-99a0-e3cbb6617fea.png">

And approval process has to be repeated.

Both Firefox and BW application are running all the time.

## Steps To Reproduce

I could not identify repeatable conditions when this issue occurs - usually it happens when I do not use Firefox for longer time (few minutes +).

When connected with app I can repeatability lock and unlock extension with biometrics. But then after some random time it is broken.

## Expected Result

As long as BW app and Firefox are running and biometric validation has been approved it should stay approved.

## Actual Result

Randomly already granted approval is invalidated.

## Environment

- Operating system: macOS 11.4
- Browser: Firefox 89
- Build Version browser extension:  1.50.0
- Build Version app: 1.26.5 (528)- but the same was happening with 1.25.1 and 1.26.3

**Comment by joshkpeterson** [comment]
I came here to report the firefox extension being unusable for me, I see a red lock icon placed over the extension's icon, and a hanging loading spinner when trying to open bitwarden either via the toolbar or sidebar.

@kapitainsky Is it possible the issue you're seeing is unrelated to biometrics? I would be curious if you can reproduce the same issue with a simpler test case, would confirm that the firefox extension is just plain not working

**Comment by kapitainsky** [comment]
It sounds you have some more serious issue indeed but in my case I have positive experience with Firefox extension. My issue is clearly related to  "Require verification for browser integration" option from BW app - otherwise everything works. And if I  disable this option it would be pretty much trouble free ride.

I have never experienced issues like yours but I had some problems with Safari extension - very basic troubleshooting which helped in my Safari case was to clean browser cache completely. It seems that technology BW has chosen to implement their extensions rely heavily on web technologies provided by browser platform and is easily impacted by some maybe accumulated errors in browser cache.

If it does not help I would suggest you open new ticket as your description points into something very different.

**Comment by kapitainsky** [comment]
Not sure what helped - as everything keep upgrading, on Firefox 91 beta now, BW plugin 1.51.1 and desktop 1.27.1. It is rock solid and only loses authentication on browser restart (which is ok). Time to close this issue.
