### ISSUE TITLE
[Firefox] Enabling of OOP Web Extensions will break the UI

### ISSUE THREAD

**Issue by sciguyryan** [bitwarden/browser#187]
Hi guys!

I just thought I would give a warning here since I tested this out today. OOP Web Extensions is due to be enabled on nightly soon (see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1190679) . Upon testing this locally it seems to make it so that no UI is presented when clicking on the toolbar icon.

Since this is something that is coming in the near future I thought it would be useful.

**Comment by kspearrin** [comment]
Thanks for the info. I'm not sure what changes for extension developers with OOP. I'll have to read more into it.

**Comment by streetwolf** [comment]
I don't know when the OP did his testing but the OOP WE patch was pulled earlier today on inbound due to a bunch of problems.  I notice now that it is back on inbound and I will be using it in a short while.  I'll let you know if there are any problems.

**Comment by sciguyryan** [comment]
> I don't know when the OP did his testing but the OOP WE patch was pulled earlier today on inbound due to a bunch of problems. I notice now that it is back on inbound and I will be using it in a short while. I'll let you know if there are any problems.

Basically pulled the patch manually and recompiled myself. I haven't tested the updated version of the patches so I have no idea if the underlying issue is resolved or not. I guess we'll see shortly!

**Comment by streetwolf** [comment]
I’m on inbound right now with the new OOP WE patch.  The pref ‘extensions.webextensions.remote’ is set to true.  I haven’t had any problems with any of my WE add-ons.


____
Gary

**Comment by streetwolf** [comment]
Did some more testing.  Seems the patch has partially broken a couple of my WE add-ons although BW so far seems to work fine but it's early in my testing.

**Comment by sciguyryan** [comment]
I can confirm that the issue I saw doesn't seem to be reproduced with the newer patch. I suspect it's safe to close this issue - we can always open up a new one for any issues that crop up.

Thanks for looking into this guys!
