### ISSUE TITLE
Bitwarden Safari extension autofill causes alltrails.com unable to log in

### ISSUE THREAD

**Issue by ywwry66** [bitwarden/browser#1870]
If I use autofill (`cmd+shift+L`) on [alltrails.com](https://www.alltrails.com/login?ref=header) and then click on the `Log in` button, I cannot log into my account. However, if I use the desktop vault and copy paste the username/psw to the corresponding fields, everything works fine.

## Steps To Reproduce

1. Go to [alltrails.com](https://www.alltrails.com/login?ref=header)
2. Unlock Bitwarden Safari extension
3. Press `cmd+shift+L`
4. Click on the `Log in` button

## Expected Result
I am logged into my account

## Actual Result
Nothing happens

## Environment

- Operating system: macOS Big Sur
- Browser: Safari 14.1.1
- Build Version: 1.26.5

**Comment by eliykat** [comment]
Interesting, it looks like the autofill script overwrites the value of the reCAPTCHA token.

```html
<input type="hidden" id="recaptcha-token" value="test@test.com" data-com.bitwarden.browser.user-edited="yes">
```

ReCAPTCHA is common enough that I think we could explicitly check for this and avoid overwriting token values.

We're tracking site-specific autofill issues in #1621, can you please fill out the form there, including a note that it overwrites the reCAPTCHA token and stops the login button from working. That way it can be collated into the other autofill issues to be reviewed all together.

As we're trying to centralise autofill problems in one place, I'll close this thread.
