### ISSUE TITLE
Edge extension generating wrong 2FA codes

### ISSUE THREAD

**Issue by Wout-M** [bitwarden/browser#1877]
## Describe the Bug

2 factor authentication codes generated by the browers extension are different from those on the mobile app. Those on the app work, those on the extension don't

## Steps To Reproduce

1. Enable 2FA on an account (e.g. Github)
2. Configure Bitwarden TOTP using a QR code with the mobile app
3. Try to log in using the autofill and 2FA code copy of the extension
4. Try to use the code of the mobile app

## Expected Result

The codes of both the extension and the mobile app should be the same and should both be useable to log into my accounts.

## Actual Result

The codes from the extension are different from those in the app, which in turn makes it impossible to log in.

## Screenshots or Videos

Screenshots on phone aren't allowed it seems, but here is the wrong code from the extension
![image](https://user-images.githubusercontent.com/38492330/120646982-61c09f80-c47a-11eb-8457-2e985cea3ee5.png)

## Environment
PC
- Operating system: [Windows 10]
- Browser: [Edge 90.0.818.66]
- Build Version [1.50.0]

Phone
- Operating System: [Android 10]
- Phone: [Nokia 6.1]
- Build Version: [2.10.0]

**Comment by tgreer-bw** [comment]
This can happen when the time on the device is wrong - can you confirm your time/date/timezone is correct on the PC?

**Comment by Wout-M** [comment]
It seems like my phone is using GMT+2 as timezone, while my pc uses UTC+1. Both display the exact same date & time though (Thursday 3 June 2022, 15:22) for my location (Belgium)

**Comment by tgreer-bw** [comment]
That would be the issue :-) 

If they are in different time zones but display the same time, it effectively makes your PC an hour off. If you change the time and time zone you should be back in business.

**Comment by Wout-M** [comment]
Well they are both different systems for the timezones, both are the correct one for Belgium. On my pc I also can only select UTC zones, while on my phone it automatically selects a GMT zone.

**Comment by tgreer-bw** [comment]
If your systems are in these time zones, they should read different times :-) 

<img width="778" alt="Screen Shot 2021-06-03 at 9 30 25 AM" src="https://user-images.githubusercontent.com/61418192/120653046-55bee880-c44e-11eb-926c-466f342db03c.png">

**Comment by Wout-M** [comment]
![image](https://user-images.githubusercontent.com/38492330/120653689-3a210580-c481-11eb-881f-cd699132c2b8.png)
![image](https://user-images.githubusercontent.com/38492330/120653812-59b82e00-c481-11eb-87fc-4478fe1279cf.png)
Well I have no idea how this is possible then

**Comment by tgreer-bw** [comment]
Not sure, but it's what is causing your issue. Bitwarden uses the machine's time to generate the code, and it being off will cause the code to be off, too. 

Perhaps enable automatic time zone, or manually set the time zone to UTC+2 on the PC and give it a shot.

**Comment by Wout-M** [comment]
That's pretty strange that basically the same location and timezones with the same time give different codes, but well I've never made a TOTP generator. As for the automatic time zone, that still puts it on UTC+1 and UTC+2 would just give me the wrong hour for my location since it's an hour later.

**Comment by kapitainsky** [comment]
In your Windows "Date & Time" settings make sure that "Adjust for daylight saving time automatically" is enabled. You are in UTC+1 time zone but your time at the moment is UTC+2 (daylight saving) - then if needed set manually correct time - automatic settings often take time to apply.

**Comment by Wout-M** [comment]
Somehow it works again without me changing anything. I'll close the ticket.
