### ISSUE TITLE
Back button can navigate to lock page without vault being locked

### ISSUE THREAD

**Issue by dario-piotrowicz** [bitwarden/browser#1882]
## Describe the Bug
When unlocking the extension you can press your mouse's back button and go back to a seemingly locked vault, but if you press your mouse's forward button you'll go back to the unlocked vault.

Not a big deal but this behaviour looks a bit strange

## Steps To Reproduce

1. Open the extension
2. Provide you master password to unlock your vault
3. Press your mouse's back button, you'll be redirected to the previous panel and vault will look locked
4. Press your mouse's forward button, you'll be back into your vault (without having entered the master password)

## Expected Result

The mouse back button should not redirect you to the panel asking you for your master password

## Actual Result

You get redirected to the panel asking you for your master password, but you can still go back to your vault without providing the password (even though a message on the panel says that your vault is locked)

## Screenshots or Videos

![bitwarden browser](https://user-images.githubusercontent.com/61631103/120933079-6e4e2d80-c6f0-11eb-82e4-e21875c3748f.gif)

## Environment

- Operating system: Ubuntu 20.04.2 LTS
- Browser: Chromium Version 91.0.4472.77 (Official Build) snap (64-bit)
- Build Version: Version: 1.50.0

## Additional Context

This does not happen in Firefox, there the mouse back button doesn't redirect you to the master password panel

The mouse events are button 8 press and 9 press for back and forward respectively

If you close the extension and reopen it the back button does not redirect you to the master password panel (basically it happens only after you've just accessed your vault without closing the extension)

At some point this issue was also present in the desktop version but I believe it is not longer there (https://github.com/bitwarden/desktop/issues/314)

**Comment by eliykat** [comment]
I fixed this in web vault and desktop (https://github.com/bitwarden/desktop/pull/847), clearly browser also needs the same fix. Thanks for the report!

**Comment by dario-piotrowicz** [comment]
cool, my please :)

By the way I just tested it in Chromium and Firefox and the latter strangely doesn't seem to have the issue so it may be a bit edge case
