### ISSUE TITLE
Unlocking vault fails, but login works

### ISSUE THREAD

**Issue by darkvodka** [bitwarden/browser#1891]
## Describe the Bug

I can't unlock my safe with the firefox extension. I get the error "invalid master password".
But if I log out and log back in with the same password it works. 
Similar to: https://github.com/bitwarden/browser/issues/1404

## Steps To Reproduce

1. Get your vault to be locked, either by reopening the browser or by manually locking the vault via Settings > Lock Attempt to unlock with your master 
2. Notice it accuses you of typing the wrong password
3. Log out, and log back in with the same password
4. Notice it logs in just fine with the same password

## Expected Result

The vault must be unlocked directly without going through the logout/login phase

## Actual Result

"Invalid master password"

## Screenshots or Videos

https://www.youtube.com/watch?v=ndI-xeZf3dA

## Environment

- Operating system: Ubuntu 21.10
- Browser: Firefox 89
- Server version: 2.10.1 
- Extension version : 1.50.0

**Comment by SergeantConfused** [comment]
Hi @darkvodka,

That may occur when using recent clients with an outdated server. Please follow the instructions here: https://bitwarden.com/help/article/updating-on-premise/ to update your local Bitwarden server to the latest version, and let me know if you continue to encounter that behaviour.

You can see the latest versions here: https://github.com/bitwarden/server and here: https://github.com/bitwarden/web

I thank you in advance for your understanding, and please do not hesitate to reply to this message if you have any further questions.

**Comment by djsmith85** [comment]
Hi @darkvodka, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
