### ISSUE TITLE
Form fill profiles

### ISSUE THREAD

**Issue by blockloop** [bitwarden/browser#19]
LastPass has the ability to store form fill profiles. I can create profiles which I use to fill out forms on new signups, etc

**Comment by jyavenard** [comment]
This is the primary reason why I'm still using LastPass

**Comment by kspearrin** [comment]
This is coming up soon now that we have the infrastructure in place from our custom fields release in 1.17.x.

**Comment by kspearrin** [comment]
This is now available in v1.20.0

**Comment by jyavenard** [comment]
is there some documentation available on how to use this?

**Comment by kspearrin** [comment]
@jyavenard No. Is there something about it that you're not understanding that would need docs?

**Comment by jyavenard** [comment]
Well, creating a new card or Ide tithe entry is easy... But I found no way of actually using them other than manually copy each field.
There's a form alright, but it ain't filling :)

Missing in identity forms are date field, like valid from, and valid until (useful for passports)
