### ISSUE TITLE
Additional space character appended to field values

### ISSUE THREAD

**Issue by M-Miller-42** [bitwarden/browser#1905]
Sometimes I have to manually copy fields from an identity (because there is no `Copy Value` icon). When I triple click the field value to select it, an artificial extra white space after the value is also selected. This can be very inconvenient in some cases, e.g. answers for security questions.
 
This appears _not_ to be a problem for some field types (`Name` and `Address`). 

![Screenshot from 2021-06-19 12-38-13](https://user-images.githubusercontent.com/4184356/122639838-7c427c00-d0fc-11eb-8004-3164c402d0d1.png)

## Steps To Reproduce
1. Create and save an Identity with `Identity Name`,`Email` or `Phone` filled out
2. View the Identity in the addon popup
3. Triple click on any of the three filled out values. (Or alternatively select the full line by clicking & holding, then swipe right.)
4. Note the artificial space at the end of the selection
5. Press Ctrl+C 
6. The copied value is different from the original from step 1

## Environment
Version: 1.50.0
Firefox 89.0.1 (64-bit)
Ubuntu 20.04

**Comment by eliykat** [comment]
Hi @M-Miller-42, this issue has already been reported in #1180, so this ticket will be closed as a duplicate.

**Comment by elasticspoon** [comment]
While I was trouble shooting another issue, I noticed that this issue still persists.

![identity-issues](https://github.com/bitwarden/clients/assets/14540596/2ef95cb0-c2bf-4b8b-ba80-0e8c61bc51f9)

I seems to be related to text nodes surrounding the interpolated strings. For example simply reformatting the line fixes the issue:

![image](https://github.com/bitwarden/clients/assets/14540596/0c90d388-917a-498f-a995-949997df6231)

```html
<div class="box-content-row" *ngIf="cipher.identity.username">
  <span
    class="row-label draggable"
    draggable="true"
    (dragstart)="setTextDataOnDrag($event, cipher.identity.username)"
    >{{ "username" | i18n }}</span
    >{{ cipher.identity.username }}</div>
```



However, the linter will reformat it back.

```html
<div class="box-content-row" *ngIf="cipher.identity.username">
    <span
      class="row-label draggable"
      draggable="true"
      (dragstart)="setTextDataOnDrag($event, cipher.identity.username)"
      >{{ "username" | i18n }}</span
   >
   {{ cipher.identity.username }}
</div>
```

The solution seems to be to wrap the interpolated string in a `div` tag. 

```html
   <div>{{ cipher.identity.username }}</div>
```

A `span` does not work, it does not display the additional characters but they are still copied to the clipboard.

If that sounds reasonable I could open a PR for this.

**Comment by eliykat** [comment]
Hi @elasticspoon, can you please open a new Issue for this problem, that way it'll get picked up by our various triage automations etc.

Your solution is nice and simple but I'd be concerned about maintainability. The next time someone touches the file they're likely to change this very specific formatting and the issue will reappear. If we could enforce this formatting via Prettier or eslint (which we already use) that might work, or a workaround might just be to provide copy buttons (which I know people have asked for anyway).

Just my 2 cents, when you create a new issue it'll go to the appropriate team to look at.

**Comment by elasticspoon** [comment]
Sounds good. 

> I'd be concerned about maintainability. The next time someone touches the file they're likely to change this very specific formatting and the issue will reappear.

I think I did a poor job explaining. I was suggesting a formatting fix would be a bad idea. Instead I was suggesting wrapping the field value in a `div` tag.
