### ISSUE TITLE
Long translations cause icons to shift from their centred locations in the user interface.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1909]
## Describe the Bug
The icons in the bottom menu bar of the browser extension shift from their centred locations to accommodate long names.

## Steps To Reproduce
1. Change your browser's language to Italian.
2. Restart your browser.
3. Unlock your Bitwarden browser extension.

## Expected Result
For the icons to remain centred.

## Actual Result
The icons are off-centre.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/73389600/122753969-b1390500-d29b-11eb-90e9-2160e29ada1c.png)
![image](https://user-images.githubusercontent.com/73389600/122753976-b39b5f00-d29b-11eb-92b8-84110f0e1d66.png)

## Environment
- Operating system: Windows 10 Pro.
- Browser: Chrome 91.0.
- Build Version: 1.50.0.

## Additional Context
N/A.

**Comment by eliykat** [comment]
It looks like the icons remain centered above their text, but the columns change width to accommodate longer labels. I'm not sure what the alternative is - text would otherwise have to be wrapped or truncated, or translations would have to be changed to be more succinct.

**Comment by SergeantConfused** [comment]
Yes, having a more succinct translation can help in examples such as this, as I was told that writing "Cassaforte" would be sufficient. And if that's not possible in other languages, we can consider wrapping the text or we can set it to scroll when it's in focus, for example.
