### ISSUE TITLE
Interest in collaborating on login form finding/autofill?

### ISSUE THREAD

**Issue by bufke** [bitwarden/browser#191]
Hello,
Several open source password manager extensions feature code that guesses and fills in login forms. Do you have any interest in helping start a separate project for this "find and fill" capability? I based [mine](https://gitlab.com/burke-software/passit-frontend/blob/master/src/app/extension/form-fill/form-fill.ts) on Mitro's implementation, though I ported it to typescript. There are several new-ish open source password managers these days and I'd love to think of ways to collaborate. We'd have to think through how to package it in a way that is useful for all parties.

**Comment by kspearrin** [comment]
We actually did not write any of our autofill code. It is all based on [1Password's autofill scripts](https://github.com/agilebits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L629) from their iOS extension that I unminified and adapted for bitwarden.

If you can come up with something better I'd be more than happy to take a look and collaborate if it's any better.

**Comment by bufke** [comment]
Interesting. I'll see how it compares to Mitro. I'll ping you when I post something to it's own git project. I'm just going to close this for now and reopen it when I have something interesting to look at.
