### ISSUE TITLE
Safari - Unable to select other 2FA Method if using a FIDO2 WebAuthn Key

### ISSUE THREAD

**Issue by aj-bw** [bitwarden/browser#1912]
**## Describe the Bug##**
when logging into the Safari browser extension, if you have a hardware key enrolled with FIDO2 WebAuthn ( does not happen when enrolled as Yubico OTP ) - the option to " use another two-step login method" is unclickable bc the redirect to a new tab happens so quickly that you cant click it. So if your FIDO key is unavailable but you have back up methods available, you cannot log into Safari browser extension

**## Steps To Reproduce##**
have a bitwarden account with a hardware key enrolled via FIDO2 WebAuthn
Open Safari
Select Login
enter credentials
For a split second you will see the "use another two-step login method" but it disappears before being able to click it
opens a new safari tab to complete webauthn process
clicking on the extension during this process does not give the option to choose another method either

**## Expected Result##**
After inputting username and password, the option to choose another 2FA method should be able to be chose

**## Actual Result##**
Redirect happens so quickly that you cannot click it, so your only option is to use your FIDO key even if you have other 2FA methods configured

**## Environment##**
- Operating system: M1 Macbook Pro 2020, MacOS 11.4
- Browser: Safari Version 14.1.1 (16611.2.7.1.4)

**Comment by kendratodd** [comment]
Good news - I believe this one was surfaced internally and already fixed for the upcoming release by: https://github.com/bitwarden/browser/pull/1879 & https://github.com/bitwarden/jslib/pull/398. 

For now, I'm going to close this as resolved, and it should be releasing very soon! Thanks!
