### ISSUE TITLE
Autofill does not copy the TOTP code to the clipboad

### ISSUE THREAD

**Issue by npenin** [bitwarden/browser#1914]
## Describe the Bug

When using autofill, the TOTP code is not copied to the clipboard, which forces the user to open the extension, and click on the clock.

## Steps To Reproduce

1. Enable auto-fill in the extension
2. Go to any website with registered credentials and TOTP. 
3. See the authentication auto-filled
4. Submit credentials
5. Try to paste

## Expected Result

the TOTP code would be pasted in step 5

## Actual Result

the clipboard is either empty or was not overriden with the TOTP code

## Environment

- Operating system: Windows 10
- Browser: Chrome 92.0.4515.51 
- Build Version (go to "Settings" → "About" in the app): 1.50.0

## Additional Context

Ideally, the TOTP would be autofilled if there is no username field but just a password/TOTP field.

**Comment by Greenderella** [comment]
Hi @npenin 

This is the intended behavior at the moment, you can check this article on our Help Center about how to use TOTP codes while the option **Enable Auto-fill on Page Load** is active: https://bitwarden.com/help/article/authenticator-keys/#use-generated-codes

**Comment by jonschlu** [comment]
@Greenderella 

Why exactly is it designed this way? It decreases the usefulness of the feature tremendously. I can't see how this would be linked to security, since you'll have to manually paste the TOTP either way. So there's no risk that a fake website can grab both login credentials and TOTP without manual user action.

**Comment by tgreer-bw** [comment]
It was the initial implementation, but TOTP codes will be copied for all autofill options in the next release:

https://github.com/bitwarden/browser/pull/1843

**Comment by npenin** [comment]
wonderful news :)
