### ISSUE TITLE
TOTP from the browser extension will not be accepted

### ISSUE THREAD

**Issue by TeraNovaLP** [bitwarden/browser#1915]
## Describe the Bug

When I copy the 2FA code from the Extension and try to use the code, this will not be accepted. The code from the Android app and from the extension on Windows works fine. I could reproduce this behavior in vivaldi and chromium.

## Steps To Reproduce

1. Go to a login page. (e.g. GitHub)
2. Use the autofill function for this page.
3. Then just paste or explicitly copy the 2FA code from the extension and try to use it.

## Expected Result

The 2FA code is accepted, and I can log in.

## Actual Result

The site says the code is not valid.

## Environment

- Operating system: Manjaro Linux KDE (Kernel: 5.10.42-1, KDE-Plasma: 5.21.5)
- Browser: Vivaldi: 4.0.2312.33 & Chromium: 91.0.4472.114
- Build Version: 1.50.0

**Comment by SergeantConfused** [comment]
Hi @TeraNovaLP,

Are your Bitwarden browser extension and your Bitwarden mobile client showing the same 6-digit TOTP code?
If not, please set your computer's time and time zone to automatic and test that again, and let me know how it goes.


Thank you in advance,

**Comment by TeraNovaLP** [comment]
@SergeantConfused 

Somehow the time zone was not right, after correcting this, all codes work fine. I completely overlook that. So I close this issue.

Thanks for your help.
