### ISSUE TITLE
Hotkey doesn't work in Vivaldi 1.10

### ISSUE THREAD

**Issue by JanSeW** [bitwarden/browser#192]
Hey guys,

in the newest Vivaldi release the Ctrl+Shift+Y hotkey doesn't work.
This is a pretty small bug but I wanted to note this.

Hope, this will be fixed soon.

Thxalot,
JanSe

**Comment by kspearrin** [comment]
Navigate to chrome://extensions in your address bar you can adjust the shortcut to whatever you like.

**Comment by JanSeW** [comment]
Thank you for your answer.
But nothing changed. I tried some hotkeys like Ctrl+Shift+D, Ctrl+5 ...

**Comment by kspearrin** [comment]
Hmm sounds like a Vivaldi issue then. Hot keys are working fine for me in chrome and Firefox.

**Comment by JanSeW** [comment]
Yes you are right. Now I tried also the hotkey for another extension.
I will post this bug in the Vivaldi forum soon.

Thxalot

**Comment by kspearrin** [comment]
FYI here: Vivaldi does not support hotkeys at the moment. We added a workaround that will allow you to autofill (`Ctrl + Shift + L`) and generate a password (`Ctrl + Shift + 9`) in the next version.
