### ISSUE TITLE
Very Laggy/Slow when editing in the Chrome-Extension in Mac OS Big Sur

### ISSUE THREAD

**Issue by neomorina** [bitwarden/browser#1923]
The Chrome extension is very slow when I edit my logins through it.
If I just type something into the input field, it takes 5 seconds to appear on the screen.
Interacting with the user interface is almost as impossible.
However, this problem only occurs in Chrome for Mac OS.
It seems to work just fine on other browsers.

**Comment by eliykat** [comment]
Hi @neomorina, this looks like an existing issue that has already been reported: #1854. I'll close this thread as a duplicate, but please add any further information or discussion over in #1854.
