### ISSUE TITLE
Chinese text in options of extension for English(UK)

### ISSUE THREAD

**Issue by brphilly** [bitwarden/browser#1924]
## Describe the Bug
There is Chinese text in the options under autofill. This seems to have been introduced by 93f830eddd2adddd826b280919de76fc499692c2. Looks like it might be a Crowdin thing and only applies to English(UK) but I'm not familiar with Crowdin so am filing an issue.

## Steps To Reproduce

1. Use the UK localisation
2. Click on the browser extension icon
3. Click on 'Settings'
4. Scroll down to and click on 'Options'
5. Scroll down to 'Autofill'

## Expected Result
It should show English text.

## Actual Result
It shows Chinese text.

## Screenshots or Videos
<img width="370" alt="Bitwarden" src="https://user-images.githubusercontent.com/65504429/124311046-03fca180-db65-11eb-8c88-3499cc1b2d38.png">

## Environment

- Operating system: MacOS BigSur 11.4
- Browser: Brave 1.26.74
- Build Version (go to "Settings" → "About" in the app): 1.51.0

**Comment by danmullen** [comment]
I can confirm I have the same issue on Windows 10 using the latest Firefox 89.0.2.  Also using Bitwarden extension version 1.51.0.

**Comment by danmullen** [comment]
The same commit changed every instance of the word "organisation" to "organization". The 's' spelling is correct in UK English.

**Comment by tgreer-bw** [comment]
@cscharf I've fixed this in crowdin.

@danmullen thanks for the heads-up!

**Comment by eliykat** [comment]
Closed as this appears to be fixed, thanks @tgreer-bw!
