### ISSUE TITLE
Browser plugin does not keep vault unlocked on Windows 11

### ISSUE THREAD

**Issue by jamincollins** [bitwarden/browser#1925]
## Describe the Bug

Bitwarden vault does not appear to stay unlocked for the duration of the browser session.  Each request (form fill, password copy, etc) is met with a prompt for the vault master password (see attached screen shot).

## Steps To Reproduce

AFAICT, this began happening after receiving the Windows 11 update via Windows Insider.

Attempt to form fill any site or copy any password.

## Expected Result

Vault to remain unlocked for the duration of the browser session as before.

## Actual Result

Each request (form fill, password copy, etc) is met with a prompt for the vault master password (see attached screen shot).

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/1904577/124314337-7783bc00-db2f-11eb-85d7-618ffe771fbe.png)

## Environment

- Operating system: Windows 11
- Browser: Brave 
- Build Version (go to "Settings" → "About" in the app): Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

**Comment by tgreer-bw** [comment]
@jamincollins this is actually our new 'Master Password Reprompt" feature. Looks like you'll want to go into the browser extension settings and perform a sync. This will make sure that your new extension has the latest vault data, and will keep this from appearing. We're patching this in https://github.com/bitwarden/jslib/pull/422 also.

**Comment by jamincollins** [comment]
Tried:
![image](https://user-images.githubusercontent.com/1904577/124317662-c122d580-db34-11eb-9758-e5450dc7a871.png)

**Comment by tgreer-bw** [comment]
Strange indeed. Can you try to log out and back in and see if the issue persists?

**Comment by jamincollins** [comment]
I have a self hosted bitwarden server using the `bitwarden.sh` script.

Issued the following commands:
```
./bitwarden.sh stop
./bitwarden.sh update
./bitwarden.sh renewcert
./bitwarden.sh start
```

After these, the plugin was finally able to sync.

After a successful sync, the plugin appears to function as desired (no longer re-prompting for master pass).
