### ISSUE TITLE
Password Generator clears out unsaved changes

### ISSUE THREAD

**Issue by Narvey** [bitwarden/browser#1927]
## Describe the Bug

When I generate a password, my recent changes get cleared.

## Steps To Reproduce

1. Create a new entry, or edit an existing one.
2. Punch in 333 as the username
3. Push the password generation button.
4. Accept the generated password (or tweak if desired)
5. Note that the 333 disappeared.

## Expected Result

333 (username) should still be there.

## Actual Result

username vanished.

## Environment

- Operating system: Mac OS High Sierra
- Browser:  Firefox 89.0.1
- Build Version (go to "Settings" → "About" in the app): 1.51.0

**Comment by saurabhs** [comment]
Can reproduce this on Firefox 89.0.2, Bitwarden 1.51.0 on Windows 10
For me the username & password fields clears out after returning from password generation (100% times if I select the first randomly generated password (didn't click the "Regenerate Password") otherwise happening around ~4/5 times).

**Comment by baek-sang** [comment]
Same issue.
Windows 10 / Firefox 90 / Bitwarden 1.51.0
And Password Genetrate choose not set.

**Comment by Jaguarvir** [comment]
Same issue
Ubuntu 20.10 / 89.0.2 / bitwarden 1.51.0
I have had to access to the website to save more registers since a couple of days, because the addon don't save the username and password

**Comment by radupotop** [comment]
I can confirm this with on Firefox 89.0.2 (64-bit), Linux 5.12.14-arch1-1.  
This was introduced with Bitwarden Version 1.51.0.  

I attached a video to illustrate the issue. 


https://user-images.githubusercontent.com/54769/124444771-d9823280-dd76-11eb-9e44-82d239cb7b0e.mp4

**Comment by eliykat** [comment]
I confirm this is reproducible and is being worked on, thanks all.

**Comment by Narvey** [comment]
@eliykat This got worse since I originally posted it. Now the generated password never saves, whereas before it would save if I didn't enter the username first.

**Comment by eliykat** [comment]
@Narvey That was also my experience. It'll be fixed in an upcoming patch release in the next week or so.

**Comment by Narvey** [comment]
@eliykat  seems to be fixed now, along with the original issue. Thanks!
