### ISSUE TITLE
Master password confirmation. Master password required when copying any data

### ISSUE THREAD

**Issue by cameronspeakflash** [bitwarden/browser#1928]
## Describe the Bug

Today the Bitwarden browser extension started requiring master password confirmation when copying any username or password. I'm using the latest version of Brave.

Master password confirmation
This action is protected. To continue, please re-enter your master password to verify your identity.

## Steps To Reproduce

1. Go to browser extension
2. Login
3. Scroll down to any entry
4. Click on password copy button

## Expected Result

The password is copied to the clipboard

## Actual Result

A prompt opens that says: "Master password confirmation" "This action is protected. To continue, please re-enter your master password to verify your identity."

This is slowing down my workflow massively since it requires manually entering the master password on every site.

## Environment

- Operating system: PopOS latest
- Browser: Brave Latest
- Build Version Version: 1.51.0

**Comment by tgreer-bw** [comment]
This is actually our Master Password Reprompt feature - perform a full sync on your Browser extension and it should be back to normal.

Another example was posted earlier here: https://github.com/bitwarden/browser/issues/1925

**Comment by cameronspeakflash** [comment]
That fixed the issue, thanks for the quick response.
Settings -> Sync -> Sync Vault Now for anyone else looking.

**Comment by eliykat** [comment]
Sync will resolve this issue for now, but we've also fixed this in the code base as well.
