### ISSUE TITLE
Vault 'Unlock with pin' ignored, prompts for master password on Firefox

### ISSUE THREAD

**Issue by beltsonata** [bitwarden/browser#1929]
## Describe the Bug

Bitwarden ignores the 'Vault timeout' setting of 'Unlock with PIN' and requires the master password to unlock the vault (however it remains logged in)

## Steps To Reproduce

1. Set the following options in Bitwarden via Firefox:

- 'Vault timeout' set to 'On browser restart'
- 'Vault timeout action' set to 'Lock'
- 'Unlock with pin' setup and enabled
- 'Two step login' disabled

2. Restart Firefox
3. Bitwarden displays the 'locked' icon 
4. Click on it

## Expected Result

I expected to see the 'Verify PIN' prompt

## Actual Result

The 'Verify master password' prompt is displayed

## Environment

- Operating system: Kubuntu 20.04
- Browser: Firefox 89.0.2, 
- Build Version (go to "Settings" → "About" in the app): 1.51.0

**Comment by SergeantConfused** [comment]
Hi @beltsonata,

Can you please make sure you did not activate 'Lock with master password on browser restart'?
Please deactivate the PIN and re-activate it by following this guide: https://bitwarden.com/help/article/unlock-with-pin/ and let me know how that goes.

Thank you in advance,

**Comment by beltsonata** [comment]
Hi @SergeantConfused thanks for your swift reply. I can't see an option like you have described, can you explain where this option is?

**Comment by beltsonata** [comment]
Never mind I found it and you are correct - somehow that had been switched on, which is odd as I thought I'd switched it off. Thanks again for your help!
