### ISSUE TITLE
Password generation: Avoid repetitions of symbols

### ISSUE THREAD

**Issue by dayfuaim** [bitwarden/browser#1939]
## Describe the Bug

During password generation in extension, very often password symbols are repeating for more than 2 times in one password. It decreases the security of password.

## Steps To Reproduce

1. Click on 'Password Generator'
2. Set:
   * Length = 14
   * all checkboxes are ON
   * Digits min. = 2
   * Symbols min. = 3
4. Click on 'Create new password'

## Expected Result

Random-looking password without repetition of any symbol.

## Actual Result

~2/3 cases: some symbols (characters, digits, specials) are repeating for 2+ times.

## Environment

- Operating system: N/A
- Browser: Every one, as I use extension.
- Build Version (go to "Settings" → "About" in the app): 1.51.0

**Comment by Greenderella** [comment]
HI @dayfuaim 

This is the intended behavior of a random password generator, sometimes characters get repeteaded. Adding constrains to that generation decreaces the strengh of the generated password.

**Comment by dayfuaim** [comment]
In other words, just click more "...and there will be given to you." ;)
I don't understand how getting rid of repetitions could _decrease_ the strength of password.

But OK, if it's intended.
