### ISSUE TITLE
Beachball on login in Firefox Developer Edition / 55.0b13 beta

### ISSUE THREAD

**Issue by mdellabitta** [bitwarden/browser#194]
Every time I log in on this browser, the extension beachballs for quite some time (2-3 minutes) before becoming available. Once this period finishes, it starts working normally; however, my preferred login period is less than 5 minutes for security reasons.

Running MacOS Sierra 10.12.6.

**Comment by kspearrin** [comment]
Probably has something to do with the decryption. How many logins are in the vault?

**Comment by mdellabitta** [comment]
466. 

I didn't see this problem in FF mainline or Chrome, if that's meaningful.

**Comment by kspearrin** [comment]
Yea, that's not a ton.

Can you run this benchmark in Firefox Dev Edition? Choose the Decrypt button.

Results are displayed in the console.


[benchmarks.zip](https://github.com/bitwarden/browser/files/1188687/benchmarks.zip)

**Comment by mdellabitta** [comment]
```Starting test: Decrypt  benchmarks.html:233:17
SJCL x 142,697 ops/sec ±1.85% (54 runs sampled)  benchmarks.html:275:21
Forge x 160,475 ops/sec ±7.67% (49 runs sampled)  benchmarks.html:275:21
WebCrypto x 7,342 ops/sec ±5.65% (45 runs sampled)  benchmarks.html:275:21
Fastest is Forge```

**Comment by kspearrin** [comment]
Hmm. That seems pretty standard then. Can you try the "Make Key" button?

**Comment by mdellabitta** [comment]
```Starting test: Make Key (PBKDF2)  benchmarks.html:142:17
SJCL x 29.17 ops/sec ±1.30% (36 runs sampled)  benchmarks.html:172:21
Forge x 20.52 ops/sec ±4.14% (35 runs sampled)  benchmarks.html:172:21
WebCrypto x 126 ops/sec ±2.34% (51 runs sampled)  benchmarks.html:172:21
Fastest is WebCrypto

**Comment by kspearrin** [comment]
That looks fine too. Can you debug the extension from `about:debugging` and see if anything crazy happening in the console?

**Comment by mdellabitta** [comment]
Nothing in the console. I tried to log in while a Performance profile session was running, and had for force quit. 

Did a sample from Activity Monitor prior to trying that Performance
 session, and came away with the attached file.

[Sample of FirefoxDeveloperEdition.txt](https://github.com/bitwarden/browser/files/1188746/Sample.of.FirefoxDeveloperEdition.txt)

**Comment by kspearrin** [comment]
Is there any issue when logging into the web vault?

**Comment by mdellabitta** [comment]
Nope, that seems to work fine.

**Comment by mdellabitta** [comment]
I'm seeing some weird behavior in trying to run the extension debugger with this. It seems like running the debugger "fixes it" in the sense that I don't have the problem in the extension once it's been through a profiling session. Given that this is a beta build, and I haven't tried to isolate this, so I can't say that it's not related to other extensions I'm using or things like Container Tabs, I'm thinking that I'll just close this issue and reopen later if it doesn't go away as Firefox updates and I can isolate it.

Thank you for your help!
