### ISSUE TITLE
In Chrome extension on macOS, can't edit entries unless I pop put extension into its own window

### ISSUE THREAD

**Issue by jikamens** [bitwarden/browser#1944]
## Describe the Bug

In current version of Google Chrome on macOS, try to add a URL to an existing entry in the extension window connected to the extension button. It doesn't work. Try to check or uncheck a collection checkbox to add an entry to an additional collection or remove it from a collection. It doesn't work. Like, you can't edit the text field, you can't make the checkbox change value. You can only edit if you pop up the extension so it's in a separate window. In that window editing works.

## Steps To Reproduce

1. Click on the extension icon in the Chrome window.
2. Click the view button on an entry.
3. Click Edit.
4. Click "New URI"
5. Try to click in the new URI text field to edit it. You can't.

Alternatively:

1. Click on the extension icon in the Chrome window.
2. Click the view button on an entry that is in the organization rather than your private vault.
3. Click Edit.
4. Click Collections.
5. Click on the collection checkboxes to try to toggle them on or off. You can't.

Now:

1. Click on the extension icon in the Chrome window.
2. Click the pop-out button to pop out Bitwarden into its own window.
3. Repeat the steps above and observe that you are able to make the edits.

## Expected Result

I should be able to edit entries in the window that's attached to the extension icon.

## Actual Result

I can't.

## Screenshots or Videos

I can't provide a video without revealing too much private information, unfortunately.

## Environment

- Operating system: macOS Big Sur
- Browser: Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- Build Version (go to "Settings" → "About" in the app): 1.51.0

**Comment by eliykat** [comment]
Does this happen on any other browsers, or just Chrome?
Does it make any difference whether the Chrome window is on your laptop monitor vs. an external monitor? If so, it may be #1854.

**Comment by jikamens** [comment]
I agree, I think this is #1854.
