### ISSUE TITLE
Can https://github.com/bitwarden/browser be used for Firefox Android?

### ISSUE THREAD

**Issue by Nihal247** [bitwarden/browser#1945]
This is not written for any issue. I want to ask if https://github.com/bitwarden/browser can be used for Bitwarden extension for Firefox Android to ask issues?

Thank you in advance.

**Comment by Greenderella** [comment]
Hi @Nihal247 

It can be used, but we recommend using the mobile app for mobile devices: https://bitwarden.com/help/article/getting-started-mobile/

**Comment by Nihal247** [comment]
Thank you @Greenderella
