### ISSUE TITLE
Unlock with Biometrics not working on Windows 10 21H1

### ISSUE THREAD

**Issue by Akirainblack** [bitwarden/browser#1946]
## Describe the Bug

Unlock with Biometrics not working on Windows 10 21H1.

## Steps To Reproduce

Install Bitwarden Desktop.
Enable unlock with Windows Hello.
Enable browser integration.
Add extension to Brave, Chrome, Edge and/or Firefox.
Attempt to enable unlock with Biometrics in any of the above browsers.

## Expected Result

Expected to enable Windows Hello to unlock.

## Actual Result

Says browser integration is not enabled.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/37367305/125162433-afb67a80-e17f-11eb-8ae2-4d19c3379a8e.png)

Showing unlock with Windows Hello and browser integration enabled as well as the error in brave.

## Environment

Windows 10 21H1, fully patched, clean install.
Bitwarden 1.27.1
Any of the latest browsers with browser plugin 1.51.1

## Additional Context

I have tested this on the same device running Windows 11 Insider preview and it works perfectly on that.

**Comment by SergeantConfused** [comment]
Hi @Akirainblack,

I just tested this using Bitwarden extension 1.51.1, Bitwarden desktop 1.27.1, Firefox 89.0.2 (64-bit), on Windows 21H1 19043.1083, and it worked as intended. I recommend you start with a clean installation and reconfigure everything according to this guide: https://bitwarden.com/help/article/biometrics/ and if you continue to encounter any trouble with this, please contact us using this form: https://bitwarden.com/contact/

Best wishes,

**Comment by eliykat** [comment]
Please follow the steps above and contact our customer success team on the link provided if you continue to have issues. If this is a bug that can be reproduced, this issue will be reopened with any additional information that customer success provides.
