### ISSUE TITLE
Creating an account never completes

### ISSUE THREAD

**Issue by gtklocker** [bitwarden/browser#195]
<img width="416" alt="screen shot 2017-08-04 at 13 26 10" src="https://user-images.githubusercontent.com/732062/28965211-a3328de0-7918-11e7-9746-ff0cbcbe101e.png">

**Comment by kspearrin** [comment]
@gtklocker Looks like some error happened (silently). Can you try again or look at the dev tools to see if something broke (error)?

**Comment by gtklocker** [comment]
@kspearrin Nothing shows up on devtools 😕 

<img width="843" alt="screen shot 2017-08-04 at 16 26 54" src="https://user-images.githubusercontent.com/732062/28970625-e8a7531a-7931-11e7-811d-82a734d33f21.png">

**Comment by kspearrin** [comment]
Dev tools work differently for extensions.

1. Inspect the actual popup.
2. Inspect the background page from chrome://extensions (enable developer mode)

**Comment by gtklocker** [comment]
You're absolutely right, I'm sorry about that.

Still nothing on the console though.

<img width="1680" alt="screen shot 2017-08-04 at 17 02 19" src="https://user-images.githubusercontent.com/732062/28971997-bcfd1cae-7936-11e7-9344-4be8635db01d.png">

**Comment by gtklocker** [comment]
Some errors do appear after a while, with the popup not visible anymore, but I don't think they're related to this issue.

<img width="847" alt="screen shot 2017-08-04 at 17 03 43" src="https://user-images.githubusercontent.com/732062/28972065-f380979c-7936-11e7-9d79-a6fe6bcf2132.png">

**Comment by kspearrin** [comment]
Can you look at the network tab? Does it try to call the API?

**Comment by gtklocker** [comment]
Nope, nothing.

**Comment by kspearrin** [comment]
Ok, there is definitely some JS error happening then. Can you try another password (that you do not use anywhere) and see if anything changes? If not, can you share the username and password combo with me (email to hello@bitwarden.com) and I can have a look?

**Comment by gtklocker** [comment]
I've tried multiple passwords/emails and none of them work. I also tried on a clean profile and had similar results.

You can try for example:
```
test@tester.net
12345678
```

Maybe it's a local issue? Let me try with Canary or Chromium and I'll edit this comment.

**Comment by gtklocker** [comment]
Same thing. Tested on:

* Chrome version: `60.0.3112.90 (Official Build) (64-bit)`
* Chromium version: `62.0.3177.0 (Developer Build) (64-bit)`

If I try to log in instead I can see the request on the Network tab and it works.

**Comment by kspearrin** [comment]
What if you register using our website?

**Comment by gtklocker** [comment]
Yup, that works. I can then login on the extension just fine.

**Comment by kspearrin** [comment]
That's really odd. Would you be available to debug the extension? I can walk you through it. Find me at https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
This is resolved in v1.14.3
