### ISSUE TITLE
Wrong autofill

### ISSUE THREAD

**Issue by Daniele122898** [bitwarden/browser#1954]
## Describe the Bug

I just moved from lastpass to bitwarden. I imported the csv file and it seemed to work all fine. But now i noticed that on every page when i click on bitwarden to autofill it seems to add a character somewhere in the password. Because the login is not correct, yet when looking at the password in bitwarden it seems to be the right one and typing it in manually works. 

So something seems to not properly work with the autofill?

## Steps To Reproduce

1. Open extension and click on autofill
2. Open extension and manually type in same password
3. Its now 1 character less

## Expected Result

Autofill should copy paste my password as it is without weird extra characters

## Actual Result

Wrong autofill

## Environment

- Operating system: Windows 10
- Browser: Chrome 91.0.4472.124
- Build Version 1.51.1

**Comment by Daniele122898** [comment]
I might have found smth out. It seems that when i copy the password it has a space in the beginning of the password. So maybe the csv import is broken and not the autofill itself? So should i move this bug to the frontend / server?

**Comment by eliykat** [comment]
Autofill definitely shouldn't add any characters, so my assumption here is that it's an import issue.

What happens if you open the item and view the password (click on the eye icon) or copy and paste the password (using Bitwarden's 'copy' button)? Does it have any extra characters? Make sure to check for whitespace.

**Comment by Daniele122898** [comment]
It seems to be an import issue so i will close this
