### ISSUE TITLE
Windows Firefox Extension: GUI Scaling/Length 

### ISSUE THREAD

**Issue by ngj5-beasTxx** [bitwarden/browser#1959]
## Describe the Bug

A recent update has made the Bitwarden menu interface incredibly short so more scrolling is required.

## Steps To Reproduce

1. Click the Bitwarden button on the toolbar and log in
2. Click the Bitwarden button on the toolbar and view the menu

## Expected Result

Longer menu interface as in the past with less scrolling involved.

## Actual Result

Short menu interface with lots of scrolling involved.

## Screenshots or Videos

![2021-07-16_13-22-01_firefox](https://user-images.githubusercontent.com/17461011/125986397-8987c688-a40d-4447-8f7f-5fd70d3a85c2.png)

## Environment

- Operating system: Microsoft Windows 10 Enterprise LTSC 2019 (x64)
- Browser: Mozilla Firefox 90.0 (64-bit)
- Build Version: 1.51.1

**Comment by eliykat** [comment]
I've seen this reported before [in this thread](https://github.com/bitwarden/browser/issues/1451). Can you try the fix in that thread?

> I found that the setting **privacy.resistFingerprinting** = `true` causes this behaviour. According to [privacytools](https://privacytools.io/browsers/#about_config) this should be set to `true` to achieve better online privacy. Setting this to the default of `false` resolved the issue for me.
>
> It is not totally unlikely that the extension [Privacy Settings](https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/) (that OP uses) modifies this advanced setting or some other setting which causes this behaviour of Bitwarden extension in Firefox.

**Comment by ngj5-beasTxx** [comment]
> 
> 
> This looks like a duplicate of #1451, so I'm going to close it. However, you can try the fix reported in that thread (see [this comment](https://github.com/bitwarden/browser/issues/1451#issuecomment-758723855)). Please continue any discussion over on #1451.

Thank you I attempted to search for this without any luck before opening up a new issue but this is most likely the same issue so I'll close it out for now!
