### ISSUE TITLE
No Master Password Reprompt from Search

### ISSUE THREAD

**Issue by jordanisaacs** [bitwarden/browser#1964]
## Describe the Bug

_Verify Master Password_ is not prompted when opening from search. It only prompts when it is on tab screen.

## Steps To Reproduce

1. Attempt to open an identity/card with re-prompt turned on from the tab page. (It will prompt you)
2. Search for the same identity/card (it won't prompt you)

or

1. Go to a website that has reprompt enabled
2. Tab page will prompt you
3. Search for password, it won't reprompt

## Expected Result

Opening from search requires master password.

## Actual Result

Does not require master password.

## Environment

- Operating system: Windows 10
- Browser: Microsoft Edge Version 91.0.864.70 (Official build) (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.5.1

**Comment by SergeantConfused** [comment]
Hi @jordanisaacs,

When you click on a vault item from the Tab page, you're initiating an Autofill action which would re-prompt for your master password, but when you're clicking on that same vault item from the My Vault or search results page, you're only displaying its details which does not require the master password; however, you would be re-prompted for the master password if you try to copy or view the password inside that vault item from that same page, for example.

I hope this clarifies everything up for you. Please do not hesitate to reply to this message if you have any questions.
