### ISSUE TITLE
TOTP codes not working in Edge extension

### ISSUE THREAD

**Issue by anstosa** [bitwarden/browser#1965]
## Describe the Bug

TOTP codes have stopped working in the browser extension

## Steps To Reproduce

1. Go to a site for which you have a TOTP code saved
2. Open the Bitwarden extension window
3. Note that the copy verification code shortcut is grayed out
4. View details
5. Note that there is no verification code listed
6. Edit the item
7. Note that the TOTP code is configured

## Expected Result

Bitwarden correctly generates TOTP codes for sites

## Actual Result

No codes are generated

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/568242/126354115-ec03cbe4-3015-4517-a163-c61ed244efc4.png)
![image](https://user-images.githubusercontent.com/568242/126354150-431f8f40-5961-4434-927d-aba4223a739d.png)
![image](https://user-images.githubusercontent.com/568242/126354495-8963a3f6-5457-4f5b-a614-955a87d61eea.png)

## Environment

- Operating system: Windows 10
- Browser: Edge 91.0.864.70
- Build Version: 1.51.1

**Comment by SergeantConfused** [comment]
Hi @anstosa,

1. Are any of your Bitwarden clients generating TOTP passwords?
2. Can you please check if your Premium features are still active, like so: https://bitwarden.com/help/article/billing-faqs/#q-how-do-i-find-out-what-subscription-plan-im-on ?

Thank you in advance,

**Comment by anstosa** [comment]
Yes, the Android client and web vault still generate TOTP codes correctly and my account is upgraded and in good standing.

**Comment by djsmith85** [comment]
I'm unable to repro this, same versions as stated above. I added the TOTP secret to my Github account item and it started generating codes immediatly after saving. The "copy TOTP" button is also enabled when visiting github.com and unlocking & opening the extension.

**Comment by anstosa** [comment]
After further testing it appears to be specific to the MS Edge. Same version working fine in Chrome

**Comment by anstosa** [comment]
Oh wait it's working now in Edge too... I have no idea what changed 🤷‍♂️

**Comment by Sulcalibur** [comment]
This has started to happen to me now `Version 103.0.1264.37 (Official build) (arm64)` Edge on Mac
