### ISSUE TITLE
Autofill does not work for textarea HTML tags

### ISSUE THREAD

**Issue by mr-manuel** [bitwarden/browser#1966]
## Describe the Bug
The autofill function do not fill out textarea HTML tags.

## Steps To Reproduce
Go to a QNAP NAS login page and let Bitwarden autofill the fields.

If you don't have a QNAP NAS go to: https://www.qnap.com/en/live-demo, start the demo and then logoff on the top right, to be able to login again and see the form.

Else here is the form code:

```HTML
<div class="anim-scale delay-2">
  <div class="field input-field">
    <span class="user-icon"></span>
    <textarea
      class="qStr"
      data-qstrph="LDAP_SERVER_STR12"
      id="username"
      autocomplete="off"
      placeholder="Username"
    >
    </textarea>
    <span class="reset-icon slice-img"></span>
  </div>
  <div class="field input-field">
    <span class="pwd-icon"></span>
    <input
      class="qStr"
      data-qstrph="QUICK04_STR09"
      id="pwd"
      type="password"
      autocomplete="off"
      placeholder="Password"
    />
    <span class="unmask-eye" style="display: inline-block;"></span>
  </div>
</div>
```
## Expected Result

The username field should be filled out.

## Actual Result

The username field is not filled out. Also a custom field is not working.

## Environment

- Operating system: Windows
- Browser: Microsoft Edge 46.3.24, Firefox 90.0.1, Google Chrome 91.0.4472.80
- Bitwarden Plugin: 1.51.1

**Comment by mr-manuel** [comment]
Refer to https://github.com/bitwarden/browser/issues/1621

**Comment by eliykat** [comment]
I can see you've already found the main issue for this. As we are trying to collate all our responses in one place, I'll close this issue per the standard response below.

I think that using `textarea` for login details is fairly unusual/nonstandard, but I see no reason why we couldn't support filling them using custom fields at least. If you add it to the Google Form in that issue, I'll look at it as part of the roundup.

---

Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by mr-manuel** [comment]
Hello @eliykat,

I submitted multiple times a request via the Google Forms, but unfortunately since months no update. Maybe do you have some informations?

**Comment by tshw3** [comment]
I have the same problem, would be awesome if its getting fixed :-), for know have a good day!

**Comment by eliykat** [comment]
@mr-manuel, no update unfortunately, however the Google Form remains the best place to submit any autofill issues (but please don't submit duplicates). Any updates will be posted in that thread.

**Comment by mr-manuel** [comment]
@eliykat are there some news?

Should it already work? I did some tests and unfortunately no change.

I found it here
https://github.com/bitwarden/clients/blob/7fe51f83daa38df15a105f4a917abd01d94eddd1/apps/browser/src/content/autofill.js#L434

but missing here
https://github.com/bitwarden/clients/blob/7fe51f83daa38df15a105f4a917abd01d94eddd1/apps/browser/src/content/autofill.js#L571-L573

**Comment by tshw3** [comment]
> @eliykat are there some news?
> 
> Should it already work? I did some tests and unfortunately no change.
/autofill.js#L571-L573

Good found, for me it is also not working yet. It would be really great if it is getting fixed.

**Comment by mr-manuel** [comment]
Now I copied the plugin, changed the lines by myself and it works with custom Bitwarden entry fields. Unfortunately I cannot create a pull request. Who can do this for me?

https://github.com/bitwarden/clients/blob/7fe51f83daa38df15a105f4a917abd01d94eddd1/apps/browser/src/content/autofill.js#L571-L573

```js
 var elsList = theDoc.querySelectorAll('input:not([type="hidden"]):not([type="submit"]):not([type="reset"])' + 
     ':not([type="button"]):not([type="image"]):not([type="file"]):not([data-bwignore]), select, textarea, ' + 
     'span[data-bwautofill]'); 
```


https://github.com/bitwarden/clients/blob/7fe51f83daa38df15a105f4a917abd01d94eddd1/apps/browser/src/content/autofill.js#L972-L973

```js
 var elements = Array.prototype.slice.call(selectAllFromDoc('input, select, textarea, button, ' + 
     'span[data-bwautofill]')); 
```

**Comment by eliykat** [comment]
I don't have any update for this one @mr-manuel, but you (or someone else) can submit a PR and it'll be reviewed by the team.

**Comment by mr-manuel** [comment]
@eliykat can you please review the PR, since it's only a small change?

**Comment by dbosompem** [comment]
Hi @mr-manuel , thank you for submitting a PR for this. The team will take a look at this and we will get back to you soon.

**Comment by mr-manuel** [comment]
Still no update?

**Comment by topmaxz** [comment]
good job! we are looking forward this, especially in textarea tag with special id (like username).
