### ISSUE TITLE
Enhancement: Change Master Password within extension

### ISSUE THREAD

**Issue by mchubby** [bitwarden/browser#197]
Hi there,

I'm not too comfortable sending the substitute master password unsalt-hashed over the web vault ui.

Could you make it possible to change the master password within the extension or app
 (sending both old and resulting hashes instead, and waiting for core acknowledgement)?

**Comment by kspearrin** [comment]
@mchubby 

I'm not sure what you are referring to. All master passwords are salted and hashed. It would be no different on the web vault vs browser extension.

**Comment by mchubby** [comment]
You have to input the password in a form field in the web version, right?
It transits over the wire, then it's salted.

**Comment by kspearrin** [comment]
All passwords and salted and hashed twice. Once locally before it goes over the wire and again when it hits the server and it stored. Read more here: https://help.bitwarden.com/article/password-salt-hash/

This process is the same in all apps.

**Comment by mchubby** [comment]
You are correct, I was misunderstood. The salt-hashing step occurs in the Angular JS code, which is executed client-side.

Can you confirm that in the event a 3rd party intercepts this identity token, by compromising the server, they can't use it to either

1. decrypt user data
2. replay it (pass-the-hash) to authenticate to web ui, change the master password and decrypt data

?

**Comment by kspearrin** [comment]
1. No, it is a hash of your password, so it has no value (one way). You need what it was before the hash which can only be achieved through brute force (which is the point of using PBKDF2).
2. You can reply it since it is the same, but again, since it cannot be used to encrypt or decrypt they would not be able to gain access to data in any way.

**Comment by mchubby** [comment]
Thanks, then the only weak spots are the scenarios where either the attacker captures the master pwd plaintext on the client (common to all pwd managers anyway), or if they manage to inject malicious client-side code in the web auth page?

Thank you very much for the prompt replies, I believe you may close this issue as won't-fix.

**Comment by kspearrin** [comment]
Yes, attack vectors will always exist if the client device is compromised.

Yes, they could, but if we are in this situation that would mean our servers are compromised and we would be restoring from backups anwyays.
