### ISSUE TITLE
Master Password Re-Prompt Checkbox

### ISSUE THREAD

**Issue by dickermoshe** [bitwarden/browser#1970]
## Describe the Bug

When filling in a new identity entry, clicking on the 'Learn More' question mark link by the 'Master password re-prompt' checkbox opens up this link in a new tab. 'https://bitwarden.com/help/article/managing-items/#protect-individual-items'
However this action closes the bit warden extension and the entry I was in middle in entering gets deleted.

## Environment

- Operating system: Windows 10
- Browser: Chrome 92.0.4515.107
- Build Version (go to "Settings" → "About" in the app): 1.51.1

**Comment by clayadams5226** [comment]
Hey @dickermoshe this is actually the expected behavior. When taking focus off of the extension it will close. As a work around you can pop the extension out by using the button in the top left corner.
