### ISSUE TITLE
Autofill is not working on Firefox Accounts Login Page

### ISSUE THREAD

**Issue by Loki-L1130** [bitwarden/browser#1976]
## Describe the Bug
Autofill is not working on https://accounts.firefox.com

## Steps To Reproduce

1. Go to https://accounts.firefox.com
2. Autofill using Browser shortcuts such as Ctrl + Shift + L or Click the respective Login Item in Tab page of the Extension.

## Expected Result

 Autofill the Item in Login Fields.

## Actual Result

 Item is not autofilled. Instead need to Copy and Paste.

## Screenshots or Videos

![Screenshot](https://user-images.githubusercontent.com/87981739/127604303-b61562cb-fbd8-4cbd-8e5d-786d8d09b0d4.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 90.0.2  
- Build Version : Browser Extension 1.51.1
## Additional Context

 Unable to Autofill even on Chromium based Browsers.

**Comment by Greenderella** [comment]
Hi @Loki-L1130 

The team is aware that some sites' login forms aren't been autofilled by our extension. This is something we are actively working on, so if you could please follow this link and complete the form: https://github.com/bitwarden/browser/issues/1621 that would help us a lot.

Thank you for your patience and understanding.

**Comment by Loki-L1130** [comment]
> if you could please follow this link and complete the form: #1621 that would help us a lot.

I do actually do not understand this. Could you please Elaborate ?

**Comment by kspearrin** [comment]
In this case, Mozilla deliberately disables Firefox browser extension content scripts from interacting from this webpage (since they own the browser, of course). Why? I am not sure, but there is no way to autofill this page in Firefox. Try Chrome, for example, and you will see it works just fine.

**Comment by eliykat** [comment]
I'm closing this because it's an issue with Firefox that is not within our control. Thanks to the team above for their prompt answers.
