### ISSUE TITLE
Failed to fetch error during extension login

### ISSUE THREAD

**Issue by mucolon** [bitwarden/browser#1977]
## Bug

Brave extension failed to sync with other device Bitwarden instances (Failed to fetch error). Removed Brave extension and downloaded again. Extension is now failing to login (Failed to fetch error).

Other device Bitwarden instances are working fine, issue seems isolated to the Brave browser.

## Screenshots

<img width="372" alt="image" src="https://user-images.githubusercontent.com/44480595/127631665-baea0e8b-33d6-4b56-b128-7809c1204084.png">

## Environment

- Operating system: Mac OS Big Sur 11.5
- Browser: Brave 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)
- Build Version: 1.51.1

**Comment by eliykat** [comment]
Thanks for getting in touch! We'd like to help you further - please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. This issue will be closed and moved over to our Help Desk.

You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/).

**Comment by poige** [comment]
Quite a useless response from bitwarden's employee…

@mucolon See https://github.com/bitwarden/clients/issues/1612#issuecomment-1116438789 that likely to fix it.

**Comment by dbosompem** [comment]
Hi @poige , @mucolon apologies if our initial response turned out unsatisfactory! Please look trough the suggested issue @poige referred to, and feel free to reopen if it doesn't help.
