### ISSUE TITLE
Pressing Enter in extension popup closes it in the latest Firefox Nightly

### ISSUE THREAD

**Issue by mariandomanik** [bitwarden/browser#198]
Using Firefox Nightly 57.0a1 (2017-08-04) (64-bit) on Windows 10 and bitwarden 1.14.2, I click on bitwarden icon, in the popup I enter my password to log in, press Enter, the popup closes without logging in. I have to manually click on "Log In". The same happens in Vault tab when I press Enter in the search field on the top.

I'm not sure if it's bitwarden issue or Firefox issue so I'll submit a bug to Mozilla if necessary.

**Comment by kspearrin** [comment]
This is definitely a Firefox issue as there is nothing unusual that we are doing here. Please open an issue with Mozilla.
