### ISSUE TITLE
"Tab" and "My Vault" not loading on Opera Extension (Windows 10)

### ISSUE THREAD

**Issue by SMontgomery** [bitwarden/browser#199]
Works fine in Chrome and Firefox but on Opera there is just a spinner on the Tab and My Vault tabs.  Tried logging out and back in, reinstalling the extension, restarting the browser.

![2017-08-06 20_41_55-extensions - opera](https://user-images.githubusercontent.com/1544664/29011427-d8225b54-7ae7-11e7-8754-1d353e4e5b12.png)

**Comment by jeroen7s** [comment]
that's weird, works perfectly fine for me, opera Beta on Arch Linux, still version 46 of opera, haven't updated to beta 47 yet

**Comment by kspearrin** [comment]
@SMontgomery This is because the opera extension is out of date. We submitted an update over a week ago but no reply form them on reviewing it yet.

**Comment by kspearrin** [comment]
New update is now live. Please let me know if there are any issues still.
