### ISSUE TITLE
Headers.set: Cannot convert argument

### ISSUE THREAD

**Issue by kNsja5w** [bitwarden/browser#1992]
When trying to sign in on the Firefox extension, the following error occurs: 

 "An error occurred: Headers.set: Cannot convert argument 2 to ByteString because the character at index 0 has value 65279 which is greater than 255."
 
It does NOT happen with the WebVault or the Safari-extension, my password is fine.

Update: After a reinstall of the Bitwarden extension, everything works like it should.

## Steps To Reproduce

1. Go to the Bitwarden Firefox-extension
2. Click on "Sign In"
3. Type in your email and password
4. Click on "Sign In"

## Expected Result

The user should be signed in

## Actual Result

Instead the error above appears

## Screenshots or Videos

<img width="353" alt="Bildschirmfoto 2021-08-03 um 10 29 10" src="https://user-images.githubusercontent.com/16246095/127986100-27a78cef-8624-4f8c-994e-65efcde0b350.png">

## Environment

- Operating system: macOS Big Sur 11.4
- Browser: Firefox 90.0.2
- Build Version 1.51.1

**Comment by Greenderella** [comment]
HI @kNsja5w 

Do you have any other extension running along Bitwarden? An ad-blocker/script-blocker/anti-malware or similar that could be interfering? 

Also, if you have already performed a clean installation of the extension by removing any leftover data ( https://help.bitwarden.com/article/where-is-data-stored-computer/) and the issue persist, I suggest you try to refresh your Firefox's profile following their instructions: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings 

Let us know how it goes.

**Comment by kNsja5w** [comment]
Thank you @Greenderella!

I do have extensions, but they all worked like a charm before, together with Bitwarden!
I also deactivated every extension and activated again after seeing none of the extensions causes the error.
Only a new installation of the extension helped.

**Comment by eliykat** [comment]
We don't have any wider reports of this bug at the moment so I'll close this as resolved.
