### ISSUE TITLE
The browser extension's window is black or dark grey in Safari.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1993]
## Describe the Bug
Opening the extension in Safari shows a black or dark grey window, and the interface is not visible.

## Steps To Reproduce
1. Install Bitwarden from the Mac App Store.
2. Enable the Safari extension.
3. Click on the extension's icon.

## Expected Result
To see the extension's interface.

## Actual Result
The extension's interface is completely black.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/73389600/128180419-a0a7a544-9f0c-4a72-a10b-abc17c2d7b61.png)

## Environment
- Operating system: macOS 11.5.1.
- Browser: Safari 14.1.2.
- Build Version: 1.27.1 (531) (Desktop).

## Additional Context
N/A.

**Comment by Mrperfec777** [comment]
linux firefox also been like this 2 weeks tried downgrading same issue , sidebar works but its inconvenient i like the drop down menu

**Comment by Hinton** [comment]
@Mrperfec777 would you be able to check if there are any errors in the console from the popup? Instructions on how to do so are available here, https://discourse.mozilla.org/t/how-can-i-inspect-the-popup-of-an-addon/34134. Which should make it easier to get an understanding of what went wrong here.

Thanks.

**Comment by MrNxbxdii** [comment]
ok thanks @Hinton

**Comment by djsmith85** [comment]
Hi @SergeantConfused , @MrNxbxdii , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
