### ISSUE TITLE
Bitwarden extension banner blinks on "save password" request

### ISSUE THREAD

**Issue by eduardoarandah** [bitwarden/browser#1997]
## Describe the Bug

When typing a new password, banner blinks making it super hard to click.

## Steps To Reproduce

Happens in:

1. Go to any login page
2. Enter details
3. See banner blinking

## Expected Result

A banner to click "save password"

## Actual Result

A banner blinking

## Screenshots or Videos

https://user-images.githubusercontent.com/4065733/128549298-d7c334b4-d427-4a22-a24c-fe642c6d90d1.mp4

## Environment

- Mac OS Big Sur
- Chrome 92
- Extension version 1.51.1
- No other extensions active

## Additional Context

No other relevant stuff

**Comment by eliykat** [comment]
Hi @eduardoarandah, we're aware of this issue and it's already been reported here: https://github.com/bitwarden/browser/issues/1243

As you can see from that issue, I've had a brief look into it but couldn't identify any obvious cause.

I'll close this issue as a duplicate, but please feel free to add any information or discussion to #1243.
