### ISSUE TITLE
When editing an existing login, changing the host doesn't update the UI

### ISSUE THREAD

**Issue by Impakt** [bitwarden/browser#1998]
## Describe the Bug
I have bitwarden on Chrome and Firefox. Sometimes when editing a URI for an existing login causes the UI to lag way behind what im entering. For example, I can press cmd+a to select the entire URI, and enter in a new one. However the UI doesn't show my changes until i tab out to another field.

## Steps To Reproduce

1. Open the Bitwarden Browser add-on
2. Click on an existing login item
3. Scroll down to URI 1 and edit the URI
4. Wait for the UI to update
5. If it doesn't, tab to the next field to see your changes.

![bitwarden uri bug](https://user-images.githubusercontent.com/1773489/128657411-a33af0b9-f992-409b-922b-8395ffc4e164.gif)

- Operating system: [e.g. Mac OS Big Sur 11.5.1]
- Browser: [e.g. 92.0.4515.131 (Official Build) (x86_64)]
- Build Version 1.51.1

**Comment by eliykat** [comment]
Hi @Impakt, this is a known issue affecting MacOS + external displays. Please see the issue here for further discussion and information: https://github.com/bitwarden/browser/issues/1854. I'll close this issue as a duplicate.
