### ISSUE TITLE
Autofill does not work properly on some sites

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#20]
Reports from reddit user Landy22:

- icloud.com -- unable to auto-fill username
  - iframe login form
- Fiverr.com -- unable to auto-fill password and username
  - Fixed
- mint.com -- unable to auto-fill password and username
  - Fixed
- stackexchange.com -- unable to auto-fill password and username
  - iframe login form

**Comment by kspearrin** [comment]
Report from user via email:

>https://mint.intuit.com/login.event?referrer=direct&soc=&utm=
>https://onlinebanking.tdbank.com/
>https://www.mygreatlakes.org/educate/login.html   [[User name does not get auto-filled ]]
>https://www.capitalone.com [[User name does not get auto-filled ]]

**Comment by kspearrin** [comment]
2b2794d will resolve many (all?) of the issues listed in this thread.

**Comment by itux420** [comment]
Hi, sorry to bring up old news but I have a website that is only accessible from within my organization's network where Bitwarden's extension is not auto-filling u/p on a the login form which happens to be located on a page loaded in an iframe. 

I am running the latest version of the Chrome extension (1.39.3) on the latest version of Vivaldi on Manjaro with the latest kernel. Wondering if there is anything I can do to get this iframe login form recognized by the Bitwarden extension? It does recognize the login form when not loaded in an iframe, by the way.

I realize that I have not provided a whole lot of information as I am not sure what (if any) info you would need to even begin to assist with this. However, if you need some details, let me know and I will happily provide. Thanks for your support and an awesome platform!
