### ISSUE TITLE
Context menu form filling choices not in the same order as in the extension popout

### ISSUE THREAD

**Issue by pannal** [bitwarden/browser#200]
As the title says. When I'm on a subdomain, where I have several entries for other subdomains of that particular domain, the extension popout correctly lists the one matching for the current subdomain at the top.

The right mouse click context menu doesn't, it seems to sort alphabetically.

**Comment by pannal** [comment]
OK, this should actually be split into two separate issues I've noticed.

#1: The context menu ignores the "favourite"-flag.
#2: In case of multiple stored logins for multiple subdomains on the same domain, BW should list the exact matching subdomain first. I'm not sure whether it should even list it before an entry with the favourite flag set.

#2 also applies to the extension popout.


@kspearrin do you want me to close this and create two separate issues?

**Comment by mhammond** [comment]
See also #107 - even with that fixed, I initially see the button's matching site list ordered correctly (ie, matching domain first) but do sometimes still see it ordered strictly alphabetically. I'm yet to dig into it, but either way, it seems the context menu should probably use the same sort semantics that issue introduced (possibly modified to take the favorite flag into account)

**Comment by pannal** [comment]
@mhammond I wasn't aware that you're involved with BitWarden, great to see! Are you the same mhammond as on starship-python?

**Comment by ctismer** [comment]
Sure he is - hi Mark!

**Comment by pannal** [comment]
Yeah, I'm the beardy offspring of that one.

**Comment by mhammond** [comment]
heh - small world @pannal and @ctismer - great to see you both again!

**Comment by kspearrin** [comment]
Can you check this now? There were some changes in recent versions to make this more inline.

**Comment by pannal** [comment]
Yes, it seems to work now. I'll keep an eye on it.
