### ISSUE TITLE
Unable to fill on firefox nightly

### ISSUE THREAD

**Issue by zer09** [bitwarden/browser#2004]
## Describe the Bug
Unable to fill login form on all site.

When I tried to fill the login form example amazon.com, it wont fill the fields.

## Steps To Reproduce
* Open amazon.com
* Click "Sign In"
* Open the Bitwarden icon on firefox extension
* Click the login details to fill the login form.
* The form is not fill out.

## Expected Result
The sign in form should be fill out.

## Actual Result
The sign in form is not fill out.

## Environment

- Operating system: Manjaro Linux KDE
- Browser: Firefox Nightly 93.0a1 (2021-08-11) (64-bit)
- Build Version: Version: 1.51.1

**Comment by maddler** [comment]
I can confirm the same issue.
Tried on both MacOS 11.5.1 and Ubuntu 21.04 with Gnome.
Addon version Version: 1.51.1.

**Comment by djsmith85** [comment]
This has already been reported with #2000 and has also been fixed. For more information please check #2000
