### ISSUE TITLE
Firefox Nightly - Right Click, autofill doesn't appear to work.

### ISSUE THREAD

**Issue by sciguyryan** [bitwarden/browser#2007]
As of about 2-3 days ago, right clicking and selecting "autofill" doesn't appear to work in the Nightly Firefox browser.

1. Unlock vault.
2. Right click on a login field in a saved web page.
3. Select Bitwarden -> Autofill

## Expected Result

The username and password should be autofilled.

## Environment

- Operating system: Windows 10
- Browser: Firefox Nightly - 93a1
- Build Version (go to "Settings" → "About" in the app): 1.51.1

## Additional Context

This is a significant issue as it renders a large part of the addon inoperable. The addon itself appears to function as expected. This issue appeared 2-3 days ago.

**Comment by djsmith85** [comment]
Hi @sciguyryan this has already been reported with #2000 and has also been fixed. For more information please check #2000
