### ISSUE TITLE
nested frame autofill does not work

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#201]
See this ridiculous website 🤷‍♂️ 

https://www30.mercantilbanco.com/olb/InitMerc?from=index

**Comment by eliykat** [comment]
This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
