### ISSUE TITLE
Auto-fill broken in Firefox Nightly

### ISSUE THREAD

**Issue by hlieberman** [bitwarden/browser#2011]
## Describe the Bug

Autofill has broken in FF Nightly.  Originally I had pointed to #1873 as the culprit, but reverting it has no positive effect.

The extension console now reports multiple instances of `Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:5704:15` when autofill is attempted to be used on any website, but I am not sure whether or not this is a red herring.

## Steps To Reproduce

1. In FF Nightly (93.0a1 (2021-08-12) (64-bit) at writing), add a login to Bitwarden on any website.
2. Navigate to the login page of that website.
3. Open the Bitwarden extension toolbox (`about:devtools-toolbox?id=%7B446900e4-71c2-419f-a6a7-df9c091e268b%7D&type=extension`) and navigate to the console.
4. Attempt to auto-fill the login by clicking on the site in the Bitwarden menu, by right-clicking and navigating to auto-fill, or any other way.
5. Observe the CSP errors in the browser extension console.

**Comment by luc-bw** [comment]
Hi @hlieberman 

This is fixed with #2001

**Comment by hlieberman** [comment]
That looks a likely culprit indeed!  Closing this as duplicate.
