### ISSUE TITLE
Autofill does not work in Firefox nightly 92.0a1 (21-08-13)

### ISSUE THREAD

**Issue by zoeronen** [bitwarden/browser#2012]
## Describe the Bug
The autofill feature, both from clicking the entry within the extension and from the right-click menu, does not work. I can still use all other aspects of the app and login successfully by copying the password.

## Steps To Reproduce
1. Install firefox-nightly or firefox-wayland-hg on an archlinux system rom the Arch User Repository
2. Install the Bitwarden extension from the official firefox store
3. Navigate to a website for which you have saved credentials in the vault
4. Click on the Bitwarden icon, click on the relevant login entry to autofill
5. Check if autofill suceeded

## Expected Result
You can also try autofilling with right-click -> Bitwarden -> Auto-fill. This should also fill both user and password fields automatically.

## Actual Result
For me, both methods don't work, just nothing happens and I am left with empty prompt fields.

## Environment

- Operating system: Garuda Linux (Arch based)
- Browser: firefox-nightly 92.0a1
- Build Version: 92.0a1.20210809093320+ha1a26ba25fbc-1

**Comment by djsmith85** [comment]
Hi @zoeronen this has already been reported and is being tracked under #2000
