### ISSUE TITLE
Autofill not working on Firefox Nightly 93 (Desktop)

### ISSUE THREAD

**Issue by selimsumlu** [bitwarden/browser#2013]
## Describe the Bug

Autofill feature of the Bitwarden Firefox extension hasn't been working for a week or so. I believe I began experiencing this on both of my PCs after the Nightly 93 release.

## Steps To Reproduce

1. Go to any login form with a saved login.
2. Click on the Bitwarden icon.
3. Click on an account to autofill.
4. Right click on a form field and try to autofill.

## Expected Result

Form should be filled upon either actions.

## Actual Result

Nothing happens.

## Environment

- Operating system: Windows 10
- Browser: Firefox 93.0a1 (2021-08-14)
- Build Version: 1.51.1

**Comment by djsmith85** [comment]
Hi @selimsumlu this issue has already been reported. For further information please check #2000 and #2001
