### ISSUE TITLE
Autofill does not work on ANY site on Firefox Nightly 93

### ISSUE THREAD

**Issue by shawnz** [bitwarden/browser#2014]
## Describe the Bug

Hi there, since upgrading to Firefox Nightly 93, autofill is no longer working on any site. No method of autofill works, whether I click the fill option in the toolbar button popup or if I use the right-click menu on the page. Downgrading to the latest stable version of Firefox, 91.0, fixes the issue.

## Steps To Reproduce

Try to use autofill on any site.

## Expected Result

The fields are filled.

## Actual Result

Nothing happens, with no error or otherwise. The toolbar button popup is dismissed like usual, and the username box becomes focused, but nothing is filled.

## Environment

- Operating system: Windows 10 21H1 19043.1165
- Browser: Firefox Nightly 93.0a1
- Build Version (go to "Settings" → "About" in the app): 1.51.1

Thanks, Shawn

**Comment by djsmith85** [comment]
Hi @shawnz this has already been reported and is being tracked under #2000 and #2001

**Comment by shawnz** [comment]
My apologies, thanks!
