### ISSUE TITLE
The Opera browser extension cannot be opened in the Opera browser's Sidebar.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#2015]
## Describe the Bug
When installing the Bitwarden extension on Opera, the Bitwarden icon flashes for a second in the Sidebar and then disappears, and the extension cannot be opened in Opera's Sidebar.

## Steps To Reproduce
1. Install the Bitwarden browser extension on Opera.
2. Pin it to the browser's toolbar.
3. Right-click on it.
4. Click on 'Manage extension'.
5. Deactivate it and re-activate it.

## Expected Result
For the Bitwarden extension to show up and remain in the Sidebar.

## Actual Result
The Bitwarden extension flashes for a second in the Sidebar, and then disappears.

## Screenshots or Videos
N/A.

## Environment
- Operating system: Windows 10 Pro 21H1 19043.1165.
- Browser: Opera 78.0.4093.147.
- Build Version: 1.51.0.

## Additional Context
N/A.

**Comment by djsmith85** [comment]
I can confirm this. For further information here's a thread from the community forum: https://community.bitwarden.com/t/bitwarden-extension-icon-disappeared-from-opera-developer-78-sidebar/30860

**Comment by tkossak** [comment]
Same here:

Bitwarden 1.51.0
Opera Version: 78.0.4093.147
System: Manjaro Linux (x86_64; XFCE)

**Comment by andreaheilrath** [comment]
Same here:

Bitwarden 1.51.0
Opera Version 78.0.4093.147
System: Windows 10 Pro Version 20H2

**Comment by KzBeck** [comment]
Same:
Bitwarden: 1.51.0
Opera: Version:78.0.4093.184
System: Windows 10 Pro

**Comment by djsmith85** [comment]
Based on this comment in the Community Forums: https://community.bitwarden.com/t/bitwarden-extension-icon-disappeared-from-opera-developer-78-sidebar/30860/11 I have just tested it with the current release of Opera and Bitwarden is shown in the sidebar and toolbar. Closing this now.
