### ISSUE TITLE
Firefox Beta/Nightly Login Issues

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#202]
I've had a few users report that firefox beta and nightly have issues with logging in. Need to investigate. Anyone else using those builds that can confirm any more information?

**Comment by Wilkolicious** [comment]
Hi @kspearrin I'm getting this problem where submitting my login details in the firefox extension does not do anything. 
On Windows 10 insider:
![image](https://user-images.githubusercontent.com/16191979/29241714-d5da140c-7f76-11e7-966c-29d5fa0d97e1.png)

On firefox nightly (was on 2017-08-11, but updated to 2017-08-12 in the last few minutes):
![image](https://user-images.githubusercontent.com/16191979/29241727-0a1de36a-7f77-11e7-836f-d29b36fcf82d.png)
![image](https://user-images.githubusercontent.com/16191979/29241742-45a1271c-7f77-11e7-8174-3d7a88791fb5.png)

Also using uBlock origin in case that is affecting it.

Please let me know if there's any other info you need.

**Comment by kspearrin** [comment]
I just installed nightly and was able to log in just fine. Weird. One thing I did notice is that in nightly the enter key always closes the popup so you have to actually use your mouse to click submit on the forms.

**Comment by Wilkolicious** [comment]
@kspearrin You're correct - I was expecting the enter button to submit the login details, but as you've stated, it simply closes the bitwarden popup.  Clicking 'Login' does indeed allow me to login.

**Comment by kspearrin** [comment]
Tracking here: https://bugzilla.mozilla.org/show_bug.cgi?id=1384078

**Comment by kspearrin** [comment]
It seems the enter key will always close the popup no matter what you are doing.

**Comment by vvuk** [comment]
Related -- for me, with Firefox 20170812100345 and extension 1.14.3, I don't have a "Login" button at all, and thus can't log in.  This shows up when I open the login panel:

```
XML Parsing Error: mismatched tag. Expected: </input>.
Location: jar:file:///C:/Users/home/AppData/Roaming/Mozilla/Firefox/Profiles/<salt>.default/extensions/%7B446900e4-71c2-419f-a6a7-df9c091e268b%7D.xpi!/popup/app/accounts/views/accountsLogin.html
Line Number 20, Column 23
```

**Comment by santagada** [comment]
clsoing the popup is probably the problem people are having, I had that twice after I figured out the bug just out of habit... :)

**Comment by kspearrin** [comment]
Closing this there is no issue with bitwarden here.
