### ISSUE TITLE
Vault web extension loads unlocked on fresh reboot.

### ISSUE THREAD

**Issue by Zagnaut1717** [bitwarden/browser#2029]
## Describe the Bug

On ArcoLinux, on fresh boot, when Firefox is opened, the vault extension is already unlocked.

## Steps To Reproduce

1. Reboot pc.
2. Open Firefox
3. The extension shows an unlocked vault
4. Upon clicking on the vault to open it, it is indeed unlocked.

## Expected Result

I would expect the vault to be locked until I unlock it manually as is the case on other systems.

## Actual Result

When Firefox loads you can plainly see by the toolbar icon the vault is unlocked.

## Environment

- Operating system: ArcoLinux
- Browser: Firefox 91.0.1 (64 bit)
- Build Version :Couldn't find one

## Additional Context
Seems to work correctly on a machine running Pop! os 20.04 Firefox 91.0.1.

I should also add that I don't log into Firefox on the ArcoLinux machine in question or do any syncing of settings.

**Comment by eliykat** [comment]
Hi @Zagnaut1717, what are your [vault timeout options](https://bitwarden.com/help/article/vault-timeout/) set to?

Do you have PIN unlock or Biometric unlock set?
