### ISSUE TITLE
"Unlock with biometrics" stopped working in Firefox add-on (Android)

### ISSUE THREAD

**Issue by pozyx** [bitwarden/browser#2031]
## Describe the Bug

"Unlock with biometrics" option is not present in Firefox add-on (Android).

## Steps To Reproduce

Go to add-on settings.

## Expected Result

"Unlock with biometrics" option present.

## Actual Result

"Unlock with biometrics" option not present.

## Screenshots or Videos

![Screenshot_20210823_123655](https://user-images.githubusercontent.com/15315056/130441194-5b4bc19a-4052-45c9-988b-38a552b1b877.jpg)

## Environment

- Operating system: Android
- Browser: Firefox  91.3.0
- Build Version: 1.52.0

**Comment by tgreer-bw** [comment]
Biometrics on Mobile only works on the mobile app. The Firefox addon biometrics are only applicable for Desktop browsers since it requires the Desktop application.

**Comment by pozyx** [comment]
Ah thanks, I was confused not realizing that Bitwarden app is auto-filling passwords in mobile Firefox, not the add-on - so biometrics works fine. I just realized I don't need the addon.
