### ISSUE TITLE
The browser extension in Wavebox does not recognize that 'Enable browser integration' is active in the desktop client.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#2032]
## Describe the Bug
Unlocking the browser extension using biometrics in the Wavebox browser does not work, because the extension states that 'Browser integration is not enabled' even though it is. 'Unlock with biometrics' works in Safari, Chrome, and Firefox on the same machine.

## Steps To Reproduce
1. Install Wavebox (https://wavebox.io/).
2. Install the Bitwarden browser extension on it.
3. Log into your Bitwarden account via the browser extension.
4. Attempt to activate 'Unlock with biometrics' (https://bitwarden.com/help/article/biometrics/).

## Expected Result
For the feature to become activated.

## Actual Result
The feature remains deactivated, and the error message states that 'Browser integration is not enabled'.

## Screenshots or Videos
N/A.

## Environment
- Operating system: macOS 11.5.2.
- Browser: Wavebox 10.92.21.2.
- Build Version: 1.52.0.

## Additional Context
Deactivating 'Run in all Cookie Containers' and activating 'Allow access to file URLs' in the extension's Settings has not effect.

**Comment by Thomas101** [comment]
Hi, I'm Tom from the Wavebox team. This is something we'd love to be able to add support for. Wavebox is a full-blown Chromium fork (not Electron, CEF etc) so the native messaging works in a similar way to Chrome, but Bitwarden will need to allow connections from the Wavebox binary and if placing a native messaging host file manually, will need to place this in the Wavebox directory.

If there's anything that's needed from our side so you can check the code signature of the binary or the native messaging paths for each platform, just let me know here or reach out to support@wavebox.io I'll be happy to pick it up there too.

Thanks!

**Comment by etuttle** [comment]
Hi, I'm a Wavebox customer and a Bitwarden customer.  I wanted to chime in with a +1 and _also_ ask that Bitwarden consider making the "allowed native clients" a configurable thing.  What if I had 10 chrome-based SSB's in .app form?  I would want the option of them all being able to connect.

PS, the way it breaks right now is super frustrating.  There is no clue to the average user why it isn't working (the whitelist in Bitwarden).

**Comment by Kirk-Ireson** [comment]
+1 and completely agree with @etuttle comments/suggestions.

**Comment by Hinton** [comment]
Hi, sorry for the late response.

We don't explicitly do anything to prevent other browsers from working with native messaging. We do however only configure the native messaging manifest for supported browsers. https://github.com/bitwarden/desktop/blob/master/src/main/nativeMessaging.main.ts#L173-L187

Many chromium variants like Brave fetch their manifest from  `~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts`. not sure how Wavebox works @Thomas101. Ideally Wavebox would look for manifests i the chrome directory as that would have the additional benefit of also providing compatibility with other extensions targeting Chrome with the NativeMessaging API.

Unfortunately with so many different browser flavors we can't really support every variant, our official list of supported browsers are available at https://bitwarden.com/help/article/getting-started-browserext/.

**Comment by Hinton** [comment]
@etuttle unfortunately there's not really a good way to make it configurable that works cross-platform. The Mac App Store desktop application is sandboxed and we have to explicitly ask permission to save/read files outside.

There are however a work-around which should work for most browsers. On Mac, identity where the browser stores the `NativeMessagingHosts` manifests, and copy the manifest from `~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts`. On Windows you will need to add the registry key to wherever it's expected.

**Comment by Thomas101** [comment]
Thanks for the info around this @Hinton! I've put a knowledge base together on our end (https://kb.wavebox.io/bitwarden/)  which explains how to copy the NativeMessagingHosts across manually. I'll speak with the team here to see if we can get Wavebox to grab these automatically

**Comment by Hinton** [comment]
Thanks for writing that up @Thomas101, I didn't really find any documentation of what directories Wavebox used. I think it would be great if you could also check the regular chrome directories since that would instantly add support for most extensions.

I'll see if we can get around to writing a help article on our side as well for non-supported browsers.
