### ISSUE TITLE
Autofill not working in Firefox

### ISSUE THREAD

**Issue by SinTan1729** [bitwarden/browser#2038]
## Describe the Bug

Autofill isn't working in Firefox Nightly. Nothing happens after selecting the entry.

## Steps To Reproduce

1. Go to some page with a login entry.
2. Click on the relevant login info in Bitwarden extension.

## Expected Result

The details should be filled.

## Actual Result

Nothing happens.

## Environment

- Operating system: Manjaro Linux
- Browser: Firefox Nightly 93.0a1 (2021-08-21) (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.52.0

**Comment by eliykat** [comment]
Hi @SinTan1729 , thanks for the bug report. This issue has already been reported here: #2000. A fix will be included in the next release (not the August release that just came out). Alternatively, you can:
* use a stable version of Firefox, or
* run a development build of the browser extension (which already has the fix) in Nightly

Please see #2000 for more discussion and information.
