### ISSUE TITLE
Browser plug-in slow-down on latest update (app1.52.1/svr1.42.2/web2.22.2)

### ISSUE THREAD

**Issue by benlenau** [bitwarden/browser#2046]
## Describe the Bug
Browser plug-in on Brave when pressed takes 3-5 secs loading before showing LOGINS. Before updating to version 1.42.2 this happend instantly.

## Steps To Reproduce

1. Click Bitwarden browser-shield plug-in (on whatever site)
2. Wait until LOGINS show up

## Expected Result
For login results to show instantly.

## Actual Result
Waiting 3-5 seconds before logins are shown.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/70938462/131231737-622d8215-601f-43f3-ac88-297aa23a01cf.png)

## Environment
- Operating system: Windows 10
- Browser: Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.52.1
- Bitwarden Server: v1.42.2
- Bitwarden Web: 2.22.2

**Comment by eliykat** [comment]
Hi @benlenau, is this delay affecting any other client?
Are there any relevant errors in the developer console (if you right-click the extension, click "Inspect" and then "Console")?
I take it that you're self-hosting. Do you have any errors in your server logs?

**Comment by benlenau** [comment]
@eliykat not affecting my iOS client and pure webclient only browser extention.
Nothing worth noting when inspecting via console - only 1 error "Failed to load resource: js-agent.newrelic.com/nr-1210.min.js:1" when testing on one site.
and 3 issues: "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown."

Where exactly do I find the server logs? (I've done docker logs < all bitwarden containers) to no avail.

**Comment by benlenau** [comment]
@eliykat something is definitely wrong. I found 6 bwdata/logs/notifications/Notifications/log_00x.txt-files which have a size of 112MB each, up from 4.4KB prior to the 27/8-2021.

**Comment by eliykat** [comment]
My suspicions were correct - it's this issue: https://github.com/bitwarden/server/issues/1531
I think the client is slow to load because the server is repeatedly trying & failing this operation, and writing logs to disk.
I'll close this issue as a duplicate, but if the issue persists after the server bug is resolved, we can reopen.

**Comment by benlenau** [comment]
> My suspicions were correct - it's this issue: [bitwarden/server#1531](https://github.com/bitwarden/server/issues/1531)
> I think the client is slow to load because it's waiting on the server, which is under excessive load (repeatedly trying & failing this operation and writing logs to disk).
> I'll close this issue as a duplicate, but if the issue persists after the server bug is resolved, we can reopen. In the meantime, please keep an eye on [bitwarden/server#1531](https://github.com/bitwarden/server/issues/1531) for any resolution.

Glad to hear that you are on top of things. Keep up the good work you do! :-)
