### ISSUE TITLE
Custom field autofill not work for hangseng.com

### ISSUE THREAD

**Issue by j16sdiz** [bitwarden/browser#2052]
## Describe the Bug

Custom field autofill not work for hangseng.com
Because the name/id is not unique 

## Steps To Reproduce

1. Go to https://e-banking.hangseng.com/1/2/logon?language=en
2. Enter a random username
3. Click on use password

## Expected Result

2nd password can be filled as well

## Actual Result
2nd password cannot be filled because id and name are not unique

## Screenshots or Videos
![hangseng](https://user-images.githubusercontent.com/31935/132097978-4c71c274-daaf-4d31-8200-88f208c70720.png)

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: Firefox
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. (Please note this feature also includes autofilling custom fields.) Please also direct any discussion or questions to that issue. This issue will now be closed.
