### ISSUE TITLE
Search function doesn't work for login notes and secure notes. Looks like #1552 is partially back

### ISSUE THREAD

**Issue by perariontaeadastra** [bitwarden/browser#2054]
## Describe the Bug
Search is broken for notes, both for in Logins and Secure Notes. Searched item can be found only typed full search word. Does not return partial results.
i.e. searching for **test** does not return items notes containing e.g. testusrname1 or testusername2 or test

Same issue can be found in the desktop version.
P.S.
Notes search in Android app stopped working altogether. No results from Notes returned as in issue #1552

## Steps To Reproduce

Create a new Login or Sec. Note containing words testusrname1, testusername2, tests in Notes field and then enter words test into the search field.

## Expected Result
Must return items, which notes fields contain search word even if entered partially.

## Actual Result
A whole word must be entered into the search filed in order to get correct search results.

## Screenshots or Videos
![sample-sec-note](https://user-images.githubusercontent.com/20157473/132135247-f3af6caf-7daf-4ac5-997f-35897e1d9dcc.png)
![test1](https://user-images.githubusercontent.com/20157473/132135244-f22a9f2a-dbfb-4840-8479-2830cba4eacf.png)
![test2](https://user-images.githubusercontent.com/20157473/132166129-536996a1-7bdc-4c04-94ed-1c6ab8a07327.png)
![search-result](https://user-images.githubusercontent.com/20157473/132135241-9ceac363-a594-4a84-a32e-3dc0fb708dec.png)
![BW_app](https://user-images.githubusercontent.com/20157473/132135497-3cd4baac-ab96-49cc-922c-c58017c34194.png)

## Environment

- Operating system: [Windows 10 Pro]
- Browser: [Brave, Chrome]
- Build Version - Both Latest
- Chrome extension version - Version: 1.52.1
- Widows app version - 1.28.2

**Comment by perariontaeadastra** [comment]
this is a serious bug. why is there no action on this report?

**Comment by perariontaeadastra** [comment]
I have checked search reasults from My Vault aka Bitwarden Web Vault and I see the same issue with search not working for partial search terms for Login Notes and Secure Notes.
Basically, search only works for exact search terms only.

![bw-test-item](https://user-images.githubusercontent.com/20157473/141330142-fa2d3fd5-39f6-4e14-95f1-84dd115e7554.png)
![bw-partial-myvault](https://user-images.githubusercontent.com/20157473/141330147-d281e203-dbfc-444f-941d-97571d7967aa.png)
![bw-full-myvault](https://user-images.githubusercontent.com/20157473/141330150-44846849-9092-4624-a3a0-1df71745690b.png)

**Comment by tomershvueli** [comment]
I'm now seeing this issue as well - is this feature working as intended?
