### ISSUE TITLE
Keyboard stops working after writing master password, until system restart.

### ISSUE THREAD

**Issue by opysium** [bitwarden/browser#2057]
## Describe the bug
Keyboard is disabling.

## Steps To Reproduce

1. Open Mozilla Firefox
2. Click on Bitwarden extension.
3. Write your master password.
4. Press enter.
5. Try to use your keyboard in anywhere in your computer (e.g notepad, address bar etc.)

## Expected Result
Keyboard expected to do what it's supposed to do.

## Actual Result
Can't input anything to anywhere.

## Environment

- Operating system: Windows 10
- Browser: Firefox 91.0.2 x64
- Build Version (go to "Settings" → "About" in the app): 1.52.1

## Additional Context
I made a simple search and in the last 30 days I saw some peoples had similar issues but they had these issues in macOS while in Windows I have this issue, for now I can only fix this problem by restarting my system.

**Comment by eliykat** [comment]
Seems similar to #1535, which reports a similar issue when autofilling.

Do you have any anti-virus software that could be interfering, such as Kaspersky? Some users in that thread said that disabling Kaspersky's secure input feature fixed this for them.

**Comment by opysium** [comment]
> 
> 
> Seems similar to #1535, which reports a similar issue when autofilling.
> 
> Do you have any anti-virus software that could be interfering, such as Kaspersky? Some users in that thread said that disabling Kaspersky's secure input feature fixed this for them.

Yeah I have Kaspersky and it's browser extension, I disabled secure input option. I'll continue using Bitwarden's browser extension and I'll keep this thread informed.

**Comment by opysium** [comment]
Looks like it's fixed, closing this issue.
