### ISSUE TITLE
TOTP not copied to clipboard

### ISSUE THREAD

**Issue by chrisirwin** [bitwarden/browser#206]
When logging on to a site with a configured TOTP key (example: github, to post this issue), the TOTP is not copied to the clipboard when the login information is filled.

I filled the login information both by clicking the site via main addon icon, as well as selecting the site via right-click context menu.

I have not tested via keyboard shortcut, as I am also affected by #179, preventing use of that feature.

**Comment by kspearrin** [comment]
This is currently a bug only in Firefox. A fix is already in place for the next version, however. More context here: https://github.com/bitwarden/web/issues/84

**Comment by kspearrin** [comment]
I'll leave this open for verification after next version goes out.

**Comment by kspearrin** [comment]
Looks like the fix did not work. Will have to investigate more to see if this is possible.

**Comment by Primokorn** [comment]
OK so I have just tested with a clean installation of Firefox (55.0.3) and Firefox beta (56.0.x).
It did work with Beta **only** so I guess we (FF stable users) just have to wait :)
Tested on Github.com.

**Comment by kspearrin** [comment]
I was able to find a workaround for this in Firefox, however, Firefox's requirements will only only it to work if autofilling from the "Current Tab" page in the bitwarden popup window. Autofilling from any other method (i.e. hotkey or context menu) will not permit access to the clipboard.

This fix will go out next release.

**Comment by Primokorn** [comment]
For the records, **dom.allow_cut_copy** must be set to true in **about:config** (Firefox).
Discussed with Osine as you know.

**Comment by kspearrin** [comment]
That setting is not required when autofilling from the popup window.

**Comment by Primokorn** [comment]
Yes but it prevents bitwarden to work properly if set to false.

**Comment by kspearrin** [comment]
Correct. This is required for autofilling from other areas. I guess this is some new flag? I was not aware of it before.

**Comment by kspearrin** [comment]
@Primokorn I can't find that flag in 57

**Comment by Primokorn** [comment]
@kspearrin actually it's a hidden pref so you can't see it by default.

**Comment by carlo** [comment]
@kspearrin Still can't get it to work (bitwarden 1.19.1 on Firefox 57.0b8 (64-bit)). Auto-filling or not, it just doesn't work.

Not sure what to do about the hidden pref but I think since the feature doesn't work correctly, this here issue should be re-opened.

**Comment by kspearrin** [comment]
@carlo Are you using autofill from selecting the login in the popup window or via hotkey? Currently it only works from the popup window in Firefox.

**Comment by andschwa** [comment]
It also does not work if it's auto-filled on page load (instead of manually triggered).

**Comment by kspearrin** [comment]
@andschwa Yes, this is intentional since autofill on page load may autofill something on a page when you are not actually going to log in. This could potentially wipe your clipboard when you did not intend it to. For this reason, TOTP copying is only done when explicitly autofilling from the UI.

**Comment by andschwa** [comment]
Ah, that makes sense, thanks for the explanation.

I think it would be advantageous for Bitwarden to streamline the auto-fill process for sites which always require a TOTP code, as I described in #492. If we can get TOTP auto-filling figured out, then we wouldn't need to auto-copy the TOTP code any more, eliminating the problems described in this issue.

**Comment by kspearrin** [comment]
Firefox won't let it happen. Can only use clipboard from popup window.

**Comment by Crocmagnon** [comment]
Could we then add a button to copy TOTP from the list?

**Comment by andschwa** [comment]
@Crocmagnon Please vote for that exact feature request: https://community.bitwarden.com/t/quick-copy-totp-code/38 😄

**Comment by Crocmagnon** [comment]
Already voted 😉 but thanks

**Comment by dpantel** [comment]
I cannot get TOTP to automatically copy in either Firefox (v66) or Chrome (v74) with the latest version of Bitwarden extension (v1.39.3).  I have tried filling in the login form via hotkeys and also by using the browser extension button.

**Comment by kspearrin** [comment]
@dpantel do you have a premium membership?

**Comment by dpantel** [comment]
@kspearrin I have a family organization

**Comment by kspearrin** [comment]
Does the item belong to the family organization or your personal vault?

**Comment by dpantel** [comment]
It belongs to the org.

I can manually get the code by drilling down into the BW extension menu. It also auto-copies to clipboard just fine in the iOS app.

**Comment by kspearrin** [comment]
@dpantel Should be fixed in next version with 92fb43fc2e92609c7b8264e2c4d3f4137ce66013 . Thanks.

**Comment by dpantel** [comment]
Thanks!
