### ISSUE TITLE
Dropdowns broken in FF on Fedora

### ISSUE THREAD

**Issue by ataraxia937** [bitwarden/browser#2068]
### Steps To Reproduce

1. Go to any dropdown element in the Firefox addon. For example, "Vault Timeout" or "Vault Timeout Action" in the settings.
2. Click on the dropdown.

### Expected Result

1. The dropdown should allow me to choose a value.

### Actual Result

1. The dropdown is completely inert and does nothing, as if it were a label.

### Additional Context

Debugger console shows these. I'm not knowledgeable and they may be irrelevant.

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://47777675-5c08-4b9a-951c-27ea247330e2/vendor.js
Source Map URL: ObjectUnsubscribedError.js.map

Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

### Operating System

Linux

### Operating System Version

Fedora 34

### Web Browser

Firefox

### Browser Version

91.0.2

### Build Version

1.52.1

**Comment by ataraxia937** [comment]
I updated to Firefox 92.0 today and there is no change.

**Comment by trevorbayless** [comment]
I am seeing this issue as well with Fedora 34. The dropdowns _do_ work however if you press the button at the top left to pop out bitwarden to a new window.

**Comment by nunocastromartins** [comment]
I'm seeing the same on  Firefox 92/Fedora 34. I believe Fedora ships a patched version of Firefox with Wayland support enabled by default, that might be the issue.

The dropdowns also work when using Bitwarden from the sidebar (`Shift+Alt+U`), so they only seem broken on the "regular" extension popup.

**Comment by person1234-ux** [comment]
Also having this issues

**Comment by Hinton** [comment]
There is an open issue in bugzilla which seems similar to this issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1729912. Unfortunately there's not much we can do on our side, the dropdowns in the browser extension are standard html elements which we cannot manipulate freely.

**Comment by major-mayer** [comment]
Works with the latest Firefox Nightly for me (96).
