### ISSUE TITLE
Bitwarden fills kraken login wrongly

### ISSUE THREAD

**Issue by pannal** [bitwarden/browser#207]
When clicking autofill on kraken.com, Bitwarden fills the username field correctly, but both the password and the TOTP field with the configured password instead of the password and the current TOTP key.

**Comment by kspearrin** [comment]
@pannal bitwarden does not currently support autofilling TOTP codes. You need to paste it in after autofilling. It's getting the field confused because the website authors have marked that input as a password field.

**Comment by pannal** [comment]
OK. An option to do that via the extension or the field-right-click would be nice.

**Comment by kspearrin** [comment]
The TOTP is automatically copied to your clipboard whenever you autofill. You just need to paste.

**Comment by pannal** [comment]
My bad. A popup with that information would help :)

**Comment by pannal** [comment]
With the latest update and the auto-fill-on-page-load-feature it doesn't copy the TOTP key to the clipboard anymore, only when manually auto-filling. Is that intended?

**Comment by kspearrin** [comment]
Yes, we don't want to overriding your clipboard that often without you knowing.

**Comment by pannal** [comment]
OK, would it be possible to add the TOTP copying feature additionally, so I can use it after auto filling? Like in the context menu or as a hot key?

**Comment by kspearrin** [comment]
Possibly, but our context menu is already getting a bit crowded. Closing this issue since the original discussion was resolved.
