### ISSUE TITLE
Bitwarden does not show as a Safari Extension to enable on the extension pane

### ISSUE THREAD

**Issue by handletastic** [bitwarden/browser#2077]
### Steps To Reproduce

1. Go to 'Safari'
2. Click on 'Safari > Safari Extensions...'
3. Search for 'Bitwarden'
4. Click on 'Get'
5. Click 'Open'
6. Successfully log in
7. Open 'Preferences' on Bitwarden
8. Click on 'Enable browser integration'
9. Click on 'Require verification for browser integration'
10. Open Safari
11. Open 'Preferences' on Safari
12. Click on 'Extensions' pane on Safari's 'Preferences'

No Bitwarden extension is listed on the available extensions.

### Expected Result

To have the Bitwarden extension available on the list of Extensions on the Safari's Preference pane

### Actual Result

The Bitwarden extension is not available on theist of Extensions on the Safari's Preference pane

### Screenshots or Videos

<img width="296" alt="image" src="https://user-images.githubusercontent.com/16025440/133909864-835918ae-2d4a-4cf8-8f1d-c5b7f9dfe684.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/16025440/133909873-5107df66-ef88-4f5d-8e0d-b41196862866.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/16025440/133909880-04aa46b9-424a-46c4-a23c-ace0fd692aa8.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/16025440/133909886-87b96ea2-3951-47ce-ba44-2361dfcfe7f4.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/16025440/133909892-62fafb41-5691-4b49-8dbb-be027df8778f.png">
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/16025440/133909952-1a55f3e4-ca5b-45c9-bea9-5ba0db003eed.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/16025440/133909961-ba2e0866-14ff-4b7b-852f-5f8047af33f3.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/16025440/133909963-ac49658c-d0a9-4ccc-8110-50b31aa06f85.png">

### Operating System

macOS

### Operating System Version

Version 11.5.2 (20G95) (Big Sur)

### Web Browser

Safari

### Browser Version

Version 14.1.2 (16611.3.10.1.6)

### Build Version

Version 1.28.2 (534)

**Comment by SergeantConfused** [comment]
Hi @handletastic,

Please create a new support ticket for this using the form here: https://bitwarden.com/contact/ so we'd be able to assist you.
Also, please note that this matter is being tracked here: https://github.com/bitwarden/browser/issues/1696 and you are more than welcome to try the workarounds that are discussed in that thread.

I hope you find this helpful, and I thank you in advance for your understanding.
