### ISSUE TITLE
Popups in popover are not displaying in the correct position

### ISSUE THREAD

**Issue by DarkArc** [bitwarden/browser#2079]
### Steps To Reproduce

Trigger any popup or copy a password.

### Expected Result

The master password reprompt and "password copied" notification banners appear in their correct positions.

### Actual Result

I'm seeing the password reprompt appear like this:

<details>
<summary>Current Situation (1.53.0)</summary>

![Untitled](https://user-images.githubusercontent.com/778012/134819912-2e75a5e9-00aa-4285-8f11-4ab3fe9adbdd.png)

</details>

<details>
<summary>Original Image (1.52.0)</summary>

![image](https://user-images.githubusercontent.com/778012/134025945-42457ee9-c90c-42cf-b918-2b1c6c9d6817.png)

</details>
The "password copied" and notification banners of the same ilk don't display at all (presumably they're so far off the screen).

### Additional Context

If displayed as a window this does not happen, and things appear in the correct positions.

### Operating System

Linux

### Operating System Version

Fedora 34

### Web Browser

Firefox

### Browser Version

92.0 - X11

### Build Version

Can't see - also broken. Extensions page says 1.52.1 (EDIT: Extension also shows this when checking via a window where things still work).

**Comment by Hinton** [comment]
This seems related to the fact FF is patched to support Wayland on Fedora, mentioned in https://github.com/bitwarden/browser/issues/2068. Could you verify if the popup behaves as correctly if you pop out the extension? (The icon in the top left corner)

**Comment by DarkArc** [comment]
This is running under X11 so I'm not sure why Wayland patches would be a factor. I can take this to red hat though if that's the conclusion.

**Comment by Hinton** [comment]
@DarkArc Hmm, I assumed it was related to the Wayland issue in the other issue but if it's running under X11 it might not be.

Would you be able to test the issue using official Mozzila binaries to conclude if it's a Fedora specific patch that causes it? https://fedoraproject.org/wiki/How_to_debug_Firefox_problems#Testing_Mozilla_binaries

**Comment by DarkArc** [comment]
This does seem to be related to Fedora patching. I cannot reproduce this on Mozilla binaries with Bitwarden 1.53.0 (though it's still broken in 1.53.0 using Fedora packages).

**Comment by DarkArc** [comment]
Reported upstream at: https://bugzilla.redhat.com/show_bug.cgi?id=2007985

@Hinton I'll let you decide whether to close this or not; might be easier for people to find if left open, but this does not appear to be _your_ bug.

**Comment by Hinton** [comment]
@DarkArc Thanks for verifying using the official binaries, will keep this open to avoid duplicate bug reports.

**Comment by DarkArc** [comment]
This has been fixed as of Fedora's update to Firefox 95.
