### ISSUE TITLE
[Firefox Desktop] Lock Options "On Lock" setting does not work on Firefox for Windows 

### ISSUE THREAD

**Issue by viertaxa** [bitwarden/browser#208]
The "Lock Options" "On Lock" setting does not work on Firefox for Windows. Chrome is working great. Version information below:

Bitwarden version from "about" screen: Version 1.14.3
FF version: 55.0.3

Windows version: Windows 10 x64 10.0.15063 Build 15063

**Comment by kspearrin** [comment]
This is because Firefox does not support On Locked. See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/idle/onStateChanged

We should probably hide the option.

**Comment by viertaxa** [comment]
I figured as much. Is there a Firefox bug open to support this? Seems like a nice security feature. I do agree that hiding the option in the FF extension is the best bet for now.

**Comment by viertaxa** [comment]
Not sure if I have done this correctly on FF's end, but I have attempted to create a bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1395199

**Comment by kspearrin** [comment]
The option has been hidden for next release.
