### ISSUE TITLE
Safari extension breaks login page of Terraform Cloud (app.terraform.io)

### ISSUE THREAD

**Issue by jaredm-oi** [bitwarden/browser#2082]
### Steps To Reproduce

With Safari Bitwarden extension enabled,

1. Go to https://app.terraform.io/session
2. Click on Bitwarden extension icon and select login to fill user name and password
3. Click on the web page's "Sign in" button

### Expected Result

I will be logged in to Terraform Cloud, after a 2FA challenge if enabled.

### Actual Result

The page does nothing after you click on "Sign in".

### Additional Context

The problem does not occur when the Bitwarden extension is disabled.

### Operating System

macOS

### Operating System Version

Big Sur 11.6 (20G165)

### Web Browser

Safari

### Browser Version

15.0 (16612.1.29.41.4, 16612)

### Build Version

1.53.0

**Comment by eliykat** [comment]
I've tested this and it appears to be an autofill issue. Sometimes autofill can accidentally override some hidden fields (e.g. catpcha) and therefore invalidate the form when you submit it.

Autofill issues affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. You can include a link back to this issue. Please also direct any discussion or questions to that issue. This issue will now be closed.
