### ISSUE TITLE
Firefox dual screen setup shows only part of the interface

### ISSUE THREAD

**Issue by taro-ball** [bitwarden/browser#2085]
### Steps To Reproduce

With two monitors setup (e.g. a laptop with connected monitor). When Firefox window is on the second screen when I click on bitwarden icon it shows only small part of the extension interface. 

### Expected Result

The extension interface shows normally on both screens

### Actual Result

When Firefox window is not on the main screen when I click on bitwarden icon it shows only small part of the extension interface. 

### Screenshots or Videos

on second screen:
![image](https://user-images.githubusercontent.com/22948157/134825345-f11d1ca5-72e7-46de-a601-76310823ab60.png)

on main screen:
![image](https://user-images.githubusercontent.com/22948157/134825356-4639d60e-ca9e-4f2c-97a5-815348002972.png)

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

latest

### Build Version

Version: 1.48.1

**Comment by eliykat** [comment]
Can you try disabling fingerprinting and see if that fixes the issue, as discussed in this thread? https://github.com/bitwarden/browser/issues/1451

**Comment by taro-ball** [comment]
In my case privacy.resistFingerprinting is set to false. Also, it works fine on the other screen, only the secondary screen is affected. 

This behavior persists on different computers with different versions of FF installed.

**Comment by eliykat** [comment]
I'm not sure then, it may have to wait for further analysis. Does it occur with other browsers? (e.g. Chrome or Edge)

**Comment by taro-ball** [comment]
No, it only affects FF. other browsers on the same PC work fine.

**Comment by taro-ball** [comment]
Just noticed this affects FF's own menu too, so probably it's the FF issue

**Comment by BigSaveDave** [comment]
Is it a laptop or small form factor screen? MY extension wasn't working on my laptop screen if it 1.) wasn't the main monitor and 2.) zoomed to 125%. If neither of these conditions occurred, it was fine. However, my 22 inch monitor had neither of these issues. It's worked on the 22in monitor being zoomed and not the main.

**Comment by Hinton** [comment]
Are the monitors using different resolution scaling? And if so does setting it to 100% on both resolve the issue (after restarting firefox)
![image](https://user-images.githubusercontent.com/137855/146191069-3c512cb5-1e85-413f-bca5-d15e033b28ea.png)

**Comment by djsmith85** [comment]
Hi @taro-ball, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
