### ISSUE TITLE
BSD/MIT License?

### ISSUE THREAD

**Issue by psmit** [bitwarden/browser#21]
Hi,

What are your future plans with Bitwarden? Are you planning to turn it into a company?

If not, would you consider relicencing (or dual licencing) with a BSD/MIT style licence? The reason I ask this at this moment is that it is easiest to do this before any other contributors get involved.

**Comment by kspearrin** [comment]
The project is already owned and operated as a business entity, 8bit Solutions LLC, not by me personally so technically it already is a business. I am not really an expert on licensing at the moment and will likely be consulting with some legal council on it soon to get a better understanding of where it needs to be. If you would like to discuss these issues further we can take it offline. You can contact me through the form on the main website. Thanks.
