### ISSUE TITLE
New item doesn't show up

### ISSUE THREAD

**Issue by ristein** [bitwarden/browser#2124]
### Steps To Reproduce

I don't think this is reproducable, just happened once
This is what I did:
1. Created new entry on Brave (Chrome) Extention # 1 on Desktop
6 days later...
2. opened Brave (Chrome) Extention # 2 on Laptop
3. Couldn't find my entry
4. Opened phone (Android), entry is there

### Expected Result

find entry on Laptop too

### Actual Result

no item

### Additional Context

after renaming on phone and a manual sync on laptop, the entry appeared. Last auto sync had been just before

### Operating System

Windows

### Operating System Version

win10 21H1

### Web Browser

Brave

### Browser Version

Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)

### Build Version

1.53.0

**Comment by Greenderella** [comment]
Hi @ristein 

If you observe that the vault is not in sync, you may want to go to Settings > Sync > SYNC VAULT NOW. If the vault still does not appear to sync, please log out and re-login.
