### ISSUE TITLE
Copying from password generator copies additional whitespace

### ISSUE THREAD

**Issue by tangowithfoxtrot** [bitwarden/browser#2130]
### Steps To Reproduce

1. Go to the Password Generator tab.
2. Triple-click the generated password to select all. 
3. Copy and paste the password in to a text editor. 

### Expected Result

The password is copied exactly as it appears. 

### Actual Result

The password is copied with added whitespace at the end. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5676771/137795634-06a69f1c-1394-4c25-9138-0d75ac2e8b5c.png)

### Additional Context

This is not an issue on macOS. Whitespace does not get copied this way. 

### Operating System

Windows

### Operating System Version

21H1

### Web Browser

Chrome

### Build Version

1.53.0

**Comment by eliykat** [comment]
Closing as a duplicate, thanks @hey24sheep.
