### ISSUE TITLE
[Suggestion] Don't let browsers remember 2FA

### ISSUE THREAD

**Issue by amdelamar** [bitwarden/browser#215]
**When:** When logging into Bitwarden with 2FA.

**What:** Web browsers will provide friendly autofill for forms that you've previously submitted before. This is annoying for 2FA codes because they can't be reused ever (hopefully) again.

**Fix:** Use some HTML attributes to tell browsers to forget input for this form.

```html
<input type="text" required autofocus autocapitalize="off" autocorrect="off" autocomplete="off" />
```

> Note: autofocus is optional, but its very nice to smooth the user experience.

**Comment by kspearrin** [comment]
Done for next release.
