### ISSUE TITLE
Safari Web Extension does not appear

### ISSUE THREAD

**Issue by sargunv** [bitwarden/browser#2154]
### Steps To Reproduce

1. Install Bitwarden from Mac App Store on the new 2021 MacBook Pro
2. Log in to Bitwarden and in preferences, enable browser integration
3. Open Safari preferences to the extensions tab
4. Look for Bitwarden in the extensions list

### Expected Result

Bitwarden should appear in the extensions list.

### Actual Result

Bitwarden does not appear in the extensions list.

### Screenshots or Videos

<img width="1292" alt="Screen Shot 2021-10-29 at 17 15 11" src="https://user-images.githubusercontent.com/1320357/139513362-3c52bfdf-5c40-4946-85d9-8bd6b69e2221.png">
<img width="1062" alt="Screen Shot 2021-10-29 at 17 15 41" src="https://user-images.githubusercontent.com/1320357/139513361-32e600ff-af98-4ac2-ac7e-2f457dd0276d.png">
<img width="904" alt="Screen Shot 2021-10-29 at 17 16 05" src="https://user-images.githubusercontent.com/1320357/139513360-9b9e9dee-2ab5-47cb-b712-26d59e1cc42f.png">

### Additional Context

I'm on the new Apple Silicon MacBook Pro (14-inch, 2021). This bug doesn't appear on my 2019 Intel MBP 13".

### Operating System

macOS

### Operating System Version

12.0 (Monterey)

### Web Browser

Safari

### Browser Version

15.0 (17612.1.29.5)

### Build Version

The desktop app is on version 1.29.0 (1790)

**Comment by shubhpatel** [comment]
Same here.
M1 Macbook Pro
Mac OS 12.0.1 (21A559)
Bitwarden 1.29.0 (1790)

**Comment by tgreer-bw** [comment]
This was addressed and submitted to the app stores - should be available as an update soon!

https://github.com/bitwarden/desktop/issues/1126

**Comment by sargunv** [comment]
Installed the update (v1.54.0) and it's now working!
