### ISSUE TITLE
Autofill on page load not working for a site

### ISSUE THREAD

**Issue by streetwolf** [bitwarden/browser#216]
Go to https://shopriteweb.rxtouch.com/shoprite/web and click on the 'Sign In' button at the top right. Create a dummy login in BW.  After doing so go to the page again and notice that it doesn't autofill on page load.  However, you can still fill it in by opening the BW menu and clicking on the entry for the site.  This is the only site I found so far where autofill on page load doesn't work.

**Comment by streetwolf** [comment]
I forgot to mention that I already had a login defined for the site in BW.  As a further test I deleted the login in BW, restarteed Fx and went back to the sign in screen.  I entered my username and password manually but was never offered to save the login info in BW.  I had to make the login in BW manually. Again, the login screen didn't do an autofill on page load.  I suspect the two are related.

**Comment by kspearrin** [comment]
Yea, that's just another site with a very unconventional login form. Not sure what I can do.

**Comment by streetwolf** [comment]
Why is it I can fill the login form by clicking on the site in my BW menu?  Can't you use the same method to autofill the site?  There are other sites where autofill and clicking on the site in my BW menu doesn't work.  For these sites I have to copy the username and/or password.  When using LastPass I used to create a custom form for these type of sites which seemed to work OK.  Will this be a feature in BW in the near future?

**Comment by kspearrin** [comment]
I see. This is because there is no login form on the page when it initially loads. That website does not invoke any navigation events when clicking the sign in links, so bitwarden doesn't know to try to autofill again. Notice that the website's address does not change when you click sign in, or if you refresh the sign in page, you end up back on the home page.

**Comment by kspearrin** [comment]
Nothing we can really do here. Closing.
