### ISSUE TITLE
Dropdown menus doesn't work

### ISSUE THREAD

**Issue by redudant-overflowing** [bitwarden/browser#2167]
### Steps To Reproduce

Click in any of the dropdown menus doesn't work. They only work if the user switch to the Xorg session.

### Expected Result

The dropdown menus doesn't work in Wayland, just in Xorg. A workaround is to press the "open in a window" button at the top left and the dropdown menus will work.

### Actual Result

The dropdown menus should work.

### Screenshots or Videos

https://user-images.githubusercontent.com/93951203/140954927-eefe93c7-d51b-4402-acc2-c7d003b8ef8d.mp4

### Operating System

Linux

### Operating System Version

Fedora 35 (with Wayland session). However, the bug doesn't happen in Xorg.

### Web Browser

Firefox

### Browser Version

94.0

### Build Version

1.54.0

**Comment by eliykat** [comment]
This is a known issue that is being tracked in #2068. I'll close this as a duplicate, but please add any additional information in that thread.
