### ISSUE TITLE
Popups appear at the bottom right corner of the Bitwarden flyout

### ISSUE THREAD

**Issue by redudant-overflowing** [bitwarden/browser#2168]
### Steps To Reproduce

Go to Settings > About. 

Note: It's not just the about popup, but all of the popups. Seems to be a random issue.

### Expected Result

Popups should appear in the middle of the Bitwarden flyout.

### Actual Result

Popups appear at the bottom right corner of the Bitwarden flyout.

### Screenshots or Videos

https://user-images.githubusercontent.com/93951203/140955859-df243317-9fd6-4f5e-b23b-6d7a8fe08846.mp4

### Additional Context

- I'm using Wayland, but this bug also happens in Xorg.
- A workaround is to press the "open in a window" button at the top left and the popups will appear correctly.

### Operating System

Linux

### Operating System Version

Fedora 35

### Web Browser

Firefox

### Browser Version

94.0

### Build Version

1.54.0

**Comment by eliykat** [comment]
This is a known issue that is being tracked in https://github.com/bitwarden/browser/issues/2079. I'll close this as a duplicate, but please add any relevant information in that thread.
