### ISSUE TITLE
save button of the save-password-bar is chopped off

### ISSUE THREAD

**Issue by MoonShade** [bitwarden/browser#217]
Even after the merge of #205 the bar at the top of the browser asking you to save a password being not tall enough seems to be an issue. The "save" button will only be somewhat half visible. Additionally, a scroll bar for this iframe is visible on the right.

![Image of bar being too small](https://i.imgur.com/xcEBF5V.png)

The scroll bar does disappear with a height of 52px for the iframe

![Image of a bar with a height of 52px](https://i.imgur.com/0U88E1H.png)

Tested with:
latest master branch
on Vivaldi (1.11.917.43)
on Linux (Ubuntu Gnome 17.4)
this doesn't change when you change the width of the browser

**Comment by pitrou** [comment]
Got the same problem here. It seems that hardcoding the frame size can be fragile, as text height can vary depending on the user's preferences, and also the actual font used (users with sight issues may for example configure a much larger font size).

**Comment by kspearrin** [comment]
@pitrou  Problem here is that the frame height has to be hard coded. Maybe we need to add some responsive design support and use abbreviated labels on the buttons to make them smaller.

**Comment by pitrou** [comment]
Is there way to avoid mutating the current page, i.e. have some kind of pop-over instead? (like when Firefox asks whether we'd like to enable geolocalization on a page)

**Comment by kspearrin** [comment]
Not that I am aware of. Firefox can do that natively.

**Comment by pitrou** [comment]
Other idea: glow the bitwarden toobar icon periodically.

**Comment by kspearrin** [comment]
@pitrou Not sure what you mean??

**Comment by pitrou** [comment]
An effect on the icon like this: https://basicuse.net/articles/pl/textile/html_css/how_to_create_flashing_glowing_button_using_animation_in_css3/example_1
This would prompt the user to click the toolbar icon, which would present the user with the "remember password" question in addition to the usual UI.

**Comment by kspearrin** [comment]
@pitrou What icon are you talking about? We don't do something like this with the bitwarden toolbar icon. Again, the browser controls that and we only pass a static image.

**Comment by pitrou** [comment]
I was indeed talking about the bitwarden toolbar icon. Barring any other solution, I would recommend making the iframe much higher at least, to avoid any future problems.

**Comment by MoonShade** [comment]
I'm asking myself if we can't let the iframe pass it's height to the plugin somehow. There is a pure javascript solution to ask for the height of the body of the iframe but that would probably trigger access violations of some kind. But maybe [passing it with postMessage](https://viget.com/extend/using-javascript-postmessage-to-talk-to-iframes) could be an option.

**Comment by kspearrin** [comment]
Fixed with https://github.com/bitwarden/browser/commit/1b344ade0d19a63b360f9bc6acdfbf1388c902ee in the next release.
