### ISSUE TITLE
Changing Firerfox user agent breaks Bitwarden Firefox extension login

### ISSUE THREAD

**Issue by cnygaard** [bitwarden/browser#2173]
### Steps To Reproduce

1. Open Firefox
2. Click on about:config in Search bar to change Firefox settings
3. Set general.useragent.override to a custom value for example ""
4. Click on Bitwarden extension Firefox icon and try and login

### Expected Result

Being able to use Bitwarden Firefox extension and login with Bitwarden Firefox addon.

### Actual Result

Login in browser extension is not shown when changing user agent from Firefox to a custom value. 

### Additional Context

For privacy reasons you might want to change which browser headers a browser sends out to prevent/make it harder for User-agent fingerprinting from ad-networks. But changing Firefox built in user agent general.useragent.override breaks Bitwarden login.

### Operating System

Linux

### Operating System Version

Debian 11

### Web Browser

Firefox

### Browser Version

78

### Build Version

20100101

**Comment by eliykat** [comment]
We expect the useragent string to be a non null/empty value. I set it to "foo" and could log in without any problems. However, we do use the useragent string to determine what browser you're using and adjust the extension's behaviour accordingly (different browsers can behave differently). If you're overriding your useragent string then you may experience undefined behaviour and this would not be supported.

**Comment by ptrcnull** [comment]
for any other people who stumble over this issue: you (sadly) have to add ` Firefox/`  (yes, with a space!) to your UA string to unbreak the addon; see here:

https://github.com/bitwarden/clients/blob/836d87f49247ec763de0f2b614b69f5696e3fff4/apps/web/src/app/core/web-platform-utils.service.ts#L27
