### ISSUE TITLE
Cmd+Shift+L does nothing if vault not already unlocked

### ISSUE THREAD

**Issue by timkgh** [bitwarden/browser#2176]
### Steps To Reproduce

If vault is not already unlocked, Cmd+Shift+L does nothing, which is confusing to the user. Is it because there's no match for the current web site? Something else? Turns out it does not do anything if the vault is not already unlocked.

### Expected Result

If vault is locked, prompt user to unlock it. See what 1Password does.

### Actual Result

Does nothing, no user feedback.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

1.54.0

**Comment by djsmith85** [comment]
Hi @timkgh, this has already been implemented with #2132 but hasn't been released yet. It will be included in the next release.
