### ISSUE TITLE
Header error for url in the exported .csv file

### ISSUE THREAD

**Issue by woodwm** [bitwarden/browser#219]
In the latest Firefox extension v1.15.3, there is a error in the header in the exported .csv file.

> name,uri,username,password,notes,folder,totp

The second words should be `url` instead of `uri`

**Comment by kspearrin** [comment]
Uri is correct. https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by woodwm** [comment]
But when I tried to import the .csv file from Bitwarden to Lastpass, it cannot detect the `uri` field and showed a warning **"its url is blank"**. I am curious what is the advantage of using `uri` instead of `url` for the use of Bitwarden.

**Comment by kspearrin** [comment]
Our export is not meant to be in lastpass' format. You should consult their import guides or support people for help with that.

**Comment by woodwm** [comment]
Actually, I do not know much about `URI` until you pointed out that. I do not mean what kind of format Bitwarden should follow. I am just curious why `URL` is not enough to cover the use of Bitwarden as `URL` seems more frequently used and I guess more familiar for most people.

**Comment by kspearrin** [comment]
It's just a header label. It could be called anything. We use URI since it is more correct for what we store in that field. Could be URLs or URIs

**Comment by woodwm** [comment]
Thanks for explanation.
