### ISSUE TITLE
ubuntu -  Vault timeout action on system lock not working

### ISSUE THREAD

**Issue by Adedamola-Aina** [bitwarden/browser#2195]
### Steps To Reproduce

1. Install Chrome on Ubuntu.
2. Install the Bitwarden browser extension on Chrome.
3. Set the 'Vault Timeout' to 'On System Lock'.
4. Set the 'Vault Timeout Action' to 'Lock'.
5. Lock the operating system.
6. Unlock the operating system.

### Expected Result

This is meant to lock the browser extension with a padlock icon showing the vault needs to be accessed with the master password again. 

### Actual Result

the browser extension is still unlocked without following the vault timeout and vault timeout action settings

### Additional Context

This function is actually working in windows 10, 11, and macOS Monterey. 

### Operating System

Linux

### Operating System Version

Ubuntu 21.10

### Web Browser

Chrome

### Browser Version

96.0.4664.45 (Official Build) (64-bit)

### Build Version

1.54.0

**Comment by Hinton** [comment]
Hi @Adedamola-Aina,

We rely on the chrome APIs for this functionality. Specifically the chrome.idle api. https://developer.chrome.com/docs/extensions/reference/idle/#event-onStateChanged

Are you able to try and replicating the issue on https://reillyeon.github.io/scraps/idle.html, click request permission, and start. Then lock and unlock your computer. if it works it should show up like this:

![image](https://user-images.githubusercontent.com/137855/146190017-c4547dfa-890e-4761-9894-ed3cb011b42b.png)

If nothing is detected then this is an internal issue in Chrome that we can't resolve ourselves.
