### ISSUE TITLE
Medium/high cpu usage when background page change title

### ISSUE THREAD

**Issue by SylwesterZarebski** [bitwarden/browser#2198]
### Steps To Reproduce

1. Open some page which changes title on background, i.e.: https://bigstar.pl/
2. Open about:performance page
3. When background page is changing title, bitwarden has CPU spikes:
![obraz](https://user-images.githubusercontent.com/1755531/143436807-0020cfa4-2628-4caa-8340-c90d7422ccb6.png)

When opened multiple pages changing its title it is spiking to high levels:
![obraz](https://user-images.githubusercontent.com/1755531/143437731-32c919bb-66c1-49ad-a951-7bfcff632084.png)

### Expected Result

No spikes when there is no user interaction.

### Actual Result

Bitwarden somehow is connected to title changing and do some work.

### Additional Context

Using browser with about 100 tabs opened, but only 20 active (rest unloaded).

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

94.0.1

### Build Version

1.54.0

**Comment by SylwesterZarebski** [comment]
It may (or not) be related to another reports like #769.

**Comment by eliykat** [comment]
This reminds of me of #1243 which was fixed by #2129. In that case we were watching for page title changes and running a bunch of logic unnecessarily. @djsmith85 do you think it could be something else in that part of the code?

**Comment by djsmith85** [comment]
@eliykat You are right the notificationBar part is fixed, but I think that `refreshBadgeAndMenu` is the issue here. It gets triggered by multiple parts of the code. I recently had a look at how the menu is built and saw some potential for optimization (cache main menu and only rebuild sub-menu when necessary). A reduction of calls to `refreshBadgeAndMenu` would definitely be a performance improvement.

**Comment by SylwesterZarebski** [comment]
It is expected to be published in next/nearest version or some time after?

**Comment by eliykat** [comment]
Hi @SylwesterZarebski, this is scheduled for our May release (25/26 May).
