### ISSUE TITLE
Firefox Addon Does Not Install - a warning says it may be corrupted

### ISSUE THREAD

**Issue by cwmke** [bitwarden/browser#22]
I installed Firefox Developers edition 51.0a2 which allows disabling signature checking with toggling the option 'xpinstall.signatures.required;false'.  I thought this may be the issue but no luck. The warning still appears. Thanks for any help and for the remarkably well functioning first release!

~~~~~
The add-on downloaded from this site could not be installed because it appears to be corrupted
~~~~~

**Comment by kspearrin** [comment]
Fiirefox availability is being tracked here: https://github.com/bitwarden/browser/issues/8

Mozilla has not finished their review yet.
