### ISSUE TITLE
Fedora Linux + Firefox == No drop down boxes.

### ISSUE THREAD

**Issue by maxamillion** [bitwarden/browser#2205]
### Steps To Reproduce

Using Fedora 35 with latest Firefox (94 at the time of this writing), login to Bitwarden browser extension, sync, then:

1. Go to Settings
2. Click on any drop down menu
3. It doesn't actually drop down

This appears to be a Firefox on Linux problem and not a Fedora specific one, Manjaro users are posting the same issue on Reddit: https://www.reddit.com/r/Bitwarden/comments/pxxtxi/firefox_addon_dropdowns_dont_work/

### Expected Result

The drop down to actually drop down and display options instead of do nothing.

### Actual Result

Nothing happens when clicking a drop down menu.

### Operating System

Linux

### Operating System Version

Fedora 35

### Web Browser

Firefox

### Browser Version

94.0

### Build Version

firefox-94.0-2.fc35.x86_64

**Comment by eliykat** [comment]
Thank you for the bug report. This is already a known issue that is being tracked in #2068. Please see the discussion there.
