### ISSUE TITLE
Not solved: CloudFlare issue in Chromium-based browsers - can't login with Error 1020 #2212

### ISSUE THREAD

**Issue by Doemaas** [bitwarden/browser#2213]
Still happens now, fresh Brave browser Versie 1.32.113 Chromium: 96.0.4664.45 (Officiële build) (x86_64) on macOS 11.6.1. It works correctly on the same machine with Firefox 95.0.

_Originally posted by @Doemaas in https://github.com/bitwarden/browser/issues/2212#issuecomment-988825371_

**Comment by djsmith85** [comment]
@Doemaas Thank you for your report in #2212 but please do not open multiple issue for the same case. An issue can always be re-opened and we are working on resolving the issue for everyone.

**Comment by Doemaas** [comment]
There was no option to reopen and I was not sure if the comment would become visible. I see you have reopened the original, thanks.
