### ISSUE TITLE
"Access Denied" error when attempting to install Bitwarden Password Manager from Chrome Store

### ISSUE THREAD

**Issue by TriggerDingus** [bitwarden/browser#2217]
### Steps To Reproduce

Open Chrome Store from Brave browser.
Search for Bitwarden Password Manager extension.
Click "Add to Brave" button

### Expected Result

Seamless Bitwarden extension install from the Chrome Store

### Actual Result

"Access Denied" error during Bitwarden extension installation from the Chrome Store.

### Screenshots or Videos

![bitwardenExt](https://user-images.githubusercontent.com/75340371/145307836-c8848268-ed4e-452f-a5b0-cdad96deee9f.jpg)

### Additional Context

I posted another issue since I have to install Bitwarden multiple times/week due to some bug that began a couple months ago, so this install is something I do multiple times/week. Typically, it goes without incident.

### Operating System

Linux

### Operating System Version

Pop! 21.04

### Web Browser

Firefox, Brave

### Browser Version

Brave Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)

### Build Version

N/A

**Comment by TriggerDingus** [comment]
I notice this hasn't been tagged by a Dev. Any updates? I tried again today and I get the same error message.

**Comment by djsmith85** [comment]
This [thread ](https://github.com/brave/brave-browser/issues/16611)on the Brave's Github issue tracking seems to indicate that they made some changes to their component update server. Updating Brave should resolve this issue. 

Please close this issue, if it gets resolved by the update.

**Comment by TriggerDingus** [comment]
I'm on the latest version:

ob@pop-os:~$ sudo apt install brave-browser
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
brave-browser is already the newest version (1.15.76).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.

**Comment by djsmith85** [comment]
Based on [Brave's Github releases](https://github.com/brave/brave-browser/releases/tag/v1.32.115) I'd say you are still on an old version. Maybe your repository needs updating (old/wrong url), might just be available via the Canonical store https://snapcraft.io/brave instead of a custom repo.

**Comment by TriggerDingus** [comment]
> Based on [Brave's Github releases](https://github.com/brave/brave-browser/releases/tag/v1.32.115) I'd say you are still on an old version. Maybe your repository needs updating (old/wrong url), might just be available via the Canonical store https://snapcraft.io/brave instead of a custom repo.

Thanks for the suggestion. I don't do snaps, so I passed on that but I was able to get myself successfully upgraded after trying again. Not sure what went wrong during my first attempt, perhaps I missed updating my repository.
