### ISSUE TITLE
Safari 15.0 Bitwarden Extension falsely states, “There are no logins available to auto-fill for the current browser tab.” until restarting Safari.

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/browser#2220]
### Steps To Reproduce

1. Open Safari 15.0 with Bitwarden Extension 1.49.1, 
2. Use click on BW extension to login into a website.
3. After an unknown amount of time, 
4. Click on the BW extension again and BW extension no longer recognizes URI matching, instead BW extension falsely states, “There are no logins available to auto-fill for the current browser tab.” until restarting Safari.

### Expected Result

Bitwarden should continue to do URI matching and login into site with matching URI criteria regardless of time elapsed.

### Actual Result

BW extension no longer recognizes URI matching.

BW extension falsely states, “There are no logins available to auto-fill for the current browser tab.” until restarting Safari.

### Screenshots or Videos

![Screen Shot 2021-10-14 at 11 11 53 AM](https://user-images.githubusercontent.com/68088552/137373682-af8fb3b4-8e74-4fec-a59a-21094c2f7cf6.png)
![Screen Shot 2021-10-14 at 11 12 33 AM](https://user-images.githubusercontent.com/68088552/137373685-df911be8-ad1d-4ed1-8a3f-b9e740d60940.png)
![Screen Shot 2021-10-14 at 11 13 30 AM](https://user-images.githubusercontent.com/68088552/137373687-2aec31dc-860c-4dd1-8266-dafd3b7dd503.png)
![Screen Shot 2021-10-14 at 11 18 46 AM](https://user-images.githubusercontent.com/68088552/137373706-6efa81cd-e337-421e-88fb-896c43b65c0c.png)

### Operating System

macOS

### Operating System Version

11.6

### Installation method

Mac App Store

### Build Version

BW Extension Version: 1.49.1

**Comment by Hinton** [comment]
Hi @ToGitOrNotToGit,

Version 1.49.1 is fairly old. Are you still experiencing the issue with the latest version of the browser extension?

**Comment by ToGitOrNotToGit** [comment]
Hi. You can close this. It is on a machine that isn’t updated frequently. ‘Check for updates’ didn’t offer any updates. I transitioned to the App Store version and was able to get a current version.
