### ISSUE TITLE
Cannot log in on Firefox extension with a tiny screen

### ISSUE THREAD

**Issue by philnash** [bitwarden/browser#224]
I just resurrected my netbook, with a 10 inch screen and a 1024x600 resolution.

I installed Firefox and then the Bitwarden extension, but I was unable to log in as the login button was off screen. I presume, given that the extension has a fixed height, that if I was to be able to log in, I also wouldn't see the bottom menu bar either.

![Screenshot of window that I can't log in to.](http://i.imgur.com/2KwcxCxl.png)

Is it possible to calculate the screen height and adjust the extension height for these small screens?

**Comment by kspearrin** [comment]
We did make some adjustments in the last release for this, but it looks like your screen is even smaller. That's an awfully small height. I can try putting and even small height in there.

**Comment by kspearrin** [comment]
Resolved for next release. Height is 300 https://github.com/bitwarden/browser/commit/2e20f051c08e69db864c4daaa9788a7837688c12
