### ISSUE TITLE
Doesn't ask for login at browser start

### ISSUE THREAD

**Issue by Yannnd** [bitwarden/browser#226]
Using 1.15.3 on Firefox nightly 57.0a1 (2017-09-12) on Debian Jessie. 

On the Mozilla Add-on page https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/reviews/ I see under the title "questions for developers" (2017-09-02) the suggestion that when the lock option has been set to 'On Restart', the user will _automatically_ be prompted for the master password after startup of the browser. However that doesn't happen. Bitwarden is locked as it should be, but I have to click the icon first to get the UI to enter the password. Am I overlooking something?

**Comment by kspearrin** [comment]
Yes, you have to click the icon to open bitwarden to log in.

**Comment by Yannnd** [comment]
Thank you for the very fast response! A clear answer.

In that case, I would like to issue a feature request to add this functionality, if the API allows it. Maybe an option could be added to the settings part of the UI to enable/disable this "Ask for password on browser start"?

**Comment by kspearrin** [comment]
You can open an issue for that. I think the only way we could do this would be to open a new full screen tab since the popup cannot be opened without the user clicking it.

**Comment by Yannnd** [comment]
Ah, I didn't know that. I don't think it would be a very elegant solution to open a new full screen tab just to enter a password. I can live with an extra mouseclick now and then :-)
