### ISSUE TITLE
web extension cannot fill sign ins in popup screens

### ISSUE THREAD

**Issue by trevmaz** [bitwarden/browser#2266]
### Steps To Reproduce

It happens when I pay in ebay with paypal or with afterpay(Australia) it opens a popup to login.

### Expected Result

Bitwarden extension should see the popup to fill

### Actual Result

Bitwarden extesion does not see the popup

### Operating System

Windows

### Operating System Version

11

### Installation method

Microsoft Store

### Build Version

1.30.0

**Comment by djsmith85** [comment]
@trevmaz  Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
