### ISSUE TITLE
Safari Webextension unavailable 

### ISSUE THREAD

**Issue by henningkessler** [bitwarden/browser#2269]
### Steps To Reproduce

According to https://bitwarden.com/help/article/install-safari-app-extension/ the Webextension should be available in Safari Preferences/Extension after at least running the Desktop App at least once. But unfortunately this is not the case for me. 

Using the help menu from the desktop app brings me into the Mac App Store and selecting the Bitwarden App there opens the Bitwarden desktop again ;-)

Hopefully I am not holding it wrong...

### Expected Result

Webextension should be available in Safari Preferences/Extension

### Actual Result

Not available 

### Operating System

macOS

### Operating System Version

12.1

### Web Browser

Safari

### Browser Version

15.2

### Build Version

17612.3.6.1.6

**Comment by Greenderella** [comment]
Our development team is aware of the Safari extension missing issue. Please try the following:

1) Run this in the terminal app:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`

2) Restart Safari
3) Enable Bitwarden

Thanks for your patience and understanding! Let us know if there is anything else we can do for you.

**Comment by henningkessler** [comment]
🥰 you are my hero 👍

Great!!!!! thanks for your help and all your work. You rock 🎸

:-)
