### ISSUE TITLE
Doesn't save proper username

### ISSUE THREAD

**Issue by Palf994** [bitwarden/browser#227]
First of all, thanks for all of your work on this awesome project. Currently moving from LogMeOnce to Bitwarden and love it.

When signing up for an account at [https://www.hot-headz.com/register](https://www.hot-headz.com/register), Bitwarden saves the city as the username instead of the email address. My other password manager did not make this same error. This makes me slightly nervous that I'll assume the extension is catching my login info properly when it actually isn't.

This issue was with the latest version of the Chrome extension, in the latest version of Chrome (61.0.3163.79) on OS X 10.11.6

Thanks again!

**Comment by kspearrin** [comment]
The extension looks for the field that comes first before the first password field and assumes that is the username. This registration form is a bit more involved and doesn't follow that usual pattern. Some improvements can be made there.

**Comment by kspearrin** [comment]
Fixed in next release with much better username detection.
