### ISSUE TITLE
Generated password always filled at the Master Passowrd/pin location

### ISSUE THREAD

**Issue by sagarkrp** [bitwarden/browser#2270]
### Steps To Reproduce

1. Go to 'Firefox extension 1.55.0'
2. Click on 'Generate a password and use in an app by copying it'
3. Now lock the vault
4. Next time you try enter to enter the PIN to unlock the previously generated password is already filled in the filed.
5. Close the browser. and next time on opening it again, the password is present in the 'Master Password' field. Even if you logout and try to login its the same. It appears at the pin generation field too.
6. Remove the already filled text, and it says "Form this website" as if it takes the extension as the app URL.

### Expected Result

The password/pin field should not be already filled out with the generated password

### Actual Result

The password/pin is filled out with the generated password

### Screenshots or Videos

![bitwarden](https://user-images.githubusercontent.com/42873729/149527654-5c2c92e3-3f66-4535-b901-fc90d88edbec.png)

### Operating System

Windows

### Operating System Version

10 (21H2)

### Web Browser

Firefox

### Browser Version

96.0

### Build Version

1.55.0

**Comment by djsmith85** [comment]
Hi @sagarkrp the popup you are seeing is not from Bitwarden but likely from the built-in password manager of your browser. 

Please have a look here on how to deactivate it: https://bitwarden.com/help/article/disable-browser-autofill/
