### ISSUE TITLE
Form Filling Problem

### ISSUE THREAD

**Issue by bkrcrc** [bitwarden/browser#231]
website: http://www.harikadizi8.com/

bitwarden cannot fill forms on this website.
screenshot: http://prntscr.com/gl8rpn

I have to manually copy username and my password to paste them in form.
Can you please check it? The problem is bitwarden or the website?

Thanks,

**Comment by kspearrin** [comment]
This website does some really weird HTML work.

When the page loads the password input field in the header does not have a `type="password"` attribute. When you focus your cursor into the username or password fields all of a sudden it adds a proper `type="password"`.

There's nothing I can do to make this work properly. For autofill to work, first focus into one of the fields. Then do the auto-fill and it will work.
