### ISSUE TITLE
Slow script warnings using Firefox with 1.16.1

### ISSUE THREAD

**Issue by mhammond** [bitwarden/browser#232]
I'm starting to see slow script warnings on twitter, and @thomcc also reports he sees it on irccloud - not on page load, but just while using an already open tab. It's difficult to reproduce, so I'm sorry I can't be more helpful - but I'm also wondering if the recent versions are doing any additional work the older versions weren't?

Bitwarden 1.16.1 on Firefox 57.

23:09:16.864 Error: Script terminated by timeout at:
getLabelTag@moz-extension://8fc4c64c-8dec-9a44-9ca7-32b4a43cb4d0/content/autofill.js:171:42
collect/getPageDetails/theFields<@moz-extension://8fc4c64c-8dec-9a44-9ca7-32b4a43cb4d0/content/autofill.js:266:49
getPageDetails@moz-extension://8fc4c64c-8dec-9a44-9ca7-32b4a43cb4d0/content/autofill.js:242:29
collect@moz-extension://8fc4c64c-8dec-9a44-9ca7-32b4a43cb4d0/content/autofill.js:572:31
@moz-extension://8fc4c64c-8dec-9a44-9ca7-32b4a43cb4d0/content/autofill.js:961:31
 1 autofill.js:171:42

**Comment by kspearrin** [comment]
Hmm. There were some changes in 1.15.x that would call `/content/autofill.js` `collect()` more frequently (which shows in your stack trace). We added `window.addEventListener('popstate', collect)` to `/content/notificationBar.js` to handle uses cases for SPA navigation events.

**Comment by kspearrin** [comment]
Try toggling "Disable Add Login Notification" under Settings → Features and see if that helps at all.

**Comment by kspearrin** [comment]
Any changes @mhammond ?

**Comment by thomcc** [comment]
This fixed it for me, but it (seems to be) a bit of an unfortunate fix, since disabling that in all cases kind of sucks.

**Comment by kspearrin** [comment]
That's not meant to be the fix. It's meant to help locate the problem.  @thomcc

**Comment by kspearrin** [comment]
I browsed twitter a bit and am not seeing excessive calls to `window.addEventListener('popstate', function() { ... });` so I am a little confused as to why this is happening still...

**Comment by mhammond** [comment]
I haven't seen it since, although I haven't used twitter much since I reported it.

> I browsed twitter a bit and am not seeing excessive calls to window.addEventListener('popstate', function() { ... }); so I am a little confused as to why this is happening still...

I *guess* that happens when you click on a re-tweeted link - the url changes even though I don't think the page actually navigated.

**Comment by mhammond** [comment]
> Any changes @mhammond ?

I'm now confident enough to say that fixed it for me too

**Comment by mhammond** [comment]
I re-enabled that option and it is semi-reliable to repro when clicking on a retweet (so the URL changes), then closing the tweet's "popup" (URL is back to twitter.com), then scrolling around for a second or 2.  1.16.1 on Fx nightly.

**Comment by kspearrin** [comment]
@mhammond What OS are you on? Trying to repro on w10 and not seeing a problem on my desktop here.

**Comment by kspearrin** [comment]
Can you update to 1.17.0 and see if anything changes?

**Comment by mhammond** [comment]
I see this on my macbook and don't use twitter on my windows box enough to know for sure. However, on my windows box I changed the pref dom.max_script_run_time to 2 and could reproduce it clicking around using 1.17.1, with the top of the stack being:

> isElementVisible@moz-extension://9408d2d8-3f65-4743-b5a9-c3fb1d2b6076/content/autofill.js:464:31

Anecdotally, it seems to happen most after I click on a tweet (causing the URL to change), and click outside the tweet (closing the "popup" and changing the URL back to just twitter.com), then scroll down such that more tweets are loaded. On my mac the loading of new tweets stalls, the slow-script warning comes up, and I wait a second or 2 before the slow-script warning closes and the new tweets appear.

**Comment by kspearrin** [comment]
Thanks for the info @mhammond . If you don't mind helping, I may try to throw together a custom build for you with some extra logging so we can better pinpoint where this issue is stemming from. Are you ok with that?

**Comment by mhammond** [comment]
SGTM - a patch would also be fine as I think I can remember how to get a custom build working.

**Comment by kspearrin** [comment]
Ok, stand by and I'll try to get something together tomorrow.

**Comment by kspearrin** [comment]
@mhammond I'm pretty sure I found the issue. Please pull master and build with 

```
npm install
gulp dist-firefox
```

Then load temp addon from the ./dist folder.

**Comment by kspearrin** [comment]
Problem was our auto-fill collection script was getting all input, select, and **buttons** from the page (which are then analyzed with other methods). Twitter has thousands of buttons in the dom after revealing a large feed. Turns out we really don't need the buttons at all so I removed them from the query selector of the autofill collection script.

**Comment by kspearrin** [comment]
1.18.0 just landed in AMO with these fixes.

**Comment by mhammond** [comment]
Awesome, thanks. I couldn't see it since running from source so I strongly suspect the issue was fixed, but I'll be sure to let you know if I see it again.
