### ISSUE TITLE
Extension crash on MS Edge 100.0.1156.1

### ISSUE THREAD

**Issue by Coffmans** [bitwarden/browser#2328]
### Steps To Reproduce

1. Click the extension button to sign into Bitwarden.
2. Type a letter in the password field
3. Observe the crash of the extension

### Expected Result

The obvious expectation is the user would be able to log into Bitwarden.

### Actual Result

The extension crashes in the browser.

![Untitled](https://user-images.githubusercontent.com/8136145/153463143-dd1ffd3d-cca1-40db-b7e4-5814aa340d7c.png)

### Additional Context

For the record, this version of MS Edge is the latest development version.  As soon as I updated to this version, the extension started to crash. 

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

100.0.1156.1 (Official build) dev (64-bit)

### Build Version

1.55.0

**Comment by Hinton** [comment]
Hi @Coffmans,

We don't officially support pre-releases of browsers since they often temporarily break things. With that said feel free to provide additional information like logs.

**Comment by Coffmans** [comment]
I hate to ask this question as I am sure it is already answered. But my research has not revealed any answers. Where can I find the logs to submit that would be beneficial?

**Comment by Hinton** [comment]
@Coffmans I'm not completely certain myself what logs would be useful in this case.

Crashlogs seems to be accessible from `edge://crashes` according to https://techcommunity.microsoft.com/t5/discussions/where-to-find-the-crash-log-and-dump-of-microsoft-edge/m-p/1767236/highlight/true#M36342

In chromium it's also possible to get additional logs by starting Chromium with the flags `--enable-logging=stderr --v=1`. I suspet the same is possible with edge. (https://www.chromium.org/for-testers/enable-logging/)

**Comment by Coffmans** [comment]
@Hinton This ticket can be closed. The latest dev build of MS Edge was released earlier today and the issue is no longer present.
