### ISSUE TITLE
Long translations doesn't display correctly in Save notification

### ISSUE THREAD

**Issue by felicienfrancois** [bitwarden/browser#233]
In french, buttons are stacked vertically even when there is enough horizontal space.
Occurs in both Firefox and Chrome

![savenot](https://user-images.githubusercontent.com/988144/30477466-904136da-9a0d-11e7-8580-844d4291e325.png)

**Comment by felicienfrancois** [comment]
For french, it would display normally on firefox with width 370px instead of 320px at https://github.com/bitwarden/browser/blob/9ee016251ab2401be8a2450ccf57bd598c45c442/src/notification/bar.css#L89

And 200px instead of 175px at https://github.com/bitwarden/browser/blob/9ee016251ab2401be8a2450ccf57bd598c45c442/src/notification/bar.css#L84.

Also I'm wondering if thoose forced width are useful. On firefox if I disable thoose forced width it display perfectly for all screen width (responsive)

**Comment by kspearrin** [comment]
Set widths are now only for English. The rest have no width set which causes stacking in some situations. Feel free to add other language widths to the CSS.

See https://github.com/bitwarden/browser/commit/438ccd0f9e94c5f2d291c91c4199bd0d3e23a69c
