### ISSUE TITLE
[Browser] Unable to View and Copy TOTP Codes

### ISSUE THREAD

**Issue by DesignatedJM02** [bitwarden/browser#2330]
### Steps To Reproduce

1. Make sure you are updated to the latest version of the extension.
2. Have TOTP Codes saved in your vault
3. View an entry that has a TOTP entry.
4. See if you see the TOTP displayed

### Expected Result

I expect to see my TOTP Code displayed in Bitwarden

### Actual Result

I do not see my TOTP Code displayed in the browser.
I can view TOTP codes in Firefox which hasn't updated to the latest version yet. My BW extension on Firefox is on version: 1.55.0. 

### Screenshots or Videos

Not applicable. Contains personal data. 

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Microsoft Edge, Brave

### Browser Version

Brave: 1.35.101. Edge: 98.0.1108.50

### Build Version

1.56.0

**Comment by cristianlivella** [comment]
Same issue here with Chrome 97.0.4692.99 on Linux.

**Comment by kegbeach** [comment]
This is a huge problem running Chrome 98.0.4758.80 on Fedora.

**Comment by metabubble** [comment]
Confirmed on Mac OSX 12.2 (M1) Chrome 98.0.4758.80 Version: 1.56.0

**Comment by toschulz** [comment]
It's happening with Chromium 98.0.4758.80 on Windows 11 with extension version 1.56.0 as well.  Glad I'm not the only one.  It looks like premium membership is not enabled for some reason.  I'm running Bitwarden self-hosted as well.

**Comment by djsmith85** [comment]
Thank you for your reports. 

I was able to reproduce this on Chrome. 

Could you please try logging out and then back in, that fixed it for me. 

I'll be looking into the possible cause.

**Comment by kegbeach** [comment]
Yes, logging out then back in fixed it.

**Comment by toschulz** [comment]
Thanks, it worked for me as well.

**Comment by ramicohen303** [comment]
It works intermittently. Still broken after restarting.

**Comment by cscharf** [comment]
FYI: https://github.com/bitwarden/jslib/pull/666

**Comment by cscharf** [comment]
Released and submitted to Chrome and Opera extension stores: https://github.com/bitwarden/browser/releases/tag/v1.56.1

**Comment by Appoxo** [comment]
> Looks like the error is not a single occurrence either if you lock the vault or close out of the browser and try to log back in via pin or master password it will also give that error. Thankfully it seems that all that is needed is a manual sync and everything pops back up. No need to fully log out. This looks like more of a decrypting issues rather than a corrupting issue.
>
> Chrome 98.0.4758.82 Bitwarden 1.56.0 Android 2.16.1 - Don't seem to have the decrypting issue with android at all.

Not really. I tried the manual resync but my premium didn't activate. Had to reinstall
Chrome: 97.0.4692.99 
Bitwarden Extension: 1.56.0

**Comment by grottas** [comment]
I'm having this issue, with the following set up, being a premium user within an organization.

Firefox: 135.0.1 (64-bit)
Bitwarden: Version 2024.12.4 / SDK: 'main (edee180)' / Server version: 2025.2.0
Windows: 11 Pro 24H2 26100.3194

I can get the TOTP codes from the desktop app and the mobile app. Firefox browser extension is not getting the premium subscription, and doesn't show the codes, and I already tried reinstalling the extension.

![Image](https://github.com/user-attachments/assets/1f834adc-6658-44d8-a4b9-ee7ec388d8f4)

@eliykat

**Comment by eliykat** [comment]
Hi @grottas, this is a known issue that was fixed by #13357 which went out in the 2025.2.0 release. Unfortunately our Firefox add-on store submissions are a bit backed up at the moment due to Mozilla's review process. Keep an eye out for updates and let us know if you have the issue after upgrading.
