### ISSUE TITLE
Bitwarden Chrome/Brave extension is now super slow after the desktop update to 1.31 (Windows 10)

### ISSUE THREAD

**Issue by ghhv** [bitwarden/browser#2338]
### Steps To Reproduce

Responsiveness is now terrible.. it wasn't great before (probably because I have an enormous password list) but now it takes ~10 seconds to open Bitwarden after clicking browser extension and CPU spikes to 40%+ - and I have an 8 core i9 CPU.. 

Does same thing on Chrome, Brave. Firefox still has the old extension and works instantly.. no delay. 

Desktop is still sluggish but not obviously worse. 

### Expected Result

Zippy.. 

### Actual Result

Slow......

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome, Brave

### Browser Version

Chrome Version 98.0.4758.82 (Official Build) (64-bit), Brave Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)

### Build Version

Version 1.31.0 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by ghhv** [comment]
OK, bad to worse.. Opened a new tab for a new site.. At least 90 seconds to respond with password selections. And black screen as shown. The sort order is all changed too.. suggestion no longer matched as before.
![image](https://user-images.githubusercontent.com/13160762/153533356-173204a7-79cb-48d4-b214-d67370e9a1b8.png)

**Comment by kspearrin** [comment]
Thanks for the report. We are aware of the issue and are working on a fix.

**Comment by cscharf** [comment]
Please reference this issue for future updates, closing this one as a duplicate. Thanks again!
https://github.com/bitwarden/browser/issues/2335

**Comment by ghhv** [comment]
Except I closed that one #2335 because I logged it under desktop instead of browser.. So this should be the current issue.

**Comment by cscharf** [comment]
Yeah, sorry @ghhv, I missed that in my haste and had moved the one from Desktop over here to Browser also. So all is good now, sorry for the confusion.

**Comment by kspearrin** [comment]
We have identified the issue and a hotfix should be incoming soon.
