### ISSUE TITLE
Bitwarden Extension - Cannot Decrypt/Login

### ISSUE THREAD

**Issue by bd-g** [bitwarden/browser#2363]
### Steps To Reproduce

1. Install Bitwarden Browser extension on Brave Browser and login with multifactor authentication enabled. Set vault timeout to ```Browser Restart```
2. Close browser, forcing a vault logout
3. Open a new browser and enter password. Vault is unlocked but all entries show ```[error: cannot decrypt]```
4. Additionally, if you try to solve this by logging all the way out and logging back into the extension, a different error occurs during login and vault is not unlocked. ```Cannot read properties of undefined (reading 'keys')```

### Expected Result

I expect to be able to login on browser restart and have the vault unlocked with entries showing. Additionally, a fresh logout and login should reset data and work okay.

### Actual Result

See ```Steps to Reproduce``` for a description of behavior.

### Screenshots or Videos

![Cannot Decrypt Error](https://user-images.githubusercontent.com/49082060/153628916-17b89a70-d382-4d13-b644-a187c586d13e.png)

![Cannot Login Error](https://user-images.githubusercontent.com/49082060/153629507-3b72877a-0ed5-40f1-a25f-fed1a50bbaa0.png)

### Operating System

Linux

### Operating System Version

Arch Linux - Kernel 5.16.8

### Web Browser

Brave

### Browser Version

98.1.35.101

### Build Version

1.56.1

**Comment by koopernick** [comment]
I had the same issue this morning, but It should be fixed with the latest update (1.56.3).
If it's not, downgrade to 1.55.x and wait for a fix I guess ^^'

**Comment by bd-g** [comment]
Can confirm that both referenced issues (cannot encrypt and cannot re-login) are fixed by 1.56.3 that I installed manually.

Just out of curiosity, how often are the releases to the Chrome Web Store / other extension stores?

**Comment by mahnac** [comment]
I am experiencing the same problem. Here on Windows 10 and Chrome.

**Comment by bd-g** [comment]
@mahnac If you go to the releases page and download the appropriate zip file and follow the install instructions on the README, you can verify that 1.56.3 works well for you too.

**Comment by mahnac** [comment]
@bd-g Thank you. I will do that now.

**Comment by mahnac** [comment]
@bd-g It is working again now. Thank you for the help.

**Comment by shivv3r** [comment]
When it will be pushed to Chrome extension store for automatic update to 1.56.3?
