### ISSUE TITLE
"Unfortunately this window is not available in private mode for this browser." in Safari non-private mode

### ISSUE THREAD

**Issue by pepperbc** [bitwarden/browser#2367]
### Steps To Reproduce

Intermittently - sometimes is fixed with a browser restart, other times is not:

1. Open Safari
2. Click on the bitwarden logo

### Expected Result

Bitwarden loads. If there is a failure, a relevant error message is presented. 

### Actual Result

Error message with "Unfortunately this window is not available in private mode for this browser." Clicking "Learn more" talks about "Extension won't load in Firefox's private mode". 

### Operating System

macOS

### Operating System Version

11.6.3

### Web Browser

Safari

### Browser Version

15.3

### Build Version

1.30.0

**Comment by eliykat** [comment]
This is a duplicate of #2297, please add any comments or information to that thread. Thanks!
