### ISSUE TITLE
unable to login using last plugins version (1.16.1)

### ISSUE THREAD

**Issue by PLabau** [bitwarden/browser#237]
since update to 1.16.1  - 
unable to save any login and if i disconnect my account on the FF plugins i was unable to log in back 
unexcepted error occurs at login 

Firefox ESR from 52.1.0 to last 52.3.0 portable fresg install (from portable apps) and just the bitwarden plugfins installed.

the plugins works in firefox 55.0.3 (not ESR version)

Workaround : install 1.15.3

**Comment by kspearrin** [comment]
That's odd. So you can log in with 1.15.3 but not 1.16.1? Do you have some time to help me debug this in live chat? https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
This is due to using a new API not available in pre-54 versions of Firefox. Options:

1. Update Firefox to latest (55)
2. Wait for version 1.16.3 to become available (just submitted a fix to Mozilla)
3. Downgrade to 1.15.3 for now

**Comment by arantius** [comment]
FWIW I'm on Firefox 55.0.2 and saw this.

**Comment by kspearrin** [comment]
1.16.3 is now live. Please update and try it.

**Comment by arantius** [comment]
Firefox 55.0.3, Bitwarden extension 1.16.3, still can't log in.  Same error as above linked dupe.

Same error after downgrade to 1.15.3.

**Comment by kspearrin** [comment]
@arantius Definitely sounds like some different issue then. Mind stopping by our dev chatroom sometime so I can help debug with you further? https://gitter.im/bitwarden/Lobby

**Comment by PLabau** [comment]
I confirm it is resolved with firefox ESR 52.3.0 !!thanks !!!

**Comment by arantius** [comment]
Yes, I mind.  I'll answer questions you ask here, but I'm not going to spend my time sitting in a chat room.

**Comment by kspearrin** [comment]
What other addons are you using ?

**Comment by arantius** [comment]
Oof, dozens.  Turns out it's probably uMatrix.  Sorry.

**Comment by undu** [comment]
Can confirm, uMatrix blocks requests to bitwarden by default. (The blocked xhr requests can be seen blocked in uMatrix's logger)

**Comment by kspearrin** [comment]
Can someone share the uMatrix rule to resolve this so I can document it?

**Comment by undu** [comment]
It depends per-installation as it includes the UUID of the bitwarden extension, it looks like this:

```
dc8ef5f6-eb0d-4c87-9e9f-0cf803f619e8.moz-extension-scheme bitwarden.com xhr allow
dc8ef5f6-eb0d-4c87-9e9f-0cf803f619e8.moz-extension-scheme bitwarden.com cookie allow
```

**Comment by kspearrin** [comment]
Done. Thanks:

https://github.com/bitwarden/help/blob/master/_articles/miscellaneous/umatrix-access-rule.md

**Comment by arantius** [comment]
It comes by default with

    matrix-off: chrome-extension-scheme true
    
I added

    matrix-off: moz-extension-scheme true
