### ISSUE TITLE
Chrome extension login fails at two-factor authentication step

### ISSUE THREAD

**Issue by pranavmarla** [bitwarden/browser#2370]
### Summary
The Chrome extension no longer lets me log in. Specifically, although it accepts my actual password, when I try to enter my two-factor authentication code, the extension throws an error.

### Steps To Reproduce

1. Attempt to login to Chrome extension, to an account where two-factor authentication has been enabled
2. Enter username and password, and click _Log In_
3. Enter two-factor authentication code and click _Continue_ -- nothing happens.
4. Click _Continue_ again -- extension throws an error (see below for details).

### Expected Result

Login should succeed

### Actual Result

Login fails: The extension doesn't accept the two-factor authentication code -- instead, it throws the following error:

> An error has occurred
must provide credentials or codes

### Screenshots or Videos

![bitwarden-login-failure](https://user-images.githubusercontent.com/6486632/153690880-1ae4af04-5d04-4b1c-9e36-dc77503a3502.png)

### Additional Context

- I am able to successfully log in via the [web vault](https://vault.bitwarden.com/#/)
- Uninstalling and reinstalling the same version of the extension seemed to _temporarily_ fix the issue -- it eventually came back.

### Operating System

Windows

### Operating System Version

Windows 10 19043.1526

### Web Browser

Chrome

### Browser Version

98.0.4758.82

### Build Version

1.56.1

**Comment by justindbaur** [comment]
Hi @pranavmarla We have a new version `1.56.3` available on the chrome web store, could you try updating and let us know if you still see the error?

**Comment by warwickmm** [comment]
I have this exact problem with 1.56.3 and Brave Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit) on Linux.

**Comment by pranavmarla** [comment]
> Hi @pranavmarla We have a new version `1.56.3` available on the chrome web store, could you try updating and let us know if you still see the error?

Thanks @justindbaur. That does seem to make the error go away for now, but I don't yet know if it's a permanent fix -- my previous workaround (uninstalling and reinstalling) also seemed to fix the issue initially, but it eventually came back.

Also, warwickmm above seems to be facing the same issue even with the newer version of the extension.

**Comment by warwickmm** [comment]
For me, after I enter the two-factor code nothing happens.  If I then click Continue a second time, then I encounter the "must provide credentials or codes" error.

**Comment by pranavmarla** [comment]
> For me, after I enter the two-factor code nothing happens. If I then click Continue a second time, then I encounter the "must provide credentials or codes" error.

@warwickmm Yup, that's the same behaviour I was seeing originally as well!

**Comment by ghhv** [comment]
Hi,
Seeing problems with 1.56.3 as well - the two factor code is invalid. I have a backup with Authy which is providing the correct code but the Bitwarden ones no longer match... this was on Brave (Chromium). Confirm that extension is up to date.

**Comment by warwickmm** [comment]
@ghhv, it sounds like your issue is unrelated to this one.

Updating to 1.56.4 fixed this for me.  Hopefully it's not just temporary like the uninstall/reinstall fix.

**Comment by ghhv** [comment]
yeah, it does as I tested further.. strange one.

**Comment by ckocyigit** [comment]
1.56.4 is still not working for me.

Iam using the Extension on Brave and have DUO as second authentication layer.

**Comment by Hinton** [comment]
@ghhv TOTP codes relies on the machines time being correct. Typically websites provides a bit of leeway but it's usually only around 90s. If the issue persists please open a separate issue to track this.

**Comment by Hinton** [comment]
Hi all,

I'm currently investigating this issue but are having troubles trying to replicating it. Are there any additional information on how to reliably reproduce it?

**Comment by cscharf** [comment]
> 1.56.4 is still not working for me.
> 
> Iam using the Extension on Brave and have DUO as second authentication layer.

@ckocyigit , Did you have any additional details or information that may help us out in reproducing the issue you're still experiencing with 1.56.4? Are you part of an organization that enforces DUO or is this your personal account? Are you using  a self-hosted server or Bitwarden's cloud? If self-hosted, what server version are you running?

**Comment by cscharf** [comment]
We believe this has been resolved with v1.56.5 and although we were able to reproduce this issue with 1.56.1, we are no longer able to reproduce this issue. Closing this issue for now. If the problem persists please feel free to re-open with more details for our QA team to reproduce. Thanks again!

**Comment by ckocyigit** [comment]
@cscharf 

It was layer 8: Pressing enter after entering the credentials closed the extension window. I just had to click the "Login" Button in the upper right corner.

But also intuitively you would think Enter would do the say as the login button.
