### ISSUE TITLE
Chrome Extension - Error accessing all passwords

### ISSUE THREAD

**Issue by Kartstig** [bitwarden/browser#2373]
### Steps To Reproduce

1. Login using Chrome Extension
2. Let machine go to sleep
3. Unlock Machine
4. Login again

### Expected Result

Passwords come up as they're supposed to.

### Actual Result

It appears there may be some weird parsing happening. I'm not sure where the in-memory data is stored, but something seems to happen after a period of time (when the computer goes to sleep). "Cannot read properties of undefined" error (see video)

### Screenshots or Videos

https://user-images.githubusercontent.com/2031422/153721982-6f725949-e440-423a-9bf6-556e5ca0c00a.mp4

### Additional Context

Seems to only happen when the machine goes to sleep or after periods of time when I have to enter my master password again

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.3 LTS

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.80 (Official Build) (64-bit)

### Build Version

1.56.3

**Comment by christiang830** [comment]
Similar happens for me. I can login, but when I try to access password there is only a spinner that doesn't stop..

**Comment by eliykat** [comment]
This should be fixed with 1.56.4. Please try updating and let me know if the problem persists.
