### ISSUE TITLE
[1.56.4] Chrome Extension - infinite loading

### ISSUE THREAD

**Issue by juliienp** [bitwarden/browser#2378]
### Steps To Reproduce

1. Open the extension
2. Prompt my master passsword
3. Write down my password
4. The app show the loader indefinitely

### Expected Result

The plugin should list all my items.

### Actual Result

The loading view is displayed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/9592397/153834406-cb15335f-ad3a-484c-bde0-27f6bae8c8fb.png)

### Additional Context

no error in the console window from the plugin

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

98.0.4758.82

### Build Version

1.56.4

**Comment by Hinton** [comment]
Hi @juliienp,

I'm having trouble replicating this issue, are you still experiencing it? And if so could you check if you have any errors in the background page as well? This page can be accessed from `More Tools -> Extensions -> Bitwarden - Free Password Manager -> Details -> Inspect views -> background.html`.

Does the spinner always show or only sometimes?

Thanks.

**Comment by Siraman25** [comment]
I also have this exact issue. I use Brave: [Version 1.35.100 Chromium: 98.0.4758.87] on Manjaro Linux. I also have the issue where the extension auto-locks itself on browser restart, even if set to never lock.

**Comment by juliienp** [comment]
Hello @Hinton, 
This afternoon everything went back to normal !
I tried to logout and login after creating this ticket, but still had the same problem.

Now the plugin works great !
I will let you know if I get this misbehaviour again

**Comment by Siraman25** [comment]
I actually solved it thanks to this reply on another issue: [2337#issuecomment-1037969153](https://github.com/bitwarden/browser/issues/2337#issuecomment-1037969153)

**Comment by juliienp** [comment]
Step to replicate : 

1. From the Bitwarden plugin settings : "Lockout now"
2. Close the browser
3. Open the browser
4. Log-in
5. Infinite loader

**Comment by ginat** [comment]
@juliienp are you still running into this issue?

**Comment by juliienp** [comment]
Hello @Hinton !
The 1.56.5 version seems to fix my issue. 😄 
But now : 
1. I press "Lock now",
2. close the browser
3. re-open the browser
4. Bitwarden is already unlocked

My configuration : 
- Expiration delay : never

**Comment by cscharf** [comment]
Hi @juliienp , I'm going to close this issue and open a new one with what you have if I can't find an existing one. This has been the behavior for some time now although speaking with Kyle it's not intended and we have a [potential fix](https://github.com/bitwarden/jslib/pull/684) queued for the next release, but it'll just need some testing/vetting.
