### ISSUE TITLE
Unnecessary log in friction

### ISSUE THREAD

**Issue by arantius** [bitwarden/browser#238]
In LastPass when I click the toolbar button (Or press Alt-I) I can just type my password:

![image](https://user-images.githubusercontent.com/84729/30564452-f3896938-9c92-11e7-977b-f7f73f60ac2a.png)

I do this frequently.  Being ~one click away is a valuable feature.  Create account is at the bottom.  (Plus I get a variety of nice auto-log-out settings.)

In BitWarden, I get:

![image](https://user-images.githubusercontent.com/84729/30564506-1f9a3e1c-9c93-11e7-8888-a543d09d1430.png)

The dialog with one click, mouse way down, log in with another click*, then I have to type my email, then finally I can type my password and log in.  This is too much work.  Please optimize the common use case.

\* And the "log in" link is dark-anti-pattern severely de-emphasized.  The "create account" link is big and bold and blue, though any given person only needs it once.

I think: if I've logged in once, give me a "remember email" check box, and if I check it, the dialog should open straight to the "log in" form, password field focused.

**Comment by kspearrin** [comment]
Logging in should only need to be done once. Why are you having to log in so much/often?

**Comment by arantius** [comment]
There are valid reasons to not leave myself logged in to my password manager forever in all circumstances.

**Comment by kspearrin** [comment]
This is why we have locking. See Settings → Lock Options.

**Comment by kspearrin** [comment]
Closing this since we already have a solution with Lock Options.
