### ISSUE TITLE
Vault Timeout settings on 'never' doesn't work since version 1.56.4

### ISSUE THREAD

**Issue by stephanedupont** [bitwarden/browser#2383]
### Steps To Reproduce

Since version 1.56.4, the extension always need me to re-enter my master password, even if the "Vault Timeout" settings is on "never".

### Expected Result

I should not have to sign-in again to Bitwarden.

### Actual Result

Almost each time I close my browser, I need to sign-in again to Bitwarden extension with my master password

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Latest Chrome

### Build Version

1.56.4

**Comment by ginat** [comment]
@stephanedupont Thank you for submitting an issue! We have reproduced this on 1.56.4 and working on a fix now. See this reply for a temporary resolution until we publish a permanent fix: https://github.com/bitwarden/browser/issues/2337#issuecomment-1038588746.

**Comment by eliykat** [comment]
This is now fixed in 1.56.5.
