### ISSUE TITLE
Modifying vault triggers very high CPU usage/freezing on macOS+Firefox

### ISSUE THREAD

**Issue by lyndsysimon** [bitwarden/browser#239]
Whenever I add, edit, or remove a login from my vault, Firefox freezes for an indeterminate amount of time. Force killing Firefox and re-opening it resolves the issue.

This is happening for me on macOS 10.12.6, running Firefox Nightly 57.0a1 (2017-09-19), and has been happening since I installed the extension, approximately two weeks ago. In IRC, @kspearrin reports the same behavior using Firefox 55.

It also seems to correlate with larger vaults; I have ~800 logins in mine.

**Comment by kspearrin** [comment]
This seems related to crypto functions getting invoked on the vault after the decrypted cache is cleared. Decrypting a vault with hundreds of logins doesn't seem to be performing well on Firefox + macOS.

**Comment by kspearrin** [comment]
This should be resolved in the latest versions. @lyndsysimon Can you check please?

**Comment by kspearrin** [comment]
Closing it since it is resolved from my testing...

**Comment by lyndsysimon** [comment]
Sorry for the delay - yes, it appears to be resolved on my end as well. Thank you :)
