### ISSUE TITLE
Vault always lock if you set a timeout or browser restart without quitting Chrome.

### ISSUE THREAD

**Issue by rafa2mac** [bitwarden/browser#2395]
### Steps To Reproduce

1. Open the browser vault settings in Chrome
2. Set the Vault Timeout "On Browser Restart" or any kind of time minutes (Lock or Logout)
3. Close every single page on Mac without actually quitting the browser.
4. Open a new page.

### Expected Result

The vault is not locked. It would lock once the time previously set expired or if you totally quit chrome (CMQ+Q)

### Actual Result

The vault lock every time you reopen a new window even though the time set is not expired or if the Chrome was not closed. 

### Additional Context

I tested the extension in Firefox and Safari: it is working ok. When you select "On Browser restart" you close all the windows without quitting the actual browser, you reopen a new page: the vault had not locked.

I also can confirm that the issue wasn't happening with Chrome 97.0.4692.71. I was able to downgrade and check that it works properly. The problem is with 98.0.4758.80.

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Chrome

### Browser Version

98.0.4758.80

### Build Version

1.56.5

**Comment by binarykitchen** [comment]
Yep, same here, and it's pretty annoying. 

It looks like a recent, big update caused this. Recommend fixing this whenever you're able because we truly love and appreciate your hard work. Peace out.

**Comment by rafa2mac** [comment]
> Yep, same here, and it's pretty annoying.
> 
> It looks like a recent, big update caused this. Recommend fixing this whenever you're able because we truly love and appreciate your hard work. Peace out.

Definitely agree! The password manager is one of the best. Look forward to seeing this bug resolved.

**Comment by tcosmo** [comment]
I have the bug too :'( it is quite annoying. For me the bug happens quite randomly: after some period of time my bitwarden on all my computers that use Chrome locks out even thought I have chosen "Browser restart" timeout.

**Comment by JourneyOver** [comment]
Happening to me as well even though I have mine set to "never", I've even tried setting a custom time with the time set to 250000 hours and it'll still randomly lock itself and well I don't think it's been anywhere near 250000 hours (28 years) since it was last locked xD Would love to see this fixed!

**Comment by Hinton** [comment]
I've managed to replicate this on chrome version 98 on macOS. Unfortunately there's not much we can do from our side, the extension background page is completely removed when all chrome windows are closed which prevents us from safely storing any state.

**Comment by turkeyphant** [comment]
Same issue here on Windows and Chrome 98.

**Comment by wenkunst** [comment]
Same problem here on macOS 10.14 and Chrome 98.0.4758.102. I use the setting system lock

**Comment by rafa2mac** [comment]
> I've managed to replicate this on chrome version 98 on macOS using the vault timeout "On Restart". Unfortunately there's not much we can do from our side, the extension background page is completely removed when all chrome windows are closed which prevents us from safely storing any state.

This is very unfortunate. I tested today on Edge and it works properly. Is there any chrome://flags that can be change to fix this? Thanks for your excellent work anyway

**Comment by rafa2mac** [comment]
Is there any update that might fix this issue on chrome? Every other browser works fine. I have been for a few weeks on Edge and never had the issue described above.

**Comment by swinggraphics** [comment]
Still broken here. Easy to reproduce.

**Comment by WillFP** [comment]
Still broken - set to never and it locks constantly

**Comment by rafa2mac** [comment]
It worked properly for a couple of weeks but this morning I updated to the new Chrome 100.0.4896.60 and it's not working anymore.

**Comment by rafa2mac** [comment]
> @WillFP That sounds like a different issue. I've had reports from others that it started working after reinstalling the extension.

It works on my end if I set it to never. It doesn't work with any other options. I have been using On Browser Restart for years and not each time the last Chrome page is closed, it gets locked. Sad cause I thought the issue was resolved with version 99. Today's update (100) broke the extension again. Wondering if the Bitwarden team can somehow communicate with the Chrome team to get this addressed. I really don't want to migrate to another browser.

**Comment by Hinton** [comment]
The Chromium bugtracker is publicly available at https://bugs.chromium.org/p/chromium/issues/list. We don't have any secret communication channel unfortunately.

**Comment by rafa2mac** [comment]
> The Chromium bugtracker is publicly available at https://bugs.chromium.org/p/chromium/issues/list. We don't have any secret communication channel unfortunately.

Ok, understood. Hopefully this will be resolved.

**Comment by rafa2mac** [comment]
Update. I just tried Chrome Canary Version 102.0.4974.2 and the vault settings work properly. So hopefully the next updates of the regular Google Chrome will fix this.

**Comment by ndevenish** [comment]
I get this behaviour on Mac, but without closing windows. Browser windows with tabs I have had open all day constantly lock themselves.

**Comment by clickyfreewheel** [comment]
Looks like this issue is caused by allowing the browser extension to run in private windows. On Firefox for MacOS, disabling this fixed the issue for me

**Comment by lkeels** [comment]
This problem still persists and is also present in Edge now.

**Comment by rafa2mac** [comment]
> This problem still persists and is also present in Edge now.

Yes. I totally gave up on this. Now they state on their website that this is normal behaviour. I don't understand why keep the timeout options since they don't work if you close your browser.

**Comment by lkeels** [comment]
It's absolutely ridiculous. I'm having to unlock my vault almost as much as I'd have to type a password, making the product all but useless. It looks like going back to LastPass is the only way to get proper functionality back.

**Comment by Hinton** [comment]
As previously mentioned, this is an upstream issue. Bitwarden only persists the state in memory, recent changes to Chrome causes our "background page" to be closed when no chrome windows are opened. This is unfortunately not something we can resolve at this point without persisting sensitive information to disk.

**Comment by swinggraphics** [comment]
With the stated reason that you can't keep track of time when the window closes without saving sensitive information to disk, there's additional absurdity here because BW will stay unlocked in Chrome when the app is quit and even when the entire system is restarted. Please, by all means, go ahead and save a tiny bit of "sensitive information" to disk, because without that, BW is just always unlocked, which is much less secure. It just doesn't make any sense.

**Comment by ndevenish** [comment]
> recent changes to Chromium causes our "background page" to be closed when no chrome windows are opened

Right, but it’s also doing it without closing chrome windows.

**Comment by praiford98** [comment]
I am having the same issue. I am using Chrome (109.0.5414.119) on Mac OS 12.6.2. No matter what i set the lockout to, Bitwarden always locks when i close all the windows and reopen. The only exception is when I set it to never and then it will not lock up. I never had this issue with Lastpass. It seems to work fine on Safari except if I quit Safari and go back in, Bitwarden is locked even though I set it to a four hour window but if  I just close the window and go back in, it is still unlocked. Chrome locks Bitwarden if I close all the windows but I don't quit Chrome.

**Comment by psdevhh** [comment]
Same issue here, Bitwarden bugs me with the master password after every browser restart despite it being set to only lock after 720 hours.
Back to Lastpass I guess.

**Comment by poebrand** [comment]
Same issue here. Details:
- Windows 10, 64 bit
- Chrome: 109.0.5414.121
- Bitwarden extension: 2023.1.0
- Vault timeout: Custom
- Hours: 168

Every time I restart the computer or exit Chrome and reopen, I have to log in again to Bitwarden with master password.

**Comment by scmanjarrez** [comment]
This also happens in firefox, I don't have bitwarden enabled in private windows.

Extension info:
© Bitwarden Inc. 2015-2023
Version: 2023.4.0
Server version: 2023.4.3 

Firefox info:
113.0.2 (64-bit)

**Comment by ggrrll** [comment]
same in brave [Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by trmartin4** [comment]
@rafa2mac we would like to close this issue if it is no longer occurring.  Please let us know if you continue to experience unexpected locking.

**Comment by swinggraphics** [comment]
The problem still exists.

**Comment by Borinius** [comment]
Still an issue on chromium.

**Comment by LaurensvanG** [comment]
Related to this, I also still think it is ridiculous that I cannot stay logged in after a restart. I know it is supposed to be to enhance 'security'. In the end, this just results in me setting an easy pin as I have to reenter it so often. With Dashlane I used my difficult password to log in every 3 days. It makes me consider switching back or setting timeout to Never, which is even worse.
I understand you disagree on which method is more secure. But maybe let the user decide which risks to take instead of forcing everybody to use your idea of security.
