### ISSUE TITLE
Safari extension disappeared

### ISSUE THREAD

**Issue by Sonisan** [bitwarden/browser#2399]
### Steps To Reproduce

1. Open Safari

### Expected Result

Bitwarden extension should be in Safari's toolbar and in Safari < Preferences < Extensions.

### Actual Result

Bitwarden extension is no longer present in Preferences < Extensions nor in Safari's toolbar. Browser integration is enabled, and I have already tried to uninstall/install the app again with no success.

### Additional Context

Everything was working fine a few days ago, I suspect the last update through the App Store broke something. A similar issue happened a few weeks ago, IIRC. 

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Safari

### Browser Version

15.3

### Build Version

Version 1.31.3 (2320)

**Comment by SergeantConfused** [comment]
Hi there,

Please first install Safari Technology Preview, reboot, and check if that restores your Bitwarden Safari extension; If it did not, please install OnyX and run a system clean-up, reboot, and test that once more. You can learn more on this behaviour here: https://github.com/bitwarden/browser/issues/1696

I hope you find this clear and helpful. If you encounter any further trouble with this, please create a support ticket using this form: https://bitwarden.com/contact/

**Comment by Sonisan** [comment]
Hi,

Reinstalling Safari Technology Preview (without even opening it!) instantly triggered a banner on the regular Safari asking if I want to install the Bitwarden extension. Now that I remember, I have uninstalled Technology Preview a few days ago.  
Really strange behaviour...

Thank you for your help.
