### ISSUE TITLE
Search won't clear itself out easily

### ISSUE THREAD

**Issue by edouardmenayde** [bitwarden/browser#240]
Hi there :-)
Just some suggestions regarding the search field :

- The search field could be improved by having a little icon just to clear it quickly
- The search field could be improved by clearing its content when clicking on vault (and maybe even the bitwarden icon) (I personally automatically think it's gonna send me back to my password list)

**Comment by kspearrin** [comment]
Your first point is already done.... there is an X.

**Comment by edouardmenayde** [comment]
That's my bad I posted in the wrong repository never mind...

**Comment by kspearrin** [comment]
This is still the case on Android.

**Comment by jjfrv8** [comment]
Am I looking in the wrong place?  I don't see an X to clear the search expression either in the browser extension or the web vault.  I've checked it on Firefox and Chrome/Chromium in Windows and Xubuntu.
