### ISSUE TITLE
Autofill on page load default changed in 1.56.0

### ISSUE THREAD

**Issue by EDIflyer** [bitwarden/browser#2400]
### Steps To Reproduce

Update extension from 1.55 to 1.56.x

### Expected Result

Autofill settings to remain unchanged

### Actual Result

Autofill on page load default changed to 'do not fill' although feature remains active (still able to trigger with Ctrl-Shift-L or clicking button in the extension to autofill.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13610277/154841865-275da83b-9d0d-4c3d-bc7a-04d6ac6faf66.png)

### Additional Context

See discussion at https://community.bitwarden.com/t/chrome-auto-fill-broken-since-1-56-0/38222/9

It is confusing for users for this functionality to stop working without warning.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Build Version

1.56.6

**Comment by eliykat** [comment]
Hi @EDIflyer, thanks for letting us know about this. This is a bug and will be fixed shortly.
