### ISSUE TITLE
Closing bitwarden while it's saving a change discards the change

### ISSUE THREAD

**Issue by passcod** [bitwarden/browser#241]
Firefox Nightly, extension v1.16.3

Changes are not saved instantly, they often take a few seconds to save, with the little spinner animation when clicking the save button. That's... annoying, but fine.

The very painful part is that if I close bitwarden (which happens if I try to do _anything else_ but waiting for the save to finish), all the changes are discarded. That is surprising and not obvious at all. It would be much better and safer for save operations to continue in the background even if the bitwarden UI is closed.

**Comment by kspearrin** [comment]
All operations are currently done on a background thread in the extension so I am unsure as to why closing the popup has any effect on a pending save operation.

**Comment by scheinercc** [comment]
I was just about to log the same issue, though I am having for as long as using the extension. Current versions: Firefox 60.0a1 (2018-03-09) and Bitwarden 1.24.0

My main example are logins I add manually: 
1) Add a new test user for Github
2) Hit save
3) Remove focus from Bitwarden doorhanger/popup before save has been finished
4) Open BW doorhanger and search for new user

**Comment by Aaron1011** [comment]
This also occurs when editing a vault entry - removing focus from the Bitwarden popup causes any unsaved changes to be lost. It would be nice if the popup restored the last open sub-page/section when closed and reopened.

**Comment by BVollmerhaus** [comment]
Same for adding new entries, it would be nice to not discard any of the popup contents when it is closed and just resume where the user left off. I often copy & paste information from somewhere else when adding new vault entries and loosing everything because I clicked somewhere else is really irritating.

**Comment by davidus05** [comment]
#push - this would be a really nice thing.

**Comment by passcod** [comment]
Well, this still happens.

**Comment by dwbit** [comment]
Hey everyone, this conversation can be continued in the [community forums](https://community.bitwarden.com/t/persist-bitwarden-ui-and-maintain-entered-data-previously-unsaved-changes-are-lost-when-move-to-another-item/5470)

**Comment by passcod** [comment]
Oh it's good news that it's tracked somewhere. At least there's a chance it will be fixed in the next... 5 years.

**Comment by dwbit** [comment]
Hey @passcod, do you use the Firefox sidebar? It creates a persistent experience for editing credentials.

**Comment by passcod** [comment]
Sometimes, but it's not as convenient. For point of reference Lastpass (for all its other faults) is perfectly capable of this.
