### ISSUE TITLE
Can't login to self-hosted vault after version 1.55

### ISSUE THREAD

**Issue by er0k** [bitwarden/browser#2410]
### Steps To Reproduce

1. Go to settings and set custom environment with self-hosted URL. Save
2. Try to login
3. Get error: "An unexpected error has occurred"

### Expected Result

I should be able to login to my vault

### Actual Result

I cannot login to my self-hosted vault via the browser extension. 

I can login fine through the web UI. 

I can login fine if I downgrade the browser extension to 1.54. 

I cannot login with versions 1.55 or 1.56.

Same result with Firefox and Chromium.

### Additional Context

Running the latest version of Bitwarden 2.26.1 in docker.

I have the same results on two machines (one debian bullseye, one is debian sid) and both are resolved by downgrading the browser extension to 1.54, which seems a pretty clear indication this bug was introduced in version 1.55.

### Operating System

Linux

### Operating System Version

debian 11

### Web Browser

Firefox

### Browser Version

98.0b7

### Build Version

1.55.0

**Comment by t3dium** [comment]
Don't have this issue with my selfhosted instance, have you visited the url at least once and accepted the self-signed certificate warning, _(assuming you used self signed ssl)_, before logging into bitwarden? If that doesn't fix it, maybe try installing the cert systemwide, or make sure you made an [.ext file](https://github.com/dani-garcia/vaultwarden/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome) when creating the certs.

**Comment by er0k** [comment]
I don't use a self signed cert. I have a valid, not-expired certificate from Let's Encrypt. As I mentioned, I can login just fine via the web UI, so I don't think it is a cert issue.

**Comment by er0k** [comment]
Well, now I'm even more confused :confused:  I started trying to debug this and was able to reproduce the "unexpected error" on version 1.56.6. I saw 2 requests:

1. `POST /accounts/prelogin`
2. `POST /connect/token`

Both got 404 responses and Bitwarden said "An unexpected error has occurred"

I downgraded to 1.54 and watched the requests, I saw 4:

1. `POST /api/accounts/prelogin`
2. `POST /identity/connect/token`
3. `POST /identity/connect/token`
4. `GET /api/sync`

All got 200 responses and I logged in as expected. 

So 1.56.6 was making requests to the wrong endpoints (`/accounts/prelogin` instead of `/api/accounts/prelogin` and `/connect/token` instead of `/identity/connect/token`). 

But when I upgraded back to 1.56.6 after this test, the requests are being made to the correct endpoints, and I can login normally again.

I'm inclined to close this since it's working for me now, but maybe someone could shed some light on why the extension would be making requests to the wrong endpoints, but then fix itself after re-installing? Perhaps some issue with updating the extension within Firefox? It seems after installing and re-installing the extension a few times it finally shook something loose :shrug:

**Comment by eliykat** [comment]
@Hinton is this related to you moving the `prelogin` endpoint into the Identity service?

**Comment by Hinton** [comment]
@eliykat no we haven't updated the clients outside development. This seems more like an issue in the state migration.

@er0k Can you verify the environment urls?

**Comment by er0k** [comment]
ah, I think I see the issue now. When I fill in the all of the fields for the custom environment URLs, it fails with the 404s. When I _only_ fill in the Server URL, it works as expected.

So this fails in 1.56.6 (but works in 1.54):

![bw-bad-urls](https://user-images.githubusercontent.com/916239/156950374-d0cb709d-7142-4c7c-9018-fd2ee0d9afba.png)

and this works:

![bw-good-url](https://user-images.githubusercontent.com/916239/156950382-8bc47d77-d8a4-4553-973a-34825ce3b805.png)

**Comment by eliykat** [comment]
Glad you got it fixed. There is no need to set the individual URLs in most cases, if you're using a standard server config then you can just give it the base URL and it will do the rest. We did make some changes recently to how URL configuration is handled by the client, that would've exposed this misconfiguration.

**Comment by er0k** [comment]
thanks!
