### ISSUE TITLE
Make the "Start the Bitwarden Desktop application" dialog a bit less "dramatic"?

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/browser#2412]
### Steps To Reproduce

Perhaps not a bug, more a feature request...not sure (feel free to close/transfer this to feature requests if it turns out to fall more on that side)

1. When not logged in yet, and without the desktop application running, open the Bitwarden extension window

### Expected Result

While yes, the extension should let me know that I can't log in using biometrics etc which are provided by my operating system/platform as only the Bitwarden Desktop app can access those(?), it would be nicer if this message was a bit less dramatic looking. Rather than a modal dialog that I first need to OK before being able to just use my master password manually, just have it inline as a boxout as part of the regular login view. No need to doorslam the user who may quite consciously not have the desktop app running at that point.

### Actual Result

Firing up the extension's popup first briefly shows the dialog that is trying to trigger the biometric authentication/Windows Hello/etc via the Desktop app. That immediately fails when the app is not running, and the scary looking dialog appears that requires the user to first OK it before being able to log in using their master password. Subjective perhaps, but this looks unnecessarily alarming, and adds an extra step before being able to log in.

### Screenshots or Videos

![screenshot of the current scary looking dialog](https://user-images.githubusercontent.com/895831/155711223-bd370d92-3a7e-4b2d-bb6d-25972838029f.png)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Build Version

1.56.6

**Comment by Hinton** [comment]
Hi @patrickhlauke,

I agree, the forum thread for this community contribution, https://community.bitwarden.com/t/automatic-biometrics-prompt-on-open-popup/17383 highlighted this as a possible ux concern. Which is also why this behaviour is opt-in and not opt-out. Ideally the lock page should check if the desktop app is available and if not show a friendly message instead of the optrusive dialog.

I'm partially split on how to track this issue, as it's both a feature request and an ux "defect". For now I'll leave it open for higher visability.

**Comment by patrickhlauke** [comment]
Ah, thanks for the pointer to the community contributions discussion @Hinton ... sorry for adding to the "is it a request or bug" dilemma ;)

**Comment by patrickhlauke** [comment]
The new behavior in 1.58.0, where it shows a discrete little "Error" rather than the frantic dialogs/alerts, is much appreciated. Closing this.

![screenshot of the new static error message that replaced the two alerts - ERROR: The Bitwarden Desktop application needs to be started before this function can be used.](https://user-images.githubusercontent.com/895831/165356591-8159d024-5e7a-42aa-9632-98ade8d6c55c.png)
