### ISSUE TITLE
Browser plugin reverting to master password even when PIN set

### ISSUE THREAD

**Issue by EDIflyer** [bitwarden/browser#2429]
### Steps To Reproduce

1. Set unlock to PIN
2. Prompted for master password instead

### Expected Result

To be asked for PIN

### Actual Result

Sometimes (generally after PC reboot) asked for master password instead of PIN

### Screenshots or Videos

PIN settings:
![image](https://user-images.githubusercontent.com/13610277/156543625-853d0a95-8ab1-4864-81f2-bdff099d8f8a.png)

Master pwd prompt on reboot:
![image](https://user-images.githubusercontent.com/13610277/156544078-84ece980-c75d-4a0b-8c16-c8ca19233a57.png)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

99.0.4844.51

### Build Version

1.56.6

**Comment by Hinton** [comment]
Can you verify that "Lock with master password on browser restart" is disabled? 
![image](https://user-images.githubusercontent.com/137855/156598396-88923ba7-2ab0-4a7c-98a6-30f0b47b9cc2.png)

**Comment by EDIflyer** [comment]
Hi @Hinton there's not a way to check the current setting as far as I can see - every time you click 'unlock with PIN' then it just shows the blank PIN with the lock button ticked.  Could it be it's defaulting to this being lock everytime and/or not respecting when it is unticked? It certainly worked fine previously so I wonder if it got reset when I upgraded (a bit like happened for me with #2400)

**Comment by ginat** [comment]
Hello! Are you still having issues with this? I re-checked Unlock with PIN (with lock with master password not checked) and it was working consistently on Firefox and Chrome.

**Comment by EDIflyer** [comment]
@ginat seems OK for me now - I think the issue was a default being reset.

**Comment by djsmith85** [comment]
@EDIflyer Thank you for reporting back on this. 

Closing this now, as the issue has been resolved.
