### ISSUE TITLE
Autofill is not working on site online.sberbank.ru

### ISSUE THREAD

**Issue by GitUser200607** [bitwarden/browser#2430]
### Steps To Reproduce

1. Go to 'https://online.sberbank.ru'
2. Try to Autofill login and Password fields. Even with the usage of custom fields name the fields will stay empty.
There is a feeling, that after fill the fields are force empty again.

### Expected Result

The fields have to be filled with Login or Password data.

### Actual Result

The fields are empty

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

97.0.1 (64-bit)

### Build Version

1.56.6

**Comment by Hinton** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
