### ISSUE TITLE
Dark mode now blue in both Edge and Firefox

### ISSUE THREAD

**Issue by github-account1111** [bitwarden/browser#2436]
### Steps To Reproduce

1. Enable Dark Mode (not Nord or Solarized).
1. Open the extension popup.

### Expected Result

The extension has a neutral dark color scheme like it did before and blends in well with other software.

### Actual Result

The extension is blue in dark mode which looks out of place in both Firefox and Edge as well as the overall Windows dark theme (all of which use black or a neutral shade of gray).

Also in Firefox it has small black curves slightly above the corners which look awkward.

### Screenshots or Videos

![edge](https://user-images.githubusercontent.com/5728319/156966297-ce76b7a4-6c38-4866-8dd6-6f0fdaeb8fbf.PNG)
![firefox](https://user-images.githubusercontent.com/5728319/156966309-08e631e9-746d-4a72-9b3e-a8b5b2d6e0ac.PNG)

### Operating System

Windows

### Web Browser

Microsoft Edge, Firefox

### Build Version

1.56.6

**Comment by Hinton** [comment]
Hi @github-account1111,

The Firefox extension popups all have rounded corners, it's a fairly recent design change from mozilla and not something we can nor should change.

The dark theme design was updated in https://github.com/bitwarden/browser/pull/2241 to better match across platforms, and is not a bug.

**Comment by github-account1111** [comment]
@Hinton I don't have a problem with rounded corners.
As I said in the post, the problem is the small black curves slightly _above_ the corners inside the popup body.
You might need to zoom in on the second screenshot to see them.

>The dark theme design was updated in https://github.com/bitwarden/browser/pull/2241 to better match across platforms, and modifying it would be a feature request not a bug report.

Then I have to ask: how is blue more cross-platform than dark gray?
It went from matching everything to matching nothing in my system (except for Github maybe which I've always disliked for the same reason of looking out-of-place).
