### ISSUE TITLE
Can not select a UPS service shipping method with bitwarden active

### ISSUE THREAD

**Issue by airy52** [bitwarden/browser#2439]
### Steps To Reproduce
Go to: https://www.ups.com/ship/guided

1. Have bitwarden extension enabled.
2. fill out a from and to address in UPS
3. Try to select a shipping method (next day, ground, etc)
4. Click next and it will say "Must select a shipping method"

### Expected Result

Expected result is that their website works.

### Actual Result

Website does not work.

### Additional Context

I notice when inspecting the radio button element thats hidden in the shipping service buttons, it has "modified by bitwarden" or something like that in it, so I disabled bitwarden and the page suddenly works.

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

98.0.4758.102 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}

### Build Version

1.56.6

**Comment by ginat** [comment]
Hello! Are you having issues at this step (screenshot attached)? Do you have any vault items saved for USPS? What does the screen look like?
<img width="790" alt="Screen Shot 2022-03-15 at 3 18 18 PM" src="https://user-images.githubusercontent.com/5688240/158481800-df813a1e-1b73-4a6e-91f1-a8aa1ead608c.png">

**Comment by djsmith85** [comment]
Hi @airy52, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
