### ISSUE TITLE
Auto-fill feature cause scroll freezes on Twitter

### ISSUE THREAD

**Issue by Alex0007** [bitwarden/browser#244]
When auto-fill is enabled and you're trying to scroll twitter feed, you can notice UI freeze for 1-2 seconds

Firefox Nightly 58.0a1 (2017-09-23) (64-bit)
Ubuntu 17.10

**Comment by kspearrin** [comment]
I wonder if this is an Ubuntu thing since it doesn't seem to be an issue on Windows for me.

**Comment by kspearrin** [comment]
related https://github.com/bitwarden/browser/issues/232

**Comment by kspearrin** [comment]
Can you update to 1.17.0 and see if anything changes?

**Comment by Alex0007** [comment]
I'm not sure, but at least i don't see "slow script" warnings now

**Comment by Alex0007** [comment]
Nope, it's still slowing down.

**Comment by kspearrin** [comment]
This is fixed for our next version. See #232
