### ISSUE TITLE
[Auto-fill] Struggling on local (sefhosted) websites

### ISSUE THREAD

**Issue by Pheggas** [bitwarden/browser#2441]
### Steps To Reproduce

1. Selfhost app with Web UI
2. Enable login for Web UI
3. Set up new login in Bitwarden where in site you put local IP of machine that is running that service with Web UI (Let's say the IP and port of Web UI for service is 192.168.1.25:5000/login)
4. Set up similar fake login with different port (like 192.168.1.25:6000/signin)
5. Enable auto filling
6. Head into login prompt to force bitwarden to fill it up
7. See the issue with filling up credentials from second website

### Expected Result

As i have specified IP and also port, and not only IP, it should see on which website Bitwarden is and fill it up with correct, correspondent credentials.

### Actual Result

Instead, Bitwarden fill up credential texboxes with credentials from different selfhosted website.

### Screenshots or Videos

Filled in credentials for Portainer rather than Paperless-ng (even if they're, obviously, each on different port, same IP tho)
![image](https://user-images.githubusercontent.com/9994511/157608058-78272ca2-5116-41d4-a69c-0f1731592c8d.png)

And for Portainer, it filled up credentials for Mealie (selfhosted service)
![image](https://user-images.githubusercontent.com/9994511/157608404-01b1b7eb-2f45-4202-a74e-a51d5248be54.png)

### Operating System

Windows

### Operating System Version

Version 21H2

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.102 (64-bit)

### Build Version

Version: 1.56.6

**Comment by Pheggas** [comment]
There's actual setting for this [found in bitwarden's documentation](https://bitwarden.com/help/uri-match-detection/). Closing.

**Comment by reinux** [comment]
Just for anyone else coming across this who finds the documentation somewhat opaque (even as a webdev myself):

The relevant section of the docs is the [Match detection options](https://bitwarden.com/help/uri-match-detection/#match-detection-options). Specifically, you want to set it to Host under the Auto-fill options:

<img width="478" height="1149" alt="Image" src="https://github.com/user-attachments/assets/182897b7-120c-4a44-8a2a-7e0d8078200c" />
