### ISSUE TITLE
Bitwarden do not fill in username on QNAP NAS login page

### ISSUE THREAD

**Issue by benzBrake** [bitwarden/browser#2443]
### Steps To Reproduce

1. Go to QNAP NAS login page
2. Wait for bitwarden auto fill

### Expected Result

Both username and password all filled

### Actual Result

Only password was filled.

### Screenshots or Videos

https://user-images.githubusercontent.com/11323774/157672181-e526c17d-03b1-4ffd-a9e2-3f391e87e035.mp4

### Additional Context

I have tested on 360chrome browser too, same problem.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

Developer 98b2

### Build Version

1.56.6

**Comment by djsmith85** [comment]
Hi @benzBrake and thank you for your report. This is a known issue with the QNAP login page and is being tracked at https://github.com/bitwarden/browser/issues/1214

Closing this as duplicate.
