### ISSUE TITLE
Bitwarden Safari Extension dissapeared

### ISSUE THREAD

**Issue by ncodee** [bitwarden/browser#2446]
### Steps To Reproduce

As per title, the extension seems to have randomly dissapeared from the Safari extensions. I've tried restarting Safari, and reboot the system, but it still doesn't appear under Extensions.

I feel this is had occured from an recent automatic update via the App Store. I also have 'Enable Browser extension' enabled through the macOS app.

### Expected Result

Not dissappear.

### Actual Result

Disappeared randomly.

### Operating System

macOS

### Operating System Version

12.3

### Web Browser

Safari

### Browser Version

15.4

### Build Version

1.31.3 (2320)

**Comment by eliykat** [comment]
Hi @ncodee, this is a known issue reported in #1696. Please try the workarounds suggested: [here](https://github.com/bitwarden/browser/issues/1696#issuecomment-873717947), [here](https://github.com/bitwarden/browser/issues/1696#issuecomment-874122595) and/or [here](https://github.com/bitwarden/browser/issues/1696#issuecomment-994730291). If you need any further help with this, you can contact our Customer Success team: www.bitwarden.com/contact/

I'll close this thread as a duplicate. Thanks!
