### ISSUE TITLE
Only add to the context menu when right clicking on a password/text box

### ISSUE THREAD

**Issue by forteller** [bitwarden/browser#245]
This might seem like a small issue. But when the [context menu looks like this](https://i.imgur.com/UalUO68.png) it would be nice if the Bitwarden part only showed up when it's actually needed.

Thanks!

**Comment by kspearrin** [comment]
Unfortunately this is not possible to do with the APIs available in Firefox

**Comment by kspearrin** [comment]
Or any other browser with web extensions *
