### ISSUE TITLE
Opening dialog to select attachment in Firefox Ubuntu extension closes the extension

### ISSUE THREAD

**Issue by Dechcaudron** [bitwarden/browser#246]
So when you try to select an attachment for an existing login, and you press the "Browse..." button, it does open a dialog of the file explorer to select the file in question, but in doing so the extension overlay is closed. Selecting the file after that has no effect. The file dialog closes, but the file is never uploaded or attached.

**Comment by kspearrin** [comment]
This is a known Firefox bug that has been open open for quite a while. See https://bugzilla.mozilla.org/show_bug.cgi?id=1292701

Unfortunately there's nothing we can do about it. You'll have to use the web vault.
