### ISSUE TITLE
Password Amazon.com and Amazon.de

### ISSUE THREAD

**Issue by stsax** [bitwarden/browser#247]
Hi, a password safe contains a login for www.amazon.com (us) and www.amazon.de (german). After the login on the german Amazon an error message is shown "false password", because the user and password for amazon.com (us) are filled in.

**Comment by kspearrin** [comment]
This is because the equivalent domain is associating the two together. Log into the web vault and navigate to Settings > Domain Rules and disable the Amazon rule.
