### ISSUE TITLE
When viewing PDF, closing the remember password prompt stops ability to use arrow keys to navigate PDF

### ISSUE THREAD

**Issue by MatthewHaskett** [bitwarden/browser#2473]
### Steps To Reproduce

1. Login to a website for which you have no saved login details to BitWarden.
2. Without closing the remember password prompt at the top, open a PDF in the same tab.
3. Note the ability to move through pages using arrow keys.
4. Close the remember password prompt.
5. Note that you can no longer move through pages using arrow keys.

### Expected Result

After closing the remember password prompt, the PDF should still be navigable via the arrow keys. 

### Actual Result

After closing the remember password prompt, the PDF is no longer navigable via the arrow keys. 

### Operating System

Windows

### Operating System Version

Windows 11 Home 22H2 22000.556

### Web Browser

Chrome

### Browser Version

Google Chrome 99.0.4844.82

### Build Version

1.57.0

**Comment by aj-bw** [comment]
Hi @MatthewHaskett ,

After reviewing the steps and versions provided I was unable to reproduce the issue. I could reliably arrow through PDFs opened in the Chrome browser regardless of any interaction or presence of the save password banner.

Between the date of you posting this issue and testing there have been updates to Google Chrome released. Please attempt to update and see if that resolves the issue. 

Feel free to contact our support team using our contact page, [https://bitwarden.com/contact](url) for additional assistance, you can include a link to this issue in the message content.
