### ISSUE TITLE
20% of Speedometer 2.0 score drop when bitwarden extension is active on any browser

### ISSUE THREAD

**Issue by LaurentOngaro** [bitwarden/browser#2474]
### Steps To Reproduce

1. install a browser or disabled all extensions in an existing one (to avoid cross influences)
2. go to https://browserbench.org/Speedometer2.0/ 
3. run the default test
4. install or enable bitwarden extension **AND log in**
5. run the same test
6. compare the scores

### Expected Result

no or small performance drop 

### Actual Result

tested with a fresh chromium installation on windows 11

- without bitwarden extension installed: score is 196.1
- with bitwarden extension installed and enabled but not logged in: score is 194.4
- with bitwarden extension installed and enabled WITH user logged in: score is 158 !

so nearly 20% of performance drop

Note that the same performance drop occurs when:

- using edge, firefox or brave browser
- using linux or windows (even if the score is higher on Linux)
- disabling the maximum of features in bitwarden options, including the domain detection

### Operating System

Windows, Linux

### Operating System Version

windows 11

### Web Browser

Chrome, Microsoft Edge, Firefox, Brave

### Build Version

latest

**Comment by LaurentOngaro** [comment]
Note that bitwarden extensions has no effect on a benchmark that mesures Webgl or computation performances (like https://browserbench.org/JetStream), but has some on responsiveness mesures (speedometer)

**Comment by djsmith85** [comment]
@LaurentOngaro: Thank you for your detailed report. 

Although I'd argue that this is not testing a very common scenario (complete refresh/re-drawing of a single tab 480 times).

I did run the test against the currently released extension and the build artifact from https://github.com/bitwarden/browser/pull/2447 (both on Chrome), out of curiosity, if that PR would improve the score.

After running both versions, I can report the changes made on https://github.com/bitwarden/browser/pull/2447 do improve the re-drawing speed (run of tests) and relates into a higher score.

From my experience the highest impact in performance is gained when disabling the context-menu or in the case of the PR, only refreshing it when necessary, if enabled.

This issue will be closed, once the linked PR is reviewed and merged.

**Comment by LaurentOngaro** [comment]
@djsmith85 I’m happy to help

Usually, the principle of benchmarks is not really to make a "real" test but to offer a point for comparison
I could make all my tests again when the binary release that includes the #2447 PR will be available
