### ISSUE TITLE
Unable to 2FA with Hardware Security Key on Linux

### ISSUE THREAD

**Issue by AlexTu2** [bitwarden/browser#2476]
### Steps To Reproduce

1. Login to a Bitwarden account with 2FA enabled for Hardware Security Keys (vault.bitwarden.com and the browser extension have the same issue)
2. Click on "Authenticate with WebAuth" 

### Expected Result

When logging into Bitwarden with 2FA on, Web Authn should allow me to use my Hardware Security Key to authorize. 

### Actual Result

When logging into the browser extension > prompts for new tab for auth. 

Clicking "Authenticate WebAuthn" gives error message "UnknownError: The operation failed for an unknown transient reason"

### Screenshots or Videos

Https://i.imgur.com/pYrVSqM.png

### Additional Context

Using Solokey V2 

### Operating System

Linux

### Operating System Version

Arch Linux 5.16.16-zen1-1-zen

### Web Browser

Firefox

### Browser Version

98.0.2 (64-bit)

### Build Version

1.57.0

**Comment by aj-bw** [comment]
Hi @AlexTu2 ,

Thank you for reaching out, however we were unable to reproduce this behavior. We'd like to assist you further. We ask that you please contact us using our contact page, here: [https://bitwarden.com/contact](url). You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by java427** [comment]
hey @AlexTu2 and @aj-bw 

Did you have a solution for this?
I do have the same problem on Firefox (Mac and Windows). I've been having it for months actually. So it happens on the current Firefox version and previous ones as well.
It works fine on Chrome.

My keys are also SOLO v1 and v2 (both have the same issue on Firefox). Is there a support page to troubleshoot the issue? Did bitwarden helped you @AlexTu2 ? How?

Thanks in advance

**Comment by philpennock** [comment]
After upgrading a vault to Argon2Id, the Firefox BW extension was unhappy (unlike the Chrome one) so I signed out and tried to sign in again, and I'm seeing the same thing.  Yubikey, Linux Firefox.  Yubikey 5C, and there's a PIN set for the FIDO2 presence.

In my case, unlike the OP above, I am using VaultWarden.  VW logs `POST /identity/connect/token => 400 Bad Request` which might help narrow it down.  (I am explicitly not asking for support for VW; I was able to log in with TOTP and am fine, I am only commenting on this issue in case the server 400 error helps the devs narrow down what might be happening here).

**Comment by wjam** [comment]
Commenting here in case anyone stumbles upon this issue while attempting to work out why WebAuthn keys aren't working in Firefox on Ubuntu (500 error when attempting to add a key in my case).

The answer, I found, was that the behaviour of Firefox becomes erratic if snap updates have been downloaded but not applied yet and so just applying the updates fixed the problem.
