### ISSUE TITLE
Ctrl+Shift+L keyboard shortcut no longer working on Firefox 98.0.2 on Windows

### ISSUE THREAD

**Issue by xeresblue** [bitwarden/browser#2483]
### Steps To Reproduce

1. Confirm that Ctrl+Shift+L is set as the auto-fill shortcut in Manange Extension Shortcuts.
2. Go to any site requiring a login.
3. Attempt to use Ctrl+Shift+L to auto-fill.
4. Reassign auto-fill to a different shortcut (I used Ctrl+Shift+1).
5. Auto-fill with new shortcut.
6. Attempt to reassign auto-fill to Ctrl+Shift+L.

### Expected Result

Shortcut should trigger auto-fill. If assigned to a different key binding, Ctrl+Shift+L should be assignable.

### Actual Result

When assigned by default to Ctrl+Shift+L, auto-fill does not trigger. Auto-fill works fine from the extension menu or context menu. If assigned to a different key binding (e.g. Ctrl+Shift+1), auto-fill shortcut works as expected. When I then attempted to reassign auto-fill to Ctrl+Shift+L, the box automatically clears as soon as I let go of the keys, retaining the "Type a letter" tool-tip--but does NOT display the "Can't override a Firefox shortcut" tool-tip as when you attempt to assign a pre-existing Firefox shortcut. Assigning any other non-conflicting key binding works as expected.

### Screenshots or Videos

![Default shortcut correct](https://user-images.githubusercontent.com/9220004/160933246-746072b3-4a4b-4e67-acf0-3211305f1d24.png)
Shortcut correctly assigned by default.

![Box clears when trying to assign](https://user-images.githubusercontent.com/9220004/160933327-b5101888-9f57-4f57-a1f0-29b31a4a0458.png)
Box clears when trying to assign back to Ctrl+Shift+L after changing.

### Additional Context

I uninstalled and reinstalled the extension during the troubleshooting process. This is the only way I was able to get Ctrl+Shift+L assigned again (but it still didn't function). No problems on other browsers and no extension shortcut conflicts.

### Operating System

Windows

### Operating System Version

10 x64

### Web Browser

Firefox

### Browser Version

98.0.2

### Build Version

1.57.0

**Comment by kopkako** [comment]
This is actually also not working in the latest Safari (Version 15.4 (17613.1.17.1.6)) on macOS (latest version, 12.3)

**Comment by xeresblue** [comment]
Turns out I was running Vivaldi at the same time, and the BW extension on Vivaldi was stealing focus from the one on Firefox. Closing Vivaldi resolved the issue.

**Comment by luca-rui** [comment]
Nice hint, had the same issue and closing the Arc browser solved it for me.

**Comment by unikitty37** [comment]
The keyboard shortcut in Vivaldi can be set to run only in Vivaldi if you don't want it to be global:

![image](https://github.com/bitwarden/clients/assets/139183/a55a2138-9446-4809-8568-aa49c8a3a1d7)

But even if I do this, the shortcut still doesn't work in Firefox. Selecting the "keyboard shortcuts" option on Firefox just takes me to https://bitwarden.com/help/keyboard-shortcuts/ rather than a page where I can change the shortcuts — and the shortcut listed does nothing when I press it!

I'm a web developer, and need to have multiple browsers open at a time — and to have the Bitwarden auto-fill work in all of them, ideally from the shortcut rather than having to click on the icon. Having to quit all other browsers is _not_ an acceptable solution!

**Comment by rowansmithau** [comment]
well i am glad to hear it's not just me @coryfklein . I have the shortcut working fine on one sonoma machine, but not on another. the one that is working is using firefox 119, while the not working one is using firefox developer edition (119.0b9). what browser version are you using?

**Comment by coryfklein** [comment]
I'm on 119, so perhaps it's a bugfix in 120?

**Comment by coryfklein** [comment]
Weird, this morning now suddenly my new ⇧ ⌘ M keyboard shortcut _stopped working_, but I used the instructions above to set it back to ⇧ ⌘ L and now *that* is working again.

**Comment by kylerm42** [comment]
I've had to switch back and forth from the default shortcut to something custom multiple times over the past few weeks (maybe a couple of months?). I'm running Firefox Developer on both MacOS Sonoma (120.0b6) and Arch Linux (117.0b8), having the same problem on both.

**Comment by ewjoachim** [comment]
Looks like this is being discussed over there: https://github.com/bitwarden/clients/issues/5144


This ticket being closed, it may make more sense to move discussion to that one.
