### ISSUE TITLE
Does Bitwarden Send My Personal Data to Bitwarden Servers??

### ISSUE THREAD

**Issue by sileeb** [bitwarden/browser#2485]
### Steps To Reproduce

Does my personal info get sent to bitwarden's servers? Doesnt that put data at risk?

### Expected Result

n/a

### Actual Result

n/a

### Operating System

Windows

### Operating System Version

10 home

### Web Browser

Firefox

### Build Version

98.02

**Comment by kspearrin** [comment]
Our help center can answer these questions for you. https://bitwarden.com/help/vault-data/
