### ISSUE TITLE
Include option to require 2FA authentication to unlock

### ISSUE THREAD

**Issue by circuitousNerd** [bitwarden/browser#249]
At the moment 2FA is only required when initially adding a vault to the Chrome plugin. Can we add the option to require 2FA each time the vault is unlocked?

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/91

**Comment by circuitousNerd** [comment]
Thanks. I searched through two pages of issues and didn't see anything that matched my request. Should've looked back further.
