### ISSUE TITLE
Is their an issue open to track Credit Cards and Secure Notes features?

### ISSUE THREAD

**Issue by lhorace** [bitwarden/browser#250]
Hi,

This could _be_ a great alternative to [LastPass](http://www.lastpass.com) and many have suggested it as alternative on Reddit as LP is missing early support for Firefox 57+. Unfortunately, there are two dying features, that I must have! Secure Notes and storing Credit Card information that I can't seem to find any open issue on? Besides, coming soon on the main site. For now I am trying SafeInTheCloud, which is feature rich, but unfortunately it's cloud sync needs much to be desired.

**Comment by kspearrin** [comment]
Yes, https://github.com/bitwarden/browser/issues/14

We're working on some preliminary things now that will allow us to add this feature in the near future. Estimated 1-2 months

**Comment by lhorace** [comment]
I see secure notes was implemented, how about Credit Cards?

**Comment by kspearrin** [comment]
https://blog.bitwarden.com/store-secure-notes-credit-cards-identities-in-your-bitwarden-vault-aa813761f5f0
