### ISSUE TITLE
extension no longer works with firefox  just blank lines evrywhere

### ISSUE THREAD

**Issue by forrayz** [bitwarden/browser#2500]
### Steps To Reproduce

1. clicking on the blue shield
2. or go to a site where should be a saved credential

### Expected Result

1. should list saved logins
2. should detect if a login is saved 

### Actual Result

 gives a list of empty elements see screenshot above.
If i go to a previously visited web page login. It will not offer any login.
In case I enter the credential manually it offers to save it. And than the saved credential looks fine on the top of the list.

### Screenshots or Videos

![kép](https://user-images.githubusercontent.com/33726645/163195587-8e7cb8ad-b424-402b-8f33-996fbb256217.png)

### Additional Context

The installed version works fine I can access my vault with it. Also works with Google Chrome 100.0.4896.88
Tried to remove and add back the extension but it did not helped at all.

### Operating System

Linux

### Operating System Version

Ubuntu 21.04

### Web Browser

Firefox

### Browser Version

firefox/hirsute-updates,hirsute-security,now 96.0+build2-0ubuntu0.21.04.1 amd64

### Build Version

1.57.0

**Comment by tangowithfoxtrot** [comment]
Hello,

Sometimes, issues like that can be caused by an issue with your network, or VPNs, ad blockers, antivirus, proxies, etc. If you are using any of these, could you try temporarily disabling them, and logging out and back in to the extension to see if your login items appear?

**Comment by forrayz** [comment]
After a reboot Bitwarden recovered. I will close the case as I cannot reproduce the error any more.
