### ISSUE TITLE
Chrome browser extension autolock with timeout set to never

### ISSUE THREAD

**Issue by coverton341** [bitwarden/browser#2502]
### Steps To Reproduce

1. Open Chrome browser and unlock the extension.
2. Go to settings
3. Set Vault Timeout to "never"
4. Close Browser
5. Reopen Browser

### Expected Result

Bitwarden Extension should still be unlocked

### Actual Result

Bitwarden extension is locked

### Additional Context

This is happening on a Surface Pro X running Windows 11 Pro with 
Processor	Microsoft SQ1 @ 3.0 GHz, 2995 Mhz, 8 Core(s), 8 Logical Processor(s)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

100.0.4896.88 (Official Build) (32-bit)

### Build Version

1.57.0

**Comment by yashwalter12** [comment]
Hello @coverton341  Looked into the issue on Windows Chrome version 100.0.4896.127 with 1.58.0 build version. Followed the same steps where I set the vault timeout 'never' and closed the browser and reopened it, the vault stayed unlocked. Could you please check it again to see if you are still having this issue.

**Comment by coverton341** [comment]
Hi @yashwalter12 I have just tried on 1.58.0 on Chrome version 101.0.4951.41 and it is now working as intended.

**Comment by djsmith85** [comment]
@coverton341 Thank you for reporting back. Closing this now.
