### ISSUE TITLE
100% CPU in Firefox and Chrome

### ISSUE THREAD

**Issue by panpiotrs** [bitwarden/browser#251]
I'm using latest Chrome and Firefox (Beta 57) on macOS 10.13.
After import from Lastpass Bitwarden starts to eat 100% CPU, I guess it's because I have 2073 logins there, in tests before import it was fine. Can you somehow test it and confirm or should I add some additional informations? Or maybe there is limit and I simply will not be able to use Bitwarden with that many logins in vault?

**Comment by kspearrin** [comment]
@panpiotrs There is a current known bug on Firefox for users with very large vaults. We have a fix in the next release which will be available soon.

**Comment by kspearrin** [comment]
See https://github.com/bitwarden/browser/issues/239 for more info

**Comment by panpiotrs** [comment]
I see that in Chrome it eats 100% CPU but only for about 30 seconds, in Firefox it freezes the browser completely each time after addon is activated - so it's somewhat different than in #239, as I don't need to interact with it, but I understand that both issues are done by the same bug. Wonderful, I'm waiting eagerly for the fix, thanks for this amazing product :)

**Comment by kspearrin** [comment]
Yes, this comes from the massive about of data being decrypted (which is then cached). We moved to a more performant decrypt implementation in the fix, which also helps chrome as well. You should still expect some amount of heavy CPU usage during this decryption stage, though it shouldn't last as long or crash your browser going forward.

**Comment by kspearrin** [comment]
If you want to help test this, feel free to stop by our dev chat and I can give you a custom build with the fix and we can see the difference. https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
resolved for next release.
