### ISSUE TITLE
Cannot see my entries

### ISSUE THREAD

**Issue by bernhardvienna** [bitwarden/browser#2510]
### Steps To Reproduce

Opening Bitwarden
Enter password

### Expected Result

See my list of entries

### Actual Result

Can see that there are entries, but everything is blank

### Screenshots or Videos

<img width="947" alt="Bildschirmfoto 2022-04-17 um 12 51 14" src="https://user-images.githubusercontent.com/103882684/163711359-45d6a5b8-a72f-491d-bbc2-770977bdae75.png">

### Additional Context

Tried to restart several times, nothing changed. Password is accepted!
the web version is fine, I can see everything. Just the BitWarden App doesn't show the data. Also on my iPhone I can see all entries and data.

### Operating System

macOS

### Operating System Version

10.14.6

### Web Browser

Brave

### Browser Version

1.38.93

### Build Version

100.0.4896.88

**Comment by Hinton** [comment]
Hi @bernhardvienna. 

This looks like an isuse for desktop. Please re-open a ticket for desktop at https://github.com/bitwarden/desktop/ with the proper version numbers.

I believe logging out and back in again might resolve the issue.

**Comment by jorritsmit** [comment]
Bitwarden desktop is archived and does not accept new issues, so i guess this is the correct place to report it? I am having the same issue but on windows 10

Version 1.32.1
Shell 16.0.7
Renderer 96.0.4664.110
Node 16.9.1
Architecture ia32

**Comment by Hinton** [comment]
@jorritsmit yes. Please create a new issue and follow the template, or reach out to our Customer Success team whom can assist in troubleshooting this at https://bitwarden.com/contact/

**Comment by bernhardvienna** [comment]
I already solved it. Log out - log in. :)

**Comment by jorritsmit** [comment]
This doesn't solve it for me but i will submit a new issue and reach out to the customer service team
