### ISSUE TITLE
Web extension generates wrong TOTP code

### ISSUE THREAD

**Issue by unickq** [bitwarden/browser#2512]
### Steps To Reproduce

TOTP code is not correct on Web.

Bitwarden iOS, Desktop and Google Authenticator generate equal codes/

### Expected Result

 correct code

### Actual Result

wrong totp

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6696821/164302774-62e5fd9e-2d40-4f19-af2a-2db73778022c.png)

### Operating System

Windows

### Operating System Version

Any

### Web Browser

Microsoft Edge

### Browser Version

100

### Build Version

Version: 1.57.0

**Comment by Hinton** [comment]
Hi @unickq,

TOTP are a "Time-based one-time password", the client uses the underlying browser or OS clocks to generate the TOTP, please verify that the devices are correct and in the correct timezones. In most environments you can fetch the current time automatically from the settings.

**Comment by unickq** [comment]
Hi @Hinton 

The screenshot above is made on the same device - Bitwarden Desktop and MS Edge extension. But I'll check it one more time to be sure tomorrow 👌

**Comment by unickq** [comment]
Interesting - can't reproduce it today on the same device.
Anyway thanks for help
