### ISSUE TITLE
Safari extension fails to login

### ISSUE THREAD

**Issue by balboah** [bitwarden/browser#2519]
### Steps To Reproduce

1. Open safari
2. Click on bitwarden in toolbar
3. Realize its logged out, click login
4. Open new tab to authenticate with WebAuthn
5. "WebAuthn verified successfully! You may close this tab."
6. Yet another tab has opened with WebAuthn and "unexpected error" in the footer

### Expected Result

Has worked fine in the past.

### Actual Result

Bitwarden is still logged out, the 2nd tab auth button doesn't trigger anything

### Additional Context

I've cleared cookies, re-installed bitwarden and restarted the mac without improvements.
The standalone bitwarden works fine. 
I noticed the latest App Store release notes mentioning Safari extension update which might have triggered this.

### Operating System

macOS

### Operating System Version

12.3.1

### Web Browser

Safari

### Browser Version

15.4

### Build Version

17613.1.17.1.13

**Comment by yashwalter12** [comment]
Hello @balboah I did check the issue on safari extension and It is working for me on Mac os 12.3 version on Safari version 15.4. Can you check again to see if you still have this issue and what kind of macOs you are having this issue on (Intel or Mac M1)
Thanks

**Comment by balboah** [comment]
Hello,

This is M1. After removing the webauthn key and adding it back once again, Safari finally let me login 👍

It should be noted Firefox and the native app worked fine with the same key even before removing & re-adding. Not sure why Safari got hung up on it.

**Comment by yashwalter12** [comment]
@balboah  Great. Closing the ticket as it is working now.
Please reach out if you have more issues.

**Comment by rraheja** [comment]
Still facing this issue. Mac OS 12.3.1, Intel chip. Native app and other browsers work, and other apps e.g. Github 2FA with security key works on safari, but only Bitwarden app does not work. Exhibits same behavior explained above. I have multiple keys (for backup) so while the workaround may work, it would be safer to see this issue resolved for good.
