### ISSUE TITLE
Modifying DOM with data-attributes

### ISSUE THREAD

**Issue by gavrilfb** [bitwarden/browser#252]
Hello, I just recently use BitWarden. So far so good. I manage to transfer my data from Lastpass almost flawlessly.

But I noticed that now on some page element, it add _data-com.agilebits.onepassword.user-edited_ after I edit them.
I check by enabling and disabling various add-ons, and I found out it is BitWarden that does this behaviour.
Could you explain what do you use this attribute for? Because it is kind of instrusive.

Thank you.
Best Regards.

**Comment by kspearrin** [comment]
These are used by the autofill content scripts that keep track of the state of the page. They shouldn't be intrusive to a webpage in any way. If they are, please post an example.

**Comment by eitland** [comment]
I know this is closed but I just came across the same today and wonder why i had DOM properties related to a password manager I haven't used.

A better description of what is happening here would be much appreciated and if possible change it as right now it looks like someone copied code from another extension and forgot to change this string.

**Comment by kspearrin** [comment]
Our autofill code comes from 1Password. See here https://github.com/bitwarden/browser/blob/master/src/content/autofill.js

We intentionally are not changing it as to keep compatibility with what sites may be doing to cater to this script.

**Comment by eitland** [comment]
That explains, thanks!
