### ISSUE TITLE
HTML code when converting from Lastpass

### ISSUE THREAD

**Issue by jfdhuiz** [bitwarden/browser#253]
Hello,

(I migrated from Lastpass, thank you for this application.)

When using the guide as provided certain symbols are converted to HTML code.

(Following is in code tags so its not parsed.)

```
Take for example the password: buAg>OajSiar7
It gets converted to: buAg&gt;OajSiar7

This is because the symbol > becomes &gt;

The guide only mentions the HTML code &amp;
```

For a list, see: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Character_entity_references_in_HTML

IMO you should mention that &amp; isn't the only one which may have to be changed and provide the user perhaps with the full list. Using symbols like these greatly increases entropy.

**Comment by kspearrin** [comment]
Please open this issue in the help repo. It is not applicable to the browser extension.
