### ISSUE TITLE
Search doesn't work in extension and doesn't detect logins.

### ISSUE THREAD

**Issue by ngnh** [bitwarden/browser#255]
Installed and created an account like 5 min ago. Clicking the extension/my vault and tying anything in search gives 0 results. But it does on the web vault. Using firefox 57.
Also it does not detect any of the sites logins. Says "no matching logins" even tho i do have a login for github.

**Comment by kspearrin** [comment]
Sounds like you need to sync. Go to Settings -> Sync. Automatic syncing only happens every few hours.

**Comment by ngnh** [comment]
That was indeed it. What wasn't clear was that when you click sync, you have to click it again. Even if you havn't synced it says "Last sync" indicating everything is fine. I didn't know the Sync in the middle was a clickable button.
