### ISSUE TITLE
Login fails on Android Firefox Beta

### ISSUE THREAD

**Issue by sandermarechal** [bitwarden/browser#257]
I cannot login using the browser extension on Firefox Beta on Android. It always gives me "An unexpected error has occured". My device runs Android 6.0.1 and [Firefox Beta 57.0b3](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta&hl=nl). I only have one other extension installed: uBlock Origin. Disabling uBlock Origin has no effect. Also, on the desktop version of Firefox the Bitwarden extension works fine alongside uBlock Origin.

**Comment by kspearrin** [comment]
This is a known bug. It should be patched with our release later today.
