### ISSUE TITLE
Suggestion: Add keyboard shortcut to search the vault

### ISSUE THREAD

**Issue by bvli** [bitwarden/browser#259]
It would be nice to have a keyboard shortcut to open the extension in search vault mode with the search input field focused. It could be `alt-w` for example,  but any key combination would be fine..

**Comment by kspearrin** [comment]
This was resolved in https://github.com/bitwarden/browser/issues/254 . Will go out soon.

**Comment by kspearrin** [comment]
Ctrl + Shift + Y will open with your cursor reach to search.
