### ISSUE TITLE
Unable to install extension in FF developer edition - "appears corrupt"

### ISSUE THREAD

**Issue by stairmast0r** [bitwarden/browser#26]
I'm using the latest version of Firefox developer edition as of writing (51.0a2), 32-bit, with xpinstall.signatures.required set to true. I'm unable to install the addon either directly from addons.mozilla.org or from my local drive after saving it, with the message that it "appears to be corrupt."

![screenshot](https://cloud.githubusercontent.com/assets/5339003/19372952/2dd18320-918e-11e6-94d5-6d7208d244bb.PNG)

**Comment by kspearrin** [comment]
Hi there,
This is becasue Mozilla has not approved the extension to be downloaded from the addons store yet. It is in review. Please refer to this task: https://github.com/bitwarden/browser/issues/8

I am anxiously awaiting for this to become available myself as well since I use Firefox primarily.

**Comment by stairmast0r** [comment]
Thanks for the quick reply! I'm sorry for the trouble, I didn't notice the closed ticket regarding the issue.

**Comment by kspearrin** [comment]
No worries! The good news is it seems we should be approved here pretty soon. Subscribe to the other ticket for updates.
