### ISSUE TITLE
Enhancement: Allow Folders to Expand/Collapse if you have less than 100 passwords

### ISSUE THREAD

**Issue by sneukam** [bitwarden/browser#262]
Folders cannot expand or collapse if a user has less than 100 passwords in the tool - I found this out when reaching out to customer support. Is there a way to make this number configurable, so end users can dictate at what point folders should become collapse-able, or is there a way to enable this by default? It seems like a good option that most users would want - and that I do in particular. I personally manage about 80 passwords, and that is a rather large amount to not have folders that I can expand or collapse to sift through my account credentials.

**Comment by kspearrin** [comment]
Now the default in v1.22.0 +
