### ISSUE TITLE
Add URI to search parameters

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#263]
I've imported my LastPass data and wanted to try something I found is already getting worked on in #77. Specifically, companies who use Taleo for job postings. Usually works like `company1.taleo.net`, `company2.taleo.net`, etc. But I've found another problem entirely. If I search for `taleo` or `taleo.net`, the only results I got were those that had `taleo` in the name of the login.

Curiously, this works as expected on logins I create with bitwarden itself. The only other example I can think of to test this phenomenon is my Microsoft account being named `Microsoft` but the login URI is `login.live.com`. A search for `live` doesn't bring that one up, but will bring up a bitwarden-created entry with a URI of `live.com` and name without `live`.

**Comment by kspearrin** [comment]
sounds like we're just searching names and not the URIs

**Comment by maxrom** [comment]
Thanks for responding so quickly. I think I put this in the wrong place. This happens in vault.bitwarden.com so it sounds like a web issue instead of browser.

**Comment by kspearrin** [comment]
Yes, please open the issue there.
