### ISSUE TITLE
Auto focusing email field in Firefox 58 causes page jump on load

### ISSUE THREAD

**Issue by scheinercc** [bitwarden/browser#264]
Just started seeing this issue yesterday while following links from a Mozilla newsletter. Each time one of the mozilla.org pages had been loaded it immediately jumped down towards the footer. It turned out that while Bitwarden was enabled the first email field got filled and focused, which for these sites was usually the newsletter field further down. In my screenshots you can see it and the filled in field in green.

I also filed a [bug in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1404559) as this seems to be a regression in FF58, though not sure if it will mean that code in Bitwarden has to be changed as well!?

![ff58-bitwarden-email-sample1](https://user-images.githubusercontent.com/817856/31041512-2892e348-a5da-11e7-9cb3-2cc0338a062f.png)
![ff58-bitwarden-email-sample2](https://user-images.githubusercontent.com/817856/31041513-2899a322-a5da-11e7-9b4b-657ed9afd945.png)
![ff58-bitwarden-email-sample3](https://user-images.githubusercontent.com/817856/31041514-289f57e0-a5da-11e7-992f-35fe7d28fb56.png)

**Comment by kspearrin** [comment]
This is a bug introduced in the latest version of bitwarden. We have a fix in place that will go out with our next version.

**Comment by scheinercc** [comment]
Ah, ok. Thought it was my profile, as I couldn't find the issue with mozregression, and not happening with a new browser profile.
Thanks!

**Comment by scheinercc** [comment]
Verified on the pages where it jumped before. Thanks for the fix!
