### ISSUE TITLE
Second over places the title under the plugin

### ISSUE THREAD

**Issue by Sytten** [bitwarden/browser#266]
The first element you over on is fine, but after that the text is under the plugin.
I'm using Firefox 57. 
(Mouse is on the username icon on the picture)
<img width="264" alt="screen shot 2017-09-30 at 11 21 20 pm" src="https://user-images.githubusercontent.com/2366731/31051436-356c88a6-a636-11e7-86ee-db1beff39cb8.png">

**Comment by kspearrin** [comment]
This is definitely a Firefox bug, nothing if bitwarden is doing. We should report to bugzilla.
