### ISSUE TITLE
Add login does not work for tokenhub.com

### ISSUE THREAD

**Issue by smartins** [bitwarden/browser#270]
Signed up for an account at https://tokenhub.com/ but never got the notification to add the login details to bitwarden.

Also tried to logoff and login again but bitwarden does not pickup that I'm logging in and does not offer to save the new login.

**Comment by kspearrin** [comment]
Thanks. This is a known issue at the moment with the add login notification.

**Comment by Moxville** [comment]
I noticed this issue for a site as well
https://outlook.live.com/owa/

**Comment by kspearrin** [comment]
This is fixed for next release.
