### ISSUE TITLE
Feature Request: Icons for "Launch Website" and "Edit Website" in "My Vault"

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#276]
Hi Kyle,

I'm requesting for new "Icons" ("Launch Website" and "Edit Website") to be added for Logins in "My Vault"
Since every time I have to click "Edit Site" and then click "Launch Website" to launch the site
Having these icons directly in login is convenient and direct as well. User can choose whether to launch the site, edit the site, copy username, copy password, etc.
![untitled](https://user-images.githubusercontent.com/31923265/31141351-cc8fbb44-a894-11e7-8432-541430e5eb42.png)

Please add these new icons for easy access
Thank You

**Comment by kspearrin** [comment]
Unfortunately there is not enough room to keep adding more icons in that manner. We need to try and figure out a better way of displaying those options.

**Comment by kspearrin** [comment]
I have added the launch icon, but we cannot add edit since there is no more room/

**Comment by Moxville** [comment]
Thank You. 
Frequently used icons / options might differ from user to user.
The most likely used options / icons can be added in login area and other less frequent icons in "Edit" section.
IMO Launch, Copy User / Pass icons could be the most used ones on a regular basis

**Comment by kspearrin** [comment]
Closing since this was added for next release.
