### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by petervnv** [bitwarden/browser#279]
Hi,

Trying to compile the browser extension on Ubuntu 16.04 LTS.
Everything seems OK until I run gulp build, which outputs a few errors:

src/popup/app/tools/toolsExportController.js: line 87, col 30, 'j' is already defined.

1 error
src/services/autofillService.js: line 246, col 73, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.
src/services/autofillService.js: line 252, col 25, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

2 errors
src/services/cryptoService.js: line 223, col 26, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

1 error
src/services/folderService.js: line 90, col 61, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

1 error
src/services/lockService.js: line 146, col 6, Unnecessary semicolon.

1 error
src/services/loginService.js: line 175, col 60, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

1 error
src/scripts/u2f.js: line 14, col 20, You might be leaking a variable (thisU2f) here.

1 error
src/background.js: line 643, col 29, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.
src/background.js: line 714, col 24, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

2 errors
[18:31:24] Finished 'lint' after 1.97 s
[18:31:24] Finished 'build' after 2.11 s

**Comment by kspearrin** [comment]
This is not a compilation failure. These are just lint warnings.

**Comment by petervnv** [comment]
Sorry. Of course you're right.
But where does it output the XPI or CRX after compilation?

**Comment by kspearrin** [comment]
This is a web extension. It's only JS/HTML.

**Comment by petervnv** [comment]
Gotcha. Thanks!
