### ISSUE TITLE
Autofill-feature for subdomain pages does not sort the available logins like the `Tab`-view does

### ISSUE THREAD

**Issue by bdalenoord** [bitwarden/browser#281]
I've got a load of services with different logins running under a subdomain, for example:
- bitbucket.test.com
- confluence.test.com
- exchange.test.com
- jira.test.com

The 'Current Tab'-view in the plugin sorts the available logins as expected, AFAIK this happens [here](https://github.com/bitwarden/browser/blob/master/src/popup/app/current/currentController.js#L97). The Autofill-feature does not apply the same sorting and due to this the wrong accounts are autofilled for various services which requires manual intervention to log in.

I'd like the autofill service to apply the same URI-based sorting for selecting an account as the 'Current Tab'-view uses.

**Comment by meffect** [comment]
Same issue here. Like you, it is sorting current tab URL logins at top of list on the `Tab` screen in the browser extension (which is a godsend all things considering). 

I think I noticed a pattern for the autofill, it seems to be using the **last used login** that I used, to fill in the next login for the different **SubDomain**.`SecondLevelDomain`.`TopLevelDomain`

**Comment by kspearrin** [comment]
Should be consistent now in 1.26.
