### ISSUE TITLE
Switching keyboard language breaks login

### ISSUE THREAD

**Issue by danielquinn** [bitwarden/browser#283]
If the user's email address is written in ASCII but parts of their password contain non-ASCII characters, this necessitates switching keyboard layout.  In GNOME, this shows a screen overlay signifying you're switching from `keyboard layout 1` to `layout 2` and at the same time, this collapses the little drop-down menu from which you're logging in.  When you re-open it, now ready to enter the rest of your password, you're back at the login screen :-(

I'm not sure how easy this is to fix, but a possible solution might be to just not reset the state of the login form if the drop-down is closed.  Either that, or find a way to make it persist through the switching of a keyboard layout.

It should also be noted that you can work around this problem by opting to login via the sidebar rather than the drop-down.

**Comment by kspearrin** [comment]
Unfortunately we have no control over when that popup closes since this is all handled by the browser. Sounds like this may be a good bug report for Firefox though since I can see how that would be rather annoying. Would you be able to report this to bugzilla and see what they say?

**Comment by danielquinn** [comment]
Sure, I'll do that.  Closing now.

**Comment by danielquinn** [comment]
[Reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1406055)
