### ISSUE TITLE
Bitwarden does not disappear after clicking "Launch Website" icon

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#284]
Hi Kyle
After clicking "Launch Website" (Login area / inside "Edit"), the website is launched but Bitwarden does not disappear automatically. I had to click somewhere in the screen to make bitwarden disappear.
This is a slight inconvenience.
Request to alter the behavior, so as to bitwarden "automatically" disappears after clicking the "Launch Website" icon

**Comment by kspearrin** [comment]
Fixed next release.
