### ISSUE TITLE
Account Log out on Browser Exit / System Restart

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#286]
Hi Kyle,
I'm requesting for an feature, when user accidentally closes the browser or if system restarts bitwarden will auto log-out of the account
I'm aware of the availability of "Lockout" option. I do not know if bitwarden will force 2FA when user tries to unlock the locked account

In my opinion this added security feature could prevent misuse if an unauthorized person tries to log-in (in a shared system) to the account with leaked master password
This feature was requested earlier.

Do you see any added security benefit in this feature ?
Also I'm not sure if its a good idea to have both "auto lock" and "auto log out" option enabled

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/browser/issues/91
