### ISSUE TITLE
[Feature] Allow multiple URIs per login

### ISSUE THREAD

**Issue by saithis** [bitwarden/browser#289]
Some pages with different domains share a single account in the background like amazon.com/amazon.de/etc. or signin.ea.com/battlelog.battlefield.com. It would be nice, if you could combine them to a single entry in the vault. Then you would only need to update a single entry when chainging the password.

**Comment by kspearrin** [comment]
Please see https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7

**Comment by saithis** [comment]
oh, thanks!
