### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#29]
Allow the user to specify a setting that will automatically log them out of the extension after X minutes. Before this can be implemented, we'll have to implement a way for two-factor cookies to be remembered so that they do not have to go through that process each time.

Another option is to figure out a way for this to just "lock" the session and not really log them out. This may be difficult to do securely on a web extension (as opposed to the mobile apps which just present a modal overlay).

**Comment by ArtemNikolaev** [comment]
Your have `loginService` inside the app with `_service.logOut`. What if we just add "logOut after" field in settings and use setTimeout to logOut him?

**Comment by kspearrin** [comment]
Yes, that would be the easy way, however, would cause issues with two factor users as mentioned above. Need to solve that first.

**Comment by kspearrin** [comment]
This was added in v1.2.0

https://github.com/bitwarden/browser/releases/tag/v1.2.0
