### ISSUE TITLE
Please let users configure how long to display the Bitwarden popup

### ISSUE THREAD

**Issue by catgun** [bitwarden/browser#294]
Please let users configure how long to display the Bitwarden popup. Right now, if I switch browser focus, it disappears immediately. This is very frustrating, as I often use Bitwarden to enter passwords in other browsers, and other browser windows.

**Comment by kspearrin** [comment]
This is not possible for us to do. The browser controls how this popup is closed. This is why we added the ability to pop it out to a full screen tab or use in the sidebar (firefox and opera).

**Comment by catgun** [comment]
Please configure Bitwarden popup to be opened in a persistent window, similar to what Google Hangouts does. Right now, if I switch browser focus, the popup disappears immediately. This is very frustrating, as I often use Bitwarden to enter passwords in other browsers, and other browser windows.

I was told that I should open the popup to a browser tab. (See issue #294) This is not as good because:

a) it's not obvious from the UI that this is what you're supposed to do if you want a persistent window
b) the pre-fill suggestions disappear
c) it requires a second click
d) it requires switching from one tab to another, rather than being able to see both at the same time. (You can open the tab in a new window, but then you get a huge window that you have to shrink down.)

Thanks!

**Comment by kspearrin** [comment]
Google Hangouts can to do this because Google owns Chrome and has whitelisted their own extension to be able to "popout" a `panel` window like you see. This won't work for other extensions since you would then be required to enable an experimental `--enable-panels` flag on the browser.

See https://stackoverflow.com/questions/11614493/how-does-the-google-hangouts-extension-create-the-panel-window

**Comment by catgun** [comment]
Thanks for the response.  FWIW, I would rather make a one-time change to a config, than have to deal with the constant annoyance of the current behavior.   Extensions can also change Chrome settings.  

Also, Google presumably doesn't have privileged access to Firefox, and the "Messenger for Google™ Hangouts" add-on popout window is persistent.  So it seems that you could make the Bitwarden popup persistent at least on Firefox without any config changes.

**Comment by kspearrin** [comment]
I have added support for `window.create` `type: popup` in the next release when clicking the popout arrow in the vault. Firefox panels these as a panel like you see in Google Hangouts.

**Comment by catgun** [comment]
Thank you!
