### ISSUE TITLE
Please configure Bitwarden popup to be opened in a persistent window, similar to what Google Hangouts does. 

### ISSUE THREAD

**Issue by catgun** [bitwarden/browser#296]
Please configure Bitwarden popup to be opened in a persistent window, similar to what Google Hangouts does. Right now, if I switch browser focus, the popup disappears immediately. This is very frustrating, as I often use Bitwarden to enter passwords in other browsers, and other browser windows. 

I was told that I should open the popup to a browser tab. (See issue  #294)  This is not as good because:

a) it's not obvious from the UI that this is what you're supposed to do if you want a persistent window
b) the pre-fill suggestions disappear
c) it requires a second click 
d) it requires switching from one tab to another, rather than being able to see both at the same time.   (You can open the tab in a new window, but then you get a huge window that you have to shrink down.) 

Thanks!

--

**Comment by kspearrin** [comment]
Please do not open a new issue. You can comment on the other one that was closed if you want to add additional feedback. Duplicate https://github.com/bitwarden/browser/issues/294

**Comment by catgun** [comment]
Sorry, it's hard to know what your conventions are.  You closed that issue, and this is a different proposal (you say it's impossible to make your current popup persistent, so I'm suggesting that you do whatever Google Hangouts does to make their popup persistent, assuming they use a different mechanism.
