### ISSUE TITLE
Focus on search field when opening extension

### ISSUE THREAD

**Issue by msp1982dk** [bitwarden/browser#299]
It would be cool if the search field was focused when the extension is opened.
Then we could search without having to click the field.

I'm using Firefox Developer v57.0b6.

**Comment by kspearrin** [comment]
This is a Firefox bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

**Comment by iangregory** [comment]
Can confirm this is fixed in Firefox 60.0b3

**Comment by taylankasap** [comment]
Autofocus stopped working a few days ago. Chrome 105.0.5195.127, Bitwarden 2022.9.1
