### ISSUE TITLE
UI cut off in Fx 57 when icon is under "More tools.."

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/browser#303]
When not placing the bitwarden icon directly on the icon bar in Fx but instead in the hidden overflow area ("More tools..." says the tooltip), the bitward UI is cut off at the bottom, see screenshots below. I'm using Fx 57.0b7 (64-bit) on macOS 10.13 When the icon is on the icon bar, everything is okay. If you think this must be a bug in Fx itself, please let me know and I will file a Bugzilla report and link it here.

![screen shot 2017-10-12 at 12 35 13](https://user-images.githubusercontent.com/26418089/31492462-6f6fdb0c-af4b-11e7-89b5-f1c47b68e260.png)

![screen shot 2017-10-12 at 12 36 22](https://user-images.githubusercontent.com/26418089/31492468-75f54fca-af4b-11e7-90ad-543b9a059e05.png)

**Comment by kspearrin** [comment]
This is a Firefox bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1402845
