### ISSUE TITLE
Please add Bitwarden button to password fields

### ISSUE THREAD

**Issue by morris-t** [bitwarden/browser#304]
Lastpass has a feature where they place the Lastpass icon in the login fields:
http://thetechnicalgeekery.com/wp-content/uploads/2012/09/1-firefoxextension.png

When you click on the icon, it shows the related logins for that site, allowing you to click whichever login you want and then having that login auto-filled.

It would be great to have the same feature in Bitwarden. I realize you can right click - Bitwarden - Autofill - account, however I find the above approach way more streamlined.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/3
