### ISSUE TITLE
Can't login to FireFox extention offline

### ISSUE THREAD

**Issue by zaits07** [bitwarden/browser#313]
Hello. Big thanks for this greate opensource software.
IMHO, Birwarden extention store passwords locally and can work offline (read-only at least).
But i can't login to use it offline.
Any advices will be appreciated.
Thanx.

**Comment by kspearrin** [comment]
Bitwarden already stores the vault locally for offline use, however, you must be logged in before to going offline and it will continue to work just fine.

**Comment by zaits07** [comment]
It's a pity.
Thank you for fast reply. I hope, in future it can be changed.
