### ISSUE TITLE
Autofills incorrect fields on TD Easyweb site

### ISSUE THREAD

**Issue by julianlam** [bitwarden/browser#317]
https://easyweb.td.com/waw/idp/login.htm

![image](https://user-images.githubusercontent.com/923011/31738089-89fded8a-b417-11e7-8b09-f226e068c5dc.png)

For ease of debugging, this is the relevant html:

``` html
<div class="td-layout-row">	 
	<div class="td-layout-column td-layout-grid3 td-layout-column-first">
		<input tabindex="2" name="login:AccessCard" class="accessCardField" id="login:AccessCard" onchange="clearDescriptionBox();" value="" maxlength="32" autocomplete="off" type="text">
		
	</div>
	<div class="td-layout-column td-layout-grid2 td-layout-column-last">
			<input tabindex="8" id="login:description" name="login:description" class="descriptionFieldWidth  " value="" maxlength="15" autocomplete="off" data-com.agilebits.onepassword.user-edited="yes" type="text">
	</div>
</div>
<div class="td-layout-row">			
	<div class="td-layout-column td-layout-grid2 td-layout-column-first">			
		<label id="password" class="td-copy-align-right" style="display: block" for="login:Webpassword"><span class="boldFont">Password</span></label>
	</div>
	<div class="td-layout-column td-layout-grid3">
		<input tabindex="3" name="login:Webpassword" class="accessCardField  " id="login:Webpassword" size="24" value="" maxlength="32" autocomplete="off" data-com.agilebits.onepassword.user-edited="yes" type="password">
	</div>
	<div class="td-layout-column td-layout-grid2 td-layout-column-last">
		<input tabindex="4" id="login" class="td-button td-button-primary" value="Login" onclick="setDevicePrintFormFields('login'); return clickOne();" title="Login to our secure financial services site" type="submit">
	</div>
</div>
```

Bitwarden does not fill the proper field (the input with class `login:AccessCard`), but instead, fills `login:description`

**Comment by julianlam** [comment]
If you use some sort of heuristic to determine which field is the username field, proximity to the password field via tab index could work... but what do I know :smile:

**Comment by kspearrin** [comment]
The current logic is that it looks for the text input immediately before the password, which is why it is failing here.

**Comment by julianlam** [comment]
I wonder how other password managers do it... I have a feeling that maintaining a list of exceptions is not going to scale well at all.

**Comment by kspearrin** [comment]
An exception list is definitely not the way to go. We could likely build more intelligent logic that gives more weight to certain inputs by checking the tab index as you suggested and also by looking for hits in the labels/placeholder values associated with the input.

**Comment by kriswilk** [comment]
Just dealt with this site myself.

@julianlam, in case you didn't know, there is a solution/workaround...use the Custom Fields feature to add a field called "login:AccessCard" and put the username or card number there. Then leave the "username" field in the vault entry BLANK. Works fine.

**Comment by julianlam** [comment]
Excellent workaround, that worked well for me. 😄

**Comment by bfranske** [comment]
Somewhat related to #501

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
