### ISSUE TITLE
Long password not fitting into password field

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#318]
Hi Kyle,
I have a lengthy password for a site
When I got to View tab (edit) for that site, I can see the password but its going out of the password field. screenshot enclosed. Can this be fixed ?
![untitled](https://user-images.githubusercontent.com/31923265/31818912-ca537cbe-b5b7-11e7-82ad-aa487af817cb.png)

**Comment by kspearrin** [comment]
Fixed in next version.
