### ISSUE TITLE
Scaling for panel wrong when using Firefox

### ISSUE THREAD

**Issue by whalley** [bitwarden/browser#321]
This problem relates to FireFox, scaling works correctly on Chrome.

I have two displays, one the native laptop display which is HighDPI with font scaling set to 175% and an external nonHighDPI monitor with scaling set to 100%. In Firefox" layout.css.dpi" is set to the default -1 which allows Firefox to scale correctly as browser windoes are moved between monitors.

When BitWarden extension is openend on the non-HighDPI monitor the fonts in the panel are scaled too high. On the HighDPI monitor scaling is correct,

![2017-10-22 11_26_09-new issue bitwarden_browser](https://user-images.githubusercontent.com/487345/31861003-22fb70be-b71c-11e7-82e2-f0c165664ea4.png)

**Comment by kspearrin** [comment]
I am pretty certain that this is a Firefox bug. I don't really see anything we can do about it. Could you try reporting it on Bugzilla and see what they say?

**Comment by whalley** [comment]
Yes, tried another extensions with the same issue...

Have raised - https://bugzilla.mozilla.org/show_bug.cgi?id=1410756

**Comment by kspearrin** [comment]
Thanks. I will close this since there is nothing we can do.
