### ISSUE TITLE
Some passwords incorrectly imported from lastpass csv

### ISSUE THREAD

**Issue by noidexe** [bitwarden/browser#325]
I've imported my passwords from LastPass. A website was complaining about incorrect password and upon inspection it turned out the character `&` in the password had been converted to `&amp;` in Bitwarden.

**Comment by GeoDosch** [comment]
On the [import-from-lastpass](https://help.bitwarden.com/article/import-from-lastpass/) help page, there is a prominent warning that describes exactly that scenario, which is caused the LastPass  exporter.

**Comment by noidexe** [comment]
Oh, sorry, I think I missed that.
