### ISSUE TITLE
Set pasteboard type for clipboard contents

### ISSUE THREAD

**Issue by pwxn** [bitwarden/browser#326]
Passwords copied to the clipboard should set the pasteboard type to a specific value, instead of a generic "text". For example, 1Password set the type as "com.agilebits.onepassword"; Lastpass sets the type as "PasswordPboardType" or "org.nspasteboard.TransientType".

This is important for people using a clipboard history manager, so that it can be configured to ignore or obscure clips of these specific types. 

I am using the chrome browser extension on Mac; I am not aware if this functionality exists on windows or in what capacity. My clipboard history tool of choice is Flycut.

**Comment by kspearrin** [comment]
We just use a standard `document.execCommand('copy');`. I am not familiar with setting pasteboard types (not a mac user). Do you know what needs to be done?

**Comment by kspearrin** [comment]
I don't see how this is possible with Javascript. Looks like something you need a native mac app to do.

**Comment by pwxn** [comment]
Yes, I started looking into it as well, and checked lastpass for reference; they are also only doing this behavior on the native app. 

Something to keep in mind then when the native apps come around.

**Comment by pwxn** [comment]
On a related note, I had looked briefly into getting the web project to run in Electron, as a cross-platform native app, and if that was the route taken it seems like Electron has this functionality in their framework.

**Comment by kspearrin** [comment]
👍

**Comment by colinfrei** [comment]
execCommand has been replaced with the Clipboard API methods, I _think_ it doesn't support setting the pasteboard type either, but it does have a mime-type, I'm not sure if that is the same?

**Comment by ChrisFR06** [comment]
> I don't see how this is possible with Javascript. Looks like something you need a native mac app to do.

Is it possible now?
