### ISSUE TITLE
Firefox: Can't delete login info

### ISSUE THREAD

**Issue by aaronbauman** [bitwarden/browser#327]
Firefox 57.0b10
Bitwarden extension 1.19.1

- click on the BW toolbar icon
- click on the "edit" pencil icon for a site
- click on "edit" again
- scroll to the bottom
- click "delete"
- click "yes" to confirm delete

expected behavior:
- clicking "yes" deletes the entry
- edit panel closes
- viewport returns to site listing
- deleted login no longer appears

observed behavior:
- clicking "yes" does nothing but close the confirm dialog
- edit panel remains open
- viewport doesn't change - still editing the login
- deleted login doesn't get deleted, still appears on site listing
- no observeable changes whatsoever
- subsequently clicking "cancel" does not delete the login
- subsequently clicking "save" does not delete the login
- there's no way to delete a login

Screencap:
![bitwarden-busted](https://user-images.githubusercontent.com/508451/32004975-1c993984-b971-11e7-99ce-1e62b33b796e.gif)

**Comment by kspearrin** [comment]
I believe what is happening here is that the server never returns a success for the delete.

**Comment by kspearrin** [comment]
@aaronbauman Would you have some time to test some possible fixes for this out with me sometime? I'm in the developer chat at https://gitter.im/bitwarden/Lobby if you can spare a few minutes.

**Comment by Primokorn** [comment]
I've just tested with bitwarden 1.20.0 and it works.

**Comment by kspearrin** [comment]
Closing for now since we released an update that should resolve this.
