### ISSUE TITLE
Extension interface does not fit into the browser area

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#328]
Hi Kyle,
I use Vivaldi 1.12.955.38 (Stable channel) (32-bit)
bitwarden 1.19.1 is installed

Sometimes when I click the extension, the bitwarden interface/window does not fit into the browser area/window.
I have seen few times happening. Most of the times it renders fine and fits into browser area

Please fix it. Thank You
![untitled](https://user-images.githubusercontent.com/31923265/32007010-f6caeb80-b9c5-11e7-9e4b-127b970eaaf3.png)

**Comment by kspearrin** [comment]
Seems like a Vivaldi bug. We don't control where the popup window renders.

**Comment by Moxville** [comment]
Thanks Kyle for your reply. I've reported this issue to Vivaldi team.
