### ISSUE TITLE
Autofill does not work when a new Firefox window opens

### ISSUE THREAD

**Issue by networkprogrammer** [bitwarden/browser#331]
I am running Firefox Beta 57.0b11 (64-bit)

After opening Firefox, Bitwarden fills login boxes using the Alt+Shift+L keystroke. 

After opening a new window, or peeling a new tab to a new window, the keystroke no longer works. Keystroke shortcut continues to work on the first opened Firefox Window.

**Comment by kspearrin** [comment]
This seems to happen with all browsers, not just Firefox.

**Comment by kspearrin** [comment]
This is fixed for next release. Thanks for the report!
