### ISSUE TITLE
Can't add new login

### ISSUE THREAD

**Issue by pannal** [bitwarden/browser#333]
I'm currently trying to add a new login for a website via the extension in Chrome.

When clicking "save", it tells me (translated) `an unexpected error has occurred`.
I've tried it several times during the last few minutes. Is this a server issue?

Update: Now it finally worked, after the extension told me that my session has expired and I needed to re-login. No connection issues or reconnects on my side.

**Comment by kspearrin** [comment]
You caught us in the middle of a server deployment. Should be resolved now.

**Comment by pannal** [comment]
Yep, thank you. 

Was this a particularly heavy server deployment? Can I expect those hickups in the future? I might consider hosting my own bitwarden server if that's the case.

**Comment by kspearrin** [comment]
Fairly standard maintenance was done with ~5 minutes of downtime. You should expect these in the future. We do deployments every few weeks.
