### ISSUE TITLE
[Edge] Unable to type characters using the alt-gr modifier

### ISSUE THREAD

**Issue by Hinton** [bitwarden/browser#335]
Got a fairly obscure bug on Edge (40.15063.674.0) with the current version of the browser extension (1.19.1).

I am unable to type any character which requires the use of the `alt gr` modifier, such as `@` and `$` on a Swedish keyboard. However if I detach the browser window using the icon in the top left corner it works fine.

**Comment by kspearrin** [comment]
Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13760501/
