### ISSUE TITLE
[Feature requests] Copy OTP code to clipboard even when using hot keys

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/browser#337]
Hi,

The feature is working very well when choosing credentials from the extension.
Maybe it has been already asked but I didn't find it.

Thank you.

**Comment by kspearrin** [comment]
This is fixed for next release (going out today).

**Comment by mindrunner** [comment]
Does not work for me...

Autofill with Mouseclickst copys the OPT into clipboard

Pressing ctrl+alt+L, autofills the website, but does not copy OTP
