### ISSUE TITLE
deleting mutliple entires is painful (bulk modification)

### ISSUE THREAD

**Issue by vvuk** [bitwarden/browser#346]
Right now, if you need to delete more than one or two entires, it's probably best to export the entire db and re-import.  Deleting is a painful process, with two annoyances along the way:

For the first entry:
- search or click on folder
- click on entry
- click on edit
- scroll to bottom
- click delete

For the next N entries:
- you're back at your search, or if no search, to the toplevel of your vault *even if you had clicked on a folder originally*; click on folder again if needed
- click on another entry
- click on edit
- scroll to bottom
- *wait for previous entry's "Deleted" notification to time out, because it covers up the delete button*
- click delete

A "bulk edit" mode that adds checkboxes next to items, allows for "select all" in response to searches, and allows for "move to folder" and "delete" actions would be really helpful.  These aren't frequently used operations, but when you want them, you really want them.

**Comment by kspearrin** [comment]
Have you considered using the web vault bulk delete options? This type of management is more suited for there rather than the browser extension.

**Comment by vvuk** [comment]
That's.. a very good point.  I completely blanked on the existence of the web vault :|  Indeed, all this is present there.  Sorry for spam!
