### ISSUE TITLE
United.com will not fill in user name

### ISSUE THREAD

**Issue by trinitron79** [bitwarden/browser#348]
When trying to log into United.com the user name field fails to populate via clicking on the bitwarden logons area or with autofill.  This was working before so I believe it's a change on United side but wanted to at least let you all know in case you're able to address it.

**Comment by kspearrin** [comment]
https://www.united.com/ual/en/us/account/account/signin

worked just fine with my test

**Comment by trinitron79** [comment]
This was off the main page, it's always worked if you were redirected to this logon page.  The main landing page is where it doesn't seem to want to work.   Not a big deal as I figured it was something on their end, definitely not a bitwarden problem but figured pointing it out helps make sure bitwarden works off every page.

**Comment by kspearrin** [comment]
I dont see a login form on the main page. I click sign in and it takes me to the link i posted previously.

![image](https://user-images.githubusercontent.com/1190944/32333441-4980c8c4-bfbe-11e7-8f6f-3912da89c009.png)

**Comment by kspearrin** [comment]
Ok, I see now. The big yellow thing that doesn't look at all like a button :)

**Comment by trinitron79** [comment]
Yep that's what where I'm talking about :)   

![image](https://user-images.githubusercontent.com/14856881/32333635-003f92e0-bfae-11e7-926c-64c6a7c521b8.png)

If you leave "Remember my Mileage Plus number" it will just have it semi hidden, that is what doesn't get updated.   If you copy / paste user name from bitwarden it works fine.

**Comment by Palf994** [comment]
@trinitron79,
Create a custom field named "MpNumber" and put your MileagePlus number as the value and that should work.

**Comment by mchugh19** [comment]
So maybe the fix here is to allow aliases on key names? Rather than recreating the username field in order for it to populate with the custom name, perhaps a feature could be added to alias fields to support the various webform names.

**Comment by trinitron79** [comment]
Thanks!  I added the custom field and that has fixed the problem!  Thanks for the tip!

**Comment by kspearrin** [comment]
This is fixed for the next version.

**Comment by kspearrin** [comment]
Can you please try now with v1.21.x?

**Comment by trinitron79** [comment]
Works for me now. (yes I removed the custom field before trying ;P )

But I did have to remove / re-add the Chrome Extension to get the 1.21.x code, mine was stuck on the 1.20.x.    Should this be auto updating?    Windows 10

**Comment by kspearrin** [comment]
It will eventually auto update. It was just pushed out so might not have propagated fully yet.

**Comment by trinitron79** [comment]
ok thanks for the fix!
