### ISSUE TITLE
Auto-fill does not work for few sites

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#351]
Hi Kyle,

a) Credentials are not properly filled for following sites. I tried to fill the credentials by right.click auto-fill and by selecting auto-fill from the extension, Either the username or the password only is filled (not both). Tried few times
http://www.geetham.net/forums/forum.php
https://mega.nz/
![untitled](https://user-images.githubusercontent.com/31923265/32381526-e27291aa-c0d8-11e7-8b17-6fe8edecb161.png)

b) auto-fill does not work for following sites. "Enable Auto-fill On Page Load" is enabled
e.g. https://mail.protonmail.com
https://zenmate.com/welcome/
https://www.scribd.com/
https://www.udemy.com/
https://my.avast.com

Browser I use is Vivaldi 1.12.955.48 (Stable channel) (32-bit)
Bitwarden 1.20.1 (installed)

**Comment by kspearrin** [comment]
- http://www.geetham.net/forums/forum.php - This website is doing something weird to replace the username field. Not sure what we can do about it.
- https://mega.nz/ - fixed in next version
- https://mail.protonmail.com - cannot reproduce. works fine for me
- https://zenmate.com/welcome/ - no login form is visible on page load
- https://www.scribd.com/ - no login form is visible on page load
- https://www.udemy.com/ - no login form is visible on page load
- https://www.udemy.com/ - no login form is visible on page load
- https://my.avast.com - cannot reproduce. works fine for me

**Comment by Moxville** [comment]
Thanks for your reply.
https://zenmate.com/welcome/ - Login page is not available on page load. Selecting "log in" button will display the login form
https://www.scribd.com/ - Login page is not available on page load. Selecting "sign in" button will display the sign in form
https://www.udemy.com/ - Login page is not available on page load. Selecting "log in" button will display the login form
https://mail.protonmail.com - Tried again. For me auto-fill on page load doesn't work.
https://my.avast.com - Tried again. For me auto-fill on page load doesn't work

Ideally "Enable Auto-fill On Page Load" feature would also work after selecting "log in" or "sign in" button (even though "log in" form is not available on page load) ?
I've seem for many sites "log in" form is not available on page load, and bitwarden extension auto-fills credentials after selecting "log in" or "sign in" button

**Comment by kspearrin** [comment]
> I've seem for many sites "log in" form is not available on page load, and bitwarden extension auto-fills credentials after selecting "log in" or "sign in" button

Can you please provide a reference site where this happens?

**Comment by Moxville** [comment]
some examples. Following sites does not have log-in form on page load. But when the click "log in" / "sign in" button, then credentials are auto-filled.
https://certcollection.org/forum/
https://geek.digit.in/community/
https://forum.glasswire.com/
https://forums.mydigitallife.net/
https://vivaldi.net/
https://www.wilderssecurity.com/

**Comment by kspearrin** [comment]
- https://certcollection.org/forum/ - Sign in takes you to a new page, new page load
- https://geek.digit.in/community/ - Login form is already loaded on page load, therefore can be filled. It just become visible when clicking the login button
- https://forum.glasswire.com/ - Login form is already loaded on page load, therefore can be filled. It just become visible when clicking the login button
- https://forums.mydigitallife.net/ - Login form is already loaded on page load, therefore can be filled. It just become visible when clicking the login button
- https://vivaldi.net/ - Sign in takes you to a new page, new page load
- https://www.wilderssecurity.com/ - Login form is already loaded on page load, therefore can be filled. It just become visible when clicking the login button

The other sites you linked that do not work do not have log in forms when the pages load. Therefore there is nothing to auto-fill at that time. Later when you click a log in button the form is added to the page in real time.

**Comment by Moxville** [comment]
Thanks Kyle for clarifying the page load points.
I will use manual auto-fill where ever auto-fill is not happening on new page load 👍

**Comment by baarkerlounger** [comment]
@kspearrin can you check this one as well please?

https://www.fidelity.co.uk/investor/ei/login.page

Auto-filling the password with BitWarden always gives credentials not recognised even though pasting the password works fine.

**Comment by kspearrin** [comment]
@baarkerlounger I am not seeing an issue while debugging it. Seems to work as expected, though I can't fully test since I don't have valid login credentials for that service.

**Comment by baarkerlounger** [comment]
@kspearrin not sure what other information I can give but I can consistently reproduce it. When I click bitwarden - copy the password and paste it, I login no problem. When I click bitwarden autofill it doesn't recognise my credentials (this is on the password screen, the username autofill works fine).

**Comment by kspearrin** [comment]
This page right?

![image](https://user-images.githubusercontent.com/1190944/33129359-a13b72ae-cf5d-11e7-9273-20eb6dee473a.png)

**Comment by baarkerlounger** [comment]
Yep

**Comment by kspearrin** [comment]
Yes, I have inspected the autofill process and I only see if autofilling the username and password fields with the correct credentials so I am a bit unsure at this time. The only thing that may be problematic is that I see the username field is `readonly` on this page (from the previous page username fill). Bitwarden is filling the username again on this page so maybe they have some logic that is rejecting that.

**Comment by kspearrin** [comment]
@baarkerlounger I added some checks to ignore readonly and disabled fields in the next version. We'll see if that changes anything.

**Comment by baarkerlounger** [comment]
Cool, anything I can do to help test?

**Comment by baarkerlounger** [comment]
Cool, thanks

**Comment by kspearrin** [comment]
You could install and test a local build if you like. Here's a compiled version of the fix: https://ci.appveyor.com/project/bitwarden/browser/build/artifacts

**Comment by allandavid** [comment]
Only the username gets filled in this website https://internet-banking.retail.dbsbank.in/login
