### ISSUE TITLE
Credit card auto-fill

### ISSUE THREAD

**Issue by benshep** [bitwarden/browser#356]
Is the credit card information supposed to be able to be auto-filled? I didn't see that option anywhere - just the option to edit the info, or to copy it.

**Comment by kspearrin** [comment]
Yes, select it from the list on the "Current Tab" tab when viewing a credit card form.

**Comment by benshep** [comment]
Thanks! I'll try that next time.

Ben

**Comment by Snuupy** [comment]
Hi, 

I see that credit card autofill only works if you click it from the main screen and not if you search for the specific card you want to use. If you search for the card, bitwarden defaults to viewing the card details. I find this unintuitive, and would prefer to have it autofill.

There is a separate discussion on [reddit](https://www.reddit.com/r/Bitwarden/comments/bbmkou/bitwarden_creditcard_autofill/?)  with other users are also claiming that this is unintuitive. Could I have this issue re-opened please?
