### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by ArtemNikolaev** [bitwarden/browser#36]
Angular have some special rools about Dependency Injection: [DI](https://docs.angularjs.org/guide/di)

Its need for requireJS or any other js minifier, becouse without it gulp can't minify code correctly and all functionality just don't work.

I believe, that production code must be combined and minified, and right DI can help to do it for the preject.

**Comment by kspearrin** [comment]
There is no need to minify the code in the browser extension. 1) The extension is downloaded once by a user and ran locally so there is no need to try to save a few extra kb of space (as opposed to a website like the web vault). 2) Minifying/obfuscating code is not allowed and will get rejected during our review process with the different browsers.
