### ISSUE TITLE
Updating to Premium failed in Firefox Extension

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/browser#363]
I just purchased a premium membership a couple of minutes ago, but my Firefox browser extension kept saying I'm not premium. I clicked the refresh button on the premium membership feature page, it said it did a refresh (refresh successful or similar) but it kept claiming I'm not premium. I tried it three times, but that just didn't work. Then I logged out and back in and after doing so, the status was finally correct (now it says I am premium and offers me to manage membership).

Firefox 57.0b14 (64-bit), macOS 10.13
bitwarden extension 1.20.1

**Comment by kspearrin** [comment]
Thanks. We'll check it out.

**Comment by kspearrin** [comment]
Fixed for next version.
