### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by Coffmans** [bitwarden/browser#364]
One of the nuisances for other password managers, such as LastPass, is support for HTTP basic authentication logins. I have a number of sites (mostly work related) where the HTTP basic authentication popup box (Chrome) needs the username and password. By using HTTP basic authentication, the auto-fill does not work and the username and password need to be entered manually or copied/pasted from the password manager. 

I performed a search to see if there was an existing ticket for this functionality and I could not find one. Not sure if it is an issue or should be considered an enhancement. In any case, I wanted to check if there were plans to support the authentication.

**Comment by kspearrin** [comment]
We actually do have support for this, as far as the APIs will allow. See here for more info: https://github.com/bitwarden/browser/issues/116

**Comment by Coffmans** [comment]
Ah, the key to the auto-fill with authentication is the requirement of single sign-in for the doman. I was similar to other users where I had multiple logins for the various sub-domains. I will have to do some tinkering with my workflow to see how best to use this approach.

**Comment by kspearrin** [comment]
Hopefully that can be mitigated when we introduce better control over subdomains with https://github.com/bitwarden/browser/issues/77
