### ISSUE TITLE
Dropdown menu on forms

### ISSUE THREAD

**Issue by bfabio** [bitwarden/browser#368]
Lastpass-like dropdown menus on forms would be a big step forward when it comes to usability:

![Lastpass menus](https://lp-cdn.lastpass.com/lporcamedia/-/media/39a191babb9043098a1becf58bd4bf91.png?h=886&w=2124&la=en&hash=D3DD2120391C9AEE44A23392DE9D37CDCA4E9F0F)

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/browser/issues/3
