### ISSUE TITLE
Generate password and add website to vault

### ISSUE THREAD

**Issue by lucacome** [bitwarden/browser#37]
Is it possible to have an option when registering to a new website and therefore generating a password to add website to the vault with login/password?

**Comment by kspearrin** [comment]
There is a task here (https://github.com/bitwarden/browser/issues/4) tracking something that will make it more automated, however, it's pretty simple to do today still. When registering for a new site, simply open bitwarden on the "Current Tab" page. Click the `+` at the top to add the site and generate a random password. Once saved, simply click it and it will autofill into your registration form.

**Comment by lucacome** [comment]
I have to refresh the page for the autofill to see it...right?

**Comment by kspearrin** [comment]
No, you should not

**Comment by kspearrin** [comment]
Closing since this is tracked elsewhere.
