### ISSUE TITLE
Bitwarden icon disappears after restarting Firefox

### ISSUE THREAD

**Issue by guojing0** [bitwarden/browser#370]
I installed Bitwarden several days ago and recently after restarting Firefox, Bitwarden icon takes its place but does not display correctly. So I could not use it.

**Comment by kspearrin** [comment]
Im not sure I understand.

> Bitwarden icon takes its place but does not display correctly

How does it display? Can you provide a screenshot?

**Comment by guojing0** [comment]
It's OK now.
