### ISSUE TITLE
Display in entry field visual indicator that bitwarden has an associated entry.

### ISSUE THREAD

**Issue by jyavenard** [bitwarden/browser#374]
This is something LastPass does.

When you got to a site that has a login form, if there's a matched entry in the vault, a little symbol is displayed on the right hand side of the login form.

Bitwarden displays nothing. if the bitwarden tool is visible in the toolbar it will show a number there (corresponding to the number of entries for this site), but this tool logo isn't always there.

LastPass handling is much more user friendly.

would be nice for bitwarden to do the same.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/3
