### ISSUE TITLE
Have option to fill forms

### ISSUE THREAD

**Issue by jyavenard** [bitwarden/browser#375]
Bitwarden in issue #19 added the ability to store custom forms, either addresses or credit card.

But those are pretty much restricted to storage use only. They serve no purpose in a web page unfortunately.

LastPass has a contextual entry Form Fills which allows to select which credit card, or address forms to use.

It would be nice to have this feature in bitwarden.

I switched to bitwarden out of necessity as it was the only password/form manager available as a webextension.
LastPass is now once again available in Firefox Quantum, and it only reminded me on how much this feature is missing in bitwarden.

**Comment by kspearrin** [comment]
cards and identities can be used for auto-fill, that is why they are presented on the "Current Tab" page. Autofill detection is pretty basic in the current version but is much smarter in the next version going out soon.

**Comment by jyavenard** [comment]
everytime I click on the form stored I get the message:
"Unable to auto-fill the selected item on this page. Copy and paste the information instead."

that's why I just assumed it didn't work.

**Comment by kspearrin** [comment]
This is because the current version only looks for certain autofill hints which many websites do not implement. The next version adds more intelligence to the detection.
