### ISSUE TITLE
[Firefox] Copy OTP to clipboard using keyboard shortcut

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/browser#378]
Hi,

Copying OTP to clipboard is working fine when selecting credentials from the extension icon. It doesn't work when using the keyboard shortcut `Ctrl+Shift+L`

*bitwarden 1.20.1*
*firefox stable portable 56.0. (32 bits)*
*Windows 7 Pro*

**Comment by kspearrin** [comment]
I assume you are using Firefox? Firefox requires you have the popup open to access clipboard. This works in Chrome.

**Comment by Primokorn** [comment]
Yes, firefox as stated above.
Do you if it's tracked in bugzilla? Excet if it can't be considered as a bug/FR for Mozilla.

**Comment by kspearrin** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard

> Browser-specific considerations
> 
> In Chrome:
> 
> You can write to the clipboard like this in all execution contexts - background pages, content scripts, options pages, and popups.
> You don't actually need "clipboardWrite", even to write to the clipboard outside a user-generated event handler.
> In Firefox:
> 
> You can write to the clipboard like this in all execution contexts **except background pages**. In Firefox you can't select text or focus an input field in background pages, so you can't write to the clipboard from a background page.
> The "clipboardWrite" permission is only supported from version 51 onwards.
> From version 57 onwards, you can copy images to the clipboard using the clipboard.setImageData() API.
