### ISSUE TITLE
Allow showing password in "edit" mode

### ISSUE THREAD

**Issue by rggjan** [bitwarden/browser#380]
Currently, in bitwarden it is possible to show the cleartext password, but not edit itt at the same time. When going to "edit" the password will always show as dots.

The problem is, when editing a password (e.g. because a mistake was typed when entering it, or when changing some characters in the password to update it), you have to do the following:
1. open the corresponding entry
1. click the "eye" besides the password to show the password
1. copy it
1. paste it in some text editor
1. change it
1. copy it from the text editor
1. go back to bitwarden
1. click "edit"
1. paste the changed password

The following workflow would be much better and shorter:

1. open the corresponding entry
1. click "edit"
1. click the "eye" besides the password to show the password (**in edit mode**, this feature is currently missing)
1. change it

**Comment by rggjan** [comment]
Possible duplicate of https://github.com/bitwarden/browser/issues/292

**Comment by kspearrin** [comment]
This is now available.

**Comment by rggjan** [comment]
Awesome, thanks!
