### ISSUE TITLE
Autofill closes Google signin window on review site.

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#382]
Report via email:

> Bit Warden doesn't work signing into google to write a review for businesses. It closes the sign-in window when you click to fill with Bit Warden.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
