### ISSUE TITLE
Duplicate folder names allowed

### ISSUE THREAD

**Issue by redwards510** [bitwarden/browser#383]
**Repro**: go to folders in settings. create a folder named "test". then create another folder named "test". Both now exist in the list of folders and it makes it quite confusing when you need to save into one of them because you cannot remember which is the "good one".

**fix**: add validation preventing duplicate folder names. they should be allowed on import though, possibly flattened since that's how they came..

**Comment by Banderi** [comment]
I understand the wish for customizability, but the presence of this generate a huge series of problems. For instance, importing from other vaults (or Bitwarden itself) will result in duplicate entries with no way to bulk delete all folders prior. If you wish to let users have the ability to have duplicate folder (which is still borderline asinine and almost no user would find a user for such feature) I would suggest making the preventative measure the default option, and asking for special confirmation when users manually put in a duplicate name for a new folder.

**Comment by DamianFekete** [comment]
> We don't plan to implement this. A user can create a folder with the same name if they want to.

@kspearrin, could you please provide some reasoning for this? Are people really using this function?
