### ISSUE TITLE
On Firefox on Android, the bitwarden menu entry sometimes disappears.

### ISSUE THREAD

**Issue by rggjan** [bitwarden/browser#386]
On Firefox on Android, the bitwarden menu entry sometimes disappears.

To make it appear again, it is necessary to restart Firefox.

Firefox 57.0

**Comment by kspearrin** [comment]
Sounds like a Firefox bug. Have you tried contacting them on bugzilla?

**Comment by rggjan** [comment]
I didn't think about that. Just filed a bug report with Mozilla as well:

https://bugzilla.mozilla.org/show_bug.cgi?id=1419062

**Comment by kspearrin** [comment]
Seems they acknowledged the bug. Closing.

**Comment by rggjan** [comment]
sure, thanks!

**Comment by scheinercc** [comment]
There might be a fix coming this way: https://bugzilla.mozilla.org/show_bug.cgi?id=1414084
