### ISSUE TITLE
Extension credentials order/favourite-flag broken

### ISSUE THREAD

**Issue by eltismerino** [bitwarden/browser#387]
Hey,

since about a day - I guess the extension was updated - the favourite flag doesn't seem to be taken into consideration when auto-selecting the appropriate credentials for the current site.

It always selects the first credentials in the list.

**Comment by kspearrin** [comment]
The favorite flag was never taken into account with this logic. It should be using the **last used** credential for autofilling.

**Comment by eltismerino** [comment]
Ok, weird. Then maybe the last used history was cleared with the last update? It definitely changed its credential selection this morning.

**Comment by kspearrin** [comment]
Looking into it more.

**Comment by pannal** [comment]
Hmm, I just opened a site with two logins, which didn't get auto-filled. Once I added the favourite-flag to one of the logins, and refreshed the page, it auto-filled. Am I missing something here?

**Comment by kspearrin** [comment]
There was a bug with the last used logic. This has been fixed in v1.21.3 which is now available.
