### ISSUE TITLE
Regression: Sort exact URL matches first 

### ISSUE THREAD

**Issue by mbudde** [bitwarden/browser#391]
The change made in https://github.com/bitwarden/browser/pull/108 no longer seems to work. I get exact matches that end up in the bottom of the list.

I suspect the cause might be that the following code should be updated to use `cipher.login.uri`. But that's just a guess from reading the code.
https://github.com/bitwarden/browser/blob/56c1ca7d2f3c514d0d3b8c1f0bc732ca192ab835/src/popup/app/current/current.component.ts#L144-L147

**Comment by kspearrin** [comment]
Yep, that got missed in the refactor on ciphers. Fixed for next version.

**Comment by SimKennedy** [comment]
@kspearrin 
Sorry to comment on an old issue, and forgive me if I'm wrong, but has this behaviour regressed again?

When I set a login to "Host" or "Exact" it still does not appear above any more recently used login that only matches the domain?

**Comment by kspearrin** [comment]
I believe the functionality has changed. Results in the autofill list are now just sorted by most recently used.
