### ISSUE TITLE
EA.com doesn't offer to save credentials when enter button pressed to log in

### ISSUE THREAD

**Issue by HizzyHaz** [bitwarden/browser#394]
BW doesn't prompt to save login on https://www.ea.com/

**Comment by kspearrin** [comment]
Testing here seemed to work just fine:

https://signin.ea.com/p/web2/login?execution=e912050662s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fresponse_type%3Dcode%26client_id%3DEADOTCOM-WEB-SERVER%26redirect_uri%3Dhttps%253A%252F%252Fwww.ea.com%252Flogin_check%26state%3D8dd0d122-e163-42e0-8a87-2d0602f1d15b

**Comment by kspearrin** [comment]
I just tested it again, using your link (which looks like the same page I tried earlier) and it still works fine. I'm not sure. Anyone else able to confirm?

**Comment by getreadyforme** [comment]
Wow this is weird!  I realized the following completely by accident: It does work when I enter my login credentials and then click on the Login button with my mouse.  But it does **NOT** work if I hit the Enter button after typing in my password.  Naturally I'm used to just hitting Enter on the keyboard.  

Let me guess, you've been using the mouse to click the button..?

![ea2](https://user-images.githubusercontent.com/7669787/33227313-56750682-d155-11e7-8ff0-bf89a25e5c4b.png)

**Comment by kspearrin** [comment]
Indeed. That would explain it. That website form must be intercepting the enter button press and posting the form with javascript. This causes it to not trigger out event listeners on form post. Unfortunately we don't have a good workaround for this kind of behavior at this time. I'll let it open though.

**Comment by getreadyforme** [comment]
OK, as long as you're aware of this, it's all good.  Hopefully not too many websites use that methodology.  
I don't mean to be a pain in the a$$, so I'll just ask - should I post any other similar issues on other URLs in the future?

**Comment by kspearrin** [comment]
If you find others, sure.

**Comment by getreadyforme** [comment]
Cool.  Thanks for the great app and keep up the good work!

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
