### ISSUE TITLE
New Site Notifications

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#4]
Detect when a form on a website is submitted. If it is determined to be a registration form or a new login that does not yet exist in the vault, overlay a notification at the top of the page asking the users if they would like to automatically save the information submitted into their vault. This will allow users to more quickly add new sites into the vault without having to open the browser action popup for the current tab.

**Comment by KarimGeiger** [comment]
I think that's one of the most important features to get this service out to the masses.

But, overall: bitwarden makes an awesome first impression and I can't wait to start using it.

**Comment by kspearrin** [comment]
This feature is now available in v1.8.0: https://github.com/bitwarden/browser/releases/tag/v1.8.0
