### ISSUE TITLE
[Firefox] Search Vault

### ISSUE THREAD

**Issue by Attoy** [bitwarden/browser#400]
When I click on the addon icon and start to type something to search on my vault the very first character I type is never typed but it is used to switch from the "Tab" tab to the "My Vault" tab, is it the expected behaviour? I'd like if it counts also my first character typed.

Just for example, I click on my addon icon, click to enable the "Search vault" field and I type "google" it shows only "oogle". I hope I was clear enough to explain this *weird* behaviour.

**Comment by c2nes** [comment]
I'm also experiencing this issue. Additionally, I've noticed that the search field is not longer activated by default upon opening the extension. Previously, I could click on the bitwarden icon and immediately start typing to begin a search. Now I have to click the bitwarden icon and then click the "Search Vault" box. The first letter I enter into the search box is discarded, but switches from the "Tab" pane to the "My Vault" pane. Then the search begins with the second letter I type.

**Comment by Attoy** [comment]
Exactly what you said @c2nes, I thought to remember that the search field was activated by default upon opening the extension but I wasn't completely sure. Let see if @kspearrin can shed some light about it.

**Comment by kspearrin** [comment]
This is fixed for next version. It is a regression bug.
