### ISSUE TITLE
Different defaults between Chrome and Firefox extension

### ISSUE THREAD

**Issue by troyengel** [bitwarden/browser#402]
Version 1.21.4 fresh install on both browsers:

* In Firefox, the Disable Analytics is On (disabled) by default
* In Chrome (Chromium), the Disable Analytics is Off (enabled) by default

Very minor, setting up three workstations each with both browsers and found this discrepancy. No opinion on if the default is On or Off, just that they should be the same. :)

**Comment by kspearrin** [comment]
It is off in Firefox by default because their extensions policy requires it to be opt-in.

**Comment by troyengel** [comment]
Gotcha, thanks!
