### ISSUE TITLE
[Firefox] Detached pop-up window starts up blank

### ISSUE THREAD

**Issue by vamcs** [bitwarden/browser#403]
Firefox 57.0
Bitwarden Extension 1.21.4
Elementary OS Loki 0.4.1 (Built on Ubuntu 16.04.3 LTS)

After clicking on the button to detach the extension window to a pop-up, the window is completely blank until I resize it. This didn't happen on Chrome, where the pop-up window starts up just fine.

**Comment by kspearrin** [comment]
Until you resize it? So dragging the window out 1 more pixel makes everything appear and work as normal?

**Comment by vamcs** [comment]
Yeah, exactly. It suddenly shows up after I resize it.

**Comment by kspearrin** [comment]
Sounds like a Firefox bug. Doesnt happen on Windows. Could you open an issue with Bugzilla?

**Comment by vamcs** [comment]
Makes sense, I'll do so. By the way, I just hovered my mouse over the pop-up window and the page showed up. Something's slow with Firefox, I guess. Thanks!

**Comment by begincalendar** [comment]
I'm also experiencing this issue on Ubuntu 16.04 in Firefox.

I don't know if relevant, but these are the error messages that appear in the console when debugging the add-on and opening a detached vault/window:

[![console-errors.png](https://s17.postimg.org/ffra1szjz/console-errors.png)](https://postimg.org/image/9etl4qcxn/)

_Note that I cleared the console prior to triggering the opening of the window._

**Comment by kspearrin** [comment]
@begincalendar I believe an issue was opened with Mozilla about this since it does not seem to be related to bitwarden.

**Comment by dmusican** [comment]
I'm experiencing precisely this same problem. @vamcs, were you able to post this to bugzilla, and if so, where is it? I'd like to follow that bug if I can and indicate I'm experiencing it as well (Ubuntu 16.04). Thanks also for posting the workarounds; at least knowing that I can resize the window is helpful.

**Comment by moham96** [comment]
Same problem here running on manjaro linux, firefox 60

**Comment by vamcs** [comment]
@dmusican hi! I ended up never replying to you. No, I was lazy/busy and never reported it to Mozilla. I have never reported anything on Bugzilla; do you know how to do it?

**Comment by dmusican** [comment]
@vamcs It's pretty similar to reporting things here. Here's the link:

https://bugzilla.mozilla.org/enter_bug.cgi
