### ISSUE TITLE
Delete the refresh token on logout

### ISSUE THREAD

**Issue by VictorNine** [bitwarden/browser#406]
The plugin should ask the server to delete the refresh token on logout

**Comment by troyengel** [comment]
This might be related (not sure) -- both Firefox and Chrome upgraded to 1.22.0 yesterday, my setting for Lock is "on Restart", as at work I close out my desktop at the end of the working day. When I came into work today, logged in and started both browsers the Lock config was reset to "Never" on both, and my password vault was unlocked.

Same problem? Different issue? This concerns me, as my passwords were left vulnerable while I was not in control of my workstation overnight. :(

**Comment by kspearrin** [comment]
@troyengel That is a different issue. Please open a new issue.

**Comment by VictorNine** [comment]
This is not as easy as I first thought. If the refresh token is deleted and you have multiple clients the others will get confused. There should be a way to log out individual clients like you can in lastpass.
