### ISSUE TITLE
[Firefox 57] Password Generator does not remember settings

### ISSUE THREAD

**Issue by erousr** [bitwarden/browser#407]
The Password Generator tool will not save settings. This makes it very difficult to quickly generate a password.

Using Windows 10 / Firefox 57.

**Comment by kspearrin** [comment]
I just tested this on Windows 10, Firefox 57, Version 1.22.0 and am not able to reproduce. Restarting the browser seems to remember my previously set generator settings.

**Comment by erousr** [comment]
Alright.

Perhaps it's an addon incompatibility.

I will try to figure it out.

Thanks for a great application.

**Comment by erousr** [comment]
Okay, this issue can be closed. I am not sure what solved it. I simply restarted Firefox in and out of Safe Mode and then it started working. The issue was probably due to one of my many other addons. (cookie/adblock?)
