### ISSUE TITLE
Lock setting was reset to 'Never' on 1.22.0 update yesterday

### ISSUE THREAD

**Issue by troyengel** [bitwarden/browser#409]
(pulling this over from #406)

Both Firefox (57) and Chrome (62.0.3202.94) upgraded the Bitwarden browser extension to version 1.22.0 yesterday (2017-11-29). My setting for Lock is "on Restart", as at work I close out my desktop at the end of the working day and have all memory cookies flushed and cache cleared (work stuff). When I came into work today, logged in and started both browsers the Lock config was reset to "Never" on both, and my password vault was unlocked in both browsers when I started them up for the day. My passwords were accidentally left vulnerable while I wasn't in physical control of my workstation. :(

Not exactly sure how to help reproduce it easily since they're both already upgraded, I might have a laptop at home that hasn't upgraded yet so I'll take a look there carefully and try to capture more details somehow if so. I imagine "something" caused it to revert to it's internal defaults during the upgrade process or subsequent browser starts.  Any idea where are the config settings stored on disk so I can try and catalog them before upgrading?

I'm aware 'Never' is the default from when I first installed and configured the extensions -- for best security, perhaps the builtin fallback default should be "on Restart' instead of 'Never'? Generally it's always a good idea for security to fail closed, not fail open... $0.02

**Comment by kspearrin** [comment]
I am using on restart as well and did not see this happen when I upgraded yesterday so I am unsure what is going on here. Do you know what version you were on previously? @Moxville mentioned in chat yesterday that he saw them happening in Vivaldi browser when upgrading from 1.20 => 1.21, which I was not able to reproduce either. But when he upgraded from 1.21 => 1.22 (today) his settings were not lost.

**Comment by troyengel** [comment]
Actually, I do! I listed it in the other issue #402 that we closed the other day when I discovered the installation defaults were different from FF to Chrome due to policy. I would have had 1.21.4 installed prior to this upgrading.  (I just learned about Bitwarden over the weekend so the 1.21.4 was the very first install on both of these browsers on Monday when I came to work)

**Comment by troyengel** [comment]
Can you help me unwind this piece of code here? I'm not a javascript ninja so don't fully grasp what it means:

* https://github.com/bitwarden/browser/commit/ab1a918326333437bc1afb72ed1d191d9b7475fa#diff-986b7f8349cbfc194a54c4c38788a005R35

There were only really two commits that I see dealing heavily with `lockOption`, this one bit of code is the only thing so far that has caught my eye -- should that be a `!==` there? (a Google led me to reading this: https://stackoverflow.com/questions/16204840/javascript-comparing-to-null-vs ) The accepted answer pretty much spells out what I'm curious about - was it undefined, or actually defined and just null? (just trying to help, I have no clue what I'm doing - I don't javascript :) )

**Comment by kspearrin** [comment]
@troyengel As far as I can tell, that code is correct. `getObjFromStorage` will never return `undefined`.

**Comment by Moxville** [comment]
My settings are preserved during update from 1.21.4 to 1.22
I checked it my desktop and laptop. No issues for me.

**Comment by troyengel** [comment]
Yeah I mean I can't reproduce this to help figure out what went wrong, it definitely happened though. I restored a few backups from the beginning of the week (I figured out where Firefox stores the data), and 'lockOption' is `-1` in all of them so just no clue how it happened. :-/  Might not be much sense in keeping this issue open if we can't reproduce it to fix.

(Firefox stores the data in `${HOME}/.mozilla/firefox/(profile)/browser-extension-data/{446900e4-71c2-419f-a6a7-df9c091e268b}/storage.js` if anyone is curious, run it through any JSON tool to make it readable)

**Comment by kspearrin** [comment]
@troyengel 

So you did restored a backup and went through the upgrade process again and it worked correctly?

**Comment by troyengel** [comment]
That I did not try, will add to the list of things to try this weekend if I can -- no I meant I just restored the files and compared them for any changes or differences to the non-password data blocks. There was no variance in the stored data which might indicate "corruption" or change from the way it was stored between the Bitwarden releases other than the sync timestamps (like perhaps it was a number and is now a string or vice-versa - `-1` remained an int and was never a string by accident, etc.)

Generally (cutting out useless info) other than timestamps, the settings have not changed on disk storage in Firefox between releases:
```
    "settings_REDACTED_UUID": {
        "equivalentDomains": [
            [... lots of domains ...]
        ]
    },
    "lastSync_REDACTED_UUID": "2017-12-01T16:57:51.093Z",
    "lockOption": -1,
    "disableContextMenuItem": true,
    "disableFavicon": true,
    "sitesLocalData": {
        "REDACTED_UUID": {
            "lastUsedDate": 1512147530575
        },
        "REDACTED_UUID": {
            "lastUsedDate": 1512136394085
        }
    },
    "disableAutoTotpCopy": true,
    "collections_REDACTED_UUID": {},
    "neverDomains": {
        [...some domains...]
    },
    "disableGa": true
```
The only variance that is expected is the new `neverDomains{}` and `collections{}`from the new features added (thanks!) between the releases of the extension.

**Comment by troyengel** [comment]
I was unable to make it happen again, which I know makes it impossible to fix. We might want to close this issue unless someone else can make it happen on demand?
