### ISSUE TITLE
Support for IP addresses

### ISSUE THREAD

**Issue by blindly** [bitwarden/browser#41]
The vault assumes everything will be a website link, but it doesn't have to be.

When adding any other kind of link, it tries to guess what the domain is. This gets particularly tedious with IP addresses. When it's an SSH link (totally made up by using the ssh://) it only shows the last 2 segments.

For example:
ssh://192.168.1.100 shows as 1.100

This results in having to click edit to see what the IP address needs to be.

![1](https://cloud.githubusercontent.com/assets/1953656/20142453/cd4c27e6-a662-11e6-89ae-bd30e8e76aa2.PNG)
![2](https://cloud.githubusercontent.com/assets/1953656/20142455/d0fe35aa-a662-11e6-8e15-a6c92c910abd.PNG)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/18
