### ISSUE TITLE
Search in Vault does not provide desired result sometimes

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#411]
Hi Kyle,
Some keywords search in "vault" does not provide the desired results.
Example, if I search for keyword "proton" I get results which are not related to "proton" keyword. Check screenshot below
Sometimes the results are accurate. Example if I search for keyword "learn", I get results only names containing the word "learn"
![untitled](https://user-images.githubusercontent.com/31923265/33474269-dabced34-d69f-11e7-9b48-0e3b27afd328.png)

Is search vault can be tweaked to show accurate results ?

**Comment by kspearrin** [comment]
Search looks at Name, Subtitle, and if it is a login the URI. One of these must have the term you are searching for in them. Look at the URI.

**Comment by Moxville** [comment]
you are correct. I just noticed that.
So is it possible to add advanced search options for user to tweak the search settings accordingly
a) Option to search Vault only by "Name"
b) Option to search only by "login"
c) Option to search only by "content"
In my opinion this will be a useful addition. Please consider. Thanks

**Comment by kspearrin** [comment]
Please open a new issue if that is a feature request.
