### ISSUE TITLE
Bug: Unable to use alternate Two-Factor Authentication Method

### ISSUE THREAD

**Issue by trparky** [bitwarden/browser#414]
In the browser extension there's no way to choose an alternative Two-Factor Authentication method. If you click on "Use another two-step login method" and you have Duo enabled it gives you no other method to login with other than using Duo and using a recovery code.

Myself I have three forms of two-step logins, just to make sure that I never get locked out of my account. The problem is that once Duo is enabled the browser extension doesn't give you any other option.

**Comment by trparky** [comment]
Oh, this seems to be only an issue with the Microsoft Edge extension.

**Comment by kspearrin** [comment]
What alternate 2FA ,method? U2F is not support by Edge, for example, which is why it is not shown.

**Comment by trparky** [comment]
Google Auth-style and Email auth.

**Comment by kspearrin** [comment]
@trparky Those should definitely be showing up, so I will have to investigate.

**Comment by trparky** [comment]
OK, I was just testing stuff. I tend to like to try and break stuff. LOL

Firefox and Google Chrome extensions work fine, just not the Microsoft Edge one. Oh well, two out of three ain't bad.

**Comment by kspearrin** [comment]
Fixed for next version. Thanks.
