### ISSUE TITLE
Semicolon in notes field may interfere with vault export tool

### ISSUE THREAD

**Issue by Palf994** [bitwarden/browser#416]
I noticed recently that if I export my vault as a .csv file, a semicolon in the notes field can interfere by shifting all values following it one column to the right in the spreadsheet. I noticed that this doesn't happen every time, but it seems like it does if there is no line break following the semicolon. For example, in one note I had a phone number followed by a semicolon and then some text. Eg. "123 456 7890; SomeText". In the .csv file the phone number was in the notes column, and "SomeText" was in the next column (URI, I think). Then the URI was in the password field, etc. The semicolon itself wasn't exported. This doesn't seem to affect how the vault entry autofills a website, only how it looks when it's exported.

In other notes I had also used semicolons, but they were a part of longer sentences that ran over multiple lines. For these the notes exported correctly including the semicolons. I'm not sure if it's the line break that's doing this or something else, but thought I'd let you know.

Thank you for your hard work on this project.

**Comment by kspearrin** [comment]
I am not aware of semicolon being an invalid/escapable character in CSV. Maybe excel needs some setting adjusted?

**Comment by Palf994** [comment]
It may be an issue with LibreOffice. I'll do some more investigating and see what I can find out.

**Comment by Palf994** [comment]
It does appear to be an option in LibreOffice. Sorry for the erroneous issue.
