### ISSUE TITLE
Webpack task fails on Linux

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/browser#421]
@kspearrin Regarding my issues around not being able to run the webpack task on linux in #392, I was able to figure out that the `useRelativePath` setting in the `file-loader` loader was triggering the issue. 
This issue seems related: https://github.com/webpack-contrib/file-loader/issues/149

 I'm not sure if that is a required setting on other operating systems, but setting it to false fixed my build issues, and based on some initial testing, the extension functioned normally. I don't much understand what it's doing however, so I'm not going to open a pull request unless this is a good fix, or if the correct fix is to wait for the issue I linked above to resolve in some way.

**Comment by kspearrin** [comment]
@Hinton ?

**Comment by Hinton** [comment]
If it works without `useRelativePath` on all platforms then it should be safe to remove. It's probably something I copied from a readme.

**Comment by kspearrin** [comment]
Looks like things still compile with `useRelativePath` commented out, but it ends up putting images in the root (with manifest) rather than in the `images` folder.

**Comment by kspearrin** [comment]
@cadecairos Can you confirm?

**Comment by cadecairos** [comment]
I can confirm that the webpack task is now working as expected on the master branch!
