### ISSUE TITLE
Custom field checkbox autofill problem

### ISSUE THREAD

**Issue by shinobumw** [bitwarden/browser#422]
Firefox 57.0.1
Bitwarden 1.22.0

-  Set the Custom Field boolean type unchecked.

Expected behavior:

- Uncheck or not check the checkbox when I click autofill.

Observed behavior:

- Whether I set the boolean type checked or not, it will check the checkbox on the first time autofill.

**Comment by kspearrin** [comment]
Looks like it toggles it back and forth each time.
