### ISSUE TITLE
Registration doesn't provide any information if the email address is already in use.

### ISSUE THREAD

**Issue by apollo13** [bitwarden/browser#424]
Contrary to the web app at http://vault.bitwarden.com, the mobile app does not give any indication when the sign-up fails due to the address already being in use.

**Comment by kspearrin** [comment]
What happens instead?

**Comment by apollo13** [comment]
You see the spinner running for a few seconds and then it just keeps showing the input fields with no error indication or anything.

**Comment by kspearrin** [comment]
I am not able to reproduce this. If I try to register with an email already in use I get an alert that says "Email X is already in use". What version are you using? I think this used to be a problem in older versions.

**Comment by apollo13** [comment]
1.22.0 is the version I got from addons.mozilla.org against the "standard" bitwarden hosted server.

**Comment by apollo13** [comment]
I can reproduce it on Firefox and Chrome(ium). The server sends the correct response:
```
{Message: "The model state is invalid.",…}
ExceptionMessage: null
ExceptionStackTrace: null
InnerExceptionMessage: null
Message: "The model state is invalid."
Object: "error"
ValidationErrors: {"": ["Email 'xxx@yyy.com' is already taken."]}
```

**Comment by kspearrin** [comment]
Whoops. I was testing with the mobile app. Just noticed this was browser extension.

**Comment by kspearrin** [comment]
Fixed for next version. Thanks.
