### ISSUE TITLE
Extension popup looses state.

### ISSUE THREAD

**Issue by apollo13** [bitwarden/browser#425]
To reproduce:
 * Open the browser extension popup
 * click `create account`
 * fill in the details
 * click on the webpage (maybe by accident or cause you wanted to copy your name from somewhere [dunno])
 * open the popup again

Now you are on the initial popup window instead of the registration form. Keeping state here would be helpful. While it is kind of a non-issue on the registration mask I expect to be really annoying when filling out a new item and copying TOTP activation codes from the browser etc…

**Comment by kspearrin** [comment]
This is why we allow you to pop-out the extension after logging in. Managing state of the extension between opening/closing the popup is not feasible.

**Comment by apollo13** [comment]
@kspearrin Popping out in firefox currently gives me an empty window that is forced to the foreground :/

**Comment by apollo13** [comment]
Ah the content seems to show once I resize it, seems buggy.

**Comment by kspearrin** [comment]
@apollo13 This is a firefox bug. See https://github.com/bitwarden/browser/issues/403
