### ISSUE TITLE
Slow to display popup when there are many cards stored

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#426]
If there are more than 50 cards stored, the BW popup is slow to load. 

It is also very slow to respond (looks non-responsive for several seconds) when scrolling to the bottom of the list and then to the top.

Recommendation: Add an option to not show cards in BW popup, or add a flag to only show most commonly used cards.

**Comment by kspearrin** [comment]
What browser is this? There shouldn't be performance issues with that few items.

**Comment by setyb** [comment]
Firefox 58.0beta10.

A total of over 500 items, but about 60 of them are cards, and so are always shown within the BW popup interface (well, you have to scroll to see all of them).

**Comment by birlorg** [comment]
With 2,621 ciphers in your vault, it's pretty slow.
Desktop app does fine and the web vault does OK, but the browser plugin (FF 59.0.2 (64-bit)) is pretty slow.

**Comment by kspearrin** [comment]
Can you see if this is now resolved in version 1.26? There were significant improvements made throughout regarding performance.

**Comment by setyb** [comment]
I read (with delight!) the changelog, and hoped for the best.  It's definitely a little faster now.  Not as big of a difference as I had hoped, but definitely a little faster.  I wish I could report even better news, because I know you put a lot of work into it.

**Comment by kspearrin** [comment]
Can you try v1.28 and see if it's better now?

**Comment by kspearrin** [comment]
Closing since this is assumed to be fixed.

**Comment by setyb** [comment]
Tested v1.28.

It seems to be somewhat faster now.  It takes about 2 seconds to populate the UI after clicking the toolbar button.  Is that within the time frame that it should operate, or is that slower than it should be working?
