### ISSUE TITLE
Extra step required to log into yahoo mail

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#427]
Google an Yahoo both require 2 pages to perform a simple login procedure (great design!).

With BW, when logging into gmail, the user specifies the account a single time, and BW will populate both the username and password fields on their appropriate pages.  Nice.

With BW, when logging into yahoo mail, the user is required to specify the account on each page of the login sequence via the BW toolbar button (IOW, twice).  Can this be made to work just like gmail, thus reducing the number of inputs required to login to yahoo mail?

**Comment by kspearrin** [comment]
This is because gmail still makes the password field available on the DOM and it then becomes visible when moving to the "next page". It's not truly two separate pages.

Yahoo likely has two distinct pages that reload the DOM, so we can't fill what's not on the page yet.

**Comment by setyb** [comment]
> This is because gmail still makes the password field available on the DOM and it then becomes visible when moving to the "next page". It's not truly two separate pages.

Thanks Kyle.  Makes sense.

> Yahoo likely has two distinct pages that reload the DOM, so we can't fill what's not on the page yet.

Can this be determined conclusively?

**Comment by kspearrin** [comment]
I just checked and yes, this is what is happening.

**Comment by setyb** [comment]
Thank you Kyle.  Perhaps some sort of "smarts" can be integrated for certain pages like that one (and other multi-page logins), where BW knows the next page will require further input from the same vault entry.

**Comment by setyb** [comment]
@kspearrin Any possibility of adding some "smarts" to workaround this issue?
