### ISSUE TITLE
Drag n drop into folders

### ISSUE THREAD

**Issue by honestserpent** [bitwarden/browser#429]
The process of adding entries to folder is a bit inconvenient to me. Maybe would be easy with some sort of drag and drop, or the possibility to add entries to a folder directly from a folder?

**Comment by kspearrin** [comment]
How would the current interface facilitate this type of functionality?

**Comment by honestserpent** [comment]
I don't think i'm understanding. The current interface does not facilitate this operation. I find moving existing entries to folders cumbersome.

**Comment by kspearrin** [comment]
I'm asking how would you suggest that this work?

**Comment by honestserpent** [comment]
I'm sorry, sometimes my english is a bit off.

Well, from the Vault tab, I would expect to able to move things around just by drag n drop.

Actually, maybe, more than drag n drop, it would be better to be able to select multiple entries and then select a destination folder. In this moment you have to do it one by one, but a "batch" move would be super useful i think

**Comment by kspearrin** [comment]
@honestserpent These type of bulk tasks can already be done from the web vault.

**Comment by honestserpent** [comment]
@kspearrin I see. Don't you think it would be useful to provide such a think in the other endpoints (mobile, browser extensions etc)?

**Comment by kspearrin** [comment]
Could be, but these type of tasks are not done very frequently so it is my opinion that a user can use the web vault whenever it needs to be done instead of cluttering up our UI in other apps with rarely used functions.

**Comment by honestserpent** [comment]
@kspearrin fair enough. In fact, it happened I would have liked this functionality right now, where I have a mess in my vault because I started saving all passwords without a structure, and only after I found myself in the process of organizing.

I guess we can close the issue then

**Comment by bentolor** [comment]
Jheez... _"Move"_. Really? Right above "Move to organization"? 

So the term "move" refers to two completely different things here: 
- One is assigning them into a new folders 
- The second one is actually moving it into a different treasure

Good UX/UI: Use same term for same action & things.

Ok – next questions: How to select those 71 entries in bulks? I don't want to promote Carpal Tunnel Syndrome…
