### ISSUE TITLE
Scrolling issue in Firefox within BW popup

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#430]
In Firefox 58.0beta10, there is definitely a scrolling issue with BW.

As the user begins to scroll down within the BW popup, the background of the headers ("Logins", "Cards") are replaced with either a black background or no background at all.  If the user pauses scrolling, the appropriate background appears (after a ~1 second lag).

When the user scrolls up, the background for the headers is replaced with details of a login or card from further down the list.  Yes, it's quite odd looking.  Once the user releases the scroll bar, the appropriate background appears (again, after a ~1 second lag).

**Comment by kspearrin** [comment]
What OS?

**Comment by kspearrin** [comment]
Can you provide a screenshot? Doesn't seem to be happening when I test on windows.

**Comment by setyb** [comment]
> What OS?

Windows 7. 

Did you try the the same version of Firefox?

If so, I'll try narrowing down potential variables.

**Comment by kspearrin** [comment]
Yes, I was on v58-beta on Windows 10. Also tested on macOS. Can you post a screenshot of what you are describing?

**Comment by setyb** [comment]
I'll work on getting you a screenshot.

In the meantime, I tried creating a brand new Firefox v58beta10 profile on Windows 7.  I then installed BW (and only BW).  The issue persisted.  So that reduces a large number of variables as the cause of the issue.

**Comment by setyb** [comment]
I emailed you a screenshot.

**Comment by kspearrin** [comment]
This looks like some sort of rendering issue on the side of Firefox. There nothing crazy we're doing here. I have seem similar things (not black bars like in your screenshot) on Firefox as well starting with v57. Could you open an issue with Bugzilla and see if the Mozilla folks have anything to say about it? I'm betting there is an issue already opened about this somewhere.

**Comment by setyb** [comment]
I just wanted to update this issue to mention that ***horizontal*** scrolling (for the Notes field) also has rendering issues, making it very hard to use.  Curious if others experience the same thing.

**Comment by setyb** [comment]
Just an update: Still an issue on BW 1.26.5 with FF60.0.

**Comment by kspearrin** [comment]
Closing this since it is a Firefox problem on Windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1426317

**Comment by setyb** [comment]
@kspearrin Kyle, I'm also getting an issue where the scrolling in the BW popup gets stuck on, as if I am holding down the scrollbar.

Would you like me to file a separate issue for that here, or do you think that's a FF bug as well?

**Comment by kspearrin** [comment]
You could open a new issue here first describing the problem and we could then determine if it's a FF bug or not.
