### ISSUE TITLE
Bitwarden Card Auto-Fill Fails on Bitwarden's own Website

### ISSUE THREAD

**Issue by BinaryPaean** [bitwarden/browser#431]
Bitwarden's Card auto-fill frequently fails to correctly fill expiration year field(s) on websites, most pointedly on Bitwarden's own website.

**Steps to Reproduce:**

1. Install Bitwarden browser extension (I am on Firefox/Windows 10).
2. Add at least one credit card to your vault.
3. Go to https://vault.bitwarden.com/#/settings/premium to upgrade to premium.
4. Use the Bitwarden extension to auto-fill CC information.

Result: The "year" expiry field is left blank.
Expectation: The CC information is fully filled in, including the year.

**Comment by kspearrin** [comment]
Seems to work for me. How do you have your year field stored? 20xx or just xx?

**Comment by BinaryPaean** [comment]
Stored as 20xx.

**Comment by BinaryPaean** [comment]
Further clues: The field ended up blank but triggered an on-page validation error. In other words, it is entirely possible the field was filled and then reset by the validation js.

**Comment by kspearrin** [comment]
This is fixed in next version.
