### ISSUE TITLE
Unnecessary side scrolling bug

### ISSUE THREAD

**Issue by oshank** [bitwarden/browser#432]
I have a custom text field that is obscenely long and prompts a side scroll. Here is a screenshot for version 1.22.0:

![image](https://user-images.githubusercontent.com/2229828/33871080-1c33a45c-dece-11e7-8816-d65339685897.png)

![image](https://user-images.githubusercontent.com/2229828/33871095-300f0eb2-dece-11e7-82b5-ba8ac12d0a65.png)

Windows 8.1 Pro, Chrome 62.0.3202.94

**Comment by kspearrin** [comment]
fixed for next version
