### ISSUE TITLE
Seperating logins for similair site domains

### ISSUE THREAD

**Issue by jdwohlever** [bitwarden/browser#436]
I've tried looking, but I see no way of setting rules to show only logins for a particular URL.
For example
domain.com/partA/login
domain.com/partB/login
Both show all logins at the domain level.
Is their a way to allow or disallow logins based on further filtering?
I want to be able to show passwords on partA only for partA
or only logins for partB when I go to partB

**Comment by kspearrin** [comment]
The solution for this was also discussed in https://github.com/bitwarden/browser/issues/77

**Comment by jdwohlever** [comment]
What solution?
I read through the entire article, and I didn't see an actual solution listed?
I use Firefox, with the bitwarden extension.

**Comment by kspearrin** [comment]
@jdwohlever The solution was determined and is being tracked in that thread. It hasn't been built yet though.
