### ISSUE TITLE
Extension menu scales badly on larger screens

### ISSUE THREAD

**Issue by lordlimecat** [bitwarden/browser#438]
I am on a laptop with a 1920x1080 primary display, and 2 secondary displays at 1920x1200 each.

If I open the bitwarden extension button in Firefox (Quantum) on my primary display, it works correctly. However, if I drag the window over to either secondary display, the bottom 4 buttons disappear. Additionally, the "edit" button disappears when selecting an entry.

**Steps to reproduce:**
1. Open firefox / chrome
2. Drag over to larger monitor
3. Open bitwarden icon and attempt to e.g. go to tools section

**What should happen:**
Buttons should appear

**What happens:**
Buttons are not visible.

**Comment by kspearrin** [comment]
Firefox bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1387340

**Comment by lordlimecat** [comment]
This also occurs in chrome latest, in exactly the same way. Please reopen this.

**Comment by kspearrin** [comment]
Also a bug in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=426656
