### ISSUE TITLE
Login credentials auto-filled in wrong input boxes in Amazon site

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#442]
Hi Kyle,
Sometimes login credentials are auto-filled in wrong input boxes.
For example in https://www.amazon.in/, when I reach the stage where I need to add my card details for payment I noticed my amazon "Login id" is auto-filled in "add card number" input box and my amazon password is auto-filled in "cvv" input box
I have enclosed one screenshot 
![untitled](https://user-images.githubusercontent.com/31923265/34194413-b75678ea-e57e-11e7-99e6-8f287c4e82f7.png)

I also noticed this in few other sites. I do not remember the site names
Its not a big issue, but just want of inform you about this issue.

Can this be improved so that bitwarden does not incorrectly auto-fill in wrong input boxes

Thanks

**Comment by kspearrin** [comment]
This would be pretty difficult to distinguish. Right now we assume any password field is what you want to autofill.

**Comment by Moxville** [comment]
Thanks kyle. Hoping in future releases this can be improved
