### ISSUE TITLE
[Enhancement] Allow specifying more granularity for lock timeout

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#449]
Lock options are currently: immediately, 1 minute, 15 minutes, 1 hour, 4 hours, and never.

Instead, can you simply allow the user to enter the number of minutes (or hours and minutes) before it auto-locks?

Thanks!

**Comment by setyb** [comment]
My apologies, this should be categorized under ***mobile***.

**Comment by vitock** [comment]
> My apologies, this should be categorized under _**mobile**_.

the browser extention also need this feature 
4hour is too short ."never "is too long ,
i need 24h option

**Comment by eliykat** [comment]
Hi @vitock, you will have the ability to set a custom vault timeout in the next release.
