### ISSUE TITLE
Import from LastPass has incorrect passwords

### ISSUE THREAD

**Issue by originalmoose** [bitwarden/browser#45]
When importing from lastpass a few of my passwords were imported incorrectly. The passwords that are incorrect contained & which I am assuming the lastpass export converted to &amp; which was imported as is to bitwarden. Replacing the &amp; in bitwarden with & fixes the passwords.

**Comment by kspearrin** [comment]
Someone else reported this a while back and then they reported back that it wasn't an issue anymore (though we didn't change anything). I suspect that this may have something to do with the encoding of the file that you safe from lastpass. Do you still have the problematic lastpass file around? Can you try saving the file with UTF8 encoding and see if it has the same problem?

**Comment by originalmoose** [comment]
That makes sense, I didn't really check the encoding when I exported. Chances are that will fix it so I'll go ahead and mark this as closed.
