### ISSUE TITLE
Bitwarden can't recognize login form inside a thread in a forum

### ISSUE THREAD

**Issue by p1nkyy** [bitwarden/browser#450]
So I'm a member of this forum called mobilism.org. It has a premium downloader, some kind of rapidleech but it's built into the forum so that you can download directly from the forum, via a blue arrow near the download link. The thing is, bitwarden can't recognize this login form. I found out the address is mblservices.org but if and when bitwarden sense this login form, it will input the login details of the forum instead (makes sense since it's located in the forum). LastPass used to be able to recognize this (the newer function can't though). Please help.
I'm using FF 56 and Bitwarden 1.22.0
Here's a screenshot of the said login form:

![screenshot-forum mobilism org-2017-12-27-15-33-18](https://user-images.githubusercontent.com/7593831/34375955-c60274b4-eb1b-11e7-8bbf-36acc97f281c.png)

You have to be registered to be able to see this. Its premium downloader has a trial period so you can try for free to see how it works.

**Comment by kspearrin** [comment]
Autofill will always fill based on the page you are on, not what the iframe is. Consider creating an equivalent domain rule so that you can still autofill. See https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7
