### ISSUE TITLE
Chrome extension logout 

### ISSUE THREAD

**Issue by kurtl1966** [bitwarden/browser#451]
hi,
i created a new account and I am able to login on my phone and in the chrome-browser. but when i want to login with the extension, it logs me out in one second with 'session timeout' (in german) i tried that on severeal pc´s, it´s always the same issue.
hope you can help me, thanks kurt
![image](https://user-images.githubusercontent.com/34885593/34379809-795ed9e0-eafd-11e7-8bce-78f238388463.png)
![image](https://user-images.githubusercontent.com/34885593/34379968-87fedcce-eafe-11e7-8745-3d65d188cd4c.png)
![bitwarden_version](https://user-images.githubusercontent.com/34885593/34379980-939626dc-eafe-11e7-8939-e0f441d06919.JPG)

**Comment by kspearrin** [comment]
Are you using bitwarden cloud server or your own?

**Comment by kurtl1966** [comment]
hi, its me again. now it is working - i´m at a different location.
could this be a proxy problem (in our company it doesnt work, but here at
home there is no problem?

2017-12-27 14:44 GMT+01:00 Kyle Spearrin <notifications@github.com>:

**Comment by kspearrin** [comment]
Not sure. You need access to identity.bitwarden.com and api.bitwarden.com

**Comment by kurtl1966** [comment]
ok thank , i´ll check that.
i think this problem can be closed ;-)

2017-12-27 15:27 GMT+01:00 Kyle Spearrin <notifications@github.com>:
