### ISSUE TITLE
Prompted to save credentials that were autofilled by bitwarden (chrome)

### ISSUE THREAD

**Issue by BradGunnerSGT** [bitwarden/browser#461]
Chrome 63 with the bitwarden extension installed. The site I was using was https://www.sweetwater.com.

I used the right-click -> bitwarden -> autofill -> site method to auto fill my username and password. After logging in, the extension prompted me to ask if I wanted to save the password that it had just auto filled.

**Comment by kspearrin** [comment]
I just tested this in Chrome 63 on macOS using extension version 1.23.0 and was not able to reproduce it. Can you try again? Not sure...

**Comment by baenglund** [comment]
I have had this on a few different websites. I've always just ignored it. Next time I'll try to remember to report back here.

**Comment by baenglund** [comment]
Firefox 60.0a1 (2018-01-26) (64-bit)
Bitwarden Version 1.24.0
https://my.voya.com/voyasso/index.html#/login

On login I autofilled credentials from bitwarden (both clicking and keyboard shortcut are affected). Upon logging in, I am presented with the popup for bitdwarden to save this password.
