### ISSUE TITLE
Identity appears with favicon for an arbitrary(?) site

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#465]
In Chrome, when I open the bitwarden extension and begin typing to search for an identity, it appears in the list with the favicon of some other site from my vault. See an example at:

https://imgur.com/a/AQ5Qs

Searching for a different identity yields a different favicon.

Running Chrome 63.0.3239.84, Bitwarden 1.23.0

**Comment by kspearrin** [comment]
Yea, I've seen this happen before. I dont think it's only an Identity problem though.

**Comment by kriswilk** [comment]
I'm definitely seeing it with both identities and cards as I organize my vault in Chrome Desktop. I'd say 25-50% of the time I get something OTHER than the generic identity/card icon. However it only seems to happen in the search mode. In the conventional list with the "logins", "cards", "identities" headings, the icons all look fine.

I have not observed this issue on mobile.

**Comment by kspearrin** [comment]
Should no longer be an issue.
