### ISSUE TITLE
[Vivaldi-Extension] UI doesn't fit in window

### ISSUE THREAD

**Issue by Thalonius** [bitwarden/browser#466]
I'm using Bitwarden utilising the Vivaldi-Extension.
On my personal laptop I've got no problems at all, but on my business laptop the UI seems to big for the window:
![bitwarden-error](https://user-images.githubusercontent.com/21099529/34672910-a9639554-f480-11e7-9380-8d11573210da.png)

If I expand the window using the button beside "Search vault" I have no problems in this window, but (of course) it looses the context of the current window.

Information about my system:
Vivaldi 
- Version 1.13.1008.36
- No other extensions are active (but "IETab" is installed, I deactivated it for testing purposes).
Windows 10 Enterprise 
- Build 15063.786 (64-Bit, Core i5)

If you need anything else just contact me.

**Comment by kspearrin** [comment]
This is a Chromium bug. Duplicate https://github.com/bitwarden/browser/issues/438
