### ISSUE TITLE
Delays with search filtering

### ISSUE THREAD

**Issue by okjed** [bitwarden/browser#471]
I've tested the extension within Chrome, Vivaldi and Firefox. Within both Chrome and Vivaldi I experience long (3-5 second) delays when beginning and editing the search within the popup. Firefox appears to work without a delay. This is with roughly 2000 entries.

**Comment by kspearrin** [comment]
Sounds like your vault is decrypting during this time. Is this just an initial delay? Does it continue to delay after it starts working?

**Comment by okjed** [comment]
Every time I open the drop down. If I go to the vault directly it doesn't have this delay.

**Comment by kspearrin** [comment]
So you're saying it only happens when actually doing a search? What about if you navigate to a folder with lots of items in it?

**Comment by okjed** [comment]
Oh, if I go to My Vault within the extension there is a significant delay initially but if I navigate into a folder it is instant (organizationally most of my entries are not in folders -- over 1500) and when I hit back to go to the top level there is a delay once again. When I mentioned vault previously, I meant when I navigate at the website.

**Comment by okjed** [comment]
I'm not sure what changed but I am not experiencing extreme delays when searching anymore.
