### ISSUE TITLE
Auto fill doesn't work for economist.com

### ISSUE THREAD

**Issue by dmusican** [bitwarden/browser#478]
I've been trying to get auto-fill to work via the Firefox plugin for `economist.com`. It fills in the password, but not my e-mail address. The HTML looks like this:

I did find this in the HTML...
````
<div class="login-form-input__wrapper login-form-input__wrapper--email">
    <input id="email-masthead" name="name" value="" required="" aria-label="email address" class="login-form__input login-form__input--email" data-com.agilebits.onepassword.user-edited="yes" type="email">
</div>

````

... so I tried a custom fields with both `email-masthead` and `name`, but it doesn't seem to work. Any thoughts?

**Comment by kspearrin** [comment]
It definitely finds and attempts to fill the field, but something the website is doing is removing it. Not sure what we can do. It does work find on this login form though: https://www.economist.com/user/login

**Comment by dmusican** [comment]
Thanks, @kspearrin. My LastPass Firefox plugin fills it in just fine, so perhaps there's something Bitwarden can do? (I'm in the process of transitioning  from LastPass to Bitwarden, because, well, Bitwarden is awesome.)

**Comment by dmusican** [comment]
I don't have 1Password installed.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
