### ISSUE TITLE
Localhost and domain rules

### ISSUE THREAD

**Issue by JourneyOver** [bitwarden/browser#479]
1 - How can I exclude localhost logins from one another? If I add say localhost:34000 I don't want the login to show up if I go to localhost:3000. Currently when adding locahost:{portnumber} the login shows up on every single localhost.

2 - Ontop of excluding localhost logins from one another, how would I go about adding localhost:{portnumber} to my "Custom Equivalent Domains"? As currently it doesn't seem to work out unless I just add it as "localhost" without the whole ":{portnumber}" bit even though as stated in 1 I only want the login to show up under a certain portnumber.

**Comment by Attoy** [comment]
I suppose this is somehow related to #77

**Comment by kspearrin** [comment]
Duplicate. Will be resolved with #77
