### ISSUE TITLE
Extension icon looks significantly more blurry and low res in Brave than Chrome

### ISSUE THREAD

**Issue by Jacalz** [bitwarden/browser#482]
If you install Bitwarden in Brave you will see that the logo is way more blurry and bad looking than the logo that is seen if you install the logo in Chrome 👎  I am sorry to say this but the logo in Brave looks really bad  🙁 See the picture here:
![image](https://user-images.githubusercontent.com/25466657/34950569-d1081ae2-fa13-11e7-82ee-b7917f254af0.png)

**Comment by kspearrin** [comment]
Sounds like a brave problem. We provide all of the necessary icons for the web extension resolutions. See https://github.com/bitwarden/browser/blob/master/src/manifest.json#L10

Seems like they are choose the lower res ones for some reason.

**Comment by Jacalz** [comment]
Looks like they are using these: Icon19
![icon19_locked](https://user-images.githubusercontent.com/25466657/34950838-98a8cde4-fa14-11e7-83f2-19694b3e9a0c.png)
![icon19](https://user-images.githubusercontent.com/25466657/34950842-9b8d5d90-fa14-11e7-8cb1-50b77fc52517.png)

**Comment by Jacalz** [comment]
Do you have any idea where the code for this would be situated?

**Comment by Jacalz** [comment]
I have contacted Jonathan Sampson on Brave about this and he promised to fix it 👍

**Comment by kspearrin** [comment]
While you're at it could you get them to update bitwarden to the latest. The version on brave is fairly outdated. See https://github.com/brave/vault-updater/issues/48

**Comment by Jacalz** [comment]
Haha already told them a couple days ago 😉 
![image](https://user-images.githubusercontent.com/25466657/34951473-bc9cc690-fa16-11e7-9631-06ba766109f6.png)
