### ISSUE TITLE
Slow for popup to appear

### ISSUE THREAD

**Issue by DMeechan** [bitwarden/browser#483]
After logging in to Bitwarden, Chrome becomes a bit laggy and it takes a few seconds before the Bitwarden popup appears with the vault.

I have ~800 items stored on my account. 

I'm also getting a lot of lag on the Android app after logging in, and it's many seconds before I'm able to view my vault (notably worse performance than the Chrome extension).

Is there anything I can do to eliminate / reduce the laggy experience on either platform?

**Comment by kspearrin** [comment]
This is likely because your vault is being decrypted during this time. 800 items is a pretty large vault to decrypt. Slower devices will obviously suffer more. Are there any performance issues after the initial log in?

**Comment by DMeechan** [comment]
After the initial log in, Chrome extension performance is fine when using a 2017 13" Macbook Pro. 

But when I switch to a 2013 15" Macbook Pro, the Chrome extension runs pretty slowly, even after the initial log in. It's not ideal, but it is usable. 

On Android, performance after the initial login is on and off. Sometimes it's perfect, other times it's nearly unusable. When I click the search button, it usually takes a second or so before the search bar appears (presumably because it's also trying to load a list of results below the search bar). It'd be great if the search bar appeared before the results loads so users can get typing immediately.

**Comment by kspearrin** [comment]
Are you using any folders or are they all in "No Folder"?

**Comment by DMeechan** [comment]
Around 70 of them are in folders, the rest are in "No Folder"

**Comment by kspearrin** [comment]
Can you try moving them all into a folder and see if that makes things better? Use the web vault to mass move them.

**Comment by DMeechan** [comment]
Wow, there's a noticeable performance improvement on both the Chrome extension and the Android app after moving everything into folders. Most folders contain around 30 items, while the largest contains 500. Performance is much better now. Thanks!

**Comment by breyed** [comment]
I think it would be good to reopen this issue. Bitwarden would be better if it was fast no matter how you organized (or didn't organize) your sites. Since it has such a nice search function, I never find organization necessary, but speed is important.

**Comment by urwrstkn8mare** [comment]
They might as well just make a default folder or allow you to set a default folder
