### ISSUE TITLE
Icon with lock shown under the label that shows if you have a site saved

### ISSUE THREAD

**Issue by Jacalz** [bitwarden/browser#484]
### Description

Same issue in both Chrome and Brave, when you follow these steps you will see the lock icon behind the label with a one that says that you have a saved logon for that site. It can be really annoying and happends a lot in day to day usage:
![image](https://user-images.githubusercontent.com/25466657/35004534-b7b822d4-faf0-11e7-8118-571ca263d108.png)

### Steps to reproduce:
1. Set the extension to lock itself immediately
2. Have two sites open that have logins saved for them (In my example I have Github and Slack)
3. Log in to the extension on tab 1 and close the extension window
4. Move over to tab 2
5. Move back to tab 1
6. Wait a couple seconds and you will see the lock pop up behind the logo

### A video of the thing in action on Chrome
 
![bitwarden bug](https://user-images.githubusercontent.com/25466657/35005126-c3226fa6-faf2-11e7-8b82-ead718797b2f.gif)

**Comment by kspearrin** [comment]
I suppose we just need to clear the badge when locking.

**Comment by kspearrin** [comment]
Badge is now properly cleared for next version.

**Comment by Jacalz** [comment]
Wonderful 👍
