### ISSUE TITLE
Firefox - Lock options "On lock" unavailable

### ISSUE THREAD

**Issue by Tchoirk** [bitwarden/browser#490]
The chrome extention has one more lock option 
The "On lock" option which i found very usefull but is unavailable on Firefox in version 1.24.0

Maybe the Firefox's extentions don't have this hability ?
I didn't found any previous issues about that, that's why i reported 
Hope it can be usefull

**Comment by kspearrin** [comment]
Firefox's API does not offer this functionality, which is why it is hidden.
