### ISSUE TITLE
Require more use of 2FA second factor

### ISSUE THREAD

**Issue by AdamWill** [bitwarden/browser#493]
I switched to Bitwarden from Lastpass (as a paying customer) and have been very happy with it (thanks!), but one thing that concerns me is that while BW supports 2FA, it almost never seems to actually require use of the second factor. Lastpass was configurable in this regard (IIRC) and defaulted to requiring it quite often - on restart of the browser, for instance, and I think even just after a long period of inactivity.

BW by comparison seems to require you to use it when first logging into the account in a given install of the browser plugin, but after that, seems to just about never require you to use it again. This is quite *convenient*, of course, but it does seem like an opportunity for improvement from a security point of view.

Thanks!

**Comment by AdamWill** [comment]
@puiterwijk , since we talked about this. One thing I forgot to mention: a manual logout requires use of the 2FA on re-login. However, it's not likely that people will remember to logout very often for this reason, I don't think.

**Comment by baenglund** [comment]
@AdamWill this seems like a duplicate of #91 #173 #249 #286 
As you can see from the other issues, they're are a lot of people interested in this issue/ feature.

**Comment by AdamWill** [comment]
Sigh...I searched for dupes by looking for 'factor', which isn't in the topic for *any* of those tickets. :P Agreed this is a dupe of #91 . Will subscribe to that.
