### ISSUE TITLE
Firefox Doesn't Auto-focus Password/Login Field

### ISSUE THREAD

**Issue by gazugafan** [bitwarden/browser#495]
I've noticed that, in Chrome and Vivaldi, clicking the Bitwarden extension icon will automatically focus the password or search field (depending on whether or not you're already logged in). This doesn't seem to happen in Firefox, though, so the process of logging in or searching requires an extra click.

Is this due to some sort of limitation or bug in Firefox's extension API? Or is there maybe something that can be done to make this work in Firefox?

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/299
