### ISSUE TITLE
Identify sidebar shortcut in menu bar

### ISSUE THREAD

**Issue by dmusican** [bitwarden/browser#497]
It looks like #392 added a sidebar keyboard shortcut (alt-shift-u for me in Linux), which is wonderful, but I only found it through searching around. The View, Sidebar menu in Firefox lists keyboard shortcuts next to items there; it would be convenient to list the keyboard shortcut for Bitwarden there next to its entry.

**Comment by kspearrin** [comment]
I don't think this is something extensions can do. Firefox controls that user interface.

**Comment by objarni** [comment]
This could be more prominent than requiring 5 minutes googling to find this closed GH issue. Maybe put it in preferences what shortcut it is for each browser/OS?
