### ISSUE TITLE
"&" imported as "&amp;"

### ISSUE THREAD

**Issue by wilbert-vb** [bitwarden/browser#498]
It has been a while ago since I imported my Lastpass vault into Bitwarden.
Today I came across a login that did not work, comparing the Bitwarden password with Lastpass revealed a difference:

Lastpass: `*****KF5G*&m`
Bitwarden: `*****KF5G*&amp;m`

**Comment by kspearrin** [comment]
This is a bug with LastPass exporter. Please see our docs at https://help.bitwarden.com/article/import-from-lastpass/
