### ISSUE TITLE
Adding a button in the textbar for user names and password

### ISSUE THREAD

**Issue by ArtexJay** [bitwarden/browser#504]
Would it be possible to add the buttons in the text field for password and username so you just have to click it to get the options of the password you have on the site, similar to that of Lastpass. I know, it's unclear so here's a picture, showing what i mean from Lastpass.
![61fae16ef17145c083bfd7b39aa6fb2d](https://user-images.githubusercontent.com/32932497/35770186-885a6720-08e4-11e8-9342-37403d2bb8c0.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/3
