### ISSUE TITLE
Autofill doesn't work in Edge

### ISSUE THREAD

**Issue by kumarharsh** [bitwarden/browser#509]
Clicking the entry in the bitwarden popover, or even right-clicking the username/password fields and selecting bitwarden > autofill > (site-name) doesn't fill in anything in Edge. There is also no feedback as to what happened.

**Comment by kspearrin** [comment]
For what website?

**Comment by kumarharsh** [comment]
Any website. Take github itself for example. Works in Chrome and Firefox, never in Edge.

**Comment by kspearrin** [comment]
GitHub is a known website that doesn't work in Edge due to Edge bugs with CSP and extensions. As far as I know, others do. Take ebay.com for example.

**Comment by kumarharsh** [comment]
Ok. Let me come back after testng out others...

**Comment by Daptonic** [comment]
Adding some info here. Edge autofill has stopped working for MicrosoftOnline sites. I was using to manage our o365 portal and as of a week or two ago, i get "Unable to auto-fill the selected item on this page. Copy and paste the information instead."

Makes the product useless to me when LastPass and others have no issues.

**Comment by kspearrin** [comment]
@Daptonic  Maybe they changed their login page? It worked before?

**Comment by kumarharsh** [comment]
@kspearrin yes, I see what you mean now. Some websites do, and some don't. I am mostly on the sites which don't work with Bitwarden+Edge, which is why I thought this had broken. Thanks for the clarification.

Can you tell me the exact bug which is there regarding CSP implementation in Edge. I'm thinking of filing a bug report with them.

**Comment by kspearrin** [comment]
@kumarharsh Websites like GitHub that have a CSP will block our content scripts from being injected. For example, try to autofill on GitHub.com and you will see:

> CSP14312: Resource violated directive 'script-src assets-cdn.github.com' in Content-Security-Policy: script eval. Resource will be blocked.

**Comment by kumarharsh** [comment]
Oh, it seems like they've fixed this (but not released it yet): https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11320212

**Comment by sebfrie** [comment]
This [fix got released](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11320212/#comment-5) in Windows 1803, aka the April 2018 update.

**Comment by kumarharsh** [comment]
Works in Edge now. Closing the issue.
