### ISSUE TITLE
Support changing keyboard shortcuts in Firefox 60+

### ISSUE THREAD

**Issue by jcs** [bitwarden/browser#512]
Previous issues had been opened for this but Firefox didn't support changing them at the time.  [Firefox 60 will have support for extensions to change their shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) and it'd be great to be able to choose different keys for Bitwarden shortcuts like using ⌘+\ on macOS for those coming from 1Password.

**Comment by kspearrin** [comment]
Lib some guy created to help with the UI for now: https://github.com/piroor/webextensions-lib-shortcut-customize-ui
