### ISSUE TITLE
How to undo "Remember me" when 2FA enabled?

### ISSUE THREAD

**Issue by jjfrv8** [bitwarden/browser#513]
I've got 2FA enabled with a Yubikey and the second time I logged in, I checked the "Remember me" option.  Now it only requires my password to log in even after manually logging out.  How can I revert back to requiring my key on log in?  I tried removing the browser add-on and reinstalling, but it didn't help.

**Comment by kspearrin** [comment]
You can deauthorize sessions from the web vault under the Settings tab (at the bottom).
