### ISSUE TITLE
Extension doesn't load after restarting Firefox

### ISSUE THREAD

**Issue by Phanx** [bitwarden/browser#517]
Possible duplicate of #370 which was closed by the submitter without explanation.

I'm seeing this same issue in Firefox 58.0.2 (64-bit) on Windows 7 (work-issued laptop). Bitwarden was working normally after installation, but the next time I launched Firefox, the Bitwarden toolbar button is missing its icon (the button is there, taking up space and showing the "bitwarden" tooltip on mouseover, but the icon image isn't shown) and clicking it opens a minimally-sized popup with no contents.

Screenshot:  
![firefox-bitwarden](https://user-images.githubusercontent.com/11352/36289461-ed7c9f58-1274-11e8-85e2-d2c501601a80.png)

Additionally, right-clicking in a password field doesn't include Bitwarden in the context menu, and the keyboard shortcut doesn't work either, so it seems the entire extension is just failing to load, though it's still shown as enabled in the Firefox add-ons manager.

I'm not sure how to go about debugging a Firefox extension, but if there's some process for getting a hold of a log, let me know and I'm happy to get it for you.

These things don't have any effect on the problem:
- Restarting Firefox again.
- Disabling and re-enabling Bitwarden in the Firefox add-ons manager.
- Uninstalling and reinstalling Bitwarden while Firefox is running.
- Disabling Bitwarden, restarting Firefox, then re-enabling Bitwarden.
- Disabling all other extensions and restarting Firefox.

This does work:
- Uninstalling Bitwarden, restarting Firefox, then reinstalling Bitwarden.

I have no such problems in Firefox on my Linux Mint desktop, Linux Mint laptop, or MacBook, so it might be Windows-specific. I'm also using the same `user.js` file on all systems, which more or less rules out the possibility of different Firefox settings being the issue.

**Comment by kspearrin** [comment]
I'm on Firefox 58 with Windows as we speak so it's definitely something with your device there. I haven't seen this before.

Can you debug the extension in `about:debugging` and see if anything shows up? It sounds like the extension is not even loaded into the browser for some reason.

**Comment by Phanx** [comment]
Here's what I did:

1. Go to `about:debugging`
2. Check "Enable add-on debugging"
3. Click "Debug" under Bitwarden

The first time, it showed errors from some unrelated addons, so I disabled all other addons, restarted Firefox, and repeated the above steps. The only things that show up in the debugging console appear to be triggered by internal browser components:

- `Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.` at `jar:file:///C:/Program Files/Mozilla Firefox/omni.ja!/components/components.manifest:175`
- `NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions]` at `chrome://global/content/browser-child.js:359

The second error seems to be the relevant one, as it repeats each time I (a) disable and re-enable Bitwarden in the add-ons manager or (b) mouse over the icon-less Bitwarden toolbar button. I also noticed that when I disable Bitwarden, the toolbar button isn't removed, but when I disable other addons, their button *is* removed from the toolbar.

I'll test with a new Firefox profile with all default settings and no extensions other than Bitwarden and report back.

**Comment by anarkopsykotik** [comment]
Got pretty much the same problem (windows 7, old HP pavilion g6 laptop, firefox 58.0.2) : launching firefox after a laptop battery shutdown, all modules seems unloaded despite the space for their icons being available on toolbar, and name appearing on mouseover. At the times, I had ublock origin, tampermonkey, disconnect, https everywhere, decentraleyes and textarea cache enabled, none of their icon appeared and they weren't working. 
Enabling/disabling them or restarting firefox didn't help. Going into their config, all settings seem to have been set to none. 
Finally got them to work by restarting in safe mode with all extension disabled, and then restarting it normally. Everything returned to normal.

**Comment by kspearrin** [comment]
This definitely seems like a Firefox bug then. Try reporting it on their bug tracker. Closing this since there isn't anything we can do about it
