### ISSUE TITLE
Auto-focus on master password field / search field

### ISSUE THREAD

**Issue by ruudkok** [bitwarden/browser#520]
When clicking the Bitwarden add-on icon in Firefox, I need to manually set focus to the master password field before I can type in my password. After logging in, I click the Bitwarden icon, I need to manually focus on the search field to find something in my vault. It would be nice to have both fields to be automatically focussed when opening the add-on popup.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/299
