### ISSUE TITLE
Autofill of cards fail when month with 2 digits is requested

### ISSUE THREAD

**Issue by roccolord** [bitwarden/browser#521]
Sites that want 01 for month Jan fails to auto fill when autofilling cards:

<input placeholder="Utgångsmånad" name="expM" id="cardExpirationMonth" type="tel" maxlength="2" data-parsley-minlength="2" data-parsley-maxlength="2" data-parsley-max="12" data-parsley-type="integer" data-parsley-trigger="change submit" data-parsley-errors-messages-disabled="true" data-parsley-required="" autocomplete="off" data-parsley-id="0877" data-com.agilebits.onepassword.user-edited="yes" class=" ">

Same is true when years with just 2 digits is requested:
<input placeholder="Utgångsår" name="expY" id="cardExpirationYear" type="tel" maxlength="2" data-parsley-minlength="2" data-parsley-maxlength="2" data-parsley-type="integer" data-parsley-trigger="change submit" data-parsley-errors-messages-disabled="true" data-parsley-required="" autocomplete="off" data-parsley-id="9723" data-com.agilebits.onepassword.user-edited="yes" class=" ">

This was found with dibs payment, https://www.dibspayment.com/

**Comment by kspearrin** [comment]
It's suppose to already handle these cases. Can you provide a link to a payment form where it does not?

**Comment by roccolord** [comment]
http://cdon.se/ /(https://cdon.eu/) does use dibs and is where I noted it. Looks like one has to create an account to get to the checkout I'm afraid.

**Comment by roccolord** [comment]
Doesn't work on Payex sites either. Doesn't fill date/month at all.

**Comment by roccolord** [comment]
Or on DB shenker.

**Comment by kspearrin** [comment]
Please provide urls to payment forms. I don’t know what these websites are.

**Comment by roccolord** [comment]
Yes I understand that but it's problematic since it most often require some type of login. Is it sufficient to save the html for the forms that are problematic and upload them here? I have been looking around if dibs have test form and they don't, same goes for payex. So it's kinda of a catch 22 atm.

**Comment by kspearrin** [comment]
Saving the page HTML might help. Attach it here and I'll give it a go.

**Comment by roccolord** [comment]
[DIBS Payment Services.zip](https://github.com/bitwarden/browser/files/1763061/DIBS.Payment.Services.zip)

Here is a Dibs payment, only Security Code was able to autofill. All other fields blank.

**Comment by kspearrin** [comment]
These card forms are just poorly labeled so it makes autofill detection difficult. I have added some fixes for them in next version, however.

**Comment by roccolord** [comment]
[Betalning _ Blocket.htm.zip](https://github.com/bitwarden/browser/files/1764373/Betalning._.Blocket.htm.zip)

This is another one, Swedens biggest trading site, doesn't fill dates, everything else fills.

**Comment by kspearrin** [comment]
Added a fix for that one too.

**Comment by Crocmagnon** [comment]
I also have problem filling on this form, only the CVV is filled : [PAYBOX.html.zip](https://github.com/bitwarden/browser/files/1787945/PAYBOX.html.zip)

**Comment by kspearrin** [comment]
@Crocmagnon This is because this website does not properly mark their forms for autofill detection, so we fall back to looking at the labels and fields names/ids.

```
<input name="NUMERO_CARTE" id="NUMERO_CARTE" size="19" maxlength="19" autocomplete="off" tabindex="1" type="TEXT">
<select name="MOIS_VALIDITE" id="MOIS_VALIDITE" size="1" tabindex="2"></select>
<select name="AN_VALIDITE" id="AN_VALIDITE" size="1" tabindex="2"></select>
```

We only have good detection for these values in English since I do not speak other languages. You can see what values we detect here, and add any others for your language if you'd like to contribute.

https://github.com/bitwarden/browser/blob/master/src/services/autofill.service.ts#L426

**Comment by Crocmagnon** [comment]
I'd love to contribute 😊 
I don't quite understand the parameter `containsOptions` of the `isFieldMatch` method https://github.com/bitwarden/browser/blob/c27f5836bfb2935ac5fd38359fb8e32a6d677e2d/src/services/autofill.service.ts#L670-L682

**Comment by kspearrin** [comment]
The contains check will check if the label/name/id _contains_ the given value. For example: "NUMERO_CARTE" contains the value "NUMERO" so it would be accepted. You would only want to do the contains check on values that are more specific and would not trigger false positives. For example, for the Cardholder name field, we will look for values that match "name", but we do not do a contains check on it since "name" is too generic and could match other fields that are not correct.

**Comment by Crocmagnon** [comment]
Ok thanks for the explanation 🙂 
The checks are case sensitive for the moment, right ?

**Comment by kspearrin** [comment]
No, use all lowercase in code.

**Comment by Crocmagnon** [comment]
Oh yes I missed the `value.toLowerCase()`
