### ISSUE TITLE
Vault search lags when searching a large number of records

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/browser#524]
I recently imported 3-4 hundred items from 1password into BitWarden, and found there's a noticable lag when entering a search query into the extension's search box.

I'm using Firefox 60, and I also see it in Chrome 64.

I wonder if there's opportunity to improve the search performance?

**Comment by kspearrin** [comment]
I have about 500 items in my vault and have not experienced any lag on Firefox and Chrome. What type of device are you using?

**Comment by kspearrin** [comment]
That said though, there is definitely room for lots of improvement in the search. It's a pretty brute force search function at the moment that relies on AngularJS repeat with a filter. Changes are planned in the coming weeks as we continue our conversion of the app to Angular 5.

I've been exploring the possibility of bringing https://lunrjs.com/ to the platform.

**Comment by cadecairos** [comment]
I've got a pretty powerful machine, Dell XPS 9550 with an i7-6700HQ CPU running Windows 10.

The delay is pretty frustrating, but usable. If you're hopeful that Angular 5 will improve performance here, I can just wait and see how it goes.

I just had a thought - does the search also look in the notes field? The 1password data I imported generated lots of data in the note fields.

**Comment by Crocmagnon** [comment]
I'm experiencing this lag but it's much more visible in the web vault than in the extension.
It's especially present when erasing the search field and the vault has to display all the logins again.

**Comment by setyb** [comment]
I can confirm this lag on Win7.  I also get some lag simply pressing the bitwarden toolbar button.

**Comment by kspearrin** [comment]
Can you see if this is improved in the newly released 1.26? There were significant changes made to try and increase performance throughout the UI.

**Comment by cadecairos** [comment]
Yes, there's a huge improvement in the responsiveness of the addon when searching for entries!

**Comment by lhorace** [comment]
Can you give profile tip, so where we can actually see where the performance problems? This ticket is you defending, and people complaining about performance. As you some majic geenie
