### ISSUE TITLE
Copy TOTP code to clipboard when autofilling on page load or contextual menu

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/browser#527]
It would be nice if the TOTP code was copied to the clipboard when using the "autofill on page load option" or even when using the autofill from contextual menu.

Currently there is no convenient way to login with TOTP when using Firefox in private browsing mode.

**Comment by kspearrin** [comment]
This is not possible in Firefox due to API limitations. Clipboard can only be accessed from popup UI.

**Comment by Crocmagnon** [comment]
Ok !
Just thinking, wouldn't it be possible to open the popup automatically when an ID with TOTP is filled in ? So you would be able to access the clipboard and copy the TOTP code anyway ?
