### ISSUE TITLE
When clicking the (locked) bitwarden icon, it takes too long until password can be entered

### ISSUE THREAD

**Issue by rggjan** [bitwarden/browser#530]
On firefox, I usually set bitwarden to lock after 15 minutes. When unlocking it, I usually:

1. Click the bitwarden icon
1. The popup appears with a white text field
1. I start entering the master password
1. after about one second, the text field turns gray
1. I notice that the text field is not ready for entering text when the field is white, and only the last few characters of my password are actually entered
1. I have to delete the password and enter it again

Why does it take a second for the text field to turn gray? Is this intentional, or a technical issue? It is quite annoying, and I cannot imagine why it should take a second to make the field writable...

**Comment by rggjan** [comment]
Sure, see a screencast of the behaviour attached: [Delay.mov.zip](https://github.com/bitwarden/browser/files/1763142/Delay.mov.zip)

Immediately after clicking the icon I start typing. Once the popup with the white textbox appears, it takes another half a second at least until the box turns gray and I my typed letters appear.

This is on Firefox on Mac OS X High Sierra.

**Comment by kspearrin** [comment]
I am not really seeing any significant delay in your video. Maybe a few hundred milliseconds involved here, but that is to be expected when loading the extension interface.

**Comment by rggjan** [comment]
The delay for loading the popup is totally fine, but I always type at least three letters until the bar turns gray. Do you think there is no way to have the bar gray from the beginning?

**Comment by mkuhring** [comment]
Not sure if this is related or if I should open a new issue. But when I click on the icon, I always have to click into the password field before I can enter my password. There is no auto-focus or similar. Is this expected behaviour? It's not a big bug but rather inconvenient.

**Comment by kspearrin** [comment]
Can you see if this is improved in the newly release 1.26? There were significant changes made to try and increase performance throughout the UI.

**Comment by rggjan** [comment]
> Can you see if this is improved in the newly release 1.26? There were significant changes made to try and increase performance throughout the UI.

Yes, the delay is completely gone! Thanks a lot, this is awesome 👍
