### ISSUE TITLE
Page Load Auto-Fill Strict Mode

### ISSUE THREAD

**Issue by TiZ-EX1** [bitwarden/browser#535]
Hi there. I messed up something today due to using an experimental feature. I currently have page load auto-fill active, and with it, I have the same functionality I had with LastPass on a fully FOSS stack. Score!

Unfortunately though, I have to manage some users for a piece of web software we use at work, and I am able to set their passwords. The browser extension detects the user edit page as a login form and drops my own password into the password change fields. I've goofed up on this once before, and again only caught my mistake halfway through what I was doing. I'm trying to work with upstream on that website to get the password changes reverted. If all else fails, I can reset the ones I broke and tell the users, and it won't be that big of a deal. Still, partially my bad for not noticing.

And yet I still feel the extension definitely should not have been doing that. The vault item in question has a *very specific URL* set as the website. I have other vault entries that I definitely want to apply to an entire domain, but not this one. My intuition tells me that if I want it to apply auto-fill to only one page, that's how I'd do it, but instead it applies to any page in that domain despite having specified a very specific page.

Is there something we can do or add to enforce that page load auto fill should only apply to the exact page specified in the vault entry?

**Comment by kspearrin** [comment]
Not now, but next release with more URI rules (see https://github.com/bitwarden/browser/issues/77) you can.

**Comment by TiZ-EX1** [comment]
Ooh, that's good stuff. Thanks kindly! <3
