### ISSUE TITLE
Edge - GitHub Credentials not recognized and saved

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/browser#538]
I logged into GitHub by typing my username and my password manually.
The Bitwarden browser extension is not asking me if the credentials should be stored.

**Comment by kspearrin** [comment]
This is due to a bug in Edge with Content Security Policy enforced website and extension content scripts. There isn't anything we can do to fix it unfortunately.

**Comment by kumarharsh** [comment]
See #509
