### ISSUE TITLE
Firefox - Overlapping Text in German UI

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/browser#539]
When I start Firefox and press the "Bitwarden" toolbar button to enter my password then I see overlapping text in the German UI of Bitwarden:

![bitwarden_firefox_overlapping_text](https://user-images.githubusercontent.com/8037790/37091041-011dbb36-2207-11e8-91ef-632c5a7a5e67.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/182
