### ISSUE TITLE
Microsoft edge: error by fetch

### ISSUE THREAD

**Issue by Tendu86** [bitwarden/browser#542]
when i connect to my self hostet Server i became a fetch error.
on Google Chrome it works fine with the self Settings / url

**Comment by kspearrin** [comment]
Are you using a self-signed certificate?

**Comment by Tendu86** [comment]
the certificate is signed by let's encrypt.
The certificate will managed by synology-cert manager. Then copying and rename the files by script to bitwarden.

**Comment by kspearrin** [comment]
What is your instance's domain name? You can email it to me at info _at_ bitwarden.com

**Comment by kspearrin** [comment]
Seems to work fine for me when I tried your domain. Enter this in server URL config for extension

`https://YOURDOMAIN.SUB.net:444`

**Comment by Tendu86** [comment]
Thanks. Yes, in chrome browser it works fine but in microsoft edge not. I will test it on other computer with windows 10 and edge.

**Comment by kspearrin** [comment]
I tested on edge. Make sure your edge and w10 are on latest.

**Comment by eliykat** [comment]
Hi @Tendu86, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
