### ISSUE TITLE
Hotkey(s) on Mac OS 10.13.3 not working

### ISSUE THREAD

**Issue by torstenb** [bitwarden/browser#543]
I am using bitwarden in Safari 11.0.3 (13604.5.6) and Chrome 65.0.3325.146 (Official Build) and in neither do the hot keys Cmd+Shit+L or Cmd+/ work.

**Comment by kspearrin** [comment]
In chrome, go to `chrome://extensions` scroll down to your keyboard shortcuts for extensions there. Is Bitwarden bound to something? Sounds like your system may be squatting on these shortcuts already.

**Comment by torstenb** [comment]
It indeed wasn’t. Same on my other Mac. Is that standard behavior to have to select a short-cut upon installation in Google Chrome on Mac?

**Comment by kspearrin** [comment]
No. Chrome auto-disabeld it for some reason.

**Comment by torstenb** [comment]
In Mac OS 10.13 in System Preferences I noticed that in the Shortcuts settings for Services, there is an entry for Cmd+Shift+L for ‘Search With Google’ under Searching. Could that have something to do with it?

**Comment by kspearrin** [comment]
Most likely. Do you know what is setting that shortcut?

**Comment by torstenb** [comment]
I do not. It is a relatively new install of High Sierra on both my Macs. The shortcut is not listed on Apple's support page for [Mac keyboard shortcuts](https://support.apple.com/en-us/HT201236), so it may not come with the default install.

**Comment by TylerBarnes** [comment]
In the latest chrome there doesn't seem to be a setting to configure hotkeys. Whats the hotkey for generating a password?
