### ISSUE TITLE
Does not prompt for save for TSP.GOV with Firefox Add-On

### ISSUE THREAD

**Issue by scottbetza** [bitwarden/browser#545]
Does not prompt for save for TSP.GOV with Firefox Add-On

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
