### ISSUE TITLE
Syncing Failed

### ISSUE THREAD

**Issue by chrisls121** [bitwarden/browser#546]
I am receiving a **Syncing Failed** error when attempting to sync using the browser extension in Chrome, it appears to have started after upgrading Bitwarden to 1.17.0. The Desktop App (1.0.5) syncs fine however.

Bitwarden Version: 1.17.0
Chrome Extension Version: 1.24.2
Chrome Version: 65.0.3325.146

The following error is logged when attempting to sync from the browser. (Attached)

[20180311.txt](https://github.com/bitwarden/browser/files/1800077/20180311.txt)

**Comment by kspearrin** [comment]
So the desktop app syncs fine, but the  browser extension doesn’t? That’s weird. What about The web vault? Is it working?

**Comment by chrisls121** [comment]
It appears the web vault is also affected. It is showing all my folders but there are no items in any of them.

I have attached the full error log. (It appears to be the same error in the log when accessing the web vault)

[20180311.txt](https://github.com/bitwarden/browser/files/1800095/20180311.txt)

**Comment by kikaida** [comment]
Having the same issue as chrisls121. 

[20180311.txt](https://github.com/bitwarden/browser/files/1800096/20180311.txt)

**Comment by kspearrin** [comment]
Ok, I think I know where the problem is happening. I've put a stop to the updates for now.

We will have to put a fix together for this which might take a day or so. Stand by.

**Comment by kspearrin** [comment]
@kikaida are you able to use the desktop app like @chrisls121 said he could?

**Comment by kspearrin** [comment]
It you can't wait a day or so you will need to restore one of the nightly mssql backups and then revert your ./bitwarden.sh to 1.16.0 and 1.23.0 and run the `update` command again.

**Comment by kikaida** [comment]
@kspearrin the desktop app is stuck on "Loading..." for me.

**Comment by chrisls121** [comment]
Will do, thanks for the update, looking forward to the fix :)

**Comment by kspearrin** [comment]
Ok guys, we will fix this officially by tomorrow, but you can fix it manually now doing the following:

1. Bash into the mssql container (see: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker#connect-to-sql-server)

  - `sudo docker exec -it bitwarden-mssql "bash"`
  - `/opt/mssql-tools/bin/sqlcmd -S localhost -U SA`
  - Enter your sa password (found in `./bwdata/env/mssql.override.env`)

2. Switch to vault database: 
  - `use vault`
  - `go`

3. Verify problem

  - `select count(1) from cipher where left(json_value(data, '$.Uris'), 8) = '[{"Uri":'`
  - `go`

If this returns more than 0, you have the issue we are trying to fix

4. Fix problem

  - `update cipher set data = json_modify(data, '$.Uris', json_query(json_value(data, '$.Uris'), '$')) where left(json_value(data, '$.Uris'), 8) = '[{"Uri":'`
  - `go`

5. Now, load your web vault. It should be working.

**Comment by chrisls121** [comment]
Thank you, both the browser and web vault are working again after running above fix. :)

**Comment by kspearrin** [comment]
1.17.1 is out with the full fix
