### ISSUE TITLE
Text does not display in microsoft edge extension

### ISSUE THREAD

**Issue by lacrosse1991** [bitwarden/browser#549]
Text does not display in some sections of the microsoft edge extension.

Some text, such as the names of my folders and site names will display, but everything else just does not show up. The functionality of the app appears to be working fine, it's just the text display portion that is not working.
![untitled](https://user-images.githubusercontent.com/2328730/37348442-71cc4a1c-26aa-11e8-8b51-b153c19b6ee6.png)

OS: Windows 10 Enterprise
OS Version: 10.0.14393 Build 14393
Edge Version: Microsoft Edge 38.14393.2068.0
EdgeHtml: Microsoft EdgeHTML 14.14393

**Comment by kspearrin** [comment]
It seems that the i18n strings never loaded for some reason. What version of Windows 10 and Edge? Does this happen every time?

**Comment by lacrosse1991** [comment]
@kspearrin Hello, I've updated my original post with version details. 
This does happen every time. I tried restarting the browser and reinstalling as well, but still got the same results.

**Comment by kspearrin** [comment]
Your version of edge seems pretty outdated. It’s probably missing some api that we are using. I don’t have a machine to test that on though. Is it possible to update?

**Comment by lacrosse1991** [comment]
@kspearrin Sorry about taking so long to respond, but my machine was finally updated to a more recent version of windows 10 (updates are controlled by the company I work for) and everything is working correctly now! Thanks for your help with this.
