### ISSUE TITLE
Continued support for Firefox 48 (version)

### ISSUE THREAD

**Issue by gitgiggity** [bitwarden/browser#550]
Could you provide continued support for Firefox 48?

I am currently using version 1.20.1, because the UI shows a blank for any version above this.

I am limited to Firefox 48, because anything more will break my favourite add-ons, namely Scrapbook Plus, and All-in-One Sidebar.

**Comment by kspearrin** [comment]
Using outdated, unsupported versions of a web browser is a very bad idea. You're potentially opening yourself up to tons of vulnerabilities on the web. We don't have any intentions on supported browser versions that are unsupported by the vendors themselves.
