### ISSUE TITLE
No images in Firefox 55 with version 1.24.2

### ISSUE THREAD

**Issue by SylwesterZarebski** [bitwarden/browser#551]
Few hours ago addon has been updated to version 1.24.2 (date 2018-03-13), but something goes wrong, because this version show some codes instead of images:
![bitwarden_no_images](https://user-images.githubusercontent.com/1755531/37364264-501386d8-26fa-11e8-981a-b45e51a72418.png)

~~If this is intentional because this addon version is unsupported on previous Firefox versions, you should not mark it as compatible with Firefox 42 or greater and then 1.24.2 should be removed from AMO and replaced with version without >=42 compatibility.~~

**Comment by Thdub** [comment]
I was submiting at the same time! having the same issuse since 1.24.2
Icon display is corrupted, both in Firefox  59.0 and Waterfox 56.0.4.1 
appearing numbers inside a square instead... 

![1](https://user-images.githubusercontent.com/37347541/37364312-6daed724-26fa-11e8-9388-c3b70313aa74.JPG)

**Comment by kspearrin** [comment]
Fixed.
