### ISSUE TITLE
not syncing with chrome extension

### ISSUE THREAD

**Issue by 7h3ju57** [bitwarden/browser#560]
Looks like when using chrome extension bitwarden no longer syncs and previously synced password are not detected. If i had to guess i'd say this has started in the last week or so.

Self hosted version of bitwarden (proper ssl cert), tested from two systems, works fine using firefox so far.

![image](https://user-images.githubusercontent.com/2500972/37628388-a8605a14-2baf-11e8-8194-bf3586ffde14.png)

**Comment by kspearrin** [comment]
update your self hosted server. it is out of date.
