### ISSUE TITLE
[1.25.2] All URIs gone from vault in Chrome extension

### ISSUE THREAD

**Issue by txtsd** [bitwarden/browser#561]
Every single entry has the URI missing, and creating a new entry creates a custom URI instead of the default one. So no entries are being matched against any website that is pulled up in the browser.
The desktop client still displays as it's supposed to.

Did something change?

**Comment by txtsd** [comment]
It's supposed to look like this
![Screenshot](https://i.imgur.com/1a3CGlC.png)

The URI field moving to the next section along with being able to add multiple URI is the new feature, I believe. Although my URIs have just vanished from the browser extension, seeing as how these launch links are just greyed out:

![Screenshot](https://i.imgur.com/TklS9S7.png)

**Comment by touch444719** [comment]
I have the same issue, all the URL field are gone from the Chrome addon.
The "auto fill" option is broken now, the addon is unusable. Please fix !

**Comment by kspearrin** [comment]
Try syncing?

**Comment by touch444719** [comment]
The sync did the trick. Thank you.

**Comment by kspearrin** [comment]
Weird that it didn't auto-sync after updating though.

**Comment by txtsd** [comment]
Please reopen this issue.
I tried syncing, but it just says Syncing Failed on a red bar.
I signed out and back in to my chrome profile, and re-logged in to Bitwarden, but it still fails to sync.
What do?

**Comment by txtsd** [comment]
Nevermind. I had to delete my Chrome profile and start over. It works now.
