### ISSUE TITLE
Firefox MacOS: No matching logins

### ISSUE THREAD

**Issue by feld** [bitwarden/browser#562]
Suddenly on Firefox Bitwarden cannot match any website to autofill logins

MacOS 10.13.4 Beta (17E182a)
Firefox 59.0.1 (64-bit)
Bitwarden: Version 1.25.2

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/561

**Comment by feld** [comment]
Just want to clarify that this was not due to "didn't sync after update" and instead is because I'm running the unsupported bitwarden-ruby implementation of the server and there were API changes.

**Comment by kspearrin** [comment]
Thanks for letting us know.
