### ISSUE TITLE
Is this line correct in utils.service.spec.ts?

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#563]
In reviewing some of the code, I came across this line:

https://github.com/bitwarden/browser/blob/f51bebd99a21779eb315066d16f26e60640195c4/src/services/utils.service.spec.ts#L9

Is this line correct, or is an error present?  Can you briefly explain the function of it?

**Comment by kspearrin** [comment]
Yes, since that is not a valid domain name, we return null.

**Comment by setyb** [comment]
Got it.  Thanks.
