### ISSUE TITLE
Can no longer save logins

### ISSUE THREAD

**Issue by scttnlsn** [bitwarden/browser#564]
Firefox on Linux

* Clicking "Yes, save this login" does nothing
* When I manually try saving a login I see a red error alert saying: "Errors have occurred.  data is undefined"

**Comment by kspearrin** [comment]
Using self hosted?

**Comment by scttnlsn** [comment]
I self-host the backend, yes.  Does that impact saving a login locally?  What if I'm offline?

**Comment by scttnlsn** [comment]
Yeah, that did the trick.  Thanks for your help!
