### ISSUE TITLE
release note for Firefox are not updated

### ISSUE THREAD

**Issue by heubergen** [bitwarden/browser#568]
I think that in the update process it was forgotten to update the release note of the Firefox extensions.
<img width="518" alt="screen shot 2018-03-24 at 9 45 59 pm" src="https://user-images.githubusercontent.com/5529410/37871210-7316d498-2fae-11e8-9417-c46b1b821ee2.png">
A [look](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/) into the previous versions confirms my suspicion.

**Comment by kspearrin** [comment]
We only update the release notes for major and minor releases. Patch releases are just big fixes.

**Comment by heubergen** [comment]
The current information is just misleading and false. As a advanced user (and those are probably the only one that cares about it anyway) I would think that the same release would be re-released over and over again because the release note those not change.
Especially with your open source policy (which I really appreciate), I think the user should be informed here more transparently.

A good example in this case is probably Momentum (https://addons.mozilla.org/en-US/firefox/addon/momentumdash/versions/).

If you really don't want to change the release note anytime, please consider at least to write something generalistic like: _Bug fixes and performance improvements_

**Comment by kspearrin** [comment]
The reasoning here is that we want to make sure people that update to the latest always see the new features included in the release notes. They could still be coming from older versions. Some platforms don't show release notes history, but Firefox does so I suppose we can provide valid notes each time. Or, we can prefix the features list with the actual release notes. Thanks for the feedback.

**Comment by heubergen** [comment]
@kspearrin just saw the changes, love it!
