### ISSUE TITLE
Logging in to Safari plugin doesn't get past Duo browser tab

### ISSUE THREAD

**Issue by jrothlis** [bitwarden/browser#569]
High Sierra 10.13.3, Safari 11.0.3, BitWarden plugin 1.24.1

When trying to authenticate to the Safari plugin for the first time (either a fresh install, or the plugin is updated), after entering my username and password, a new browser tab opens saying something like "please wait" or "loading" (can't remember exactly) but the Duo website never loads. I am able to "choose another method" and use my authenticator, so no problem getting in, but is it a bug or something specific about my computers (has happened on my Mac mini and my MacBook adorable)?

I use 1Blocker, and just to test, I white-listed the Duo.com website, but this didn't help.

Thanks!

--John

**Comment by kspearrin** [comment]
you probably need to whitelist duosecurity.com

**Comment by jrothlis** [comment]
Tried that, no improvement. I also disabled 1Blocker completely (in Safari preferences), no improvement. The tab is titled "Two-step Login", the URL field is blank, and the web page shows "Loading..."

**Comment by labor4** [comment]
my Safari console says
`Error: Duo Web SDK error: No API hostname is given for Duo to use.  Be sure to pass a "host" parameter to Duo.init, or through the "data-host" attribute on the iframe element.`

**Comment by jrothlis** [comment]
@labor4 good to know someone else has the issue (not just me)...

**Comment by kspearrin** [comment]
@labor4 Does your self hosted server have a Duo AKey set the in env file? @jrothlis  Are you also on a self hosted server?

**Comment by labor4** [comment]
yes it has, but I guess it was generated.
(Brave works, if that matters)

**Comment by jrothlis** [comment]
No, not self hosted. I haven't had a chance to look at Safari console though (I didn't even think to look).

**Comment by Petahh** [comment]
I have exactly the same problem. For me after several attempts DUO page loads but in new tab. When I start interacting with it Bitwarden extension is suppressed to background and whole sign up is canceled. 

Was able to get pass this with a workaround of Requesting push authentication, not approving it just yet but after entering username/password and getting new duo authentication popup, then hit on mobile approve. 

This is a bug, duo should load directly in the extension pop-up, instead it loads in separate browser tab which is wrong. Procedure is described in: https://help.bitwarden.com/article/setup-two-step-login-duo/ where you can also see duo in extension tab.

![](https://help.bitwarden.com/images/two-step/duo/browser.png)

**Comment by Petahh** [comment]
> @Petahh Duo opening in a new window is the expected functionality on Safari. This is because Safari extensions do not support injecting the Duo iframe into the popup window like other browsers do.
> 
> After you complete the Duo prompt, the Duo window should close and your popup window should continue with logging in to your vault.

Thanks for clarifying. Appreciated.

**Comment by kspearrin** [comment]
Should be fixed in latest safari extension.
