### ISSUE TITLE
Disable breach detection for passwords

### ISSUE THREAD

**Issue by BirknerAlex** [bitwarden/browser#571]
Hello,

I've seen the browser extension has now a option to check for data breaches. It has been requested in this issue #523.

Is there any way to completely disable this feature? I can't find any option yet. I've clicked accidentally on the button a few times yet but for me I don't want to send my passwords to external services even if it's correctly hashed.

Thank you in advance.

**Comment by Crocmagnon** [comment]
Your password __isn't sent__ to an external service. This feature is implemented as follow :
-  Hash the password
- Send the first few characters of the hash to the service
- The service returns all hashes that matches your first characters
- The extension _locally_ search for your full password hash in the list returned
- If matched, then there is _a strong probability_ your password has been leaked

By the way, for this kind of feature request you want to go to https://community.bitwarden.com/ 🙂

**Comment by BirknerAlex** [comment]
Thanks @Crocmagnon for explanation. That solution sounds good for me, feeling now more safe. :+1:
