### ISSUE TITLE
[Vivaldi-Extension] popup size is wrong

### ISSUE THREAD

**Issue by benoitjadinon** [bitwarden/browser#573]
## repro
I installed the extension on Vivaldi 1.15.1137.3 (Official Build) (64-bit) (OSX) and the popup size is too small, probably Vivaldi related, cause it seems to work in Chrome
![new_issue_ _bitwarden_browser](https://user-images.githubusercontent.com/205116/38193754-edaa0d1c-3673-11e8-8fe5-fbb5c2f25643.png)

## quick workaround
I've added the extension url ( chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#!/environment ) as a side web-panel

**Comment by kspearrin** [comment]
Have you tried contacting the Vivaldi folks? This seems specific to their browser. I have not seen this happen on Windows 10 (using Vivaldi right now).

**Comment by benoitjadinon** [comment]
it seems to open correctly (except that it's cropped) today, but I think there was a Vivaldi update. thx
