### ISSUE TITLE
Chrome Extension : Sync vault failed

### ISSUE THREAD

**Issue by ThibautMarechal** [bitwarden/browser#578]
Since one or two week, i can't synchronize my account with the server (self-hosted) from the chrome extension (Works on Safari). All i see is an alert "Syncing failed" and this error in the console.
If you have anothers questions feel free to ask.

![bw_bug_chrome](https://user-images.githubusercontent.com/20936586/38305775-64d61976-380e-11e8-81d8-1a99ddb159d8.PNG)

**Comment by kspearrin** [comment]
update your server
