### ISSUE TITLE
Copying the TOTP code to clipboard doesn't work on Synology NAS interface

### ISSUE THREAD

**Issue by jlnostr** [bitwarden/browser#579]
When I'm logging in onto my NAS interface (DS216j by Synology, latest firmware) and pressing `Ctrl+Shift+L` to fill in the credentials, the TOTP code isn't copied after a successful login. The TOTP field is filled out correctly and the code works if I manually copy it.

On other pages, e.g. GitHub this is working fine.

Is there a place of logs or something like that, which might help solving the problem?

**Comment by kspearrin** [comment]
What browser?

**Comment by jlnostr** [comment]
Firefox 59.0.2.

**Comment by kspearrin** [comment]
TOTP copying does not work on Firefox unless you use the popup to autofill.

**Comment by jlnostr** [comment]
Oh well, that's true. It's specific to Firefox, right?

**Comment by kspearrin** [comment]
Yes.
