### ISSUE TITLE
Firefox plugin login popup disappear

### ISSUE THREAD

**Issue by scifire91** [bitwarden/browser#580]
Hey,
We have a wired issue with Firefox 59 an Ubuntu 18.04 (Beta).
In this version the Bitwarden plugin popup disappear in that moment when i try to type my master password in. 

Firefox: 59.01
Distri: Ubuntu 18.04 Bionic Beaver with latest daily updates
with older Ubuntu versions this problem is not present only with 18.04

If i can give you more information let me know.

Thanks,

//cc: @mfuhrmann

**Comment by kspearrin** [comment]
Seems related: https://github.com/bitwarden/browser/issues/96

**Comment by scifire91** [comment]
yes it look like. But i have a fresh clean system without any other extensions. Also on the same system chrome is working fine.

**Comment by DominoTree** [comment]
Also seeing this on Ubuntu 18.04 with FF 59.01 with no other plugins loaded.

**Comment by jdtanner** [comment]
I'm seeing the same problem here with Firefox 59.0.1 and Beta 2 of Ubuntu (Gnome) 18.04. Extension allows email address to be completed, but as soon as you try and type a password the extension window disappears.

**Comment by jdtanner** [comment]
Also present in Firefox 59.0.2

**Comment by kspearrin** [comment]
Can someone that is experiencing this problem open a bug report with Mozilla and link it here? I don't have a device that can reproduce it.

**Comment by DominoTree** [comment]
Looks like this bug is related - I'm seeing the same behavior using *any* addon that has a popup with a password field.

https://bugzilla.mozilla.org/show_bug.cgi?id=1405634

**Comment by DominoTree** [comment]
Just confirmed that switching to Wayland from default X11 seems to solve the issue as reported in the Mozilla thread.

**Comment by kspearrin** [comment]
Closing since this is a Firefox bug.

**Comment by favadi** [comment]
If anyone is looking for a workaround, the bug is in ibus-gtk3 package of Ubuntu, not Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1405634#c16.

**Comment by jaywick** [comment]
I'd like to point out a workaround could be to use the sidebar with `Shift + Alt + U`

**Comment by MichaelDemeyer** [comment]
Another workaround for peoples using Latin languages on Ubuntu :
Settings -> Region and language -> Manage Installed languages -> Switch "Keyboard input method system" to "XIM" or "None"

**Comment by berkes** [comment]
@MichaelDemeyer might work for you, but it can open an issue on ubuntu where all native text-areas become unreadable. More information on the metamask thread for this exact same issue: https://github.com/MetaMask/metamask-extension/issues/3313#issuecomment-418677844

**Comment by tmihai20** [comment]
I had this issue after upgrading to 1804. I was using X11, not Wayland and I still had this issue. Immediately after installing 1804 there were no proprietary drivers available (at least for the graphic card). I just installed today the Nvidia proprietary drivers and the issue is gone. I can use the extension in Firefox for Linux again, as before.

**Comment by plembo** [comment]
Still happening on Ubuntu 18.04 LTS with the distro's build of Firefox 63. Many thanks to those here who provided workarounds!

**Comment by berkes** [comment]
The patch has landed in gnome-shell, and is fixed there. Ubuntu has not yet backported as of writing. The bug for ubuntu is here: https://bugs.launchpad.net/firefox/+bug/1794655

**Comment by jeffshee** [comment]
Hi! I'm experiencing the same bug on Fedora 29 as well. I thought this is Ubuntu specific problem, am I wrong?

ibus-gtk3-1.5.19-16.fc29.x86_64

**Comment by tmihai20** [comment]
This is most likely an X11/Wayland issue, this is why it would happen on other distros. I am not seeing it anymore, but I do not know if Ubuntu fixed the issue in gnome-shell or because of the workarounds I tried. I think I received some updates on my 18.04 to gnome and its components/plugins.

**Comment by jeffshee** [comment]
Hmm, so I have to wait until the fix reach Fedora? But the fix was there 2 months ago already right? Should I report to Fedora or...?

(or can we have an option to show UI at sidebar when clicked on the extension icon? `Shift+Alt+U` works fine but I might forget it someday later..)

**Comment by Omar-Elrefaei** [comment]
In Firefox making sure `apz.popups.enabled = true` in `about:config` fixed it for me.
Strangely, this flag only affects bitwarden, other extensions work fine with it disabled.
