### ISSUE TITLE
firefox: bitwarden doesn't work with an API-endpoint needing a client-certificate

### ISSUE THREAD

**Issue by yxzzx** [bitwarden/browser#581]
With chrome I can connect to my client certificate protected bitwarden server. With firefox I can't.
It looks like fetch requests on firefox need an additional argument:
see https://stackoverflow.com/questions/39417232/fetch-fails-in-firefox-with-ssl-client-authentication

fetch(someUrl, { credentials: 'include' })

**Comment by kspearrin** [comment]
This was fixed a few versions ago.
