### ISSUE TITLE
Context menu Firefox 59 Win 10 missing "Copy Username", "Copy Password", "Generate Password"

### ISSUE THREAD

**Issue by leekelo** [bitwarden/browser#582]
The context menu on Firefox 59.0.2 64-bit for Windows 10 is missing the option for "Copy Username",  "Copy Password" and "Generate Password".  I also notice this does not work on Microsoft Edge. Works perfect on Chrome.

![2018-04-06](https://user-images.githubusercontent.com/7585823/38447501-7fc742d2-39b2-11e8-99ed-e9ca66a8b377.png)
.

I have removed the add-on, cleared caches, reinstalled, same result.

Thank you,
Kelly

**Comment by kspearrin** [comment]
These are hidden on Firefox because there are no apis available to access the clipbaord outside of the pop up window.

**Comment by leekelo** [comment]
Thank you! I appreciate the fast response.

**Comment by Crocmagnon** [comment]
@kspearrin, what about this : https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard ?

**Comment by kspearrin** [comment]
@Crocmagnon As the page states:

> You can write to the clipboard like this in all execution contexts except background pages. In Firefox you can't select text or focus an input field in background pages, so you can't write to the clipboard from a background page.

The background page is how we write to clipboard from other contexts outside of the popup window.
