### ISSUE TITLE
Chrome crashes when adding a card through the extension

### ISSUE THREAD

**Issue by rhnonose** [bitwarden/browser#585]
OS: macOS High Sierra `10.13.1`
Chrome version: `65.0.3325.181 (Official Build) (64-bit)`
Extension version: `1.25.5`

When adding a new card through the extension, the browse crashes instantly.

Fields filled: name, cardholder name, number, brand, expiration date and security code
Tried multiple times with the same data, happens consistently.

**Comment by kspearrin** [comment]
Not able to reproduce. Is this still an issue?

**Comment by rhnonose** [comment]
Can't reproduce anymore.
