### ISSUE TITLE
Brave Extension Fails To Sync

### ISSUE THREAD

**Issue by 9-5** [bitwarden/browser#586]
After quite a bit of observation, Bitwarden's extension for the Brave browser appears to have issues syncing currently existing account information from the vault. I've reinstalled both the extension and the browser to no avail. Anyone else have any ideas?

_Something interesting, however, is that if a new login is created via the extension, it appears within the web vault._

**Comment by kspearrin** [comment]
Are you using the "site isolation" feature in Brave?

See https://community.brave.com/t/bitwarden-not-working/18195
