### ISSUE TITLE
Autofill cuts password at tmdb.org

### ISSUE THREAD

**Issue by heubergen** [bitwarden/browser#589]
Bitwarden cuts the password when you try to fill in the password and username at tmdb.org after 28 characters.
URL: https://www.themoviedb.org/login

**Comment by kspearrin** [comment]
I don't seem to have any issue in the latest dev version:

![image](https://user-images.githubusercontent.com/1190944/38880359-80498ccc-4233-11e8-8441-e51bb426521c.png)

**Comment by heubergen** [comment]
Sorry false alarm; this login came as an import from 1Password6 and I just had to delete some obsolete forms in the login...
