### ISSUE TITLE
v1.26.0 on Firefox (Ubuntu 16.04): Copy buttons not working

### ISSUE THREAD

**Issue by begincalendar** [bitwarden/browser#599]
* OS: Ubuntu 16.04
* Browser: Firefox 59.0.2
* Add-on: 1.26.0

Received the updated version of the browser extension this morning and noticed that the copy buttons no longer work (i.e. the data does not end up in the clipboard).

The issue does not occur in Chrome.

I tried debugging the add-on and looking for error messages in the console (when clicking a copy button), but none appeared.

Is there anything else I can do to try and provide more information?

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/596
