### ISSUE TITLE
TOTP not automatically copying - Safari

### ISSUE THREAD

**Issue by jmauss** [bitwarden/browser#602]
Using Safari, I am not sure if this is how it is supposed to work or not but the TOTP code does not automatically copy to the clipboard after autofilling on a web page. Any help?

**Comment by kspearrin** [comment]
What method are you using to autofill?

**Comment by jmauss** [comment]
Simply clicking on the appropriate login in the Bitwarden extension window.

**Comment by kspearrin** [comment]
Fixed for Safari in next version.
