### ISSUE TITLE
Cannot log into firefox browser extension in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cmbrownfield** [bitwarden/browser#608]
Just installed Ubuntu 18.04 LTS (Bionic Beaver).  It is fully patched.  The installed Firefox is 59.0.2 (64-bit).  The extension installs, but I cannot log into it.  I can type my email address, but moving to the "master password" field always closes the extension window (I've tried clicking and tabbing).  For what it's worth, bitwarden works fine on Chrome on the same computer.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/580
