### ISSUE TITLE
Master password remembered by autocompletion in clear text when visibility is on

### ISSUE THREAD

**Issue by mkuhring** [bitwarden/browser#609]
With the Firefox Add-on, when I enter my master password and turn visibility on (via the eye icon), the password seems to be saved by some autocompletion functionallity (Firefox?). So next time I enter the password with visibility on, it actually offers me my password in clear text!

Edit: So basically everything I enter into the password field and submit is saved, correct password or not. I think the (visible) password field should certainly not make use of any autocompletion functionallity.

**Comment by kspearrin** [comment]
This is fixed in next version.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/commit/73013d51e07f13980f992df59e30b66698ee3f01

https://github.com/bitwarden/jslib/commit/df1649bac151ccb7a00244a3633f5ba3adf178a8

**Comment by kspearrin** [comment]
Any version greater than 1.26.3 will contain the fix

**Comment by kspearrin** [comment]
1.26.4 is now rolling out with this fix
