### ISSUE TITLE
"Unable to auto-fill" when multiple browser windows open. Firefox.

### ISSUE THREAD

**Issue by hheexx** [bitwarden/browser#610]
When I have more then 1 firefox window open I get "Unable to auto-fill..." error.
Not site related. For all sites.

Firefox 60.

**Comment by eliykat** [comment]
Hi @hheexx, are you still experiencing this issue with the latest Firefox and Bitwarden? If so, can you please confirm exact Firefox and Bitwarden versions, plus what operating system you're using?

**Comment by hheexx** [comment]
Looks like its fixed....
