### ISSUE TITLE
Does not open on Google Login Pages

### ISSUE THREAD

**Issue by danielmyasnikov** [bitwarden/browser#611]
Thank you for a great open source project and your support. However the browser extensions struggles to open on Google Login Page :(

Much appreciate if you can fix it, thank you.

Version of the extension: 1.26.3

**Comment by kspearrin** [comment]
> the browser extensions struggles to open on Google Login Page

Sorry but I have no idea what that means. Could you be more specific please?

**Comment by danielmyasnikov** [comment]
Browser: Chrome Version 66.0.3359.139
OS: MacOS Sierra 10.12.6
Bitwarden version: 1.26.3

@kspearrin , so to reproduce, use Chrome to go to http://accounts.google.com/ page and click bitwarden extension

*Desired result*:
Bitwarden extension opens.

*Current result*
Bitwarden extension does not open.

Let me know if you still have question

**Comment by kspearrin** [comment]
Sounds like you are suffering from this chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c44
