### ISSUE TITLE
Firefox 59: Bitwarden unlock screen saves password in form history when "show password" active

### ISSUE THREAD

**Issue by Zoopa** [bitwarden/browser#614]
When unlocking BitWarden while "show password" is active, the password is stored in Firefox's form history. If that's something the extension can prevent, it should prevent it.

Steps to reproduce:
* Lock BitWarden
* On the unlock screen, click the eye icon
* Type in any text and submit
* Firefox will suggest that string next time you try to unlock BitWarden (and set "show password")

**Comment by tcoenraad** [comment]
I was just looking if this reported before. Should not be to hard to fix, see https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion for instructions.

Thank you for your amazing work!

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/609
