### ISSUE TITLE
Can't unlock vault from Firefox Toolbar

### ISSUE THREAD

**Issue by MichaelDemeyer** [bitwarden/browser#615]
After upgrading from Ubuntu 16.04 to 18.04, the "Verify Master Password" prompt do not display correctly when invoked from button toolbar. Is displayed for half second then closed. It still work correctly from sidebar.

Uninstall and reinstall the add-on make it work for a couple of times, but the bug eventually reappear. 

Firefox 59.0.2 64-bits.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/580
