### ISSUE TITLE
Cannot edit password in Firefox

### ISSUE THREAD

**Issue by SheamusPatt** [bitwarden/browser#616]
Bitwarden seems to have a bug in that the Edit dialog for an entry does not allow the password to be changed. Using the eyeball I can view it, but CTRL-V just closes the dialog, and I cannot get a right-click context menu to appear at all. Since it doesn’t always pick up a password change, this is a SERIOUS PROBLEM.

Fortunately, it seems to be Firefox specific. I was able to update the entry for a site I use often by bringing it up in the Chrome extension, and editing it there.

Browser details: Firefox ESR 52.6.0 (64-bit) on AMD 64 Linux.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/580 ?

**Comment by favadi** [comment]
I'm not sure but it is a high chance it is the same Firefox bug reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1405634. One thing I don't know how to explain is the popup works fine after the vault is unlocked, but will disappear after a second if it is locked.

**Comment by SheamusPatt** [comment]
I concur. I tried the workaround suggested for bug [#580](https://github.com/bitwarden/browser/issues/580), to run on Wayland, and the problem is gone. In fact I noticed that it's not just CTRL-V but simply depressing the CTRL key that closes the dialog.
