### ISSUE TITLE
Chrome Browser Extension issues at HighDPI in windows 10

### ISSUE THREAD

**Issue by hiramknick** [bitwarden/browser#617]
When using High DPI (4K) Monitors on Windows 10 the extension becomes unusable.  none of the buttons inside of the Extension are not clickable when the DPI setting in Windows 10 >100%.

**Comment by kspearrin** [comment]
Does this fix it? https://github.com/bitwarden/browser/issues/184

**Comment by hiramknick** [comment]
@kspearrin this does resolve it.  Thanks!
