### ISSUE TITLE
Firefox Extension Consumes Memory and Firefox Becomes Unresponsive

### ISSUE THREAD

**Issue by Shadow00Caster** [bitwarden/browser#618]
Latest version of FF, latest version of on-premise BW (docker), latest version of BW FF extension, Win10.

Recently I noticed upon launching FF, I could not navigate to any sites, none of my extensions would respond and there was one Firefox.exe pid consuming 500Mb+ of memory which is uncommon.  After some trial and error, I figured out it was the BW extension and can replicate it 100%.

This never happened before so not sure if this is something new or not, is there any log information that I can provide?

**Comment by kspearrin** [comment]
Try reverting to 1.26.3 and see if the problem goes away. We made a change in 1.26.4 that I suspect is the problem and we have a fix coming out soon.

**Comment by Shadow00Caster** [comment]
Looks like that did it, I disabled updates on the addon for now.  ETA on fix?

**Comment by kspearrin** [comment]
Likely tomorrow or Tuesday

**Comment by kspearrin** [comment]
Can you try 1.25.5 and let me know? It is now live for Firefox.

**Comment by Shadow00Caster** [comment]
I assume you meant 1.26.5, negative, same symptoms.

**Comment by Shadow00Caster** [comment]
Sure thing, just lmk when and where.

**Comment by kspearrin** [comment]
You can swing by the dev chatroom at https://gitter.im/bitwarden/Lobby and ping me when you have some availability.

**Comment by kspearrin** [comment]
Could you try version 1.26.6 and see if it's any better?

**Comment by Shadow00Caster** [comment]
I updated to what FF saw as latest which was 1.26.5 after FF's update today (60) and it worked normally where previously it had issues.  Maybe the FF update had something in it.  I just forced 1.26.6 from the add-on site as FF still was not seeing it as latest and it still appears to be working.

**Comment by kspearrin** [comment]
Go to the addons page in Firefox and tell it to check for updates.

**Comment by kspearrin** [comment]
Great
