### ISSUE TITLE
[Firefox 60 Linux] Unable to enter password as pop up closes

### ISSUE THREAD

**Issue by scottsweb** [bitwarden/browser#621]
I am unable to enter my master password into the extension as the pop up closes almost as soon as it has been clicked.

Here is what it looks like:

![peek 2018-05-13 14-40](https://user-images.githubusercontent.com/411945/39967970-3dc6f896-56bd-11e8-9ccd-25a9648ab53d.gif)

Seems fine in Chrome.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/580
