### ISSUE TITLE
Using 'Pop out to a new window' stopped respecting auto lock

### ISSUE THREAD

**Issue by IOI-655321** [bitwarden/browser#623]
I was doing something in my browser extension in firefox (v60) 1.26.6 and popped out the window so I didnt lose state when clicking away. I noticed after about 30 mins when I opened another site my bitwarden extension showed active and a matched login.

I checked my lock settings and it was still set to 1 min, then noticed id left the popped out window open and it had remained logged in. Is this expected behaviour or can it be made to respect the auto lock option?

**Comment by kspearrin** [comment]
Hi,
Locking will only occur whenever the popup interface is closed. If you opened it by means of the popup button or by "popping out" to a new window the lock timer will not start until the window is closed.

**Comment by eliykat** [comment]
Same issue as #1334. There is more discussion on that thread, so I'll close this one as the duplicate.
