### ISSUE TITLE
have to press extension multiple times to open

### ISSUE THREAD

**Issue by phynias** [bitwarden/browser#624]
for some reason recently i have to press the extension button 2+ times to have it open. when i press it the first time just a small box shows up.

latest chrome on mac.

<img width="183" alt="screen shot 2018-05-18 at 2 08 46 pm" src="https://user-images.githubusercontent.com/10147213/40258057-261d7210-5aa5-11e8-91f8-0a089ddfb5c9.png">

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
