### ISSUE TITLE
Fails to load on Gmail sometimes

### ISSUE THREAD

**Issue by jcrben** [bitwarden/browser#626]
Fairly often, I'm seeing this on Gmail:
![image](https://user-images.githubusercontent.com/5614134/40524852-caed5be8-5f91-11e8-862b-b745ac5e42d0.png)

Usually it happens when I've tabbed thru a few windows and come back to Gmail.

It doesn't seem to happen so much in other windows - Gmail has more than others, so maybe that affects it?

Can't recall if this is happening on other Google pages.

On a side note, thanks for the great software! I subscribed for a premium membership today - I still have a Lastpass premium account but I'm trying to use it less and less.

**Comment by kspearrin** [comment]
Duplicate #604
