### ISSUE TITLE
[ Feature Request ] Multiple Accounts Simultaneously

### ISSUE THREAD

**Issue by Aetherall** [bitwarden/browser#627]
Hi !
First of all, thanks for your amazing product !
I was looking for a free open source alternative to keeweb, I found it !

Use case :
I work as a freelancer developper, and I create a bitwarden account for each of my clients, so I can provide a secured access to their hosting platforms, registrars, mail providers, etc
Right now, I have to create a new browser profile for each one, so I can use the multiple accounts simultaneously.

I would be great to be able to log in multiple accounts once, and then "switch context" to another account

As for google services

Thanks for your time ! 

A happy user :)

**Comment by Crocmagnon** [comment]
Hi @Aetherall,
This repo is for bug reports. For feature requests, please head to https://community.bitwarden.com/c/feature-requests 🙂

**Comment by Aetherall** [comment]
Sorry !
