### ISSUE TITLE
Chrome extension does not open on login.salesforce.com

### ISSUE THREAD

**Issue by ricka** [bitwarden/browser#628]
MacOS 10.13.4
Chrome: 66.0.3359.181

I'm not sure if this is an issue with this particular domain, the number of logins I have, or what, but I use Bitwarden for Salesforce logins, of which I have many. When trying to open the extension on login.salesforce.com, the extension pops out and immediately pops back to a very small box without any contents ([video here](https://youtu.be/cRKFnlkIJkc))

If there is more debugging I can do somehow, I'm happy to do this to help get this resolved.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
