### ISSUE TITLE
On firefox, bitwarden popup closes immediatley

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/browser#629]
Using Firefox 60.0.1 with Bitwarden extension 1.26.6, when I click on the bitwarden icon that opens the popup, it closes after a second. I can't use it, I have to use the client or Chrome (so, no auto-fill)

I'll be glad to submit any necessary details.

**Comment by ewjoachim** [comment]
Hm, I've managed to log in using the sidebar, and now the popup works, so it seems linked to the vault unlock page.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/580

**Comment by ewjoachim** [comment]
Indeed, sorry for the noise.
