### ISSUE TITLE
Firefox 60 when running on a mixed DPI setup has unreadably small text.

### ISSUE THREAD

**Issue by cooperaj** [bitwarden/browser#632]
I'm running Firefox on a MBP with a retina display and an attached standard DPI monitor. The firefox window, when running on the retina screen looks like:

<img width="460" alt="screenshot 2018-06-01 16 38 28" src="https://user-images.githubusercontent.com/400210/40849784-c5350d02-65ba-11e8-80bd-0ab621781787.png">

The same window, moved to the standard DPI monitor looks like:

![screenshot 2018-06-01 16 38 39](https://user-images.githubusercontent.com/400210/40849812-d525880e-65ba-11e8-9d43-9d4d2c46cede.png)

As you can see the retina version isn't so usable.

**Comment by kspearrin** [comment]
This seems like a Firefox bug. I am not sure what we could do differently. We just specify the font size like any web page, 14px.

**Comment by cooperaj** [comment]
I thought so, so I hunted around for firefox issues first. I was unable to find any :/

Also, none of the other extensions that show UI in that way have the same issue.

**Comment by kspearrin** [comment]
Could you open an issue on Bugzilla to see what the Mozilla folks say? I have no idea how I would go about fixing this on my end.

**Comment by djsmith85** [comment]
Hi @cooperaj , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
