### ISSUE TITLE
browserAction disappears from Firefox

### ISSUE THREAD

**Issue by da2x** [bitwarden/browser#634]
The extension button randomly disappears in Firefox. It happens about once per week after hours of browsing. It happen the first week I started using Bitwarden in February and has kept happening ever since. It has happen on macOS and Linux.

Disabling and re-enabling the extension doesn’t make the button reappear. I can’t connect to the extension from about:debugging, either. I don’t really know what to do to provide good information here as I can’t locate any useful info or logs.

The icon reappears when I restart Firefox.

**Comment by kspearrin** [comment]
I am not sure why that would happen, though it sounds like an issue with Firefox itself rather than the extension. We only tell Firefox to show an image in the toolbar and then they handle everything from there.

**Comment by da2x** [comment]
I agree with you. It’s probably a Firefox issue. However, I’ve never seen it happen with any of my other extensions. I’d file it with Firefox if I’d ever seen it happen to another extension. As far as I know, not even crashing the background script would cause this to happen. (I don’t believe this is happening as I’m not logging any content process crashes in Firefox.)

Wild unfounded speculation based on male bughunter intuition: could it be because Bitwarden feature checks by calling `chrome.browserAction` instead of checking for `'browserAction' in chrome`? In places like `browserActionSetBadgeText()` which are called quite frequently. Could be one of those “shouldn’t cause any issues but maybe” kind of deals. I really don’t know, though.

**Comment by kspearrin** [comment]
Well, one problem here is that I use Firefox daily on macOS and Windows and have never seen this happen. So it seems environment specific for some reason.

**Comment by da2x** [comment]
Actually, I’ve since had this happen in Firefox for Android, Vivaldi on macOS, and [another user complains about it on Brave](https://github.com/brave/browser-laptop/issues/13831). I thought it was a Firefox-only issue, but maybe not.

**Comment by eliykat** [comment]
Hi @da2x, are you still experiencing this issue on the latest versions of Firefox and Bitwarden? If so, can you please provide updated troubleshooting information, including Firefox, Bitwarden and operation system versions.

**Comment by da2x** [comment]
I’ve not seen this in maybe a year. Closing.
