### ISSUE TITLE
Window does not open completely on Chrome

### ISSUE THREAD

**Issue by kidk** [bitwarden/browser#636]
Chrome version: Version 66.0.3359.181

Check screenshot for example. The window only seems to open a bit, clicking again twice usually resolves it.

![screen shot 2018-06-05 at 14 24 57](https://user-images.githubusercontent.com/184273/40975746-3e4fd3fc-68cc-11e8-9f9d-216b232f2cc7.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
