### ISSUE TITLE
Autofill doens't work on any site with current Firefox Nightly builds

### ISSUE THREAD

**Issue by heubergen** [bitwarden/browser#639]
Sorry for the spam! I'm currently unable to tell when that started but it seems like Bitwarden's autofill function has a general issue with Firefox Nightly. First I thought it was my profile or some extensions but here is how it really is:

1. Start Firefox with a fresh profile
2. Install Bitwarden and login
3. Deactivate the extensions
4. Restart Firefox
5. Activate Bitwarden
6. Autofill works now till you restart Firefox again

**Comment by kspearrin** [comment]
This is a nightly bug. https://bugzilla.mozilla.org/show_bug.cgi?id=1467136
