### ISSUE TITLE
Chrome for Mac - Bitwarden often doesn't open properly the first time clicked (and randomly other times)

### ISSUE THREAD

**Issue by anthonymag** [bitwarden/browser#641]
The extension never opens properly the first time I click it. Just shows a small white box. Sometimes it takes more than two tries, but the first time it always requires a second click.

Chrome for Mac
Version 66.0.3359.181

macOS 10.13.5

Demonstration:

![2018-06-08_14-32-24](https://user-images.githubusercontent.com/29254374/41174881-5046b4c2-6b29-11e8-8a82-ac20af12d72e.gif)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
