### ISSUE TITLE
No feedback when auto-filling on Firefox on Android

### ISSUE THREAD

**Issue by da2x** [bitwarden/browser#642]
1. Save a password for somesite.com
2. Go to somesite.com’s login form
3. Press the Firefox overflow menu: Bitwarden (this opens a new tab)
4. Tap on somesite.com’s password

Bitwarden fills the password in the background tab as expected. However, the pop-over/tab doesn’t close like it does on desktop. There is no feedback anywhere that anything happen, however. There should at least be a notification text telling the user that the login form is ready and to close the redundant tab.

**Comment by p3lim** [comment]
It _does_ however let you know when it failed, so if you press it and you don't get an error, press back and it'll close the Bitwarden tab, and you'll be presented with the login form filled.

This is not a solution to the issue however, proper feedback is necessary, preferably by closing the Bitwarden tab.

**Comment by da2x** [comment]
I stumbled upon a work around that closes the extension popout-tab when it's supposed to (see #695). It's already released and available to all on MAO.
