### ISSUE TITLE
Bitwarden Chrome Plugin problem: displaying small square when clicking on extension icon

### ISSUE THREAD

**Issue by youngpilot** [bitwarden/browser#643]
For multiple months I'm constantly experiencing the following bug with the bitwarden Chrome extension: 

<img width="207" alt="screenshot 2018-06-09 11 59 10" src="https://user-images.githubusercontent.com/15856506/41190491-f90ea7fc-6bdf-11e8-8eba-63b3bea70573.png">

When clicking the icon the bitwarden window doesnt open but a small rectangular square is opened. By clicking on the bitwarden icon multiple times, the actual bitwarden plugin UI is eventually displayed. 

Super annoying, because this happens every day. Already reinstalled the extension, rebooted my mac, logged out and in again. Unfortunately no changed behavior.

Would love to get a fix! Thanks in advance.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
