### ISSUE TITLE
Wrong URI match

### ISSUE THREAD

**Issue by joshuaavalon** [bitwarden/browser#649]
![](https://user-images.githubusercontent.com/7152420/41422550-b67428ae-702b-11e8-9ec3-e59498653c7e.PNG)

Version 1.26.0

Amazon (JP): `https://www.amazon.co.jp` (Default)
Amazon (US): `https://www.amazon.com` (Default)

However, no matter I go to `https://www.amazon.co.jp` or `https://www.amazon.com`, it shows both of them.

**Comment by kspearrin** [comment]
This is due to the global domain rules. You can adjust those in the web vault under Settings -> Domain Rules.

**Comment by joshuaavalon** [comment]
@kspearrin My bad. I forgot such thing exists. I use URI 1, URI 2 pattern instead of the domain rules.
