### ISSUE TITLE
Chrome extension bugged on osx high sierra

### ISSUE THREAD

**Issue by mkrogh** [bitwarden/browser#651]
OS: OSX High Sierra
Browser: Chrome 66.0.3359.181 (Official Build) (64-bit)
Bitwarden: 1.27.0

## How to reproduce

1. Go to any page
2. Click on the bitwarden icon in the tool bar

## Expected behavior

That the bit warden menu shows up

## What actually happens

The briefly shows for less than a second, and then is just an empty square, see image below. You need to click the icon 3 times before the menu shows up properly.

<img width="42" alt="screenshot 2018-06-15 08 17 27" src="https://user-images.githubusercontent.com/434088/41453120-cd428f14-7074-11e8-8339-cc8d5942085a.png">

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/604
