### ISSUE TITLE
UAC consent locks Bitwarden on system lock

### ISSUE THREAD

**Issue by pannal** [bitwarden/browser#652]
When the Bitwarden Chrome extension is set to lock `On System Lock` and I execute an action on the system that requires UAC consent, Bitwarden is locked afterwards.

**Comment by kspearrin** [comment]
This sounds like an issue with the chrome API since we just respond to when the API sends the lock event to Bitwarden.

**Comment by pannal** [comment]
Sounds right. Can you give me a hint where I would report this to?

**Comment by kspearrin** [comment]
https://bugs.chromium.org/p/chromium/issues/list

**Comment by pannal** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=853514

**Comment by kspearrin** [comment]
Closing since this is a Chrome issue.
