### ISSUE TITLE
Browser extension disappears at password entry, can't login - Firefox 60.0.2

### ISSUE THREAD

**Issue by blu-elephant** [bitwarden/browser#654]
Using the browser add-on for **Firefox 60.0.2 (64-bit) on Ubuntu 18.04 LTS** 
Browser Extension: 1.27.0

When I go to enter my Master Password by either of the following methods the extension disappears from view:
* using tab to navigate form the email entry field to the password entry field, OR
* clicking the field

This makes it impossible to enter my master password using the browser extension (email entry is possible). 

A re-install OR disable/enable of the extension fixes the issue in the short term. First time I do this after an install the browser extension appears in Firefox side bar (the same location where your history appears if you do CTRL+h). I can log in successfully when I do this but after this first use I get the same issue. 

Other extensions I have in use are:
* Ghostery
* GNOME Shell integration
* Privacy Badger

I've noticed that the behaviour is the same if I click the Master Password field used in the "Create Account" process too via the browser extension. 

I have no issues on Chromium.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/issues/580
