### ISSUE TITLE
Start up performance is really bad

### ISSUE THREAD

**Issue by mcfedr** [bitwarden/browser#655]
I now have a few hundred items in my vault, and every time I start up the browser the bitwarden extension spends a few minutes using 100% of cpu. Its starting to be come a really issue where I nearly want to remove the extension and go back to copy paste from the online vault.

Happens in Chrome and Firefox.

**Comment by kspearrin** [comment]
When you start up the browser is is decrypting all of your data. This would only happen if you are using lock option "Never" under settings. Else, it would only happen when you actually unlock the vault.
