### ISSUE TITLE
Hostnames ignored?

### ISSUE THREAD

**Issue by omnitec** [bitwarden/browser#658]
Is there a reason that BitWarden ignores the hostname when searching for a vault entry? IOW, if there are 30 entries for a domain name, BitWarden will never recognize the single entry for the current host, and the BasicAuth auto-fillin will fail

**Comment by kspearrin** [comment]
Perhaps you are looking for this? https://help.bitwarden.com/article/uri-match-detection/

**Comment by omnitec** [comment]
On Tue, 26 Jun 2018, Kyle Spearrin wrote:

> Perhaps you are looking for this? https://help.bitwarden.com/article/uri-match-detection/
>
Bingo - thanks!

Might you happen know which is best for BasicAuth? Tried "Exact" and
"Hostname", neither would autofill. We have two or three servers
internally using BasicAuth, and it would be really nice if BW could detect
that exact URL and autofill.

	Thanks again!!

	Lee

**Comment by kspearrin** [comment]
Basic auth has to result one only 1 login being returned or it will not be performed.

**Comment by kspearrin** [comment]
You have to limit each login that is being returned in your result set to a more restrictive matching rule.

**Comment by omnitec** [comment]
On Tue, 26 Jun 2018, Kyle Spearrin wrote:

> You have to limit each login that is being returned in your result set to a more restrictive matching rule.
>
Understood, .. but setting that entry to Exact Matech does not trigger
Basic Auth; neither does setting that entry to Hostname.

Searching on that hostname only returns a single entry, ..

	TIA!

	Lee
