### ISSUE TITLE
No autocompletion on Google anymore on Firefox

### ISSUE THREAD

**Issue by Sytten** [bitwarden/browser#660]
It seems like the auto completion of username and password doesn't work anymore on google login form. Though, it works well if I click on the auto-fill button in the context menu so it's strange...

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
