### ISSUE TITLE
Bitwarden popup in Firefox becomes blank while typing, after page load

### ISSUE THREAD

**Issue by kawaiiDango** [bitwarden/browser#663]
I was adding a login info in the popup panel while waiting for the site to load and redirect to another page. When the redirect actually completed, the popup panel became blank, and the partially typed info was lost. Happens like 1 out of 10 times, and doesn't seem specific to a site. Slow connections might also trigger this cuz sites were taking a significant amount of time to load at that time, but I'm not sure.

**Comment by kspearrin** [comment]
I am not sure I understand how you created this problem. Can you please provide steps for reproducing this?

**Comment by kawaiiDango** [comment]
- maybe simulate a slow, high latency connection (not sure if this is required)
- go to a forum site which shows a redirecting page after login/logout
- have the password saved in firefox but not in bitwarden
- try to login
- simultanously, open bitwarden popup > add a login. Do not save
- the popup becomes blank after one of those redirects complete (about 1 out of 10 times, not always)
- closing and reeopening the popup goes back to the "tabs" screen and anything typed on add a login was lost.

**Comment by kawaiiDango** [comment]
Ok, it became blank again when i was just dragging the mouse on the add login panel, tying to randomly select text. This time, unlike I mentioned earlier, the webpage wasn't loading or redirecting. Maybe the something just crashes?

It happened once in in 5 hrs of usage, and Im not sure what exactly can reproduce it. I have analytics enabled, hope that it reports crashes.

**Comment by SiqingYu** [comment]
+1
Every time it detaches from the bar, it becomes blank.
![screenshot_20181013_224929](https://user-images.githubusercontent.com/22290018/46906700-435cad00-cf3a-11e8-9a4c-0e4897117157.png)

**Comment by eliykat** [comment]
@kawaiiDango, @SiqingYu Are you still experiencing this issue on the latest versions of Firefox and Bitwarden? If so, can you please provide updated troubleshooting information, including the versions of Firefox, Bitwarden and your operating system. If this issue has been fixed in the meantime, please let me know and I'll close this issue.

**Comment by SiqingYu** [comment]
@eliykat I have switched to Chrome for a long time. The Chrome Bitwarden extension works well.
