### ISSUE TITLE
Login issue (psnprofiles.com) Safari only

### ISSUE THREAD

**Issue by heubergen** [bitwarden/browser#666]
This issue only occurs with Safari. Tested with Safari v12 under macOS 10.14.

Setup:
Installed Bitwarden for Safari Extensions, Auto-fill is disabled
STR:
Open https://psnprofiles.com/login
Open Bitwarden and click on the the saved logins from this site

What happens:
Bitwarden somehow tries to solve the Captcha for me which ends in an error:
<img width="494" alt="screen shot 2018-07-10 at 1 13 13 pm" src="https://user-images.githubusercontent.com/5529410/42534975-0353b614-8443-11e8-912c-2e889be61b0a.png">

With the same page and login, the problem doesn't occur under Firefox Nightly (63.x) with macOS 10.14.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
