### ISSUE TITLE
[chrome] Right clicking any link, folder or entry causes chrome to crash

### ISSUE THREAD

**Issue by alex-irt** [bitwarden/browser#667]
Opening the extension menu in chrome, then right clicking any link (like the log out link under the master password input field) or right clicking any folder or password item instantly crashes chrome.

Version: Chrome for Windows 10 Version 67.0.3396.99 (Official Build) (64-bit)

Work around: Do not right click

**Comment by kspearrin** [comment]
Not able to reproduce this, so it seems specific to your environment. Maybe try a new user profile to see if it persists?

**Comment by alex-irt** [comment]
Thanks for the prompt reply. You're right it must be something else causing it, I can't replicate it on another computer.

**Comment by ivancuric** [comment]
Same thing happening here. MacOS, Chrome 68.

**Comment by vlad-teodor** [comment]
The same thing is happening here. Windows 10, Chrome 68.0.3440.106 (64-bit).

It doesn't happen in Opera (with the Chrome extension), Firefox or Edge.
Creating a new user profile doesn't help. Disabling all other extensions doesn't help.
