### ISSUE TITLE
Brave browser extension is slow loading when clicking the icon

### ISSUE THREAD

**Issue by manueltorrez** [bitwarden/browser#668]
Brave browser extension is slow loading when I click the Bitwarden icon. I checked using Chrome before and it runs smoothly but in Brave it's slow. Everything is good from loging in to search, generating passwords, etc. But it's slow at first

### Additional information

**brave info:** 0.23.31-1
**OS:** Manjaro Linux

**Comment by tntturtl** [comment]
I have the same issue in Brave on Windows 10 Pro.

**Comment by lhorace** [comment]
Brave from the tickets I read, not sure, can you give example? I mean whcn you click, did get the loading symbol?

**Comment by eliykat** [comment]
Hi @manueltorrez, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
