### ISSUE TITLE
Chrome's "On System Lock" setting locks the extension on a browser restart as well

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#669]

**Comment by kspearrin** [comment]
This is true for every lock option other than never.

**Comment by maxrom** [comment]
I see. So the difference between the two is if I leave Chrome up, the extension will be locked when I unlock Windows (which I've just confirmed). Thanks.

**Comment by kspearrin** [comment]
Yes, with lock options other than never, your key is only held in memory, which is always lost on restart of the browser.
