### ISSUE TITLE
Login fill problem

### ISSUE THREAD

**Issue by Mioni** [bitwarden/browser#670]
https://marcacaoconsulta.hapvida.com.br in CÓDIGO DO BENEFICIÁRIO don't fill, this is bug?
 
![ba3e13cd-75b0-41a8-a5ff-c775ffa6c992](https://user-images.githubusercontent.com/6830783/42770919-edc90174-88fb-11e8-841e-bbc939735e43.png)

**Comment by kspearrin** [comment]
That website does not load for me. Can you save the page and attach it here?

**Comment by Mioni** [comment]
Sure.

[Hapvida.zip](https://github.com/bitwarden/browser/files/2198747/Hapvida.zip)

**Comment by kspearrin** [comment]
How are you expecting this to fill? It doesn't look like the page has a password field on it.

**Comment by Mioni** [comment]
I know this field is like document I tested with 1passwordx and it worked normal I thought it was some kind of "bug".
If this is complicated to implement I understand. 😋

**Comment by kspearrin** [comment]
It sounds like you want to use custom fields: https://help.bitwarden.com/article/custom-fields/

**Comment by Mioni** [comment]
it's worked!
I did not know this function, thank you!
