### ISSUE TITLE
Automatically signs in for basic auth

### ISSUE THREAD

**Issue by pgera** [bitwarden/browser#676]
The chrome extension automatically signs in for basic_auth in the default setup. I can't find an option to disable this behaviour. I have an nginx site that uses {auth_basic "Restricted";
               auth_basic_user_file /etc/nginx/.htpasswd;}, and the extension automatically signs me in.

**Comment by kspearrin** [comment]
There isn't an option to turn it off. As a workaround, you could create a second fake login for the same URI. Basic auth logins will only be attempted if there is only 1 matching login. So if there are two by creating the fake one, it wont do it.

**Comment by pgera** [comment]
Any particular reason why this is treated separately ? Isn't auto-fill generally discouraged from a security perspective ?

**Comment by pieterdd** [comment]
Is that the case? Because in LastPass, I still got a login dialog with a button to autofill. Might be behavior specific to Firefox though, not sure.

**Comment by hexchain** [comment]
It seems that [gopassbridge](https://github.com/gopasspw/gopassbridge) is able to show a popup on basic auth requests. Maybe there's still a way to do user interaction?

**Comment by kspearrin** [comment]
@hexchain Can you show a screenshot/video of what it looks like with gopassbridge?

**Comment by hexchain** [comment]
@kspearrin Sure.

When visiting a site that requires HTTP Basic authentication, a popup window is shown:

![image](https://user-images.githubusercontent.com/529520/56965382-758fce00-6b5d-11e9-8458-cf5c4e88fafa.png)

By clicking on the item, it will authenticate with the selected credential. The Chrome username and password dialog is shown if the popup window is closed.

**Comment by Kaan88** [comment]
Same with Kee.pm, this issue needs to be reopened.
