### ISSUE TITLE
More than one login item per domain confuses Bitwarden

### ISSUE THREAD

**Issue by lguariento** [bitwarden/browser#677]
Hello,
I'm using Bitwarden plugin for Firefox 61 on OSX. It all works fine, until I have to fill in a login form for a domain for which I have more than one login item stored in my vault.

For instance:

www.mydomain.com/folder1/login_page_1
www.mydomain.com/folder2/login_page_2
www.mydomain.com/folder3/login_page_3

The address stored within each login item is the complete address (with the subfolder correctly input).

This happens even if I have a wordpress blog and also a ssh login/password stored for when I update the wordpress itself (to be filled in the Wordpress update page, within the administration). Bitwarden, when I go to mywordpresssite.com/admin, fills in the ssh details, not the login details.

I've migrated to Bitwarden recently; before that, I was using Lastpass, which was always correctly detecting the right page. I've started to have these issue when I started using Bitwarden.

**Comment by kspearrin** [comment]
You can adjust the match detection. See here: https://help.bitwarden.com/article/uri-match-detection/
