### ISSUE TITLE
how can i build this project... somebody help me.

### ISSUE THREAD

**Issue by rain3k** [bitwarden/browser#679]
i have a some problem.. when this project built

how can i build this project... somebody help me.

below node.js,gulp version
kimui-MacBook-Pro-2:browser kimkyungkuk$ node -v
v10.6.0
kimui-MacBook-Pro-2:browser kimkyungkuk$ gulp -v
[16:47:52] CLI version 2.0.1
[16:47:52] Local version 3.9.1

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.2.4 install /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.2 install /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/kimkyungkuk/.npm/node-sass/4.9.2/darwin-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> ngx-infinite-scroll@0.8.4 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/ngx-infinite-scroll
> opencollective postinstall

                   Thanks for installing ngx-infinite-scroll 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                            Number of contributors: 24
                               Number of backers: 2
                                Annual budget: $57
                               Current balance: $33

    👉  Donate: https://opencollective.com/ngx-infinite-scroll/donate

> node-sass@4.9.2 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> tldjs@2.0.0 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser/node_modules/tldjs
> node ./bin/postinstall.js

> bitwarden@0.0.0 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser
> npm run sub:init

> bitwarden@0.0.0 sub:init /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser
> git submodule update --init --recursive

fatal: Not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! bitwarden@0.0.0 sub:init: `git submodule update --init --recursive`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 sub:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimkyungkuk/.npm/_logs/2018-07-25T06_47_56_731Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! bitwarden@0.0.0 postinstall: `npm run sub:init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimkyungkuk/.npm/_logs/2018-07-25T06_47_56_770Z-debug.log
kimui-MacBook-Pro-2:browser kimkyungkuk$ mkdir .git
kimui-MacBook-Pro-2:browser kimkyungkuk$ npm install

> bitwarden@0.0.0 postinstall /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser
> npm run sub:init

> bitwarden@0.0.0 sub:init /Users/kimkyungkuk/Documents/Project/KT_Project/browser-master/browser
> git submodule update --init --recursive

fatal: Not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! bitwarden@0.0.0 sub:init: `git submodule update --init --recursive`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 sub:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimkyungkuk/.npm/_logs/2018-07-25T07_07_43_811Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! bitwarden@0.0.0 postinstall: `npm run sub:init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the bitwarden@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kimkyungkuk/.npm/_logs/2018-07-25T07_07_43_840Z-debug.log

**Comment by Crocmagnon** [comment]
How did you get the sources ? It seems that `npm` is looking for the `.git` folder containing git data, however this folder is not provided in the zip download, it only exists when you `git clone` the project.

**Comment by kspearrin** [comment]
You need to properly clone the repo.
