### ISSUE TITLE
Minimum special characters field hidden in password generator for french location

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/browser#682]
I'm using a french-localized version of the browser extension and the field for minimum special characters is hidden, see :

<img width="389" alt="capture d ecran 2018-08-01 a 14 44 53" src="https://user-images.githubusercontent.com/3630554/43522501-d9889760-9599-11e8-8828-842e4c6eb039.png">

In English version I can see the field but it has a margin with the border of the extension compared to the other field.

![capture d ecran 2018-08-01 14 51 00](https://user-images.githubusercontent.com/3630554/43522746-8b5c630e-959a-11e8-852d-2420025b3730.png)

Reproducible on Firefox 61.0.1 on macOS and Windows and Firefox Nightly 63.0a1 (2018-08-01) on Windows.

**Comment by kspearrin** [comment]
what browser?

**Comment by Crocmagnon** [comment]
I updated my comment to add the browser

**Comment by Crocmagnon** [comment]
Any update on this @kspearrin ? Are you able to reproduce this behavior ?

**Comment by kspearrin** [comment]
I tested in Chrome and it seems fine. Will have to check Firefox now.

**Comment by kspearrin** [comment]
Can't seem to figure out how to change the interface language of Firefox. :-/

**Comment by Crocmagnon** [comment]
I've found this, does it help ? https://support.mozilla.org/fr/questions/1018686

**Comment by kspearrin** [comment]
Those instructions seem to be outdated. Those keys dont exist in about:config for me

**Comment by Crocmagnon** [comment]
I guess you'll have to download another version of FF from https://support.mozilla.org/en-US/locales

**Comment by Crocmagnon** [comment]
I just got it to work :
1. Download the proper language pack addon from https://addons.mozilla.org/en-US/firefox/language-tools/
2. In about:config, add the `intl.locale.requested` key with the value `fr` (for french)

**Comment by kspearrin** [comment]
Should be fixed in next version. Thanks.
