### ISSUE TITLE
"Never remember for this website" is never remembering for the wrong website

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#683]
Specifically, for capitalone.com, when I sign in from the homepage capitalone.com, by the time the prompt to save the credentials or never remember for this site, I've been signed in and redirected to myaccounts.capitalone.com. When I click never remember, I suspect it's making that choice for myaccounts.capitalone.com, not capitalone.com itself because I'm asked each time I sign in after.

**Comment by Crocmagnon** [comment]
I don't know the current implementation but IMHO in your example Bitwarden should _never remember_ `homepage.capitalone.com` and not `capitalone.com`

**Comment by eliykat** [comment]
The next release will include the ability to manage this "never remember" domain list: https://github.com/bitwarden/browser/pull/1376

This should allow you to tweak entries where the prompt doesn't catch the correct domain.
