### ISSUE TITLE
Enpass Issues with Importation of Data

### ISSUE THREAD

**Issue by squirrelboot** [bitwarden/browser#685]
When importing my data from Enpass, it doesn't properly import. It mislabels the URL/URI as Secure Note instead of a login. So over 500 of my logins don't get recognized/work when using BitWarden.
[See examples here](https://imgur.com/a/HHjJFjZ)

Further, there is a current issue where if the data import has a portion which exceeds 10,000 characters, it will fail importing and not explain why. I had to contact support. Long ago, in a secure note I had added some terms/conditions I saved, in case the company backed out of an agreement. It was easy to remove the offending entry after I learned where it was. But again, the tool does NOT currently work in telling us where (what line) the issue exists. 

[Current error looks like this](https://imgur.com/wodEakW)

UPDATE: PLEASE NOTE!

I have now discovered that [Enpass has a version 6 BETA](https://www.enpass.io/enpass-6-beta-downloads/).

[New Export Option](https://i.imgur.com/yviwkfb.png)
[JSON/TEXT](https://i.imgur.com/IqKTme4.png)

They currently only allow exporting in .JSON and .TXT files now. I think JSON is better though, as it's much more specific and defined that in CSV files for example.

I would really like to try RE-IMPORTING my Enpass data to BitWarden using the JSON option, to see if this resolves my issues as noted above. 

Can someone create a tool for importing this data?

**Comment by djsmith85** [comment]
@squirrelboot Thank you for opening this isse. Since your initial posting, several versions have been released, and with commit https://github.com/bitwarden/jslib/commit/e64fdf4e2137cfd28377ab02bf9967442eb599e7 a Enpass json importer was added.

If this issue is resolved, could you please close it.

**Comment by eliykat** [comment]
I'm closing this as I believe it's been resolved by https://github.com/bitwarden/web/pull/841, plus the Enpass importer mentioned above.
