### ISSUE TITLE
Firefox: Can't open the popup of extension

### ISSUE THREAD

**Issue by JonathanMM** [bitwarden/browser#686]
Hello everyone,
I can't use firefox extension of bitwarden. After install it, when I click on the icon of bitwarden near the address bar, a popup displayed and ask my password.
But, I don't have the time to fill it because it closes immediately, approximatively 0,5s after it opens, without action on my side.
Have you an idea to solve this issue?

**Comment by kspearrin** [comment]
Linux ?

**Comment by JonathanMM** [comment]
Yes, ubuntu 18.04 64bits

**Comment by kspearrin** [comment]
Duplicate #580

**Comment by JonathanMM** [comment]
Oh, many thanks :)

**Comment by doofz** [comment]
I'm running Windows 10 and have the same issue as described by @JonathanMM
