### ISSUE TITLE
Bitwarden Firefox addon suppresses HTTP Basic Auth dialog

### ISSUE THREAD

**Issue by ryan77627** [bitwarden/browser#687]
Hello all! I am trying to login to my webpage, "protected" by basic auth, (Used mostly for basic user verification, nothing site breaking) but in firefox, I immediately get a 401 Unauthorized response when going to the website. After disabling bitwarden, it shows the dialog fine. I am aware of request #116 however two things:

- My vault is locked during this
- I do have passwords on this domain, however not this specific SUB-domain, so it shouldn't try to autofill from a locked vault.

Any reason it would suppress the dialog? This doesn't happen in Chrome. Thanks!

**Comment by kspearrin** [comment]
If the vault is locked it should not attempt anything so I am not sure if there is some difference in how the APIs behave in Firefox.

**Comment by ryan77627** [comment]
I just installed firefox beta and put bitwarden on that, issue seems to be gone. Weird, some sort of cache must've remained, even though I cleared my cache and restarted firefox multiple times. Oh well, false alarm maybe? ¯\ \_(ツ)_/¯
