### ISSUE TITLE
Bitwarden popup disapear when clicking the bitwarden button on firefox

### ISSUE THREAD

**Issue by ehudon** [bitwarden/browser#691]
When I click the bitwarden button using Firefox 61.0.1 on Ubuntu 18.04.1, the popup automatically disapear. The same use case works fine with Firefox 61.0.1 o MacOS High-Sierra. In both case the only plugin I have installed is Bitwarden.

![file](https://user-images.githubusercontent.com/17802570/43900629-7342a980-9bb3-11e8-86ec-972eb3e018e7.gif)

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/issues/580
