### ISSUE TITLE
"Unable to auto-fill the selected item on this page"

### ISSUE THREAD

**Issue by HizzyHaz** [bitwarden/browser#692]
cannot auto fill on the following URL in Firefox 62.0.2
https://support.mozilla.org/en-US/users/auth

Auto-fill does work in Chrome and Vivaldi

Same issue with Firefox Sync account login:
https://accounts.firefox.com/signin?service=sync&context=fx_desktop_v3&entrypoint=menupanel

**Comment by kspearrin** [comment]
Yea, I noticed this too. It seems like Firefox is blocking extension content scripts on their own domains for whatever reason. Not sure what could be done about it.

**Comment by getreadyforme** [comment]
OK. Thanks.

**Comment by code-sur** [comment]
same here

**Comment by winkler-winsen** [comment]
I had the same problem reported to Bitwareden community forums: https://community.bitwarden.com/t/firefox-account-sync-autofill-does-not-work/7643/4

Firefox has a block list for webextentions on specified domains. You can find them under `about:config` section `extensions.webextensions.restrictedDomains`:

> accounts-static.cdn.mozilla.net,accounts.firefox.com,addons.cdn.mozilla.net,addons.mozilla.org,api.accounts.firefox.com,content.cdn.mozilla.net,discovery.addons.mozilla.org,install.mozilla.org,oauth.accounts.firefox.com,profile.accounts.firefox.com,support.mozilla.org,sync.services.mozilla.com

My questions: 
1. Is it possible to throw a warning message in Firefox Addon to give the user an advice, why Bitwarden cannot work on specific domain.
2.  Put a note on [Help/FAQ](https://bitwarden.com/help/), which describes the behavior and tell users how to edit this block list, if they want to enable Bitwarden on a specific domain. I looked on GitHub for editing Help/FAQ pages, but cannot find it, so I can't create a Pull Request for that.

P.S. I removed `accounts.firefox.com` from my block list to make Bitwarden work for that domain.

CU!Lars

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
