### ISSUE TITLE
Most icons do not show up

### ISSUE THREAD

**Issue by Mioni** [bitwarden/browser#693]
Still have enough on the list..
![untitled](https://user-images.githubusercontent.com/6830783/43991413-c30e000a-9d42-11e8-92a5-81dfe4d95e77.png)

Vivaldi 1.15

**Comment by kspearrin** [comment]
Yes, there were some known issues with the icons server for a couple of days which led to lots of icon requests caching 404. It should get better in the next few days as the old bad caches expire.

**Comment by kspearrin** [comment]
I purged the cache on our CDN, so these should now start showing up.
