### ISSUE TITLE
Extension menu instantanely hide when I click on it.

### ISSUE THREAD

**Issue by SimonLefort** [bitwarden/browser#694]
Hello, 
Thank you for your work on BitWarden.

On Firefox 61.0.1 (on Ubuntu 18.04 with Gnome), it's impossible to use the extension because it "auto-hide" when I click on it. I click, I see menu appeared and it disappear. I can't log in. :-/ 

The version is 1.29.0.

I hope we'll find a solution. :-)

**Comment by kspearrin** [comment]
#580
