### ISSUE TITLE
Firefox extension stops working after entering search term

### ISSUE THREAD

**Issue by tomwassenberg** [bitwarden/browser#699]
After upgrading to v1.30.1, the Firefox extension stops responding after I enter a few characters as a search term.

CPU usage rises dramatically and on one of my machines (Windows, Fx 62.0b17) the addon window doesn't re-appear when clicking on the icon. On Linux (Fx 61.0.1) Firefox locks up entirely and has to be force quit.

I can reproduce the issues on v1.30.0 and v1.30.1 of the Firefox extension.

Tested on Windows 10 with Firefox 62.0b17 and Linux Mint with Firefox 61.0.1.

**Comment by kspearrin** [comment]
How many items are in the vault? Can you also reproduce this in the web vault?

**Comment by tomwassenberg** [comment]
Thanks for the instant reply!

Same thing happens with the web vault. Vault contains approximately 500 items.

**Comment by kspearrin** [comment]
Ok. Sounds like there is some item that is causing this same bug I discovered in Lunr: https://github.com/olivernn/lunr.js/issues/368

Try performing your search query with a preceding `>` and see if the same issue occurs.

For example, `>something` instead of `something`.

**Comment by tomwassenberg** [comment]
Looks like you're right, preceding the query with `>` seems to resolve the issue.

**Comment by kspearrin** [comment]
Ok, it's definitely the bug I linked above which seems to have issues with wildcards, which are used by default when not doing a `>` search. Would you happen to have a few minutes to help me try to debug this further in your vault? I am available in our [dev chatroom](https://gitter.im/bitwarden/Lobby) here and would like to try to run through some steps to figure out which item in your vault is causing the problem.

**Comment by kspearrin** [comment]
@tomwassenberg I pushed 1.30.2 which reduces regular searching to only trailing wildcards for now. Can you update and try it to see if the problem with regular searching is resolved?

**Comment by kspearrin** [comment]
It was also pushed to the web vault.

**Comment by tomwassenberg** [comment]
Yes, 1.30.2 (+ web) fixes the problem with regular searches :)

**Comment by kspearrin** [comment]
Closing this for now. Tracking at https://github.com/olivernn/lunr.js/issues/368
