### ISSUE TITLE
Keyboard Commands (hotkeys)

### ISSUE THREAD

**Issue by UberPanda** [bitwarden/browser#7]
Either I missed it or the current state of completion in chrome extension is only through mouse based interaction.
I do not think I am the only one thinking that keyboard based interaction would be nice too.

**Comment by kspearrin** [comment]
Good suggestion,

How would you expect the hotkeys to work? I am not a huge hotkey user myself as far as browser usage is concerned, so I may not be the best to define this feature.

One option could be with the browser omnibox API. https://developer.chrome.com/extensions/omnibox

**Comment by UberPanda** [comment]
My current habit (which comes from using keepassx) would be something like : 

Type a key combination (ctrl + shift + n in my case) which prompts available completions, navigate through them with arrows and select one with enter.
Hotkeys could also be used to create a new entry.
Thus, I do not think that omnibox would be a good solution. However the commands api should do the trick : https://developer.chrome.com/extensions/commands

**Comment by kspearrin** [comment]
Excellent. I'll put this on the roadmap for an upcoming release.

**Comment by kspearrin** [comment]
Check out https://github.com/bitwarden/browser/commit/691d2625d723977ce04503627b8935b901c43ee6

**Comment by UberPanda** [comment]
Seems nice for now.
Next step would be being able to customize hotkeys, but that looks like quite a bit more work.

**Comment by kspearrin** [comment]
The hotkeys are fully customizable via the browser extension settings. These are just the defaults.

**Comment by UberPanda** [comment]
Indeed, seems to work fine. Might need a little visual refinement though (currently I can only see which login is selected through a very thin blue highlight, more explicit highlighting might be a plus).

**Comment by kspearrin** [comment]
Yea, it just needs some additional styling for the focus state. Will see what I can do.

**Comment by blockloop** [comment]
I have a manually configured LastPass keyboard shortcut which I can set in the options.

**Comment by kspearrin** [comment]
This should help: https://github.com/bitwarden/browser/commit/97fe37515bf868d9821e13d3b8def252f36f025e

**Comment by blockloop** [comment]
@kspearrin when will this make it to the Chrome store?

**Comment by kspearrin** [comment]
@blockloop it's there now with 1.1.0 (might take ~30 minutes or so to propagate) https://github.com/bitwarden/browser/releases/tag/v1.1.0

**Comment by UberPanda** [comment]
Just noticed that if you use the addon, you would get something like : 
 - shortcut
 - Tab(s)
 - Enter (that fills the login)
But then pressing enter would not do anything. A simple way to solve this would be setting the text cursor to be at the end of the filled password. Another way would be to include the enter in the plugin after typing the password (as keepass would do by default).

**Comment by blockloop** [comment]
I've updated and restarted Chrome and I'm still not able to use the keyboard shortcuts. I don't even see that command as an option in the shortcuts menu

![image](https://cloud.githubusercontent.com/assets/3022496/19275041/f7abfcfa-8f97-11e6-879c-65d9581b84e0.png)

![image](https://cloud.githubusercontent.com/assets/3022496/19275044/fa621646-8f97-11e6-93bf-b0881d329234.png)

**Comment by kspearrin** [comment]
@blockloop You don't see what command? I see both supported commands there now. "Activate the extension" is the one that will open the extension to the "Current Tab" page.

It appears the that default that I picked for OSX (Command+Shift+Y) is already taken by something else in the browser and therefore loses that binding. This is why you are seeing "Not set". You can choose to set it to whatever you like.

If you can, please recommend me a good default for OSX since it seems the one I have chosen cant work there.

**Comment by blockloop** [comment]
Ah. I was looking for a command to "fill form." I misunderstood. I used CTRL \ (backslash) with LastPass. I don't think it had any issues. 


Sent from my iPhone

**Comment by SylwesterZarebski** [comment]
What about Firefox - how can I change shortcut?

**Comment by kspearrin** [comment]
@SylwesterZarebski Unfortunately Firefox does not allow you to change the shortcut at this time.

**Comment by SylwesterZarebski** [comment]
Thanks, that's sad, but i'll wait for new version which allows to change key shortcut (like LastPass or other addons).

**Comment by kspearrin** [comment]
You'll find that the new version of lastpass for Firefox coming out soon will also lose this functionality. This all has to do with the move to web extensions which is not as feature rich for Firefox yet as the older Firefox apis.

**Comment by shkm** [comment]
Great that we have a shortcut, but two requests below. I use Firefox.

1. I have to hit tab twice to get to my list of logins, which isn't ideal.
2. If there's only one login available, can it just autofill when pressing the shortcut?

**Comment by stephenermshar** [comment]
Would it be possible to do something like Alfred for Mac OS where results are numbered? For instance, pressing Cmd+3 selects the 3rd option.

<img width="578" alt="Screen Shot 2020-02-01 at 8 32 53 PM" src="https://user-images.githubusercontent.com/10591356/73603011-161e7e80-4532-11ea-8cb8-93247d1b7c7c.png">

**Comment by KevinNSTA** [comment]
@stephenermshar  this is a pretty old request, probably should just make a feature request here https://community.bitwarden.com/c/feature-requests

They Migrated away from Issues as Feature Requests a while back - like a couple years I think

**Comment by shkm** [comment]
There's this feature request:

https://community.bitwarden.com/t/add-essential-keyboard-shortcuts-navigation/76/47

**Comment by akaleeroy** [comment]
So Bitwarden doesn't have Omnibox API integration? What's the "power-user" login sequence presently?

For example LastPass on Chromium: 

1. <kbd>Alt</kbd>+<kbd>D</kbd> to go to address bar
2. `lp` <kbd>Spacebar</kbd> to select the LastPass extension's search engine
3. Type `acmeforums`
4. <kbd>↓</kbd> to select **ACME Inc. Forums** from suggestions
5. <kbd>Enter</kbd>

**Comment by PsychoData** [comment]
It is reprogrammable with Chrome. You can check what you have it set to under chrome://extensions/shortcuts 
For example I use both 1 Password X (Chrome) at - <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>X</kbd> 
and I have BitWarden set to <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>S</kbd>  

But I believe the default for BitWarden (By clearing my choices) is <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>Y</kbd>  
![image](https://user-images.githubusercontent.com/3719116/79642564-27a81780-816c-11ea-9ef1-15c92d5abbd7.png)

**Comment by 1024mb** [comment]
At least in Vivaldi I had to enter chrome://extensions/shortcuts to assign the shortcut because there was none by default, this was caused most probably by Tab Session Manager which also used the same shortcut to (de)activate the extension.
Couldn't this shortcut configuration be implemented inside Bitwarden's extension settings?
