### ISSUE TITLE
Bitwarden gets confused over fields on AWS login

### ISSUE THREAD

**Issue by rjcoupe** [bitwarden/browser#70]
Logging into an AWS account can involve both an account and username field entry. One account can have many usernames.

**Actual Behaviour**
Bitwarden reads the "account" field as the one into which the saved username should be injected on auto-fill.

**Expected Behaviour**
The saved username is inserted into the correct field (either leaving the "account" field blank, or filling it with the originally entered value).

**Comment by kspearrin** [comment]
What page is this happening on because [this one](https://www.amazon.com/ap/signin?openid.assoc_handle=aws&openid.return_to=https%3A%2F%2Fsignin.aws.amazon.com%2Foauth%3Fresponse_type%3Dcode%26client_id%3Darn%253Aaws%253Aiam%253A%253A015428540659%253Auser%252Fhomepage%26redirect_uri%3Dhttps%253A%252F%252Fconsole.aws.amazon.com%252Fconsole%252Fhome%253Fstate%253DhashArgs%252523%2526isauthcode%253Dtrue%26noAuthCookie%3Dtrue&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&action=&disableCorpSignUp=&clientContext=&marketPlaceId=&poolName=&authCookies=&pageId=aws.ssop&siteState=pre-register%2Cen_US&accountStatusPolicy=P1&sso=&openid.pape.preferred_auth_policies=MultifactorPhysical&openid.pape.max_auth_age=120&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&server=%2Fap%2Fsignin%3Fie%3DUTF8&accountPoolAlias=&forceMobileApp=0&language=en_US&forceMobileLayout=0) seems to work just fine?

**Comment by DanCardin** [comment]
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1

**Comment by kspearrin** [comment]
The above link redirects me to this:

https://www.amazon.com/ap/signin?openid.assoc_handle=aws&openid.return_to=https%3A%2F%2Fsignin.aws.amazon.com%2Foauth%3Fresponse_type%3Dcode%26client_id%3Darn%253Aaws%253Aiam%253A%253A015428540659%253Auser%252Fec2%26redirect_uri%3Dhttps%253A%252F%252Fconsole.aws.amazon.com%252Fec2%252Fv2%252Fhome%253Fregion%253Dus-east-1%2526state%253DhashArgs%252523%2526isauthcode%253Dtrue%26noAuthCookie%3Dtrue&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&action=&disableCorpSignUp=&clientContext=&marketPlaceId=&poolName=&authCookies=&pageId=aws.ssop&siteState=unregistered%2Cen_US&accountStatusPolicy=P1&sso=&openid.pape.preferred_auth_policies=MultifactorPhysical&openid.pape.max_auth_age=120&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&server=%2Fap%2Fsignin%3Fie%3DUTF8&accountPoolAlias=&forceMobileApp=0&language=en_US&forceMobileLayout=0

Which again seems to autofill just fine for me?

**Comment by kspearrin** [comment]
Is this not the page you are on?

![capture](https://cloud.githubusercontent.com/assets/1190944/22186145/1685202a-e0bf-11e6-875c-097b15f180df.PNG)

**Comment by DanCardin** [comment]
https://console.aws.amazon.com/ redirects me to a page like this
![screenshot from 2017-01-25 14-33-22](https://cloud.githubusercontent.com/assets/701548/22306034/ae77b49e-e30b-11e6-87f9-f89a99fb1c8a.png)

**Comment by King-Tut-Tut** [comment]
I get redirected to the same page Kyle gets redirected to.

**Comment by kspearrin** [comment]
I'm not sure how to get tot hat page @DanCardin . Can you provide a direct link to what you are being redirected to?

**Comment by kspearrin** [comment]
I found this which looks like your page: https://account.signin.aws.amazon.com/console

But autofill seems to work just fine for me on it?

**Comment by mlerota** [comment]
It's not working for me either. Every customer has it's own link to his account. For example: 
https://123456789.signin.aws.amazon.com/console 

or can have an alias to this account like:

https://customer1.signin.aws.amazon.com/console

When you go to your AWS login, you are redirected to some huge url. But at the end 
you have three fields: Account, User Name and Password. 
- in account field you put: 123456789 or customer1 
- in username field you put: your_username
- in pass: you password of course

When you activate Bitwarden, it messes up these three fields. The correct way would be: 
- Account: customer1 
- Username: your_username
- Pass: *****

But instead it says:
- Account: account
- Username: customer1
- Pass: *****

This Account and username field get messed up.

**Comment by rjcoupe** [comment]
This appears to be fixed in the current version as of April 5th 2017.

**Comment by ShantanuNair** [comment]
It's still very broken in the current release as far as I cant tell. Bitwarden does not differentiate between AWS IAM / AWS root user / Amazon Retail.

**Comment by tiagocborg** [comment]
I just come from lastpass, and I can confirm that it does't work. Bitwarden are able to fill username and password, but it fails doesn't work with the account id. Maybe there is a way to point custom fields that are already supported by bitwarden to unmapped fields on the website?

**Comment by david-va** [comment]
https://signin.aws.amazon.com/
same here, for root options the password is entered on a separate form, it's not auto identified/filled
![image](https://user-images.githubusercontent.com/32459780/87575829-2e95e600-c6d9-11ea-806b-49a2ad9e7ba2.png)

**Comment by stevemarksd** [comment]
why is this closed if is still happening?

**Comment by MatteoInfi** [comment]
This is still broken

**Comment by Exodus** [comment]
This is not broken for me, but I have found myself configuring the fields myself:
In Bitwarden you want to configure an extra text field:
Name: account
Value: Whatever your account-id is.

Remember that Bitwarden picks this up from html id and will autofill it.

**Comment by dave-michael** [comment]
> This is not broken for me, but I have found myself configuring the fields myself:
> In Bitwarden you want to configure an extra text field:
> Name: account
> Value: Whatever your account-id is.
> 
> Remember that Bitwarden picks this up from html id and will autofill it.

Recently switched to BitWarden and was having the same issue. This resolved it for me. Thanks!

**Comment by Ryanb58** [comment]
> > This is not broken for me, but I have found myself configuring the fields myself:
> > In Bitwarden you want to configure an extra text field:
> > Name: account
> > Value: Whatever your account-id is.
> > Remember that Bitwarden picks this up from html id and will autofill it.
> 
> Recently switched to Bitwarden and was having the same issue. This resolved it for me. Thanks!

Thanks! This information helped remedy the issue.

**Comment by eliykat** [comment]
We have a dedicated issue going at #1621 if anyone is experiencing further autofill problems that they'd like to report. However, custom fields are likely to be the quickest way to fix it for yourself without waiting for us ;)

**Comment by undermark5** [comment]
@eliykat Ya, custom fields are great and all, except for the fact there isn't a way to reference existing properties of the vault item, I shouldn't have to copy the username or password into the custom fields. Duplication is generally a bad thing, and in this case I think such duplication is very bad. Please consider [this issue](https://github.com/bitwarden/browser/issues/1683) and [feature request](https://community.bitwarden.com/t/custom-field-variables-for-username-and-password/8389/8)

**Comment by eliykat** [comment]
@undermark5 We've since implemented that feature, they're called Linked Fields and they're a type of custom field. (they are "linked" to an existing property so you don't have to duplicate it.) See more information [here](https://bitwarden.com/help/custom-fields/).
