### ISSUE TITLE
Chrome Extension: Password Generator, cannot copy password

### ISSUE THREAD

**Issue by Daptonic** [bitwarden/browser#700]
As of this morning I have been unable to copy the generated password in the Chrome extension, I have not tried other browsers as of yet.

When clicking on the password I get the "password copied" notification, but when pasting to notepad it pastes whatever was in the clipboard previously.

**Comment by kspearrin** [comment]
Fixed in 1.30.3 coming out soon. Thanks.

**Comment by Daptonic** [comment]
Awesome. Thanks!
