### ISSUE TITLE
Auto-fill with multiple accounts

### ISSUE THREAD

**Issue by g4rpch** [bitwarden/browser#702]
Hi folks,
on some websites I'm registered with multiple accounts. All are stored on the vault.
With auto-fill option enabled a (random?) account is used to fill up the login form.
Anyway to prompt for a window that ask which account you want to use to login?

Cheers
G4rp

**Comment by Crocmagnon** [comment]
The last entry you used is autofilled if multiple are detected.

Also, GitHub issues are not for feature requests, please head to https://community.bitwarden.com/.
There's already a feature request for this : https://community.bitwarden.com/t/overlay-popup-interface/14

**Comment by kspearrin** [comment]
Yes, autofill on page load will use the last used login from a manual autofill.
