### ISSUE TITLE
Can't access folder details / delete folder

### ISSUE THREAD

**Issue by mwiesen** [bitwarden/browser#704]
Because the folder name is too long and I can't click the pencil icon. Maybe line breaking is a solution?

For context, I imported my vault from Lastpass where I have a lot of folders with long names. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/13396818/44348797-c3ffaf80-a49b-11e8-96fb-05e891a941cb.png)

**Comment by kspearrin** [comment]
Your screenshot shows the pencil icon. Can you not click it?

**Comment by mwiesen** [comment]
No I can't using Chrome or Edge on Windows. Also when I move the mouse over the pencil, no URL is displayed at the bottom left of the browser window.

However, I can confirm the issue doesn't exist on Firefox, where the long folder names are broken into multiple lines.

**Comment by kspearrin** [comment]
Fixed next version 
![image](https://user-images.githubusercontent.com/1190944/44425396-bdd00880-a559-11e8-9833-47ef1d713b4e.png)

**Comment by mwiesen** [comment]
Thank you so much for the quick fix!!!
