### ISSUE TITLE
Context menu nesting structure is unnecessary and annoying

### ISSUE THREAD

**Issue by chris-morgan** [bitwarden/browser#705]
The context menu structure is:

+ Bitwarden
  + Auto-fill
    + *Site (username)*

This is rather annoying to use, as I have to go to Bitwarden, then Auto-fill, then the site. Three layers where it should be two.

For reference, Firefox’s own approach with its built-in password manager is:

+ Fill Login
  + *Username*
  + ----
  + View Saved Logins

Only one level of hierarchy, 👍.

**Comment by chris-morgan** [comment]
Looking at https://help.bitwarden.com/article/auto-fill-browser/ I see what the other options are (though I’m uncertain why “Copy Username” and “Copy Password” would exist, if they are what I imagine they are).

I still urge flattening the structure and just using a separator between the sections, just like Firefox’s “Fill Login” does. Something like this:

+ Bitwarden
  + Fill john.smith (github.com)
  + Fill john@company.com (github.com)
  + ----
  + Copy Username
  + Copy Password
  + ----
  + Generate Password (copied)

(Note that I changed *site (username)* to *username (site)* as well, the latter seeming a much more sensible order especially if “Fill” or “Auto-fill” is prepended.)

Nesting in menus should be kept to a minimum for optimal task efficiency.

**Comment by kspearrin** [comment]
There is a copy username/password for every matching login, so with your example it would beL

- Bitwarden
  - Fill john.smith (github.com)
  - Fill john@company.com (github.com)
  - __
  - Copy Username (john.smith)
  - Copy Username (john@company.com)
  - __
  - Copy Password (john.smith)
  - Copy Password (john@company.com)
  - __
  - Generate Password (copied)

**Comment by kspearrin** [comment]
In that screenshot, the submenu arrows are just hidden by the autofill submenu.

**Comment by chris-morgan** [comment]
Oh, those are further submenus. Got it.

Well then: I suggest flattening all of them and grouping by login.

**Comment by Crocmagnon** [comment]
@kspearrin, if you're talking about the clipboard features I tweeted you, they might already have been merged into FF 61 as I'm now able to paste TOTP code without having to look for it in the extension. You might want to give it a try :)

**Comment by CodingMarkus** [comment]
IMHO there is no need to flatten copy username/password. The 99 out of 100 case is that a user wants the data to be filled. It's okay if I have to go two levels 1% of the time but right now I have to go two levels 100% of the time.

**Comment by CodingMarkus** [comment]
I'm still hoping that this feature is implemented, as when designing UI, one should always design it so that is works well for the 99% case and currently it doesn't. Like I said, there is no need to flatten everything, why not keeping everything as it is and just flatten logins on top? Do you really think anyone would mind? I strongly doubt that, but okay, add a setting. I doubt anyone will use it but allow the user to choose if s/he wants the logins flattened or not.

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

I see that a thread has already been created for this feature request [here](https://community.bitwarden.com/t/browser-context-menu-nesting-structure-is-unnecessary-and-annoying/12532). Please move any future discussion to that thread.

This issue will now be closed. Thanks!
