### ISSUE TITLE
Bitwarden does not sync on Brave

### ISSUE THREAD

**Issue by stephenkru** [bitwarden/browser#708]
I can't get the brave extension to work again. I reset windows and installed Brave fresh 2 days ago and it would not sync. Gives the failed to sync message. Vault tab is empty. Tried clean installs of brave and deleted the local and roaming brave folders, nothing. Site isolation is not enabled. Tried changing my password, setting up a new account, nothing works. Bitwarden works on chrome.

**Comment by HoLeePhuq** [comment]
I AM HAVING THE SAME ISSUE! @jonathansampson

Can you take a look at this?

**Comment by kspearrin** [comment]
This is an issue with Brave, not Bitwarden. Update your Brave to the latest version.
