### ISSUE TITLE
Autofill not populating username when below password

### ISSUE THREAD

**Issue by a-jackson** [bitwarden/browser#709]
The autofill feature does not populate the username field if it is below the password in the DOM. 

Looking at the code [here](https://github.com/bitwarden/browser/blob/master/src/services/autofill.service.ts#L828) it seems to intentionally stop looking once it has reached the password field.

The site I have experienced this on is not public so I cannot link to it but here is a screenshot
![image](https://user-images.githubusercontent.com/2199309/44847270-d53e7e00-ac4a-11e8-8105-f8385e473b06.png)

I tried swapping the fields in the dev tools and it was able to fill in both fields as expected. The field names are Username and Password despite the labels.

I am using Chrome 68.0.3440.106

**Comment by kspearrin** [comment]
This would be expected since we make the assumption that the username field is the last field before the first password field.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
