### ISSUE TITLE
auto-fill option: clipboard is set to 'undefined' every time a website is opened

### ISSUE THREAD

**Issue by SpineEyE** [bitwarden/browser#710]
Every time I open a website (same tab or new tab), my clipboard is filled with the word 'undefined' (without quotes). It doesn't happen when I just open a new empty tab with about:blank.

I have the "experimental" option "Enable Auto-fill On Page Load" enabled. When I disable it, the bug doesn't happen anymore.

Bitwarden version 1.31.2
Firefox Nightly
Arch Linux

Edit: This started some weeks ago, don't remember what version unfortunately. It took some time to narrow it down to this addon and this option.

**Comment by kspearrin** [comment]
I just tested this on Firefox 61 on Windows and wasn't able to reproduce. I'll have to try nightly later.

**Comment by kspearrin** [comment]
Thanks. This is fixed for next version.
