### ISSUE TITLE
BW does not ask if Credentals should be saved (Google Chrome)

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/browser#712]
At **some** websites BW (BitWarden) does not ask if the login data should be saved (the notification at the top is not shown).
Here some URLs as example:

- https://www.google.de
- https://todo.uservoice.com/forums/597175-feature-suggestions

Of cause I can go to the BW toolbar icon and select to add the credentials manually, but here I have to enter the data manually again.
In the notification it would be just one mouse click (increases Usability and UX).

**Comment by OLLI-S** [comment]
Bug entry added: https://github.com/bitwarden/browser/issues/712

**Comment by OLLI-S** [comment]
I have a router and a repeater form AVM and those devices can be configured via a website.
If I enter the passwords of both pages BW does not ask if the login data should be saved.
The URLs are:

- http://fritz.box/
- http://fritz.powerline/

**Comment by OLLI-S** [comment]
The Login in the German version of Todoist is also not stored in Bitwarden:

- https://de.todoist.com/

**Comment by OLLI-S** [comment]
Also not here:

- https://account.elderscrollsonline.com/login

**Comment by OLLI-S** [comment]
@kspearrin Is this the correct place and the correct format to post these issues?
Or should I post one topic for each website separate?

**Comment by kspearrin** [comment]
Yes, this is fine. Thanks for reporting these.

**Comment by OLLI-S** [comment]
Net candidate: the website of Allianz (the largest insurance in Europe):
- https://meine.allianz.de/

**Comment by OLLI-S** [comment]
And an other one:

- https://help.vivy.com/hc/de

**Comment by OLLI-S** [comment]
And an other one (texted in Mozilla Firefox):
- https://todoist.com/ (German UI)

**Comment by OLLI-S** [comment]
Also in the Forums of Fairphone the Credentials are not saved (in Mozilla Firefox)
- https://forum.fairphone.com/
I think they use the same forums software that Bitwarden does

**Comment by OLLI-S** [comment]
Also here:
- https://www.equateplus.com/EquatePlusParticipant/?login

**Comment by xyxzxyz** [comment]
Also https://mail.google.com

I know this one is tricky but LastPass was able detect new login. 1Password use a different approach I think. It puts an icon within right side of password field just like LastPass and gives your an option to save. It was able to save both username and password.

![image](https://user-images.githubusercontent.com/22533296/52530796-931c6c80-2cbf-11e9-922b-49e1ae2a655b.png)

![image](https://user-images.githubusercontent.com/22533296/52530810-e7275100-2cbf-11e9-826c-94c5297c0628.png)

**Comment by OLLI-S** [comment]
How is the progress of this issue?
Because Bitwarden is still not asking if the credentials should be saved for the listed websites.
And it is annoying to add them manually

**Comment by OLLI-S** [comment]
And an other website, where Bitwarden  does not ask if the credentials should be saved (Google Chrome):
https://vulndetect.com/

**Comment by OLLI-S** [comment]
@tgreer-bw
This issue is open for 2 years now, so what should we do?

**Comment by tgreer-bw** [comment]
Improvement is always constant @OLLI-S  :-)

It appears that some of these sites are now using password input/update functions that are more standardized (i.e. now work with Bitwarden)

**Comment by OLLI-S** [comment]
Close the issue?

**Comment by tgreer-bw** [comment]
I think so - we can actually use #320 as a reference.

**Comment by eliykat** [comment]
This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue.
