### ISSUE TITLE
BW does not ask if credentials should be saved (Safari edition)

### ISSUE THREAD

**Issue by drasbeck** [bitwarden/browser#714]
Whenever I create a new account I am not asked to store credentials for the account.

This has consistently been happening to me in Public Beta 9 of macOS Mojave, i.e. Safari 12.0 (14606.1.36.1.9). The same was the case with latest the latest Safari on macOS High Sierra 10.13.6.

Coming from Firefox, where this feature mostly works, I feel this should also be a feature in the Safari extension?

**Comment by kspearrin** [comment]
Can you provide an example website where this happens please?

**Comment by drasbeck** [comment]
I just tried logging in on an unsaved website and the dialog was shown. Adding to that, I must say I have not had this problem since restarting the computer.

I will report back if anything shows up.

**Comment by eliykat** [comment]
Hi @drasbeck, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
