### ISSUE TITLE
Support Yurplan payment form

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/browser#717]
I've encountered this mapping on Yurplan payment form :
- `payment_cc_code` -> Card number
- `payment_cc_date` -> Expiry date
- `payment_cc_ccv` -> Verification code
- `payment_cc_name` -> Holder name

When I tried to autofill, the name was filled correctly but the date was not filled at all and the verification code was filled into the card number field.

From the code I understand that the behavior is logical since `cc-code` is parsed as a "contains" and so matches `payment_cc_code`. What should we do about that ?

I will add `payment-cc-date` to the required field in a PR.

**Comment by eliykat** [comment]
Fixed in linked PR.
