### ISSUE TITLE
Chromium based browsers don't automatically open the extension field to insert the master password

### ISSUE THREAD

**Issue by jppmarujo** [bitwarden/browser#719]
# What should be happening
The same that happens on Firefox. When right-clicking a password field, selecting Bitwarden -> Auto-fill,  clicking on _'the vault is locked'_ should open the extension square on the top right corner in order for the user to input the master password.

# What happens
After clicking on  _'the vault is locked'_ in the right click context menu (auto-fill), nothing happens on Chromium based browsers. The user has to click the extension icon on the top right corner to be able to input the master password.

# Steps to reproduce
On any Chromium based browser (like Chrome or Vivaldi), go to a webpage where you have your password saved on Bitwarden, and make sure the vault is locked.

Right click the field you want to fill, select Bitwarden, then auto-fill, and click on _'the vault is locked'_ . Nothing happens on the extension icon.

**Comment by kspearrin** [comment]
Unfortunately this is not possible to do with the Chrome APIs.
