### ISSUE TITLE
bitwarden does not recognize this as a login

### ISSUE THREAD

**Issue by johnmudd** [bitwarden/browser#72]
Here's the HTML. 
[view-source_str.html.txt](https://github.com/bitwarden/browser/files/714296/view-source_str.html.txt)

**Comment by kspearrin** [comment]
Could you provide the website URL for this login form? The attached HTML is not sufficient for debugging the issue.

**Comment by johnmudd** [comment]
Oh, sorry. It's an internal website.

**Comment by johnmudd** [comment]
Does this help?
![screenshot from 2017-01-18 14 46 49](https://cloud.githubusercontent.com/assets/755393/22080295/0f1841e4-dd8d-11e6-8534-08f24a72c8e4.png)

**Comment by kspearrin** [comment]
If you can just right click that page and save as you should get a proper html file that you can upload here.

**Comment by johnmudd** [comment]
I see now. My initial upload here is fouled up. No wonder it's not useful. 
[login.html.txt](https://github.com/bitwarden/browser/files/714950/login.html.txt)

**Comment by kspearrin** [comment]
This is probably because your intranet site doesn't have a fully qualified domain which the app looks for. Can you give me an example of what this domain looks like? Is it `http://str/verifyLogin.jsp`?

**Comment by johnmudd** [comment]
http://str/index.jsp
http://str/

**Comment by kspearrin** [comment]
Yea, that's what's breaking it. I'll see if I can figure out a fix. Thanks for the report.

**Comment by breamachine** [comment]
I appear to have the same issue for a number of internal systems that use ip addresses or server names rather than domain names, including this one:
https://sl07203:4848/common/index.jsf
Is this the same issue?

**Comment by kspearrin** [comment]
Yes. Non standard Uris like that are all included with this bug.

**Comment by kspearrin** [comment]
This should eb resolved in v1.11.0
