### ISSUE TITLE
chrome crash on right click inside extension

### ISSUE THREAD

**Issue by lexybarton** [bitwarden/browser#721]
##  ISSUE

Chrome [(`69.0.3497.81`)](https://chromium.googlesource.com/chromium/src/+/refs/tags/69.0.3497.81) crashes when I right click inside the Bitwarden 1.31.2 (https://github.com/bitwarden/browser/commit/0b5b46b54c8c1363ef6a8e1215fea3323cb6d42e). extension

## CONDITIONS

- must be logged in the Bitwarden
- right click must be on any listed entry

## SUBJECTIVE

I do suspect a conflict between the extension and some of my settings, other extensions, or less usual network  / system configurations might be causing this. 

## FOLLOW UP

- When I have time I will try to isolate the cause by reducing configurations
- **Hint me** where and how to collect relevant logs, I will gladly do so

- - - 

#### chrome://version/

Google Chrome | 69.0.3497.81 (Official Build) (64-bit) (cohort: 69_win_81)
-- | --
Revision | 032b3ca19e9af20182f9bd03deefc0faf4695558-refs/branch-heads/3497@{#869}
OS | Windows
JavaScript | V8 6.9.427.19
Flash | 30.0.0.154 C:\Users\admin\AppData\Local\Google\Chrome\User Data\PepperFlash\30.0.0.154\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disk-cache-dir="R:\\" --flag-switches-begin --autoplay-policy=document-user-activation-required --enable-fast-unload --history-entry-requires-user-gesture --enable-offer-store-unmasked-wallet-cards --enable-offline-auto-reload --enable-tab-audio-muting --show-saved-copy=primary --enable-features=AppBanners,AutofillExpandedPopupViews,BackgroundVideoTrackOptimization,DesktopPWAWindowing,DesktopPWAsLinkCapturing,ExperimentalAppBanners,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxTabSwitchSuggestions,OmniboxTailSuggestions,PWAFullCodeCache,ParallelDownloading,PasswordExport,PasswordForceSaving,SoundContentSetting,ZeroSuggestRedirectToChrome --disable-features=IPH_DemoMode --flag-switches-end
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default

#### chrome://extensions/?id=nngceckbapebfimnlniiiahkandclblb

property | value
--|--
Version | 1.31.2
Size | 10.9 MB 
ID | nngceckbapebfimnlniiiahkandclblb
```

**Comment by djsmith85** [comment]
I've tried to reproduce this, without any success. 

@lexybarton I'm closing this issue now, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
