### ISSUE TITLE
Safari Extension problem with KDF 

### ISSUE THREAD

**Issue by pilot3090** [bitwarden/browser#723]
I can't login through the Bitwarden Safari extension when I set the KDF iterations to a value higher than 5000. The error is shown in the picture below

![schermata 2018-09-11 alle 18 07 00](https://user-images.githubusercontent.com/43180817/45373409-b1d2e600-b5ef-11e8-9656-09f2e1a2da12.jpg)

**Comment by kspearrin** [comment]
The Safari extension is always 5-6 weeks behind all others in updates due to Apple's terrible review process for the extension gallery. You''' have to wait another 4 weeks or so for version 1.31 before you can use anything other than the default 5000 iterations.

**Comment by pilot3090** [comment]
Oh ok, thank you so much for your answer!
