### ISSUE TITLE
Card last 4 not searchable

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#724]
According to https://help.bitwarden.com/article/searching-vault/

> Indexed Fields
>
>The following fields from items in your vault are indexed and are searchable:
>
>    - shortId - First 8 characters of the item’s id.
>    - name
>    - subTitle - Login username, card last four, and identity name.
> ...

However, the card last 4 is not searchable from within the browser extension (v1.31.2).

This will be very useful functionality when fixed.

**Comment by kspearrin** [comment]
try it with a asterisk: `*1234`

**Comment by setyb** [comment]
1. Yes, that works, but isn't it supposed to be directly searchable without using a wildcard?

2. BTW, I also tried adding `(1234)` to the name field, but that requires entering in a left-paren before each search.  Is their a way to tell lunr to treat parens like whitespace?

**Comment by kspearrin** [comment]
Should all be fixed in next version.

**Comment by setyb** [comment]
Thank you!
