### ISSUE TITLE
Chrome: Extension locks shortly after unlocking

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#728]
My Lock Option is "On System Lock" so whenever I wake my computer up or open Chrome I have to unlock, which I understand and accept. But when I open Chrome, unlock the extension, and either minimize Chrome or otherwise focus on another window it's locked when I come back.

**Comment by kspearrin** [comment]
What are your lock options set to?

**Comment by kspearrin** [comment]
I just tested this and was not able to reproduce it on windows. Maybe try setting it to something else and then back to "On System Lock" to see if that refreshes some bad configuration or something?

**Comment by maxrom** [comment]
I figured out what causes this! It's when something happens to request a UAC approval. I have mine set to the highest "always notify" setting.
