### ISSUE TITLE
Lastpass not importing & properly

### ISSUE THREAD

**Issue by jmauss** [bitwarden/browser#73]
Everything imported from Lastpass just fine, other than the `&` character. This was imported (in all cases) as `&amp;`

Using the chrome extension from the extension store.

Thanks!

**Comment by kspearrin** [comment]
This has been reported before and I believe that it was determined that the encoding of the file was causing the issue. Try opening your CSV and re-saving it explicitly as a UTF-8 encoding and try again.

**Comment by jmauss** [comment]
I did it again using Visual Studio Code and made sure to select UTF-8 at the bottom. Saved it as lastpass_export.csv on the desktop and imported it. Same issue as last time with `&` appearing as `&amp;` as well as the `<` appear as `&lt;`. This IS how it appears in the csv generated by LastPass itself (the code and not the character).

**Comment by kspearrin** [comment]
Can you put together a quick example file with a few sites in it that I can use to reproduce the issue and attach it here?

**Comment by jmauss** [comment]
Won't let me attach .csv here, I will put it in code:

```
url,username,password,extra,name,grouping,fav
https://www.facebook.com/,tester@test.com,J!rlZxaO3X5,,Facebook,Social,0
https://www.reddit.com/,tester,"6t1J,&gt;AVonp",,Reddit,Social,0
https://twitter.com/login,tester@test.com,YnrtAD8Uj3`,,Twitter,Social,0
```

Hope this example is enough...

**Comment by kspearrin** [comment]
So if I understnad correctly based on your example, it looks like this is a problem with LastPass's exporter, rather than bitwarden's importer? Your export file is showing `&gt;`

**Comment by jmauss** [comment]
Yes, that is what I had mentioned in my second comment, that it was LastPass exporting it that way. I posted this issue because I wasn't sure if your import code was parsing through that and fixing it. If it is something you would rather wait and have LastPass fix, I will try to contact them instead.

**Comment by kspearrin** [comment]
I can't really fix it unfortunately. How would I know that someone didn't explicitly have their password with those characters?

**Comment by jmauss** [comment]
Very true, I will bring this up with LastPass. Thanks for your time checking this out!

**Comment by kspearrin** [comment]
Added https://help.bitwarden.com/getting-started/import-from-lastpass/
