### ISSUE TITLE
In Firefox Nightly on Android, bitwarden extension is often infinite spinner, with logcat showing |JavaScript Error: "TypeError: platformUtilsService is null; can't access its "getDevice" property"|

### ISSUE THREAD

**Issue by dholbert** [bitwarden/browser#731]
I use Firefox Nightly with the Bitwarden extension from http://addons.mozilla.org.  I just did a fresh install of both and I logged into my Bitwarden account in the extension.

After restarting Firefox: when I try to use the extension by using the "Bitwarden" menu item (from the Firefox top-right menu on a site where I've got a saved password), I end up just seeing a throbber spin forever in a circle -- it never finishes loading the Bitwarden extension's UI.  Moreover, this goes by in my adb logcat:
````
09-18 14:46:54.429 13372 13396 E GeckoConsole: [JavaScript Error: "TypeError: platformUtilsService is null; can't access its "getDevice" property" {file: "moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js" line: 1300}]
09-18 14:46:54.429 13372 13396 E GeckoConsole: SearchService@moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:1300:9
09-18 14:46:54.429 13372 13396 E GeckoConsole: popup_search_service_PopupSearchService@moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:9603:9
09-18 14:46:54.429 13372 13396 E GeckoConsole: 607@moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:9664:39
09-18 14:46:54.429 13372 13396 E GeckoConsole: __webpack_require__@moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:79:12
09-18 14:46:54.429 13372 13396 E GeckoConsole: checkDeferredModules@moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:46:23
09-18 14:46:54.429 13372 13396 E GeckoConsole: @moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:152:18
09-18 14:46:54.429 13372 13396 E GeckoConsole: @moz-extension://790bfff8-d991-431d-b6e7-6512497d89cb/popup/main.js:1:11
09-18 14:46:54.436 13372 13372 D GeckoToolbar: onTabChanged: LOADED
````

**Comment by dholbert** [comment]
(This doesn't happen every time, but it does happen often. Not sure what precise series of steps causes it.)

**Comment by kspearrin** [comment]
Is this only a problem on android and only on nightly?

**Comment by dholbert** [comment]
I'm not sure. The only other platform where I regularly use the browser-extension is Firefox Nightly on Desktop (where I've never had any issues).

I also use the Android app, and I've never hit an issue like this in that app.

**Comment by dholbert** [comment]
I'm trying the extension on Firefox release for Android, and I'll report back if I hit the error there.

I didn't hit it on my first attempt there. But that might just because I'm getting lucky. (i.e. I also didn't hit it in my second attempt on Nightly, though I did hit it on my first attempt on Nightly, which is what I captured that logcat output from.)

**Comment by dholbert** [comment]
I still haven't been able to trigger the error in Firefox release (62), but I did trigger it again in Firefox Nightly (64) just now.

**Comment by dholbert** [comment]
I looked at the `main.js` whose line 1300 is referenced in the backtrace with the error message, and it's the final line that I'm quoting here:

````js
class SearchService {
    constructor(cipherService, platformUtilsService) {
        this.cipherService = cipherService;
        this.indexing = false;
        this.index = null;
        this.onlySearchName = false;
        this.onlySearchName = platformUtilsService.getDevice() === _enums_deviceType__WEBPACK_IMPORTED_MODULE_2__[/* DeviceType */ "a"].EdgeExtension;
````

It's that `platformUtilsService.getDevice()` call, which is throwing because platformUtilsService is null.

It looks like there's some special-case code elsewhere in this `main.js` file that checks `platformUtilsService` for nullness. Maybe we need that here, too, and some graceful fallback?

**Comment by kspearrin** [comment]
Doing a null check there likely won't solve the problem. There is some larger issue at play that is making platformUtilsService (which is used all over the app) null in the first place. It should never be null.

**Comment by kspearrin** [comment]
I've got Nightly installed on my Nexus 5X and have not been able to reproduce the issue after opening and closing the addon about 5-6 times. Though I am seeing another problem on nightly vs stable: autofill doesn't seem to work for whatever reason.

**Comment by kspearrin** [comment]
Are you using private mode by chance? I was able to get this same error in private mode on desktop.

**Comment by dholbert** [comment]
No, this is in normal browsing mode.

**Comment by eliykat** [comment]
The `Unchecked lastError value` is being tracked in #1208.

As this is an old issue and there have been no further updates, I'm going to close it. However, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
