### ISSUE TITLE
Extension is completely broken in Microsoft Edge on Windows 10 Insider Preview build 17763.1

### ISSUE THREAD

**Issue by trparky** [bitwarden/browser#732]
The BitWarden browser extension is completely broken in Microsoft Edge on Windows 10 Insider Preview build 17763.1. It keeps telling me "Unfortunately this window is not available in private mode for this browser." even though I'm not in a Private window and I have enabled Private Mode access for the extension. You cannot log into your BitWarden account because of this issue, that's the reason why I'm saying that it's "completely broken". With the release of the new Windows 10 version looming on the horizon, this issue needs to be fixed.

![image](https://user-images.githubusercontent.com/32105035/45762939-7b075c00-bbfd-11e8-949b-59853b199be6.png)

I have version 1.32.1 of the extension installed.

**Comment by kspearrin** [comment]
I'm still trying to install a VM with the preview on it. Having issues at the moment.

**Comment by yorickdowne** [comment]
Same on Insider build 18242. This then affects Edge in the soon-to-be-released October 2018 update, and in the 19H1 update.

**Comment by kspearrin** [comment]
I can't even get the "Unfortunately this window is not available in private mode for this browser." problem due to other bugs in Edge. I just opened this one: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/

Please vote on it for increased visibility to MS team.

**Comment by kspearrin** [comment]
Also, I would strongly suggest that you report these issues to MS through the feedback hub in Edge (Settings -> Help & Feedback -> Send Feedback). These are breaking bugs on their side that need to be addressed ASAP if they plan to ship this in October.

**Comment by trparky** [comment]
I voted it up.

**Comment by kspearrin** [comment]
Anyone here want to try to help be debug this more? I can't get debugging at all working on my 17763 VM due to the above linked error so I can't really proceed. Maybe it works for one of you though?

**Comment by ruffy91** [comment]
I have the Edge debugger for the extension running.
If you can give me a line to set a breakpoint in the code I can give you the call stack for it.

**Comment by kspearrin** [comment]
@ruffy91 Are you able to debug dev builds? Or only the production build?

**Comment by ruffy91** [comment]
ATM only the production build.
Where can I get a dev build?
Is it possible to build the extension in Windows Subsystem on Linux and then install it?

**Comment by kspearrin** [comment]
You can build it on any environment with node.js.

Check out the repo and then

```
npm install
npm run build:prod
```

Then side-load the build folder into Edge extensions. You'll need to enable developer mode under windows settings and also `about:flags` in Edge. Feel free to stop by dev chatroom if you want to discuss. https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
Now tracking here: https://github.com/bitwarden/browser/issues/744
