### ISSUE TITLE
Not working on Firefox 62

### ISSUE THREAD

**Issue by kolaente** [bitwarden/browser#733]
When I want to open the panel (via the addon icon in the toolbar) or auto fill in a password if the master vault is locked, it closes directly making it unusable.
It works when I reinstall the addon until I lock the vault again.
We're using a selfhosted version.

Firefox Version 62 Aurora
Bitwarden Server Version 2.2.0
Bitwarden Addon Version 1.32.1

**Comment by kspearrin** [comment]
Linux?

**Comment by kolaente** [comment]
Yes, `4.15.0-34-generic #37-Ubuntu`

**Comment by kspearrin** [comment]
duplicate https://github.com/bitwarden/browser/issues/580
