### ISSUE TITLE
Bitbucket + Huddle password 'leak'

### ISSUE THREAD

**Issue by oldenboom** [bitwarden/browser#738]
When logging into Huddle the password is both copied to the password field as well as the help-popup, immediately showing the password unencrypted. This doesn't happen with 1Password.

Using macOS 10.13.6, Safari 11.1.2 with BitWarden 1.31.2 Safari extension.

**Comment by kspearrin** [comment]
Could you provide a URL where we can reproduce this?

**Comment by oldenboom** [comment]
Easy: my.huddle.net


... sent from my iphone.

**Comment by kspearrin** [comment]
Not able to reproduce. I don't see anything copied to the help popup.

![image](https://user-images.githubusercontent.com/1190944/45977639-36722b00-c018-11e8-912b-e04e4ea7cfb0.png)

**Comment by oldenboom** [comment]
Strange. This is what I get.

Kind regards,

Rembert Oldenboom.

-- 
*Rembert Oldenboom /* Floating Point <https://www.floating-point.nl/>
tel: 06 - 3195 9633 <callto:0631959633>
Cruquiusweg 1 | 2102 LS Heemstede

**Comment by kspearrin** [comment]
Don't see anything. Please attach a screenshot.

**Comment by oldenboom** [comment]
Hi,

I attached a MP4. It got probably filtered.
The MP4 can be seen online here:
https://www.floating-point.nl/tmp/huddle-bitwarden.mp4

Rembert
-- 
*Rembert Oldenboom /* Floating Point <https://www.floating-point.nl/>
tel: 06 - 3195 9633 <callto:0631959633>
Cruquiusweg 1 | 2102 LS Heemstede

**Comment by kspearrin** [comment]
Maybe it is safari specific for whatever reason. I was testing in Chrome on windows.

**Comment by oldenboom** [comment]
Yes, it is Safari specific. That's why I mentioned the Safari version.
With FireFox and Chrome on the Mac it works well.
With Safari no issues with other sites.

**Comment by kspearrin** [comment]
Should be fixed in the next version. Thanks.
