### ISSUE TITLE
Password autofill not working on TreasuryDirect

### ISSUE THREAD

**Issue by AnthonyGiorgio** [bitwarden/browser#739]
When trying to autofill my credentials on the TreasuryDirect site, only the username prompt is handled correctly.  When I am on URL https://www.treasurydirect.gov/RS/PW-Display.do I cannot autofill the "Password" field.  Note that the Username field is filled in on the prior page, and that works perfectly.

The error message from the extension is "Unable to auto-fill the selected item on this page. Copy and paste the information instead."

This is in Firefox 62.0.2 under Linux with v 1.32.1 of the extension.

**Comment by kspearrin** [comment]
Unfortunately I cannot access that page without a user account. If you'd like for us to look at it further, you could need to save the HTML of the page and upload it here.

**Comment by kspearrin** [comment]
According to the HTML posted, there is only a password field. Not sure how the username field you are seeing is loaded. A screenshot perhaps?

**Comment by AnthonyGiorgio** [comment]
The username is loaded on the prior page, and then the password page loads.  It's an odd setup, and was last updated quite a number of years ago.  There's a wacky virtual keyboard you're supposed to use to click the password to supposedly defeat keyloggers, but I prefer to just paste the password from my vault.
![treasurydirect](https://user-images.githubusercontent.com/17408915/46300602-21465080-c572-11e8-8c59-5b7579d82716.png)

**Comment by kspearrin** [comment]
I imagine that they have some kind of preventative measures on the page to prevent typing into the field. This is why you see this virtual keyboard instead. Not really anything we can do I imagine.

**Comment by AnthonyGiorgio** [comment]
Well, the Enpass browser extension pastes directly into the password field, and I remember LastPass doing so as well.  Can't you just modify the field contents?

**Comment by gianlucaborello** [comment]
Autofill in Bitwarden works if I manually edit the HTML from Chrome's inspector and remove the `readonly` attribute in:

```
<input type="password" autocomplete="off" readonly="readonly"...
```

Any chance Bitwarden can work around that?

**Comment by paradoxministry** [comment]
I always do the same thing when I log in as @gianlucaborello , it's just a huge hassle and I think the DOM can be manipulated by Bitwarden to remove the `readonly` attribute.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by ThoolooExpress** [comment]
If you use uBlock Origin (or probably other modern adblockers too but I've only tested it on uBlock Origin), there is a quick-and-dirty workaround. Simply define a custom filter:

```
www.treasurydirect.gov##+js(ra.js, readonly, input.pwordinput)
```

This will remove the `readonly` attribute from the password box, and then Bitwarden will work as expected.

**Comment by Giterd** [comment]
> If you use uBlock Origin (or probably other modern adblockers too but I've only tested it on uBlock Origin), there is a quick-and-dirty workaround. Simply define a custom filter:
> 
> ```
> www.treasurydirect.gov##+js(ra.js, readonly, input.pwordinput)
> ```
> 
> This will remove the `readonly` attribute from the password box, and then Bitwarden will work as expected.

Genius, thanks very much.  Works for Lastpass.  What a clunky system!
