### ISSUE TITLE
Extensions autocloses after a second on Firefox

### ISSUE THREAD

**Issue by Lanseuo** [bitwarden/browser#740]
When I open the browser extension from the icon on the right side of the URL bar, the window becomes visible and I can see the login screen (only master password). But then the extension autocloses after a second, before I can do anything.

I get the following output in the Browser Console:

```
msg.target.ownerGlobal.gBrowser.getTabForBrowser(...) is undefined LoginManagerParent.jsm:135
receiveMessage
resource://gre/modules/LoginManagerParent.jsm:135:25
receiveMessage
jar:file:///usr/lib/firefox/browser/omni.ja!/components/nsBrowserGlue.js:254:15
receiveMessage self-hosted:1031:17
[Show/hide message details.] msg.target.ownerGlobal.gBrowser.getTabForBrowser(...) is undefined LoginManagerParent.jsm:124
receiveMessage
resource://gre/modules/LoginManagerParent.jsm:124:25
receiveMessage
jar:file:///usr/lib/firefox/browser/omni.ja!/components/nsBrowserGlue.js:254:15
receiveMessage self-hosted:1031:17 
```

![screenshot from 2018-09-29 07-50-51](https://user-images.githubusercontent.com/20486366/46241593-73457580-c3bc-11e8-8359-70a034f41de4.png)

But if I open the extension using `Shift + Alt + U`, the extension becomes visible on the left (like bookmarks or history) and I can use the extension normally.

After having logged in using the extension on the left side, I can also use the normal window using the button on the right of the url bar.

I am using Firefox 62.0 (64-bit) on Ubuntu and Bitwarden Extension 1.32.1

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/issues/580
