### ISSUE TITLE
Chrome extension locks after a Windows UAC prompt when set to lock on system lock

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#741]
I opened #728 without realizing what specifically caused the behavior; I thought it was just if I left the computer unattended for a while but not long enough to sleep. But I realized that it's actually consistently happening when I do something that causes a UAC prompt.

**Comment by kspearrin** [comment]
Unfortunately this is not something we can change. The browser tells us when the lock event occurs and we respond accordingly. If a UAC event triggers the lock event in chrome (`chrome.idle.onStateChanged`), the extension will lock. It would need to be reported upstream to Chromium if that is not the expected functionality.
