### ISSUE TITLE
Auto-fill isn't working with multiple login data for same hostname.

### ISSUE THREAD

**Issue by NamruEU** [bitwarden/browser#742]
Hi,
first thank you very much for you amazing software.

Maybe I have 2 problems.
1. I have multiple accounts for a webmail provider. This results that auto-fill isn't working. One is the main account but sometimes I need to login to the other accounts. From my point of view this can be fixed with implementation of a priority number for each login data (URL) (eg. the smallest number will be used for auto-fill). Other login data can be provided with an modified username field that are extended by a drop down list sorted by the priority number from login data.

2. My second problem is that autofill isn't working If you have multiple login data but seperated by subdomains or URLs. For example site hosting or mailing. The browser extention gives me all my accounts for all sub-domains and different URLs. Maybe this can be fixed with are more restricted hostname/URL filtering.

Thanks in advance for reading and checking :)
br Namru

**Comment by kspearrin** [comment]
Please see https://help.bitwarden.com/article/uri-match-detection/
