### ISSUE TITLE
Bitwarden fails to Autofill on boostmobile.com with Firefox

### ISSUE THREAD

**Issue by lhorace** [bitwarden/browser#743]
I've been using you guys for 6 months but there is times I just wonder. Autofill doesn't work on this page on Firefox version 62.0.2 (64-bit) on ArchLinux https://myaccount.boostmobile.com/sign-in.html?intnav=UtilNav:SignIn

I want to give feedback:

On my Android phone, I am pretty surprise, it works pretty well when I expect it to fail. Which does on occasion. For me, Android 7.1.1, when it switch to login screen to sign in, click the account (the account associated with the login), goes back to the App. The App refreshes, rinse, wash, repeat. Overall, I am happy with it, so not major complaints. 

When autofill doesn't work as expected, I just think Lastpass, I never had that problem. :( Why upgrade to premium?

**Comment by harogaston** [comment]
Well both inputs have very non standard ids and types:
a. id=phoneID type=tel
b. id=pinID  type=te

**Comment by lhorace** [comment]
Thanks, I'm going to close this ticket, it's been months. I don't use that site that often for it to be bother.
