### ISSUE TITLE
Edge Extension Issues with October 2018 Windows 10 Update

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#744]
The October 2018 update for Windows 10 (1809) introduces bugs with browser extensions in Edge (44.17763.1.0) when trying to use Angular apps in the popup window (browserAction). Because of these regressions, Bitwarden is no longer usable in the popup window from the toolbar in Edge 44.17763.1.0 (or greater).

We have submitted bug reports to Edge's public issue tracker here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/ . To date, we have not had a reply from the Edge team to acknowledge the issue or provide a workaround. 

- Please [vote on the issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/) to help bring attention to the problem. Click the "+ Me too" button under the "Reports" header on the right side.
- Please submit an issue using the Feedback Hub feature in Edge under Options -> Help & Feedback -> Send Feedback to help bring attention to the problem.

The only workaround we have discovered is to not use the _popup window_ from the toolbar (browserAction) and instead open the extension to a new _pop out window_. The problem does not occur in the pop out window, however, this window has limited functionality in regards to interacting with your current browser tab and providing autofill selections. To perform autofills, you will need to use one of the [other methods available](https://help.bitwarden.com/article/auto-fill-browser/), such as keyboard shortcuts or the right-click context menu.

If the problem is fixed or another workaround becomes available, we will update the extension as soon as possible.

**Comment by kspearrin** [comment]
Opened an issue with Angular to see if they have any suggestions for a workaround: https://github.com/angular/angular/issues/26508

**Comment by isaac2004** [comment]
Does this have anything to do with the extension ALWAYS popping into a new Window? This is a pain because auto populate does not work because of this.

**Comment by kspearrin** [comment]
> The only workaround we have discovered is to not use the popup window from the toolbar (browserAction) and instead open the extension to a new pop out window. The problem does not occur in the pop out window, however, this window has limited functionality in regards to interacting with your current browser tab and providing autofill selections. To perform autofills, you will need to use one of the other methods available, such as keyboard shortcuts or the right-click context menu.

**Comment by corbob** [comment]
I think with the announcement of Edge switching to Chromium base it's general consensus that this will not be fixed except by a Chromium switch. It's a shame as I wanted to give Edge a go, but this made it unusable.

**Comment by AlbertoPa** [comment]
In the current status the Edge extension is only partially functional. I am unable to use it on most of my sites, if an automatic fill of the matching credentials is not done. If this issues is not going to be addressed, I feel it is misleading to leave the extension available (basically the browser is not supported).

**Comment by kspearrin** [comment]
@AlbertoPa The next major update to edge will see better support from Bitwarden. You can try it here: https://www.microsoftedgeinsider.com/en-us/

**Comment by isaac2004** [comment]
I am using Insider Edge with this extension and the experience is the exact same as Chrome

**Comment by AlbertoPa** [comment]
True but the expectation should not be a user adopts a development version of a browser for a paid product, hence my comment.

**Comment by SuzukiStumpy** [comment]
Any timeline on when this issue is likely to be fixed?  It's April 2020 now and still the browser extension appears in an popup window.  (Microsoft Edge 44.18362.449.0)

**Comment by corbob** [comment]
@SuzukiStumpy this issue has been fixed in the latest version of Microsoft Edge: https://www.microsoft.com/en-us/edge (note this is **not** the same Edge that you already have installed, and so does not come through Windows Update)

**Comment by SuzukiStumpy** [comment]
> @SuzukiStumpy this issue has been fixed in the latest version of Microsoft Edge: https://www.microsoft.com/en-us/edge (note this is **not** the same Edge that you already have installed, and so does not come through Windows Update)

Ahh ... that'll explain it then  :)   Thought I'd read somewhere that the new Edge was in the standard WU pushes.  Downloading it now instead.  Thanks.

**Comment by corbob** [comment]
> 
> 
> > @SuzukiStumpy this issue has been fixed in the latest version of Microsoft Edge: https://www.microsoft.com/en-us/edge (note this is **not** the same Edge that you already have installed, and so does not come through Windows Update)
> 
> Ahh ... that'll explain it then :) Thought I'd read somewhere that the new Edge was in the standard WU pushes. Downloading it now instead. Thanks.

It looks like it will be coming through [Windows Updates](https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/) (or possibly Feature Upgrades?), however based on the fact that I'm on Insider Preview Fast ring and currently running version 2004 with the old edge I couldn't take a guess at when it'll actually roll out.
