### ISSUE TITLE
Firefox on Ubuntu - can't log in

### ISSUE THREAD

**Issue by benshep** [bitwarden/browser#745]
Running Firefox 62.0 64-bit on Ubuntu 18.04.1. When I click the Bitwarden button in the Firefox toolbar, the login window shows for an instant and then disappears. I can log in from the sidebar OK, and when I'm logged in the menu displays properly from the toolbar button.

I've never had this issue on Firefox on Windows, or on my other Linux PC (which runs Lubuntu).

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/issues/580

**Comment by benshep** [comment]
Sorry. I did search but obviously not hard enough!
