### ISSUE TITLE
Bitwarden browser plugin doesn't export Collections or Card data

### ISSUE THREAD

**Issue by alexhk** [bitwarden/browser#747]
I have 5 entries of the type card and 17 logins stored in a "Family Collection" (to share with family).

When the data is being exported as CSV via Settings > Tools > Export Vault I am missing these 17 logins and the 5 cards.

I am not sure if anything else is missing. Is there a way to make the Bitwarden (Chrome) plugin export all data?

Normal logins and secure notes seem to be exported fine.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/browser/issues/533
