### ISSUE TITLE
Password History Lost if Vault Locked

### ISSUE THREAD

**Issue by discoli-zz** [bitwarden/browser#748]
Hello, so earlier today I was signing up to the service, copied the password and signed in and didn't bother saving it as it was temporary, then I copied a URL and lost the password, so I though to check the password history, but the vault was locked, so I unlocked it and the password wasn't there.

**Comment by kspearrin** [comment]
I believe that this is the intended behavior at the moment. Password generator history is only saved for the current session. If you lock the app, it is cleared. Maybe it should be changed to the login session and only clear when logging out.

**Comment by kspearrin** [comment]
Nevermind. I just tested this and it was not cleared when locked. It is only cleared when logging out.

**Comment by fabianski7** [comment]
so, you could add an option to clear when you leave the section.
