### ISSUE TITLE
Issue on BananaRepublic

### ISSUE THREAD

**Issue by CSharpFan** [bitwarden/browser#749]
Hey! 

While my wife was shopping (oh dear) she complained that she couldn't log in on BananaRepublic.

First of all: for some reason BitWarden paints something around the username & inputbox:

![image](https://user-images.githubusercontent.com/864376/46577279-42ef6f80-c998-11e8-9ec8-ba49ac132918.png)

Notice the 3, which is weird, I don't have 3 passwords. 

This does not show up when disabling the extension and doing a hard refresh, or running in Incognito.

![image](https://user-images.githubusercontent.com/864376/46577321-e3925f00-c999-11e8-883f-cc2adf39200c.png)

Then the log-in fails. It succeeds if I disable BW and hard-refresh the page. 

I have looked at the data that gets posted. On the broken one:

![image](https://user-images.githubusercontent.com/864376/46577345-44219c00-c99a-11e8-94eb-731ea10f9232.png)

On the non-broken one:

![image](https://user-images.githubusercontent.com/864376/46577352-5bf92000-c99a-11e8-937b-e5b98384d90d.png)

Please ignore the extensions. I tested this before on another laptop where I removed all extensions except BW. Just didn't take any screenshots there.

**Comment by kspearrin** [comment]
> First of all: for some reason BitWarden paints something around the username & inputbox:
> Notice the 3, which is weird, I don't have 3 passwords.

Looks like LastPass to me. Bitwarden doesn't do that.

**Comment by CSharpFan** [comment]
You're right. Going further, this isn't Bitwarden. The boxes are painted by uBlock Origin (!)
