### ISSUE TITLE
Bitwarden performance is degraded in Edge October 2018 update

### ISSUE THREAD

**Issue by lhorace** [bitwarden/browser#750]
I'm not sure if any of the developers are aware but the performance on Edge 1809 update is dismal. From what I understand from #744 issue, Edge introduced a lot regressions which could be the cause of the downgraded performance. Rendering and searching performance is dismal for everyday use compounding that one needs to open a browser tab/window to view your vault.

**Comment by kspearrin** [comment]
I would not be surprised if there are other regressions that haven't been discovered yet, including this one. Not sure what we could do. There are already tons of hacks in the extensions to deal with Edge issues.

**Comment by lhorace** [comment]
I already responded to Edge issue and submit feedback through the feedback hub. It appears your ticket got assigned, that's great news, and see when that get's fixed. If that improves anything else.

**Comment by kspearrin** [comment]
We'll see. I have about 10 other tickets open on the Edge issue tracker, some dating back over a year that have been assigned and some even confirmed, but nothing has been done yet. :-/

**Comment by kspearrin** [comment]
Unfortunately I only see a way to filter by "issued created by me", which doesn't give a public URL that would work.

**Comment by lhorace** [comment]
That's fine, I'll do it the hard way, and btw it seem you putting in a lot effort. Great Job

**Comment by kspearrin** [comment]
Here ya go:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16906063/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18386569/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13760501/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12377248/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12236493/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12227553/

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18153422/
