### ISSUE TITLE
URL Starts With does not seem to work

### ISSUE THREAD

**Issue by RickkeeC** [bitwarden/browser#752]
Hello, With LogMein, I get hundreds of choices when trying to login.  Should the begins with only show the items that "begins with"   
Uri 1
https://acme-dc1-
Starts with option

But it still shows all of them.
![2018-10-10 14_15_45-window](https://user-images.githubusercontent.com/40076667/46757151-4dab4c80-cc97-11e8-96c8-f28799955c90.png)

**Comment by kspearrin** [comment]
What is the URL of the LogMeIn window?

**Comment by RickkeeC** [comment]
Hi, every one is different, this is an example:

https://gator-dc1-skrgyvasdf.app04-01.logmein.com/?rawtnl=2484bf497_0&gwsid=_ptg1yvkHn7asdfgz3OOObxPKW6R4oL8

Rick

**Comment by kspearrin** [comment]
You would need to specify a more strict rule on all of those items. I imagine they are all still set to "default".

**Comment by RickkeeC** [comment]
Hello:
Thank you for the update, it is appreciated.
I don’t understand the logic, lots of editing to get it to work the way I want, but I will give it a try and revert if still having a problem.

Since it is not a bug, but ‘by design’, perhaps worthy of a feature suggestion that STARTS WITH  would be changed to override DEFAULT and only present only the items that START WITH.
I will try CONTAINS, but am assuming CONTAINS is programmed the same way and would be more intuitive if it only displayed items that are CONTAINED.

Rick Cassel

R. A. Cassel & Associates
Professional IT Management
Office: 407.599.5890
EMail: rick.cassel@racassel.com
Visit:  www.racassel.com

**Comment by kspearrin** [comment]
There is a feature request here for changing the default: https://community.bitwarden.com/t/option-to-change-the-default-match-detection-for-uris/455
