### ISSUE TITLE
Overlay UI partly broken in version 1.32.5 on Microsoft Edge

### ISSUE THREAD

**Issue by adrianghc** [bitwarden/browser#753]
The overlay UI is broken in some scenarios when interacting with entries. One possible way to reproduce is e.g. by opening an entry and closing it. Doing this results in the blue header appearing twice, and the rest of the UI not working correctly - e.g. not reacting to clicks, though hovering shows a reaction. This happens when opening the overlay in a separate window as well.

**Comment by djsmith85** [comment]
Closing this as we do not support MS Edge versions pre Chromium. If it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
