### ISSUE TITLE
Can't save/autofill google/gmail credentials with BW

### ISSUE THREAD

**Issue by Mokubyow** [bitwarden/browser#759]
Hi Kyle,

I just started using BW, its pretty awesome, thanks for creating it!

The first account that I wanted BW to save a password for was my Gmail/overall google account. The BW Chrome extension doesn't seem to know how to pick up or insert passwords into this particular google sign in form:

![image](https://user-images.githubusercontent.com/4634087/47229740-72d64400-d396-11e8-8e3d-07492e654eb9.png)

**Comment by kspearrin** [comment]
I just tested the same form logging into Gmail and it seems to autofill it just fine. Not sure what the difference is.

**Comment by Mokubyow** [comment]
Wow that is very weird are you using Chrome?

**Comment by kspearrin** [comment]
Unfortunately we cannot detect adding new logins if there is not a username and password field on the same page. It wont work when it is broken into multiple steps like this Google form.

**Comment by xyxzxyz** [comment]
Anyway to to get Bitwarden to detect it at all?

![image](https://user-images.githubusercontent.com/22533296/52526911-e1584e00-2c74-11e9-96e9-001812550bc2.png)

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known issue that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this post: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
