### ISSUE TITLE
Tracking user activity

### ISSUE THREAD

**Issue by mtahmed** [bitwarden/browser#76]
According to this comment on an article advocating using bitwarden, google analytics is apparently used to track user activity?

https://medium.com/@chihchun/thanks-for-disclosing-the-issue-of-lastpass-5308ffbd93f#.hn73mdhik

Any thoughts on that? I haven't dug into code myself yet.

**Comment by kspearrin** [comment]
Hi, thanks for the link to the comment. I have replied there.

Google analytics can be easily turned off by the user by navigating to Settings > Features.

**Comment by mtahmed** [comment]
What are Google Analytics used for anyway?

**Comment by kspearrin** [comment]
Google analytics allows us to anonymously track how users are using parts of the application. For example, we can learn how long users spend on the registration page, how often users use the autofill features, etc. None of the analytics data can be tracked back to you specifically. It is all aggregated together in metrics that help us learn how certain features are being used in the app.

**Comment by Primokorn** [comment]
Actually YOU only have anonymous data but GOOGLE has more information on bitwarden users.

**Comment by cwmke** [comment]
You might want to consider something like [piwik](https://github.com/piwik/piwik) which is self-hosted and should have similar capabilities.

**Comment by alexandreroberts** [comment]
I wasn't able to find the option to disable Google Analytics. I looked under "Settings > Features" but also looked through the other options. Has this option moved?

**Comment by kspearrin** [comment]
Analytics are no longer in the apps.

**Comment by alexandreroberts** [comment]
That's wonderful news! Thank you.

**Comment by hypeJunction** [comment]
Has it been added again? I see requests to Google being blocked by my tracker protection
