### ISSUE TITLE
Autofill bug in Android

### ISSUE THREAD

**Issue by hemlok89** [bitwarden/browser#760]
Hello,
I am using Bitwarden on my phone running LineageOS 14.1 (Android Nougat). I am using Chrome as my browser. If a login is detected in a page, there are two different outcome is occurring. If the cursor is in username field, bitwarden in detecting com.android.chrome ie. nothing. But when the cursor is in password field, the proper login is detected.

**Comment by kspearrin** [comment]
Does this happen on any website or some particular website? Could you provide an example?

**Comment by ponchofiesta** [comment]
I sometimes have the same problem. I just tested it on:
- https://heise.de: worked
- https://computerbase.de: didn't work - "Es befinden sich keine Zugangsdaten für com.brave.browser in deinem Tresor." (in english: no credentials for com.brave.browser). Then go back, focus the password field and it works. But: going back again and focus username field again: works too.

I'm using Brave browser which is based on Chromium but I had the same with Chrome.

**Comment by hemlok89** [comment]
Sorry, I did not follow up with this thread. This issue is hard to reproduce as it happens randomly. But here is a link to Slimjet Forum [login page](http://www.slimjet.com/en/forum/ucp.php?mode=login&sid=5968597fb3dc8cca510d844b1a12dfff). Sometimes the issue happens, other times does not.

**Comment by ItsEcholot** [comment]
I can confirm this behaviour it seems to be rather random on which websites it happens and when it happens... Of course this doesn't help finding the source of the problem at all 😒

**Comment by dhilgarth** [comment]
I also have this problem. Very frequently. If it helps, I can run a special build which logs additional info.

**Comment by pannal** [comment]
I also have this issue, since day one. Do you guys use SwiftKey?

**Comment by dhilgarth** [comment]
I have since seen this more seldom, however, I often see it if a browser is hosted inside an app, e.g. when I click on a link in Slack and it opens inside the app.

**Comment by aunger** [comment]
I see this problem on my low-memory-and-slow LG Stylo. I assume that it has something to do with BW (or Chrome) being unloaded _during_ autofill due to low memory.

I'd love to see this fixed. Thanks!
