### ISSUE TITLE
Having info typed backwards

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#763]
I don't know how to replicate it but I remember I had an issue where my information was typing backwards. I was wondering if anyone else has had this problem or if it was recently fixed? I am using the firefox extension.

**Comment by kspearrin** [comment]
Not really sure I understand what you are describing.

**Comment by Gameplet3** [comment]
Instead of the typing cursor moving to the right it just stays on the left, and the words are typed sdrawkcab

**Comment by kspearrin** [comment]
Sounds like your device is going into RTL mode or something.

**Comment by eliykat** [comment]
It appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
