### ISSUE TITLE
Autofill Hotkey doesn't work on Chrome (MacOS Mojave)

### ISSUE THREAD

**Issue by ln206** [bitwarden/browser#764]
So for some reason, the autofill hotkeys (cmd + shift + L) work fine on Safari and Firefox but not on Chrome. I even tried to change the hotkey in Chrome's extensions page, but it didn't work. Anybody know why?

**Comment by kspearrin** [comment]
Is something else squatting on the hotkey you are trying to use?

**Comment by ln206** [comment]
No, I don't think so.

**Comment by gmcinalli** [comment]
I've tested it in my Mojave and it works perfectly on Chrome.

**Comment by ln206** [comment]
Thank you for your info. I just can't figure out why it doesn't work on mine.

**Comment by ln206** [comment]
I just reinstalled extension on Chrome, and it works now.

Thanks, everyone.

**Comment by gmcinalli** [comment]
Can you post a screenshot of the Chrome Extensions keyboard shortcuts
section?

Il giorno mer 31 ott 2018, 17:40 Long Nguyen <notifications@github.com> ha
scritto:
