### ISSUE TITLE
Bitwarden seems to have bad `Energy Impact` at page load as reported by Firefox's new about:performance page

### ISSUE THREAD

**Issue by FatOrangutan** [bitwarden/browser#769]
Every time I reload a tab or open a new page or switch to a different tab, Bitwarden briefly rises up to the top of the table with `Energy Impact` in the `Medium` range. This seems a bit unreasonable to me given that:
1) I have `Enable Auto-fill On Page Load` unchecked. I'd expect Bitwarden to lay back and wait for the page to finish loading instead of doing something that might negatively affect page load speed.
2) In these cases, Bitwarden's energy usage surpasses that of nearly all other extensions in my browser, including e.g. uBlock which needs to filter every single network request.
3) I can reproduce the issue with the following quick test:

-on a new Firefox Nightly profile, install Bitwarden. Close the sidebar that it opens. Don't login. Open `about:performance` in a tab. In a new tab, do a Google search for `test`. Switch back to the `about:performance` tab, click the Bitwarden row so it gets a highlight and is easy to track. Right click the Google tab (without switching to it), click Reload. Observed behaviour: at its hightest, Bitwarden had an energy impact of 2.55.
-Uninstall Bitwarden. Restart Firefox just in case. Install LastPass. Repeat the same test, while ensuirng you never login to LastPass either. At its highest, LastPass had an energy impact of 0.4.
-Repeat test with 1Password X. At its highest, 1Password reported 0.22.
-I can reproduce same high (both in the absolute sense, and also compared to other p/w managers) CPU numbers in Chrome + Bitwarden' Chrome extension. I'm not even logged into Bitwarden!

**Comment by kspearrin** [comment]
Try disabling "Add Login Notification" and "Change Password Notification". Does the problem go away then?

**Comment by FatOrangutan** [comment]
Sorry but it doesn't seem to have helped. I'm getting pretty much the same readings.

**Comment by kspearrin** [comment]
Given that I don't have any information about how this new performance page works and how its metrics are computed I am not sure what I can do to debug this problem. Or even determine if it is a problem. What I can tell you is that Bitwarden does various things whenever you change tabs, refresh tabs, etc to update the state of the extension. It seems that is probably what is registering on this new performance page.

Are you noticing any performance issues on your device while using Bitwarden?

**Comment by kspearrin** [comment]
I am also seeing some of my other extensions "spiking" when I reload the tab, such as the Tree Style Tabs extension that I use. I assume that this means it is doing some work during that operation to (which would make sense).

**Comment by FatOrangutan** [comment]
>Or even determine if it is a problem.  
  
Did you compare a logged out Bitwarden vs a logged out, say, 1Password X, both on Chrome? Shift+Esc opens Chrome's Task Manager.

>Are you noticing any performance issues on your device while using Bitwarden?

Not in particular.

**Comment by Ilmanfordinner** [comment]
Hey, just wanted to mention that I have the same issue. Here's a screenshot of my about:performance

![image](https://user-images.githubusercontent.com/10760984/58553017-b0902a80-820b-11e9-9978-2e4357003143.png)

It's really annoying when I'm on battery for the CPU to use an extra 1.5 watts just for having BitWarden on.

**Comment by Crocmagnon** [comment]
The number in the Energy impact column doesn't seem to have a unit related. Are you sure it's in Watts ?

**Comment by serovar** [comment]
Any news on this issue?

**Comment by diego-treitos** [comment]
I am having the same problem. However, if I check the "Disable Context Menu Options" box, the situation seems to improve a lot. Can anybody else also confirm this?

**Comment by DarkMio** [comment]
I am impacted by this problem in general. It seems to extend just page loads, where the Bitwarden browser addon seems to keep the CPU on high frequency, causing my laptop to heat up. Disabling the addon keeps the system cool and thus less noisy.

**Comment by JaggedJax** [comment]
For me Bitwarden is by far and away the highest thing on the list. Everything else is always in the single digits, but Bitwarden has a baseline of 12 and is regularly above 50 every few seconds. This happens even when I'm just sitting on the Task manager tab and not switching around or doing anything else.

![image](https://user-images.githubusercontent.com/553588/86403814-4abe6f80-bc63-11ea-8447-c214294ec6f2.png)

I haven't played with any settings yet as I just found this issue here, but I'm not sure what it's doing in the background all the time

**Comment by ValentinVERGEZ** [comment]
Hello,

I experience the same issue.  
I did try to toggle all the options one by one and found that 'Disable Context Menu Options' has a visible impact.  
I'm able to reproduce it with all options enabled except 'Enable Auto-fill On Page Load' (all options unchecked) and then switching 'Disable Context Menu Options' on and off.  
The energy impact goes from 0.5-2 when disabled to 1.5-10 when enabled.

**Comment by diego-treitos** [comment]
Yes, I can confirm that is the behavior. The "Context Menu" has a big performance toll. I already experienced that [a year ago](https://github.com/bitwarden/browser/issues/769#issuecomment-566205051). No fix so far...

**Comment by btdmaster** [comment]
Could the "Context Menu" default to off temporarily until this is fixed? I only noticed it existed a few months after I installed the extension, and I think the hotkeys are more efficient regardless.

**Comment by DevJackSmith** [comment]
my Firefox was running high CPU until i started looking into it and shutting off extensions one by one. Finally found that Bitwarden was the culprit. Really wish this would be fixed or at least disabled Context Menu option by default.
