### ISSUE TITLE
Safari TOTP not copying automatically when using keyboard fill shortcut

### ISSUE THREAD

**Issue by compgeek35610** [bitwarden/browser#770]
Hi there,

I’ve run across a bug in the bitwarden plugin for Safari (12.0.1) on macOS.

When filling passwords by using the keyboard shortcut (Cmd + / ) the TOTP code generated does not copy to the clipboard.

On the same sites, filling by clicking onto the extension and choosing the account works as expected and does copy the code. Tested on Chrome and the behaviour is as expected when using keyboard or mouse to fill.

Is it possible to get this fixed? I much prefer the keyboard shortcut to invoke the fill, but being broken for all my 2fa sites takes all the fun out of it!

-Brad

**Comment by kspearrin** [comment]
Unfortunately, in Safari we can only invoke clipboard copying when an action is performed from the popup window.

**Comment by developmentMLPN** [comment]
Coming from Enpass I'm surprised to hear that. I used exactly the same mechanism there with no problem . Hotkey shortcut and then paste the TOTP (it was added to the clipboard). Do you know what's the difference ?

**Comment by kspearrin** [comment]
I am not sure how Enpass works, but I imagine is is paired with a native desktop application that is probably handling these type of functions. Bitwarden's browser extensions function independently and do not directly communicate with a native desktop application. Therefore, we are at the mercy of functions that the browser APIs offer.

**Comment by developmentMLPN** [comment]
OK. I can confirm that idd Enpass browser plugin works by connecting to a native app.
Thanks explaining.

Also tacking the information you passed into consideration i think you can close this ticket.
