### ISSUE TITLE
TOTP not copied to clipboard when using auto-fill

### ISSUE THREAD

**Issue by chrfle** [bitwarden/browser#779]
When using the auto-fill feature (which is fantastic) the TOTP is not copied to clipboard when you log in.

If I fill out login manually by clicking on BW, it works as expected.

Using firefox plugin.

**Comment by kspearrin** [comment]
> If I fill out login manually by clicking on BW, it works as expected.

Can you explain what you mean here?

**Comment by chrfle** [comment]
If I in the first page that asks for username/password, click the bitwarden icon at the top right of my browser and then click the appropriate login the field are filled in and the TOTP is placed in my clipboard.

But If I use "Enable Auto-fill On Page Load" from the bitwarden options, the username/password is automatically inserted when I visit the page. But the TOTP is not placed in clipboard.

**Comment by kspearrin** [comment]
This is expected. We don't auto-copy the TOTP code on page-load autofills. TOTP copy will only occur when you perform explicit autofill actions.

**Comment by chrfle** [comment]
Could you explain the rationale for this decision? Why would I not want it copied when using auto-fill?
Could it become a user setting?

**Comment by kspearrin** [comment]
Since autofill on page load can happen at any point in time when a password field is encountered on a website we don't want to arbitrarily override a user's clipboard contents with a TOTP code that they may not need. This is why it only occurs when you manually invoke an autofill action.

**Comment by chrfle** [comment]
Fair enough, thanks for taking the time to answer.

**Comment by maxrom** [comment]
Thanks Kyle. That makes perfect sense and I thought before even when I used the key shortcut it still wasn't copying, which is the perfect compromise, but I find now that it is after all.
