### ISSUE TITLE
Cannot login on OSX Mojava Firefox plugin

### ISSUE THREAD

**Issue by madchap** [bitwarden/browser#780]
Freshly installed OS and plugin. Can't login onto my private Bitwarden URL. 
100% reproducible.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/5468769/48659053-fcd40400-ea4b-11e8-8316-cb7d80a76292.png">

Thanks for your help.

**Comment by kspearrin** [comment]
Sounds like there is a problem with your server. What is its status?

**Comment by madchap** [comment]
Just fine. Can login from Android phone and Linux FF and see my stuff. I will install chrome on osx and give it a shot there.

I will provide some browser version info when I can. Meanwhile, if any specific info/debug/log can help, let me know.

[Sent from mobile device]

________________________________

**Comment by madchap** [comment]
Alright, it was me being dumb.. Wrong subdomain, duh.
