### ISSUE TITLE
Styling issue on Chrome (dark theme)

### ISSUE THREAD

**Issue by Zaczero** [bitwarden/browser#781]
I'm using the dark theme of Bitwarden on Chrome *(latest)* and there is that one thing that drives me crazy. Basically you can see 2px height white bars on top and bottom of the extension's pop-up.

I've checked that on Firefox and it's filled as it should *(no white bars)* so it's only something with Chrome's default styling.

![white bars preview](https://i.gyazo.com/f5d56e74154308f018c042219dc52c4c.png)

**Comment by kspearrin** [comment]
Unfortunately I don’t know a way to fix that.  It’s part of the native UI it seems.

**Comment by Zaczero** [comment]
Ugh, I noticed it on other extensions too 👎
That's looking so ugly #chrome_fix
Loving Bitwarden tho <3
