### ISSUE TITLE
TOTP code not copying after autofill on Twitter.com

### ISSUE THREAD

**Issue by maxrom** [bitwarden/browser#784]
When I sign into Twitter.com in Google Chrome and my credentials autofill, my paste is still whatever the last thing I copied was. This is the only website I know acting like this for me.

**Comment by kspearrin** [comment]
What method did you use to autofill?

**Comment by maxrom** [comment]
Well they're just showing up so I'm assuming it's due to the "Enable Auto-fill On Page Load" option.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/779
