### ISSUE TITLE
Doesn't correctly fill tsp.gov username

### ISSUE THREAD

**Issue by backerman** [bitwarden/browser#786]
When filling in login information on the front page of tsp.gov, the password is entered in both the username and password spaces.

Observed in BW v. 1.34.0, Firefox 63.0.3, Linux x86_64.

**Comment by kspearrin** [comment]
This would be expected since the username field is marked as type password. To work around the problem you can use a custom field to target the correct field for your username.

https://help.bitwarden.com/article/custom-fields/
