### ISSUE TITLE
Autofill fails for www.s-pankki.fi

### ISSUE THREAD

**Issue by vatjjar** [bitwarden/browser#787]
Just tried to access Finnish banking site https://www.s-pankki.fi and tried to save credentials to bitwarden. When I try to login using autofill, the process fails.

What bitwarden does it actually fills the saved password for both username and password. Username has to be entered manually.

Tested with Chrome 70 and Firefox 61 on Win 10 and Ubuntu Linux. Browser extension version 1.34.0

**Comment by kspearrin** [comment]
Same issue as https://github.com/bitwarden/browser/issues/786
