### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by gcstang** [bitwarden/browser#79]
Upon auto logout you're only asked for the master password to log back in when Two Factor is enabled.

If you manually logout then you're asked for the master password and authentication token.

This seems broken, it should ask for both if I'm asking it to automatically log out.

**Comment by kspearrin** [comment]
The feature is for auto-locking the app, not logging out. Two factor is only meant to be when logging in, not unlocking the application.

**Comment by gcstang** [comment]
Ok I can understand that view point.
It just seems to me that it defeats the purpose of having 2factor if my password has been compromised.  If I have a browser on another computer that has locked the application only my password is needed to obtain access.

**Comment by kspearrin** [comment]
That is more of a use case of deauthorization any logged in sessions.
