### ISSUE TITLE
Firefox toolbar button briefly opens window to login then closes

### ISSUE THREAD

**Issue by strawsa** [bitwarden/browser#790]
FF 63.0.3
Ubuntu 18.04

The overlay that appears from using the BItwarden toolbar button crashes every time you open it to login to the database. Using Alt+Shit+U (sidebar) works fine, so it's just the overlay.

I've cleared my FF profile and restarted clean but the issue continues.

This is only for the initial password entry. After I use the sidebar to login, the Bitwarden button works fine.

**Comment by kspearrin** [comment]
#580
