### ISSUE TITLE
Unlock vault password field should autofocus when choosing "uinlock vault"

### ISSUE THREAD

**Issue by Pajn** [bitwarden/browser#791]
Reproduction:

- Use Firefox
- Have vault locked
- Focus a login field
- Use the menu key to "right click" with the keyboard
- Use arrow keys to go to Bitwarden > Unlock vault
- Press enter
- Now you must use the mouse to focus the Bitwarden Vault Unlock Password field.

If the field was autofocused when opened, the unlock flow would work with just a keyboard

**Comment by kspearrin** [comment]
This should already be the case. I just tested on Firefox in Windows 10 and it worked as expected.

**Comment by Pajn** [comment]
Hmm, I can reproduce it every time in Ubuntu. I will try to see if there is some conflict or other problem, otherwise it might be OS specific (different timings/event order or something like that maybe?).

**Comment by djsmith85** [comment]
Hi @Pajn, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
