### ISSUE TITLE
When using 2FA (Email), switching the Window aborts the login

### ISSUE THREAD

**Issue by 5nafu** [bitwarden/browser#795]
When using Email-2FA with Bitwarden, one need to login and then enter the 6-digit-code.
But, to get this information I need to switch to a different application (email client). This closes the Bitwarden popup, and thus aborts the login.

Returning with the code, you first need to login again, and another Code will be send. In my case, I got the same code multiple times, enabling me (after realizing this)  to use the previously copied code.

**Environment:**
* OS: Linux 4.13.0-46-generic
* Browser: 
  * Firefox 61.0.1 
  * Chrome 69.0.3497.100 
* Extension: Version 1.35.2 
* Server: BW 2.6.2/ BW-Web 2.0.0 Selfhosted

**Comment by kspearrin** [comment]
We need to offer an option to pop out to a new persistent window so that the focus change won't cause the window to close.

**Comment by kspearrin** [comment]
Should be fixed next version. It will offer to pop out the window for you.
