### ISSUE TITLE
Firefox Status

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/browser#8]
The Firefox extension was submitted to Mozilla on Sept 23rd and is currently in review. It seems that the review process for Firefox is a much longer wait time (compared to Chrome, which is nearly instant) since they rely on volunteers for this code review process. There is an indicator on their developer site that shows what position you are in line for review. We started on Sept 23rd @ queue position 111 of 111. I will follow up in this thread with the status.

https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

**Comment by kspearrin** [comment]
Oct 8th status

Queue Position: 57 of 165

**Comment by kspearrin** [comment]
Oct 11th status

Queue Position: 38 of 145

**Comment by kspearrin** [comment]
Oct 13th status

Queue Position: 20 of 137

**Comment by webjames** [comment]
@kspearrin The link in the readme and issue description is now 'not found'.

**Comment by kspearrin** [comment]
We've hit a bit of a roadblock here. Apparently Mozilla has now banned the use of Angular 1.x outright, which is a core library of our extension. I was not aware of this until just now. I have raised an issue with Mozilla and it is being tracked here: https://github.com/mozilla/addons-linter/issues/1000

Stay tuned.

**Comment by kspearrin** [comment]
Good news. Angular has resolved the issue that has been holding us back. They plan to release v1.5.9 of angular soon. Whenever that happens we will quickly upgrade and re-submit to Mozilla for review.

**Comment by ethanhs** [comment]
Though it looks like in the linter discussion mozilla is still not satisfied with the checks in v1.5.9... 

But it looks like the angular team and Mozilla are working together to resolve it?

**Comment by kspearrin** [comment]
I believe that their linter will require an update to block v1.5.9 which means it will require no change on their end and we can resubmit as soon as v1.5.9 lands.

**Comment by kspearrin** [comment]
As of v1.5.0, we are now in review with Mozilla again. We are working on trying to reduce the wait time of the review process.

**Comment by walterbe** [comment]
When you try to install the version V1.50 (link first posting) you get an error that this extension doe sot work in FF 43 or higher. 
Question; is there an version that works in the current FF release?  A not yet approved by Mozilla version , a developer version?
The fact there is no working FF extension available to use by the users is not helping the Kickstarter campaign. A version outside the official library is a lot better then no extension.

**Comment by evaryont** [comment]
I believe that's because Mozilla hasn't signed the add-on since it's still in review? And users in regular versions of Firefox can't disable the code signing check, so bitwarden doesn't have much power here other than to wait for the review to finish. Or convince it's users to use the nightly edition of Firefox, with all of that potential instability.

**Comment by walterbe** [comment]
If that is the reason I understand it. But strange for something like FF there is no setting somewhere, like by means of an about:config setting, you can override that.

**Comment by kspearrin** [comment]
As mentioned, Mozilla requires that the extension be reviewed and signed before you can add it from their store. There is nothing we can really do about it. The wait time for their review process on new addons is months. We are in the queue at position 208 of 306 :( .

The only option to use the extension in the meantime is to build the source and add it locally via `about:debugging`, but that is only temporary and will require you to do it each time you restart the browser. Or use Chrome or Opera :-/.

**Comment by walterbe** [comment]
@kspearrin  about Opera;  
On the website is the notice that just like with FF the plugin for Opera is waiting for approval by Opera.   I do not find a thread about this plugin for Opera here.  Where is that not-approved Opera plugin? That can be installed manually on Opera?

**Comment by kspearrin** [comment]
Regarding Opera, we have had our extension in their review queue for 3 months now and there is no response. New addons for Opera seem to be dead since noone is reviewing new submissions there anymore. The good news is that Opera and Chrome Web Store extensions are compatible -- meaning you can install bitwarden from the Chrome web store by using this opera extension: https://addons.opera.com/en/extensions/details/download-chrome-extension-9/

I will need to put together a help article to link to from the homepage Opera icon.

**Comment by Zorroblanco** [comment]
Hi there, I ve installed Bitwarden from Chrome store with this extension https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/?src=search This could a temporaly solution (It`s working fine, but I dont if exist some problem with security, please check it) Sorry for my english Im spanish guy. Cheers

**Comment by walterbe** [comment]
@Zorroblanco   thank you. It is complicated and inconvenient but at least it works. Thanks again.

**Comment by kspearrin** [comment]
Dec 22
Queue Position: 163 of 319

**Comment by Primokorn** [comment]
Then we can expect a review at the end of January...

**Comment by kspearrin** [comment]
Dec 27
Queue Position: 119 of 317

**Comment by kspearrin** [comment]
Dec 30 - 113 of 327

**Comment by MichaelPolla** [comment]
Thanks Kyle for keeping us informed of the Firefox queue progress. Can't wait to use this add-on.
Happy new year !

**Comment by kspearrin** [comment]
Jan 1
98 of 301

**Comment by kspearrin** [comment]
Jan 6
88 of 304

**Comment by kspearrin** [comment]
Jan 11
77 of 302

**Comment by kspearrin** [comment]
Jan 16
Queue Position: 62 of 309

**Comment by kspearrin** [comment]
We are out of the queue and in active review. Expect release soon!

**Comment by cipri-tom** [comment]
Another extension which I'm using 'bypasses' the Firefox review queues by providing a GreaseMonkey script. Would that be something sensible for you to do, too ? I mean, saying a hotfix is needed and as a user you have to wait until the queue clears, I'd prefer to get an unsigned version on GreaseMonkey, because I have to trust you anyways.

**Comment by kspearrin** [comment]
I'm waiting to see how the review process works for updates once we are in the store. I sure hope that we don't have to wait 2 months every time we want to submit an update, especially for things like important hotfixes like you mention.

**Comment by Danerd** [comment]
Any news about the review process? (I want this addon so bad.) :-)

**Comment by kspearrin** [comment]
Mozilla started reviewing it over a week ago and then went silent. We're sitting at Queue Position: 11 of 275

Hoping any day now.

**Comment by kspearrin** [comment]
Waiting almost 2 weeks since they "started" the review. I sent an email asking about the status. Their reply:

> we are currently going through a surge of submissions, so the review takes longer than usual.
> Also, a lot of developers request expedited review, which makes prioritization hard.
> We will try to get to yours as soon as we can.

Sorry guys, I thought ti would be ready by now..

Queue Position: 7 of 236

**Comment by kspearrin** [comment]
Queue Position: 6 of 246

**Comment by Primokorn** [comment]
More than 4 months to get it approved... That's a serious issue for Firefox team compared to other browsers.
Thanks for keeping us informed.

**Comment by jmauss** [comment]
The new betas of Firefox are showing some serious increase in speed... hoping that bitwarden gets approved by their release!

**Comment by kspearrin** [comment]
Queue Position: 5 of 294 :(

**Comment by grafenhofer** [comment]
Such a long waiting time does not seem to be that common: https://blog.mozilla.org/addons/2017/02/14/add-ons-update-92

**Comment by kspearrin** [comment]
Mozilla relies heavily on community members to review addons. Apparently since our addon is not a simple one, and contains a lot of code the community reviewers will not review it. Therefore, our addon falls into a bucket of only a select few official Mozilla employees (one that I know of) that review addons. Reviewing addons is not their only job, so we're stuck waiting for them to have some time in order to decide to start reviewing it.

This was the explanation I was given by Mozilla during all my emails to them about this. Sad that we have to wait so long. We're at their mercy at this point :(

**Comment by kspearrin** [comment]
We moved a tick. Queue Position: 4 of 298

**Comment by mhammond** [comment]
I suspect the "is corrupt" message is due to the following log entries I see on current Nightlies:

> 1487663041974   addons.xpi      WARN    Download of https://addons.mozilla.org/firefox/downloads/file/594812/bitwarden_free_password_manager-1.9.4-an+fx.xpi?src=dp-btn-primary failed: Error: Cannot find id for addon C:\Users\skip\AppData\Local\Temp\tmp-v8d.xpi (resource://gre/modules/addons/XPIProvider.jsm:5519:19) JS Stack trace: loadManifest/<@XPIProvider.jsm:5519:19 < ....

IIUC, https://github.com/bitwarden/browser/blob/master/src/manifest.json doesn't specify an ID for this addon? It *does* appear to load from about:debugging though.

**Comment by kspearrin** [comment]
@mhammond The corrupt message is simply because Mozilla hasn't reviewed it yet.

**Comment by UmarMughal** [comment]
Guys when we can expect this extension, what is the current status?

**Comment by kspearrin** [comment]
Please refer to the updates above.

**Comment by mhammond** [comment]
@kspearrin I'm confident the issue isn't simply that it hasn't been reviewed, so I took your addon, unzipped it, added:

>  "applications": {
>    "gecko": {
>      "id": "addon@bitwarden.com",
>      "strict_min_version": "42.0"
>    }
>  },  

to manifest.json, re-packed it, and I could install the addon fine. I'm fairly sure that will only work on Nightly and Aurora with the preference xpinstall.signatures.required set to false, but in that environment it's certainly possible to manually install your own unsigned addons and have them work. I suspect about:debugging generates an ID for you (and it may even be possible that the repacked xpi of the signed addon that will end up on addons.mozilla.org will also have an ID assigned for you), but it's certainly true that the lack of the ID in the XPI pointed at above is preventing it from being installed in Nightly and Aurora with the "must be signed" preference set to false..

**Comment by kspearrin** [comment]
@mhammond According to this: https://wiki.mozilla.org/Add-ons/Extension_Signing

> Mozilla now requires all extensions to be signed by Mozilla in order for them to be installable in Release and Beta versions of Firefox. Signing will be done through addons.mozilla.org (AMO) and will be mandatory for all extensions, regardless of where they are hosted.

> Firefox 40-42: Firefox warns about signatures but doesn't enforce them.
> Firefox 43: Firefox enforces the use of signatures by default, but has a preference that allows signature enforcement to be disabled (xpinstall.signatures.required in about:config).
> Firefox 48: (Pushed from Firefox 46). Release and Beta versions of Firefox for Desktop will not allow unsigned extensions to be installed, with no override. Firefox for Android will enforce add-on signing, and will retain a preference — which will be removed in a future release — to allow the user to disable signing enforcement.

Are you saying that this is not necessarily the case?

**Comment by kspearrin** [comment]
According to the above, `xpinstall.signatures.required` is not overridable (is that a word?) after Firefox 48. I don't have a problem adding that to the manifest though and we can see if it works?

**Comment by mhammond** [comment]
The above is for the release and beta channels only - Nightly and Aurora (aka Dev Edition) does still allow it. So while that doesn't help the vast majority of users, it probably does help unstick developers and gives an option for your "early adopters".

**Comment by kspearrin** [comment]
Looks like an ID has already been assigned by AMO and I cannot change it at this point (without abandoning my current submission and starting over).

> Your add-on failed validation with 1 error.
The add-on ID in your manifest.json or install.rdf (addon@bitwarden.com) does not match the ID of your add-on on AMO ({xxxxxxxxxxxxxxxxxxxxxxxx})

**Comment by mhammond** [comment]
Can you just use the ID assigned by AMO? I don't think the ID is exposed via any UI, so it doesn't really matter what it is.

**Comment by kspearrin** [comment]
Give it a try now from the AMO listing. I don't get the corrupt error anymore, now just a signing error.

**Comment by mhammond** [comment]
On a current Nightly with `xpinstall.signatures.required=false`, the addon installs and appears to work fine :)

**Comment by kspearrin** [comment]
@mhammond Great! I see you are part of the Mozilla Org. Do you happen to pull any weight there in the Firefox addons department? We've been patiently waiting for our extension to be listed since September. This whole process has been painful. I'm a Firefox user myself and I've had to basically abandon it for the past 6 months in favor of Chrome because of this.

**Comment by mhammond** [comment]
I'm afraid I don't carry any weight in addons :( I did however raise this in our internal forums and made the exact same point as you - ie, "5 months in review, during which there are 6.5k chrome users of the addon - surely this is hurting us!" and I'll continue to agitate where I can.

**Comment by kspearrin** [comment]
I can't tell you how many emails I get every week about "when will it be available on Firefox?" :-(

**Comment by Anaithsol** [comment]
Is it intentional for the Firefox addon to log you out of your vault after a set amount of time regardless of activity? It seems that every 30 minutes or so, I have to login in yet again and provide my verification code. 

This event still occurs consistently despite my lock option being set to never in the settings menu.

That said, my apologies if this isn't the best location to post this issue. It was only just recently I was able to use this addon on a permanent basis with the Nightly version of Firefox. I've had this occur in the past with about:debugging, but I always chalked the occurrence as a result of the temporary nature behind the addition method.

**Comment by kspearrin** [comment]
@Anaithsol please open a separate issue.

**Comment by umarmughal** [comment]
Finally extension reviewed by Mozilla and available to install but panel is blank if using in "Private Mode" is this only me?

**Comment by kspearrin** [comment]
Finally! After 155 days of waiting, the extension has been reviewed by Mozilla and available on Firefox now here: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager

Thank you all for your patience. I'm sorry it took so long but there wasn't a hole lot we could do differently here.

If you have any problems, please open them as separate issues.

**Comment by kspearrin** [comment]
Additionally, since we're so behind in Firefox now, if you all enjoy the extension there, please consider leaving us a good review in the addons store. It helps a lot!!

**Comment by umarmughal** [comment]
@kspearrin This won't work in Private Mode?

**Comment by kspearrin** [comment]
@umarmughal This is due to a bug with Firefox that Mozilla is working on fixing. See here: https://bugzilla.mozilla.org/show_bug.cgi?id=1319452

There's nothing we can do about it at this time.

**Comment by mhammond** [comment]
Note that https://bitwarden.com/ still indicates the addon is in review - it should probably be changed to the AMO link.

**Comment by kspearrin** [comment]
Fixed in all places exception the web vault. Not ready to do a release there yet.
