### ISSUE TITLE
Paypal popup?

### ISSUE THREAD

**Issue by johnmudd** [bitwarden/browser#80]
Paypal Checkout popup is ignored? Here's the HTML.
[PayPalCheckout.html.txt](https://github.com/bitwarden/browser/files/732532/PayPalCheckout.html.txt)

**Comment by kspearrin** [comment]
Seems to work with my latest tests.

**Comment by neverfox** [comment]
@kspearrin Hmm, this has never worked for me (and is my biggest pain point at the moment switching from LastPass), if you mean the popup that happens whenever you try to purchase from a website using PayPal and it opens a new browser window for you to enter your email/password. LastPass picks it up but I have to manually get my information from BitWarden. I running Chrome 65.0.3325.162 on OS x 10.13.3. If it should be working, I'm happy to help provide any additional information that would help debug it.

**Comment by kspearrin** [comment]
@neverfox Please provide a test website that shows the problem.

**Comment by 13am** [comment]
@kspearrin Trying to pay the premium fee at bitwarden.com using paypal shows the problem. Bitwarden plugin is unable to set the login information to the popup. Firefox 62.0.3, Fedora 28.

**Comment by oldrich-s** [comment]
@kspearrin the same for me. paypal popup requires manual filling...

**Comment by DanielSWolf** [comment]
Same problem here. Whenever I pay for something using PayPal, a new Chrome window opens, but with a minimal browser bar (see screenshot). In contrast to a normal Chrome window, the browser bar doesn't show any extension icons, so there is no way for me to click on the Bitwarden icon to trigger auto-fill.

![image](https://user-images.githubusercontent.com/5963162/101603679-39db0c80-3a00-11eb-9db4-eb0e73535054.png)

**Comment by DanielSWolf** [comment]
I found a way that works for me! Even though the Bitwarden extension icon is hidden, I can right-click anywhere within the popup window, then select *Bitwarden* > *Auto-fill*.

![image](https://user-images.githubusercontent.com/5963162/101604280-f92fc300-3a00-11eb-9c26-0d0030ddf587.png)

**Comment by tgreer-bw** [comment]
CMD/CTRL + Shift + L will also autofill and you can keep pressing it to cycle through any matching logins 🤘
