### ISSUE TITLE
Bitwarden browser extension offers to re-save newly generated password [Vivaldi]

### ISSUE THREAD

**Issue by tokyovigilante** [bitwarden/browser#800]
I will often add a login to a new site to Bitwarden via the browser extension, by manually entering my username then generating a password, and saving the new login before completing registration. 

The browser extension will then show a popover bar at the top of the screen offering to "update" the saved password even though it is not changed and is already saved.

**Comment by tokyovigilante** [comment]
Just the first time after logging in.


On Tue, Dec 11, 2018, at 1:27 AM, Kyle Spearrin wrote:
> Does this only happen after the first time that you log in after
> creating it? Or does it happen every time you log into the website?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/bitwarden/browser/issues/800#issuecomment-445833829

**Comment by kspearrin** [comment]
Can you provide an example website registration process where I can reproduce this issue?

**Comment by tokyovigilante** [comment]
It seems to happen on the majority of websites I visit, however most recently on phoronix.com <http://phoronix.com/>.

**Comment by kspearrin** [comment]
Just tried that same procedure again and still was not able to reproduce the issue.

**Comment by tokyovigilante** [comment]
Thanks for your attention. I have subsequently upgraded both Vivaldi and Bitwarden and the problem seems to have gone away.
