### ISSUE TITLE
Update password dialog does not reappear after redirect

### ISSUE THREAD

**Issue by multiwebinc** [bitwarden/browser#801]
When you have a password for a website saved in the vault and then enter a different password into that website, you get a prompt asking you if you would like to update the password stored. However if the password update confirmation page on the actual website has a redirect, that dialog never re-appears, forcing manual intervention to update the stored password, something that will likely confuse many users. This dialog should reappear indefinitely for that domain on every page load, even after clicking on links on that page, until the user manually interacts with the dialog and chooses either to update it or not. This is how LastPass handles it and it works amazing.

Tested with Chrome on Windows.

**Comment by kspearrin** [comment]
It should already do this if you are still on the same domain. Can you provide an example website to reproduce the problem?

**Comment by multiwebinc** [comment]
The example that happened to me earlier occurred when updating my Outlook mail password (on live.com). As soon as the password was changed, I got a confirmation and was redirected to another page and the prompt never reappeared. It is highly possible it was a redirect to another domain, or at least subdomain. When you say "same domain" in this case does this include Equivalent Domains?

**Comment by multiwebinc** [comment]
Also, I think it would be a good idea to guarantee the dialog has actually been displayed on-screen for a minimum amount of time if redirected to other domains (if not directly dismissed). Like say 15 seconds. You could log in to a website and immediately be redirected to another related domain and the popup shows up for a split second and that's it.

**Comment by andySF** [comment]
Same behavior on https://www.myqnapcloud.com

**Comment by eliykat** [comment]
This is the same issue as described in #1419. There is more recent discussion on the other issue, so I'll close this one as a duplicate.
