### ISSUE TITLE
Password autofill not working on Twitter

### ISSUE THREAD

**Issue by iKarith** [bitwarden/browser#804]
Fill logic fails for twitter.com, filling something shorter than my saved twitter password.  I can copy/paste the correct password from BitWarden by hand, but it doesn't fill from the pulldown properly. Firefox extension version 1.35.2 installed 2018-12-07.

**Comment by kspearrin** [comment]
I just tested this and it seemed to work fine for me.

**Comment by iKarith** [comment]
It works if I keep a short password, but if I use a longer passphrase, it
appears to cut it off.

Joseph

**Comment by kspearrin** [comment]
How long of a password are you using?

**Comment by iKarith** [comment]
Four words with separators, auto-generated.

Joseph

**Comment by iKarith** [comment]
Is there possibility that I should recreate the login from scratch? The
password I'm using is one BitWarden generated (because I changed it), but
the rest of the login details were imported from 1Password. I didn't try
that because I can't imagine how that could be a problem. I'd expect the
fields to be 1:1 since I didn't use anything custom.

Joseph

**Comment by kspearrin** [comment]
I just created a new twitter account with the password "tableful-dill-obsessed-suing-civic-plausible" and it seems to autofill and log in without issue.

**Comment by kspearrin** [comment]
Cannot reproduce

**Comment by iKarith** [comment]
This may be PEBKAC, apparently my extension is old. It doesn’t have dark
mode, and I just installed on another machine which does. So I’m probably
in need of an update.

Thanks Kyle, and Merry Christmas. :)
