### ISSUE TITLE
CloudFlare banned IP

### ISSUE THREAD

**Issue by davidosomething** [bitwarden/browser#806]
Hey, my IP was banned on CloudFlare
I was moving a bunch of things into folders and deleting old entries from a recent import

Error 1006 Ray ID: 48946d5aaee34728 • 2018-12-14 23:24:59 UTC

**Comment by kspearrin** [comment]
It should be unblocked now.

**Comment by lucrito** [comment]
I have the same Problem :/
Ray ID: 497eec04689c63d9 • 2019-01-12 10:25:55 UTC
