### ISSUE TITLE
Recursive Redirect

### ISSUE THREAD

**Issue by cleyden** [bitwarden/browser#807]
After creating a folder, clicking on a new type can cause constant redirects between all of the types.

Windows 10
Browser: Firefox 64.0

![bitwarden_folder_test](https://user-images.githubusercontent.com/6565410/50070233-00100a80-0219-11e9-8192-249392cc6df9.gif)

**Comment by kspearrin** [comment]
Can you list the reproduction steps please?

**Comment by cleyden** [comment]
1. Create a new folder
2. Change type selection, at least two times
3. Page begins to auto-redirect between all types

**Comment by kspearrin** [comment]
I have tried to do these steps and was unable to reproduce the problem. Does it happen every time?

**Comment by cleyden** [comment]
On further testing, creating a new folder doesn't appear to be required to reproduce the issue. I am consistently reproducing the problem however.

Also tested in Chrome Version 71.0.3578.98 (64-bit)

Gif of reproduction:
![bitwarden_folder_test_2](https://user-images.githubusercontent.com/6565410/50268015-f71b7500-0474-11e9-94c5-fa841d03bc9e.gif)

**Comment by kspearrin** [comment]
This should be fixed in the next version, v2.8.

Thanks.
