### ISSUE TITLE
[BUG] CMD + SHIFT + L still works incognito in Firefox

### ISSUE THREAD

**Issue by 2mill** [bitwarden/browser#808]
Hey so I realized when I am trying to use Bitwarden extension in incognito mode, I am blocked from doing so. However, when the Bitwarden is already logged in, pressing CMD + SHIFT + L will still autofill login fields. I am unaware if this is an issue with the other browser versions.

**Comment by kspearrin** [comment]
I'm not sure I understand how this is an issue?

**Comment by 2mill** [comment]
It’s not really an issue if you think about it, but considering that you cannot use the Bitwarden extension while incognito, shouldn’t you be barred from using the autofill shortcut as well?

**Comment by kspearrin** [comment]
No, since its only a limitation of Firefox's ability to work with the extension in private mode. See more here: https://help.bitwarden.com/article/extension-wont-load-in-private-mode/
