### ISSUE TITLE
Save password banner is flickering

### ISSUE THREAD

**Issue by SR-G** [bitwarden/browser#81]
I'm using Bitwarden extension (1.8.2) under Vivaldi 1.7.735.11 (Build officiel) (64 bits)

Each time i have the top banner about saving a new password, that Bitwarden banner is "flickering" (appearing / disappearing very quickly over and over). I can't even close the banner with the close button on the right, i have to close the tab (CTRL-W), disable Bitwarden extension, and then reopen it again.

Any idea about that behavior ? (haven't found anything related)

**Comment by Zorroblanco** [comment]
Hi, same here, Firefox 51 (x86) win 7 32 (and performance is slow: 2-3 seconds to load after clik on icon) Cheers (sorry for my english)

**Comment by kspearrin** [comment]
Thanks for the report. This has now been fixes for the next release here: https://github.com/bitwarden/browser/commit/b2aa4fed7899e95a6ae71b54fb57c0f806bfdf79

Weird how the same issue wasn't occurring in Chrome.

**Comment by kspearrin** [comment]
This fix is now available in the Chrome web store and Firefox addons store.

**Comment by SR-G** [comment]
I can confirm that it's working now without any flickering under Vivaldi, thanks for the fix.
