### ISSUE TITLE
Chrome plugin can't update/create items when server is offline

### ISSUE THREAD

**Issue by bradyjoh** [bitwarden/browser#810]
- Environment: My computer is in a state where the Bitwarden instance is inaccessible. This could be due to being offline, Bitwarden being down, being in a different network behind a firewall, etc. 
- Issue: I want to add a new set of credentials or update an existing username/password, but get a "Failed to Fetch" error. 
- Expectation: The local Bitwarden vault should be editable even when the Bitwarden server is inaccessible, and then the remote vault should be updated during the next sync. 

I believe this used to work with old Chrome extension versions (August/September 2018), and now it doesn't. I have to write down the password elsewhere in plaintext and then add it to Bitwarden once the server is accessible again.  

Is there a setting that allows offline operation? 

Happy to provide more detail if needed.

**Comment by kspearrin** [comment]
Hi,

No Bitwarden application has ever been able to write to the vault while offline. This is the expected functionality. The vault is only accessible in read-only mode while offline.

**Comment by bradyjoh** [comment]
Got it. Just a couple thoughts from a UX perspective:
- After going through the whole "creating a new item" or "updating an existing item" process, only upon pushing the Save button did I find the "failed to fetch" error preventing me from saving all the changes I made. As a user, I'd love to be warned before spending time making changes that will disappear the second I leave the page.
- As a user that wants to use Bitwarden offline during international travel, I would love to stash changes and have them get applied once I am able to contact the server. This could happen dynamically, or even with an "offline mode" that requires a bidirectional sync when coming back online. 
- As a user, I'm wondering if "Sync" would be better described and shown in the UI as "Fetch" or "Pull latest items" or something. If the aforementioned behavior remains unchanged, there will never be a client->server sync that happens when that button is pressed, as the client->server sync must always succeed when saving or updating an item. Thus, the "Sync" button really only does server->client retrievals. 

I realize conflict/merge resolution between offline-edited items and their online counterparts could be a developmental challenge. Is that the reasoning behind read-only local vaults, or are there other considerations?

**Comment by kspearrin** [comment]
The reason this isn't offered as a feature today is because the use case doesn't have much demand from our users. The logic to manage an offline queue of vault updates and then handle conflicts when coming back online is rather difficult and complex. Therefore, it has not been a priority.

**Comment by jotaf98** [comment]
> After going through the whole "creating a new item" or "updating an existing item" process, only upon pushing the Save button did I find the "failed to fetch" error preventing me from saving all the changes I made. As a user, I'd love to be warned before spending time making changes that will disappear the second I leave the page.

I second this, it's a UI-only change -- don't allow editing when offline, since it's going to throw an error and lose data!

Hopefully it's easier to implement, since it doesn't require overhauling any sync logic at all.
