### ISSUE TITLE
Safari wrong TOTP

### ISSUE THREAD

**Issue by ItsEcholot** [bitwarden/browser#812]
It seems like the safari extension displays the TOTP key for Steam wrongly:
![image](https://user-images.githubusercontent.com/2771251/50346839-e67e0400-0533-11e9-82d1-90865d2e6869.png)

While the web vault returns the TOTP key correctly:
![image](https://user-images.githubusercontent.com/2771251/50346938-3d83d900-0534-11e9-80e0-8dcd5de4851c.png)

**Comment by kspearrin** [comment]
The update is still pending for the Safari extensions gallery.
