### ISSUE TITLE
User Name field not recognized

### ISSUE THREAD

**Issue by Ramapitecus** [bitwarden/browser#817]
I'm trying to use the browser extension on a page that is in Spanish. And will redirect to another page to input the password after providing a username. 
This is the input field: 
```	
<input name="txtUsuario" type="text" maxlength="10" id="txtUsuario" class="LogTxtBox" autocomplete="off" placeholder="USUARIO">
```

It's not one of the default id's the extension looks for. I've added a custom field for the entry as recommended on the FAQ and it's working. But I still report it here maybe we could add some other languages besides English and German.

**Comment by kspearrin** [comment]
I don't know Spanish, so adding new keywords for these would need to be done by a Spanish-speaking community member via pull request.

**Comment by harogaston** [comment]
Spanish speaker here. "txtUsuario" (a.k.a "txtUser") does not look standard at all for a "username"" input filed id. I would not recommend autofilling that.
