### ISSUE TITLE
Buttons too small on 4k display

### ISSUE THREAD

**Issue by Fealthas** [bitwarden/browser#818]
![image](https://user-images.githubusercontent.com/25716039/50568136-aed54000-0d1b-11e9-8d44-ec7eceede464.png)
The buttons to increase/decrease length and min number of characters are too small.

**Comment by kspearrin** [comment]
Which browser? This looks like more of a browser issue to me.

**Comment by Fealthas** [comment]
Firefox Quantum 64.0

**Comment by kspearrin** [comment]
Can you try the following fiddle on this device to see if the same issue is present? https://jsfiddle.net/ahy6b0oL/

**Comment by Fealthas** [comment]
![image](https://user-images.githubusercontent.com/25716039/50578844-30f16180-0e0d-11e9-8daf-5d840bb068c8.png)
Guess it is a browser issue.
