### ISSUE TITLE
Password autofill not working on Citi

### ISSUE THREAD

**Issue by yoasif** [bitwarden/browser#827]
1. Visit https://online.citi.com/US/login.do
2. Autofill login and password

What happens:

Password gets populated, username does not

Expected result:

Both password and username are populated

Using Firefox nightly, but reproducible on stable.

**Comment by kspearrin** [comment]
Unfortunately this website some some really weird stuff to prevent us from robo-pasting (autofilling) your password in. It seems intentional.

**Comment by xyxzxyz** [comment]
I tested it, Bitwarden filled out the logins just fine.

**Comment by yoasif** [comment]
It *is* working now!
