### ISSUE TITLE
[Self-Hosted] Can't login, Firefox extension session expired

### ISSUE THREAD

**Issue by Svarto** [bitwarden/browser#828]
Hi,

I am trying to log into my bitwarden through the Firefox extension but I instantly get kicked out (even before entering my 2FA) with two error messages:

"Logged Out - your login session has expired"

AND

"An unexpected error has occurred"

I can login to Bitwarden through the website and through my android bitwarden mobile client.

I had a look at firefox debugging of the bitwarden extension, and there is only one XHR request being sent and a 401 Unauthorized returned right away (9 ms). I am not sure what is wrong, I tried disabling all Firefox add-ons, uninstalling them, uninstalling and reinstalling bitwarden but nothing works.

**Comment by Svarto** [comment]
Having a bit deeper look, it seems like the request from the app fails the CSRF check as the response from my reverse-proxy is "401 CSRF origin error". Is this expected? Do I need to turn off CSRF checking to use the bitwarden browser extension?

**Comment by kspearrin** [comment]
Bitwarden does not perform CSRF checks, so I am not sure where that is coming from.

**Comment by Svarto** [comment]
It's coming from my Zero Trust Reverse Proxy (pritunl-zero). Got it to work though by turning of the CSRF check - not sure if that opens up a security risk / why this became such a problem for only the browser extension and nothing else...

-------- Original Message --------
