### ISSUE TITLE
Automatically unlock vault with native password manager

### ISSUE THREAD

**Issue by AndreasBackx** [bitwarden/browser#836]
On Linux you've got Gnome Keyring and KDE Wallet (if not more), on MacOS you've got the MacOS Keychain, and on Windows I don't really know. Many of each OS' features plug into these along with Git, GPG, VS Code, etc. to store their credentials. So most of the time when you're logged in, your keyring/keychain is already unlocked because you either unlocked it during login or another application already unlocked it. That's why I think most people are still using a password manager like the one that's built into Google Chrome, or the iOS and MacOS keychain. So I came here to ask whether it's possible to use Google Chrome's (and perhaps others as well, I haven't looked that much into it) credentials API (which integrates with Gnome keyring, KDE Wallet...) to automatically unlock the vault.

I've also wondered whether the desktop app could offer this feature if it does not do so already: replace Gnome Keyring and KDE Wallet on Linux. (I'm unsure whether it's possible on MacOS, but I think it might be possible because it's possible on iOS). Though, a respective issue would have to be made there as well. Then, in the end we'd be able to use Bitwarden from end-to-end.

**Comment by kspearrin** [comment]
Hi,
Unfortunately such APIs do not exist for web extensions (at least none that I know of). We only have an unsecured storage API.

**Comment by AndreasBackx** [comment]
I haven't looked that much into this, but I did find some resources that might allow you access to the password managers:

https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API
https://developers.google.com/web/updates/2018/03/webauthn-credential-management

**Comment by AndreasBackx** [comment]
Are you sure?

https://w3c.github.io/webappsec-credential-management/#passwords
https://w3c.github.io/webappsec-credential-management/#credential-chooser

**Comment by AndreasBackx** [comment]
So after trying it out myself. It does seem like this interacts with Google Chrome's password storage:

![Example](https://i.imgur.com/FLUV7r9.png)

```javascript
const credentials = new PasswordCredential({
	id: "username",
	password: "password",
});
navigator.credentials.store(credentials);
```

You can then use `get()` instead of `store()` to retrieve the information, see docs for more information. I assume that we can also leverage this in the application. But I've been thinking about something myself.

Google Chrome currently provides support for Gnome Keyring and KDE Wallet. I haven't looked that deep into it yet, but I assume that both of these use a different protocol/API for communication. What if we could create a protocol for at least Linux (and perhaps other operating systems as well) so that BitWarden and other password storage platforms can be plugged into by any application like it is on iOS (and Android?)?

I'm personally interested in a project like this.

**Comment by kspearrin** [comment]
Nice. I didn't know about some of these API.

Unfortunately, while this works in the main browser window, it appears that the API is blocked in extensions windows.

![image](https://user-images.githubusercontent.com/1190944/51364541-7ae37400-1aaa-11e9-8923-32bd91f3d333.png)

**Comment by hephaware** [comment]
I'm also interrested in running Bitwarden as a replacement for kwallet or gnome-keyring. It would be neat :-D

**Comment by cpholt** [comment]
I'll second that.  If bitwarden could replace KWallet underneath in Ubuntu/etc, that would be Awesome.

**Comment by cies** [comment]
Does building BW into KWallet mean that you can also have a local copy of data? That would make offline, different line, or surviving BW server outage a possibility :)

**Comment by leonardehrenfried** [comment]
Since bitwarden has an API, would it be possible to write an adapter so that GNOME keyring et al. synchronise their data with Bitwarden?

**Comment by AndreasBackx** [comment]
> Since bitwarden has an API, would it be possible to write an adapter so that GNOME keyring et al. synchronise their data with Bitwarden?

Yes, you'd either have to use the https://github.com/bitwarden/jslib or use [the API](https://docs.bitwarden.com/api/)

**Comment by Famiu** [comment]
I would also love this feature. I'd like to urge the developers to implement it if possible

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Alexander-Shukaev** [comment]
I have a question regarding this.  So basically, if option `Never` is chosen, the extension saves to `chrome.storage`.  In case of GNOME keyring availability, any Chrome-like browser will actually store `chrome.storage` encrypted in `Login` keyring by default, which would be unlocked upon desktop environment session logon.  Is this assumption correct?  If yes, then I guess it's secure enough to have `Never` in such case.

**Comment by AlphaCraft9658** [comment]
I kinda missed what happened here. Has this been implemented? There seem to be some keys for Bitwarden in my KWallet.

**Comment by jokeyrhyme** [comment]
> I kinda missed what happened here. Has this been implemented? There seem to be some keys for Bitwarden in my KWallet.

Yeah, I'm a little confused, too

If my default login keychain hasn't been unlocked yet (Linux, GNOME), then launching Bitwarden Desktop does cause a system/polkit/GNOME prompt to appear to unlock it, but then the Bitwarden Desktop app still requires my Bitwarden credentials to decrypt the vault

I don't think it's useful to read/write to the system keychain if there's still going to be a Bitwarden credential check, I'd rather only have the Bitwarden check and not have any system keychain integration at all (or at least an option to turn it off)

**Comment by trmartin4** [comment]
Hello!

We have recently introduced an update to the desktop clients that will attempt to store your authentication access token and refresh token in a secure storage location, depending on the client OS.  So this would be KeyChain on MacOS, Credential Manager on Windows, and a Secrets Service (abstracted through `libsecret`) on Linux.  These tokens were previously stored on disk.

This is why you are now seeing the prompts to unlock your keychain when attempting to access your vault; we must gain access to the secure storage in order to retrieve your access token to perform any authenticated actions against the server API.  Unlike the original topic of this thread, we are not storing any of your Bitwarden vault data in the platform native credential manager - only the access and refresh tokens.

**Comment by jokeyrhyme** [comment]
@trmartin4 thanks for explaining, and the intention of the change makes sense

Is it intended that I still need to enter my Bitwarden master password / credentials after the system keychain is unlocked?
