### ISSUE TITLE
[Chrome Extension] "View Login" Copy Password

### ISSUE THREAD

**Issue by Anshinritsumai** [bitwarden/browser#84]
- Chrome Version - 55.0.2883.87 m (64-bit)
- Extension Version - 1.8.2
- Tested after disabling all other extensions, still won't work as intended.

When [viewing an individual login](http://puu.sh/tNJLx/fa5dc5b61c.png), the "Copy Password" button will **not** copy the password, until the "Toggle Password" button has been clicked (thus showing the password). If you attempt to "Copy Password" without hitting the "Toggle Password" button first, the expected password will not be copied, and instead you'll be left with whatever was the last item on your clipboard.

This will occur regardless of whatever action was taken previously or even if the copy password button is the first button clicked while on this screen.

For example, I have clicked "Copy Username" and then followed it up with a click of "Copy Password", only to have the "password" be nothing more than the username which was copied earlier.

**Comment by kspearrin** [comment]
Thanks for the report. I was able to reproduce the bug.

**Comment by kspearrin** [comment]
Resolved in 1.9.x
