### ISSUE TITLE
Firefox keyboard shortcut does not work on macOS

### ISSUE THREAD

**Issue by jcrben** [bitwarden/browser#841]
For whatever reason, CTRL+SHIFT+L doesn't work for me on Firefox 64.0.2 on macOS.

CTRL+SHIFT+L does work for my Firefox on my NixOS laptop, which is where I primarily use Firefox. I primarily use Google Chrome on macOS, so it's not that big of a deal.

Let me know if I can help debugging this or if it seems like a one-off thing affecting just me.

It seems that there might be a way to adjust the shortcut? https://community.bitwarden.com/t/ability-to-change-keyboard-shortcuts-in-firefox-60/42/4

**Comment by Crocmagnon** [comment]
On macOS you need to use <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd>

**Comment by jcrben** [comment]
That doesn't work for me either.

**Comment by adamwinn** [comment]
It works for me on macOS with Firefox.  If there is already a login filled, it will not re-fill it and give the animation.  I thought that's what would happen.  I removed the autofill that Firefox had done and made sure the form was blank, then Cmd + Shift + L filled it in fine.

**Comment by jcrben** [comment]
Seems to be working now.
