### ISSUE TITLE
Bitwarden don’t recognize Login-Fields on rockauto.com

### ISSUE THREAD

**Issue by rampolino** [bitwarden/browser#843]
Bitwarden don’t recognize Login-Fields on rockauto.com. If I put the Login Data manually into Bitwarden then Bitwarden only fill Password and don’t fill Email-Adress/Username
All on Mac Mojave and Safari Extension

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
