### ISSUE TITLE
Bitwarden fail to fill credit card form from on Kasikorn bank payment gateway

### ISSUE THREAD

**Issue by tuangd** [bitwarden/browser#844]
Hi,

I am from Thailand, this payment gateway is from one of the biggest banks here.

From the screenshot, you will see that they split the credit card number form into slots, and BW failed to recognize them. I'm not sure is it because of the language or not.
But when I was using LastPass (I migrated to BW last year) it was filling the form fine.
Currently, I have to copy and paste the number by myself.

I hope that I proved enough info, but if you need more let me know.

![kbankpg png](https://user-images.githubusercontent.com/8474403/51665351-254d2100-1fee-11e9-8680-b541d9e00a5b.jpg)
[Payment.zip](https://github.com/bitwarden/browser/files/2790803/Payment.zip)

**Comment by kspearrin** [comment]
Currently we dont support scenarios like this where the card number is split into 4 input fields.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
