### ISSUE TITLE
2-step verification not working with Firefox plugin

### ISSUE THREAD

**Issue by Wetrain** [bitwarden/browser#845]
Hi there,

I enabled a U2F key along with an authenticator app for logging in to Bitwarden.

However when i log in via the Firefox extension, i am not prompted for the second step authentication?

This seems like a major security flaw, the desktop app prompts me as expected along with the website, yet the firefox extension just requires my master password?

**Comment by mshoestrng** [comment]
I have the same issue. It would be great if you could add the option to required 2FA whenever the browser plugin (Firefox, Chrome etc.) is locked. Then every user would have the choice whether to use 2FA or not in browser plugins.

**Comment by whiskeysierra** [comment]
> For convenience, the apps and extensions lock your vault after some period of inactivity but they don’t log you off. So they don't prompt you for 2FA when you try to use them again.

I have to say, using my U2F key is so much more convenient than entering my master password or PIN.
