### ISSUE TITLE
[Feature] Notification on new site -> remember this answer for this site

### ISSUE THREAD

**Issue by marcelloh** [bitwarden/browser#85]
It would be nice to have  bitwarden remember the answer for a site,
so it wouldn't harass me every time on the same site, when I choose for not saving the password.
(it keeps asking me until I close the question somehow)

**Comment by bellinom** [comment]
I'd like to see this added as well. I frequently use work passwords that I don't want remembered in my personal vault, and am always asked to save.

**Comment by kspearrin** [comment]
will be available next version. see:

![image](https://user-images.githubusercontent.com/1190944/27096927-9d1bac6c-5040-11e7-8715-c84bedc0365b.png)

**Comment by marcelloh** [comment]
Very pleased to see this :-) Thank you very much
