### ISSUE TITLE
Launch button in Browser Vault only tries first URI and doesn't skip regular expressions

### ISSUE THREAD

**Issue by gene1wood** [bitwarden/browser#850]
# Steps to reproduce

1. Create a credential in BitWarden
2. Create `URI 1` as anything other than Regular Expression
3. Create `URI 2` as a Regular Expression
4. Save the credential
5. Click the `Launch` button in the vault for the credential and the site is successfully launched
6. Either create a new credential or modify the existing one such that
7. `URI 1` is a Regular Expression
8. `URI 2` is anything other than Regular Expression
9. Save the credential
10. Click the `Launch` button in the vault for the credential

# Expected results

The site should launch successfully regardless of the order of the URIs

# Actual results

The site will not launch because only the first URI is checked/used

# Proposed fix

Instead of taking the first URI in the list of URIs, create a list of the URIs excluding regular expressions and launch the first URI in that list.

#656 is a related issue

**Comment by kspearrin** [comment]
I suppose we should just use the first URI that is a valid URI.
