### ISSUE TITLE
Clicking the extension, while vault is locked, will briefly expose from previous usage the confidential matching entries (Name, User name) & Payment Cards (truncated) info

### ISSUE THREAD

**Issue by maanuair** [bitwarden/browser#851]
I rely heavily on BitWarden extensions in my day to day browsing.
I noticed the following weird use case, below.

**Steps to reproduce**
- With the extension installed in Safari or Firefox, go to a website login page
- Click the extension button to fill in the login form : you're asked you master password
- Enter your master password, and click the corresponding entry to fill the login form
- Then, wait for the vault to lock itself (according to your setting; mine is 5 minutes)
- Browse to another site
- Click the extension button

**Expected result**
- The vault is locked and I'm asked my master password

**Actual**
- The vault is locked: OK
- **However**, I can see — during a brief instant  (like < 1 s) — the previous display where the extension listed:
  - all the entries that matched my previous site (i.e.: Names, User names)
  - all payment cards info (partial info, but still)
  - => So  **NOT OK**
- Then I get the subsequent master password prompt as expected: OK

**Reproducibility**
- 100% in Safari 12.0.2 (14606.3.4)
- ~~100% in Firefox 64.0~~ (EDIT: Not FF, my bad)
- Both on macOS Mojave 10.14.2 (18C54)

**Extra information**
The main point I raise here is that the extension divulges some confidential information, even for a brief instant, before it shows the master password page.

I was expecting my privacy to be enforced in this use case.
What do you think ?

**Comment by kspearrin** [comment]
Due to how the Safari extension works, this makes sense, but I am testing this in Firefox on macOS and cannot reproduce. Are you sure the issue is also visible there?

**Comment by maanuair** [comment]
Thanks for your reply.

Hmm, you're right: I cannot reproduce in FF, I must have confused myself...
(I'm feeling guilty you wasted the time to reproduce, I'm sorry for that ! :-/ )

I edited my description!

Re Safari, does it mean it's gonna stay as is, as per Safari's extensions design?
