### ISSUE TITLE
Firefox Extension on Mac OS prompts for master password before BitWarden is actually used

### ISSUE THREAD

**Issue by baarkerlounger** [bitwarden/browser#856]
On Firefox on Ubuntu it seems the default behaviour is to only ask for the master password when you click the bitwarden extension icon, i.e. try to use it to enter a login, etc

On Mac OS it seems the default behaviour is to prompt you for the password when you launch the browser regardless of whether you're trying to use this or not.

Is this just buried in the settings somewhere or can this be made consistent? Personally I prefer the behaviour on Ubuntu.

**Comment by Crocmagnon** [comment]
I don't experience this behavior with Firefox on macOS.

**Comment by baarkerlounger** [comment]
I can reproduce consistenly. Can send you a screen recording if it's helpful.

**Comment by kspearrin** [comment]
Bitwarden does not prompt for master password like you depribe. Sounds like something Firefox is doing itself, unrelated to Bitwarden.

**Comment by baarkerlounger** [comment]
It doesn't seem to affect any other extension and as I mentioned seems to work differently on Firefox on other platforms. Do you have any idea what could cause this that I could raise to their team?

**Comment by kspearrin** [comment]
Do you have a master password set to protect your Firefox user profile data?

**Comment by baarkerlounger** [comment]
That's what it is! Apologies for wasting your time and thanks for the help!
