### ISSUE TITLE
Safari Extension causes strange side effects with the URL bar

### ISSUE THREAD

**Issue by feld** [bitwarden/browser#857]
With the BitWarden extension enabled in Safari I notice that frequently when I try to edit a URL to quickly get to another part of a site it just refreshes the same page I'm on after pressing ENTER to attempt to navigate to that URL. Sometimes you can bypass this by putting your cursor at the very end of the URL before pressing ENTER, but it doesn't always work. It's very bizarre and frustrating behavior that ceases immediately when I disable the Bitwarden extension in Safari.

**Comment by kspearrin** [comment]
Honestly I am not sure. We don't do anything that I know of that should interfere with the native UI of editing the address bar.
