### ISSUE TITLE
Bitwarden thinks that every Firefox tab and window is private mode, even with private browsing disabled.

### ISSUE THREAD

**Issue by sciguyryan** [bitwarden/browser#859]
When updating Firefox to the latest nightly build (07/02/2019) BitWarden refuses to function, stating that it "is not available in Private Browsing mode". I am perplexed as private browsing is completely disabled so it seems likely that an issue has come up between BitWarden and the latest Firefox nightly build.

If this could be investigated I'd appreciate it.

**Comment by kspearrin** [comment]
On firefox, if we cannot access the background page from the browser action popup, we assume this is private mode. Sounds like nightly broke something with background page access from popup.

**Comment by sciguyryan** [comment]
That could be the case. Is there anything you'd like me to try in order to help you debug this? It's the least I can do.

**Comment by kspearrin** [comment]
Really, it just need to be reported to Mozilla that `chrome.extension.getBackgroundPage()` is returning null from non-private mode browserAction popup windows.

**Comment by vatjjar** [comment]
This started to happen to me today on linux with ff 65.0.1. I do not run nightlies, I run only release that comes through ubuntu channels.

It seems that once this problem starts to occur, if I restart firefox for good (i.e. killall firefox and restart), it seems to fix the problem (at least for a while). I do not understand how it can break on the fly, and then fix itself on ff restart.

**Comment by tim1aust** [comment]
I am experiencing the same behavior, starting just this morning. Running FF 66.0.3 on Manjaro Linux (64 bit), which was last updated on April 10 (over a week ago). Same puzzling "break on the fly, and then fix itself on ff restart".

**Comment by tim1aust** [comment]
Looking in dmesg:
`[58441.290261] WebExtensions[20250]: segfault at 0 ip 00007f1851fa0856 sp 00007ffded62df80 error 6 in libxul.so[7f184e88a000+4f66000]
[58441.290266] Code: 31 c0 4c 8b 04 24 48 85 c0 0f 85 25 f4 ff ff e9 f7 f8 ff ff e8 f3 a9 8e fc 48 8d 05 6c 0e e8 01 48 8b 0d 95 bd b8 03 48 89 01 <c7> 04 25 00 00 00 00 53 12 00 00 ff 15 19 db b8 03 48 8d 05 0f 0e`
Google found:
https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/
Apparently some changes in ff WebExtensions API..

**Comment by SpineEyE** [comment]
I also got this message from Bitwarden today. I don't get any WebExtension error in dmesg and BitWarden's autofill still works. It also shows the little number on the icon to show that there are accounts for the current website.

Not sure how to reproduce this though, this just happened the first time in a normal browsing session (I had a private window open before and closed it, but I only noticed the bug about half an hour later). My other addons seem to be working fine, including uBlock Origin, Zoom Page WE, Cookie AutoDelete.

**Comment by SpineEyE** [comment]
Nevermind, this is not random, I found out how it can be triggered. Install https://github.com/mozfreddyb/webext-firstpartyisolation , click that extenion's button (which should disable first-party cookie isolation, logo becomes red). Then, Bitwarden will show the error message that this bug is about. Click the extension button again, button becomes transparent again, BitWarden works again.

Not I have no idea if that's the fault of BitWarden, that other extension or Firefox, maybe somebody knows?

**Comment by tedsilb** [comment]
This is happening to me too, on Firefox main build 67.0.2, macOS 10.15. No private windows open, it happens even after restarting Firefox.

**Comment by jeroen7s** [comment]
does anyone here have firstparty isolation enabled? as that seems to trigger this behavior
after disabling firstparty isolation in firefox about:config it seems to work normally again.

**Comment by hadrianw** [comment]
@jeroen7s disabling first party isolation works for me, but it's sad.

**Comment by SpineEyE** [comment]
@hadrianw  I have first party isolation active the whole time and Bitwarden works. The problem is just when a website decides not to work, and I disable third party isolation temporarily using the addon I mentioned [above](https://github.com/bitwarden/browser/issues/859#issuecomment-499451774). After that, Bitwarden thinks I'm in privacy mode until I re-enable first-party isolation.

So it seems to be the other way round as you say it.

**Comment by jeroen7s** [comment]
@SpineEyE that's really weird, since FirstParty Isolation is definitely off by default.

**Comment by SpineEyE** [comment]
I just tried it with a fresh profile: If `privacy.firstparty.isolate` is off when you install Bitwarden, the bug will come up when you enable `privacy.firstparty.isolate` and the other way round: When `privacy.firstparty.isolate` is on, then you install Birwarden and switch `privacy.firstparty.isolate` off, the bug will come up.

**Comment by Elehiggle** [comment]
I have opened a Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1624155

**Comment by devurandom** [comment]
I just ran into this after rebuilding Firefox 83.0 (Gentoo/Linux).

**Comment by devurandom** [comment]
> I just ran into this after rebuilding Firefox 83.0 (Gentoo/Linux).

The issue resolved itself by setting "Run in private windows: Allow" and then immediately setting it back to "Don't allow".

**Comment by timothyclarke** [comment]
> > I just ran into this after rebuilding Firefox 83.0 (Gentoo/Linux).
> The issue resolved itself by setting "Run in private windows: Allow" and then immediately setting it back to "Don't allow".

Thanks this happened to me on Linux (ubuntu) with FireFox 94.0 (64-bit) and Birwarden 1.54.0

Can one of the developers update https://bitwarden.com/help/article/extension-wont-load-in-private-mode/ to add instructions to allow then Don't allow per @devurandom as a work around

**Comment by dwbit** [comment]
> > > I just ran into this after rebuilding Firefox 83.0 (Gentoo/Linux).
> > > The issue resolved itself by setting "Run in private windows: Allow" and then immediately setting it back to "Don't allow".
> 
> Thanks this happened to me on Linux (ubuntu) with FireFox 94.0 (64-bit) and Birwarden 1.54.0
> 
> Can one of the developers update https://bitwarden.com/help/article/extension-wont-load-in-private-mode/ to add instructions to allow then Don't allow per @devurandom as a work around

This should be addressed in the latest update and revised Help Center article, but let me know if you have any outstanding issues.

**Comment by jeremymeyers** [comment]
This is still happening in Firefox 110.0 on Mac.
