### ISSUE TITLE
Rename Default Folder

### ISSUE THREAD

**Issue by Lavenblade** [bitwarden/browser#86]
Super minor, but if it isn't hard to do I'd like to be able to rename the default folder.

If this is feasible, I'll open an issue for the web vault and mobile vault repos.

**Comment by kspearrin** [comment]
The default folder actually isn't a folder at all. It's basically "uncategorized".

**Comment by Lavenblade** [comment]
Oh, I see. Well that won't work then, sorry about that. :P

**Comment by kspearrin** [comment]
No worries. Maybe we should change it to "uncategorized" or something more meaningful than "none"

**Comment by Lavenblade** [comment]
Either way works for me, it's just an OCD thing with capitalization.

Are sub-folders going to be something you're interested in down the road after more important things are handled? I'm an organization freak by nature.

**Comment by kspearrin** [comment]
We're tracking sub-folders here: https://github.com/bitwarden/core/issues/9
