### ISSUE TITLE
Firefox sidebar opens on new window

### ISSUE THREAD

**Issue by nicolaimainiero** [bitwarden/browser#861]
Every time I open a new Firefox window, bitwarden activates the sidebar, which is annoying.
Please provide an option to change this behaviour.

**Comment by kspearrin** [comment]
Sounds like a bug in Firefox. We don't have any control of how the sidebar gets activated, other than with the hotkey that we provide.

**Comment by nicolaimainiero** [comment]
Thanks, for the fast respose. What amazes me is that if I disable the extension, the sidebar won't open either. I will further investigate this behaviour.
It also only happens when all Firefox windows are minimized. As soon as I open a new visible window, it doesn't happen.
Sounds really like a bug in Firefox. So I close this issue.
