### ISSUE TITLE
Auto-focus inputs (master password/search) don't get focused when BW is pinned to the Firefox overflow menu

### ISSUE THREAD

**Issue by ysrn** [bitwarden/browser#862]
Using Ctrl+Shift+Y when BW is pinned to the Firefox overflow menu doesn't move focus to the default input.

Similar to #837 I guess, but different use case, so hopefully something can be done about it (delayed call to focus(), perhaps).

**Comment by kspearrin** [comment]
I am not sure what the overflow menu is. Can you please list repro steps?

**Comment by ysrn** [comment]
1. Open Firefox
2. Right-click BW in the toolbar
3. Select "Pin to Overflow Menu"
4. Open the overflow menu (arrow icon at the far end of the toolbar, just before the hamburger button)
5. Click BW in the overflow menu

Result: BW popup opens but doesn't focus the input.

**Comment by kspearrin** [comment]
Looks like a Firefox issue. The popup window is not focused by Firefox whenever you open it from the overflow menu. If the window is not focused, I cannot focus any elements within the window. Should be reported to Bugzilla for Firefox.
