### ISSUE TITLE
Line-wrap broken in view mode

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#864]
When editing a vault item, the *Notes* section is properly line-wrapped.

But when viewing a vault item, the *Notes* section horizontally scrolls and scrolls to show all data on 1 line until it hits a hard return.

The line-wrap behavior in view mode needs to match that in edit mode.

**Comment by kspearrin** [comment]
This is actually the intended functionality at the moment since it helps with viewing and copy/pasting long lines of data.

**Comment by setyb** [comment]
Ooooh... I ***really*** don't like it.

I'm trying to think of a way to handle both cases.  The only thing I can think of is: *If there are no spaces in the strings, then scroll, otherwise wrap.*

Is that possible?

BTW, what types of long lines of data are people storing in notes?  Aren't attachments a better choice for storing data?

**Comment by kspearrin** [comment]
I updated it to `whitespace: pre-line` in the next version so that it will wrap on lines (unless the value is longer than the line, which which it would overflow with horizontal scrolling.

**Comment by setyb** [comment]
Sounds great.  Thanks Kyle!
