### ISSUE TITLE
Password updated with `XXXXXXX`

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#865]
So at this website <https://banking.ing.at/online-banking/>, after logging in, it seems to substitute the password field with lots of X, and is constantly detected by BitWarden and will ask if I want to update password (to `XXXXXXXXXXXXXXXXXX`). This problem occurs at Firefox and Chrome.
Imho, this could be both bug or feature request.

Best wishes.

**Comment by kspearrin** [comment]
I am not sure what could be done in this case other than adding a option to not prompt for password updates on certain websites. It seems XXXXXXXXXXXXX as a different password than is saved in your vault, so it offers to update it for you.

**Comment by setyb** [comment]
I think that would be a useful option.

There could additionally be a master toggle to not prompt for password changes on any website.

**Comment by kspearrin** [comment]
There already is a master toggle under settings > options.

**Comment by setyb** [comment]
Thanks Kyle; I forgot about that.

**Comment by gadfsgagfaq435** [comment]
hi 
am having a similiar problem at blizzard.com every time i log in bitwarden wants to replace the saved password with ................. 
this is both an annoyance and a bit dangerous bcos it can lead to password loss in worst case scenario (i guess there is still the "password bin" but still...)
cant bitwarden either specifically recognize if the mask of the website hides the real password or simply generally ignore XXXXXXXXXX and ........................... ? clearly no one is going to use that as a password and if they do its time to teach them not to :D

thanks.
