### ISSUE TITLE
Autofill not working on multiple sites

### ISSUE THREAD

**Issue by joeySeal** [bitwarden/browser#866]
OS Windows 10
In firefox 65 on https://www.ally.com/ for example if I right click in the login text box it finds the matching login but clicking autofill does nothing. https://www.fastmail.com/ has the same issue as do many other sites. If try the the same sites using chrome auto fill works. Sometimes but usually not it will work on the second try.
[Screenshot](https://i.imgur.com/WnyVe9J.png)

**Comment by kspearrin** [comment]
Unfortunately, I am not able to reproduce. Autofilling works every time from the context menu.

**Comment by joeySeal** [comment]
I regularly have the issue on multiple sites, do you have an suggestions on how I can provide you with useful troubleshooting info?

**Comment by xhoy** [comment]
@kspearrin what info do you like to reproduce, we just started using bitwarden and it sometimes doesn't even popup to save the password in the first place.

**Comment by alexcanepa** [comment]
Same issue as @xhoy on MacOS Firefox 74

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
