### ISSUE TITLE
Custom Equivalent Domains

### ISSUE THREAD

**Issue by a-m-s** [bitwarden/browser#87]
Custom Equivalent Domains don't appear to work in the Chrome browser extension. When I visit a site with an equivalent domain I set up myself it only shows the matches with the exact domain.

However, when I try a Global Equivalent Domain all seems well (for example, youtube.com shows my google.com login).

When I visit the same website on Android the app gives me the full list I expect, so that's working.

**Comment by kspearrin** [comment]
This is because the update to the extension to support these has not been published yet. It will come with version 1.9.x
