### ISSUE TITLE
selfhost configuration - serverurl doesnt trim whitespaces

### ISSUE THREAD

**Issue by messimuc** [bitwarden/browser#871]
A user in my selfhosted environement copy and pasted the serveradress to the extension configation with an additional whitespaces at the end. Login wasnt possible. It was really hard to track down the misstake as it is not visible in client config gui or the server log. The extension would be much more robust if this kind of user error is dealt with automatically. Chrome Extension installed 02/15/19

**Comment by kspearrin** [comment]
Should be resolved with https://github.com/bitwarden/jslib/commit/c37a52be8568fe749bb6e4c190dc4c736f02fb80
