### ISSUE TITLE
deleting mutliple folders

### ISSUE THREAD

**Issue by hubgitbb** [bitwarden/browser#875]
i have done a bulk import from keepass and now there are a lot of folders that a want to remove. how can i delete multiple folders at once?

**Comment by kspearrin** [comment]
Folders can only be deleted one at a time. You can bulk delete items from the web vault, however. You may also want to just purge the entire vault and try again. You can do this from Settings > My Account in the web vault.

**Comment by hubgitbb** [comment]
thx
