### ISSUE TITLE
How safe is BW against memory attacks?

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/browser#876]
Hi,

Have you read https://www.forbes.com/sites/kateoflahertyuk/2019/02/20/password-managers-have-a-security-flaw-heres-how-to-avoid-it/ yet?

It doesn't mention bitwarden in the article but I was wondering how vulnerable bitwarden client side apps are to these memory attacks (desktop, mobile and browser).

Cheers

**Comment by kspearrin** [comment]
Please don't open the same question issue in multiple repos.
