### ISSUE TITLE
[Chrome Extension] My Vault fails to display results

### ISSUE THREAD

**Issue by Lavenblade** [bitwarden/browser#88]
Google Chrome Version: 56.0.2924.87 (64-bit)

On occasion, 'My Vault' fails to display any results when nothing is typed into the search bar. I am not sure of a workaround. Most of the time it will not display anything unless I type into the search box.

I do not know if this is an issue in other browsers or older versions of google chrome.

Screenshot:
![deyhw7d](https://cloud.githubusercontent.com/assets/18235822/23087861/5790847a-f52c-11e6-89fa-5aff363a089f.png)

**Comment by kspearrin** [comment]
That's odd. When it happens, can you right click into the popup and inspect it to see if there are any JS errors in the console?

**Comment by Lavenblade** [comment]
Sure, no problem.

`Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: login in vaultFolderLogins = (vaultLogins | filter: { folderId: folder.id }
                            | filter: searchLogins() | orderBy: ['name', 'username']), Duplicate key: object:16, Duplicate value: {"id":"0301528c-b22c-49bd-ba76-a71800057f02","folderId":null,"favorite":false,"name":"Outlook","uri":"http://live.com","domain":"live.com","username":"lavenblade@live.com","password":"xProtocol256","notes":null}
http://errors.angularjs.org/1.5.9/ngRepeat/dupes?p0=loginNaNn%20vaultFolderLogins%20%3D%20(vaultLogins%20%7C%filter%3A%20%7B%folderId%3A%folder.id%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%filter%3A%searchLogins()%20%7C%orderBy%3A%20%5B'name'%2C%20'username'%5D)&p1=object%3A16&p2=%7B%id%22%3A%c-b22c-49bd-ba76-a71800057f02%22%2C%folderId%22%3Anull%2C%favorite%22%3Afalse%2C%22name%22%3A%Outlook%22%2C%22uri%22%3A%22http%3A%2F%2Flive.com%22%2C%domain%22%3A%22live.com%22%2C%22username%22%3A%22lavenblade%40live.com%22%2C%22password%22%3A%22xProtocol256%22%2C%22notes%22%3Anull%7D
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:68:12
    at ngRepeatAction (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:30441:21)
    at $watchCollectionAction (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:17615:13)
    at Scope.$digest (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:17755:23)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:17952:26
    at completeOutstandingRequest (chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:6035:10)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/lib/angular/angular.js:6314:7`

**Comment by kspearrin** [comment]
This will be fixed in the next release (1.9.x). Thanks for the info!
