### ISSUE TITLE
clipboardRead permission requested

### ISSUE THREAD

**Issue by IanSavchenko** [bitwarden/browser#883]
Hi,

Chrome disabled version 1.39.1 of extension due to a new permission requested. Can I ask what is the purpose of it? Looking quickly through the code, I see that a `readFromClipboard` utility function was introduced recently, but is never used.  https://github.com/bitwarden/browser/commit/91a0566f2c745718773b71b693bacefe688924de#diff-051a8a7bcae8db1e4cee8eb09b52e619

Btw, thanks for such a nice product from a premium subscriber and promoter 🙌

**Comment by kspearrin** [comment]
This permission was added to support the new auto-clear clipboard feature: https://community.bitwarden.com/t/automatically-clear-clipboard-after-x-seconds-when-using-copy-functions/29

**Comment by IanSavchenko** [comment]
Awesome, thank you! 

A small suggestion for the future: mention this kind of things in the changelog or have the permission optional and requested when a new feature is activated by the user.

Keep up the good work! 👏

**Comment by kspearrin** [comment]
> have the permission optional and requested when a new feature is activated by the user.

Unfortunately this is not possible with web extensions.

**Comment by IanSavchenko** [comment]
> Unfortunately this is not possible with web extensions. Permissions have to be requested up front in the manifest.

I believe it is possible and not too hard, actually. Check out these links for [Chrome](https://developer.chrome.com/apps/permissions) and on [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions). (I just happen to work with web extensions).

**Comment by kspearrin** [comment]
Wow, TIL. Thanks.

**Comment by kspearrin** [comment]
Leaving open for visibility.

**Comment by ycecube** [comment]
Looks like this functionality not just clears the copied data from bitwarden, but anything from my current clipboard, this is not really good as I can lose copied text not related to bitwarden.
