### ISSUE TITLE
Firefox password history is blank (empty) for all my sites.

### ISSUE THREAD

**Issue by JackDinn** [bitwarden/browser#884]
I don't know if this happened just after the last firefox browser addon update or not but all my password histories are missing. It shows i have "X" number of history passwords 
![zz_20190306-173029](https://user-images.githubusercontent.com/5557560/53900948-96441780-4035-11e9-922f-7cf92150f287.png)

but when i click it its blank.

![zz_20190306-170821](https://user-images.githubusercontent.com/5557560/53900449-78c27e00-4034-11e9-9805-fee93f0a2323.png)

I have checked with the linux appimage desktop GUI ver 1.12.0 and it works properly, the password history are all showing.

Manjaro KDE, Bitwarden firefox addon ver 1.39.1

**Comment by kspearrin** [comment]
Will be fixed in 1.39.2 . Thanks.
