### ISSUE TITLE
With PIN unlock activated password autofills even with locked vault on Chrome

### ISSUE THREAD

**Issue by Lectos27** [bitwarden/browser#885]
As per the title, when I activate the PIN unlock, set the PIN and subsequently lock the vault; I can go to a webpage where a login exist in the vault and press the shortcut keys Ctrl+Shift+L and the user/password is autofilled. Again, all this while the vault is supposedly Locked. 

This behaviour does not happen when PIN unlock is unticked and vault is locked

This might be a related issue to the one posted in here: [(1)](https://community.bitwarden.com/t/invalid-pin-unlocks-my-vault-in-firefox/4923) and here [(2)](https://community.bitwarden.com/t/invalid-pin-unlocks-my-vault-in-firefox-cont/4951). So it seems that while the PIN unlock is selected, the vault is not really locked.

Using version 1.39.1 of the Chrome plugin

**Comment by kspearrin** [comment]
Should be fixed in 1.39.2. Going live now. Thanks
