### ISSUE TITLE
BW populates "password" field with user ID. Nothing in "user" field.

### ISSUE THREAD

**Issue by johnmudd** [bitwarden/browser#89]
Seems to ignore user field and treat password field as the user field.

Web site: https://customer.publix.com/

[Sign In to My Publix.html.txt](https://github.com/bitwarden/browser/files/785077/Sign.In.to.My.Publix.html.txt)

**Comment by kspearrin** [comment]
Their website is doing some weird things to try to prevent bots which is focused the extension. I'll have to look for a way around it.

**Comment by kspearrin** [comment]
Seems this website is no longer around.
