### ISSUE TITLE
Vivaldi, FIDO U2F not offered

### ISSUE THREAD

**Issue by roccolord** [bitwarden/browser#893]
Vivaldi 2.4.1483.4 doesn't offer the FIDO U2F option (I have FIDO, Yubikey and Duo enabled). It's not the default and it's not in the list of selectable 2FA.

Works in Opera 60.

**Comment by kspearrin** [comment]
How do you get vivaldi 2.4? 

Mine shows 2.3 is up to date.

**Comment by roccolord** [comment]
Hi, snapshots are here:
https://vivaldi.com/blog/snapshots/

**Comment by Hinton** [comment]
Hi @roccolord,

We moved from U2F to WebAuthn a while back which should have resolved this isuue.

If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by tuxfy** [comment]
5.1.2567.66 (Stable channel) stable (64-Bit)  is now not working anymore. Firefox works fine, Chromium not.
