### ISSUE TITLE
Copying password or username has missing $VALUE$

### ISSUE THREAD

**Issue by Laurisade** [bitwarden/browser#895]
Brave latest stable version.

While copying password or username from the browser extension, the text is missing $VALUE$ string.
![image](https://user-images.githubusercontent.com/6094860/54486769-a52c9480-4895-11e9-9a57-71d3050c1a2f.png)
At least with Estonian language ($VALUE$ is copied).

**Comment by kspearrin** [comment]
I corrected it on crowdin. Can you confirm that is should be "$VALUE$ on kopeeritud" ?

**Comment by Laurisade** [comment]
Hello!

Yes, it is correct. 
Current Crowdin translation is

$VALUE$ on kopeeritud

So it should work? But it is not :)

**Comment by kspearrin** [comment]
That's because I just corrected it. It didn't have `$VALUE$`' before.

**Comment by kspearrin** [comment]
Will be fixed next version.
