### ISSUE TITLE
Edge extension keeps forgetting user when restarting Edge

### ISSUE THREAD

**Issue by adrianghc** [bitwarden/browser#898]
Today's excellent update to version 1.39.3.0 introduces an unfortunate issue where every time Edge is restarted, the Bitwarden extension has forgotten who I'm signed in as. When prompting for the password, it says I'm signed in as $1 and the password does not work. The only solution is to sign out and back in, until the next time I restart Edge. This is on version 1803, build 17134.648. I've already tried uninstalling and reinstalling the Bitwarden extension, to no avail.

**Comment by kspearrin** [comment]
sigh....

let me revert it

**Comment by adrianghc** [comment]
Have you checked if this is also an issue on newer versions? Because in that case you could revert it only for 17134 and leave the newer version of Bitwarden for newer Windows versions.

**Comment by kspearrin** [comment]
I am on 1809 and it seems pretty broken too. I'll just revert it until the new Chromium version of Edge comes out and hope that one doesn't suck too :)

**Comment by adrianghc** [comment]
Maybe it works on 1903. Could we do something? Since 1903 isn't out yet anyway but I'm going to upgrade as soon as the final build reaches Insiders, how about you revert it for all versions up to 1903 and when 1903 rolls around, I'll let you know if the bug is still there on 1903? In that case, you could still revert it for 1903 but if it turns out 1903 fixes the issue, even better.

**Comment by kspearrin** [comment]
Is 1903  with the new Chromium Edge?

**Comment by adrianghc** [comment]
Nope, not yet, but since there is that one issue that 1903 fixes (the one with websites signing me out), I thought maybe it's related to Bitwarden's problem so that one would be fixed in 1903. I'd just rather wait until the final 1903 build comes out, probably this week, before upgrading to 1903 again. But when I do, I can tell you if it indeed fixes the issue.

**Comment by adrianghc** [comment]
Or alternatively, I could fire up a VM with 1903 real quick and let you know in 20 minutes or so. How's that sound?

**Comment by kspearrin** [comment]
Unfortunately I don't see a way to limit the submission to certain windows versions. Appears to be all or nothing.

**Comment by adrianghc** [comment]
Is that different with Edge extensions? Because I was pretty sure that was possible with normal apps.

**Comment by kspearrin** [comment]
I can't find anywhere. I submitted a new 1.39.4 (which is actually the old 1.35.2). You should have ~24 hours or so to test since it won't be live until it gets reviewed.

**Comment by adrianghc** [comment]
Very well then, I'll keep you posted.

**Comment by adrianghc** [comment]
Well, no luck on 1903 either, I'm afraid.
