### ISSUE TITLE
Update manifest to fully support FF 66 keyboard shortcut manager

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#899]
`manifest.json` currently contains a blank description for the keyboard shortcut to open bitwarden in the sidebar.  This causes confusion in the new FF 66 keyboard shortcut manager.

I can submit a pull request to fix this, or you can do it, whichever you prefer.

**Comment by kspearrin** [comment]
What kind of confusion? I am not sure why it is blank to being with. Maybe we should remove it like `_execute_browser_action`? Does the browser provide a description for those special commands in Firefox like on Chrome?

**Comment by setyb** [comment]
> What kind of confusion? I am not sure why it is blank to begin with. Maybe we should remove it like `_execute_browser_action`? Does the browser provide a description for those special commands in Firefox like on Chrome?

Here is how it currently looks in Firefox:
![bw_screenshot](https://user-images.githubusercontent.com/32158528/71778708-011bf300-2f66-11ea-97cf-ecf297047a08.png)

I'm working on the fix now, and will have it done soon.

**Comment by setyb** [comment]
I fixed the missing string, replaced a default string with a custom string, removed non-standard periods, and improved the ordering.

I hope this helps! :)

**Comment by jay-dee7** [comment]
Would we be ever able to add custom shortcuts to specific credentials? as in there's a few websites i have to login daily, it would be a great addition i think. If it's already a thing, please let me know/ I couldn't find anything so far

**Comment by setyb** [comment]
@jay-dee7 That's an interesting idea. To my knowledge, it's not currently possible.

**Comment by setyb** [comment]
@cscharf Good question.  I think 2 things maybe need to occur:

1. Perhaps move the suggestion by @jay-dee7 to another issue so it doesn't get lost.
2. See if my code resolving this issue made its way into the release.  I did not sign the CLA (see https://github.com/bitwarden/server/issues/1115).
