### ISSUE TITLE
[Edge] Bitwarden becomes a small pop-up window after clicking

### ISSUE THREAD

**Issue by TiSpH** [bitwarden/browser#901]
Bitwarden does not show up at proper position, indeed, it becomes a pop-up window and not be able to detect the site which I opened in the main window (so I have to copy and paste my accounts manually)

Edge: 44.17763.1.0
EdgeHTML 18.17763
Bitwarden: 1.39.4
Windows Build: 17763.253

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/744
