### ISSUE TITLE
Autofill payment card security code not handling leading zeroes

### ISSUE THREAD

**Issue by IOI-655321** [bitwarden/browser#903]
I was trying to autofill some payment card details id saved for a work test card. I have to use 000 for security code but this only autofilled to a single 0. Non leading zero entries work perfectly and changing it to 010 autofilled to 10.

Can this be fixed please?

This was in Firefox extension Version: 1.39.3

**Comment by kspearrin** [comment]
I am not able to reproduce. It autofilled correctly for me. See below:

![image](https://user-images.githubusercontent.com/1190944/54996890-dd705900-4fa0-11e9-9b33-c40947cbbdc6.png)

https://stripe.dev/elements-examples/

**Comment by IOI-655321** [comment]
Hmm ok must be a site specific issue then.  Thanks for looking into it.
