### ISSUE TITLE
Highlighting skip the last character (firefox only)

### ISSUE THREAD

**Issue by koopernick** [bitwarden/browser#904]
Hello,

Since today (I don't know exactly when it started), when I highlight some text from my secure note, it always skip the last character (see attachment) from selection.

![kozdklz](https://user-images.githubusercontent.com/4642079/54919649-a434dc00-4f01-11e9-92b0-97b1c8b32d4e.png)

I only have this issue from the firefox addon. Works from vault and chrome addon.

**Comment by kspearrin** [comment]
Sounds like a problem with Firefox. We don't change anything about how your highlighting of notes works.

**Comment by touch444719** [comment]
All right, I'll try a ff reset.

**Comment by dezertdezine** [comment]
I'm seeing this too, since v1.39.0

**Comment by kspearrin** [comment]
If you reinstall 1.38 the problem goes away?

**Comment by dezertdezine** [comment]
This is working OK for me now.
Firefox: 68.0.2
Bitwarden: 1.41.0
