### ISSUE TITLE
Any chance of a changelog?

### ISSUE THREAD

**Issue by yb66** [bitwarden/browser#907]
Hi there,

To see the changes I had to go over to the Firefox Addons page and combine that with browsing through the commits. It's obviously not ideal, any chance of adding a changelog?

Regards,
iain

**Comment by kspearrin** [comment]
At the moment I don't have the resources to compile a full changelog on each release. I will briefly cover new features and anything major in the release notes, however. https://github.com/bitwarden/browser/releases

**Comment by yb66** [comment]
Thanks. I wasn't thinking of anything too onerous, I use the template from http://keepachangelog.com/ and keep things pretty brief, but I appreciate the time pressures.

Great product, thanks for your effort.

Regards,
iain
