### ISSUE TITLE
Autocomplete fails for umlaut domains

### ISSUE THREAD

**Issue by magicsunday** [bitwarden/browser#910]
If I store a password for a umlaut domain (a domain containing ä, ö or ü), the password autocomplete fails. If have to use the puny code style type of the domain to get it working. Which is not very handy.

Seems not only a issue in the browser extension, but also in the IOS app.

**Comment by kspearrin** [comment]
Can you provide an example website where I can test this, please?

**Comment by magicsunday** [comment]
https://obs.bürgerhaus.de/

**Comment by kspearrin** [comment]
When I visit this website, in my browser tools if I check `document.location.href`, I get the following:

```
> document.location.href
"https://obs.xn--brgerhaus-q9a.de/"
```

Any idea why?

**Comment by kspearrin** [comment]
I guess that is the puny code version of the domain. The browser doesn't report it the way that includes the umlaut.

**Comment by magicsunday** [comment]
Yes https://obs.xn--brgerhaus-q9a.de/ is the puny code version of the domain. If I store this one as url in the vault record, the autocomplete is successful.

**Comment by kspearrin** [comment]
For now, we can only support puny code versions of the domain. An external library would be required to decode it back if we wanted to support it further in the future.

**Comment by magicsunday** [comment]
Are there no external libs yet?

**Comment by Crocmagnon** [comment]
As a workaround, is there somewhere we can convert a domain with accents to its puny code version ? Non ascii characters in domain names will likely appear more and more

**Comment by kspearrin** [comment]
If you view the website in your browser then open Bitwarden, click "Add New" from the "current tab" page. The prefilled info for the website is the puny code version, which is what the browser reports the domain as.

**Comment by cvvvlad** [comment]
Hello! Autocomplete not working when I'm using russian punycode in Regular Expressions. 
The website I'm trying is `https://президентскиегранты.рф/` (punycode `https://xn--80afcdbalict6afooklqi5o.xn--p1ai`).
I tryied this regular expressions:
`^https:\/\/президентскиегранты\.рф` and `^https:\/\/xn--80afcdbalict6afooklqi5o\.xn--p1ai` but it is not working on main page.
