### ISSUE TITLE
bitwarden not working in private windows on firefox

### ISSUE THREAD

**Issue by shawn-j** [bitwarden/browser#911]
just got bitwarden a week ago.  it's working great, though a few days ago it stopped working in private windows on ff.  i right click, and all the login options are there.  but they dont' autofill. worked just fine a few days ago.  am i missing something?  thanks in advance

**Comment by kspearrin** [comment]
If you create a new firefox user profile, does it work there?

**Comment by shawn-j** [comment]
> 
> 
> If you create a new firefox user profile, does it work there?

just tried it- yes, but i have to do it twice.   so i right click, then click on bitwarden>acct, and it does nothing.  then i do that again, and it autofills like it should.

**Comment by devurandom** [comment]
This seems to have duplicates in #1444 and #1050.

**Comment by cscharf** [comment]
This is a duplicate of #136
