### ISSUE TITLE
Master Password and Swiftkey

### ISSUE THREAD

**Issue by ericrbg** [bitwarden/browser#912]
Not sure if this should be in this repo, or Swiftkey's, but I've found that if I turn the password visibilty on and then type my master password, Swiftkey will remember the order of my password when I'm typing it to unlock the Vault, which is a serious security issue. 

**Browser:** FF Nightly Mobile
**Version:** 1.39.9

**Comment by kspearrin** [comment]
The input is marked with several attributes informing the browser not to remember the values from this input:

```
<input appinputverbatim="" id="masterPassword" name="MasterPassword" required=""  autocomplete="off" autocapitalize="none" autocorrect="none" spellcheck="false" inputmode="verbatim"  type="text">
```

Not sure what else we could do to tell SwiftKey not to remember values typed in this field.

**Comment by ericrbg** [comment]
Definitely a SwiftKey bug then. I'll close and report to them.
