### ISSUE TITLE
Autofill not working on Paymentwall

### ISSUE THREAD

**Issue by zwzy** [bitwarden/browser#913]
Auto fill does not properly work on the Paymentwall merchant login.
It fills in the email address, but not the password.

URL: [https://api.paymentwall.com/pwaccount/signin](url)

**Comment by kspearrin** [comment]
For whatever reason, they mark their input fields as `readonly` until you focus them. Then they can be filled.

**Comment by kspearrin** [comment]
I added some fixes for next version to focus fields explicitly during the autofill operation.

**Comment by zwzy** [comment]
Thanks!
