### ISSUE TITLE
Text is not selectable when Bitwarden is opened in the Firefox sidebar.

### ISSUE THREAD

**Issue by nonylours** [bitwarden/browser#914]
Hi.
I can't select text when Bitwarden is opened in the Firefox sidebar (Shift+Alt+Y). This makes difficult to copy a part of a secure note.
It only affects the sidebar. The text is selectable if I open Bitwarden with the top right button.
I am using Windows 10.

**Comment by kspearrin** [comment]
Sounds like a Firefox bug. Have you tried reporting it to Mozilla?

**Comment by nonylours** [comment]
No, I don't have any other add-ons using the sidebar so I was supposing it was a Bitwarden problem. I will check Firefox bug reports. Thanks.

**Comment by esa1975** [comment]
Sorry to bump this. @nonylours any luck with this from the Firefox end? If you have an open issue can you link to it here? I am unable to find anything on their end. Thanks!

**Comment by kachkaev** [comment]
Same issue here and it is quite inconvenient. I can only borrow data from a Bitwarden card by pressing ‘copy value’ next to _some_ standard and as well as all custom fields. When it comes to copying a part of a note, grabbing text is simply not possible. It is necessary to press ‘edit’ to get that stuff.

![Kapture 2020-05-30 at 16 56 30](https://user-images.githubusercontent.com/608862/83333071-a5486280-a296-11ea-869b-8cd556395e7d.gif)


If Firefox limits text selection in the sidebar only to the input fields, how about making all field values read-only textareas?

Perhaps, in addition to making login and password field names draggable, other filed names coudl be draggable too? I quite liked the idea of dragging and dropping text like that.

**Comment by nonylours** [comment]
I don't know if the problem was fixed by bitwarden or mozilla, but the text is now selectable on the latest versions. Thanks.
