### ISSUE TITLE
Autofill doesn't work on Amtrak.com

### ISSUE THREAD

**Issue by eborenst** [bitwarden/browser#916]
Bitwarden isn't able to fill in my login info on Amtrak.com. Amtrak also doesn't let you paste passwords, so you have to manually type the info in every time.

Firefox 66.0.2, Bitwarden 1.39.3.

Works fine in LastPass.

**Comment by kspearrin** [comment]
This is happening because (for performance reasons) we only parse the first 50 form elements on the page. Amtrack has 150 on its homepage, and the login form is after the first 50.

Not sure what the solution is at the moment.

**Comment by Blazeflack** [comment]
Would this be the same limitation that prevents me from auto-filling anything but the first field on selvbetjening.medarbejderkoncepter.dk (after clicking one of the 2 buttons)?

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
