### ISSUE TITLE
First unlock with password doesn't switch to PIN entry

### ISSUE THREAD

**Issue by krystof-k** [bitwarden/browser#919]
If I have PIN unlock turned on and I have to fill password after browser restart, even if I do with the correct password, nothing happens. I have to close the extension window, open it again and then I can finally fill in the PIN.

Actually, it would make sense to not require PIN immediately after entering correct password.

**Comment by kspearrin** [comment]
I am not able to reproduce the issue. After restarting the browser, I simply enter master password. Subsequent locks only require PIN.

Please provide steps to reproduce the issue.

**Comment by krystof-k** [comment]
Hmm, this is weird, I wasn't able to reproduce it either. Closing and I'll reopen if it happens again.

**Comment by gmcinalli** [comment]
I'm often experiencing this issue, now that I'm trying to reproduce it I can't, the next time it happens I'll try to remember the exact steps.

However, I can certainly say that it occurs only with the Chrome extension.

**Comment by krystof-k** [comment]
Yep, still happening for me too.

**Comment by gmcinalli** [comment]
@krystof-k Have you been able to reproduce it?

**Comment by krystof-k** [comment]
Unfortunately not. It always behaves fine when I try to reproduce it.

**Comment by gmcinalli** [comment]
It just happened to me now, but I have no idea how to reproduce it.
