### ISSUE TITLE
Consistent Loss of Vault Access on Firefox (Nightly)

### ISSUE THREAD

**Issue by Anaithsol** [bitwarden/browser#92]
Is it intentional for the Firefox addon to log you out of your vault after a set amount of time regardless of activity? Despite my lock option being set to never in the settings menu, it seems that within every 30 minutes or so, I have to login yet again and provide my verification code to regain access.

The Google Chrome extension doesn't exhibit this same problem after giving it a pretty thorough test.

**Edit:** I don't know if this has any bearing on the issue at hand or not but it seems the lock option always resets to never in the settings menu no matter what you change it too.

**Comment by kspearrin** [comment]
Thanks for the report. This has been fixed with v1.9.7. You can update directly from AMO with the nightly now to get the fix.
