### ISSUE TITLE
Autofill username and password when both fields are of type "password" (hidden)

### ISSUE THREAD

**Issue by wutr** [bitwarden/browser#920]
Bitwarden 1.39.3 on Firefox 66 (Linux) is unable to distinguish between username and password when both have to be filled in an HTML password input box. Instead, Bitwarden fills the password in both boxes.

I have tried custom fields in all possible combinations with leaving/removing data from the default username/password fields in bitwarden, but I can't get it to work. When leaving both username and password fields empty and using custom fields only, bitwarden complains that it is unable to autofill. When only entering the username bitwarden ignores it, because the usename has to be filled in an HTML password box as well which it doesn't seem to like.

Am I missing something? I expected Bitwarden to use the data in the custom fields when username and password were left empty. Or is there a trick for that?

**Comment by kspearrin** [comment]
It sounds like you are not correctly targeting the input fields with your custom field names. They should always be filled first, before username and password.

**Comment by wutr** [comment]
It could be, but for the following:

`<input type="PASSWORD" name="LOGINID" maxlength="2147483647" class="LOGINIDCSS" id="LOGINID" tabindex="1">`

in the custom fields I've used `LOGINID` as the name. Is that not right?

**Comment by kspearrin** [comment]
Should be correct. Can you link the webpage in question?

**Comment by wutr** [comment]
Preferably not, but I can send you the link directly if that's possible?

**Comment by kspearrin** [comment]
If you can email it to support@bitwarden.com and reference this issue and mention to direct the email to @kspearrin I can investigate further.

**Comment by wutr** [comment]
Thanks, I've sent an email with the link.

**Comment by kspearrin** [comment]
I tried the URL that you sent and it autofilled as expected with a custom field named "LOGINID" with the username and the password stored in the normal password field.

**Comment by wutr** [comment]
Thanks for having a go, without sounding condescending, are you sure the username and password being filled by your instance of Bitwarden are different? I've tried again with username empty, password as it should be, and "LOGINID" set to the username, but no luck, it still fills the password in both boxes and ignores "LOGINID". It then subsequently throws a couple of errors in a javascript dialogue:

`Access violation at address 029016AE in module 'PyramidSelfservice.dll'. Read of address FFFFFFFE`

Anything I can do to get your results?

**Comment by kspearrin** [comment]
After autofilling the fields, I checked with the following via console.

![image](https://user-images.githubusercontent.com/1190944/56581863-eeae8480-65a3-11e9-8458-a19d4d2850ff.png)

This mathes the values I have stored in Bitwarden.

**Comment by wutr** [comment]
Ok, I ran the same in console but for me (surprise surprise) LOGINID and PASSWORDID are the same value.

The final thing I could think of was to try with the Bitwarden username and password fields empty, and just have "LOGINID", but then it complains:

`Unable to auto-fill the selected item on this page. Copy and paste the information instead`

I've tried with all addons disabled too, no change.

**Comment by kspearrin** [comment]
I am not sure, but here is the item I created:

![image](https://user-images.githubusercontent.com/1190944/56583167-f7548a00-65a6-11e9-892a-147c71e609bf.png)

**Comment by wutr** [comment]
That's all I have as well... Are you on Firefox 66.0.3?

**Comment by kspearrin** [comment]
This was in Chromium. I can reproduce the issue in Firefox. No clue why there is a difference here.

**Comment by wutr** [comment]
Looking at the Browser Console in Firefox, anytime any information is typed into either LOGINID or PASSWORDID (including when autofilled) a POST with the following Request URL is made:

`https://*stuffremoved*/PyramidSelfservice.dll/*stuffremoved*/$/callback?callback=LOGINID.DoOnAsyncKeyPress&x=0&y=0&which=100&modifiers=`

My knowledge of anything web related is very limited, but I guess the `LOGINID.DoOnAsyncKeyPress` call is where it might go wrong when autofilled by Bitwarden.

It's fine when I copy and paste (ie. no errors but still a POST).

It works fine with Lastpass

**Comment by kspearrin** [comment]
So the reason it doesn't work on Firefox is that this webpage is reporting that the height of the HTML document area is only 16 pixels.

```
document.getElementById('LOGINID').ownerDocument.documentElement.scrollHeight

16
```

On Chrome this is correct, showing full height of browser window (1042 in my case).

```
document.getElementById('LOGINID').ownerDocument.documentElement.scrollHeight

1042
```

The reason this is significant is that we only autofill custom fields if they are "viewable" in the browser window area. Since Firefox is reporting that this input field is not viewable on screen, it skips it during the custom field filing checks.

**Comment by wutr** [comment]
OK that makes sense.

Before I end up trying (and failing) a greasemonkey userscript to either change the scrollheight or the type of the input field, is there a way to make bitwarden not fill in the password in both boxes? I know they are both of type "password", but the ID is different. Is that ignored?

**Comment by kspearrin** [comment]
The only way to stop it would be to fill it something else using a custom field, which in this case is failing.

**Comment by wutr** [comment]
[https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight)

How did you determine Firefox reports the field as not viewable? I understand it reports `scrollHeight=16`, but looking at the inspector it says `height=21px` (from the LOGINIDCSS class).

**Comment by kspearrin** [comment]
"Viewable" is defined as the element existing in the area determined by `document.getElementById('LOGINID').ownerDocument.documentElement.scrollHeight`

**Comment by wutr** [comment]
OK that seems to be the issue then.

When I enter this in the console:
`document.documentElement.style.height = 2000`

followed by this:
`document.getElementById('LOGINID').ownerDocument.documentElement.scrollHeight`

the result is `2000` and autofill works (with empty username field and custom `LOGINID`).

**Comment by wutr** [comment]
Here's my user script "fix". It works. Thanks for your help @kspearrin 

```
// ==UserScript==
// @name     Hidden input fields - Bitwarden autofill fixer
// @version  1
// @include  *://change.theURL.com/*
// @run-at   document-end
// @grant    none
// ==/UserScript==

document.documentElement.style.height = "100%"
```
