### ISSUE TITLE
Not updated on Safari Extensions Galery ?

### ISSUE THREAD

**Issue by SkYNewZ** [bitwarden/browser#922]
Hi,
I can see the latest version is [v1.39.3](https://github.com/bitwarden/browser/releases/tag/v1.39.3) but, on Safari, while "auto update extensions" is enable, I have the v1.37.

Any idea about this difference ?

<img width="979" alt="image" src="https://user-images.githubusercontent.com/26750012/56616239-2f96af80-661d-11e9-9caa-53aa9ba4b086.png">

**Comment by kspearrin** [comment]
Yes, Apple has now stopped approving updates to Safari extensions in favor or their new way of building extensions (Safari App Extension), which Bitwarden is not compatible with. See here for more info: https://github.com/bitwarden/browser/issues/664

**Comment by Moxville** [comment]
As compared to Github latest version chrome browser extension still shows v1.39.3
Has Google Chrome also stopped approving new extension updates due to some issues ?
