### ISSUE TITLE
Add "Copy TOTP" to context menu

### ISSUE THREAD

**Issue by dpantel** [bitwarden/browser#924]
There are a lot of GitHub issues and forum feature requests surrounding TOTP auto-copying, auto-filling, and having shortcut buttons in the extension.  Unfortunately they seem all over the place and with a lot of only-tangentially-related stuff thrown in.

The reason this is a **bug** is this old issue: #136 .  The current workaround for Firefox in Private mode is to auto-fill user/pass via the context menu.  However that process breaks down on sites that have 2FA enabled as there is no way to get it without opening a non-private window, or using another device.

**Comment by Crocmagnon** [comment]
You could still <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>, that autofills your credentials and then copies your TOTP to the clipboard.

**Comment by dpantel** [comment]
@Crocmagnon

That feature is buggy and does not work in my browser.

**Comment by 4x0v7** [comment]
@Crocmagnon Thanks for the suggestion! I did not know that keyboard shortcut, it works for me!
The context menu filling does indeed copy the TOTP to the clipboard :)

**Comment by RoiArthurB** [comment]
I'm afraid they do not want to add a TOTP quick copy icon in the browser plugin : https://github.com/bitwarden/browser/pull/968

I hope they'll change their mind later and add it (it's the only feature missing from my pov)

**Comment by olavinto** [comment]
Shouldn't this be closed since copying TOTP is now possible from the context menu?

**Comment by dpantel** [comment]
@RoiArthurB The issue you mention has nothing to do with this one, as I clearly stated in the original message.

@olavinto You're absolutely correct!  No idea when that made it into the code base, but it's there now, at least on Firefox. Closing.
