### ISSUE TITLE
Firefox addon disabled, reporting legacy, will not reinstall

### ISSUE THREAD

**Issue by chrisdlangton** [bitwarden/browser#927]
Self-explanatory, Firefox addon was disabled by mozilla, the addon page us reporting it is a legacy plugin and asks you to find alternative replacements. It is still in the addon store but it will not reinstall, or install once removed.

**Comment by kspearrin** [comment]
This is a bug in Firefox that affects all addons. There is nothing we can do. We'll have to wait for Mozilla to fix it.

**Comment by chrisdlangton** [comment]
many addons are uneffected, i doubt you've gone beyond "not my problem" which is frustrating to learn ...

**Comment by chrisdlangton** [comment]
@kspearrin damn.. i just realised you probably don't even use firefox, have not tested your own theory.. 
if you had done so you'd see most addons are not effected..

**Comment by iGEL** [comment]
@chrisdlangton No need for false accusations.  :unamused:

It is a bug in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 or https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by chrisdlangton** [comment]
What accusation would that be? Clearly you're over sensitive and ignorant.
Let me make an accusation now, you assume you're being effected by a common issue, and show no evidence you have investigated to _prove_ this bug report is in fact caught up in a common issue you assume is the cause.

**Comment by chrisdlangton** [comment]
Confirming you guys fixed this issue. @Crocmagnon  thank you for _actually_ investigating. 
"Not my problem" attitudes really show maturity, glad someone here is more evolved.

**Comment by kspearrin** [comment]
@chrisdlangton As explained previously, this was a problem with Firefox itself. No fix was deployed by Bitwarden. Mozilla has since resolved the problem, which is why Bitwarden now works again in Firefox. See https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by chrisdlangton** [comment]
@kspearrin According to you're own team, you sigend the plugin and now it works. go figure..
Anyway your team have actually investigated this now and that is all i asked for so no more drama necessary, i don't need you to agree, i just wanted to have this issue looked at and not dismissed so easily.

**Comment by kspearrin** [comment]
I am the only team member that has reported anything here. Again, no changes were made on our end. My initial reply was made after already investigating the problem and closing several other duplicate issues. I am sorry that was not clear. Our Firefox addon has always been signed. This has always been a requirement of AMO. If you read the blog link I provided to you by Mozilla, you can better understand the problem that existed with Firefox.
