### ISSUE TITLE
Firefox 66 - bitwarden is disabled.

### ISSUE THREAD

**Issue by Cash4Programming** [bitwarden/browser#928]
Firefox just updated to version 66 and disabled all of my add-on.  No way to install or update. :(  It says the download is not available.

**Comment by kspearrin** [comment]
This is a bug in Firefox that affects all addons. There is nothing we can do. We'll have to wait for Mozilla to fix it.

**Comment by iGEL** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 or https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
