### ISSUE TITLE
Fails to auto-fill on hostelworld.com

### ISSUE THREAD

**Issue by jeremejevs** [bitwarden/browser#929]
Both login and credit card details. Not sure why, only 5 forms and 13 input elements on the page, and the fields have `username` and `password` as their names.

**Comment by kspearrin** [comment]
I just tested autofilling the sign in form and it seems to work just fine.

**Comment by jeremejevs** [comment]
Have no idea what was wrong yesterday, both work fine now, even with a clean state. Closing.
