### ISSUE TITLE
Support Brave Browser

### ISSUE THREAD

**Issue by Danerd** [bitwarden/browser#93]
Are there any plans to support the Brave Browser? :-)

**Comment by kspearrin** [comment]
We've already added support and submitted the pull requests to brave. We're just waiting for them to accept them.

https://github.com/brave/browser-laptop/pull/6918
https://github.com/brave/muon/pull/153

Feel free to contact the brave and encourage them to accept them :)

**Comment by Danerd** [comment]
Will do it! :-)
