### ISSUE TITLE
Bitwarden Extension is not compatible with last Firefox version

### ISSUE THREAD

**Issue by Sigri44** [bitwarden/browser#931]
Hello,

With Firefox 66.0.3 the bitwarden extension don't work.

![bt](https://user-images.githubusercontent.com/9304947/57178420-ef7eca80-6e6f-11e9-895b-a3a095d759a4.png)

Link : https://support.mozilla.org/1/firefox/66.0.3/WINNT/fr/unsigned-addons

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/928
