### ISSUE TITLE
Loading background-color is whitish on dark theme

### ISSUE THREAD

**Issue by glitsj16** [bitwarden/browser#933]
OS: Arch Linux
Main web browser: Firefox (66.0.3)
Webextension version: 1.39.3

Hi, I've set bitwarden to use the `dark` theme. Looks beautifull (as well as the light version for that matter). One smallish, yet irritating thing I've noticed is that the `loading` page is the only part that isn't actually 'dark', causing a white flash that looks out-of-place.

This isn't a bug in the sense of a coding error, more of a feature-request if one looks to classify it somehow. In any case, I'm preparing a PR to add light/dark theme support for `app-root > #loading` shortly, as that's where I believe a few changes are needed to 'fix' this. Just wanted to bring this to your attention here.

Regards

**Comment by kspearrin** [comment]
This occurs because the "loading" state is when the application is still bootstrapping. Because of this, we don't yet have proper access to 1) change HTML bindings via Angular and 2) fetch settings such as what theme is being used.

**Comment by glitsj16** [comment]
@kspearrin That makes sense, thanks for explaining. I guess the only way to handle this for users is in their userContent.css (where it does work).

**Comment by silverwind** [comment]
Maybe put the theme setting into a fast storage and then apply it before Angular initializes?

Another option could be a pure CSS solution via [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), thought that will not honour the custom setting.

**Comment by DarkArc** [comment]
It may be worth it to have a smaller, faster, script, that doesn't require the full app to be boostrapped. i.e.
```
<head>
  <script type="text/javascript">
    document.body.style.backgroundColor = localStorage.getItem("lastBackgroundColor") || DEFAULT_COLOR;
  </script>
  ...
</head>
```

**Comment by silverwind** [comment]
@DarkArc good idea. It may be as simple as putting something like that in [`popup/index.html`](https://github.com/bitwarden/browser/blob/master/src/popup/index.html).

**Comment by josias-r** [comment]
I found this old GIF illustrating this problem. https://imgur.com/AX7q2En
Still not fixed after one year? 🤔

**Comment by DarkArc** [comment]
I tried to fix it, it's a little bit awkward, and then other things came up. Probably best done by someone in house as somethings likely need some light-moderate refactoring to make it work cleanly.

**Comment by redudant-overflowing** [comment]
I'm having this issue in 1.54.0.

https://user-images.githubusercontent.com/93951203/140961996-649a9835-06a4-4bb1-b438-e5a6eb5dcbf2.mp4

**Comment by sinazadeh** [comment]
Bitwarden still has the same issue on the Zen browser. Are there any known workarounds or custom CSS solutions?

**Comment by DarkArc** [comment]
It's still an issue on Firefox as well (I just checked -- I think it hasn't bothered me quite as much because Bitwarden just loads its initial UI faster for me these day)... Good point bringing it back up (and sorry for not commenting when the bot marked this as stale).

@patrick-bitwarden could this be reopened?

**Comment by sinazadeh** [comment]
Someone [suggested a custom CSS fix](https://github.com/bitwarden/clients/issues/1813#issuecomment-888860193) that might help, but it doesn't seem to work with the latest version. I tried debugging it, but no luck so far.
