### ISSUE TITLE
Unable to view attachment- web version

### ISSUE THREAD

**Issue by timetoseek** [bitwarden/browser#937]
The web version does not allow viewing of attachments as part of the record (actually, clicking the paperclip in the web version has no effect, and even if you click the record, you are not able to view the attachment:
![file_not_visible_web_version](https://user-images.githubusercontent.com/26972658/57544128-4589bd00-730b-11e9-94c9-c5e69f3f7390.jpg)

**This function works well in the Brave/Chrome browser extension and in the desktop version:**
![file_visible_desktop_win10EE](https://user-images.githubusercontent.com/26972658/57544196-78cc4c00-730b-11e9-9eeb-3634ea0166f2.jpg)

**Comment by havramar** [comment]
Would love to see this being consistent with desktop/extension versions. From my perspective as a new (paying :)) user, it's easiest to start with the web version of Bitwarden's Vault where the attachment UI is pretty confusing.
