### ISSUE TITLE
Firefox has updated how extensions work in private mode, maybe they have fixed the issue stopping Bitwarden working in private mode.

### ISSUE THREAD

**Issue by rikminke** [bitwarden/browser#938]
Maybe someone could see? I am not a developer.

**Comment by kspearrin** [comment]
It would be helpful if you included a reference to what has changed in private mode.

**Comment by jpandersen87** [comment]
Mozilla article from march briefly going over changes in the now-released build: https://blog.mozilla.org/addons/2019/03/26/extensions-in-firefox-67/

**Comment by jpandersen87** [comment]
From what I can gather the status of the getBackgroundPage function in private windows is unchanged so the viability of the bitwarden firefox extension fully functioning in private windows in its current design is also unchanged,

**Comment by EnriqCG** [comment]
More info can be found here: https://support.mozilla.org/en-US/kb/extensions-private-browsing?as=u&utm_source=inproduct

**Comment by kspearrin** [comment]
> From what I can gather the status of the getBackgroundPage function in private windows is unchanged so the viability of the bitwarden firefox extension fully functioning in private windows in its current design is also unchanged,

This seems to be the case. Still not possible.

**Comment by daithi-coyle** [comment]
How does LastPass do it? Could Bitwarden not just read the page header or tab title or something and make it's best suggestion from there? (I'm completely taking a stab in the dark here I have no dev knowledge/experience).

**Comment by WesleyBranton** [comment]
Correct me if I'm wrong, but can't you just not use the getBackgroundPage API? You should be able to get the same or similar functionality using Firefox's Native Messaging API...
