### ISSUE TITLE
Firefox - password generator "Copy Password" adds leading and trailing spaces

### ISSUE THREAD

**Issue by jagerman** [bitwarden/browser#94]
I just installed the Firefox add-on (excited to start using this!), and signed up for a site.

I added a login for the site (generating the password in bitwarden), and hit "Copy password" on the password generator, then pasted the password into the site.

This resulted in an inability to log in to the site: my password had been created with leading and trailing spaces.

This is easy to reproduce: click on the plugin icon, go to Tools -> Password Generator -> Copy Password, then paste the password somewhere: it will have a leading and trailing space.

**Comment by jagerman** [comment]
(I don't use the other browsers so I can't confirm whether or not this is specific to the Firefox plugin).

**Comment by kspearrin** [comment]
Thanks, I am able to reproduce.

**Comment by kspearrin** [comment]
Fixed with https://github.com/bitwarden/browser/commit/a13da0005cde169b740bbba67bc5f55764fae37c

v1.9.9 and above.
