### ISSUE TITLE
Problem logging in after autofill

### ISSUE THREAD

**Issue by mindrunner** [bitwarden/browser#940]
I have a problem with a login site. It is a Huawei WiFi Router E5573s-508, branded by Claro Guatemala.

Autofilling my password leads to a "username or password wrong" error message. Copying the password to the clipboard and then pasting it lets me log in.

What can be the issue here?

Btw: On Android and Chrome, the problem is the same!

![2019-05-27-111142_1873x921_scrot](https://user-images.githubusercontent.com/1413542/58432621-9110ca80-8070-11e9-9b8d-8e41cbfbd8bd.png)
![2019-05-27-110807_1901x933_scrot](https://user-images.githubusercontent.com/1413542/58432622-9110ca80-8070-11e9-97a1-79e5ea6e4b3f.png)

**Comment by kspearrin** [comment]
Unfortunately, without access to the page, I am not sure how I could troubleshoot this. Maybe you could save the HTML page and zip it up for me to try?

**Comment by mindrunner** [comment]
Yeah, i was thinking of something like that. Atached is the downloaded html. if you need more information just let me know. also i could try debugging it by myself if you give me a poke into the right direction! ;)
[index.html.zip](https://github.com/bitwarden/browser/files/3225316/index.html.zip)

**Comment by kspearrin** [comment]
It appears to be filling the fields as I expect in this example. I am not sure why they wouldn't accept the credentials. Some websites have weird scripts to try to block automation. One thing I have seen on some websites is you need to manually focus into one of the fields. Try clicking the username and password fields with your mouse after autofilling. Then click log in. Does it work then?

**Comment by mindrunner** [comment]
Already tried that. :/ Super weird behaviour....

**Comment by kspearrin** [comment]
What if you remove one character from the end of the filled password and then manually type it back and click login?

**Comment by mindrunner** [comment]
Haha, I solved the miracle. 

The password field is limited to 15 chars. Its impossible to type in more. However, BitWarden seems to ignore that and fills in more characters than possible. Thus, not accepted.

Pasting from the clipboard truncates the password to the first 15 chars. Thus, gets accepted.
