### ISSUE TITLE
Logout confirmation widget is hard to read in Firefox sidebar

### ISSUE THREAD

**Issue by glitsj16** [bitwarden/browser#941]
When the Bitwarden extension is running in the Firefox sidebar, the `logout confirmation` widget is not fully on top. Or, put differently, the settings content bleeds thru the widget, which negatively affects readability. Looks like a `z-index` issue. Playing with some CSS via userContent.css, I can have it on top when opening moz-extension://f1ec689d-9c93-44b3-a28a-dc8673525e70/popup/index.html#/tabs/settings in a tab with the below CSS. But this does NOT work in the sidebar. Is this something that would be fixable in Bitwarden or is this a Firefox bug/feature?

```
$ cat userContent.css
@-moz-document url-prefix(moz-extension://f1ec689d-9c93-44b3-a28a-dc8673525e70) {
    div.box.list,
    div.box.list * {
        z-index: 1 !important;
    }
    html .swal-modal,
    html .swal-modal * {
        /*background-color: yellow !important;*/
        z-index: 999 !important;
    }
}

```
OS: Arch Linux
Firefox: 67.0
Bitwarden WE: 1.39.3

**Comment by kspearrin** [comment]
Can you provide a screenshot of the issue? `userContent.css` is not something part of the Bitwarden extension, so it sounds like a Firefox problem.

**Comment by glitsj16** [comment]
@kspearrin Turns out to be a Firefox issue indeed. Adapting the CSS in userContent.css to be similar with Bitwarden's scss fixed it. Sorry for the noise.
