### ISSUE TITLE
Not possible to log in to Firefox extension with U2F enabled

### ISSUE THREAD

**Issue by jurjenoskam** [bitwarden/browser#943]
I just installed a fresh copy of Win 10 1903 and Firefox 67, so I had to log in to the Bitwarden extension again. I have a Yubikey attached to my account as a second factor, in U2F mode. After entering my login credentials (email address and master password) in the extension, I very briefly see the extension "sliding in" the window where it asks me to push the button on my security key or to select another 2FA method. Unfortunately, almost immediately the extension window disappears and a Windows Security window pops up that instructs me to touch my security key:

![image](https://user-images.githubusercontent.com/39823959/58367179-6ee64380-7edc-11e9-85de-3abcf5edf9a6.png)

After pressing the button on the Yubikey, the Windows Security window disappears but the extension is not logged in. Clicking the extension icon results in the extension showing the window with the "Log In" and "Create Account" buttons.

Unfortunately, this means it is not possible to use the extension at all.

**Comment by emmett421** [comment]
I had the same exact problem. What I did to login was reinstall the extension so that it would open on the left side of the firefox window (that I couldn't figure out how to enable after closing it) and for some reason when Bitwarden is open in that side window, it works with u2f and windows. Hopefully this is fixed by the developers soon.

**Comment by jurjenoskam** [comment]
Thanks, when the extension is shown in the Firefox Sidebar it is possible to log in with my U2F token! While uninstalling and reinstalling the extension will indeed cause it to be shown in a sidebar after reinstall (which will enable you to log in), it is sufficient to let Firefox show the Sidebar and select the Bitwarden extension to be shown in it.

**Comment by belidzs** [comment]
The hotkey to pull up the sidebar with bitwarden is `Shift+Alt+Y`
