### ISSUE TITLE
"Failed to fetch" error w/ hostile certificate

### ISSUE THREAD

**Issue by marcinsmialek** [bitwarden/browser#944]
When I'm on a network which replaces some certificates, and I click "Log In" button in Bitwarden extension (Vivaldi / Chrome), it shows an error message:

> An error has occurred
> Failed to fetch

Expected behavior:

- An error message is displayed, with some explanation.
- I can access my offline vault.

Current behavior:

- Vague error message is displayed.
- I cannot access my passwords.

Also, just after clicking the Bitwarden icon on the toolbar, I'm presented with the initial "log in / create account" screen, rather than one with my email already filled, and master password field (available after clicking log in).

**Comment by Branlew** [comment]
I'm having this problem,  with every new account I register on Bitwarden. I am using Edge Developers edition. It has worked on this browser but no longer.
An error has occurred
Failed to fetch

**Comment by JonathanAJ** [comment]
I'm too. Issue that I created #1000.

**Comment by ShantanuNair** [comment]
I'm experiencing this issue currently as well.

**Comment by soakes** [comment]
I am also getting the same problem, I only noticed today but looks like started about 9 days ago as i've been using cached login copy.  This is using self-hosted version.
