### ISSUE TITLE
Login popup steals focus on Firefox - cannot use extension/right-click/autofill

### ISSUE THREAD

**Issue by mpenguin** [bitwarden/browser#946]
I'm using Rutorrent on Feral hosting as part of my seedbox. The login "pop-up" steals focus, making it impossible for me to switch tabs or select the Bitwarden icon. Auto-fill doesn't work, right-click menu does not give me the Bitwarden option, and the keyboard shortcut also does not work. This is only on Firefox; if I go to the same page on Brave browser, the login does not steal focus, and I can use any of the methods to input my username and password.

Why is this only an issue on Firefox? Is there something in the Gecko engine (as compared to Chromium) that makes the login steal focus? Is there any way to work around this issue?

**Comment by kspearrin** [comment]
Can you provide a screenshot of what this login box looks like?

**Comment by mpenguin** [comment]
Here's a screenshot with tabs/sensitive info blurred out. It's a pop-up that steals focus entirely - I cannot switch tabs, cannot use extension icons. I can use other programs outside of Firefox, but it steals focus within Firefox entirely.

![T36x0fF8J5](https://user-images.githubusercontent.com/6459925/59400830-58d8ee00-8dcb-11e9-8888-de5a5f52cd8d.png)

**Comment by kspearrin** [comment]
This is called a basic auth prompt. The only way to autofill these is to make sure there is exactly 1 match in the vault for the given URI. If that is the case, it will automatically provide the credentials for you and log you in. The prompt will not even be shown.

**Comment by mpenguin** [comment]
I don't like to have Autofill on, though. And it only steals focus on Firefox, not on Brave/Chromium browsers. Is this a limitation of the Gecko engine?

**Comment by kspearrin** [comment]
That's a question for Firefox devs.

**Comment by mpenguin** [comment]
I made an entry with the exact URL and set it to "EXACT" in the Bitwarden settings, but it still didn't autofill. I've tried a few different settings for the rutorrent entry, but it doesn't seem to autofill no matter what I do.

**Comment by kspearrin** [comment]
Are there other items that also match this URL? You need to make sure only 1 matches.

**Comment by mpenguin** [comment]
There are others that match the base url (geryon.feralhosting.com" but the URLS are not exact. For example, ZNC uses
https://geryon.feralhosting.com/<user>/znc/
Others use /deluge or /transmission/web or whatever. Will those interfere, even if I have them set to "exact" match detection?

**Comment by kspearrin** [comment]
Yes, only 1 item can match the given page, or the prompt will show.

**Comment by mpenguin** [comment]
OK. I had to delete every other Feral URI (even the main Feral login page) for it to work. Thanks for the help.
