### ISSUE TITLE
Microsoft Edge Chromium Autofill Shortcut

### ISSUE THREAD

**Issue by i-love-code** [bitwarden/browser#950]
In Microsoft's new Chromium-based Edge browser, the shortcut ctrl+shift+L is already a built-in shortcut and blocks the auto-fill functionality for the Bitwarden extension.

I would love to see this be resolved, clicking the extension is a PITA :)

**Comment by i-love-code** [comment]
It looks like on old Edge, the shortcut was Ctrl + /, unfortunately it doesn't look like the chromium-based version of Edge uses that shortcut.

**Comment by i-love-code** [comment]
Edit: Found the keyboard shortcuts tab of Edge.

![image](https://user-images.githubusercontent.com/1737733/59613112-eece8a80-90e3-11e9-81ce-0b47c048b3f9.png)

**Comment by i-love-code** [comment]
I was! It was actually blank to begin with, for some reason. Setting it to Ctrl+Shift+L actually allowed me to use that shortcut and prevented the built-in shortcut bound to that key.

**Comment by K3RGIO** [comment]
Hey, where in the heck did you find that settings page. I can't find it any it's driving me insane !

**Comment by i-love-code** [comment]
edge://extensions/shortcuts

or, "Menu > Extensions > (Left side tab) Keybindings"

**Comment by wkappes** [comment]
> Edit: Found the keyboard shortcuts tab of Edge.
> 
> ![image](https://user-images.githubusercontent.com/1737733/59613112-eece8a80-90e3-11e9-81ce-0b47c048b3f9.png)

Save my life! Thank you!

**Comment by douglasparker** [comment]
It seems that the `Ctrl + Shift + L` shortcut has to be manually added to the new Chromium-based Edge. I can't imagine this is the intended out of the box configuration... Can this issue be reopened so that it can be addressed?

**Comment by douglasparker** [comment]
@kspearrin This is still an issue in the new Chromium based Edge. It was actually hard to find the required settings page to fix this.

@i-love-code This issue should be reopened until a fix is rolled out that way less experienced users don't encounter this issue.

**Comment by KyleRAnderson** [comment]
One note however is that Ctrl + Shift + L is already a shortcut in Microsoft Edge chromium (see [this documentation](https://support.microsoft.com/en-gb/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad)). Is there a suggestion for a different key combination that can be used for Edge chromium?
