### ISSUE TITLE
KhanAcademy autofill does not work for username field

### ISSUE THREAD

**Issue by iorv3th** [bitwarden/browser#954]
Clicking on the FireFox extension button does not autofill username. I've also tried right-clicking the username field and using autofill. Neither options work. Screenshot attached.

![image](https://user-images.githubusercontent.com/11638681/59896439-72ff6700-939d-11e9-8ee2-0aba0bb4ef64.png)

**Comment by kspearrin** [comment]
This is because the username field is in a completely separate form on the page.

![image](https://user-images.githubusercontent.com/1190944/59921003-51809880-93fa-11e9-84a8-d3d481a7ee02.png)

No idea why they would do something like this.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
