### ISSUE TITLE
Configure the default generated password length

### ISSUE THREAD

**Issue by mvdan** [bitwarden/browser#955]
I realise the forum is preferred for feature requests, but following what upstream said in https://github.com/bitwarden/server/issues/132, I think it's a feature that should exist.

I'm also a bit lazy to create yet another forum account :) I wonder if Google/GitHub/OpenID logins would be possible.

I like generating longer passwords than the default of 14. Generating one works fine; I can just raise the length to whichever length I prefer.

However, this gets tedious, as I generate passwords somewhat regularly. Every time I have to play with the slider. From the comment in the issue linked above, it seems like the desktop app has an option to configure this default. Could the browser extension gain the same?

I've tried my best to search for this in the options, as well as this repo and the forums, but haven't found anything.

**Comment by kspearrin** [comment]
> I wonder if Google/GitHub/OpenID logins would be possible.

It is.

> However, this gets tedious, as I generate passwords somewhat regularly. Every time I have to play with the slider.

Your last settings should be remembered. The default is only set after the first installation.

> From the comment in the issue linked above, it seems like the desktop app has an option to configure this default. Could the browser extension gain the same?

The default is configured by just changing the slider.

**Comment by mvdan** [comment]
> It is.

Oh, my bad. I still can't see how, though; I can just sign up, or log in with a user+password.

> The default is configured by just changing the slider.

Hm, then clearly I'm doing something wrong, as I've moved the slider up maybe five times, but any time I open up my browser again (Firefox) it's back to 14.

Any way I can help you debug this?

**Comment by kspearrin** [comment]
Are you clearing your browsers data after close or something?

**Comment by mvdan** [comment]
I'm not; for example, the github login cookie stays there.

I can't reproduce right now, though. I just restarted the browser and the slider is where I left it. Maybe it's a reboot that did it, or something else. I'll reopen with more details if it happens again.
