### ISSUE TITLE
mail.com username field not properly recognised

### ISSUE THREAD

**Issue by bvdlingen** [bitwarden/browser#958]
Big Bitwarden fan and premium user here! 

I just discovered a minor inconvinience or bug:

When subscribing to https://www.mail.com I saved my username and password using the Bitwarden browser plugin for Chrome.

When logging in using the Bitwarden browser plugin for Chrome my password is filled in twice: both as username and as password.

See below for the relevant html code of mail.com login:

` <p>Log in and enjoy your email. It is our pleasure to provide you a mailbox customized to your needs.</p></div><div class="login-box">
  | <div class="headline">Login<span class="login-ssl"></span></div>
  | <a class="premium-login" href="https://www.mail.com/premiumlogin/#.1258-header-login1-1" target="_top">Premium Login</a><form action="https://login.mail.com/login#.1258-header-login1-2" method="post" id="login-form" class="mod mod-loginform">
  | <input type="hidden" name="service" value="mailint">
  | <input type="hidden" name="uasServiceID" value="mc_starter_mailcom">
  | <input type="hidden" name="successURL" value="https://$(clientName)-$(dataCenter).mail.com/login">
  | <input type="hidden" name="loginFailedURL" value="https://www.mail.com/int/logout/?ls=wd">
  | <input type="hidden" name="loginErrorURL" value="https://www.mail.com/int/logout/?ls=te">
  | <input type="hidden" name="edition" value="int">
  | <input type="hidden" name="lang" value="en">
  | <input type="hidden" name="usertype" value="standard">
  |  
  | <div class="login-input-wrapper">
  | <label for="login-email">Email</label>
  | <input id="login-email" name="username" class="login-input js-hide-label" type="text" placeholder="Email">
  | </div>
  | <div class="login-input-wrapper">
  | <label for="login-password">Password</label>
  | <input id="login-password" class="login-input js-hide-label" type="password" name="password" placeholder="Password">
  | </div>
  |`

**Comment by kspearrin** [comment]
I just tested this in Chrome and was not able to reproduce the problem. Username and password were filled properly.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
