### ISSUE TITLE
Can't login or register in Firefox extension under Linux

### ISSUE THREAD

**Issue by 13xforever** [bitwarden/browser#96]
When trying to focus on Password input (or any other input, i.e. on registration form), Bitwarden popup suddenly collapses. Doesn't happen under Windows.

Browser console is full of json and html errors ([accountsLogin.html](../blob/master/src/popup/app/accounts/views/accountsLogin.html#L19)):
![image](https://cloud.githubusercontent.com/assets/36445/23333261/7b4a1622-fbaa-11e6-84dd-d7aeee0b71cf.png)

(Not sure if it's the cause or just a red flag).

OS: Antergos + GNOME 3.22.3
Browser: Firefox Developer Edition (53.0a2 2017-02-25)

**Comment by 13xforever** [comment]
I just tried Plasma Desktop 5.9.2 and this behavior is not happening under it, so it's probably GNOME3-specific.

**Comment by kspearrin** [comment]
I'll have to install a Linux VM and test there. Linux has been untested with the addon.

Those console errors are normal and also happen on Windows, so I don't think they are related.

**Comment by kspearrin** [comment]
I just tested this with an Ubuntu VM with GNOME and was not able to reproduce any issues with the login or registration pages of the addon.

**Comment by 13xforever** [comment]
Maybe someone more experienced with Linux with the same problem will help, but I honestly don't even know how to start poking at this issue.

After I successfully logged in in Plasma, I have no other issues in GNOME so far.

**Comment by 3lpsy** [comment]
I had a similar issue on both Linux (Arch, Plasma) as well as Mac where I was unable to login (I received a "Unexpected Error Occurred" when attempting to login). After disabling my other extensions (Https Everywhere, ublock origin, NoScript, FoxyProxy, and Disconnect), I was able to login. I haven't had an opportunity to test it on Linux or narrow down which extension was causing me trouble, but it's worth a shot.

**Comment by keshto** [comment]
I have Gnombuntu and did not have this issue when registering/logining in with firefox extension.

**Comment by Danerd** [comment]
The solution of @3lpsy worked for me too.

**Comment by dralley** [comment]
FWIW I'm using Fedora 25 w/ GNOME 3 on three separate computers and have not encountered this issue on any of them, so I doubt GNOME is the cause.

**Comment by jonathonf** [comment]
Whitelist rule for uBlock:
```
@@||api.bitwarden.com/connect/token$xmlhttprequest,domain=8035511a-e050-4d09-9562-7effa672420d.moz-extension-scheme
```

Whitelist rule for uMatrix:
```
8035511a-e050-4d09-9562-7effa672420d.moz-extension-scheme api.bitwarden.com xhr allow
```

**Comment by 13xforever** [comment]
It is no longer reproducible on my side as well with Gnome 3.24.2 and Bitwarden extension 1.14.2
