### ISSUE TITLE
Uncaught ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by lots0logs** [bitwarden/browser#960]
Looks like this error occurs here:

https://github.com/bitwarden/browser/blob/f35bc516c0a096650dab8adf738b06ac28dc4f63/src/background/idle.background.ts#L18

The fix is simple. I'll submit a PR shortly.

**Comment by kspearrin** [comment]
What browser throws this error?

**Comment by lots0logs** [comment]
Its inside an electron app. I referenced this issue over there (look directly above your comment for the link)
