### ISSUE TITLE
Adding an item to the vault uses the same password each time

### ISSUE THREAD

**Issue by niniack** [bitwarden/browser#965]
When adding an item (login or card) the password/code generated is always the same. This could be a vulnerability if an individual were to blindly accept the initially suggested password as all of their passwords would be the same string. I would suggest not having a pre-generated password, so the user must go through the action of generating a password and at least giving it a quick glance before saving it.

![location](https://user-images.githubusercontent.com/41016622/60763767-59227d00-a049-11e9-99c5-3509717f60e2.png)

Browser: Firefox
Bitwarden version: 1.39.3

**Comment by kspearrin** [comment]
We do not pre-generate passwords on add. This sounds like something that your browser it doing. Try turning off the native password manager's autofill in your browser.

**Comment by niniack** [comment]
Okay, I have done so. It doesn't seem to change the behavior. I was inclined to believe it was on Bitwarden's end because it also autofills the name, username, and uri fields. Is this expected behavior? Thanks

**Comment by kspearrin** [comment]
Your screenshot does not show any other fields autofilled. This would not be expected behavior.

**Comment by niniack** [comment]
My bad, I removed it to hide personal info and didn't think ahead to generate dummy info. Sounds like my browser is trying to be smart, thanks for helping out
