### ISSUE TITLE
Exporting via Vivaldi (Chromium) Extension Fails (Initially)

### ISSUE THREAD

**Issue by ment4list** [bitwarden/browser#966]
When opening the extension in Vivaldi (Chrome Extension) and going to **Settings > Export Vault** and submitting with either JSON or CSV file types, nothing happens and no files are created in the Downloads folder.

You have to first open up the extension in a new window by clicking the "Pop out" icon on the top left. After opening in a new window the export works as expected and the browser prompts to store the file.

![Pop Out in New Window](https://user-images.githubusercontent.com/1780782/60890101-e983dc00-a25a-11e9-893d-ff470ae365e8.png)

**Comment by kspearrin** [comment]
This appears to be a bug in Vivaldi itself.

**Comment by JulianGro** [comment]
Still an issue. I just reported the bug to Vivaldi, but from my experience with them they will probably not fix it.
