### ISSUE TITLE
Bitwarden prowser plugin doesn´t check certificate expiration

### ISSUE THREAD

**Issue by xydian** [bitwarden/browser#967]
Hi,

today i accessed the web interface of my bitwarden instance and realised my certificates were expired some time ago. I mainly use the browser plugin and i didn´t get any notification by the plugin that the certificates are not valid anymore. Is this expected behavior or a bug?

**Comment by kspearrin** [comment]
We don't do any certificate validation for you. Your browser should be responsible for this.
