### ISSUE TITLE
Firefox U2F won't login.

### ISSUE THREAD

**Issue by optomux** [bitwarden/browser#969]
When trying to login with Firefox I am presented with this message.
security.webauth.u2f is set to true.

> This browser cannot process U2F requests in this popup window. Do you want to open this popup in a new window so that you can log in using U2F?

**Comment by kspearrin** [comment]
This is correct. This message has nothing to do with security.webauth.u2f. The latest Firefox on windows 1903 cannot process u2f prompts in the pop up. Click yes.

**Comment by optomux** [comment]
Well I don't use 1903 rather 1809.

**Comment by kspearrin** [comment]
This is a workaround fix we put in place for:

https://bugzilla.mozilla.org/show_bug.cgi?id=1562620

**Comment by kspearrin** [comment]
I can’t detect what version of Windows you use, so the fix goes to everyone on Windows with Firefox.  You’ll eventually be on 1903 and affected by the same bug.

**Comment by optomux** [comment]
Yeah no go on Firefox Nightly. Same story.
