### ISSUE TITLE
Avoid ambiguous characters option doesn't behave as expected

### ISSUE THREAD

**Issue by yureiita** [bitwarden/browser#97]
Mac OS X 10.11.6, Firefox 50.0.1, Bitwarden 1.9.8

The avoid ambiguous characters option doesn't behave as expected. Some characters seems to never appear at all in the generated password (assuming ambiguous characters are 0,1,I,L,O).

Steps to reproduce:

1. Open the password generator in the addon
2. Change the length to 24 to maximise the number of characters visible
3. Check the 0-9 option only and leave the other options unchecked
4. Click regenerate password
5. Check which number have appeared and write them down
6. Repeat step 4-5 until all numbers from 0-9 have been written
7. Now check the avoid ambiguous characters option
8. Repeat steps 4-6

Below are the results that i have found including for other sets of characters. I only check for each set of characters, I didn't check for a different combination of sets of characters.

0-9 checked only:
* avoid ambiguous unchecked: no number 0, 1 and 9
* avoid ambiguous checked: no number 1

A-Z checked only:
* avoid ambiguous unchecked: no letter O and Z
* avoid ambiguous checked: no letter O

a-z checked only:
* avoid ambiguous unchecked: no letter l and z
* avoid ambiguous checked: no letter l

special char checked only:
* avoid ambiguous unchecked: no * sign
* avoid ambiguous checked: no * sign

When avoid ambiguous characters is unchecked, all characters should be included in the pool of password generator. But from the results above, some characters are not included.

**Comment by kspearrin** [comment]
Yea I am seeing some of the weirdness there as well. Doesn't look it it is working correctly.
