### ISSUE TITLE
Lock now behavior.

### ISSUE THREAD

**Issue by ci70** [bitwarden/browser#970]
Clicking on `Lock now` in the `Chrome` extension does not immediately close the window instead it just floats there..

**Comment by kspearrin** [comment]
It is not meant to close the window, only lock the application. Does the application lock?

**Comment by optomux** [comment]
How am I supposed to know it's locked? It should be similar to `log out`.
I don't use the application on Windows. Sorry.

**Comment by kspearrin** [comment]
It should take you to the lock screen.

**Comment by optomux** [comment]
Well it doesn't. I keep clicking on the lock now button but nothing happens.
I'll record a video.

**Comment by kspearrin** [comment]
Is there an error in the console?

**Comment by optomux** [comment]
Here it is.
![Demo](https://user-images.githubusercontent.com/10778276/60970739-e48a5f80-a322-11e9-8e81-92a2898d80fc.gif)

**Comment by kspearrin** [comment]
Can you check for errors in the console for the background page?

Go to chrome://extensions, enable developer code, and then inspect the background.html page for Bitwarden.

**Comment by optomux** [comment]
Here you go.

extensions::setIcon:20 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Image.img.onload (extensions::setIcon:20:36)
