### ISSUE TITLE
Password entered in non-password field

### ISSUE THREAD

**Issue by IBBoard** [bitwarden/browser#974]
I just tried to log in at https://www.cclonline.com/customer/login/ and found that BitWarden correctly enters my details but it ALSO puts the password in a field of type "text".

My best guess is that this happens because the text box is a "forgot your password" box within the same form and is called `ctl00_txtForgotPassword`. However, it seems dangerous to put passwords in input boxes of `type="text"`.

**Steps to recreate:**
 * Add credentials for https://www.cclonline.com/customer/login/
 * Right-click > Bitwarden > Auto-fill > Your Credentials

**Expected behaviour:** "Username or email" and "Password" boxes are filled in.

**Actual behaviour:** Both boxes are filled in *and* the password is filled in within the "Email address" field in the "Forgotten your password" section.

**System:** Firefox 67.0.4 on openSUSE Linux and Bitwarden extension 1.40.0

**Minimal test case:**

```
<html>
<head><title>BitWarden bug test</title></head>
<body>
<form method="GET" action="/">
<div>
    <label for="ctl00_txtUsername" id="ctl00_lblUsername">Username or Email</label>
    <input name="ctl00$txtUsername" type="text" id="ctl00_txtUsername">
</div>
<div>
    <label for="ctl00_txtPassword" id="ctl00_lblPassword">Password</label> 
    <input name="ctl00$txtPassword" type="password" id="ctl00_txtPassword" class="txtBox ">
</div>
<div>
    <label for="ctl00_txtForgotPassword" id="ctl00_lblForgotPassword">Forgot password?</label>
    <input name="ctl00$txtForgotPassword" type="text" id="ctl00_txtForgotPassword" class="txtBox ">
    <p>This is not really a password field and should not be filled in!</p>
</div>
</form>
</body>
</html>
```

**Comment by kspearrin** [comment]
Having trouble reproducing the problem on the site. Is this the login form you are referring to?

![image](https://user-images.githubusercontent.com/1190944/61182997-776c1800-a609-11e9-9aa9-d35f00f80d36.png)

**Comment by IBBoard** [comment]
Yes, it's that page. My password ends up in the "Forgotten your password?" box as well.

It also happens with the minimal test case (now available at https://ibboard.co.uk/temp/bitwarden.html)

**Comment by kspearrin** [comment]
Thanks. I can reproduce.
