### ISSUE TITLE
Password autofill not working

### ISSUE THREAD

**Issue by allandavid** [bitwarden/browser#975]
Password autofill is not working in this website https://internet-banking.retail.dbsbank.in/login
I am not able to manually paste the password either.

**Comment by allandavid** [comment]
> Password autofill is not working in this website https://internet-banking.retail.dbsbank.in/login
> I am not able to manually paste the password either.

BTW...I am using Firefox

**Comment by kspearrin** [comment]
If you can’t even paste the password then it sounds like the website is preventing automated measure of providing the password. Bank websites are known for doing this because they want you to physically type the password for whatever reason.

**Comment by allandavid** [comment]
Thanks for the quick reply. I used to use Lastpass and it didn't have any issues with autofill on this website.

**Comment by allandavid** [comment]
> Thanks for the quick reply. I used to use Lastpass and it didn't have any issues with autofill on this website.

Here's a screenshot of Lastpass autofilling the fields
![Screen Shot 2019-07-14 at 11 32 44 PM](https://user-images.githubusercontent.com/1513017/61187529-0b80c280-a690-11e9-90a1-b01ea629ac56.png)

**Comment by kspearrin** [comment]
I am not sure what could be done. For example, try running the following code on the website:

```
document.getElementById("password").value = "mypassword"
```

It sets the value, and then when you focus the page, the website removes it. I don't really know what they are doing behind the scenes to prevent programmatic assignment of the password value, but it is definitely non-standard.

**Comment by allandavid** [comment]
I noticed that they are using assets.adobedtm.com. Could this be causing the issue?

**Comment by elfez** [comment]
Go into about:config, search for `dom.event.clipboardevents.enabled` and toggle it to **false**. That resolves the issue for me.
