### ISSUE TITLE
autocomplete="off" gets ignored fills passwords but shouldn't

### ISSUE THREAD

**Issue by jonathanmmm** [bitwarden/browser#979]
Hi,

First of all I want to say thanks for your help and contribution for a safer and easier web experience :)

I found this issue while embedding through iframe an existing website in another website (external pages in nextcloud).

I have autofill enabled for nextcloud and if I now open a website through i frame but I have something like:

<form class="form-signin" method="post" autocomplete="off">

or 

 <input type="password" autocomplete="off" class="input-block-level" placeholder="Enter password" name="password">

it fills automatically one of my nextcloud passwords.

I am testing this in the chrome browser extension (in brave).
Version: 1.39.3

It should recognize the autocomplete="off" (like the new-password) and the far greater problem is iframe.

Is this a security risk, because if I embedded another website and it just autofills the password the website could steel the password. I believe there are many companies you let access to certain websites outside of the companies intranet through iframe or something similar through javascript or something.

Is there something I can change in the html/php code of the website?

**Comment by kspearrin** [comment]
`autocomplete="off"` gets ignored on password field by every password manager, including the built-in ones for the browser.

The iframe problem was highlighted and addressed in our recent security audit. See more here: https://cdn.bitwarden.net/misc/Bitwarden%20Security%20Assessment%20Report.pdf BWN-01-001

**Comment by jonathanmmm** [comment]
Ok, so does this mean I have autocomplete="off" wrongly implemented in the website and the bitwarden plugin does not autofill such password fields (I have the experimental autofill enabled in the browser plugin).

**Comment by jonathanmmm** [comment]
> `autocomplete="off"` gets ignored on password field by every password manager, including the built-in ones for the browser.
> 
> The iframe problem was highlighted and addressed in our recent security audit. See more here: https://cdn.bitwarden.net/misc/Bitwarden%20Security%20Assessment%20Report.pdf BWN-01-001

I am also iframing bitwarden (selfhosted) in my nextcloud instance:
`<input appinputverbatim="" class="text-monospace form-control ng-touched ng-dirty ng-valid " id="masterPassword" name="MasterPassword" required="" autocomplete="off" autocapitalize="none" autocorrect="none" spellcheck="false" inputmode="verbatim" type="password" data-com.bitwarden.browser.user-edited="yes">`

so you can see it shows autocomplete="off" but bitwarden plugin automatically fills the bitwarden login fields with my nextcloud credentials.

**Comment by kspearrin** [comment]
Sorry, I think I worded that poorly. I meant the `autocomplete="off"` attribute gets ignored on password fields, meaning it provides no value to stop password managers and other autofill functions in the browser from actually autofilling passwords into it.

**Comment by jonathanmmm** [comment]
> Sorry, I think I worded that poorly. I meant the `autocomplete="off"` attribute gets ignored on password fields, meaning it provides no value to stop password managers and other autofill functions in the browser from actually autofilling passwords into it.


Ok, thanks for the fast replay. So is there any other way to do this, am I on the wrong track to archieve this?
I thought autocomplete="off" does exactly this, stopping autocompletion. Or does it only stop asking the user if it should save the password?
Hope you can help this word confusion (autocomplete="off" sounds confusing if it does not do what says^^).

**Comment by kspearrin** [comment]
See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

**Comment by silverwind** [comment]
It's a hard problem to solve. Initially browsers honored autocomplete="off" but there were a few bad sites that used to set it on their login forms to "enhance" security so browsers and password-managers decided to ignore the attribute.

I think the best solution would be if Bitwarden would allow to right-click a input element and let the user blacklist that specific form auto-filling.

**Comment by neoKushan** [comment]
> 
> 
> > Sorry, I think I worded that poorly. I meant the `autocomplete="off"` attribute gets ignored on password fields, meaning it provides no value to stop password managers and other autofill functions in the browser from actually autofilling passwords into it.
> 
> Ok, thanks for the fast replay. So is there any other way to do this, am I on the wrong track to archieve this?
> I thought autocomplete="off" does exactly this, stopping autocompletion. Or does it only stop asking the user if it should save the password?
> Hope you can help this word confusion (autocomplete="off" sounds confusing if it does not do what says^^).

The best way to look at it is that autocomplete and password managers are two separate systems of the browser. Autocomplete is a convenience feature for remembering things you regularly fill out on forms across multiple sites - Names, addresses, that kind of thing. 
For password management, you _wouldn't_ want that, you wouldn't want a password you typed into site A to be "remembered" by the browser and suggested for site B (Not that you could even tell, since the password field is obfuscated). For passwords, you want your password management system to auto**fill** the password specific to that site.

Autocomplete != Autofill.

**Comment by jonathanmmm** [comment]
@silverwind thanks that explains that it does it not work :)

**Comment by silverwind** [comment]
I do realize there should be some way for a website to opt-out of erronous autofills. I recently had Bitwarden wrongly fill a list of `<input>`'s like this:

````
<input placeholder="auth_hostname"/>
<input placeholder="auth_password"/>
<input placeholder="auth_username"/>
````

Basically, it was autofilling on first and second input and the only workaround I found was hack that changed the placeholder attribute to not include the string `password`.

MDN mentions `autocomplete="new-password"` as one way to opt-out of autofilling. While it's probably not the right solution, some documented (and ideally standardized) way to opt-out would help in cases like this.

**Comment by subsite** [comment]
I work as a developer on a web shop. There are multiple admins who can add and edit the user accounts, including changing the user's email and password. 

So, if an admin uses bitwarden and opens a user for editing, bitwarden will replace the user's  password with the admin's own (from bitwarden). If the admin then submits the form, this user will no longer be able to log in to the site.

I get that I can disable auto fill for a particular site, but I can't do that for everyone who might have admin access on this site. Please provide a way to disable auto fill in the input field!

Maybe something like the LastPass specific `data-lpignore="true"` attribute (which I hear might no longer work, but that's another story). Or the aforementioned `autocomplete="new-password"`.

**Comment by jonathanmmm** [comment]
I have the same problem. E.g. website is nextcloud.com and I am logged in as admin. I had to specify the url as https://nextcloud.com/login and as "begins with" (hope this is the right english translation). But if I need to authorize a specific task and have to reenter the admin passwort I have to search it. Because the website doesn't start anymore with .../login.

This is a way to stop making non wanted autocompletion. But something like switching it off through  a header in an input field or to switch autocomplete for a specific url would be great.

That way I could use Autocomplete for URL1 "https://nextcloud.com/login" "begins with"
And NO autocompletion for URL2 "https://nextcloud.com" "standard".

**Comment by zoffixznet** [comment]
I'm facing the same issue as some of the commenters above. I'm an admin on a site and some fields get filled with my passwords, just because a placeholder on the field matches word "password".

I *can* modify the site, but failing to find any workable solution to block BitWarden from autofilling that page. I wish there was a blocklist for URLs or some attribute that was respected.

The only solution that came close is to configure the logins for the site to have extact match, but I have dozens of logins and need them working on multiple subdomains and pages, _except_ for that page.
