### ISSUE TITLE
Auto-fill for offline sites (extensions)

### ISSUE THREAD

**Issue by lasscap** [bitwarden/browser#981]
I am using a Firefox extension for mega.nz, thus the website is not downloaded but uses the code from the extension for improved security. Unfortunately, the auto-fill function does not work with the `moz-extension://` prefix.

If I set the match detection to "Host" then the login is indicated to me in the Bitwarden extention but I cannot auto-fill it into the website.

**Comment by kspearrin** [comment]
What is the URL of the extension? I imagine it is not `moz-extension://mega.nz`

**Comment by lasscap** [comment]
It is `moz-extension://[a long number unique to the user]/mega/secure.html`

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
