### ISSUE TITLE
auto-fill for basic authentication doesn't work

### ISSUE THREAD

**Issue by amirtal** [bitwarden/browser#985]
Credentials for a web page with basic auth exists in Bitwarden (only single login)
Open a web page with basic auth enabled.

Bitwarden should send the credentials to the web page automatically.
in fact, nothing happens.
Enter credentials popup from browser is displayed.

Google Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
Firefox: 60.8.0esr (64-bit)
Bitwarden: 1.40.1

i see several issues opened on this subject, all of them suggest the same thing:
this option should be present on the extension.
however, i do not see it working as expected, either on firefox or on chrome.
on linux (ubuntu 18.10) or on windows 10.

i created a test with only one user saved, for example on https://jigsaw.w3.org/HTTP/Basic/ , but browser login popup opens and remains blank.
no change until i manually enter the credentials and continue.

Amir.

**Comment by kspearrin** [comment]
Is your vault unlocked at the time of visiting the website? Seems to work for me.

**Comment by amirtal** [comment]
sorry, it was another issue unrelated to BW...
i was going to delete this.

didn't expect such a fast reply :) 
thanks for the hard work on this project!

Amir.
