### ISSUE TITLE
Login failure: "The operation failed for an operation-specific reason"

### ISSUE THREAD

**Issue by peter-jansson** [bitwarden/browser#986]
Using Firefox 60.7.2esr (64-bit) on Redhat and the Bitwarden browser extension version 1.41.0, login fails with the rather cryptic error message...

> An error has occurred
> The operation failed for an operation-specific reason

... popping up in a red box. This same error occurs when I use the same browser to try to login at the web-vault. Using the CLI on the same computer works fine.

**Comment by kspearrin** [comment]
Sounds like a failure somewhere in the browser's crypto APIs. I am not sure why this is specific to a RedHat installation, though, since this doesn't seem to occur on other OS.
