### ISSUE TITLE
[Firefox Extension] dropdown menu display hidden when pinch to zoom is enabled

### ISSUE THREAD

**Issue by mkatychev** [bitwarden/browser#988]
### Description of the bug:
When `apz.allow_zooming` is `true` in `about:config`, the html body fails to display for the Firefox Bitwarden Add-on.

<img width="374" alt="addon_missing" src="https://user-images.githubusercontent.com/11223234/62527510-cd0f9b00-b82a-11e9-8cb1-c146d7ba8e03.png">

### Versions of Firefox tested:
* Firefox Developer Edition 69.0b10 (64-bit)
* Firefox Stable 68.0.1 (64-bit)
### Workarounds:
* setting `apz.allow_zooming` back to `false` restores previous functionality
* When pinned to overflow menu, the exrension's DOM elements render  as expected
* The right-click Bitwarden menu still works as expected

**Comment by kspearrin** [comment]
This sounds like a Firefox bug. Can you try reporting it at https://bugzilla.mozilla.org/home ?
