### ISSUE TITLE
Chrome GPOs: force installing Bitwarden AND specifying default server

### ISSUE THREAD

**Issue by abctaylor** [bitwarden/browser#989]
It's possible to use ADMX files to configure a list of extensions for Chrome to install via Group Policy. However, it is not possible to specify extension-specific settings via GPOs, such as the default server in the Bitwarden extension.

I want all Chrome browsers to have Bitwarden [OK, done successfully] and also have the default server specified in the extension [how?]

1. Is there a registry key?
2. Is it somewhere in `C:\Users\%username%\AppData\Local\Google\Chrome\User Data\Default\Extensions\nngceckbapebfimnlniiiahkandclblb`?

![image](https://user-images.githubusercontent.com/30197206/62832977-1a2aad00-bc2f-11e9-94ea-f7a838306132.png)

**Comment by kspearrin** [comment]
These settings are stored using chrome's `chrome.storage` APIs. I am not sure if there is a way to pre-stored values for an extension.

**Comment by abctaylor** [comment]
That might be a tough one... closing for now. I'll re-open this if I find a solution. I am feeling that this will need to be done with some form of new user profile creation startup/first login script.

**Comment by kspearrin** [comment]
Yes, please do let us know if you find a solution. We have had others ask about this in the past, but I am not familiar with provisioning apps with group policies like this, so I don't have an answer.

**Comment by Dennis14e** [comment]
@abctaylor Did you find a solution?

**Comment by dwestness** [comment]
I have also been looking for a way to distribute our self hosted URL to the bitwarden extension by default. I can automatically deploy the extension to all systems via Google Admin policy, but no ability to pre-configure it with the self-hosted URL unfortunately. I do see this option does exist in Google Admin policy for the Bitwarden Android app to pre-configure this setting however, just which is could be done on the Chrome Extension as well.

**Comment by hexicans** [comment]
Hello,

Need to get a solution too

Thanks

**Comment by henrili** [comment]
I am also interested in this, and it should be possible, based on the documentation linked below. It requires that configurable settings be declared in a manifest, and then the extension can read settings from the storage.managed API. It's up to the extension dev. how/if managed settings should be enforced.

https://developer.chrome.com/docs/extensions/mv2/manifest/storage/

**Comment by LandauerW** [comment]
I am also interested in this. It is a pain users getting there to change the URL

**Comment by p3lim** [comment]
If this extension supported [chrome.storage.managed](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) as fallback to `chrome.storage.local`, this could be achieved.

Example policy.json [for Firefox](https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/):
```json
{
	"policies": {
		"3rdparty": {
			"Extensions": {
				"{446900e4-71c2-419f-a6a7-df9c091e268b}": {
					"environmentUrls": {
						"base": "bitwarden.internal.corp"
					}
				}
			}
		}
	}
}
```
I'm unsure how this would be set on Chrome since I don't use nor manage it, but I'd assume there's an equivalent policy there.

**Comment by yutotakano** [comment]
I'd like to request this to be reopened, given that a possible solution/feature-request has been posted above. Using the `storage.managed` API (available in Firefox, Chrome, Edge), it should be possible to implement the following:

1. Declare some fields, like server base URL as managed options (see docs)
2. When doing any chrome storage `.get()` operations for those fields, check if there's a managed value for it, in which case use that and ignore any local values.
3. Disable the form fields for changing the managed options on the extension UI.

How does this sound?

**Comment by abctaylor** [comment]
Another idea just sprang to mind.

What about looking up a SRV record to obtain this? The addin could look for _bwautodiscover (unqualified) and the local DNS resolver for the network would return the record for _bwautodiscover.ad.example.com with server values. This could then be put into chrome.storage. This way could be quite efficient and easy to manage centrally.

Andrew

**Comment by alexschomb** [comment]
FWIW, I like the SRV suggestion. It is clean and more universally to adopt (Windows/Mac/Linux/iOS/Android desktop, cli and browser) than a MS group policy or registry setting. 
Possible downsides: not always applicable (e.g. laptops and smartphones/tablets outside the DNS zone/AD) and might lead to bad practices (announcing the location/port of the BW server on public DNS). Still, I think that such problems can be overcome and/or rely in the responsibility of the administrators, who benefit from the automatic configuration.
