### ISSUE TITLE
Autofill on atlassian.com not working correctly

### ISSUE THREAD

**Issue by maxgrass** [bitwarden/browser#992]
Browser: Chrome on Windows

https://id.atlassian.com/login

![image](https://user-images.githubusercontent.com/169885/63229271-0f5bb380-c1ff-11e9-962b-55cadb0596c4.png)

It's the same mechanism as microsoft login etc. Where you first put your username, then click next for the next dialog/step with a password field.

Bitwarden fills both username and password per se (I see them appearing in the text-fields) but the request gets malformed this way.

Obviously tried in Chrome's Private mode without extensions.

**Comment by kspearrin** [comment]
I just tested this with my atlassian account on both Firefox and Chrome on Windows 10 and it worked just fine.

**Comment by maxgrass** [comment]
Verified working on Mac as expected as well. I'll close this for now and post more specifics later on.
