### ISSUE TITLE
Save new entry does not come up on economist.com

### ISSUE THREAD

**Issue by scheinercc** [bitwarden/browser#993]
macOS 10.14
Firefox Nightly 70;

1. Go to https://www.economist.com
2. Create a new account

At this stage I would Bitwarden already expect to ask to save a new entry when I hit the form's save button.

In order to try to save automatically, I logged out and back in again (with the pw still in my clipboard), but even submitting the login form on the login page didn't trigger the "save new entry" bar.

**Comment by kspearrin** [comment]
Looks like the login form is failing because the submit button isn't part of the actual `<form>` element.

**Comment by scheinercc** [comment]
Fair point Kyle. I can raise it with them. You reckon there is anything you can tweak on the algorithm for the plugin to still pick up the submit in such a case? Otherwise feel free to close.

**Comment by kspearrin** [comment]
It's a common issue. We have some ways to try to make guesses about what the submit button for a form is, but it appears to be failing here. More research/debugging is needed to see if a better solution or fix could be had.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.
