### ISSUE TITLE
Context menu allows user to click "Generate Password" when vault is locked

### ISSUE THREAD

**Issue by samteezy** [bitwarden/browser#995]
Currently using this in both official stable Chrome as well as Brave (Chromium-based), extension version 1.41.0.

One thing I've observed is that even when the vault is locked, I can right click and select "Generate Password (copied)" without any prompt from the extension that it's actually _not_ generating a password. This means that whatever was last in my clipboard usually ends up getting pasted into the password field.

I think safe options would be to prompt the user or remove that context menu option if the vault's locked. Worst case scenario, clearing out the clipboard so that the user can't paste anything incorrectly might work too.

**Comment by stilettk** [comment]
Yes, this is definitely frustrating: I have just reset my password to a simple word which was in my clipboard.
And I really want this to be available wheAn my vault is locked, because this don't affect my existing vault data.

**Comment by djsmith85** [comment]
This was fixed a while ago with commit https://github.com/bitwarden/browser/commit/277480e7ff09cb57adfa7af5f643645f38fd1dd7

Closing this now.
