### ISSUE TITLE
Using PIN code to live lock/unlock is insecure

### ISSUE THREAD

**Issue by up4k** [bitwarden/browser#997]
First of all, I want to make it clear: unlocking the vault using a PIN code is not insecure in itself. The concrete implementation of this is unsafe (if the user uses the option "Lock with master password on browser restart").
https://community.bitwarden.com/t/unlock-vault-with-PIN/31/38
> the master key is held in memory until you perform an application/browser restart

That is, locking is not performed at all. The master key is stored in memory and can be easily retrieved from there. Steps to reproduce (using Chrome browser):
1. Set "Unlock with PIN" and enable option "Lock with master password on browser restart" (default).
2. Restart browser.
3. Unlock the vault using your master key.
4. "Lock" the vault through the extension button or wait for it locking after timeout if you set that (doesn't matter).
5. Goto _chrome://extensions/?id=nngceckbapebfimnlniiiahkandclblb_ and open Debug of background.html from there (you need to activate Developer mode to perform this).
6. In console, you can call any JS object like **bitwardenMain.cryptoService.encKey**, seeing your every secrets.

There is no secrets in memory in case of timeout/manual lock if you always unlock the vault using master password or using PIN on browser restart (cause PIN is used to decrypt entire vault in that case and not only to hide UI).
Whether there is  physical access to the device by an attacker or malicious software, the PIN code will not protect against the leak of protected data. It’s just blowing dust into user's eyes - only the UI is locked.
I propose implementing a PIN code lock as follows:
1. When loading the browser, the vault is encrypted with a master password.
2. The PIN code is stored in the vault in encrypted form with salt and becomes available when decrypting the vault.
3. After the vault has been decrypted with a master password, the master key is encrypted with a PIN code (without salt) and stored in memory (not on disk).
4. If the vault is locked while the browser is running, all secrets should be deleted from the memory, except for the master key encrypted with a PIN code.
5. Even if an attacker will get access to master key encrypted with a PIN code from memory, he still needs to bruteforce a PIN code to decrypt the master key that decrypts the vault.
6. A user who knows the PIN code can still easily unlock the vault.

Obviously, this algorithm is safer than just locking the UI with a PIN code. In some threat models, this is safer than locking the vault with a PIN on the disk: accessing the offline vault can be more trivial for the attacker than the browser’s memory, so it must be encrypted with a complex master password, and it’s enough to encrypt a master key with a PIN code during the session to improve UX (but do not leave the master key in memory in decrypted form in case of locked state).
A separate question may arise about salt. The fact is that I did not understand how PBKDF works. In the situation if encode(PIN, mak) == encode(mak, PIN) we get the same values ​​in memory and on disk, which completely makes no sense to save encrypted MAK in memory and it allows an attacker with offline access to get the same thing as if the entire storage were encrypted with a PIN code. Reliable salt can get rid of this. If, however, my fears were groundless and PBKDF is not reversible it is possible to do without salt.

**Comment by kspearrin** [comment]
Should be resolved with:

https://github.com/bitwarden/jslib/commit/b74ee7b3ee823a820854623cc32c8522a09e9f4d
https://github.com/bitwarden/browser/commit/eb0bc6a01c9ad36303326d07cc0838da3af7eb60

Let me know what you think.
