### ISSUE TITLE
An unhandled server error has occured

### ISSUE THREAD

**Issue by MonsieurPoutounours** [bitwarden/browser#999]
Hi,

Since last update of my self-hosted (Synology / docker) vault, i can't login anymore. 

The error displayed is : 

An unhandled server error has occured.

The only error i can find is in the api logs :

fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
Settings must be of the form "name=value".

Version 2.11.0, vault was working for several months, i updated via ./bitwarden.sh updateself; ./bitwarden.sh update

**Comment by kspearrin** [comment]
See https://github.com/bitwarden/server/issues/555
